#!/usr/bin/env python3
"""Regenerate english_quadgrams.txt and english_words.txt, the English statistics
the monoalphabetic substitution cracker scores candidate keys with.

Both come from ten public-domain Project Gutenberg novels. Each book's licence
header and footer (everything outside the "*** START OF" and "*** END OF"
lines) is dropped.

* english_quadgrams.txt: the rest of the book is reduced to its ASCII letters
  A-Z (upper-cased, everything else removed, so quadgrams run across word
  breaks) and every run of four letters is counted. Quadgrams seen only once
  are left out: they are 0.2% of the total and would add 13,000 lines.
* english_words.txt: the words of three or more letters seen at least five
  times, plus a short list of common one- and two-letter words. The books
  also have plenty of two-letter fragments of contractions and foreign words
  ("ll", "re", "de"), which would let gibberish split into "words".

Only the Python standard library is used. Downloaded books are kept in
target/ciphey-gutenberg at the top of the repository (Cargo's build directory,
which git ignores), so a second run doesn't download them again. The two files
are written next to this script.

    python3 src/storage/ngrams/gen_quadgrams.py
"""

import argparse
import collections
import os
import re
import sys
import time
import urllib.request

# Alice in Wonderland, Tom Sawyer, Frankenstein, Emma, Dracula, Jane Eyre,
# Pride and Prejudice, Great Expectations, Sherlock Holmes, Moby Dick
BOOK_IDS = [11, 74, 84, 158, 345, 1260, 1342, 1400, 1661, 2701]

# Words shorter than three letters that english_words.txt lists
SHORT_WORDS = (
    "A I AM AN AS AT BE BY DO GO HE IF IN IS IT ME MY NO OF OH ON OR SO TO UP US WE"
).split()

URL = "https://www.gutenberg.org/cache/epub/{id}/pg{id}.txt"

START = re.compile(r"^\*\*\* ?START OF (THE|THIS) PROJECT GUTENBERG EBOOK", re.M)
END = re.compile(r"^\*\*\* ?END OF (THE|THIS) PROJECT GUTENBERG EBOOK", re.M)
WORD = re.compile(r"[A-Z]+")

HERE = os.path.dirname(os.path.abspath(__file__))

# Where downloaded books are kept: target/ciphey-gutenberg in the repository.
# Fixed rather than a command-line option, so no file path comes from user input.
CACHE_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(HERE))), "target", "ciphey-gutenberg"
)


def download(book_id):
    """Returns the book's text, from the cache if it's there."""
    path = os.path.join(CACHE_DIR, "pg{}.txt".format(book_id))
    if not os.path.exists(path):
        url = URL.format(id=book_id)
        print("downloading", url, file=sys.stderr)
        request = urllib.request.Request(
            url, headers={"User-Agent": "ciphey gen_quadgrams.py"}
        )
        with urllib.request.urlopen(request, timeout=60) as response:
            data = response.read()
        with open(path, "wb") as f:
            f.write(data)
        time.sleep(1)  # be polite to gutenberg.org
    with open(path, "rb") as f:
        return f.read().decode("utf-8-sig")


def body(book_id, text):
    """The book without the Project Gutenberg header and footer."""
    start = START.search(text)
    end = END.search(text)
    if start is None or end is None or end.start() < start.end():
        sys.exit("book {}: could not find the START/END OF lines".format(book_id))
    # The START line itself ends with the title, so skip to the next line
    return text[text.index("\n", start.end()) + 1 : end.start()]


def letters(text):
    """Upper-cased ASCII letters of `text`, everything else removed."""
    return "".join(c for c in text.upper() if "A" <= c <= "Z")


def header(lines):
    """`lines` as a comment block."""
    return "".join("# {}\n".format(line) for line in lines)


def write_quadgrams(path, quadgrams, min_count):
    """Writes the quadgrams seen at least `min_count` times, most common first."""
    total = sum(quadgrams.values())
    kept = sorted(
        ((q, n) for q, n in quadgrams.items() if n >= min_count),
        key=lambda item: (-item[1], item[0]),
    )
    kept_total = sum(n for _, n in kept)
    with open(path, "w", newline="\n") as out:
        out.write(
            header(
                [
                    "English quadgram counts, generated by gen_quadgrams.py from Project",
                    "Gutenberg books {}.".format(", ".join(map(str, BOOK_IDS))),
                    "{:,} quadgrams, {:,} distinct; the {:,} seen at least {} times are".format(
                        total, len(quadgrams), len(kept), min_count
                    ),
                    "listed ({:.1%} of the total).".format(kept_total / total),
                ]
            )
        )
        for quadgram, n in kept:
            out.write("{} {}\n".format(quadgram, n))
    print(
        "{:,} quadgrams, {:,} distinct, {:,} written to {}".format(
            total, len(quadgrams), len(kept), path
        ),
        file=sys.stderr,
    )


def write_words(path, words, min_count):
    """Writes the words of 3+ letters seen at least `min_count` times and the
    short words, in alphabetical order."""
    kept = {w for w, n in words.items() if len(w) >= 3 and n >= min_count}
    kept.update(SHORT_WORDS)
    with open(path, "w", newline="\n") as out:
        out.write(
            header(
                [
                    "English words, generated by gen_quadgrams.py from Project Gutenberg",
                    "books {}.".format(", ".join(map(str, BOOK_IDS))),
                    "The {:,} words of three or more letters seen at least {} times, and".format(
                        len(kept) - len(SHORT_WORDS), min_count
                    ),
                    "{} common shorter words.".format(len(SHORT_WORDS)),
                ]
            )
        )
        for word in sorted(kept):
            out.write(word + "\n")
    print("{:,} words written to {}".format(len(kept), path), file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument(
        "--min-quadgram-count",
        type=int,
        default=2,
        help="leave out quadgrams seen fewer times (default: %(default)s)",
    )
    parser.add_argument(
        "--min-word-count",
        type=int,
        default=5,
        help="leave out words seen fewer times (default: %(default)s)",
    )
    args = parser.parse_args()
    os.makedirs(CACHE_DIR, exist_ok=True)

    quadgrams = collections.Counter()
    words = collections.Counter()
    for book_id in BOOK_IDS:
        text = body(book_id, download(book_id))
        stream = letters(text)
        # Counted per book, so no quadgram spans two books
        quadgrams.update(stream[i : i + 4] for i in range(len(stream) - 3))
        # Accented letters split words: "naïve" gives "NA" and "VE", which are too
        # short to be kept
        words.update(WORD.findall(text.upper()))

    write_quadgrams(
        os.path.join(HERE, "english_quadgrams.txt"),
        quadgrams,
        args.min_quadgram_count,
    )
    write_words(os.path.join(HERE, "english_words.txt"), words, args.min_word_count)


if __name__ == "__main__":
    main()
