//! Crack the affine cipher without knowing the key.
//!
//! The affine cipher encrypts each letter x (A = 0, ..., Z = 25) as E(x) = (a*x + b) mod 26,
//! where a is coprime with 26, and decrypts it as D(y) = a^-1 * (y - b) mod 26. Case,
//! digits, whitespace, punctuation and non-ASCII characters are left as they are.
//!
//! That gives 12 * 26 = 312 keys. a = 1 is a Caesar shift and (a, b) = (25, 25) is Atbash,
//! which have their own decoders, so this cracker tries the other 285. Running the checker
//! on all of them would cost about ten times what Caesar does, so the keys are ranked
//! first, without decrypting anything: every key turns the ciphertext's letter pairs into
//! some other letter pairs, and the keys that would produce the most English-looking pairs
//! come first. Only the best few are decrypted and checked, with Low sensitivity for
//! gibberish detection. Ciphey runs every decoder on every text the search expands, so
//! text that can't be English under any key (Base64 and its Caesar shifts, long runs of a
//! few letters, letter pairs that no key makes English) is turned away before that.
//! Reference: <https://en.wikipedia.org/wiki/Affine_cipher>

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;
use gibberish_or_not::Sensitivity;
use once_cell::sync::Lazy;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::trace;

/// Every multiplier coprime with 26 except 1, which is a Caesar shift.
const MULTIPLIERS: [u8; 11] = [3, 5, 7, 9, 11, 15, 17, 19, 21, 23, 25];

/// The key (a, b) that is Atbash, which the Atbash decoder already tries.
const ATBASH_KEY: (u8, u8) = (25, 25);

/// How many of the best-ranked keys are decrypted and run through the checker.
const KEYS_CHECKED: usize = 5;

/// How many decryptions are returned for the search to keep exploring when none of the
/// checked ones is plaintext. Returning every key would flood the search frontier.
const CANDIDATES_RETURNED: usize = 3;

/// Pre-check: the fewest ASCII letters worth cracking.
const MIN_LETTERS: usize = 6;

/// Pre-check: the fewest pairs of adjacent letters (inside a word) worth ranking keys on.
const MIN_BIGRAMS: usize = 3;

/// Pre-check: texts with at least this many ASCII letters must use at least
/// [`MIN_DISTINCT_LETTERS`] different ones.
const MIN_LETTERS_FOR_DISTINCT_CHECK: usize = 100;

/// A key maps distinct letters to distinct letters, so an affine encryption of English
/// uses as many different letters as the English does: at least 16 in every window of
/// 100 or more letters from 30 Project Gutenberg books. Long texts with fewer, such as
/// Caesar shifts of Base64 of binary digits, can rank a key highly on a handful of
/// repeated letter pairs, but no key turns them into English.
const MIN_DISTINCT_LETTERS: usize = 12;

/// Pre-check: with at least [`MIN_PAIRS_FOR_SCORE_GATE`] letter pairs, at most one pair in
/// this many may be a lowercase letter followed by an uppercase one (`aB`). A key keeps
/// each letter's case, and English almost never changes case inside a word: at most 1 pair
/// in 11 in 4,480 windows of Project Gutenberg books and of Ciphey's docs, Rust identifiers
/// included. Base64 and its Caesar and rot47 shifts do it about one pair in four.
const MAX_LOWER_UPPER_PAIRS_ONE_IN: usize = 8;

/// Gate: the fewest letter pairs for which [`MIN_MEAN_PAIR_LOG_PROB`] is applied. Fewer
/// pairs give a noisier score, and short texts are cheap to check anyway.
const MIN_PAIRS_FOR_SCORE_GATE: f32 = 20.0;

/// Gate: the lowest mean `ln P` per letter pair that the best-ranked key may produce for
/// its decryption to be checked. Affine encryptions of 5,213 English windows from Project
/// Gutenberg (10 to 120 letter pairs, random keys) never scored below -6.53 (median -5.2),
/// while half of the nodes the search runs this cracker on (Base64, hex, their Caesar and
/// rot47 shifts, gibberish) score below -6.88. Below this no key reads like English, so
/// checking the best five would only spend about 0.5 ms per long node for nothing.
const MIN_MEAN_PAIR_LOG_PROB: f32 = -6.6;

/// `ln P(first, second)` for every pair of English letters, from
/// `src/storage/ngrams/english_bigrams.txt`. The file is embedded in the binary, so an
/// installed `ciphey` doesn't need the source tree to find it.
pub(crate) static BIGRAM_LOG_PROBS: Lazy<[[f32; 26]; 26]> =
    Lazy::new(|| parse_bigram_log_probs(include_str!("../storage/ngrams/english_bigrams.txt")));

/// The Affine cracker, call:
/// `let affine_decoder = Decoder::<AffineDecoder>::new()` to create a new instance
/// And then call:
/// `result = affine_decoder.crack(input, &checker)` to crack an affine string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::affine_decoder::AffineDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_affine = Decoder::<AffineDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // Wikipedia's example, encrypted with a = 5 and b = 8
/// let result = decode_affine.crack("IHHWVC SWFRCP", &checker);
/// assert!(result.success);
/// // If it succeeds, the 0th element is the plaintext, else it contains up to 3
/// // decryptions with the best-ranked keys
/// assert_eq!(result.unencrypted_text.unwrap()[0], "AFFINE CIPHER");
/// assert_eq!(result.key.unwrap(), "a=5, b=8");
/// ```
pub struct AffineDecoder;

impl Crack for Decoder<AffineDecoder> {
    fn new() -> Decoder<AffineDecoder> {
        Decoder {
            name: "Affine",
            description: "The affine cipher is a monoalphabetic substitution cipher that maps each letter x to (a*x + b) mod 26, where a is coprime with 26. Caesar (a = 1) and Atbash (a = b = 25) are special cases with their own decoders, so this cracker ranks the other 285 keys by English letter-pair frequencies and checks the five best. Uses Low sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/Affine_cipher",
            tags: vec!["affine", "decryption", "classic", "substitution"],
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// Ranks the keys, then checks the best `KEYS_CHECKED` decryptions in order and stops
    /// at the first one the checker identifies, reporting its key as `a=<a>, b=<b>`.
    /// Otherwise returns the best `CANDIDATES_RETURNED` decryptions, unidentified.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Affine cipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        // Use the checker with Low sensitivity, like the Caesar cracker
        let checker_with_sensitivity = checker.with_sensitivity(Sensitivity::Low);

        let mut candidates = Vec::with_capacity(KEYS_CHECKED);
        for ((a, b), decoded_text) in decryptions_to_check(text) {
            let checker_result = checker_with_sensitivity.check(&decoded_text);
            if checker_result.is_identified {
                trace!("Found a match with affine key a={}, b={}", a, b);
                results.unencrypted_text = Some(vec![decoded_text]);
                results.update_checker(&checker_result);
                results.key = Some(format!("a={a}, b={b}"));
                return results;
            }
            candidates.push(decoded_text);
        }

        if candidates.is_empty() {
            trace!("Failed to crack affine: the text is not worth trying");
            return results;
        }
        candidates.truncate(CANDIDATES_RETURNED);
        results.unencrypted_text = Some(candidates);
        results
    }
    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// The decryptions `crack` runs the checker on, best key first: those of the
/// `KEYS_CHECKED` best-ranked keys that change the text.
fn decryptions_to_check(text: &str) -> impl Iterator<Item = ((u8, u8), String)> + '_ {
    rank_keys(text)
        .into_iter()
        .take(KEYS_CHECKED)
        .map(move |(a, b)| ((a, b), decrypt(text, a, b)))
        .filter(move |(_, decoded_text)| check_string_success(decoded_text, text))
}

/// Every key (a, b) this cracker tries, best first, or nothing if `text` fails the
/// pre-checks (see [`ciphertext_bigrams`]) or no key turns it into English-looking letter
/// pairs (see [`MIN_MEAN_PAIR_LOG_PROB`]).
///
/// A key's score is the English log-probability of the letter pairs its decryption would
/// contain, `sum of count(y1, y2) * ln P(D(y1), D(y2))` over the ciphertext's letter pairs.
/// It is computed from the pair counts alone, so ranking costs the same for any length of
/// text and needs no decryption. Ties keep the order of [`MULTIPLIERS`], then `b`.
fn rank_keys(text: &str) -> Vec<(u8, u8)> {
    let Some(bigrams) = ciphertext_bigrams(text) else {
        return Vec::new();
    };
    let pairs: f32 = bigrams.iter().map(|&(_, _, count)| count).sum();
    let log_probs = &*BIGRAM_LOG_PROBS;

    let mut scored: Vec<(f32, (u8, u8))> = keys()
        .filter_map(|(a, b)| {
            let table = decryption_table(inverse_mod_26(a)?, b);
            let score = bigrams
                .iter()
                .map(|&(first, second, count)| {
                    count * log_probs[usize::from(table[first])][usize::from(table[second])]
                })
                .sum::<f32>();
            Some((score, (a, b)))
        })
        .collect();
    // A stable sort, so the ranking is deterministic
    scored.sort_by(|left, right| right.0.total_cmp(&left.0));
    if let Some(&(best, _)) = scored.first() {
        if pairs >= MIN_PAIRS_FOR_SCORE_GATE && best / pairs < MIN_MEAN_PAIR_LOG_PROB {
            trace!(
                "Affine: no key reads like English (best {:.2} per pair)",
                best / pairs
            );
            return Vec::new();
        }
    }
    scored.into_iter().map(|(_, key)| key).collect()
}

/// Every key (a, b) this cracker tries: a in [`MULTIPLIERS`], b in 0..26, except Atbash.
fn keys() -> impl Iterator<Item = (u8, u8)> {
    MULTIPLIERS
        .into_iter()
        .flat_map(|a| (0..26).map(move |b| (a, b)))
        .filter(|&key| key != ATBASH_KEY)
}

/// Counts the pairs of adjacent ASCII letters in `text`, case-folded, as
/// `(first, second, count)` with letters as 0..26. Letters separated by anything else,
/// such as a space, an apostrophe or a non-ASCII letter, don't form a pair.
///
/// Returns `None` unless `text` passes the pre-checks that reject what can't be affine
/// ciphertext, such as hex, numbers and very short input, before any work is done:
/// at least [`MIN_LETTERS`] ASCII letters, letters making up at least half of the
/// non-whitespace characters, at least [`MIN_BIGRAMS`] letter pairs, at least
/// [`MIN_DISTINCT_LETTERS`] different letters once there are
/// [`MIN_LETTERS_FOR_DISTINCT_CHECK`] letters, and few case changes inside words (see
/// [`MAX_LOWER_UPPER_PAIRS_ONE_IN`]).
fn ciphertext_bigrams(text: &str) -> Option<Vec<(usize, usize, f32)>> {
    let mut counts = [[0u32; 26]; 26];
    let mut letters = 0usize;
    let mut seen_letters = 0u32;
    let mut non_whitespace = 0usize;
    let mut pairs = 0usize;
    let mut lower_upper_pairs = 0usize;
    let mut previous: Option<usize> = None;
    let mut previous_lowercase = false;

    for c in text.chars() {
        if c.is_whitespace() {
            previous = None;
            continue;
        }
        non_whitespace += 1;
        let current = letter_index(c);
        if let Some(second) = current {
            letters += 1;
            seen_letters |= 1 << second;
            if let Some(first) = previous {
                counts[first][second] = counts[first][second].saturating_add(1);
                pairs += 1;
                if previous_lowercase && c.is_ascii_uppercase() {
                    lower_upper_pairs += 1;
                }
            }
        }
        previous = current;
        previous_lowercase = c.is_ascii_lowercase();
    }

    if letters < MIN_LETTERS || letters * 2 < non_whitespace || pairs < MIN_BIGRAMS {
        return None;
    }
    if letters >= MIN_LETTERS_FOR_DISTINCT_CHECK
        && (seen_letters.count_ones() as usize) < MIN_DISTINCT_LETTERS
    {
        return None;
    }
    if pairs as f32 >= MIN_PAIRS_FOR_SCORE_GATE
        && lower_upper_pairs * MAX_LOWER_UPPER_PAIRS_ONE_IN > pairs
    {
        return None;
    }

    let mut bigrams = Vec::new();
    for (first, row) in counts.iter().enumerate() {
        for (second, &count) in row.iter().enumerate() {
            if count > 0 {
                bigrams.push((first, second, count as f32));
            }
        }
    }
    Some(bigrams)
}

/// The position in the alphabet (0..26) of an ASCII letter, in either case.
fn letter_index(c: char) -> Option<usize> {
    if c.is_ascii_alphabetic() {
        Some(usize::from(c.to_ascii_lowercase() as u8 - b'a'))
    } else {
        None
    }
}

/// The inverse of `a` mod 26, if `a` is coprime with 26.
fn inverse_mod_26(a: u8) -> Option<u8> {
    (1..26u8).find(|&x| (u16::from(a) * u16::from(x)) % 26 == 1)
}

/// D(y) = a^-1 * (y - b) mod 26 for every letter y (0..26), given a^-1 and b < 26.
fn decryption_table(a_inverse: u8, b: u8) -> [u8; 26] {
    let mut table = [0u8; 26];
    for (y, plain) in (0u16..).zip(table.iter_mut()) {
        *plain = ((u16::from(a_inverse) * (y + 26 - u16::from(b))) % 26) as u8;
    }
    table
}

/// Decrypts `text` with the affine key (a, b): ASCII letters are decrypted and keep their
/// case, everything else (digits, punctuation, whitespace, non-ASCII letters) is copied.
/// If `a` is not coprime with 26 there is no such key and `text` comes back unchanged.
fn decrypt(text: &str, a: u8, b: u8) -> String {
    let Some(a_inverse) = inverse_mod_26(a) else {
        return text.to_string();
    };
    let table = decryption_table(a_inverse, b % 26);
    text.chars()
        .map(|c| match c {
            'a'..='z' => char::from(b'a' + table[usize::from(c as u8 - b'a')]),
            'A'..='Z' => char::from(b'A' + table[usize::from(c as u8 - b'A')]),
            other => other,
        })
        .collect()
}

/// Parses lines of `<letter><letter> <count>` into `ln(count / total)`. Pairs that are
/// missing, or have a count of 0, get `ln(0.01 / total)` so a rare pair is never
/// infinitely unlikely. Malformed lines are skipped.
fn parse_bigram_log_probs(source: &str) -> [[f32; 26]; 26] {
    let mut counts = [[0u64; 26]; 26];
    let mut total = 0u64;
    for line in source.lines() {
        let mut fields = line.split_ascii_whitespace();
        let (Some(pair), Some(count)) = (fields.next(), fields.next()) else {
            continue;
        };
        let mut letters = pair.chars().map(letter_index);
        let (Some(Some(first)), Some(Some(second)), None) =
            (letters.next(), letters.next(), letters.next())
        else {
            continue;
        };
        let Ok(count) = count.parse::<u64>() else {
            continue;
        };
        counts[first][second] = counts[first][second].saturating_add(count);
        total = total.saturating_add(count);
    }

    let total = total.max(1) as f64;
    let mut log_probs = [[(0.01 / total).ln() as f32; 26]; 26];
    for (log_row, count_row) in log_probs.iter_mut().zip(counts.iter()) {
        for (log_prob, &count) in log_row.iter_mut().zip(count_row.iter()) {
            if count > 0 {
                *log_prob = (count as f64 / total).ln() as f32;
            }
        }
    }
    log_probs
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };
    use crate::decoders::interface::{Crack, Decoder};

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    /// Encrypts with E(x) = a*x + b mod 26, the textbook definition, to check that
    /// `decrypt` undoes it.
    fn encrypt(text: &str, a: u8, b: u8) -> String {
        text.chars()
            .map(|c| {
                let base = match c {
                    'a'..='z' => b'a',
                    'A'..='Z' => b'A',
                    other => return other,
                };
                let x = u16::from(c as u8 - base);
                char::from(base + ((u16::from(a) * x + u16::from(b)) % 26) as u8)
            })
            .collect()
    }

    /// (ciphertext, a, b, plaintext). Each was checked with CyberChef 11.5
    /// `Affine Cipher Encode`/`Affine Cipher Decode` (see #991); the first is the example
    /// on <https://en.wikipedia.org/wiki/Affine_cipher>.
    const VECTORS: [(&str, u8, u8, &str); 7] = [
        ("IHHWVC SWFRCP", 5, 8, "AFFINE CIPHER"),
        ("Afccx, Bxscy!", 7, 3, "Hello, World!"),
        (
            "Qaaoixc UQ'm riow k dasxt az nkqax",
            3,
            10,
            "Cooking MC's like a pound of bacon",
        ),
        (
            "Yt uek tpo nokt ax tyiok, yt uek tpo uabkt ax tyiok",
            9,
            4,
            "It was the best of times, it was the worst of times",
        ),
        (
            "Usl nfdpz eyrbg wrm ofvcj rqly usl ktix arh bsdkl usl ptu jkllcj.",
            11,
            19,
            "The quick brown fox jumps over the lazy dog while the cat sleeps.",
        ),
        (
            "jhca{cjjips_iw_zewn_ycnr}",
            17,
            2,
            "flag{affine_is_just_math}",
        ),
        (
            "Zeahqi xm kcdrv lndsgw, onytf jp uxb.",
            7,
            3,
            "Sphinx of black quartz, judge my vow.",
        ),
    ];

    /// How many of `VECTORS`, from the start, the Athena checker identifies. It rejects
    /// the last one, "Sphinx of black quartz, judge my vow.", even though its key ranks
    /// first (see `sphinx_example_ranks_first_but_is_not_identified`).
    const IDENTIFIED: usize = 6;

    #[test]
    fn multipliers_are_the_units_mod_26_except_one() {
        let units: Vec<u8> = (2..26u8).filter(|&a| inverse_mod_26(a).is_some()).collect();
        assert_eq!(units, MULTIPLIERS);
        // Known inverse pairs: 3 and 9, 5 and 21, 7 and 15, 11 and 19, 17 and 23, 25 and 25
        for (a, inverse) in [(3, 9), (5, 21), (7, 15), (11, 19), (17, 23), (25, 25)] {
            assert_eq!(inverse_mod_26(a), Some(inverse));
            assert_eq!(inverse_mod_26(inverse), Some(a));
        }
        for a in [0, 2, 4, 13, 26] {
            assert_eq!(inverse_mod_26(a), None, "{a} shares a factor with 26");
        }
    }

    #[test]
    fn keyspace_is_285_keys_without_caesar_or_atbash() {
        let keys: Vec<(u8, u8)> = keys().collect();
        assert_eq!(keys.len(), 285);
        assert!(keys.iter().all(|&(a, b)| a != 1 && b < 26));
        assert!(!keys.contains(&ATBASH_KEY));
        let mut deduplicated = keys.clone();
        deduplicated.sort_unstable();
        deduplicated.dedup();
        assert_eq!(deduplicated.len(), keys.len());

        let ranked = rank_keys(VECTORS[1].0);
        assert_eq!(ranked.len(), 285);
        let mut ranked_sorted = ranked.clone();
        ranked_sorted.sort_unstable();
        assert_eq!(ranked_sorted, deduplicated);
    }

    #[test]
    fn decrypt_test_vectors() {
        for (ciphertext, a, b, plaintext) in VECTORS {
            assert_eq!(decrypt(ciphertext, a, b), plaintext, "a={a}, b={b}");
            assert_eq!(encrypt(plaintext, a, b), ciphertext, "a={a}, b={b}");
        }
    }

    #[test]
    fn decrypt_undoes_encrypt_for_every_key() {
        let plaintext = "The Quick Brown Fox, 42 jumps over THE lazy dog!";
        for a in [1].into_iter().chain(MULTIPLIERS) {
            for b in 0..26 {
                assert_eq!(decrypt(&encrypt(plaintext, a, b), a, b), plaintext);
            }
        }
    }

    #[test]
    fn decrypt_keeps_case_and_non_letters() {
        assert_eq!(decrypt("", 5, 8), "");
        assert_eq!(
            decrypt("Ihhwvc é 123 Swfrcp! 攻 😀", 5, 8),
            "Affine é 123 Cipher! 攻 😀"
        );
    }

    #[test]
    fn decrypt_with_invalid_multiplier_changes_nothing() {
        assert_eq!(decrypt("IHHWVC SWFRCP", 2, 8), "IHHWVC SWFRCP");
        assert_eq!(decrypt("IHHWVC SWFRCP", 13, 8), "IHHWVC SWFRCP");
    }

    #[test]
    fn bigram_table_is_english() {
        let log_probs = &*BIGRAM_LOG_PROBS;
        let index = |pair: &str| {
            let mut letters = pair.chars().map(|c| letter_index(c).unwrap());
            (letters.next().unwrap(), letters.next().unwrap())
        };
        let log_prob = |pair: &str| {
            let (first, second) = index(pair);
            log_probs[first][second]
        };
        let most_common = log_probs
            .iter()
            .flatten()
            .copied()
            .fold(f32::NEG_INFINITY, f32::max);
        assert_eq!(log_prob("TH"), most_common);
        assert!(log_prob("HE") > log_prob("QZ"));
        assert!(log_probs
            .iter()
            .flatten()
            .all(|p| p.is_finite() && *p < 0.0));
    }

    #[test]
    fn bigram_parser_floors_missing_pairs_and_skips_bad_lines() {
        let log_probs = parse_bigram_log_probs("TH 3\nHE 1\nbad line\nXYZ 5\nQ 2\nAB x\n\n");
        assert!((log_probs[19][7] - (0.75f32).ln()).abs() < 1e-6);
        assert!((log_probs[7][4] - (0.25f32).ln()).abs() < 1e-6);
        let floor = (0.01f32 / 4.0).ln();
        assert!((log_probs[0][1] - floor).abs() < 1e-5);
        assert!((log_probs[25][25] - floor).abs() < 1e-5);
    }

    #[test]
    fn true_key_ranks_in_the_top_two() {
        // A Python prototype of this ranking put the true key at rank 0 or 1 on these
        // texts (see #991). Only the top KEYS_CHECKED are checked.
        for (ciphertext, a, b, _) in VECTORS {
            let rank = rank_keys(ciphertext)
                .iter()
                .position(|&key| key == (a, b))
                .expect("the true key is ranked");
            assert!(rank < 2, "{ciphertext:?}: a={a}, b={b} ranked {rank}");
        }
    }

    #[test]
    fn short_examples_rank_in_the_top_two() {
        // The other two texts from the prototype in #991
        for plaintext in ["Meet me at noon", "attack at dawn"] {
            for (a, b) in [(5, 8), (7, 3), (21, 0), (25, 1)] {
                let rank = rank_keys(&encrypt(plaintext, a, b))
                    .iter()
                    .position(|&key| key == (a, b))
                    .expect("the true key is ranked");
                assert!(rank < 2, "{plaintext:?}: a={a}, b={b} ranked {rank}");
            }
        }
    }

    #[test]
    fn successful_decoding_reports_the_key() {
        let affine_decoder = Decoder::<AffineDecoder>::new();
        for &(ciphertext, a, b, plaintext) in &VECTORS[..IDENTIFIED] {
            let result = affine_decoder.crack(ciphertext, &get_athena_checker());
            assert!(result.success, "{ciphertext:?} was not cracked: {result:?}");
            assert_eq!(result.unencrypted_text.unwrap(), vec![plaintext]);
            assert_eq!(result.key.unwrap(), format!("a={a}, b={b}"));
        }
    }

    #[test]
    fn issue_example_reports_its_key() {
        let affine_decoder = Decoder::<AffineDecoder>::new();
        let result = affine_decoder.crack("IHHWVC SWFRCP", &get_athena_checker());
        assert!(result.success);
        assert_eq!(result.unencrypted_text.unwrap()[0], "AFFINE CIPHER");
        assert_eq!(result.key.as_deref(), Some("a=5, b=8"));
        assert_eq!(result.decoder, "Affine");
    }

    #[test]
    fn flag_is_identified_by_lemmeknow() {
        let affine_decoder = Decoder::<AffineDecoder>::new();
        let result = affine_decoder.crack("jhca{cjjips_iw_zewn_ycnr}", &get_athena_checker());
        assert!(result.success);
        assert_eq!(
            result.unencrypted_text.unwrap()[0],
            "flag{affine_is_just_math}"
        );
        assert_eq!(result.key.as_deref(), Some("a=17, b=2"));
        assert_eq!(result.checker_name, "LemmeKnow Checker");
    }

    #[test]
    fn sphinx_example_ranks_first_but_is_not_identified() {
        // The issue's longer example. The Athena checker rejects the plaintext at Low
        // sensitivity, so the cracker can't report success, but the true key ranks first
        // and its decryption is the first candidate handed back to the search.
        let (ciphertext, a, b, plaintext) = VECTORS[6];
        assert_eq!(rank_keys(ciphertext)[0], (a, b));

        let affine_decoder = Decoder::<AffineDecoder>::new();
        let result = affine_decoder.crack(ciphertext, &get_athena_checker());
        let candidates = result.unencrypted_text.unwrap();
        assert_eq!(candidates[0], plaintext);
        if result.success {
            assert_eq!(result.key.as_deref(), Some("a=7, b=3"));
        } else {
            assert_eq!(candidates.len(), CANDIDATES_RETURNED);
            assert!(result.key.is_none());
        }
    }

    #[test]
    fn checks_at_most_five_keys() {
        assert_eq!(KEYS_CHECKED, 5);
        for text in [
            // 19 letter pairs, too few for the score gate
            "T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0",
            VECTORS[4].0,
            VECTORS[6].0,
        ] {
            assert_eq!(decryptions_to_check(text).count(), KEYS_CHECKED);
        }
    }

    #[test]
    fn unidentified_text_returns_the_three_best_decryptions() {
        // Reversed English: its letter pairs pass the score gate under the true key, but no
        // decryption is English the right way round.
        let affine_decoder = Decoder::<AffineDecoder>::new();
        let reversed: String = VECTORS[3].3.chars().rev().collect();
        let text = encrypt(&reversed, 9, 4);
        let result = affine_decoder.crack(&text, &get_athena_checker());
        assert!(!result.success, "{result:?}");
        assert!(result.key.is_none());
        let expected: Vec<String> = rank_keys(&text)
            .into_iter()
            .take(CANDIDATES_RETURNED)
            .map(|(a, b)| decrypt(&text, a, b))
            .collect();
        assert_eq!(expected.len(), CANDIDATES_RETURNED);
        assert_eq!(result.unencrypted_text.unwrap(), expected);
    }

    #[test]
    fn score_gate_skips_text_no_key_turns_into_english() {
        // Each passes the pre-checks with enough letter pairs for the gate, but the best
        // key's decryption still doesn't read like English: nothing is decrypted or
        // checked, and nothing is returned.
        let affine_decoder = Decoder::<AffineDecoder>::new();
        for text in [
            // Plain English is not an affine encryption of English: a = 1 is Caesar's
            "The quick brown fox jumps over the lazy dog",
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
            // Base32 of "The quick brown fox jumps over the lazy dog"
            "KRUGKIDROVUWG2ZAMJZG653OEBTG66BANJ2W24DTEBXXMZLSEB2GQZJANRQXU6JAMRXWO===",
        ] {
            let bigrams = ciphertext_bigrams(text).expect("passes the pre-checks");
            let pairs: f32 = bigrams.iter().map(|&(_, _, count)| count).sum();
            assert!(pairs >= MIN_PAIRS_FOR_SCORE_GATE, "{text:?}: {pairs} pairs");
            assert!(rank_keys(text).is_empty(), "{text:?} passed the score gate");
            assert_eq!(decryptions_to_check(text).count(), 0, "{text:?}");
            let result = affine_decoder.crack(text, &get_athena_checker());
            assert!(!result.success, "{text:?}");
            assert!(result.unencrypted_text.is_none(), "{text:?}");
        }
    }

    #[test]
    fn mixed_case_text_is_rejected() {
        let affine_decoder = Decoder::<AffineDecoder>::new();
        for text in [
            // Base64 of "The quick brown fox jumps over the lazy dog": 12 of 49 pairs are `aB`
            "VGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZw==",
            // The decoder benchmarks' miss input (benches/data/decoders.toml): 7 of 23
            "T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV",
        ] {
            assert!(ciphertext_bigrams(text).is_none(), "{text:?}");
            let result = affine_decoder.crack(text, &get_athena_checker());
            assert!(result.unencrypted_text.is_none(), "{text:?}");
        }
        // English with identifiers in it stays below one pair in eight (7 of 73 here)
        let identifiers = encrypt(
            "The CheckerTypes::CheckWaitAthena function returns a ThreadSafePriorityQueue of SearchNodes",
            5,
            8,
        );
        assert!(ciphertext_bigrams(&identifiers).is_some());
        // Short texts aren't checked: too few pairs to tell
        assert!(ciphertext_bigrams("aBcDeF gHiJ").is_some());
    }

    #[test]
    fn score_gate_keeps_affine_english() {
        // Longer than the gate's minimum, encrypted with every one of the 285 keys
        let plaintext =
            "It was the best of times, it was the worst of times, it was the age of wisdom";
        for (a, b) in keys() {
            let ranked = rank_keys(&encrypt(plaintext, a, b));
            assert_eq!(ranked.len(), 285, "a={a}, b={b} was gated");
            assert_eq!(ranked[0], (a, b), "a={a}, b={b}");
        }
    }

    #[test]
    fn long_text_with_few_distinct_letters_is_rejected() {
        // A Caesar shift of Hexadecimal output that the search produces: 120 letters but
        // only 10 different ones. Its best key scores -6.04 per pair, so only this
        // pre-check stops it.
        let text = "L|NMNMOLJHN|NMJHNIOLJHOLNPNMJHN~N{NLJHN{NQNONPOLNPN~OMOKNMJHNINNOLNMOJJHN|NQNLN}NQNONPOLJHNIN}NLJHNJOJNQN}NOJHOLNPNMJHN|NIOHJ{JHOLNP";
        assert!(ciphertext_bigrams(text).is_none());
        let result = Decoder::<AffineDecoder>::new().crack(text, &get_athena_checker());
        assert!(result.unencrypted_text.is_none());
        // English of the same length uses far more letters
        let english = VECTORS[3].0.repeat(3);
        assert!(ciphertext_bigrams(&english).is_some());
    }

    #[test]
    fn pre_checks_reject_input_that_cannot_be_affine() {
        let affine_decoder = Decoder::<AffineDecoder>::new();
        for text in [
            "",
            "😀",
            "ab",
            "12345",
            // 5 letters
            "abc de",
            // 6 letters but only 2 pairs
            "ab cd e f",
            // 6 letters and 4 pairs, but more digits than letters
            "abc12345 def67890",
            // hex
            "48656c6c6f2c20576f726c6421",
            // letters, but no two next to each other
            "a1b2c3d4e5f6g7h8",
            // non-ASCII letters only
            "éèêëàâäôöûüç",
            "     ",
        ] {
            assert!(rank_keys(text).is_empty(), "{text:?} passed the pre-checks");
            let result = affine_decoder.crack(text, &get_athena_checker());
            assert!(!result.success, "{text:?}");
            assert!(result.unencrypted_text.is_none(), "{text:?}");
            assert!(result.key.is_none(), "{text:?}");
        }
        // Just enough: 6 letters, 3 pairs, half the non-whitespace characters
        assert_eq!(rank_keys("abcd e f").len(), 285);
        assert_eq!(rank_keys("abcd e f 1!2?3.").len(), 285);
    }

    #[test]
    fn caesar_atbash_and_plaintext_are_not_cracked() {
        // ROT13 and Atbash keys are skipped (the Caesar and Atbash decoders own them),
        // and ordinary English shouldn't decrypt to anything English.
        let affine_decoder = Decoder::<AffineDecoder>::new();
        for text in [
            "Uryyb, Jbeyq!",
            "Svool, Dliow!",
            "The quick brown fox jumps over the lazy dog",
        ] {
            let result = affine_decoder.crack(text, &get_athena_checker());
            assert!(!result.success, "{text:?} was cracked: {result:?}");
            assert!(result.key.is_none());
            let candidates = result.unencrypted_text.unwrap_or_default();
            assert!(candidates.len() <= CANDIDATES_RETURNED);
            assert!(!candidates.iter().any(|c| c == "Hello, World!"));
        }
    }

    #[test]
    fn decoder_metadata() {
        let affine_decoder = Decoder::<AffineDecoder>::new();
        assert_eq!(affine_decoder.get_name(), "Affine");
        assert_eq!(affine_decoder.get_popularity(), 0.5);
        assert_eq!(
            affine_decoder.get_link(),
            "https://en.wikipedia.org/wiki/Affine_cipher"
        );
        // A cracker, not a decoder, and not reciprocal: two affine steps compose into one
        let tags = affine_decoder.get_tags();
        assert!(!tags.contains(&"decoder"));
        assert!(!tags.contains(&"reciprocal"));
        assert!(tags.contains(&"affine"));
    }

    #[test]
    fn registered_once() {
        let decoders = crate::filtration_system::get_decoder_by_name("Affine");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Affine");
        let decoder = crate::decoders::DECODER_MAP
            .get("Affine")
            .expect("Affine is in DECODER_MAP")
            .get::<()>();
        assert_eq!(decoder.get_name(), "Affine");
    }
}
