//! Decode an Ascii85 string (the Adobe / btoa flavour of Base85)
//! Performs error handling and returns a string
//! Call ascii85_decoder.crack to use. It returns a `CrackResult`; check
//! `result.unencrypted_text.is_some()` to see if it decoded.
//!
//! Ascii85 turns every 4 bytes into 5 characters from `!` to `u`. Each character is the
//! base-85 digit `c - 33` and a group is read big-endian. `z` stands for a whole group of
//! four zero bytes and whitespace is ignored. Adobe wraps the data in `<~ ... ~>`; PDF and
//! PostScript streams often only have the `~>` end marker.
//! See <https://en.wikipedia.org/wiki/Ascii85>.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The Ascii85 decoder, call:
/// `let ascii85_decoder = Decoder::<Ascii85Decoder>::new()` to create a new instance
/// And then call:
/// `result = ascii85_decoder.crack(input)` to decode an Ascii85 string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::ascii85_decoder::Ascii85Decoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_ascii85 = Decoder::<Ascii85Decoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_ascii85.crack("<~BOu!rD]j7BEbo7~>", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hello world");
/// ```
pub struct Ascii85Decoder;

impl Crack for Decoder<Ascii85Decoder> {
    fn new() -> Decoder<Ascii85Decoder> {
        Decoder {
            name: "Ascii85",
            description: "Ascii85, also called Base85, is a binary-to-text encoding developed by Paul E. Rutter for the btoa utility. It uses five ASCII characters from ! to u to represent four bytes of binary data, and z for four zero bytes. Adobe's variant, used in PostScript and PDF, wraps the data in <~ and ~>.",
            link: "https://en.wikipedia.org/wiki/Ascii85",
            tags: vec!["ascii85", "base85", "decoder", "base"],
            popularity: 0.4,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// On success `unencrypted_text` holds the decoded text and the checker has run on it
    /// Else `unencrypted_text` is `None` and the reason is logged
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Ascii85 with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_ascii85(text).and_then(bytes_to_text) else {
            debug!("Failed to decode Ascii85: the input is not Ascii85 or does not decode to text");
            return results;
        };

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Ascii85 because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);

        results.update_checker(&checker_result);

        results
    }
    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Value of the highest digit, `u`. A final partial group is padded with it.
const PAD_DIGIT: u64 = 84;

/// Strips the optional Adobe `<~` prefix and `~>` suffix from the trimmed input.
/// Returns the body and whether either marker was there.
fn strip_markers(text: &str) -> (&str, bool) {
    let mut body = text.trim();
    let mut delimited = false;
    if let Some(rest) = body.strip_prefix("<~") {
        body = rest;
        delimited = true;
    }
    if let Some(rest) = body.strip_suffix("~>") {
        body = rest;
        delimited = true;
    }
    (body, delimited)
}

/// Cheap O(n) check, before anything is allocated, that `body` can be Ascii85.
///
/// The body may only contain digits (`!` to `u`), `z` and whitespace, so `v` to `y`, `{|}~`
/// (including a `~` outside the markers) and non-ASCII text all fail. Without the `<~ ~>`
/// markers the body must also look like encoder output: wrapped with line breaks only (no
/// spaces or tabs, which mean prose) and with at least one digit that is neither a letter nor
/// a number, so that words like `Hello` are not decoded into junk.
fn looks_like_ascii85(body: &str, delimited: bool) -> bool {
    let mut has_symbol = false;
    for &byte in body.as_bytes() {
        match byte {
            b'!'..=b'u' => has_symbol |= !byte.is_ascii_alphanumeric(),
            b'z' | b'\n' | b'\r' => {}
            b' ' | b'\t' | 0x0b | 0x0c if delimited => {}
            _ => return false,
        }
    }
    delimited || has_symbol
}

/// Decodes Ascii85, with or without the `<~ ~>` markers (either one may be missing), into bytes.
///
/// Returns `None` if the input fails [`looks_like_ascii85`], has a `z` inside a group, has a
/// group above `u32::MAX`, or ends in a single leftover digit, which no encoder produces.
fn decode_ascii85(text: &str) -> Option<Vec<u8>> {
    let (body, delimited) = strip_markers(text);
    if !looks_like_ascii85(body, delimited) {
        return None;
    }

    let mut decoded = Vec::with_capacity(body.len() / 5 * 4 + 4);
    let mut group: u64 = 0;
    let mut digits: usize = 0;
    for &byte in body.as_bytes() {
        match byte {
            b'!'..=b'u' => {
                group = group * 85 + u64::from(byte - b'!');
                digits += 1;
                if digits == 5 {
                    decoded.extend_from_slice(&u32::try_from(group).ok()?.to_be_bytes());
                    group = 0;
                    digits = 0;
                }
            }
            // `z` replaces a whole group, so it can only appear between groups.
            b'z' if digits == 0 => decoded.extend_from_slice(&[0; 4]),
            b'z' => return None,
            // Whitespace, already vetted by `looks_like_ascii85`.
            _ => {}
        }
    }

    // A final group of k digits holds k - 1 bytes: pad it with `u` and keep those bytes.
    match digits {
        0 => {}
        1 => return None,
        _ => {
            for _ in digits..5 {
                group = group * 85 + PAD_DIGIT;
            }
            let bytes = u32::try_from(group).ok()?.to_be_bytes();
            decoded.extend_from_slice(&bytes[..digits - 1]);
        }
    }
    Some(decoded)
}

/// Turns decoded bytes into text, or `None` if they are not text.
///
/// Ascii85 often wraps binary data (PDF streams, compressed blobs) and almost any string in
/// its alphabet decodes to something, so only strict UTF-8 without control characters other
/// than tabs and line breaks is kept. That rejects nearly all junk before the checkers run.
fn bytes_to_text(bytes: Vec<u8>) -> Option<String> {
    let text = String::from_utf8(bytes).ok()?;
    let is_text = !text
        .chars()
        .any(|c| c.is_control() && !matches!(c, '\t' | '\n' | '\r'));
    is_text.then_some(text)
}

#[cfg(test)]
mod tests {
    use super::{decode_ascii85, Ascii85Decoder};
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::interface::{Crack, Decoder},
        decoders::DECODER_MAP,
        filtration_system::get_decoder_by_name,
    };

    // Unless noted otherwise, the vectors were made with Python 3 `base64.a85encode(...,
    // adobe=True)` and decoded back with `base64.a85decode`; the bodies match CyberChef's
    // "To Base85" with the `!-u` alphabet.

    /// The example from issue #926.
    const SPHINX: &str = r#"<~;fHDaDKm:BAftQ!@:O'qEHP]1FF#J\C3='"AKYi8+Eh[I/c~>"#;
    /// The example from issue #926 without the markers.
    const SPHINX_BARE: &str = r#";fHDaDKm:BAftQ!@:O'qEHP]1FF#J\C3='"AKYi8+Eh[I/c"#;
    /// "The quick brown fox jumps over the lazy dog"
    const FOX: &str = "<~<+ohcEHPu*CER),Dg-(AAoDo:C3=B4F!,CEATAo8BOr<&@=!2AA8c)~>";
    /// The Hobbes quote from Wikipedia's Ascii85 article, wrapped at 75 columns.
    const LEVIATHAN: &str = concat!(
        r#"<~9jqo^BlbD-BleB1DJ+*+F(f,q/0JhKF<GL>Cj@.4Gp$d7F!,L7@<6@)/0JDEF<G%<+EV:2F!,"#,
        "\n",
        r#"O<DJ+*.@<*K0@<6L(Df-\0Ec5e;DffZ(EZee.Bl.9pF"AGXBPCsi+DGm>@3BB/F*&OCAfu2/AKY"#,
        "\n",
        r#"i(DIb:@FD,*)+C]U=@3BN#EcYf8ATD3s@q?d$AftVqCh[NqF<G:8+EV:.+Cf>-FD5W8ARlolDIa"#,
        "\n",
        r#"l(DId<j@<?3r@:F%a+D58'ATD4$Bl@l3De:,-DJs`8ARoFb/0JMK@qB4^F!,R<AKZ&-DfTqBG%G"#,
        "\n",
        r#">uD.RTpAKYo'+CT/5+Cei#DII?(E,9)oF*2M7/c~>"#,
    );

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    // Runs the decoder and returns the plaintext it found, if any.
    fn crack(text: &str) -> Option<String> {
        Decoder::<Ascii85Decoder>::new()
            .crack(text, &get_athena_checker())
            .unencrypted_text
            .map(|texts| texts[0].clone())
    }

    #[test]
    fn ascii85_decodes_issue_example() {
        // Athena does not recognise this pangram as English, so only the text is checked.
        assert_eq!(
            crack(SPHINX).as_deref(),
            Some("Sphinx of black quartz, judge my vow.")
        );
    }

    #[test]
    fn ascii85_decodes_issue_example_without_markers() {
        assert_eq!(
            crack(SPHINX_BARE).as_deref(),
            Some("Sphinx of black quartz, judge my vow.")
        );
    }

    #[test]
    fn ascii85_decodes_and_identifies_plaintext() {
        let result = Decoder::<Ascii85Decoder>::new().crack(FOX, &get_athena_checker());
        assert_eq!(
            result.unencrypted_text.unwrap()[0],
            "The quick brown fox jumps over the lazy dog"
        );
        assert!(result.success);
    }

    #[test]
    fn ascii85_decodes_the_string_from_the_z85_tests() {
        // z85_decoder.rs uses this Ascii85 string as a non-Z85 input
        assert_eq!(crack("87cURD]j.8ATD?*").as_deref(), Some("Hello there!"));
    }

    #[test]
    fn ascii85_decodes_hello_world_in_every_framing() {
        for text in [
            "<~BOu!rD]j7BEbo7~>",
            // Whitespace inside the markers is ignored
            "<~BOu!r D]j7B\nEbo7~>",
            // PDF and PostScript streams often only have the end-of-data marker
            "BOu!rD]j7BEbo7~>",
            // A missing end marker is accepted, like CyberChef does
            "<~BOu!rD]j7BEbo7",
            // Surrounding whitespace is trimmed
            "  <~BOu!rD]j7BEbo7~>\n",
            // Bare input may be wrapped with line breaks
            "BOu!rD]j7\r\nBEbo7",
        ] {
            assert_eq!(crack(text).as_deref(), Some("hello world"), "{text:?}");
        }
    }

    #[test]
    fn ascii85_decodes_multi_line_wikipedia_example() {
        // https://en.wikipedia.org/wiki/Ascii85#Example_for_Ascii85
        assert_eq!(
            crack(LEVIATHAN).as_deref(),
            Some("Man is distinguished, not only by his reason, but by this singular passion from other animals, which is a lust of the mind, that by a perseverance of delight in the continued and indefatigable generation of knowledge, exceeds the short vehemence of any carnal pleasure.")
        );
    }

    #[test]
    fn ascii85_decodes_full_and_partial_groups() {
        // "Man " -> "9jqo^" is the first group of the Wikipedia example
        assert_eq!(decode_ascii85("<~9jqo^~>"), Some(b"Man ".to_vec()));
        // A final group of k digits holds k - 1 bytes
        assert_eq!(decode_ascii85("<~9`~>"), Some(b"M".to_vec()));
        assert_eq!(decode_ascii85("<~9jn~>"), Some(b"Ma".to_vec()));
        assert_eq!(decode_ascii85("<~9jqo~>"), Some(b"Man".to_vec()));
    }

    #[test]
    fn ascii85_decodes_zero_group_and_largest_group() {
        assert_eq!(
            decode_ascii85("zBOu!rDZ"),
            Some(vec![0x00, 0x00, 0x00, 0x00, 0x68, 0x65, 0x6c, 0x6c, 0x6f])
        );
        assert_eq!(decode_ascii85("s8W-!"), Some(vec![0xff; 4]));
    }

    #[test]
    fn ascii85_rejects_invalid_groups() {
        // 2^32, one more than the largest group
        assert_eq!(decode_ascii85("s8W-\""), None);
        // `z` inside a group
        assert_eq!(decode_ascii85("BOzu!"), None);
        // A single leftover digit holds no bytes; no encoder produces it
        assert_eq!(decode_ascii85("BOu!rD]j7BE"), None);
        // A padded final group can overflow too
        assert_eq!(decode_ascii85("<~uuuu~>"), None);
    }

    #[test]
    fn ascii85_rejects_characters_outside_the_alphabet() {
        for text in [
            // RFC 1924 Base85 uses `v` to `~`
            "Xk~0{Zy<MXa%^M",
            // btoa's `y` (four spaces) extension is not supported
            "<~y~>",
            // `~` is only allowed in the markers
            "<~BOu!r~D]j7BEbo7~>",
            "😀",
            "<~😀~>",
        ] {
            assert_eq!(decode_ascii85(text), None, "{text:?}");
            assert_eq!(crack(text), None, "{text:?}");
        }
    }

    #[test]
    fn ascii85_rejects_bare_text_that_is_not_encoder_output() {
        for text in [
            // Only letters and numbers
            "Hello",
            "SGVsbG8gV29ybGQh",
            // Spaces or tabs without markers
            "hello world",
            "BOu!r D]j7BEbo7",
            "BOu!r\tD]j7BEbo7",
        ] {
            assert_eq!(decode_ascii85(text), None, "{text:?}");
            assert_eq!(crack(text), None, "{text:?}");
        }
    }

    #[test]
    fn ascii85_rejects_output_that_is_not_text() {
        // Z85 for "Hello World!" is valid Ascii85, but decodes to invalid UTF-8
        assert!(decode_ascii85("nm=QNzY&b1A+]nf").is_some());
        assert_eq!(crack("nm=QNzY&b1A+]nf"), None);
        // NUL bytes from `z`
        assert_eq!(crack("zBOu!rDZ"), None);
        // "hello\x01"
        assert_eq!(crack("BOu!rDZK"), None);
    }

    #[test]
    fn ascii85_keeps_tabs_line_breaks_and_non_ascii_text() {
        assert_eq!(crack("BOu!rD[CW+Ebo7n").as_deref(), Some("hello\tworld\n"));
        // "Grüße, 世界"
        assert_eq!(crack("7rlM[_k1Kk+QU%ukEUu").as_deref(), Some("Grüße, 世界"));
    }

    #[test]
    fn ascii85_decode_empty_string() {
        assert_eq!(decode_ascii85(""), None);
        assert_eq!(crack(""), None);
    }

    #[test]
    fn ascii85_rejects_empty_bodies() {
        // Valid Ascii85 for no bytes, but there is nothing to return
        assert_eq!(decode_ascii85("<~~>"), Some(Vec::new()));
        for text in ["<~~>", "<~", "~>", "<~ \n ~>"] {
            assert_eq!(crack(text), None, "{text:?}");
        }
    }

    #[test]
    fn ascii85_decode_handles_panics() {
        assert_eq!(crack("hello my name is panicky mc panic face!"), None);
    }

    #[test]
    fn ascii85_handle_panic_if_emoji() {
        assert_eq!(crack("😂"), None);
    }

    #[test]
    fn ascii85_is_registered() {
        let decoders = get_decoder_by_name("Ascii85");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Ascii85");
        // The cache looks decoders up by name when it reads a stored path back
        assert!(DECODER_MAP.contains_key("Ascii85"));
    }
}
