//! Decode backslash escapes, the way C, Python and JavaScript write bytes in string
//! literals: `\110\145\154\154\157`, `\x48\x69`, `Line one\nLine two\t\x41` and so on.
//!
//! The text is scanned once. Every well-formed escape is replaced by the byte it stands for
//! and everything else is copied unchanged, so escapes mixed with ordinary text decode too.
//!
//! | Escape                       | Byte                                                  |
//! |------------------------------|-------------------------------------------------------|
//! | `\NNN`                       | 1 to 3 octal digits, at most 2 if the first is 4 to 7 |
//! | `\xHH`                       | exactly 2 hex digits, either case                     |
//! | `\a` `\b` `\f` `\n` `\r` `\t` `\v` | BEL, BS, FF, LF, CR, TAB, VT                    |
//! | `\\` `\'` `\"`               | the character after the backslash                     |
//!
//! As in JavaScript and CyberChef, an octal escape never goes above `\377` (255): `\400`
//! is `\40` (a space) followed by `0`. Anything else after a backslash is copied as it is,
//! like Python and CyberChef do: `\e`, `\/`, `\8`, `\q`, a `\x` without two hex digits and a
//! trailing `\`. So are `\uXXXX`, `\u{…}` and `\UXXXXXXXX`, which the Unicode Escapes
//! decoder reads, so that the two decoders don't both produce the same text.
//!
//! Escapes stand for bytes, not characters: `\xc3\xa9` is `é`. The bytes are read as UTF-8,
//! falling back to Latin-1. The whole text may be a quoted literal, such as the Python bytes
//! repr `b'caf\xc3\xa9'` or `"\x48\x69"`; the quotes and the `b` are dropped.
//!
//! References:
//! * [Escape sequences in C](https://en.wikipedia.org/wiki/Escape_sequences_in_C)
//! * [Python escape sequences](https://docs.python.org/3/reference/lexical_analysis.html#escape-sequences)
//! * [ECMA-262 legacy octal escapes](https://tc39.es/ecma262/#prod-annexB-LegacyOctalEscapeSequence)
//! * [CyberChef Unescape string](https://gchq.github.io/CyberChef/#recipe=Unescape_string())
//!
//! ```
//! use ciphey::checkers::{
//!     athena::Athena,
//!     checker_type::{Check, Checker},
//!     CheckerTypes,
//! };
//! use ciphey::decoders::backslash_escape_decoder::BackslashEscapeDecoder;
//! use ciphey::decoders::interface::{Crack, Decoder};
//!
//! let decoder = Decoder::<BackslashEscapeDecoder>::new();
//! let checker = CheckerTypes::CheckAthena(Checker::<Athena>::new());
//!
//! let result = decoder.crack(r"\110\145\154\154\157\054\040\x57\x6f\x72\x6c\x64\x21", &checker);
//! assert!(result.success);
//! assert_eq!(result.unencrypted_text.unwrap()[0], "Hello, World!");
//!
//! // Text without a single escape is not decoded
//! let result = decoder.crack(r"C:\Users", &checker);
//! assert!(result.unencrypted_text.is_none());
//! ```

use crate::checkers::CheckerTypes;
use crate::decoders::interface::{bytes_to_string, check_string_success};

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The backslash escape decoder, call:
/// `let decoder = Decoder::<BackslashEscapeDecoder>::new()` to create a new instance
/// And then call:
/// `result = decoder.crack(input, &checker)` to decode the escapes in a string
/// The struct generated by new() comes from interface.rs
pub struct BackslashEscapeDecoder;

impl Crack for Decoder<BackslashEscapeDecoder> {
    fn new() -> Decoder<BackslashEscapeDecoder> {
        Decoder {
            name: "Backslash Escapes",
            description: "C, Python and JavaScript string escapes (\\NNN in octal, \\xHH in hexadecimal, \\n, \\t, \\\\ and the other single-character escapes) mixed with literal text, optionally inside a Python b'…' repr.",
            link: "https://en.wikipedia.org/wiki/Escape_sequences_in_C",
            tags: vec!["backslash_escape", "escape", "string", "decoder"],
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// Replaces every escape in `text` with its byte (see the module docs for the forms)
    /// and runs the checker on the result.
    ///
    /// Fails unless at least one escape was replaced. Trailing NULs, the terminator of a C
    /// string, are dropped; any other control character apart from tab, carriage return
    /// and line feed fails the text, and so does a result that is only whitespace.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying backslash escapes with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        // One pass over the bytes that rejects almost every input the search tries
        if !has_escape(text) {
            trace!("No backslash escape in text");
            return results;
        }

        let Some(decoded_text) = decode_backslash_escapes(text) else {
            debug!("Failed to decode backslash escapes: none replaced, or the result is not text");
            return results;
        };

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode backslash escapes because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);

        results.update_checker(&checker_result);

        results
    }
    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Whether some backslash in `text` starts a well-formed escape.
///
/// This runs on every text the search tries, and nearly all of them have no backslash at
/// all. Searching for a `char` uses `memchr`, so the common case is a fast scan with no
/// allocation.
fn has_escape(text: &str) -> bool {
    let bytes = text.as_bytes();
    text.match_indices('\\')
        .any(|(index, _)| parse_escape(&bytes[index + 1..]).is_some())
}

/// Decodes `text`, or returns `None` if it has no escape or doesn't decode to text.
fn decode_backslash_escapes(text: &str) -> Option<String> {
    let mut bytes = decode_escapes(strip_literal_quotes(text).as_bytes())?;
    // A C string ends with a NUL byte: `hello world\0`
    while bytes.last() == Some(&0) {
        bytes.pop();
    }
    let decoded = bytes_to_string(bytes);
    if decoded.trim().is_empty() || has_unexpected_control_character(&decoded) {
        return None;
    }
    Some(decoded)
}

/// The text inside a quoted string literal that makes up the whole (trimmed) text: a
/// Python bytes repr `b'…'` or `B"…"`, or a bare `'…'` or `"…"`. Returns `text` unchanged
/// if it isn't one.
fn strip_literal_quotes(text: &str) -> &str {
    let trimmed = text.trim();
    let unprefixed = trimmed.strip_prefix(['b', 'B']).unwrap_or(trimmed);
    ['\'', '"']
        .into_iter()
        .find_map(|quote| unprefixed.strip_prefix(quote)?.strip_suffix(quote))
        .unwrap_or(text)
}

/// Replaces every well-formed escape in `bytes` with the byte it stands for and copies the
/// rest unchanged, so non-ASCII text between escapes keeps its UTF-8 bytes.
///
/// Returns `None` when nothing was replaced.
fn decode_escapes(bytes: &[u8]) -> Option<Vec<u8>> {
    let mut decoded = Vec::with_capacity(bytes.len());
    let mut replaced_any = false;
    // Everything before this offset has been written to `decoded`
    let mut copied_up_to = 0;
    let mut i = 0;

    while let Some(offset) = bytes[i..].iter().position(|&byte| byte == b'\\') {
        let backslash = i + offset;
        i = backslash + 1;
        // Anything that isn't an escape, such as `\q`, `\u0041` or a trailing `\`, is
        // copied unchanged along with the text around it
        let Some((byte, len)) = parse_escape(&bytes[i..]) else {
            continue;
        };
        decoded.extend_from_slice(&bytes[copied_up_to..backslash]);
        decoded.push(byte);
        replaced_any = true;
        i += len;
        copied_up_to = i;
    }

    if !replaced_any {
        return None;
    }
    decoded.extend_from_slice(&bytes[copied_up_to..]);
    Some(decoded)
}

/// Parses the escape whose backslash comes just before `after`. Returns the byte it stands
/// for and how many bytes of `after` it uses, or `None` if the backslash doesn't start an
/// escape.
fn parse_escape(after: &[u8]) -> Option<(u8, usize)> {
    let &first = after.first()?;
    let byte = match first {
        b'\\' | b'\'' | b'"' => first,
        b'a' => 0x07,
        b'b' => 0x08,
        b'f' => 0x0c,
        b'n' => b'\n',
        b'r' => b'\r',
        b't' => b'\t',
        b'v' => 0x0b,
        b'x' => {
            let high = hex_digit_value(*after.get(1)?)?;
            let low = hex_digit_value(*after.get(2)?)?;
            return Some(((high << 4) | low, 3));
        }
        b'0'..=b'7' => {
            // `\377` is the largest byte. Like JavaScript, read a third digit only after a
            // first digit of 0 to 3, so the value always fits in a byte.
            let max_digits = if first <= b'3' { 3 } else { 2 };
            let digits = after
                .iter()
                .take(max_digits)
                .take_while(|digit| matches!(digit, b'0'..=b'7'))
                .count();
            let value = after[..digits]
                .iter()
                .fold(0, |value, &digit| value * 8 + (digit - b'0'));
            return Some((value, digits));
        }
        _ => return None,
    };
    Some((byte, 1))
}

/// The value of one ASCII hex digit, either case
fn hex_digit_value(digit: u8) -> Option<u8> {
    match digit {
        b'0'..=b'9' => Some(digit - b'0'),
        b'a'..=b'f' => Some(digit - b'a' + 10),
        b'A'..=b'F' => Some(digit - b'A' + 10),
        _ => None,
    }
}

/// Whether `text` has a control character other than tab, carriage return or line feed.
/// Plaintext doesn't contain BEL, ESC or NUL, so escapes that decode to one mean this
/// wasn't a string of escaped text.
fn has_unexpected_control_character(text: &str) -> bool {
    text.chars()
        .any(|c| c.is_control() && !matches!(c, '\t' | '\r' | '\n'))
}

#[cfg(test)]
mod tests {
    use super::{decode_escapes, has_escape, BackslashEscapeDecoder};
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::{
            crack_results::CrackResult,
            interface::{Crack, Decoder},
            DecoderType, DECODER_MAP,
        },
        filtration_system::get_decoder_by_name,
    };

    // References: Python 3.9 reading the text as a bytes literal (`ast.literal_eval`, then
    // UTF-8) and CyberChef's "Unescape string"
    // (https://gchq.github.io/CyberChef/#recipe=Unescape_string(), `Utils.parseEscapedChars`).
    // For every vector that decodes, both give the decoder's output unless the test says
    // otherwise. The vectors from the implementation plan in
    // https://github.com/bee-san/Ciphey/issues/941 were checked with both.

    /// The medium plaintext of benches/data/decoders.toml
    const LIGHTHOUSE: &str =
        "Meet me at the old lighthouse after midnight and bring the map, the key and a torch.";

    /// `LIGHTHOUSE` with letters as `\xHH` and everything else as `\NNN`, made with Python:
    /// `''.join('\\x%02x' % b if chr(b).isalpha() else '\\%03o' % b for b in s.encode())`
    const LIGHTHOUSE_ESCAPED: &str = r"\x4d\x65\x65\x74\040\x6d\x65\040\x61\x74\040\x74\x68\x65\040\x6f\x6c\x64\040\x6c\x69\x67\x68\x74\x68\x6f\x75\x73\x65\040\x61\x66\x74\x65\x72\040\x6d\x69\x64\x6e\x69\x67\x68\x74\040\x61\x6e\x64\040\x62\x72\x69\x6e\x67\040\x74\x68\x65\040\x6d\x61\x70\054\040\x74\x68\x65\040\x6b\x65\x79\040\x61\x6e\x64\040\x61\040\x74\x6f\x72\x63\x68\056";

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    // helper for tests: the whole crack result
    fn crack(text: &str) -> CrackResult {
        Decoder::<BackslashEscapeDecoder>::new().crack(text, &get_athena_checker())
    }

    // helper for tests: the decoded candidate, if the decoder returned one
    fn decode(text: &str) -> Option<String> {
        crack(text)
            .unencrypted_text
            .and_then(|candidates| candidates.into_iter().next())
    }

    // Cracks `ciphertext` and asserts the checker accepted `plaintext`
    fn assert_cracks_to(ciphertext: &str, plaintext: &str) {
        let result = crack(ciphertext);
        assert_eq!(
            result.unencrypted_text.as_deref(),
            Some(&[plaintext.to_string()][..]),
            "{ciphertext:?}"
        );
        assert!(result.success, "the checker should accept {plaintext:?}");
    }

    // Asserts the decoder rejects `text` without producing a candidate
    fn assert_fails(text: &str) {
        let result = crack(text);
        assert_eq!(result.unencrypted_text, None, "{text:?} should fail");
        assert!(!result.success, "{text:?} should fail");
    }

    #[test]
    fn backslash_escape_decodes_octal_issue_example() {
        // Issue #941. Octal decodes this one too.
        assert_cracks_to(
            r"\150\145\154\154\157\040\167\157\162\154\144",
            "hello world",
        );
    }

    #[test]
    fn backslash_escape_decodes_mixed_issue_example() {
        // Issue #941
        assert_cracks_to(
            r"Line one\nLine two\t\x41\x42\103",
            "Line one\nLine two\tABC",
        );
    }

    #[test]
    fn backslash_escape_decodes_octal_and_hex_mixed() {
        // Neither Octal (no `x`) nor Hexadecimal (odd number of digits) decodes this
        assert_cracks_to(
            r"\110\145\154\154\157\054\040\x57\x6f\x72\x6c\x64\x21",
            "Hello, World!",
        );
    }

    #[test]
    fn backslash_escape_decodes_short_octal() {
        // 1 and 2 digit octal escapes
        assert_cracks_to(
            r"\110\145\154\154\157\54\40\127\157\162\154\144\41",
            "Hello, World!",
        );
    }

    #[test]
    fn backslash_escape_decodes_python_bytes_repr() {
        // Python's repr of the bytes. CyberChef keeps the b'' wrapper.
        assert_cracks_to(
            r"b'Meet me at the old lighthouse\tafter midnight.\n'",
            "Meet me at the old lighthouse\tafter midnight.\n",
        );
    }

    #[test]
    fn backslash_escape_decodes_bench_input() {
        assert_cracks_to(LIGHTHOUSE_ESCAPED, LIGHTHOUSE);
    }

    #[test]
    fn backslash_escape_decodes_escapes_mixed_with_letters() {
        // Athena does not accept the pangram as plaintext, so check the candidate itself
        assert_eq!(
            decode(r"\123\x70h\151\x6ex\040\x6ff\040\x62l\141\x63k\040\x71u\141\x72t\172\x2c \152\x75d\147\x65 \155\x79 \166\x6fw\056").as_deref(),
            Some("Sphinx of black quartz, judge my vow.")
        );
    }

    #[test]
    fn backslash_escape_reads_bytes_as_utf8() {
        // Athena does not accept "café ☕" as plaintext, so check the candidate itself.
        // CyberChef keeps the b'' wrapper.
        assert_eq!(
            decode(r"b'caf\xc3\xa9 \xe2\x98\x95'").as_deref(), // codespell:ignore caf
            Some("café ☕")
        );
    }

    #[test]
    fn backslash_escape_falls_back_to_latin1() {
        // 0xFF is not UTF-8 on its own
        assert_eq!(decode(r"\xff").as_deref(), Some("ÿ"));
        assert_eq!(decode(r"\377").as_deref(), Some("ÿ"));
        // One byte that isn't UTF-8 makes the whole text Latin-1, literal text included, so
        // the UTF-8 bytes of é become "Ã©". CyberChef works on characters and gives "éÿ";
        // a Python bytes literal can't hold é.
        assert_eq!(decode(r"é\xff").as_deref(), Some("Ã©ÿ"));
    }

    #[test]
    fn backslash_escape_keeps_non_ascii_text_around_escapes() {
        // CyberChef agrees. Python only takes ASCII in a bytes literal.
        assert_eq!(decode(r"日本\x41é").as_deref(), Some("日本Aé"));
    }

    #[test]
    fn backslash_escape_decodes_quotes_and_keeps_escaped_slashes() {
        // \/ is not an escape in C or Python, so it stays. CyberChef agrees.
        assert_eq!(
            decode(r#"He said \"hi\" and left.\nhttp:\/\/example.com"#).as_deref(),
            Some("He said \"hi\" and left.\nhttp:\\/\\/example.com")
        );
    }

    #[test]
    fn backslash_escape_decodes_single_character_escapes() {
        assert_eq!(
            decode(r#"a\\b\'c\"d\ne\rf\tg"#).as_deref(),
            Some("a\\b'c\"d\ne\rf\tg")
        );
    }

    #[test]
    fn backslash_escape_accepts_upper_and_lower_case_hex() {
        assert_eq!(decode(r"\x4D\x4d\x4e\x4E").as_deref(), Some("MMNN"));
    }

    #[test]
    fn backslash_escape_octal_takes_at_most_two_digits_after_4_to_7() {
        // CyberChef and JavaScript agree. Python reads three digits and wraps \400 around
        // to \x00.
        assert_eq!(decode(r"\400").as_deref(), Some(" 0"));
        assert_eq!(decode(r"\777").as_deref(), Some("?7"));
        assert_eq!(decode(r"\608").as_deref(), Some("08"));
        // A first digit of 0 to 3 takes three, and no more
        assert_eq!(decode(r"\1011").as_deref(), Some("A1"));
        assert_eq!(decode(r"\1234").as_deref(), Some("S4"));
        // \x takes exactly two hex digits
        assert_eq!(decode(r"\x414").as_deref(), Some("A4"));
    }

    #[test]
    fn backslash_escape_copies_other_backslashes_unchanged() {
        // CyberChef agrees. Python rejects \x without two hex digits and keeps the others.
        assert_eq!(
            decode(r"\x41 \e \/ \8 \q \x4g \x \N{DASH}").as_deref(),
            Some(r"A \e \/ \8 \q \x4g \x \N{DASH}")
        );
    }

    #[test]
    fn backslash_escape_leaves_unicode_escapes_to_their_own_decoder() {
        // Deliberately unlike CyberChef, which gives "AB" and reads \u{41} too: the Unicode
        // Escapes decoder reads \u, so the search finds "AB" one step later instead of
        // twice. Python bytes literals don't read \u or \U either.
        assert_eq!(decode(r"\u0041\x42").as_deref(), Some(r"\u0041B"));
        assert_eq!(decode(r"\\u0041").as_deref(), Some(r"\u0041"));
        assert_eq!(
            decode(r"\U00000041\u{41}\x43").as_deref(),
            Some(r"\U00000041\u{41}C")
        );
    }

    #[test]
    fn backslash_escape_decodes_an_escaped_backslash_once() {
        // `\\n` is a backslash and an `n`, not a line feed
        assert_eq!(decode(r"\\n").as_deref(), Some(r"\n"));
        // An escaped backslash, then a trailing one that is copied. CyberChef agrees; Python
        // rejects a trailing backslash.
        assert_eq!(decode(r"\\\").as_deref(), Some(r"\\"));
        // Double escaping takes two passes, which the search does
        assert_eq!(decode(r"\\x41\\x42\\x43").as_deref(), Some(r"\x41\x42\x43"));
        assert_eq!(decode(r"\x41\x42\x43").as_deref(), Some("ABC"));
    }

    #[test]
    fn backslash_escape_decodes_windows_paths_like_python() {
        // \n is a line feed and \U is not an escape; the checker decides
        assert_eq!(decode(r"C:\Users\new").as_deref(), Some("C:\\Users\new"));
    }

    #[test]
    fn backslash_escape_drops_trailing_nul() {
        // The terminator of a C string. Python and CyberChef keep the NUL.
        assert_eq!(decode(r"hello world\0").as_deref(), Some("hello world"));
        assert_eq!(decode(r"\x41\x42\x43\0\x00\000").as_deref(), Some("ABC"));
    }

    #[test]
    fn backslash_escape_strips_quotes_around_the_literal() {
        // Python reads each of these as one literal. CyberChef keeps the quotes and the b.
        for text in [
            r"b'\x41\x42\x43'",
            r#"b"\x41\x42\x43""#,
            r"B'\x41\x42\x43'",
            r#"B"\x41\x42\x43""#,
            r"'\x41\x42\x43'",
            r#""\x41\x42\x43""#,
            " b'\\x41\\x42\\x43'\n",
        ] {
            assert_eq!(decode(text).as_deref(), Some("ABC"), "{text:?}");
        }
        // Escaped quotes inside the literal
        assert_eq!(decode(r"b'it\'s'").as_deref(), Some("it's"));
        assert_eq!(decode(r#"b"it's \x41""#).as_deref(), Some("it's A"));
    }

    #[test]
    fn backslash_escape_keeps_unmatched_quotes() {
        // CyberChef agrees. These are not Python literals.
        for (text, expected) in [
            (r"'abc\x41", r"'abcA"),
            (r"abc\x41'", r"abcA'"),
            (r#"'abc\x41""#, r#"'abcA""#),
            (r"b'abc\x41", r"b'abcA"),
            (r"x'abc\x41'", r"x'abcA'"),
        ] {
            assert_eq!(decode(text).as_deref(), Some(expected), "{text:?}");
        }
    }

    #[test]
    fn backslash_escape_keeps_whitespace_outside_a_literal() {
        assert_eq!(decode(" \\x41 \n").as_deref(), Some(" A \n"));
    }

    #[test]
    fn backslash_escape_fails_on_plan_vectors() {
        // The `fail:` vectors in the implementation plan
        for text in [
            "",
            "😀",
            "hello world",
            r"\u0041",
            r"\q",
            r"\e",
            r"abc\",
            r"C:\Users",
            r"tab\vff\f",
            r"a\x00b",
            "150 145 154 154 157",
            r"\u0043\u0061\u0066\u00E9",
            "48656c6c6f",
            // benches/data/decoders.toml `miss`
            "T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV",
        ] {
            assert_fails(text);
        }
    }

    #[test]
    fn backslash_escape_fails_without_a_well_formed_escape() {
        for text in [
            r"\",
            r"\x",
            r"\x4",
            r"\x4g",
            r"\xg4",
            r"\8\9",
            r"\/\/",
            r"\U00000041",
            r"\u{41}",
            r"\N{DASH}",
            // The closing quote is escaped, so nothing is left once the quotes are dropped
            r"'abc\'",
        ] {
            assert_fails(text);
        }
    }

    #[test]
    fn backslash_escape_fails_on_empty_literals() {
        for text in ["b''", "''", r#""""#, r#"b"""#, "B''"] {
            assert_fails(text);
        }
    }

    #[test]
    fn backslash_escape_fails_on_control_characters() {
        for text in [
            // BEL, BS, VT, FF
            r"\a\x41\x42",
            r"\b\x41\x42",
            r"\v\x41\x42",
            r"\f\x41\x42",
            // NUL, other than at the end
            r"\0abc",
            r"a\000bc",
            // ESC, DEL, and C1 controls both as Latin-1 and as UTF-8
            r"\x1b[31mred",
            r"\x7f\x41\x42",
            r"\x85\x41\x42",
            r"\xc2\x85\x41\x42",
        ] {
            assert_fails(text);
        }
    }

    #[test]
    fn backslash_escape_fails_when_only_nul_or_whitespace_is_left() {
        for text in [
            r"\0",
            r"\0\0\0",
            r"\x00",
            r"\040\040\040",
            r"\n\t\r",
            "\\n  \t",
        ] {
            assert_fails(text);
        }
    }

    #[test]
    fn backslash_escape_handles_panics() {
        assert_fails("hello my name is panicky mc panic face!");
    }

    #[test]
    fn backslash_escape_handles_panic_if_empty_string() {
        assert_fails("");
    }

    #[test]
    fn backslash_escape_handles_panic_if_emoji() {
        assert_fails("😀");
        assert_fails(r"😀\");
        // CyberChef agrees; a Python bytes literal can't hold 😀
        assert_eq!(decode(r"😀\x41").as_deref(), Some("😀A"));
    }

    #[test]
    fn backslash_escape_pre_check_agrees_with_decoding() {
        // Every text of 1 to 5 characters over an alphabet of escape parts: the cheap
        // check passes exactly when decoding replaces something
        let alphabet = ['\\', 'x', '4', '1', 'g', 'n', 'u', '8', 'é'];
        let mut texts = vec![String::new()];
        for _ in 0..5 {
            texts = texts
                .iter()
                .flat_map(|text| alphabet.iter().map(move |c| format!("{text}{c}")))
                .collect();
            for text in &texts {
                assert_eq!(
                    has_escape(text),
                    decode_escapes(text.as_bytes()).is_some(),
                    "{text:?}"
                );
            }
        }
    }

    #[test]
    fn backslash_escape_is_registered() {
        let decoders = get_decoder_by_name("Backslash Escapes");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Backslash Escapes");

        // Cached results find their decoder by name
        let decoder = DECODER_MAP
            .get("Backslash Escapes")
            .expect("Backslash Escapes should be in DECODER_MAP")
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "Backslash Escapes");
        assert_eq!(decoder.get_popularity(), 0.5);
    }

    #[test]
    fn backslash_escape_crack_result_round_trips_through_json() {
        // The cache stores paths as JSON and finds the decoder again through DECODER_MAP
        let decoder = Decoder::<BackslashEscapeDecoder>::new();
        let json = CrackResult::new(&decoder, r"\x41".to_string())
            .get_json()
            .unwrap();
        let crack_result: CrackResult = serde_json::from_str(&json).unwrap();
        assert_eq!(crack_result.decoder, "Backslash Escapes");
        assert_eq!(crack_result.link, decoder.link);
    }
}
