//! Decode Bacon's cipher, also called the Baconian cipher.
//!
//! Each letter is written as a group of five binary symbols, traditionally `A` and `B`.
//! Read as a binary number (`A` = 0, `B` = 1), a group is the letter's index in one of
//! two alphabets:
//!
//! * standard: Bacon's original 24 letters, where I and J share a code, as do U and V,
//! * complete: all 26 letters, one code each.
//!
//! The two symbols can be any pair of characters (`A`/`B`, `a`/`b`, `0`/`1`, ...). They
//! are also often hidden in a cover text, one symbol per letter: lowercase for `A` and
//! uppercase for `B`.
//!
//! The decoder tries both alphabets and both ways of assigning the two symbols, so at
//! most 4 readings per mode, and checks the likeliest first (see `rank_candidates`):
//!
//! * Symbol mode: the input is exactly two distinct symbols in groups of five, with or
//!   without whitespace between groups. A whitespace-separated token longer than one
//!   group is a word, so a message written word by word keeps its spaces.
//! * Case mode: the input looks like a cover text, with the case changing inside words
//!   far more often than in ordinary writing. The case of ordinary text decodes to
//!   junk, so only a candidate the checker accepts is returned.
//!
//! References: <https://en.wikipedia.org/wiki/Bacon%27s_cipher>,
//! <https://www.dcode.fr/bacon-cipher> and CyberChef's "Bacon Cipher Decode".

use crate::checkers::checker_type::{Check, Checker};
use crate::checkers::english::EnglishChecker;
use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, trace};
use std::cmp::Reverse;

/// Symbols per letter.
const GROUP_LEN: usize = 5;

/// The largest code a group can hold, `BBBBB`. Swapping `A` and `B` turns code `c`
/// into `MAX_CODE - c`.
const MAX_CODE: u8 = (1 << GROUP_LEN) - 1;

/// The fewest letters a message needs to be worth decoding. Anything shorter is too
/// easily mistaken for a word.
const MIN_LETTERS: usize = 3;

/// Bacon's 24-letter alphabet: I and J share a code, as do U and V.
const STANDARD_ALPHABET: &[u8] = b"ABCDEFGHIKLMNOPQRSTUWXYZ";

/// The 26-letter alphabet, with a code for every letter.
const COMPLETE_ALPHABET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZ";

/// Both alphabets, with the names used in `CrackResult::key`. Readings are listed in
/// this order, which breaks ties when they are ranked.
const ALPHABETS: [(&str, &[u8]); 2] = [
    ("standard", STANDARD_ALPHABET),
    ("complete", COMPLETE_ALPHABET),
];

/// Case mode only: the fewest ASCII letters a cover text needs, enough for 5 letters.
const COVER_MIN_LETTERS: usize = 25;

/// Case mode only: the smallest share of the non-whitespace characters that must be
/// letters, in percent.
const COVER_MIN_LETTER_PERCENT: usize = 70;

/// Case mode only: the smallest share of letters that must be case flips, in percent.
/// A flip is a letter whose case differs from the letter before it in the same word,
/// except for the second letter of a capitalised word.
const COVER_MIN_FLIP_PERCENT: usize = 15;

/// Case mode only: the longest a cover text's words can be on average, in letters.
/// This keeps out encodings with mixed case and line breaks, such as wrapped Base64.
const COVER_MAX_AVERAGE_WORD_LEN: usize = 12;

/// The Baconian decoder, call:
/// `let baconian_decoder = Decoder::<BaconianDecoder>::new()` to create a new instance
/// And then call:
/// `result = baconian_decoder.crack(input)` to decode Bacon's cipher
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::baconian_decoder::BaconianDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_baconian = Decoder::<BaconianDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_baconian.crack("AABBB AABAA ABABA ABABA ABBAB", &checker);
/// assert!(result.success);
/// assert_eq!(result.unencrypted_text.unwrap()[0], "HELLO");
/// // The alphabet and which symbol stood for A and which for B
/// assert_eq!(result.key.unwrap(), "standard, A=A B=B");
/// ```
pub struct BaconianDecoder;

impl Crack for Decoder<BaconianDecoder> {
    fn new() -> Decoder<BaconianDecoder> {
        Decoder {
            name: "Baconian",
            description: "Bacon's cipher or the Baconian cipher is a method of steganographic message encoding devised by Francis Bacon in 1605. Each letter is written as a group of five binary symbols, A and B, using Bacon's 24-letter alphabet (I=J, U=V) or the full 26-letter one. The two symbols can be any pair of characters, or hidden in the letter case of a cover text.",
            link: "https://en.wikipedia.org/wiki/Bacon%27s_cipher",
            tags: vec!["baconian", "bacon", "substitution", "classic", "decoder"],
            popularity: 0.4,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes symbol mode first. If the input isn't two symbols in groups of five, tries
    /// case mode, which only returns a candidate the checker identifies.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Baconian with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let mut candidates = symbol_mode_candidates(text);
        let symbol_mode = !candidates.is_empty();
        if !symbol_mode {
            candidates = case_mode_candidates(text);
        }
        rank_candidates(&mut candidates);

        for candidate in &candidates {
            if !check_string_success(&candidate.text, text) {
                continue;
            }
            let checker_result = checker.check(&candidate.text);
            // If checkers return true, exit early with the correct result
            if checker_result.is_identified {
                trace!("Found a match with Baconian variant {}", candidate.key);
                results.unencrypted_text = Some(vec![candidate.text.clone()]);
                results.update_checker(&checker_result);
                results.key = Some(candidate.key.clone());
                return results;
            }
        }

        // Nothing was identified as plaintext. Symbol-mode decodings go to the search to
        // try; case-mode ones are almost always junk, so they are dropped.
        if symbol_mode {
            results.unencrypted_text = Some(candidates.into_iter().map(|c| c.text).collect());
        } else {
            debug!("Failed to decode Baconian: no reading was identified as plaintext");
        }
        results
    }
    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// One way of reading the input, and what it decodes to.
#[derive(Debug)]
struct Candidate {
    /// The decoded letters.
    text: String,
    /// The alphabet and the symbol assignment, such as `standard, A=A B=B`.
    key: String,
}

/// Symbol mode: decodes `text` as two symbols in groups of five.
///
/// Returns nothing unless the whole input is exactly two distinct non-whitespace
/// characters, at least `MIN_LETTERS` groups of them, with every whitespace-separated
/// token a whole number of groups. Almost every input fails this within its first few
/// characters. Otherwise it returns every valid decoding: up to 2 alphabets × 2
/// assignments of the symbols, without duplicates.
fn symbol_mode_candidates(text: &str) -> Vec<Candidate> {
    let Some(scan) = scan_symbols(text) else {
        return Vec::new();
    };
    let [a_symbol, b_symbol] = scan.symbols;
    let tokens: Vec<Vec<u8>> = text
        .split_whitespace()
        .map(|token| to_codes(token.chars().map(|c| c == b_symbol)))
        .collect();
    let separator = if scan.words { " " } else { "" };
    let names = [a_symbol.to_string(), b_symbol.to_string()];
    decode_variants(&tokens, separator, [&names[0], &names[1]])
}

/// What [`scan_symbols`] learnt about an input that is two symbols in groups of five.
struct SymbolScan {
    /// The two symbols. The first one stands for `A` in the first assignment tried.
    symbols: [char; 2],
    /// Whether a whitespace-separated token is longer than one group, which makes every
    /// token a word.
    words: bool,
}

/// The symbol-mode pre-check, one pass that stops at the first character that rules the
/// input out. See [`symbol_mode_candidates`].
fn scan_symbols(text: &str) -> Option<SymbolScan> {
    let mut first: Option<char> = None;
    let mut second: Option<char> = None;
    let mut symbol_count = 0;
    let mut token_len = 0;
    let mut words = false;
    // The extra space ends the last token, so it is checked like the others.
    for c in text.chars().chain(std::iter::once(' ')) {
        if c.is_whitespace() {
            if token_len % GROUP_LEN != 0 {
                return None;
            }
            words |= token_len > GROUP_LEN;
            token_len = 0;
            continue;
        }
        if first != Some(c) && second != Some(c) {
            if first.is_none() {
                first = Some(c);
            } else if second.is_none() {
                second = Some(c);
            } else {
                return None;
            }
        }
        token_len += 1;
        symbol_count += 1;
    }
    let (Some(first), Some(second)) = (first, second) else {
        return None;
    };
    if symbol_count < MIN_LETTERS * GROUP_LEN {
        return None;
    }
    // Sorting puts the A first for A/B, a/b and 0/1. Both ways round are tried anyway;
    // this only decides which is tried first.
    let symbols = if first < second {
        [first, second]
    } else {
        [second, first]
    };
    Some(SymbolScan { symbols, words })
}

/// Case mode: decodes the letter case of `text`, lowercase as `A` and uppercase as `B`
/// or the other way round.
///
/// Returns nothing unless `text` looks like a cover text (see
/// [`looks_like_cover_text`]). Letters past the last complete group are ignored, and so
/// are trailing groups that are all lowercase: a cover text longer than the message is
/// written normally after it.
fn case_mode_candidates(text: &str) -> Vec<Candidate> {
    if !looks_like_cover_text(text) {
        return Vec::new();
    }
    let mut codes = to_codes(
        text.chars()
            .filter(char::is_ascii_alphabetic)
            .map(|c| c.is_ascii_uppercase()),
    );
    while codes.last() == Some(&0) {
        codes.pop();
    }
    if codes.len() < MIN_LETTERS {
        return Vec::new();
    }
    decode_variants(&[codes], "", ["lowercase", "uppercase"])
}

/// Whether `text` looks like a cover text with a message hidden in its letter case.
///
/// It needs at least `COVER_MIN_LETTERS` ASCII letters, to be mostly letters, to have
/// words of a normal length (so it contains whitespace), and to flip case inside its
/// words far more often than ordinary writing does. Capitalised and all-caps words have
/// no flips, so ordinary text fails, as does Base64, which has no spaces or very long
/// words.
fn looks_like_cover_text(text: &str) -> bool {
    let mut words = 0;
    let mut non_whitespace = 0;
    let mut letters = 0;
    let mut flips = 0;
    let mut in_word = false;
    // The case of the previous character if it was a letter, and how many letters in a
    // row have been seen.
    let mut previous_upper: Option<bool> = None;
    let mut run = 0;
    for c in text.chars() {
        if c.is_whitespace() {
            in_word = false;
            previous_upper = None;
            run = 0;
            continue;
        }
        if !in_word {
            in_word = true;
            words += 1;
        }
        non_whitespace += 1;
        if !c.is_ascii_alphabetic() {
            previous_upper = None;
            run = 0;
            continue;
        }
        letters += 1;
        let upper = c.is_ascii_uppercase();
        if let Some(previous) = previous_upper {
            // "Hello": an uppercase first letter followed by lowercase is normal.
            let capitalised = run == 1 && previous && !upper;
            if previous != upper && !capitalised {
                flips += 1;
            }
        }
        previous_upper = Some(upper);
        run += 1;
    }
    letters >= COVER_MIN_LETTERS
        && letters * 100 >= non_whitespace * COVER_MIN_LETTER_PERCENT
        && flips * 100 >= letters * COVER_MIN_FLIP_PERCENT
        && letters <= words * COVER_MAX_AVERAGE_WORD_LEN
}

/// Orders readings so the likeliest plaintext is checked first.
///
/// A message usually decodes with both alphabets, and as the checker's first hit wins,
/// a near-English misreading checked first can beat the real message: `HELLO` written
/// with the Complete alphabet reads as `HEMMP` with the Standard one, and a lenient
/// English check accepts misreadings such as `FAUHES YPSL MEFU FAS EACH` (for
/// `FATHER WORK LEFT FAR EACH`). So readings a strict English check accepts come first,
/// then the rest by how common their letters are in English.
fn rank_candidates(candidates: &mut [Candidate]) {
    if candidates.len() < 2 {
        return;
    }
    let strict = Checker::<EnglishChecker>::new().with_sensitivity(Sensitivity::Low);
    candidates.sort_by_cached_key(|candidate| {
        (
            !strict.check(&candidate.text).is_identified,
            Reverse(letter_score(&candidate.text)),
        )
    });
}

/// English letter frequencies in percent, A to Z: Lewand's table for running text, from
/// <https://en.wikipedia.org/wiki/Letter_frequency>.
const ENGLISH_LETTER_PERCENT: [f64; 26] = [
    8.2, 1.5, 2.8, 4.3, 12.7, 2.2, 2.0, 6.1, 7.0, 0.15, 0.77, 4.0, 2.4, 6.7, 7.5, 1.9, 0.095, 6.0,
    6.3, 9.1, 2.8, 0.98, 2.4, 0.15, 2.0, 0.074,
];

/// How English the letters of `text` look: the log-likelihood of its uppercase letters
/// under English letter frequencies, in thousandths. Higher is more English. Only
/// comparable between texts with the same number of letters, which all readings of one
/// input have.
fn letter_score(text: &str) -> i64 {
    let log_likelihood: f64 = text
        .bytes()
        .filter(u8::is_ascii_uppercase)
        .map(|letter| ENGLISH_LETTER_PERCENT[usize::from(letter - b'A')].ln())
        .sum();
    (log_likelihood * 1000.0).round() as i64
}

/// Packs bits (`true` for `B`) into five-bit codes, dropping an incomplete final group.
fn to_codes(bits: impl Iterator<Item = bool>) -> Vec<u8> {
    let bits: Vec<bool> = bits.collect();
    let (groups, _incomplete) = bits.as_chunks::<GROUP_LEN>();
    groups
        .iter()
        .map(|group| {
            group
                .iter()
                .fold(0, |code, &bit| (code << 1) | u8::from(bit))
        })
        .collect()
}

/// Decodes `tokens` (the codes of each token, with `names[0]` read as `A`) with both
/// alphabets and both assignments of the two symbols, joining tokens with `separator`.
/// Skips any reading with a code past the end of its alphabet, and duplicates.
fn decode_variants(tokens: &[Vec<u8>], separator: &str, names: [&str; 2]) -> Vec<Candidate> {
    let [a, b] = names;
    let mut candidates: Vec<Candidate> = Vec::new();
    for (swapped, a_name, b_name) in [(false, a, b), (true, b, a)] {
        for (alphabet_name, alphabet) in ALPHABETS {
            let Some(words) = tokens
                .iter()
                .map(|codes| to_letters(codes, alphabet, swapped))
                .collect::<Option<Vec<String>>>()
            else {
                continue;
            };
            let text = words.join(separator);
            if candidates.iter().any(|candidate| candidate.text == text) {
                continue;
            }
            candidates.push(Candidate {
                text,
                key: format!("{alphabet_name}, {a_name}=A {b_name}=B"),
            });
        }
    }
    candidates
}

/// The letters `codes` stand for in `alphabet`, or `None` if a code is past its end.
/// With `swapped`, `A` and `B` are swapped first.
fn to_letters(codes: &[u8], alphabet: &[u8], swapped: bool) -> Option<String> {
    codes
        .iter()
        .map(|&code| {
            let code = if swapped { MAX_CODE - code } else { code };
            alphabet
                .get(usize::from(code))
                .map(|&letter| char::from(letter))
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::athena::Athena;

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    /// Runs the decoder with the Athena checker
    fn crack(text: &str) -> CrackResult {
        Decoder::<BaconianDecoder>::new().crack(text, &get_athena_checker())
    }

    /// Asserts the decoder identifies `text` as `plaintext` with the variant `key`
    fn assert_cracks(text: &str, plaintext: &str, key: &str) {
        let result = crack(text);
        assert!(result.success, "{text:?} was not cracked: {result:?}");
        assert_eq!(result.unencrypted_text, Some(vec![plaintext.to_string()]));
        assert_eq!(result.key.as_deref(), Some(key));
        assert!(!result.checker_name.is_empty());
    }

    /// The candidate texts symbol mode produces, in order
    fn symbol_texts(text: &str) -> Vec<String> {
        symbol_mode_candidates(text)
            .into_iter()
            .map(|c| c.text)
            .collect()
    }

    // The ciphertexts below were made with CyberChef's "Bacon Cipher Encode" and
    // decode back to the same text with its "Bacon Cipher Decode"
    // (https://gchq.github.io/CyberChef/). "Standard" is its "Standard (I=J and U=V)"
    // alphabet, "inverted" its "Invert Translation" option.

    /// HELLO, Standard alphabet, A/B. The example in issue #996.
    const HELLO_STANDARD: &str = "AABBB AABAA ABABA ABABA ABBAB";
    /// HELLO, Complete alphabet, A/B.
    const HELLO_COMPLETE: &str = "AABBB AABAA ABABB ABABB ABBBA";
    /// ITWASTHEBESTOFTIMES, Standard, A/B.
    const BEST_OF_TIMES_STANDARD: &str = "ABAAA BAABA BABAA AAAAA BAAAB BAABA AABBB AABAA AAAAB AABAA BAAAB BAABA ABBAB AABAB BAABA ABAAA ABABB AABAA BAAAB";
    /// ITWASTHEBESTOFTIMES, Standard, 0/1, inverted.
    const BEST_OF_TIMES_INVERTED_01: &str = "10111 01101 01011 11111 01110 01101 11000 11011 11110 11011 01110 01101 10010 11010 01101 10111 10100 11011 01110";
    /// ITWASTHEBESTOFTIMES, Complete, A/B.
    const BEST_OF_TIMES_COMPLETE: &str = "ABAAA BAABB BABBA AAAAA BAABA BAABB AABBB AABAA AAAAB AABAA BAABA BAABB ABBBA AABAB BAABB ABAAA ABBAA AABAA BAABA";
    /// HELLO hidden in the case of a cover text, lowercase = A, uppercase = B, Complete
    /// alphabet. The letter-case example in issue #996. CyberChef's decoder, with the
    /// "Case" translation, reads it as HELLOAA: the last 10 letters are padding.
    const HELLO_IN_CASE: &str = "thE QUicK broWn FOx JuMPs OVEr the lazy dog";

    #[test]
    fn decodes_standard_alphabet() {
        assert_cracks(HELLO_STANDARD, "HELLO", "standard, A=A B=B");
    }

    #[test]
    fn decodes_complete_alphabet() {
        assert_cracks(HELLO_COMPLETE, "HELLO", "complete, A=A B=B");
        // CyberChef's Standard decode of the same input
        assert_eq!(symbol_texts(HELLO_COMPLETE)[0], "HEMMP");
    }

    #[test]
    fn decodes_unspaced_groups() {
        assert_cracks("AABBBAABAAABABAABABAABBAB", "HELLO", "standard, A=A B=B");
    }

    #[test]
    fn decodes_zeros_and_ones() {
        assert_cracks(
            "00111 00100 01010 01010 01101",
            "HELLO",
            "standard, 0=A 1=B",
        );
    }

    #[test]
    fn decodes_lowercase_symbols() {
        assert_cracks(
            "aabbb aabaa ababa ababa abbab",
            "HELLO",
            "standard, a=A b=B",
        );
    }

    #[test]
    fn decodes_any_pair_of_symbols() {
        // HELLO_STANDARD with A as 🥓 and B as 🍳: multi-byte symbols are compared as chars
        assert_cracks(
            "🥓🥓🍳🍳🍳 🥓🥓🍳🥓🥓 🥓🍳🥓🍳🥓 🥓🍳🥓🍳🥓 🥓🍳🍳🥓🍳",
            "HELLO",
            "standard, 🥓=A 🍳=B",
        );
    }

    #[test]
    fn decodes_inverted_symbols() {
        // CyberChef: HELLO, Standard, A/B, inverted
        assert_cracks(
            "BBAAA BBABB BABAB BABAB BAABA",
            "HELLO",
            "standard, B=A A=B",
        );
    }

    #[test]
    fn decodes_longer_message() {
        assert_cracks(
            BEST_OF_TIMES_STANDARD,
            "ITWASTHEBESTOFTIMES",
            "standard, A=A B=B",
        );
    }

    #[test]
    fn decodes_longer_message_inverted_zeros_and_ones() {
        assert_cracks(
            BEST_OF_TIMES_INVERTED_01,
            "ITWASTHEBESTOFTIMES",
            "standard, 1=A 0=B",
        );
    }

    #[test]
    fn decodes_longer_message_complete_alphabet() {
        assert_cracks(
            BEST_OF_TIMES_COMPLETE,
            "ITWASTHEBESTOFTIMES",
            "complete, A=A B=B",
        );
    }

    #[test]
    fn decodes_word_by_word() {
        // CyberChef with "Keep extra characters" on encodes each word separately, so
        // the space survives. HELLOWORLD without it isn't identified as plaintext.
        assert_cracks(
            "AABBBAABAAABABAABABAABBAB BABAAABBABBAAAAABABAAAABB",
            "HELLO WORLD",
            "standard, A=A B=B",
        );
        // One-letter words are a single group
        assert_eq!(
            symbol_texts("ABAAA AAAAAABABB AABBBAABAABAAAAAABAA")[0],
            "I AM HERE"
        );
    }

    #[test]
    fn standard_alphabet_merges_i_j_and_u_v() {
        // CyberChef: JULIUS, Standard, A/B
        assert_eq!(
            symbol_texts("ABAAA BAABB ABABA ABAAA BAABB BAAAB")[0],
            "IULIUS"
        );
    }

    #[test]
    fn returns_every_valid_reading_when_none_is_identified() {
        let candidates = symbol_mode_candidates(HELLO_COMPLETE);
        let readings: Vec<(&str, &str)> = candidates
            .iter()
            .map(|c| (c.text.as_str(), c.key.as_str()))
            .collect();
        // Swapped, AABAA becomes BBABB (27), which is past the end of both alphabets
        assert_eq!(
            readings,
            [
                ("HEMMP", "standard, A=A B=B"),
                ("HELLO", "complete, A=A B=B")
            ]
        );
    }

    #[test]
    fn identical_readings_are_returned_once() {
        // A to H have the same codes in both alphabets
        assert_eq!(symbol_texts("AAAAA AAAAB AAABA"), ["ABC"]);
    }

    #[test]
    fn likelier_reading_is_checked_first() {
        // CyberChef: Complete alphabet, A/B, "Keep extra characters". The Standard
        // reading, FAUHES YPSL MEFU FAS EACH, is tried first and the default checker
        // accepts it, so without ranking it was returned instead.
        assert_cracks(
            "AABABAAAAABAABBAABBBAABAABAAAB BABBAABBBABAAABABABA ABABBAABAAAABABBAABB AABABAAAAABAAAB AABAAAAAAAAAABAAABBB",
            "FATHER WORK LEFT FAR EACH",
            "complete, A=A B=B",
        );
        // Likewise UHESE GSEAU
        assert_cracks(
            "BAABBAABBBAABAABAAABAABAA AABBABAAABAABAAAAAAABAABB",
            "THERE GREAT",
            "complete, A=A B=B",
        );
    }

    #[test]
    fn letter_score_prefers_common_letters() {
        assert!(letter_score("HELLO") > letter_score("HEMMP"));
        assert!(letter_score("THERE GREAT") > letter_score("UHESE GSEAU"));
        assert_eq!(letter_score(""), 0);
    }

    #[test]
    fn decodes_letter_case() {
        assert_cracks(HELLO_IN_CASE, "HELLO", "complete, lowercase=A uppercase=B");
        let candidates: Vec<String> = case_mode_candidates(HELLO_IN_CASE)
            .into_iter()
            .map(|c| c.text)
            .collect();
        // CyberChef's Standard reading is HEMMPAA. Swapped, the padding would be
        // BBBBB, which is why it is dropped before swapping.
        assert_eq!(candidates, ["HEMMP", "HELLO"]);
    }

    #[test]
    fn decodes_letter_case_with_uppercase_as_a() {
        // HELLO_IN_CASE's message the other way round: uppercase = A, lowercase = B.
        // CyberChef reads it as HELLO?? with the Case translation and Invert Translation.
        assert_cracks(
            "THe quICk BROwN foX jUmpS oveR the lazy dog",
            "HELLO",
            "complete, uppercase=A lowercase=B",
        );
    }

    #[test]
    fn symbol_mode_rejects_invalid_input() {
        for text in [
            "",
            " \n\t ",
            // One symbol
            "BBBBB BBBBB BBBBB",
            // Three symbols
            "ABCAB AAAAA BBBBB",
            // Not a whole group
            "AABB",
            "AABBB AABA",
            "AABBB AABAA ABABA ABABA ABBA",
            // Fewer than 3 groups
            "AABBB AABAA",
            // A token that isn't a whole number of groups, though the total is
            "AABBBA ABAAA BABAA BABAA BBAB",
            // 8-bit binary
            "01101000 01100101 01101100 01101100 01101111",
            "😀",
            "The quick brown fox jumps over the lazy dog",
        ] {
            assert!(
                scan_symbols(text).is_none(),
                "{text:?} passed the pre-check"
            );
            assert!(symbol_mode_candidates(text).is_empty(), "{text:?}");
        }
    }

    #[test]
    fn invalid_input_is_not_cracked() {
        for text in [
            "",
            "😀",
            "BBBBB BBBBB BBBBB",
            "ABCAB AAAAA BBBBB",
            "AABB",
            "AABBB AABA",
            "The quick brown fox jumps over the lazy dog",
            "Hello World, this is NASA calling from the iPhone of McDonald",
            "aGVsbG8gdGhlcmUgZ2VuZXJhbA==",
        ] {
            let result = crack(text);
            assert!(!result.success, "{text:?}: {result:?}");
            assert!(result.unencrypted_text.is_none(), "{text:?}: {result:?}");
        }
    }

    #[test]
    fn junk_symbol_readings_are_candidates_but_not_plaintext() {
        // Morse digits are two symbols in groups of five too
        let result = crack(".---- ..--- ...-- ....- .....");
        assert!(!result.success);
        let candidates = result.unencrypted_text.expect("expected candidates");
        assert!(!candidates.is_empty() && candidates.len() <= 4);
    }

    #[test]
    fn cover_text_gate() {
        assert!(looks_like_cover_text(HELLO_IN_CASE));
        assert!(looks_like_cover_text(
            "THe quICk BROwN foX jUmpS oveR the lazy dog"
        ));
        for text in [
            "The quick brown fox jumps over the lazy dog",
            "THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG",
            "Hello World, this is NASA calling from the iPhone of McDonald",
            "The Quick Brown Fox Jumps Over The Lazy Dog",
            // Base64 and a JWT: no whitespace, or lines far longer than words
            "VGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZw==",
            "VGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVy\nIHRoZSBsYXp5IGRvZyBhbmQgdGhlIHF1aWNrIGJy",
            "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIn0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
            // Too few letters
            "thE QUicK broWn",
            // Mostly not letters
            "t1h2E3 Q4U5i6c7K8 b9r0o1W2n3 F4O5x6 J7u8M9P0s1 O2V3E4r5 t6h7e8",
            "",
            "😀",
        ] {
            assert!(!looks_like_cover_text(text), "{text:?} passed the gate");
            assert!(case_mode_candidates(text).is_empty(), "{text:?}");
        }
    }

    #[test]
    fn case_mode_needs_three_letters_of_message() {
        // Two letters (01010 and 10101) and 15 letters of lowercase padding
        let text = "hElLo WoRlD and some more text";
        assert!(looks_like_cover_text(text));
        assert!(case_mode_candidates(text).is_empty());
    }

    #[test]
    fn case_mode_only_returns_identified_plaintext() {
        // Mixed case that passes the gate but hides nothing
        let text = "xKcd PLoW zuRb qEEn tIVo mAPz YorK gLiB";
        assert!(looks_like_cover_text(text));
        let result = crack(text);
        assert!(!result.success, "{result:?}");
        assert!(result.unencrypted_text.is_none(), "{result:?}");
    }

    #[test]
    fn to_codes_drops_incomplete_group() {
        let bits = "0011100100011".chars().map(|c| c == '1');
        assert_eq!(to_codes(bits), vec![7, 4]);
    }

    #[test]
    fn is_registered() {
        let decoders = crate::filtration_system::get_decoder_by_name("Baconian");
        assert_eq!(decoders.components.len(), 1);
        assert!(crate::decoders::DECODER_MAP.contains_key("Baconian"));
    }
}
