//! Decode Base100 ("base💯"), which writes every byte as one emoji.
//! Performs error handling and returns a string
//! Call base100_decoder.crack to use. It returns a `CrackResult` whose `unencrypted_text` is
//! `None` when the input isn't Base100.
//!
//! Byte `b` is the code point U+1F3F7 + b, so the 256 symbols run from 🏷 (U+1F3F7, byte 0)
//! to 📶 (U+1F4F6, byte 255), with no separators and no padding. Printable ASCII is 🐗
//! (space) to 👵 (`~`). The encoding carries bytes, so the bytes have to be UTF-8 text.
//!
//! References: the reference implementation <https://github.com/AdamNiederer/base100>
//! (`char_to_emoji_scalar` in `src/lib.rs`), PyPI's `pybase100`
//! <https://pypi.org/project/pybase100/> and dCode
//! <https://www.dcode.fr/base100-emoji-encoding>.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The Base100 decoder, call:
/// `let base100_decoder = Decoder::<Base100Decoder>::new()` to create a new instance
/// And then call:
/// `result = base100_decoder.crack(input)` to decode a Base100 string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::base100_decoder::Base100Decoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_base100 = Decoder::<Base100Decoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_base100.crack("👟👜👣👣👦🐗👮👦👩👣👛", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hello world");
/// ```
pub struct Base100Decoder;

/// The code point of byte 0. Byte `b` is `U+1F3F7 + b`.
const FIRST_SYMBOL: u32 = 0x1F3F7;

/// Variation selector-16. Chat clients and editors add it after emoji that have a text
/// form, such as 🏷️ or 🐿️, when the text is copied.
const VARIATION_SELECTOR_16: char = '\u{FE0F}';

impl Crack for Decoder<Base100Decoder> {
    fn new() -> Decoder<Base100Decoder> {
        Decoder {
            name: "Base100",
            description: "Base100 (base💯) writes every byte as one emoji from U+1F3F7 to U+1F4F6.",
            link: "https://github.com/AdamNiederer/base100",
            tags: vec!["base100", "emoji", "decoder", "base"],
            // A novelty encoding, but it is on dCode and turns up in CTFs far more often
            // than Base65536 (0.2)
            popularity: 0.3,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes `text` as Base100 and checks the result with `checker`.
    /// `unencrypted_text` is `None` when `text` isn't Base100 or doesn't decode to text.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Base100 with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(bytes) = decode_base100(text) else {
            debug!("Failed to decode Base100 because the text isn't Base100 emoji");
            return results;
        };

        // Strict UTF-8, not `interface::bytes_to_string`: its Latin-1 fallback would turn
        // any run of 💀…📶 (bytes 0x80 to 0xFF) into text. UTF-8 text such as `Grüße, 世界`
        // still decodes.
        let Ok(decoded_text) = String::from_utf8(bytes) else {
            debug!("Failed to decode Base100 because the bytes aren't UTF-8");
            return results;
        };
        trace!("Decoded text for Base100: {:?}", decoded_text);

        if !is_text(&decoded_text) {
            debug!("Failed to decode Base100 because the bytes are control characters or only whitespace");
            return results;
        }

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Base100 because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Reads Base100 symbols back into bytes, or returns `None` if `text` isn't Base100.
///
/// Leading and trailing whitespace is ignored. U+FE0F after a symbol is skipped; the
/// reference decoder doesn't do this, but the bytes are the same either way. Any other
/// character, including whitespace or a zero-width joiner between symbols, fails.
fn decode_base100(text: &str) -> Option<Vec<u8>> {
    let text = text.trim();
    let mut chars = text.chars();
    // Almost every input fails here, on its first character, before anything is allocated
    let first = symbol_to_byte(chars.next()?)?;

    // Every symbol is 4 bytes of UTF-8
    let mut bytes = Vec::with_capacity(text.len() / 4);
    bytes.push(first);
    for c in chars {
        if let Some(byte) = symbol_to_byte(c) {
            bytes.push(byte);
        } else if c != VARIATION_SELECTOR_16 {
            return None;
        }
    }
    Some(bytes)
}

/// The byte a Base100 symbol stands for, or `None` if `c` isn't one of the 256 symbols.
fn symbol_to_byte(c: char) -> Option<u8> {
    // Below U+1F3F7 the subtraction wraps around to a huge number, and above U+1F4F6 it is
    // 256 or more, so only the 256 symbols fit in a byte
    u8::try_from(u32::from(c).wrapping_sub(FIRST_SYMBOL)).ok()
}

/// Whether decoded bytes are text: no control characters except tabs and line breaks
/// (U+007F and the C1 controls count as control characters), and not only whitespace.
///
/// Emoji that aren't Base100 still decode when every one of them is in the range, and this
/// rejects many of them: 🏷 is NUL, and the skin tone modifiers 🏻 to 🏿 are bytes 4 to 8.
fn is_text(text: &str) -> bool {
    !text.trim().is_empty()
        && !text
            .chars()
            .any(|c| c.is_control() && !matches!(c, '\t' | '\n' | '\r'))
}

#[cfg(test)]
mod tests {
    use super::{decode_base100, Base100Decoder};
    use crate::checkers::athena::Athena;
    use crate::checkers::checker_type::{Check, Checker};
    use crate::checkers::CheckerTypes;
    use crate::decoders::interface::{Crack, Decoder};
    use crate::decoders::{DecoderType, DECODER_MAP};
    use crate::filtration_system::get_decoder_by_name;

    // Unless noted otherwise, every vector here was made with PyPI `pybase100` 0.3.1
    // (`pybase100.encode`), decoded back with `pybase100.decode`, and compared character
    // by character with `chr(0x1F3F7 + b)`, the definition in the reference implementation
    // (https://github.com/AdamNiederer/base100, `char_to_emoji_scalar`).

    /// The bench `medium` plaintext, and the `search.toml` plaintext
    const MEDIUM: &str =
        "Meet me at the old lighthouse after midnight and bring the map, the key and a torch.";

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    // Runs the decoder with the Athena checker and returns the decoded text, if any
    fn crack(text: &str) -> Option<String> {
        let decoder = Decoder::<Base100Decoder>::new();
        let result = decoder.crack(text, &get_athena_checker());
        if result.unencrypted_text.is_none() {
            assert!(!result.success, "{text:?} failed but was marked successful");
        }
        result.unencrypted_text.map(|texts| texts[0].clone())
    }

    // Asserts that Athena accepts what `text` decodes to and returns it
    fn crack_successfully(text: &str) -> String {
        let decoder = Decoder::<Base100Decoder>::new();
        let result = decoder.crack(text, &get_athena_checker());
        assert!(result.success, "Athena should accept {text:?}: {result:?}");
        result.unencrypted_text.unwrap()[0].clone()
    }

    #[test]
    fn decodes_the_issue_example() {
        // https://github.com/bee-san/Ciphey/issues/928
        assert_eq!(crack_successfully("👟👜👣👣👦🐗👮👦👩👣👛"), "hello world");
    }

    #[test]
    fn decodes_the_fox_pangram() {
        assert_eq!(
            crack_successfully("👋👟👜🐗👨👬👠👚👢🐗👙👩👦👮👥🐗👝👦👯🐗👡👬👤👧👪🐗👦👭👜👩🐗👫👟👜🐗👣👘👱👰🐗👛👦👞"),
            "The quick brown fox jumps over the lazy dog"
        );
    }

    #[test]
    fn decodes_a_ctf_flag() {
        let decoder = Decoder::<Base100Decoder>::new();
        let result = decoder.crack(
            "👝👣👘👞👲👙🐫👪🐪👖🐨🐧🐧👖🐨👪👖🐪👤🐧👡🐨👴",
            &get_athena_checker(),
        );
        assert!(result.success, "LemmeKnow should identify the flag");
        assert_eq!(result.checker_name, "LemmeKnow Checker");
        assert_eq!(
            result.unencrypted_text.unwrap()[0],
            "flag{b4s3_100_1s_3m0j1}"
        );
    }

    #[test]
    fn decodes_the_bench_medium_text() {
        // benches/data/decoders.toml, Base100 medium
        assert_eq!(
            crack_successfully("👄👜👜👫🐗👤👜🐗👘👫🐗👫👟👜🐗👦👣👛🐗👣👠👞👟👫👟👦👬👪👜🐗👘👝👫👜👩🐗👤👠👛👥👠👞👟👫🐗👘👥👛🐗👙👩👠👥👞🐗👫👟👜🐗👤👘👧🐣🐗👫👟👜🐗👢👜👰🐗👘👥👛🐗👘🐗👫👦👩👚👟🐥"),
            MEDIUM
        );
    }

    #[test]
    fn decodes_text_athena_does_not_identify() {
        // Decoded, but these are too short or unusual for the English checker, so only
        // the text is checked here
        assert_eq!(
            crack("👊👧👟👠👥👯🐗👦👝🐗👙👣👘👚👢🐗👨👬👘👩👫👱🐣🐗👡👬👛👞👜🐗👤👰🐗👭👦👮🐥")
                .unwrap(),
            "Sphinx of black quartz, judge my vow."
        );
        // The two examples on https://www.dcode.fr/base100-emoji-encoding
        assert_eq!(crack("🐹👘👪👜🐨🐧🐧").unwrap(), "Base100");
        assert_eq!(crack("👛🐺👦👛👜").unwrap(), "dCode");
    }

    #[test]
    fn decodes_utf8_text() {
        // The bytes of non-ASCII UTF-8 text are symbols from 💀 (0x80) up
        assert_eq!(
            crack("🐾👩💺💳💺💖👜🐣🐗📛💯💍📞💌💃").unwrap(),
            "Grüße, 世界"
        );
    }

    #[test]
    fn keeps_tabs_and_line_breaks() {
        assert_eq!(crack("🐿👠🐁🐿👠🐄🐁🐀🐘").unwrap(), "Hi\nHi\r\n\t!");
    }

    #[test]
    fn ignores_surrounding_whitespace() {
        assert_eq!(
            crack_successfully("  👟👜👣👣👦🐗👮👦👩👣👛\r\n"),
            "hello world"
        );
    }

    #[test]
    fn skips_variation_selector_16() {
        // Copying 🐿 or 🏷 from a chat client often adds U+FE0F after it
        assert_eq!(
            crack_successfully("👟\u{FE0F}👜👣👣👦🐗👮👦👩👣👛"),
            "hello world"
        );
        assert_eq!(
            crack("🐿\u{FE0F}👠🐁🐿\u{FE0F}👠🐄🐁🐀🐘\u{FE0F}").unwrap(),
            "Hi\nHi\r\n\t!"
        );
    }

    #[test]
    fn decode_base100_returns_the_bytes() {
        assert_eq!(decode_base100("🏷"), Some(vec![0x00]));
        assert_eq!(decode_base100("📶"), Some(vec![0xFF]));
        assert_eq!(decode_base100("🐗👵"), Some(vec![0x20, 0x7E]));
        // 💯 is a single byte, 0xB8
        assert_eq!(decode_base100("💯"), Some(vec![0xB8]));
    }

    #[test]
    fn decode_base100_reads_every_byte() {
        // chr(0x1F3F7 + b) for every byte, as in the reference implementation
        let text: String = (0..=255u32)
            .map(|b| char::from_u32(0x1F3F7 + b).unwrap())
            .collect();
        let expected: Vec<u8> = (0..=255).collect();
        assert_eq!(decode_base100(&text), Some(expected));
        // One code point either side of the range
        assert_eq!(decode_base100("\u{1F3F6}"), None);
        assert_eq!(decode_base100("\u{1F4F7}"), None);
    }

    #[test]
    fn fails_on_bytes_that_are_not_utf8() {
        // 💯 alone is the byte 0xB8, a UTF-8 continuation byte
        assert_eq!(crack("💯"), None);
        // `G` then 0xC3, the first byte of a two-byte character, with nothing after it
        assert_eq!(crack("🐾💺"), None);
    }

    #[test]
    fn fails_on_control_characters() {
        // NUL
        assert_eq!(crack("🏷"), None);
        assert_eq!(crack("👟👜👣👣👦🏷"), None);
        // DEL (U+007F)
        assert_eq!(crack("👟👶👠"), None);
        // U+0085 NEXT LINE, a C1 control character, as UTF-8
        assert_eq!(crack("👟💹👼👠"), None);
    }

    #[test]
    fn fails_on_only_whitespace() {
        // Three spaces, and two line feeds
        assert_eq!(crack("🐗🐗🐗"), None);
        assert_eq!(crack("🐁🐁"), None);
    }

    #[test]
    fn fails_on_other_emoji() {
        // Out of the range on the first character
        assert_eq!(crack("😀"), None);
        assert_eq!(crack("😂😂😂😂😂"), None);
        assert_eq!(crack("🔥🔥"), None);
        // A skin tone modifier on an emoji outside the range
        assert_eq!(crack("🙋🏽"), None);
        // 👍 is in the range (`V`) but the skin tone modifier 🏽 is the control byte 0x06
        assert_eq!(crack("👍🏽"), None);
        // Zero-width joiners between the symbols of a family emoji
        assert_eq!(crack("👨\u{200D}👩\u{200D}👧"), None);
        // 🏷️: NUL and a variation selector
        assert_eq!(crack("🏷\u{FE0F}"), None);
    }

    #[test]
    fn fails_on_whitespace_between_symbols() {
        assert_eq!(crack("🐶 🐱"), None);
        assert_eq!(crack("👟👜👣👣👦\n🐗👮👦👩👣👛"), None);
        assert_eq!(crack("👟👜👣👣👦\t👮👦👩👣👛"), None);
    }

    #[test]
    fn fails_on_a_variation_selector_first() {
        assert_eq!(crack("\u{FE0F}👟👜👣👣👦"), None);
    }

    #[test]
    fn fails_on_other_encodings() {
        // Braille
        assert_eq!(crack("⠓⠑⠇⠇⠕"), None);
        // Base65536: the decoder's doc test and both bench fixtures
        assert_eq!(crack("𒅓鹨𖡮𒀠啦ꍢ顡啫𓍱𓁡𠁴唬𓍪鱤啥𖥭𔐠𔕯ᔮ"), None);
        assert_eq!(
            crack("驍𓉥ꔠ啥𓉡𓈠驨𒀠饬ꌠ鱩𓉨𒁨𓅵啥魡驴啲鹭𐙤鱩𓉨阠饮霠鹲鱮𓈠驨ꔠ𒅡唬鵴啥驫啹𐙡啤啡𒁴顲捨"),
            None
        );
        assert_eq!(
            crack("鹃鵰𖥥鸠啳𐙡阠𓉵ꕯ𓉡饥餠顥饯𐙩啧𒁴ꍯ售𒁙啵鹧驶鸠啴𐙥𓁣𒅹驴啤𓁯騠顮饯饥𓈠𖡥啴𐙡啤𓉩𓈠鹲𓅥𓈠啯𒁷ꉲ𒀠𓉵𔔠陨啴陷啳𒁤驮𓈠啯𓉩唬鹷鵴𓍯啴𒁹啵陨鹶鱮𓈠啯𐙫𔕯𓈠驨ꈠ𖥥𒀠啲𔑥𐙥𓈠驨頠𒅩驨捲縠啴驳𓁡鵣𓅥𓈠𓁨𓍯鵧ꔠ𐙡啹𒁰𓅳革马餠顥饯𐙩𓅧唬鵣顥𓅫騠顡啨陣饮饩𓉡啥𒁴𓄠驥𔔠驨鵴𓁥鸠啴𒁬ꉯ啳鹬驫稠鱮鹬鵳𒀠啲陭顴驨啳啡𐙫𔕯啮陰𓉴𓁥啮𓍳鵣阠啳𐙡騠陭ꍩ阠饤驲𓅳唬𐙡啤𓉳𒅯啳鵷𐙥鸠啴鹦饮啳𒁳驭鵴𐙩啧鵴𓉡𓀠陥𓅤ꌠꉩ啥ꍰ鹡𓉮𖡥捴舠𓅯啴魯𓈠驨𓈠ꕩ啥鵴𓅩𓈠ꉡ𓅥ꌠ𓅥啳鵴𐙡阠𓄠顥𐙯慤𔔠鹨鵣ꔠꉡ𓅥鸠啴陨饮啹𒁦啲陣𓉰𓁵啥鵴啥ꍦ鱡頠陨ꍬ𐙥驧慳𒄠𠁵ꍺ啥𓍨𓉮啳𐙡啤𒁦啲𐙡𒁹驮𔔠𒁨𓄠𓍴靭马啳顡𒁲𓅳阠𓄠𓁴𐙡驧𓄠𓁴𐙩啧𐙩阠ꌠ鱯鬠ꍩ捥"),
            None
        );
        // Base64
        assert_eq!(crack("aGVsbG8gd29ybGQ="), None);
    }

    #[test]
    fn fails_on_the_bench_miss_input() {
        assert_eq!(
            crack("T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV"),
            None
        );
    }

    #[test]
    fn reversed_text_is_decoded_but_not_accepted() {
        let decoder = Decoder::<Base100Decoder>::new();
        let result = decoder.crack("👛👣👩👦👮🐗👦👣👣👜👟", &get_athena_checker());
        assert!(!result.success, "Athena accepted `dlrow olleh`");
        assert_eq!(result.unencrypted_text.unwrap()[0], "dlrow olleh");
    }

    #[test]
    fn handles_panic_if_empty_string() {
        assert_eq!(crack(""), None);
    }

    #[test]
    fn handles_panic_if_whitespace() {
        assert_eq!(crack("   "), None);
        assert_eq!(crack(" \t\r\n "), None);
    }

    #[test]
    fn handles_panic_if_emoji() {
        assert_eq!(crack("😀"), None);
    }

    #[test]
    fn fails_on_english() {
        assert_eq!(crack("hello world"), None);
        assert_eq!(crack("Hello"), None);
        assert_eq!(crack("hello my name is panicky mc panic face!"), None);
    }

    #[test]
    fn is_registered() {
        // Exactly one decoder by that name runs in the search
        let decoders = get_decoder_by_name("Base100");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Base100");
        // Cached results name the decoder; reading them back looks it up here
        let decoder = DECODER_MAP
            .get("Base100")
            .expect("Base100 should be in DECODER_MAP")
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "Base100");
    }
}
