//! Decode Base64 written with a non-standard alphabet, such as crypt(3)'s itoa64 or
//! CyberChef's Atom128.
//!
//! Everything but the table of 64 symbols is ordinary Base64: 6 bits per symbol, 4
//! symbols to 3 bytes, and 1 or 2 trailing padding symbols or none. The alphabets are
//! CyberChef's `From Base64` presets (`ALPHABET_OPTIONS` in its `src/core/lib/Base64.mjs`),
//! which are the ones CTF players meet:
//!
//! | Key | Symbols 0 to 63 | Padding |
//! |---|---|---|
//! | `Filename safe` | `A-Za-z0-9+-` | `=` |
//! | `itoa64 / crypt(3)` | `./0-9A-Za-z` | `=` |
//! | `bcrypt` | `./A-Za-z0-9` | `=` |
//! | `XML` | `A-Za-z0-9_.` | none |
//! | `y64` | `A-Za-z0-9._` | `-` |
//! | `z64` | `0-9a-zA-Z+/` | `=` |
//! | `Radix-64 (CyberChef)` | `0-9A-Za-z+/` | `=` |
//! | `ROT13` | `N-ZA-Mn-za-m0-9+/` | `=` |
//! | `Atom128`, `Megan35`, `Zong22`, `Hazz15` | shuffled tables that use `=` as a symbol | `C`, `5`, `2`, `5` |
//!
//! Standard and URL-safe Base64 belong to the Base64 decoder. Text it decodes to UTF-8 is
//! rejected here, so the search doesn't get the same candidate twice.
//!
//! Every applicable alphabet is tried. Output that isn't printable ASCII is dropped, the
//! rest is ranked by its share of letters and spaces, and the best three are checked.
//! The alphabet is reported as the key.
//!
//! References: <https://en.wikipedia.org/wiki/Base64#Variants_summary_table>,
//! <https://github.com/gchq/CyberChef/blob/master/src/core/lib/Base64.mjs>.

use crate::checkers::checker_result::CheckResult;
use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;
use base64::alphabet::{Alphabet, Symbol};
use base64::engine::general_purpose::{self, GeneralPurpose};
use base64::Engine as _;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, trace};

/// The Base64 Alt decoder, call:
/// `let base64_alt_decoder = Decoder::<Base64AltDecoder>::new()` to create a new instance
/// And then call:
/// `result = base64_alt_decoder.crack(input)` to decode Base64 with a non-standard alphabet
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::base64_alt_decoder::Base64AltDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_base64_alt = Decoder::<Base64AltDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // The crypt(3) / itoa64 alphabet: ./0-9A-Za-z
/// let result = decode_base64_alt.crack(
///     "J4VZ653pOKBf647mPrRi64NjS0/eRKpkQm/jRaJm65FcNG/gMLdt64FjNk==",
///     &checker,
/// );
/// assert!(result.success);
/// assert_eq!(
///     result.unencrypted_text.unwrap()[0],
///     "The quick brown fox jumps over the lazy dog"
/// );
/// assert_eq!(result.key.as_deref(), Some("itoa64 / crypt(3)"));
/// ```
pub struct Base64AltDecoder;

/// Shorter text decodes to printable junk with too many alphabets. 12 symbols are 9 bytes.
const MIN_LEN: usize = 12;

/// How many candidates go to the checker, and to the search when none is identified.
const MAX_CANDIDATES: usize = 3;

impl Crack for Decoder<Base64AltDecoder> {
    fn new() -> Decoder<Base64AltDecoder> {
        Decoder {
            name: "Base64 Alt",
            description: "Base64 with a non-standard alphabet: crypt/itoa64, bcrypt, y64, z64, Radix-64, XML, filename-safe, ROT13 and CyberChef's Atom128, Megan35, Zong22 and Hazz15; the alphabet is reported as the key.",
            link: "https://en.wikipedia.org/wiki/Base64#Variants_summary_table",
            tags: vec!["base64", "base64_alt", "decoder", "base"],
            popularity: 0.4,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes `text` with every alphabet that fits it and checks the best candidates, at
    /// most three. Returns the first one the checker identifies, or else all of them for
    /// the search to decode further.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Base64 Alt with text {:?}", text);
        let candidates = decode_alt(text);
        if candidates.is_empty() {
            debug!("Base64 Alt found no alphabet that decodes the text to printable ASCII");
            return CrackResult::new(self, text.to_string());
        }
        check_candidates(self, text, candidates, |candidate| checker.check(candidate))
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Runs `check` on each candidate in order and returns the first one it identifies, with
/// its alphabet as the key. If it identifies none, returns every candidate, and as the key
/// their alphabets in the same order.
fn check_candidates(
    decoder: &Decoder<Base64AltDecoder>,
    text: &str,
    candidates: Vec<(&'static str, String)>,
    mut check: impl FnMut(&str) -> CheckResult,
) -> CrackResult {
    let mut results = CrackResult::new(decoder, text.to_string());
    for (alphabet, candidate) in &candidates {
        let checker_result = check(candidate);
        if checker_result.is_identified {
            trace!("Found a match with the {alphabet} Base64 alphabet");
            results.unencrypted_text = Some(vec![candidate.clone()]);
            results.update_checker(&checker_result);
            results.key = Some(alphabet.to_string());
            return results;
        }
    }

    let alphabets: Vec<&str> = candidates.iter().map(|(alphabet, _)| *alphabet).collect();
    results.key = Some(alphabets.join(", "));
    results.unencrypted_text = Some(candidates.into_iter().map(|(_, text)| text).collect());
    results
}

/// A set of ASCII bytes: bit `b` stands for byte `b`.
type ByteSet = u128;

/// The set of `bytes`. Fails to compile for a non-ASCII byte.
const fn byte_set(bytes: &[u8]) -> ByteSet {
    let mut set = 0;
    let mut i = 0;
    while i < bytes.len() {
        set |= 1 << bytes[i];
        i += 1;
    }
    set
}

/// The set of the bytes `first..=last`.
const fn byte_range(first: u8, last: u8) -> ByteSet {
    let mut set = 0;
    let mut byte = first;
    while byte <= last {
        set |= 1 << byte;
        byte += 1;
    }
    set
}

/// `A-Z`
const UPPER: ByteSet = byte_range(b'A', b'Z');
/// `a-z`
const LOWER: ByteSet = byte_range(b'a', b'z');
/// `A-Za-z0-9`
const ALPHANUMERIC: ByteSet = UPPER | LOWER | byte_range(b'0', b'9');
/// Every symbol and padding character of the alphabets below
const SYMBOLS: ByteSet = ALPHANUMERIC | byte_set(b"+/=-_.");
/// Standard Base64, padding included
const STANDARD: ByteSet = ALPHANUMERIC | byte_set(b"+/=");
/// URL-safe Base64, padding included
const URL_SAFE: ByteSet = ALPHANUMERIC | byte_set(b"-_=");

/// A Base64 alphabet this decoder tries.
struct AltAlphabet {
    /// Reported as the key, e.g. `itoa64 / crypt(3)`
    name: &'static str,
    /// The set of the 64 symbols
    symbol_set: ByteSet,
    /// The padding character, or `None` for an alphabet without padding
    padding: Option<u8>,
    /// Decodes text in this alphabet once the padding is removed
    engine: GeneralPurpose,
}

impl AltAlphabet {
    /// Builds the alphabet at compile time, so a malformed table can't compile.
    const fn new(name: &'static str, symbols: &'static str, padding: Option<u8>) -> Self {
        // The crate wants a padding symbol even for an alphabet without padding. `=` is
        // fine for those: it isn't one of their symbols, and the engine never sees padding.
        let engine_padding = match padding {
            Some(padding) => padding,
            None => b'=',
        };
        let Some(engine_padding) = Symbol::new(engine_padding) else {
            panic!("the padding must be printable ASCII");
        };
        let alphabet = match Alphabet::new_with_padding(symbols, engine_padding) {
            Ok(alphabet) => alphabet,
            Err(_) => panic!("not 64 distinct printable symbols, or the padding is one of them"),
        };
        AltAlphabet {
            name,
            symbol_set: byte_set(symbols.as_bytes()),
            padding,
            engine: GeneralPurpose::new(&alphabet, general_purpose::NO_PAD),
        }
    }
}

/// The alphabets, in the order they are tried. Candidates with the same score keep it.
///
/// Left out: standard and URL-safe Base64 (the Base64 decoder), Uuencoding and Xxencoding
/// (line-framed formats of their own), IMAP's modified UTF-7 (UTF-7 framing and UTF-16
/// text) and BinHex (a container with run-length encoding, whose symbols would turn
/// Ascii85 into junk candidates).
static ALPHABETS: [AltAlphabet; 12] = [
    AltAlphabet::new(
        "Filename safe",
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+-",
        Some(b'='),
    ),
    AltAlphabet::new(
        "itoa64 / crypt(3)",
        "./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
        Some(b'='),
    ),
    AltAlphabet::new(
        "bcrypt",
        "./ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789",
        Some(b'='),
    ),
    AltAlphabet::new(
        "XML",
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_.",
        None,
    ),
    AltAlphabet::new(
        "y64",
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._",
        Some(b'-'),
    ),
    AltAlphabet::new(
        "z64",
        "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ+/",
        Some(b'='),
    ),
    AltAlphabet::new(
        "Radix-64 (CyberChef)",
        "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz+/",
        Some(b'='),
    ),
    AltAlphabet::new(
        "ROT13",
        "NOPQRSTUVWXYZABCDEFGHIJKLMnopqrstuvwxyzabcdefghijklm0123456789+/",
        Some(b'='),
    ),
    AltAlphabet::new(
        "Atom128",
        "/128GhIoPQROSTeUbADfgHijKLM+n0pFWXY456xyzB7=39VaqrstJklmNuZvwcdE",
        Some(b'C'),
    ),
    AltAlphabet::new(
        "Megan35",
        "3GHIJKLMNOPQRSTUb=cdefghijklmnopWXYZ/12+406789VaqrstuvwxyzABCDEF",
        Some(b'5'),
    ),
    AltAlphabet::new(
        "Zong22",
        "ZKj9n+yf0wDVX1s/5YbdxSo=ILaUpPBCHg8uvNO4klm6iJGhQ7eFrWczAMEq3RTt",
        Some(b'2'),
    ),
    AltAlphabet::new(
        "Hazz15",
        "HNO4klm6ij9n+J2hyf0gzA8uvwDEq3X1Q7ZKeFrWcVTts/MRGYbdxSo=ILaUpPBC",
        Some(b'5'),
    ),
];

/// The bytes of a text that [`scan`] accepted.
struct Scan {
    /// Every byte of the text
    all: ByteSet,
    /// The bytes before the last two, where padding can't be
    head: ByteSet,
}

/// Collects the bytes of `text` in one pass, or returns `None` at the first byte that no
/// alphabet uses. `text` has at least two bytes.
fn scan(text: &[u8]) -> Option<Scan> {
    let (head, tail) = text.split_at(text.len() - 2);
    let mut head_set = 0;
    for &byte in head {
        head_set |= symbol_bit(byte)?;
    }
    let mut all = head_set;
    for &byte in tail {
        all |= symbol_bit(byte)?;
    }
    Some(Scan {
        all,
        head: head_set,
    })
}

/// The bit for `byte` if some alphabet uses it as a symbol or padding.
fn symbol_bit(byte: u8) -> Option<ByteSet> {
    // `None` for a byte above 127
    let bit = (1 as ByteSet).checked_shl(u32::from(byte))?;
    (SYMBOLS & bit != 0).then_some(bit)
}

/// `text` without its padding, if what is left is written in `alphabet`. More than two
/// padding characters don't fit any alphabet.
fn unpadded<'a>(alphabet: &AltAlphabet, text: &'a [u8], scan: &Scan) -> Option<&'a [u8]> {
    let padding_len = alphabet.padding.map_or(0, |padding| {
        text.iter()
            .rev()
            .take(3)
            .take_while(|&&byte| byte == padding)
            .count()
    });
    if padding_len > 2 {
        return None;
    }
    let body = &text[..text.len() - padding_len];
    // The bytes of `body`: those before the last two, plus whichever of the last two
    // aren't padding
    let body_set = text[text.len() - 2..body.len()]
        .iter()
        .fold(scan.head, |set, &byte| set | 1 << byte);
    (body_set & !alphabet.symbol_set == 0).then_some(body)
}

/// Decodes unpadded `body` and returns it if every byte is printable ASCII, a tab or a
/// line break. Other output is almost never plaintext, and allowing it doubles the junk
/// candidates that random text produces.
fn decode_printable(engine: &GeneralPurpose, body: &[u8]) -> Option<String> {
    // One symbol left over is never valid Base64
    if body.len() % 4 == 1 {
        return None;
    }
    let bytes = engine.decode(body).ok()?;
    if !bytes
        .iter()
        .all(|&byte| matches!(byte, b' '..=b'~' | b'\t' | b'\n' | b'\r'))
    {
        return None;
    }
    String::from_utf8(bytes).ok()
}

/// Whether `text` (already trimmed) is standard or URL-safe Base64 that the Base64 decoder
/// turns into UTF-8, so this decoder must not offer another reading of it. Text ending in
/// `-` is left to this decoder: `-` is y64's padding, and the Base64 decoder reads it as
/// data (`aGVsbG8gd29ybGQ-` is `hello world>` to it and `hello world` in y64).
fn base64_decoder_finds(text: &str, scan: &Scan) -> bool {
    // Anything else would fail to decode
    let fits = scan.all & !STANDARD == 0 || scan.all & !URL_SAFE == 0;
    fits && !text.ends_with('-') && {
        // What `base64_decoder.rs` does: drop every `=`, decode with the standard alphabet
        // if the text contains `+`, `/` or `=` and with the URL-safe one otherwise, and
        // keep the bytes if they are UTF-8
        let unpadded: Vec<u8> = text.bytes().filter(|&byte| byte != b'=').collect();
        let engine = if text.contains(['+', '/', '=']) {
            &general_purpose::STANDARD_NO_PAD
        } else {
            &general_purpose::URL_SAFE_NO_PAD
        };
        engine
            .decode(unpadded)
            .is_ok_and(|bytes| std::str::from_utf8(&bytes).is_ok())
    }
}

/// The share of `text` that is ASCII letters and spaces, which ranks the candidates.
fn letter_share(text: &str) -> f32 {
    let letters = text
        .bytes()
        .filter(|&byte| byte.is_ascii_alphabetic() || byte == b' ')
        .count();
    letters as f32 / text.len().max(1) as f32
}

/// Decodes `text` with every alphabet that fits it, and returns the alphabet name and the
/// text of the best [`MAX_CANDIDATES`] decodings that are printable ASCII, best first.
/// Nothing is checked.
fn decode_alt(text: &str) -> Vec<(&'static str, String)> {
    let text = text.trim();
    if text.len() < MIN_LEN {
        return Vec::new();
    }
    let bytes = text.as_bytes();
    let Some(scan) = scan(bytes) else {
        return Vec::new();
    };
    // Each alphabet has all 52 letters, so real input of 12 or more symbols has both
    // cases: hex, Base32, binary and digits stop here
    if scan.all & LOWER == 0 || scan.all & UPPER == 0 {
        return Vec::new();
    }
    if base64_decoder_finds(text, &scan) {
        trace!("Leaving {:?} to the Base64 decoder", text);
        return Vec::new();
    }

    let mut candidates: Vec<(f32, &'static str, String)> = ALPHABETS
        .iter()
        .filter_map(|alphabet| {
            let body = unpadded(alphabet, bytes, &scan)?;
            let decoded = decode_printable(&alphabet.engine, body)?;
            check_string_success(&decoded, text)
                .then(|| (letter_share(&decoded), alphabet.name, decoded))
        })
        .collect();
    // Stable, so equal scores keep the order of `ALPHABETS`
    candidates.sort_by(|a, b| b.0.total_cmp(&a.0));
    candidates
        .into_iter()
        .take(MAX_CANDIDATES)
        .map(|(_, alphabet, decoded)| (alphabet, decoded))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::{
        check_candidates, decode_alt, decode_printable, letter_share, scan, unpadded, AltAlphabet,
        Base64AltDecoder, ALPHABETS, MAX_CANDIDATES, SYMBOLS,
    };
    use crate::{
        checkers::{
            athena::Athena,
            checker_result::CheckResult,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::{
            base64_decoder::Base64Decoder,
            crack_results::CrackResult,
            interface::{Crack, Decoder},
        },
        filtration_system::get_decoder_by_name,
    };
    use base64::engine::general_purpose::{self, GeneralPurpose};
    use base64::Engine as _;

    // Unless noted otherwise, every vector was made with Python's base64.b64encode and
    // str.translate onto the alphabet (padding mapped to its padding character) and decoded
    // back the same way. The two issue examples (#933) and the Atom128 form of the bench
    // text were also decoded with CyberChef 10.24 `From Base64` (strict mode, the preset
    // alphabet).

    const SPHINX: &str = "Sphinx of black quartz, judge my vow.";
    const FOX: &str = "The quick brown fox jumps over the lazy dog";
    const MEDIUM: &str =
        "Meet me at the old lighthouse after midnight and bring the map, the key and a torch.";
    const ITOA64: &str = "itoa64 / crypt(3)";

    /// The bench text in itoa64 (`benches/data/decoders.toml`)
    const MEDIUM_ITOA64: &str = "HKJZR0/hNG/VR0/oO4IUPqlY64ldNqVoO4xpQqIUMKNoNL6UPKZYPaZbO5EUMKtY647mOKtb65FcNG/hML.g65FcNG/fNLYUMKtY642UR4xmMqUi";

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn crack(text: &str) -> CrackResult {
        Decoder::<Base64AltDecoder>::new().crack(text, &get_athena_checker())
    }

    fn alphabet(name: &str) -> &'static AltAlphabet {
        ALPHABETS
            .iter()
            .find(|alphabet| alphabet.name == name)
            .unwrap_or_else(|| panic!("no alphabet named {name:?}"))
    }

    /// Asserts that `text` decodes to `plaintext` in `key`, and that the checker accepts it.
    fn assert_cracked(text: &str, plaintext: &str, key: &str) {
        let result = crack(text);
        assert!(result.success, "{text:?} was not identified: {result:?}");
        assert_eq!(
            result.unencrypted_text.as_deref(),
            Some(&[plaintext.to_string()][..])
        );
        assert_eq!(result.key.as_deref(), Some(key), "{text:?}");
    }

    /// Asserts that the best candidate for `text` is `plaintext` in `key`. For text the
    /// checker doesn't identify, where the search gets every candidate.
    fn assert_decoded(text: &str, plaintext: &str, key: &str) {
        let candidates = decode_alt(text);
        assert_eq!(
            candidates.first(),
            Some(&(key_name(key), plaintext.to_string())),
            "{text:?}: {candidates:?}"
        );
        let result = crack(text);
        let texts = result.unencrypted_text.expect("no candidate");
        assert_eq!(texts[0], plaintext);
        assert!(result.key.unwrap().starts_with(key));
    }

    fn key_name(key: &str) -> &'static str {
        alphabet(key).name
    }

    fn assert_no_candidate(text: &str) {
        assert_eq!(decode_alt(text), Vec::new(), "{text:?}");
        let result = crack(text);
        assert!(result.unencrypted_text.is_none(), "{text:?}: {result:?}");
        assert!(!result.success);
    }

    #[test]
    fn issue_itoa64_example() {
        // The Athena checker doesn't accept this pangram, so the search gets it as a
        // candidate instead
        assert_decoded(
            "Ir/cOKts64xa647gMKBf653pML7oSWkUObJYNqIUPLYURaxr9U==",
            SPHINX,
            ITOA64,
        );
    }

    #[test]
    fn issue_atom128_example() {
        // `=` is a symbol here (`KiT=Pohk`), and `CC` is the padding
        assert_decoded(
            "gm1zMiuNPIcxPIQ3KiT=PohkKjQJpYqWMyH5LlgW+j5W0xcmOWCC",
            SPHINX,
            "Atom128",
        );
    }

    #[test]
    fn fox_in_itoa64_and_atom128() {
        assert_cracked(
            "J4VZ653pOKBf647mPrRi64NjS0/eRKpkQm/jRaJm65FcNG/gMLdt64FjNk==",
            FOX,
            ITOA64,
        );
        assert_cracked(
            "HIX6PohkMiT=PIQs+m0VPILap2170ikqns1a0xHsPoAzLD13KjBuPIAaLqCC",
            FOX,
            "Atom128",
        );
    }

    #[test]
    fn hello_world_in_other_alphabets() {
        assert_cracked("YETqZE6eb07wZEO=", "hello world", "bcrypt");
        assert_cracked("q6lIr6YwtSZOr6g=", "hello world", "z64");
        assert_cracked("nTIfoT8tq29loTD=", "hello world", "ROT13");
        assert_cracked("kLf8lLCWnwDslLb5", "hello world", "Megan35");
    }

    #[test]
    fn y64_padding_is_a_dash() {
        // Filename safe reads the `-` as a symbol and comes second
        assert_eq!(
            decode_alt("aGVsbG8gd29ybGQ-"),
            [
                ("y64", "hello world".to_string()),
                ("Filename safe", "hello world?".to_string())
            ]
        );
        assert_cracked("aGVsbG8gd29ybGQ-", "hello world", "y64");
        assert_cracked(
            "VGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZw--",
            FOX,
            "y64",
        );
    }

    #[test]
    fn fox_in_zong22_and_hazz15() {
        assert_cracked(
            "SygN0f+Wao160yweUzPG0yLhBjKmPoWQpeKhPOSe0fYkLbKiI=lM0yYhLQ22",
            FOX,
            "Zong22",
        );
        assert_cracked(
            "Am7Fi6lSD8JtimjbE=3MimwRXONT38SGqbNR3rAbi6fcw0NsvuVLimfRwG55",
            FOX,
            "Hazz15",
        );
    }

    #[test]
    fn bench_text_in_itoa64_and_atom128() {
        assert_cracked(MEDIUM_ITOA64, MEDIUM, ITOA64);
        assert_cracked(
            "fiH60219LD1X021JMIgW+lr5PIrBLlXJMIcknlgWKiLJLjPW+i65+x6yMobWKiu5PIQsMiuyPoAzLD19Kj/3PoAzLD1=Lj5WKiu5PIGW0IcsKlWV",
            MEDIUM,
            "Atom128",
        );
    }

    #[test]
    fn surrounding_whitespace_is_trimmed() {
        assert_cracked("  YETqZE6eb07wZEO=\n", "hello world", "bcrypt");
    }

    #[test]
    fn standard_and_url_safe_base64_are_left_to_base64() {
        assert_no_candidate("aGVsbG8gd29ybGQ=");
        assert_no_candidate("SGVsbG8gV29ybGQ");
        assert_no_candidate("TWVldCBtZSBhdCB0aGUgb2xkIGxpZ2h0aG91c2UgYWZ0ZXIgbWlkbmlnaHQgYW5kIGJyaW5nIHRoZSBtYXAsIHRoZSBrZXkgYW5kIGEgdG9yY2gu");
        assert_no_candidate("aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8_ZXhhbXBsZT10ZXN0");
        // With whitespace around it, too
        assert_no_candidate(" aGVsbG8gd29ybGQ=\n");
    }

    #[test]
    fn gate_agrees_with_the_base64_decoder() {
        let base64 = Decoder::<Base64Decoder>::new();
        let checker = get_athena_checker();
        for text in [
            "aGVsbG8gd29ybGQ=",
            "SGVsbG8gV29ybGQ",
            "SGVsbG8tV29ybGQ",
            "SGVsbG8+Pz8/Cg==",
            "SGVsbG8-Pz8_Cg",
            "aGVsbG8gd29ybGQ-",
            "YETqZE6eb07wZEO=",
            "q6lIr6YwtSZOr6g=",
            "nTIfoT8tq29loTD=",
            "kLf8lLCWnwDslLb5",
            "p21Yp21Hp29+",
            "gIGCg4SFhoeIiYqLjI2Oj5CRkpOUlZaXmJmam5ydnp8=",
            "gm1zMiuNPIcxPIQ3KiT=PohkKjQJpYqWMyH5LlgW+j5W0xcmOWCC",
            "J4VZ653pOKBf647mPrRi64NjS0/eRKpkQm/jRaJm65FcNG/gMLdt64FjNk==",
        ] {
            let scan = scan(text.as_bytes()).unwrap();
            let base64_found = base64.crack(text, &checker).unencrypted_text.is_some();
            // Text ending in `-` is the exception: this decoder reads it as y64 padding
            let expected = base64_found && !text.ends_with('-');
            assert_eq!(
                super::base64_decoder_finds(text, &scan),
                expected,
                "{text:?}"
            );
        }
    }

    #[test]
    fn equals_sign_inside_is_a_symbol_only_for_the_custom_alphabets() {
        let text = b"gm1zMiuNPIcxPIQ3KiT=PohkKjQJpYqWMyH5LlgW+j5W0xcmOWCC";
        let scan = scan(text).unwrap();
        let fitting: Vec<&str> = ALPHABETS
            .iter()
            .filter(|alphabet| unpadded(alphabet, text, &scan).is_some())
            .map(|alphabet| alphabet.name)
            .collect();
        // The `=` inside rules out every alphabet that pads with `=` or has no `=`. Of the
        // four that use `=` as a symbol, Megan35 and Hazz15 pad with `5`, which this text
        // has inside (`MyH5Llg`).
        assert_eq!(fitting, ["Atom128", "Zong22"]);
    }

    #[test]
    fn padding_letter_inside_skips_that_alphabet_only() {
        // itoa64 of "Meet me at NOON in the park": its `C`s are data, which Atom128 (where
        // `C` is the padding) can't have, but itoa64 still decodes it
        let text = "HKJZR0/hNG/VR0/CHoxC64Zi65FcNG/kML7f";
        let scan = scan(text.as_bytes()).unwrap();
        assert!(unpadded(alphabet("Atom128"), text.as_bytes(), &scan).is_none());
        assert!(unpadded(alphabet(ITOA64), text.as_bytes(), &scan).is_some());
        assert_eq!(
            decode_alt(text),
            [(ITOA64, "Meet me at NOON in the park".to_string())]
        );
    }

    #[test]
    fn padding_is_stripped_only_at_the_end() {
        let atom128 = alphabet("Atom128");
        let text = b"gm1zMiuNPIcxPIQ3KiT=PohkKjQJpYqWMyH5LlgW+j5W0xcmOWCC";
        let scan = scan(text).unwrap();
        assert_eq!(
            unpadded(atom128, text, &scan),
            Some(&text[..text.len() - 2])
        );
        // One padding character, and a `C` just before the last character isn't padding
        let one = b"gm1zMiuNPIcxPIQ3KiT=PohkKjQJpYqWMyH5LlgW+j5W0xcmOWC";
        assert_eq!(
            unpadded(atom128, one, &super::scan(one).unwrap()),
            Some(&one[..one.len() - 1])
        );
        let inner = b"gm1zMiuNPIcxPIQ3KiT=PohkKjQJpYqWMyH5LlgW+j5W0xcmOWCx";
        assert_eq!(unpadded(atom128, inner, &super::scan(inner).unwrap()), None);
    }

    #[test]
    fn three_padding_characters_fit_no_alphabet() {
        assert_no_candidate("Ir/cOKts64xa647gMKBf653pML7oSWkUObJYNqIUPLYURaxr9U===");
        assert_no_candidate("YETqZE6eb07wZEO===");
    }

    #[test]
    fn one_symbol_left_over_is_rejected() {
        // 13 symbols: 4 * 3 + 1
        assert_no_candidate("Ir/cOKts64xa6");
        assert_eq!(
            decode_printable(&alphabet(ITOA64).engine, b"Ir/cOKts64xa6"),
            None
        );
    }

    #[test]
    fn whitespace_inside_is_rejected() {
        assert_no_candidate("YETqZE6e b07wZEO=");
        assert_no_candidate("J4VZ653pOKBf647mPrRi64NjS0/eRKpkQm/j\nRaJm65FcNG/gMLdt64FjNk==");
    }

    #[test]
    fn short_and_empty_input_is_rejected() {
        assert_no_candidate("");
        assert_no_candidate("   ");
        assert_no_candidate(" \n\t");
        assert_no_candidate("Hello");
        assert_no_candidate("hello world");
        // bcrypt `hello world` cut to 11 symbols
        assert_no_candidate("YETqZE6eb07");
    }

    #[test]
    fn emoji_doesnt_panic() {
        assert_no_candidate("😀");
        assert_no_candidate("😂😂😂😂😂");
        assert_no_candidate("YETqZE6eb07wZEO=😀");
    }

    #[test]
    fn other_encodings_are_rejected() {
        // The bench miss input stops at its first space
        assert_no_candidate("T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV");
        // Hex and Base32 have one letter case
        assert_no_candidate("4d656574206d6520617420746865206f6c64");
        assert_no_candidate("JVSWK5BANVSSAYLUEB2GQZJAN5WGIIDMNFTWQ5DIN52XGZJAMF");
        assert_no_candidate("123456789012345");
        assert_no_candidate("abcdefghijklmnop");
        // Base58 (Bitcoin) of the bench text
        assert_no_candidate("6X6FW9Fv3pE3p6JtGkbStCFRnzXNxB2FpZzj3qrCm9DJAyJXHm7eixRZfy9rkN8nTwk8SRHWUDmeoc7qJTrURpjgfxQqR3oSt9wR67mGcrjWXhrx2Zb");
        // CamelCase words
        for text in [
            "HelloWorldFooBar",
            "ThisIsATestString",
            "CamelCaseWordPair",
            "QuickBrownFoxJumps",
        ] {
            assert_no_candidate(text);
        }
    }

    #[test]
    fn binary_data_is_rejected() {
        // Python: base64.b64encode(bytes(range(0x80, 0xa0)))
        assert_no_candidate("gIGCg4SFhoeIiYqLjI2Oj5CRkpOUlZaXmJmam5ydnp8=");
        // Python: base64.b64encode(zlib.compress(b"hello world, hello world, hello world"))
        assert_no_candidate("eJzLSM3JyVcozy/KSdFRyMDBAQADjA2t");
    }

    #[test]
    fn at_most_three_candidates_best_first() {
        // ROT13, Atom128, z64 and Megan35 all decode this to printable ASCII
        let text = "p21Yp21Hp29+";
        let scan = scan(text.as_bytes()).unwrap();
        let printable = ALPHABETS
            .iter()
            .filter(|alphabet| {
                unpadded(alphabet, text.as_bytes(), &scan)
                    .and_then(|body| decode_printable(&alphabet.engine, body))
                    .is_some()
            })
            .count();
        assert_eq!(printable, 4);

        let candidates = decode_alt(text);
        assert_eq!(candidates.len(), MAX_CANDIDATES);
        assert_eq!(candidates[0], ("ROT13", "smKsmTso~".to_string()));
        let shares: Vec<f32> = candidates.iter().map(|(_, t)| letter_share(t)).collect();
        assert!(
            shares.windows(2).all(|pair| pair[0] >= pair[1]),
            "{shares:?}"
        );
    }

    /// A checker result that identifies the text or doesn't
    fn check_result(is_identified: bool) -> CheckResult {
        let mut result = CheckResult::new(&Checker::<Athena>::new());
        result.is_identified = is_identified;
        result
    }

    #[test]
    fn checks_at_most_three_and_hands_them_all_on() {
        let decoder = Decoder::<Base64AltDecoder>::new();
        let text = "p21Yp21Hp29+";
        let mut checked = Vec::new();
        let result = check_candidates(&decoder, text, decode_alt(text), |candidate| {
            checked.push(candidate.to_string());
            check_result(false)
        });
        assert_eq!(checked.len(), MAX_CANDIDATES);
        assert!(!result.success);
        assert_eq!(result.unencrypted_text, Some(checked));
        assert_eq!(result.key.as_deref(), Some("ROT13, Atom128, z64"));
    }

    #[test]
    fn checking_stops_at_the_first_identified() {
        let decoder = Decoder::<Base64AltDecoder>::new();
        let text = "p21Yp21Hp29+";
        let candidates = decode_alt(text);
        let second = candidates[1].clone();
        let mut calls = 0;
        let result = check_candidates(&decoder, text, candidates, |_| {
            calls += 1;
            check_result(calls == 2)
        });
        assert_eq!(calls, 2);
        assert!(result.success);
        assert_eq!(result.unencrypted_text, Some(vec![second.1]));
        assert_eq!(result.key.as_deref(), Some(second.0));
    }

    /// The symbols of `engine`'s alphabet, in order
    fn symbols(engine: &GeneralPurpose) -> String {
        // The 48 bytes that standard Base64 writes as its own alphabet
        let every_symbol = general_purpose::STANDARD_NO_PAD
            .decode("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")
            .unwrap();
        engine.encode(every_symbol)
    }

    #[test]
    fn alphabets_are_well_formed() {
        let crypt = GeneralPurpose::new(&base64::alphabet::CRYPT, general_purpose::NO_PAD);
        let bcrypt = GeneralPurpose::new(&base64::alphabet::BCRYPT, general_purpose::NO_PAD);
        assert_eq!(symbols(&alphabet(ITOA64).engine), symbols(&crypt));
        assert_eq!(symbols(&alphabet("bcrypt").engine), symbols(&bcrypt));
        assert_eq!(
            symbols(&alphabet("Atom128").engine),
            "/128GhIoPQROSTeUbADfgHijKLM+n0pFWXY456xyzB7=39VaqrstJklmNuZvwcdE"
        );
        for alphabet in &ALPHABETS {
            // 64 distinct symbols and a padding character that isn't one of them are
            // checked when the table is built
            assert_eq!(alphabet.symbol_set.count_ones(), 64, "{}", alphabet.name);
            assert_eq!(alphabet.symbol_set & !SYMBOLS, 0, "{}", alphabet.name);
            assert_eq!(
                super::byte_set(symbols(&alphabet.engine).as_bytes()),
                alphabet.symbol_set,
                "{}",
                alphabet.name
            );
            if let Some(padding) = alphabet.padding {
                assert_ne!(SYMBOLS & 1 << padding, 0, "{}", alphabet.name);
            }
        }
    }

    #[test]
    fn registered_once() {
        let decoders = get_decoder_by_name("Base64 Alt");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Base64 Alt");
        assert!(crate::decoders::DECODER_MAP.contains_key("Base64 Alt"));
    }
}
