//! Decode Base92, the encoding from <https://github.com/thenoviceoof/base92> that
//! CyberChef's "From Base92" also implements.
//!
//! The input is read as one stream of bits, most significant first. Every 13 bits become
//! two characters: the 13-bit value `v` is written as the digits `v / 91` and `v % 91`. At
//! the end, 7 to 12 leftover bits are padded with zeros to 13 and written as a pair, and 1
//! to 6 leftover bits are padded to 6 and written as one character. The 91 digits are `!`
//! (0), `#` to `_` (1 to 61) and `a` to `}` (62 to 90), so space, `"`, `` ` `` and `~` are
//! not digits. A lone `~` is the encoding of empty input.
//! Reference: `_base92python.py` in the `base92` 2.0.0 package on PyPI, by the same author.
//!
//! Call base92_decoder.crack to use. It returns a `CrackResult`; its `unencrypted_text`
//! is `Some` if the text decoded.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The Base92 decoder, call:
/// `let base92_decoder = Decoder::<Base92Decoder>::new()` to create a new instance
/// And then call:
/// `result = base92_decoder.crack(input)` to decode a Base92 string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::base92_decoder::Base92Decoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_base92 = Decoder::<Base92Decoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_base92.crack("Fc_$aOTdKnsM*k", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hello world");
/// ```
pub struct Base92Decoder;

/// The 91 digits: `!`, then `#` to `_`, then `a` to `}`. A digit's value is its index.
const ALPHABET: [u8; 91] =
    *b"!#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_abcdefghijklmnopqrstuvwxyz{|}";

/// The value of every ASCII byte as a Base92 digit, or -1 if it isn't one.
const DIGIT_VALUES: [i8; 128] = {
    let mut table = [-1; 128];
    let mut value = 0;
    while value < ALPHABET.len() {
        table[ALPHABET[value] as usize] = value as i8;
        value += 1;
    }
    table
};

/// Two digits hold 13 bits, so a pair worth this much or more (`}$` and up) is invalid.
const PAIR_LIMIT: u32 = 1 << 13;

/// A lone final digit holds 6 bits, so it has to be worth less than this (`!` to `b`).
const LAST_DIGIT_LIMIT: u32 = 1 << 6;

impl Crack for Decoder<Base92Decoder> {
    fn new() -> Decoder<Base92Decoder> {
        Decoder {
            name: "Base92",
            description: "Base92 (thenoviceoof) packs 13 bits into two characters from 91 printable ASCII symbols; ~ encodes empty input.",
            link: "https://github.com/thenoviceoof/base92",
            tags: vec!["base92", "decoder", "base"],
            popularity: 0.3,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns a `CrackResult` with `unencrypted_text` set if the text decoded
    /// Else `unencrypted_text` is `None` and the reason is logged
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Base92 with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let encoded = text.trim();
        if !looks_like_base92(encoded) {
            debug!("Failed to decode Base92 because the text failed the length, alphabet or symbol pre-check");
            return results;
        }

        let Some(decoded_text) = decode_base92(encoded).and_then(printable_utf8) else {
            debug!("Failed to decode Base92 because a digit pair overflowed or the output isn't printable UTF-8");
            return results;
        };

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Base92 because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);

        results.update_checker(&checker_result);

        results
    }
    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// The value of `byte` as a Base92 digit, or `None` if it isn't one.
fn digit_value(byte: u8) -> Option<u32> {
    match DIGIT_VALUES.get(usize::from(byte)) {
        Some(&value) if value >= 0 => Some(value as u32),
        _ => None,
    }
}

/// Cheap structural checks, so the search spends almost nothing on text that isn't Base92.
/// The text needs at least two characters (one can't hold a byte, and `~` stands for no
/// bytes at all), only digits, and at least one digit that isn't a letter or a number:
/// Base92 output of 10 or more characters is all letters and numbers less than 2% of the
/// time, while single words, hex, Base58 and Base64 without padding always are. Sentences
/// fail on their first space, and `"`, `` ` ``, `~` and non-ASCII fail too.
fn looks_like_base92(text: &str) -> bool {
    if text.len() < 2 {
        return false;
    }
    let mut has_symbol = false;
    for &byte in text.as_bytes() {
        if digit_value(byte).is_none() {
            return false;
        }
        has_symbol |= !byte.is_ascii_alphanumeric();
    }
    has_symbol
}

/// Decodes Base92 to bytes like `base92.decode` from the `base92` 2.0.0 package: pairs of
/// digits as 13 bits, a lone final digit as 6 bits, every complete byte kept and the
/// padding bits at the end dropped. `~` decodes to no bytes.
///
/// Returns `None` if `text` has a character that isn't a digit, is a single digit, or has a
/// pair worth 8192 or more, which no encoder writes. Unlike the reference, a lone final
/// digit worth 64 or more (`c` to `}`) is rejected too: an encoder only puts 6 bits there,
/// and the reference decoder ORs the 7th into the byte before while CyberChef reads it as
/// 7 bits, so such text has no agreed meaning.
fn decode_base92(text: &str) -> Option<Vec<u8>> {
    let text = text.as_bytes();
    if text == b"~" {
        return Some(Vec::new());
    }
    if text.len() == 1 {
        return None;
    }

    // Every two digits (16 bits of input) hold 13 bits, so the output is shorter.
    let mut decoded = Vec::with_capacity(text.len());
    // The bits not written out yet are the low `bits` bits of `buffer`; at most 7 + 13.
    let mut buffer: u32 = 0;
    let mut bits = 0;
    let (pairs, last) = text.as_chunks::<2>();
    for &[high, low] in pairs {
        let value = digit_value(high)? * 91 + digit_value(low)?;
        if value >= PAIR_LIMIT {
            return None;
        }
        buffer = (buffer << 13) | value;
        bits += 13;
        while bits >= 8 {
            bits -= 8;
            decoded.push((buffer >> bits) as u8);
        }
        buffer &= (1 << bits) - 1;
    }
    if let &[last] = last {
        let value = digit_value(last)?;
        if value >= LAST_DIGIT_LIMIT {
            return None;
        }
        buffer = (buffer << 6) | value;
        bits += 6;
        if bits >= 8 {
            decoded.push((buffer >> (bits - 8)) as u8);
        }
    }
    Some(decoded)
}

/// The decoded bytes as text, if they are valid UTF-8 without control characters other
/// than tab, CR and LF. Almost any string without spaces fits the 91-digit alphabet, so
/// this keeps binary garbage out of the search.
fn printable_utf8(bytes: Vec<u8>) -> Option<String> {
    let text = String::from_utf8(bytes).ok()?;
    let printable = text
        .chars()
        .all(|c| !c.is_control() || matches!(c, '\t' | '\r' | '\n'));
    printable.then_some(text)
}

#[cfg(test)]
mod tests {
    use super::{decode_base92, Base92Decoder, ALPHABET};
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            lemmeknow_checker::LemmeKnow,
            CheckerTypes,
        },
        decoders::interface::{Crack, Decoder},
    };

    /// The Athena checker, which the search uses.
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    /// Decodes `text` with the Athena checker and returns the decoded text, if any.
    fn crack(text: &str) -> Option<String> {
        Decoder::<Base92Decoder>::new()
            .crack(text, &get_athena_checker())
            .unencrypted_text
            .map(|texts| texts[0].clone())
    }

    /// Decodes `text` with the Athena checker and asserts that it accepts `plaintext`.
    fn assert_cracked(text: &str, plaintext: &str) {
        let result = Decoder::<Base92Decoder>::new().crack(text, &get_athena_checker());
        assert_eq!(result.unencrypted_text.unwrap()[0], plaintext);
        assert!(result.success, "Athena should accept {plaintext:?}");
    }

    /// Base92-encodes `bytes` the way `base92.encode` from the `base92` 2.0.0 package does,
    /// so the decoder can be checked against an encoder.
    fn encode_base92(bytes: &[u8]) -> String {
        if bytes.is_empty() {
            return "~".to_string();
        }
        let digit = |value: u32| char::from(ALPHABET[value as usize]);
        let mut encoded = String::new();
        let mut buffer: u32 = 0;
        let mut bits = 0;
        for &byte in bytes {
            buffer = (buffer << 8) | u32::from(byte);
            bits += 8;
            while bits >= 13 {
                bits -= 13;
                let value = buffer >> bits;
                encoded.push(digit(value / 91));
                encoded.push(digit(value % 91));
                buffer &= (1 << bits) - 1;
            }
        }
        match bits {
            0 => {}
            1..=6 => encoded.push(digit(buffer << (6 - bits))),
            _ => {
                let value = buffer << (13 - bits);
                encoded.push(digit(value / 91));
                encoded.push(digit(value % 91));
            }
        }
        encoded
    }

    // Unless a test says otherwise, every vector was made with `base92.encode` from the
    // `base92` 2.0.0 package on PyPI, decoded back with `base92.decode`, and decodes the
    // same with CyberChef's "From Base92" algorithm (src/core/operations/FromBase92.mjs).

    /// The bench suite's medium plaintext.
    const MEDIUM: &str =
        "Meet me at the old lighthouse after midnight and bring the map, the key and a torch.";

    /// `MEDIUM`, Base92-encoded.
    const MEDIUM_BASE92: &str = "=5^dl?57>ogS$p[GEU&taJ'bhnke,79eK=H4OSb$:es:+Z<HHn1kZu'b*&iH*]UkHms3ld3j$FgR%s#;Fc[a_%e>$.p\\$p%1JxvkSl**";

    #[test]
    fn base92_decodes_hello_world() {
        // The example in the base92 README
        assert_cracked("Fc_$aOTdKnsM*k", "hello world");
    }

    #[test]
    fn base92_decodes_quick_brown_fox() {
        assert_cracked(
            "?a&JO[d]VmnA*]UqK}gxX'e.$@uWBEWlI3j{iP6LQ78l*UmM-ESuI",
            "The quick brown fox jumps over the lazy dog",
        );
    }

    #[test]
    fn base92_decodes_hello() {
        // 40 bits: three pairs and a final single digit
        assert_cracked(";K_$aOB", "Hello");
    }

    #[test]
    fn base92_decodes_ctf_flag() {
        assert_cracked("F#S<YRa;;%F-kSUa3EGyX*cIV", "flag{b4s3_92_1s_fun}");
    }

    #[test]
    fn base92_decodes_bench_medium_text() {
        assert_cracked(MEDIUM_BASE92, MEDIUM);
    }

    #[test]
    fn base92_decodes_sphinx_pangram() {
        // The example in the issue. It decodes, but Athena does not recognise this
        // pangram, so only the decoded text is checked.
        assert_eq!(
            crack("?A&W\\;7-$Jjn*]DnDzE2hUa//lxw$p?HE=v5OYe>$XqEjU").unwrap(),
            "Sphinx of black quartz, judge my vow."
        );
    }

    #[test]
    fn base92_sets_unencrypted_text_when_the_checker_rejects_it() {
        // LemmeKnow only accepts things like IP addresses and URLs
        let checker = CheckerTypes::CheckLemmeKnow(Checker::<LemmeKnow>::new());
        let result = Decoder::<Base92Decoder>::new().crack("Fc_$aOTdKnsM*k", &checker);
        assert!(!result.success);
        assert_eq!(result.unencrypted_text.unwrap()[0], "hello world");
    }

    #[test]
    fn base92_decodes_every_output_length() {
        // 1, 2, 3 and 4 bytes: a pair, a pair and a single digit, two pairs, two pairs
        // and a single digit
        assert_eq!(decode_base92("D,"), Some(b"a".to_vec()));
        assert_eq!(decode_base92("D82"), Some(b"ab".to_vec()));
        assert_eq!(decode_base92("D8<q"), Some(b"abc".to_vec()));
        assert_eq!(decode_base92("D8<rF"), Some(b"abcd".to_vec()));
        assert_eq!(decode_base92(""), Some(Vec::new()));
        assert_eq!(decode_base92("~"), Some(Vec::new()));
        assert_eq!(crack("D8<rF").unwrap(), "abcd");
    }

    #[test]
    fn base92_pair_values_stop_at_8191() {
        // `}#` is 90 * 91 + 1 = 8191, thirteen 1 bits
        assert_eq!(decode_base92("}#"), Some(vec![0xFF]));
        assert_eq!(decode_base92("!!"), Some(vec![0x00]));
        // `}$` is 8192 and `}}` 8280. The reference decoder rejects both (CyberChef
        // writes out 14 bits instead).
        assert_eq!(decode_base92("}$"), None);
        assert_eq!(decode_base92("}}"), None);
        assert_eq!(decode_base92("Fc_$aOTdKnsM}}"), None);
        assert_eq!(crack("}$"), None);
        assert_eq!(crack("}}"), None);
    }

    #[test]
    fn base92_rejects_a_final_digit_above_6_bits() {
        // An encoder writes 6 bits in a lone final digit, so `!` to `b`. The reference
        // decoder turns `;K_$aOc` into "Helln" and CyberChef reads `c` as 7 bits.
        assert_eq!(decode_base92(";K_$aOb"), Some(b"Hello".to_vec()));
        assert_eq!(decode_base92(";K_$aOc"), None);
        assert_eq!(decode_base92(";K_$aO}"), None);
        assert_eq!(crack(";K_$aOc"), None);
    }

    #[test]
    fn base92_round_trips_through_the_reference_encoder() {
        // The test encoder reproduces the reference vectors...
        assert_eq!(encode_base92(b""), "~");
        assert_eq!(encode_base92(b"hello world"), "Fc_$aOTdKnsM*k");
        assert_eq!(encode_base92(b"Hello"), ";K_$aOB");
        assert_eq!(encode_base92(MEDIUM.as_bytes()), MEDIUM_BASE92);
        // ...and every length from 0 to 200 bytes, of pseudo-random bytes, decodes back
        let mut state: u32 = 0x9E37_79B9;
        for length in 0..=200 {
            let bytes: Vec<u8> = (0..length)
                .map(|_| {
                    state ^= state << 13;
                    state ^= state >> 17;
                    state ^= state << 5;
                    state as u8
                })
                .collect();
            let encoded = encode_base92(&bytes);
            assert_eq!(decode_base92(&encoded), Some(bytes), "{encoded:?}");
        }
    }

    #[test]
    fn base92_decodes_multibyte_utf8_and_whitespace() {
        assert_eq!(crack("Dy1i'/Tk0Y0i").unwrap(), "café ☕");
        assert_eq!(crack("t)y'X>@8").unwrap(), "日本");
        assert_eq!(crack("Jw1U/73o/M+1B").unwrap(), "tab\there\r\n");
    }

    #[test]
    fn base92_trims_surrounding_whitespace() {
        assert_eq!(crack("  Fc_$aOTdKnsM*k\n").unwrap(), "hello world");
    }

    #[test]
    fn base92_rejects_characters_outside_the_alphabet() {
        // Internal whitespace, `"`, `` ` `` and `~` anywhere, and non-ASCII
        assert_eq!(crack("Fc_$aOT dKnsM*k"), None);
        assert_eq!(crack("Fc_$a\"OTdKnsM*k"), None);
        assert_eq!(crack("Fc_$a`OTdKnsM*k"), None);
        assert_eq!(crack("Fc_$aOTdKnsM*k~"), None);
        assert_eq!(crack("~Fc_$aOTdKnsM*k"), None);
        assert_eq!(crack("Fc_$aOTdKnsM*ké"), None);
        assert_eq!(decode_base92("Fc_$aOT dKnsM*k"), None);
        assert_eq!(decode_base92("Fc_$aOTdKnsM*ké"), None);
    }

    #[test]
    fn base92_rejects_output_that_is_not_utf8() {
        // `}#` decodes to FF
        assert_eq!(crack("}#"), None);
    }

    #[test]
    fn base92_rejects_output_with_control_characters() {
        // "hi\x07there" (BEL), "a\x7fb" (DEL) and a NUL byte are valid UTF-8 but not text
        assert_eq!(decode_base92("Fd-Vld3o/M"), Some(b"hi\x07there".to_vec()));
        assert_eq!(crack("Fd-Vld3o/M"), None);
        assert_eq!(decode_base92("D;v)"), Some(b"a\x7fb".to_vec()));
        assert_eq!(crack("D;v)"), None);
        assert_eq!(crack("!!"), None);
    }

    #[test]
    fn base92_rejects_text_without_symbols() {
        // `D82` is valid Base92 for "ab", but text made only of letters and digits is far
        // more often a word, hex or Base64, so the pre-check skips it
        assert_eq!(decode_base92("D82"), Some(b"ab".to_vec()));
        assert_eq!(crack("D82"), None);
        assert_eq!(crack("Hello"), None);
        assert_eq!(crack("48656c6c6f"), None);
    }

    #[test]
    fn base92_rejects_too_short_text() {
        assert_eq!(decode_base92("a"), None);
        assert_eq!(crack("a"), None);
        assert_eq!(crack("~"), None);
        assert_eq!(crack("!"), None);
    }

    #[test]
    fn base92_rejects_other_base_encodings() {
        // Z85 and Base91 from their decoders' tests, RFC 1924 Base85 and Ascii85 (with and
        // without delimiters) of "hello world", and Base64
        for text in [
            "nm=QNzY&b1A+]nf",
            "TPwJh>Io2Tv!lE",
            "Xk~0{Zy<MXa%^M",
            "<~BOu!rD]j7BEbo7~>",
            "BOu!rD]j7BEbo7",
            "aGVsbG8gd29ybGQ=",
        ] {
            assert_eq!(crack(text), None, "{text:?}");
        }
    }

    #[test]
    fn base92_rejects_the_bench_miss_string() {
        assert_eq!(
            crack("T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV"),
            None
        );
    }

    #[test]
    fn base92_decode_empty_string() {
        assert_eq!(crack(""), None);
        assert_eq!(crack(" \t\n"), None);
    }

    #[test]
    fn base92_decode_handles_panics() {
        assert_eq!(crack("hello my name is panicky mc panic face!"), None);
        assert_eq!(crack("hello world"), None);
        assert_eq!(crack("a b"), None);
        assert_eq!(crack("\"hi\""), None);
    }

    #[test]
    fn base92_handle_panic_if_emoji() {
        assert_eq!(crack("😀"), None);
        assert_eq!(crack("😂😂😂😂😂"), None);
    }

    #[test]
    fn base92_decoder_metadata() {
        let decoder = Decoder::<Base92Decoder>::new();
        assert_eq!(decoder.get_name(), "Base92");
        assert_eq!(decoder.get_popularity(), 0.3);
        assert_eq!(decoder.get_link(), "https://github.com/thenoviceoof/base92");
        assert!(decoder.get_description().contains("13 bits"));
        for tag in ["base92", "decoder", "base"] {
            assert!(decoder.get_tags().contains(&tag), "missing tag {tag}");
        }
    }

    #[test]
    fn base92_is_registered() {
        let decoders = crate::filtration_system::get_decoder_by_name("Base92");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Base92");
        // Cached results name their decoders, so it has to be in DECODER_MAP too
        let mapped = crate::decoders::DECODER_MAP
            .get("Base92")
            .expect("Base92 should be in DECODER_MAP");
        assert_eq!(
            mapped.get::<crate::decoders::DecoderType>().get_name(),
            "Base92"
        );
    }
}
