//! Decode Base36: the bytes of the text written as one big-endian unsigned integer in radix
//! 36, with the digits `0-9` and the letters `a-z` (`a` = 10 … `z` = 35). `fuvrsivvnfrbjwajo`
//! is `hello world`.
//! Call base36_decoder.crack to use. It returns a `CrackResult` whose `unencrypted_text` is
//! `None` when the input isn't Base36.
//!
//! This is what Python's `int(text, 36).to_bytes(...)`, PyPI `base36.loads` and CyberChef's
//! `From Base` (radix 36) → `To Base` (16) → `From Hex` do. Letters may be upper or lower case,
//! but not both in one input: encoders write a single case, and mixed-case alphanumerics are
//! Base58, Base62 or Base64. Input that is only digits is left to the decimal decoders.
//!
//! dCode's "Base 36 cipher" is a different encoding, which writes every word as a base-36
//! number in decimal (`HELLO` is `29234652`). It isn't decoded here.
//!
//! References: <https://en.wikipedia.org/wiki/Base36>,
//! <https://gchq.github.io/CyberChef/#recipe=From_Base(36)To_Base(16)From_Hex('Auto')>,
//! <https://pypi.org/project/base36/>.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};
use num::BigUint;

/// The Base36 decoder, call:
/// `let base36_decoder = Decoder::<Base36Decoder>::new()` to create a new instance
/// And then call:
/// `result = base36_decoder.crack(input)` to decode a Base36 string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::base36_decoder::Base36Decoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_base36 = Decoder::<Base36Decoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_base36.crack("fuvrsivvnfrbjwajo", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hello world");
/// ```
pub struct Base36Decoder;

/// Inputs with fewer digits than this, not counting leading zeros, are rejected. Eight
/// digits are at least 36^7 ≈ 2^36, so at least 5 bytes: `hello` is `5pzcszu7`. Shorter
/// texts are too short to identify, and too much else decodes to printable UTF-8: 6.2 % of
/// random 6-digit strings, against 0.7 % of 8-digit ones and 0.9 % of English words of eight
/// or more letters.
const MIN_DIGITS: usize = 8;

/// Inputs longer than this are rejected. 1300 digits decode to at most 841 bytes, and the
/// search drops results and candidates of 821 to 5000 bytes anyway (see
/// `calculate_string_quality`). The cap bounds the big-integer work on every long
/// single-case alphanumeric string the search produces.
const MAX_LEN: usize = 1300;

impl Crack for Decoder<Base36Decoder> {
    fn new() -> Decoder<Base36Decoder> {
        Decoder {
            name: "Base36",
            description: "Base36 writes the bytes of the text as one big-endian integer in radix 36 using the digits 0-9 and letters a-z (case-insensitive). Used for short IDs and in CTFs; dCode's word-by-word 'Base 36 cipher' is not this mode.",
            link: "https://en.wikipedia.org/wiki/Base36",
            tags: vec!["base36", "decoder", "base"],
            popularity: 0.3,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes `text` as Base36 and checks the result with `checker`.
    /// `unencrypted_text` is `None` when `text` isn't Base36 of UTF-8 text.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Base36 with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_base36(text) else {
            debug!("Failed to decode Base36 because the text isn't Base36 of UTF-8 text");
            return results;
        };
        trace!("Decoded text for Base36: {:?}", decoded_text);

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Base36 because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Decodes Base36 to text, or returns `None` if `text` isn't Base36 of UTF-8 text without
/// control characters (tabs and line breaks are allowed).
fn decode_base36(text: &str) -> Option<String> {
    let digits = text.trim().as_bytes();
    if digits.len() > MAX_LEN {
        return None;
    }

    // A single scan that rejects almost every input before anything is allocated. It stops
    // at the first byte that isn't an ASCII letter or digit (spaces, `=`, `+`, `/`, `-`, `_`,
    // non-ASCII), and at the first letter in the other case: mixed case is Base58, Base62 or
    // Base64, not Base36.
    let mut has_lower = false;
    let mut has_upper = false;
    for &byte in digits {
        match byte {
            b'0'..=b'9' => {}
            b'a'..=b'z' if !has_upper => has_lower = true,
            b'A'..=b'Z' if !has_lower => has_upper = true,
            _ => return None,
        }
    }
    // Only digits (including empty input): decimal numbers belong to Decimal, A1Z26 and
    // dCode's "Base 36 cipher". This also means the number below is never zero.
    if !has_lower && !has_upper {
        return None;
    }
    let leading_zeros = digits.iter().take_while(|&&byte| byte == b'0').count();
    if digits.len() - leading_zeros < MIN_DIGITS {
        return None;
    }

    // `parse_bytes` alone isn't a validator: it also accepts a leading `+` and skips `_`.
    // The scan above has rejected both. It accepts either case.
    let number = BigUint::parse_bytes(digits, 36)?;
    let decoded = String::from_utf8(number.to_bytes_be()).ok()?;
    if decoded
        .chars()
        .any(|c| c.is_control() && !matches!(c, '\t' | '\n' | '\r'))
    {
        return None;
    }
    Some(decoded)
}

#[cfg(test)]
mod tests {
    use super::{decode_base36, Base36Decoder, MAX_LEN};
    use crate::checkers::athena::Athena;
    use crate::checkers::checker_type::{Check, Checker};
    use crate::checkers::CheckerTypes;
    use crate::decoders::crack_results::CrackResult;
    use crate::decoders::interface::{Crack, Decoder};
    use crate::decoders::{DecoderType, DECODER_MAP};
    use crate::filtration_system::get_decoder_by_name;

    // Every vector was checked with Python 3.9 (`int(text, 36).to_bytes(...)`, and encoded
    // with `int.from_bytes(data, "big")` written in radix 36 and round-tripped). The issue
    // plan also checked them with PyPI `base36` 0.1.1 `loads` and CyberChef 10.24
    // `From Base` (36) → `To Base` (16) → `From Hex`.
    // https://github.com/bee-san/Ciphey/issues/922

    /// "Meet me at the old lighthouse after midnight and bring the map, the key and a torch."
    /// in Base36, the bench `medium` input.
    const MEDIUM: &str = "a822v1oz8f1g6201c07e8y94rud6he0289o4d0fxi2pthhv60m2s9nfnu6qul2zwxpn8wdgzfebbb7rml6tb0hl2ze8kye5p1355vfz8nh9otnrvkqdmkecd8s6ratdg6m";
    const MEDIUM_PLAINTEXT: &str =
        "Meet me at the old lighthouse after midnight and bring the map, the key and a torch.";

    /// The 576-character bench `long` plaintext in Base36 (891 characters).
    const LONG: &str = "so9prlhidreohee7vqsbzqgjgjbislomh4zfqf7cr7dty1t0wk9h4246juaqptqdorc293hcqp4dqadd9wvuo3zf8klii9nbinprs1dbgzqldbxipnhncjpg08whsddclrkls0cqei18vw7n3376bwg9fejfup7jedcazxqlivitsxsn99fasliyd64f7hbjqsupshms5hx5td2h4wp0sgyivbkyepdre7852ids631vek03vxnoas21ym9fnw00ryo3bqxam556f58uehbptz3jnb5a868t2th0dvofsh1cp7tv43pfmmj7oll9hixlzl2l2xadbpbngm0prwdpwzvmvfabi2uaolw738atg2v6oaf1sdwh48hhdj5b8nzzh7dfcsaog1zk7glbs00e58mhr0y7867grmz00tzi1zw7q0j142auvuijuzq18u1w60c5560k40jqbagv3oomcagpa80hcr5hxks64kwmpy8cysuuy4kjctrpjr6i57dfd5q3jpzv0x8go92z0th7qxo2gxc8e3832n9pqu1sm5m9i04bz1wcmcvb6x1or5k6qoj734yl45ua8qotyxmwd9e9sbbvtaxl89hodhj2j1ia31mxdq7b3klzvbkep05l7vifkcddt55mnxv5qbst4ox6x26eok1h8tuyy07jz3os0mxlyj9nch1gepcjl7tl88sv4dt3lbpkgu6l5v8xwr8vf92cl1pxyvw58g7lf55z9po7x5k70mro38vg5rr9hnzj9el5qe0wj1gy8980uix4lu4xzwsuvp2fduqmgkb5k4mz50801dxss09fi2qf5l4uio9ziejotroeozja4jpa61z3qcsjtdzovg485kirbgu81vi68sncmr2";
    const LONG_PLAINTEXT: &str = "Ciphey is an automated decoding tool. You give it encrypted or encoded text and it tries to work out what was done to it, without you having to know the key or even the cipher. It searches through many possible decodings, checks each candidate to see whether it looks like English or matches a known pattern such as an email address, and stops when it finds something that reads like plaintext. Most of the time this takes less than a second, which makes it handy for capture the flag challenges, puzzle hunts and for anyone who stumbles across a strange string in a log file.";

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn crack_result(text: &str) -> CrackResult {
        Decoder::<Base36Decoder>::new().crack(text, &get_athena_checker())
    }

    // Runs the decoder with the Athena checker and returns the decoded text, if any
    fn crack(text: &str) -> Option<String> {
        let result = crack_result(text);
        if result.unencrypted_text.is_none() {
            assert!(!result.success, "{text:?} failed but was marked successful");
        }
        result.unencrypted_text.map(|texts| texts[0].clone())
    }

    // Asserts that Athena accepts what `text` decodes to, and that it is `plaintext`
    fn assert_identified(text: &str, plaintext: &str) {
        let result = crack_result(text);
        assert!(result.success, "Athena should accept {plaintext:?}");
        assert_eq!(result.unencrypted_text.unwrap()[0], plaintext);
    }

    #[test]
    fn decodes_the_issue_example() {
        assert_identified("fuvrsivvnfrbjwajo", "hello world");
    }

    #[test]
    fn decodes_upper_case() {
        // dCode and CyberChef's `To Base` write upper case
        assert_identified("FUVRSIVVNFRBJWAJO", "hello world");
    }

    #[test]
    fn decodes_leading_zero_digits() {
        assert_identified("00fuvrsivvnfrbjwajo", "hello world");
    }

    #[test]
    fn decodes_surrounding_whitespace() {
        assert_identified("  fuvrsivvnfrbjwajo\n", "hello world");
    }

    #[test]
    fn decodes_pangram() {
        assert_identified(
            "29t3ubyznhh32o9x3pzvljp1qa22wun2quo35naempn0gtx0lxiyrf3qwwi0lzu165j",
            "The quick brown fox jumps over the lazy dog",
        );
    }

    #[test]
    fn decodes_text_athena_does_not_identify() {
        // Decoded, but Athena doesn't take this pangram for English
        assert_eq!(
            crack("t6fss0bzhiga409xgixyoj42r05ennyc9q1jabi6hwoexpa60mtuihpv2").unwrap(),
            "Sphinx of black quartz, judge my vow."
        );
    }

    #[test]
    fn decodes_bench_medium() {
        assert_identified(MEDIUM, MEDIUM_PLAINTEXT);
    }

    #[test]
    fn decodes_bench_long() {
        assert_eq!(LONG.len(), 891);
        assert_identified(LONG, LONG_PLAINTEXT);
    }

    #[test]
    fn decodes_the_shortest_accepted_input() {
        // Eight digits, the minimum. Athena accepts `hello` with its password checker, so
        // only the decoded text is checked here.
        assert_eq!(crack("5pzcszu7").unwrap(), "hello");
    }

    #[test]
    fn decode_base36_returns_the_text() {
        assert_eq!(
            decode_base36("fuvrsivvnfrbjwajo").as_deref(),
            Some("hello world")
        );
    }

    #[test]
    fn decode_base36_caps_the_length() {
        // Zero digits in front don't change the value, so both inputs are valid Base36 of
        // the medium plaintext; only the length differs.
        let at_limit = format!("{}{MEDIUM}", "0".repeat(MAX_LEN - MEDIUM.len()));
        assert_eq!(at_limit.len(), 1300);
        assert_eq!(decode_base36(&at_limit).as_deref(), Some(MEDIUM_PLAINTEXT));

        let over_limit = format!("0{at_limit}");
        assert_eq!(over_limit.len(), 1301);
        assert_eq!(decode_base36(&over_limit), None);
    }

    #[test]
    fn fails_on_digits_only() {
        // dCode's "Base 36 cipher" of HELLO; that mode isn't decoded here
        assert_eq!(crack("29234652"), None);
        assert_eq!(crack("00000000"), None);
        assert_eq!(crack("0"), None);
    }

    #[test]
    fn fails_on_mixed_case() {
        assert_eq!(crack("Fuvrsivvnfrbjwajo"), None);
        assert_eq!(crack("fuvrsivvnfrbjwajO"), None);
    }

    #[test]
    fn fails_with_fewer_than_eight_digits() {
        assert_eq!(crack("abcdefg"), None);
        // Leading zeros don't count
        assert_eq!(crack("0000abcdefg"), None);
    }

    #[test]
    fn fails_when_the_bytes_are_not_utf8() {
        // 02 E6 5F ...: the issue example without its last digit
        assert_eq!(crack("fuvrsivvnfrbjwaj"), None);
        // F4 6F 1B D2 A7
        assert_eq!(crack("deadbeef"), None);
        // 93 BE 69 ...: the hex of "hello world" is valid Base36 input too
        assert_eq!(crack("68656c6c6f20776f726c64"), None);
        // Unpadded Base32 of "hello world"
        assert_eq!(crack("NBSWY3DPEB3W64TMMQ"), None);
    }

    #[test]
    fn fails_on_control_characters() {
        // 07 C3 17 ...: a single English word of eight or more letters is valid input
        assert_eq!(crack("lighthouse"), None);
        // 02 90 D7 40 FF FF
        assert_eq!(crack("zzzzzzzz"), None);
    }

    #[test]
    fn fails_on_what_parse_bytes_would_accept() {
        // num-bigint accepts a leading `+` and skips `_`
        assert_eq!(crack("+fuvrsivvnfrbjwajo"), None);
        assert_eq!(crack("fuvrsivv_nfrbjwajo"), None);
    }

    #[test]
    fn fails_on_other_encodings() {
        // Base58 Bitcoin of "hello world"
        assert_eq!(crack("StV1DL6CwTryKyV"), None);
        // Base64 of "hello world"
        assert_eq!(crack("aGVsbG8gd29ybGQ="), None);
    }

    #[test]
    fn fails_on_the_bench_miss_input() {
        assert_eq!(
            crack("T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV"),
            None
        );
    }

    #[test]
    fn fails_on_english() {
        assert_eq!(crack("hello world"), None);
        assert_eq!(crack("hello my name is panicky mc panic face!"), None);
    }

    #[test]
    fn handles_panic_if_empty_string() {
        assert_eq!(crack(""), None);
    }

    #[test]
    fn handles_panic_if_whitespace() {
        assert_eq!(crack("   "), None);
    }

    #[test]
    fn handles_panic_if_emoji() {
        assert_eq!(crack("😀"), None);
        assert_eq!(crack("fuvrsivvnfrbjwajo😀"), None);
    }

    #[test]
    fn is_registered() {
        // Exactly one decoder by that name runs in the search
        let decoders = get_decoder_by_name("Base36");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Base36");
        // Cached results name the decoder; reading them back looks it up here
        let decoder = DECODER_MAP
            .get("Base36")
            .expect("Base36 should be in DECODER_MAP")
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "Base36");
    }
}
