//! Decode Base85 with the RFC 1924 alphabet, as used by git binary patches and
//! Python's `base64.b85encode`.
//!
//! Every 4 bytes become 5 base-85 digits, most significant first. The alphabet is
//! ``0-9A-Za-z!#$%&()*+-;<=>?@^_`{|}~`` and a digit's value is its index. A final group of
//! n bytes (1 to 3) is written as n + 1 characters. Unlike Ascii85 there are no `<~ ~>`
//! delimiters, no whitespace and no `z` shortcut: four zero bytes encode as `00000`.
//! Reference: <https://datatracker.ietf.org/doc/html/rfc1924>
//!
//! Call base85_decoder.crack to use. It returns a `CrackResult`; its `unencrypted_text`
//! is `Some` if the text decoded.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The Base85 (RFC 1924) decoder, call:
/// `let base85_decoder = Decoder::<Base85Decoder>::new()` to create a new instance
/// And then call:
/// `result = base85_decoder.crack(input)` to decode a Base85 string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::base85_decoder::Base85Decoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_base85 = Decoder::<Base85Decoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_base85.crack("Xk~0{Zy<MXa%^M", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hello world");
/// ```
pub struct Base85Decoder;

/// The RFC 1924 alphabet. A digit's value is its index.
const ALPHABET: [u8; 85] =
    *b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz!#$%&()*+-;<=>?@^_`{|}~";

/// The value of every ASCII byte as a Base85 digit, or -1 if it isn't one.
const DIGIT_VALUES: [i8; 128] = {
    let mut table = [-1; 128];
    let mut value = 0;
    while value < ALPHABET.len() {
        table[ALPHABET[value] as usize] = value as i8;
        value += 1;
    }
    table
};

/// The digit `~`, which pads a short final group.
const HIGHEST_DIGIT: u64 = 84;

impl Crack for Decoder<Base85Decoder> {
    fn new() -> Decoder<Base85Decoder> {
        Decoder {
            name: "Base85",
            description: "Base85 with the RFC 1924 alphabet (0-9, A-Z, a-z and !#$%&()*+-;<=>?@^_`{|}~), as used by git binary patches and Python's base64.b85encode. Every four bytes are written as five base-85 digits.",
            link: "https://datatracker.ietf.org/doc/html/rfc1924",
            tags: vec!["base85", "rfc1924", "decoder", "base"],
            popularity: 0.3,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns a `CrackResult` with `unencrypted_text` set if the text decoded
    /// Else `unencrypted_text` is `None` and the reason is logged
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Base85 with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let encoded = text.trim();
        if !looks_like_base85(encoded) {
            debug!("Failed to decode Base85 because the text failed the alphabet, length or symbol pre-check");
            return results;
        }

        let Some(decoded_text) = decode_base85(encoded).and_then(printable_utf8) else {
            debug!("Failed to decode Base85 because a group overflowed or the output isn't printable UTF-8");
            return results;
        };

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Base85 because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);

        results.update_checker(&checker_result);

        results
    }
    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// The value of `byte` as a Base85 digit, or `None` if it isn't one.
fn digit_value(byte: u8) -> Option<u64> {
    match DIGIT_VALUES.get(usize::from(byte)) {
        Some(&value) if value >= 0 => Some(value as u64),
        _ => None,
    }
}

/// Cheap structural checks, so the search spends almost nothing on text that isn't Base85.
/// The text must be non-empty, have a length an encoder can produce (a lone trailing digit
/// can't hold a byte), use only the alphabet, and contain at least one symbol: text made
/// only of letters and digits is far more often a word, Base62 or Base64. Sentences
/// (spaces) fail the alphabet check, as do Z85 with any of `.` `/` `:` `[` `]` and Ascii85
/// with any of `"` `'` `,` `.` `/` `:` `[` `\` `]`.
fn looks_like_base85(text: &str) -> bool {
    if text.is_empty() || text.len() % 5 == 1 {
        return false;
    }
    let mut has_symbol = false;
    for &byte in text.as_bytes() {
        if digit_value(byte).is_none() {
            return false;
        }
        has_symbol |= !byte.is_ascii_alphanumeric();
    }
    has_symbol
}

/// Decodes RFC 1924 Base85 to bytes. Returns `None` if `text` contains a character outside
/// the alphabet, has a length no encoder produces, or a group is larger than `u32::MAX`
/// (`|NsC0` is the largest). Like Python's `base64.b85decode`, a final group of n
/// characters is padded with `~` and yields its first n - 1 bytes.
fn decode_base85(text: &str) -> Option<Vec<u8>> {
    let text = text.as_bytes();
    if text.len() % 5 == 1 {
        return None;
    }

    let mut decoded = Vec::with_capacity(text.len() / 5 * 4 + 3);
    for group in text.chunks(5) {
        let mut value: u64 = 0;
        for position in 0..5 {
            let digit = match group.get(position) {
                Some(&byte) => digit_value(byte)?,
                None => HIGHEST_DIGIT,
            };
            value = value * 85 + digit;
        }
        let value = u32::try_from(value).ok()?;
        decoded.extend_from_slice(&value.to_be_bytes()[..group.len() - 1]);
    }
    Some(decoded)
}

/// The decoded bytes as text, if they are valid UTF-8 without control characters other
/// than tab, CR and LF. Almost any string without spaces fits the 85-character alphabet,
/// so this keeps binary garbage out of the search.
fn printable_utf8(bytes: Vec<u8>) -> Option<String> {
    let text = String::from_utf8(bytes).ok()?;
    let printable = text
        .chars()
        .all(|c| !c.is_control() || matches!(c, '\t' | '\r' | '\n'));
    printable.then_some(text)
}

#[cfg(test)]
mod tests {
    use super::{decode_base85, Base85Decoder};
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            lemmeknow_checker::LemmeKnow,
            CheckerTypes,
        },
        decoders::interface::{Crack, Decoder},
    };

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    /// Decodes `text` with the Athena checker and returns the decoded text, if any.
    fn crack(text: &str) -> Option<String> {
        Decoder::<Base85Decoder>::new()
            .crack(text, &get_athena_checker())
            .unencrypted_text
            .map(|texts| texts[0].clone())
    }

    // Test vectors were made with Python 3 `base64.b85encode` and checked with
    // `base64.b85decode` and CyberChef's "From Base85" with the alphabet
    // 0-9A-Za-z!#$%&()*+\-;<=>?@^_`{|}~ (the RFC 1924 / IPv6 alphabet).

    #[test]
    fn base85_decodes_hello_world() {
        assert_eq!(crack("Xk~0{Zy<MXa%^M").unwrap(), "hello world");
    }

    #[test]
    fn base85_decodes_quick_brown_fox() {
        let result = Decoder::<Base85Decoder>::new().crack(
            "RA^-&adl~9Yan8BZ+C7WW^Z^PYISXJb0BYaWpW^NXk{R5VS0HWWN&8",
            &get_athena_checker(),
        );
        assert_eq!(
            result.unencrypted_text.unwrap()[0],
            "The quick brown fox jumps over the lazy dog"
        );
        assert!(result.success, "Athena should accept the plaintext");
    }

    #[test]
    fn base85_decodes_sphinx_pangram() {
        // Athena does not recognise this pangram, but the decoded text is still returned
        assert_eq!(
            crack("Q*dZ$Zg?PXW*}m0VPk6`adlyGbb2fxYIS61Wgu;NAa-weE&").unwrap(),
            "Sphinx of black quartz, judge my vow."
        );
    }

    #[test]
    fn base85_sets_unencrypted_text_when_the_checker_rejects_it() {
        // LemmeKnow only accepts things like IP addresses and URLs
        let checker = CheckerTypes::CheckLemmeKnow(Checker::<LemmeKnow>::new());
        let result = Decoder::<Base85Decoder>::new().crack("Xk~0{Zy<MXa%^M", &checker);
        assert!(!result.success);
        assert_eq!(result.unencrypted_text.unwrap()[0], "hello world");
    }

    #[test]
    fn base85_decodes_short_final_groups() {
        // 1, 2 and 3 trailing bytes are written as 2, 3 and 4 characters
        assert_eq!(decode_base85("VE"), Some(b"a".to_vec()));
        assert_eq!(decode_base85("VPX"), Some(b"ab".to_vec()));
        assert_eq!(decode_base85("VPaz"), Some(b"abc".to_vec()));
        assert_eq!(decode_base85("VPa!s"), Some(b"abcd".to_vec()));
        assert_eq!(decode_base85(""), Some(Vec::new()));
        assert_eq!(crack("VPa!s").unwrap(), "abcd");
    }

    #[test]
    fn base85_decodes_multibyte_utf8_and_whitespace() {
        assert_eq!(crack("V_{~)sUYH*l>").unwrap(), "café ☕");
        assert_eq!(crack("bYWr%Xk~I`4GI").unwrap(), "tab\there\r\n");
    }

    #[test]
    fn base85_trims_surrounding_whitespace() {
        assert_eq!(crack("  Xk~0{Zy<MXa%^M\n").unwrap(), "hello world");
    }

    #[test]
    fn base85_z_is_an_ordinary_digit() {
        // In Ascii85 `z` stands for four zero bytes; in RFC 1924 it is the digit 61
        assert_eq!(decode_base85("O<`^z"), Some(b"Man ".to_vec()));
        assert_eq!(decode_base85("00000"), Some(vec![0; 4]));
    }

    #[test]
    fn base85_largest_group_is_u32_max() {
        assert_eq!(decode_base85("|NsC0"), Some(vec![0xFF; 4]));
    }

    #[test]
    fn base85_rejects_overflowing_groups() {
        assert_eq!(decode_base85("|NsC1"), None);
        assert_eq!(decode_base85("~~~~~"), None);
        // a short final group is padded with `~`, which can overflow too
        assert_eq!(decode_base85("|NsC"), None);
        assert_eq!(crack("|NsC1"), None);
        assert_eq!(crack("~~~~~"), None);
        assert_eq!(crack("Xk~0{~~~~~"), None);
    }

    #[test]
    fn base85_rejects_output_that_is_not_utf8() {
        // `|NsC0` decodes to FF FF FF FF
        assert_eq!(crack("|NsC0"), None);
    }

    #[test]
    fn base85_rejects_output_with_control_characters() {
        // "hi\x07there", valid UTF-8 but with a BEL character
        assert_eq!(decode_base85("XlVy@Xk~I`"), Some(b"hi\x07there".to_vec()));
        assert_eq!(crack("XlVy@Xk~I`"), None);
    }

    #[test]
    fn base85_rejects_lengths_no_encoder_produces() {
        // A lone trailing digit can't hold a byte. Python ignores it, we reject the text.
        assert_eq!(decode_base85("Xk~0{Z"), None);
        assert_eq!(crack("Xk~0{Z"), None);
        assert_eq!(crack("~"), None);
    }

    #[test]
    fn base85_rejects_text_without_symbols() {
        // `VPX` is valid Base85 for "ab", but text made only of letters and digits is far
        // more often a word, Base62 or Base64, so the pre-check skips it
        assert_eq!(decode_base85("VPX"), Some(b"ab".to_vec()));
        assert_eq!(crack("VPX"), None);
        assert_eq!(crack("HelloWorld"), None);
    }

    #[test]
    fn base85_rejects_z85() {
        // Z85 for "Hello World!", from z85_decoder.rs. `]` isn't in the RFC 1924 alphabet.
        assert_eq!(crack("nm=QNzY&b1A+]nf"), None);
    }

    #[test]
    fn base85_rejects_ascii85() {
        // Ascii85 for "Hello World" (Python `base64.a85encode`), with and without delimiters
        assert_eq!(crack("87cURD]i,\"Ebo7"), None);
        assert_eq!(crack("<~87cURD]i,\"Ebo7~>"), None);
    }

    #[test]
    fn base85_decode_empty_string() {
        assert_eq!(crack(""), None);
        assert_eq!(crack(" \t\n"), None);
    }

    #[test]
    fn base85_decode_handles_panics() {
        assert_eq!(crack("hello my name is panicky mc panic face!"), None);
        assert_eq!(crack("hello world"), None);
    }

    #[test]
    fn base85_handle_panic_if_emoji() {
        assert_eq!(crack("😀"), None);
        assert_eq!(crack("😂😂😂😂😂"), None);
    }

    #[test]
    fn base85_decoder_metadata() {
        let decoder = Decoder::<Base85Decoder>::new();
        assert_eq!(decoder.get_name(), "Base85");
        assert_eq!(decoder.get_popularity(), 0.3);
        assert_eq!(
            decoder.get_link(),
            "https://datatracker.ietf.org/doc/html/rfc1924"
        );
        assert!(decoder.get_description().contains("RFC 1924 alphabet"));
        for tag in ["base85", "rfc1924", "decoder", "base"] {
            assert!(decoder.get_tags().contains(&tag), "missing tag {tag}");
        }
    }

    #[test]
    fn base85_is_registered() {
        let decoders = crate::filtration_system::get_decoder_by_name("Base85");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Base85");
        // Cached results name their decoders, so it has to be in DECODER_MAP too
        let mapped = crate::decoders::DECODER_MAP
            .get("Base85")
            .expect("Base85 should be in DECODER_MAP");
        assert_eq!(
            mapped.get::<crate::decoders::DecoderType>().get_name(),
            "Base85"
        );
    }
}
