//! Decode Baudot code: ITA2 (International Telegraph Alphabet No. 2, the Baudot–Murray
//! code), the 5-bit teleprinter code, written as groups of `0`s and `1`s.
//!
//! Each character is a group of five bits, a value from 0 to 31 read most significant
//! bit first: `00011` is 3, which is `A`. That is Wikipedia's "543·21" column, dCode's
//! default and the table Python Ciphey shipped. There are two tables: `11011` (FIGS)
//! switches to the figures, `11111` (LTRS) back to the letters, and decoding starts in
//! the letters. NUL, CR, BEL and ENQ print nothing, and LF is a new line.
//!
//! The figures of the ITA2 standard and of the US teletypewriter variant (US-TTY) differ
//! in six codes; dCode and Python Ciphey use US-TTY. Some sources write the bits in
//! transmission order, least significant bit first (`11000` for `A`), which is the same
//! code with each group reversed. So there are up to four readings, checked in this
//! order:
//!
//! * most significant bit first, with the US-TTY figures, then with the ITA2 figures if
//!   the input uses one of the six codes where they differ,
//! * the same least significant bit first. These readings are only returned when the
//!   checker identifies them: the reversed reading of ordinary Baudot is junk that a
//!   lenient English check can accept.
//!
//! The first reading the checker identifies wins, unless only a lenient English check
//! accepted it and a reversed reading does better: for text written least significant
//! bit first, it is the most-significant-bit-first reading that is junk.
//!
//! References: <https://en.wikipedia.org/wiki/Baudot_code#ITA_2_and_US-TTY>,
//! <https://www.dcode.fr/baudot-code> and the tables of the PyPI package `baudot` 0.1.1
//! (`ITA2_STANDARD` and `ITA2_US`).

use crate::checkers::checker_result::CheckResult;
use crate::checkers::checker_type::{Check, Checker};
use crate::checkers::english::EnglishChecker;
use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, trace};

/// Bits per character.
const GROUP_LEN: usize = 5;

/// The fewest characters (five-bit groups) an input needs to be worth decoding.
const MIN_CODES: usize = 3;

/// Shift to figures: the codes after it are read with the figures table.
const FIGS: u8 = 0b11011;

/// Shift to letters: the codes after it are read with the letters table.
const LTRS: u8 = 0b11111;

/// Stands for a code that prints nothing in the tables below: NUL, CR, BEL and ENQ.
/// FIGS and LTRS are handled before the tables are read.
const NOTHING: char = '\0';

/// The letters, the same in ITA2 and US-TTY, indexed by code.
const LETTERS: [char; 32] = [
    NOTHING, 'E', '\n', 'A', ' ', 'S', 'I', 'U', // 00000 to 00111
    NOTHING, 'D', 'R', 'J', 'N', 'F', 'C', 'K', // 01000 to 01111
    'T', 'Z', 'L', 'W', 'H', 'Y', 'P', 'Q', // 10000 to 10111
    'O', 'B', 'G', NOTHING, 'M', 'X', 'V', NOTHING, // 11000 to 11111
];

/// The US-TTY figures, indexed by code. `00101` (S) is BEL.
const FIGURES_US_TTY: [char; 32] = [
    NOTHING, '3', '\n', '-', ' ', NOTHING, '8', '7', // 00000 to 00111
    NOTHING, '$', '4', '\'', ',', '!', ':', '(', // 01000 to 01111
    '5', '"', ')', '2', '#', '6', '0', '1', // 10000 to 10111
    '9', '?', '&', NOTHING, '.', '/', ';', NOTHING, // 11000 to 11111
];

/// The ITA2 standard figures, indexed by code. `01001` (D) is ENQ ("who are you?") and
/// `01011` (J) is BEL. They differ from the US-TTY figures at S, D, J, Z, H and V.
const FIGURES_ITA2: [char; 32] = [
    NOTHING, '3', '\n', '-', ' ', '\'', '8', '7', // 00000 to 00111
    NOTHING, NOTHING, '4', NOTHING, ',', '!', ':', '(', // 01000 to 01111
    '5', '+', ')', '2', '£', '6', '0', '1', // 10000 to 10111
    '9', '?', '&', NOTHING, '.', '/', '=', NOTHING, // 11000 to 11111
];

/// Each code with its five bits in reverse order, to read groups written least
/// significant bit first.
const REV5: [u8; 32] = {
    let mut table = [0; 32];
    let mut code = 0;
    while code < 32 {
        table[code] = (((code & 1) << 4)
            | ((code & 2) << 2)
            | (code & 4)
            | ((code & 8) >> 2)
            | ((code & 16) >> 4)) as u8;
        code += 1;
    }
    table
};

/// `CrackResult::key` for each reading: the bit order, then the figures table. The bit
/// orders are in the order they are tried.
const KEYS: [[&str; 2]; 2] = [
    ["MSB-first, US-TTY", "MSB-first, ITA2"],
    ["LSB-first, US-TTY", "LSB-first, ITA2"],
];

/// The Baudot decoder, call:
/// `let baudot_decoder = Decoder::<BaudotDecoder>::new()` to create a new instance
/// And then call:
/// `result = baudot_decoder.crack(input)` to decode Baudot code
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::baudot_decoder::BaudotDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_baudot = Decoder::<BaudotDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_baudot.crack(
///     "10100 00001 10010 10010 11000 00100 10011 11000 01010 10010 01001",
///     &checker,
/// );
/// assert!(result.success);
/// assert_eq!(result.unencrypted_text.unwrap()[0], "HELLO WORLD");
/// // The bit order and the figures table of the reading
/// assert_eq!(result.key.unwrap(), "MSB-first, US-TTY");
/// ```
pub struct BaudotDecoder;

impl Crack for Decoder<BaudotDecoder> {
    fn new() -> Decoder<BaudotDecoder> {
        Decoder {
            name: "Baudot",
            description: "Baudot / ITA2 5-bit teleprinter code with LTRS and FIGS shifts (ITA2 and US-TTY figures)",
            link: "https://en.wikipedia.org/wiki/Baudot_code",
            tags: vec!["baudot", "ita2", "teleprinter", "decoder"],
            popularity: 0.3,
            phantom: std::marker::PhantomData,
        }
    }

    /// Checks the most-significant-bit-first readings, then the reversed ones, and
    /// returns the first the checker identifies, unless only a lenient English check
    /// accepted it and a reversed reading reads better. Otherwise returns the
    /// most-significant-bit-first readings for the search to try.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Baudot with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(codes) = parse_codes(text) else {
            debug!("Failed to decode Baudot: the input isn't groups of five 0s and 1s");
            return results;
        };

        let msb_first = readings(&codes, KEYS[0], text);
        let msb_hit = match identify(&msb_first, checker) {
            Some(hit) if hit.is_confident() => return hit.into_result(results),
            msb_hit => msb_hit,
        };

        // Nothing was identified, or only by a lenient English check. Text written least
        // significant bit first reads as junk the other way round, and English-looking
        // junk can scrape past that check: the reversed pangram in the tests does.
        let reversed: Vec<u8> = codes.iter().map(|&code| REV5[usize::from(code)]).collect();
        let lsb_first = readings(&reversed, KEYS[1], text);
        if let Some(hit) = identify(&lsb_first, checker) {
            if msb_hit.is_none() || hit.is_confident() {
                return hit.into_result(results);
            }
        }
        if let Some(hit) = msb_hit {
            return hit.into_result(results);
        }

        // Nothing was identified as plaintext. The reversed readings are dropped: they
        // are junk for ordinary Baudot, and English-looking junk can mislead the search.
        if msb_first.is_empty() {
            debug!("Failed to decode Baudot: no reading has a letter or a digit");
        } else {
            results.unencrypted_text =
                Some(msb_first.into_iter().map(|reading| reading.text).collect());
        }
        results
    }
    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// One way of reading the input, and what it decodes to.
#[derive(Debug)]
struct Reading {
    /// The decoded text.
    text: String,
    /// The bit order and the figures table, such as `MSB-first, US-TTY`.
    key: &'static str,
}

/// The pre-check and parser: the codes (0 to 31) of `text`, read most significant bit
/// first, or `None` if `text` isn't Baudot.
///
/// One pass over the bytes, which stops at the first byte that rules the input out
/// (ordinary text fails on its first letter). Every byte must be `0`, `1` or ASCII
/// whitespace. With more than one whitespace-separated token, every token must be one
/// five-bit group, which rejects 8-bit binary such as `01001000 01100101` at its second
/// token; a single token must be a whole number of groups. At least `MIN_CODES` groups.
fn parse_codes(text: &str) -> Option<Vec<u8>> {
    let mut codes = Vec::new();
    // The code being read and how many of its bits have been read
    let mut code = 0;
    let mut bits = 0;
    // Bits in the current token and in the first token, and the tokens finished so far
    let mut token_len = 0;
    let mut first_token_len = 0;
    let mut tokens = 0;
    // The extra space ends the last token, so it is checked like the others.
    for &byte in text.trim().as_bytes().iter().chain(b" ") {
        match byte {
            b'0' | b'1' => {
                // Tokens after the first: the groups are written one per token, so this
                // one and the first one must be exactly one group long.
                if tokens > 0 && (first_token_len != GROUP_LEN || token_len == GROUP_LEN) {
                    return None;
                }
                token_len += 1;
                code = (code << 1) | (byte - b'0');
                bits += 1;
                if bits == GROUP_LEN {
                    codes.push(code);
                    code = 0;
                    bits = 0;
                }
            }
            byte if byte.is_ascii_whitespace() => {
                if token_len == 0 {
                    continue;
                }
                if tokens == 0 {
                    first_token_len = token_len;
                } else if token_len != GROUP_LEN {
                    return None;
                }
                tokens += 1;
                token_len = 0;
            }
            _ => return None,
        }
    }
    // A single token that isn't a whole number of groups leaves bits over.
    if bits != 0 || codes.len() < MIN_CODES {
        return None;
    }
    Some(codes)
}

/// Decodes `codes` with the US-TTY figures, and with the ITA2 figures too if that reads
/// differently. Readings without an ASCII letter or digit are dropped: shifts, NULs and
/// spaces alone aren't a message.
fn readings(codes: &[u8], keys: [&'static str; 2], input: &str) -> Vec<Reading> {
    let (us_tty, figures_differ) = decode(codes, &FIGURES_US_TTY);
    // Two codes can make up for each other: FIGS S J is BEL ' in US-TTY and ' BEL in ITA2.
    let ita2 = figures_differ
        .then(|| decode(codes, &FIGURES_ITA2).0)
        .filter(|ita2| *ita2 != us_tty);
    let mut readings = vec![Reading {
        text: us_tty,
        key: keys[0],
    }];
    if let Some(ita2) = ita2 {
        readings.push(Reading {
            text: ita2,
            key: keys[1],
        });
    }
    readings.retain(|reading| {
        reading
            .text
            .bytes()
            .any(|byte| byte.is_ascii_alphanumeric())
            && check_string_success(&reading.text, input)
    });
    readings
}

/// Decodes `codes` (each 0 to 31), starting in the letters, with `figures` as the
/// figures table. Also returns whether a code was read in figures where the ITA2 and
/// US-TTY figures differ, so whether the other figures table reads differently.
fn decode(codes: &[u8], figures: &[char; 32]) -> (String, bool) {
    let mut text = String::with_capacity(codes.len());
    let mut in_figures = false;
    let mut figures_differ = false;
    for &code in codes {
        match code {
            FIGS => in_figures = true,
            LTRS => in_figures = false,
            _ => {
                let code = usize::from(code);
                let character = if in_figures {
                    figures_differ |= FIGURES_US_TTY[code] != FIGURES_ITA2[code];
                    figures[code]
                } else {
                    LETTERS[code]
                };
                if character != NOTHING {
                    text.push(character);
                }
            }
        }
    }
    (text, figures_differ)
}

/// A reading the checker identified as plaintext.
struct Hit<'a> {
    /// The reading.
    reading: &'a Reading,
    /// The checker's verdict on it.
    checker_result: CheckResult,
}

impl Hit<'_> {
    /// Whether more than a lenient English check identified the reading: another checker
    /// did (LemmeKnow, a crib or a wordlist), or a strict English check accepts it too.
    /// The search ranks the results of one step the same way.
    fn is_confident(&self) -> bool {
        let strict = Checker::<EnglishChecker>::new().with_sensitivity(Sensitivity::Low);
        self.checker_result.checker_name != strict.name
            || strict.check(&self.reading.text).is_identified
    }

    /// `results` as a success with this reading as the plaintext.
    fn into_result(self, mut results: CrackResult) -> CrackResult {
        trace!("Found a match with Baudot reading {}", self.reading.key);
        results.unencrypted_text = Some(vec![self.reading.text.clone()]);
        results.update_checker(&self.checker_result);
        results.key = Some(self.reading.key.to_string());
        results
    }
}

/// The first of `readings` the checker identifies as plaintext.
fn identify<'a>(readings: &'a [Reading], checker: &CheckerTypes) -> Option<Hit<'a>> {
    readings.iter().find_map(|reading| {
        let checker_result = checker.check(&reading.text);
        checker_result.is_identified.then_some(Hit {
            reading,
            checker_result,
        })
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::athena::Athena;

    /// The Athena checker, as the search uses it
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    /// Runs the decoder with the Athena checker
    fn crack(text: &str) -> CrackResult {
        Decoder::<BaudotDecoder>::new().crack(text, &get_athena_checker())
    }

    /// Asserts the decoder identifies `text` as `plaintext` with the reading `key`
    fn assert_cracks(text: &str, plaintext: &str, key: &str) {
        let result = crack(text);
        assert!(result.success, "{text:?} was not cracked: {result:?}");
        assert_eq!(result.unencrypted_text, Some(vec![plaintext.to_string()]));
        assert_eq!(result.key.as_deref(), Some(key));
        assert!(!result.checker_name.is_empty());
    }

    /// Asserts the decoder doesn't identify `text`, and hands `candidates` to the search
    fn assert_candidates(text: &str, candidates: &[&str]) {
        let result = crack(text);
        assert!(!result.success, "{text:?} was cracked: {result:?}");
        let expected: Vec<String> = candidates.iter().map(|c| c.to_string()).collect();
        assert_eq!(result.unencrypted_text, Some(expected), "{text:?}");
        assert!(result.key.is_none());
    }

    /// The texts and keys of the most-significant-bit-first readings of `text`
    fn msb_readings(text: &str) -> Vec<(String, &'static str)> {
        let codes = parse_codes(text).expect("expected Baudot");
        readings(&codes, KEYS[0], text)
            .into_iter()
            .map(|reading| (reading.text, reading.key))
            .collect()
    }

    // Unless noted, the vectors decode the same with an independent Python decoder built
    // from Wikipedia's ITA2 / US-TTY table
    // (https://en.wikipedia.org/wiki/Baudot_code#ITA_2_and_US-TTY) and with the tables of
    // the PyPI package `baudot` 0.1.1 (ITA2_US and ITA2_STANDARD), which index the same
    // 32-entry tables by value.

    /// HELLO WORLD, the example in issue #956, made with the table Python Ciphey shipped.
    const HELLO_WORLD: &str = "10100 00001 10010 10010 11000 00100 10011 11000 01010 10010 01001";
    /// THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG
    const FOX: &str = "10000 10100 00001 00100 10111 00111 00110 01110 01111 00100 11001 01010 11000 10011 01100 00100 01101 11000 11101 00100 01011 00111 11100 10110 00101 00100 11000 11110 00001 01010 00100 10000 10100 00001 00100 10010 00011 10001 10101 00100 01001 11000 11010";
    /// `FOX` read the wrong way round, least significant bit first
    const FOX_REVERSED_READING: &str = "EST XMNCV WRABI PAQ GMUFH AKTR EST DOZY LAJ";

    #[test]
    fn decodes_issue_example() {
        assert_cracks(HELLO_WORLD, "HELLO WORLD", "MSB-first, US-TTY");
    }

    #[test]
    fn decodes_unspaced_groups() {
        assert_cracks("1010000001100101001011000", "HELLO", "MSB-first, US-TTY");
    }

    #[test]
    fn decodes_any_ascii_whitespace_between_groups() {
        assert_cracks(
            "  10100\t00001\n10010\r\n10010  11000 00100 10011 11000 01010 10010 01001\n",
            "HELLO WORLD",
            "MSB-first, US-TTY",
        );
    }

    #[test]
    fn decodes_dcode_example() {
        // dCode's example (https://www.dcode.fr/baudot-code): FIGS before 0 and 3, LTRS
        // before the second D. Athena doesn't identify DC0D3.
        assert_candidates(
            "01001 01110 11011 10110 11111 01001 11011 00001",
            &["DC0D3"],
        );
    }

    #[test]
    fn decodes_dcode_default_input() {
        // The input dCode's Baudot decoder shows by default; it ends with FIGS !
        assert_eq!(
            msb_readings("01001 01110 11000 01001 00001 00100 11001 00011 00111 01001 11000 10000 11011 01101"),
            [("DCODE BAUDOT!".to_string(), "MSB-first, US-TTY")]
        );
    }

    #[test]
    fn figures_shift_switches_to_digits() {
        // FIGS 1 0, a space (the same in both tables), LTRS P M
        assert_cracks(
            "11100 00001 00001 10000 00100 11100 00001 00100 00011 10000 00100 11011 10111 10110 00100 11111 10110 11100",
            "MEET ME AT 10 PM",
            "MSB-first, US-TTY",
        );
    }

    #[test]
    fn us_tty_figures_are_tried_before_ita2() {
        // FIGS D is $ in US-TTY and ENQ, which prints nothing, in ITA2. Athena accepts
        // both readings, so the US-TTY one wins by being checked first.
        let text =
            "00101 00001 01100 01001 00100 11011 01001 10000 10110 00100 11111 01100 11000 10011";
        assert_eq!(
            msb_readings(text),
            [
                ("SEND $50 NOW".to_string(), "MSB-first, US-TTY"),
                ("SEND 50 NOW".to_string(), "MSB-first, ITA2"),
            ]
        );
        assert_cracks(text, "SEND $50 NOW", "MSB-first, US-TTY");
    }

    #[test]
    fn line_feed_is_a_new_line() {
        // HI LF THERE. Athena doesn't identify it, so it is a candidate.
        assert_candidates(
            "10100 00110 00010 10000 10100 00001 01010 00001",
            &["HI\nTHERE"],
        );
    }

    #[test]
    fn carriage_return_prints_nothing() {
        // HI CR LF THERE and HI LF CR THERE: one new line each
        for text in [
            "10100 00110 01000 00010 10000 10100 00001 01010 00001",
            "10100 00110 00010 01000 10000 10100 00001 01010 00001",
        ] {
            assert_eq!(
                msb_readings(text),
                [("HI\nTHERE".to_string(), "MSB-first, US-TTY")]
            );
        }
    }

    #[test]
    fn decodes_least_significant_bit_first() {
        // HELLO WORLD with each group reversed. Read most significant bit first it is
        // STDDA BARDL, which isn't identified.
        let text = "00101 10000 01001 01001 00011 00100 11001 00011 01010 01001 10010";
        assert_eq!(
            msb_readings(text),
            [("STDDA BARDL".to_string(), "MSB-first, US-TTY")]
        );
        assert_cracks(text, "HELLO WORLD", "LSB-first, US-TTY");
    }

    #[test]
    fn decodes_pangram() {
        assert_cracks(
            FOX,
            "THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG",
            "MSB-first, US-TTY",
        );
    }

    #[test]
    fn junk_reversed_reading_is_not_returned() {
        // Read least significant bit first, the pangram is the junk below, which a
        // lenient English check accepts. It must never reach the search unverified.
        let codes = parse_codes(FOX).unwrap();
        let reversed: Vec<u8> = codes.iter().map(|&code| REV5[usize::from(code)]).collect();
        let junk = readings(&reversed, KEYS[1], FOX);
        assert_eq!(junk[0].text, FOX_REVERSED_READING);
        assert!(
            get_athena_checker()
                .check(FOX_REVERSED_READING)
                .is_identified
        );
        let result = crack(FOX);
        let outputs = result.unencrypted_text.unwrap();
        assert!(!outputs.contains(&junk[0].text), "{outputs:?}");
    }

    #[test]
    fn decodes_pangram_written_least_significant_bit_first() {
        // The other way round: the pangram with each group reversed. Its
        // most-significant-bit-first reading is the junk, which Athena accepts through
        // the English checker but a strict English check doesn't, so the real reading
        // wins.
        let text = "00001 00101 10000 00100 11101 11100 01100 01110 11110 00100 10011 01010 00011 11001 00110 00100 10110 00011 10111 00100 11010 11100 00111 01101 10100 00100 00011 01111 10000 01010 00100 00001 00101 10000 00100 01001 11000 10001 10101 00100 10010 00011 01011";
        assert_eq!(
            msb_readings(text),
            [(FOX_REVERSED_READING.to_string(), "MSB-first, US-TTY")]
        );
        assert_cracks(
            text,
            "THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG",
            "LSB-first, US-TTY",
        );
    }

    #[test]
    fn lenient_hit_wins_when_the_reversed_reading_is_junk() {
        // MEET ME AT 10 PM only passes the lenient English check, and its reversed
        // reading, UTTE UT OE /! FU, isn't identified at all
        let text = "11100 00001 00001 10000 00100 11100 00001 00100 00011 10000 00100 11011 10111 10110 00100 11111 10110 11100";
        let codes = parse_codes(text).unwrap();
        let reversed: Vec<u8> = codes.iter().map(|&code| REV5[usize::from(code)]).collect();
        assert_eq!(
            readings(&reversed, KEYS[1], text)[0].text,
            "UTTE UT OE /! FU"
        );
        assert_cracks(text, "MEET ME AT 10 PM", "MSB-first, US-TTY");
    }

    #[test]
    fn baconian_zeros_and_ones_are_not_identified() {
        // HELLO in Bacon's cipher (standard alphabet, 0=A 1=B) is groups of five 0s and
        // 1s too. As Baudot it reads U RRF, which Athena rejects: the Baconian decoder
        // cracks it instead.
        assert_candidates("00111 00100 01010 01010 01101", &["U RRF"]);
    }

    #[test]
    fn ita2_figures_can_print_a_pound_sign() {
        // FIGS H T: # 5 in US-TTY, £ 5 in ITA2
        assert_eq!(
            msb_readings("11011 10100 10000"),
            [
                ("#5".to_string(), "MSB-first, US-TTY"),
                ("£5".to_string(), "MSB-first, ITA2"),
            ]
        );
    }

    #[test]
    fn identical_figures_readings_are_returned_once() {
        // FIGS S J is BEL ' in US-TTY and ' BEL in ITA2. Followed by LTRS A B C.
        assert_eq!(
            msb_readings("11011 00101 01011 11111 00011 11001 01110"),
            [("'ABC".to_string(), "MSB-first, US-TTY")]
        );
    }

    #[test]
    fn shifts_at_the_start_and_repeated() {
        // FIGS FIGS 1 2 3 LTRS LTRS A B C
        assert_eq!(
            msb_readings("11011 11011 10111 10011 00001 11111 11111 00011 11001 01110"),
            [("123ABC".to_string(), "MSB-first, US-TTY")]
        );
    }

    #[test]
    fn unspaced_binary_passes_the_gate_but_is_not_identified() {
        // "hello" as 8-bit binary is 40 bits, a whole number of groups
        let result = crack("0110100001100101011011000110110001101111");
        assert!(!result.success, "{result:?}");
        let candidates = result.unencrypted_text.expect("expected candidates");
        assert!(
            !candidates.is_empty() && candidates.len() <= 2,
            "{candidates:?}"
        );
    }

    #[test]
    fn rejects_input_that_is_not_baudot() {
        for text in [
            "",
            " \n\t ",
            "😀",
            "hello world",
            "HELLO WORLD",
            // 10 bits: fewer than 3 groups
            "10100 00001",
            "1010000001",
            // A token that isn't one group
            "10100 0000",
            "10100 00001 100101",
            "1010 00001 10010",
            "1010000001 10010",
            // A single token that isn't a whole number of groups: 19 and 21 bits
            "1010000001100101001",
            "101000000110010100101",
            // 8-bit binary
            "01001000 01100101 01101100",
            // Other digits or separators
            "10100 00001 10012",
            "10100,00001,10010",
            "10100 00001\u{a0}10010",
            // The bench `miss` string
            "T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV",
        ] {
            assert!(parse_codes(text).is_none(), "{text:?} passed the pre-check");
            let result = crack(text);
            assert!(!result.success, "{text:?}: {result:?}");
            assert!(result.unencrypted_text.is_none(), "{text:?}: {result:?}");
        }
    }

    #[test]
    fn rejects_readings_without_a_letter_or_digit() {
        for text in [
            // LTRS FIGS LTRS
            "11111 11011 11111",
            // NULs
            "00000 00000 00000",
            // Spaces
            "00100 00100 00100",
            // CR LF CR
            "01000 00010 01000",
        ] {
            assert!(parse_codes(text).is_some(), "{text:?}");
            let result = crack(text);
            assert!(!result.success, "{text:?}: {result:?}");
            assert!(result.unencrypted_text.is_none(), "{text:?}: {result:?}");
        }
    }

    #[test]
    fn parses_groups_most_significant_bit_first() {
        assert_eq!(parse_codes("00011 11000 11011"), Some(vec![3, 24, 27]));
        assert_eq!(parse_codes("000111100011011"), Some(vec![3, 24, 27]));
        assert_eq!(parse_codes(" 00011 11000 11011 \n"), Some(vec![3, 24, 27]));
    }

    #[test]
    fn reversed_codes() {
        assert_eq!(REV5[0b00011], 0b11000);
        assert_eq!(REV5[0b01000], 0b00010);
        // FIGS, LTRS and space read the same both ways
        assert_eq!(REV5[usize::from(FIGS)], FIGS);
        assert_eq!(REV5[usize::from(LTRS)], LTRS);
        assert_eq!(REV5[0b00100], 0b00100);
        for code in 0..32 {
            assert_eq!(usize::from(REV5[usize::from(REV5[code])]), code);
        }
    }

    #[test]
    fn figures_tables_differ_in_six_codes() {
        let differ: Vec<char> = (0..32)
            .filter(|&code| FIGURES_US_TTY[code] != FIGURES_ITA2[code])
            .map(|code| LETTERS[code])
            .collect();
        assert_eq!(differ, ['S', 'D', 'J', 'Z', 'H', 'V']);
    }

    #[test]
    fn is_registered() {
        let decoders = crate::filtration_system::get_decoder_by_name("Baudot");
        assert_eq!(decoders.components.len(), 1);
        assert!(crate::decoders::DECODER_MAP.contains_key("Baudot"));
    }
}
