//! Decode a big integer: the bytes of the text read as one big-endian unsigned integer and
//! written in decimal. `126207244316550804821666916` is `hello world`.
//! Call big_integer_decoder.crack to use. It returns a `CrackResult` whose `unencrypted_text`
//! is `None` when the input isn't such an integer.
//!
//! This is what PyCryptodome's `bytes_to_long` / `long_to_bytes`, Python's
//! `int.from_bytes(data, "big")` / `n.to_bytes((n.bit_length() + 7) // 8, "big")` and
//! CyberChef's `From Base` (10) → `To Base` (16) → `From Hex` do. RSA challenges in CTFs
//! print their message this way, often as `m = 4149…` or `flag = …`, and Python 2 adds an
//! `L` to the number. The input is one run of digits, optionally after a `name =` or
//! `name:` prefix and before one `L`. Zero bytes at the start of the text can't be
//! represented, which doesn't matter for text.
//!
//! The hex form (`0x5370…`) is the Hexadecimal decoder's. Digits in groups of three
//! (`104101108…`) are the Decimal decoder's; read as one number they almost never give
//! UTF-8 text.
//!
//! References:
//! <https://pycryptodome.readthedocs.io/en/latest/src/util/util.html#Crypto.Util.number.long_to_bytes>,
//! <https://gchq.github.io/CyberChef/#recipe=From_Base(10)To_Base(16)From_Hex('Auto')>.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};
use num::BigUint;

/// The Big integer decoder, call:
/// `let big_integer_decoder = Decoder::<BigIntegerDecoder>::new()` to create a new instance
/// And then call:
/// `result = big_integer_decoder.crack(input)` to decode a big integer
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::big_integer_decoder::BigIntegerDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_big_integer = Decoder::<BigIntegerDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_big_integer
///     .crack("126207244316550804821666916", &checker)
///     .unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hello world");
/// ```
pub struct BigIntegerDecoder;

/// Numbers with fewer digits than this, not counting leading zeros, are rejected. Twelve
/// digits are at least 10^11 > 2^36, so at least 5 bytes: `hello` is `448378203247`.
/// Shorter texts are too short to identify, and 10 or 11 digits are what Unix timestamps and
/// phone numbers look like.
const MIN_DIGITS: usize = 12;

/// Numbers with more digits than this are rejected. 2000 digits decode to at most 831
/// bytes, and the search drops results and candidates of 821 to 5000 bytes anyway (see
/// `calculate_string_quality`). The cap bounds the big-integer work on long runs of digits.
const MAX_DIGITS: usize = 2000;

/// The longest name accepted before the `=` or `:`, as in `m = …` or `flag = …`.
const MAX_NAME_LEN: usize = 16;

impl Crack for Decoder<BigIntegerDecoder> {
    fn new() -> Decoder<BigIntegerDecoder> {
        Decoder {
            name: "Big integer to bytes",
            description: "The bytes of the text read as one big-endian integer and written in decimal, as PyCryptodome's bytes_to_long / long_to_bytes and Python's int.from_bytes do. Common in RSA CTF challenges (m = 4149…). An optional name = prefix and Python 2's trailing L are accepted.",
            link: "https://pycryptodome.readthedocs.io/en/latest/src/util/util.html#Crypto.Util.number.long_to_bytes",
            tags: vec!["long_to_bytes", "bigint", "decimal", "decoder", "base"],
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes `text` as a big integer and checks the result with `checker`.
    /// `unencrypted_text` is `None` when `text` isn't a big integer of UTF-8 text.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Big integer to bytes with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_big_integer(text) else {
            debug!("Failed to decode Big integer to bytes because the text isn't a big integer of UTF-8 text");
            return results;
        };
        trace!("Decoded text for Big integer to bytes: {:?}", decoded_text);

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Big integer to bytes because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Decodes a decimal big integer to text, or returns `None` if `text` isn't one integer
/// whose big-endian bytes are UTF-8 text without control characters (tabs and line breaks
/// are allowed).
fn decode_big_integer(text: &str) -> Option<String> {
    // Rejects almost every input at its first byte, before anything is allocated
    let rest = strip_name_prefix(text.trim().as_bytes())?;
    // Python 2 printed a `long` with an `L` after it
    let digits = rest.strip_suffix(b"L").unwrap_or(rest);
    if digits.len() > MAX_DIGITS {
        return None;
    }
    // A single scan that stops at the first byte that isn't a digit: a second number or a
    // line break (`n = …\ne = 65537`), the `x` of `0x…`, a `_`, a second `L`.
    if !digits.iter().all(u8::is_ascii_digit) {
        return None;
    }
    let leading_zeros = digits.iter().take_while(|&&byte| byte == b'0').count();
    let significant = &digits[leading_zeros..];
    if significant.len() < MIN_DIGITS {
        return None;
    }

    // `parse_bytes` alone isn't a validator: it also accepts a leading `+` and skips `_`.
    // The scan above has rejected both. The number starts with a non-zero digit, so it
    // isn't zero, whose `to_bytes_be()` would be `[0]`.
    let number = BigUint::parse_bytes(significant, 10)?;
    let decoded = String::from_utf8(number.to_bytes_be()).ok()?;
    if decoded
        .chars()
        .any(|c| c.is_control() && !matches!(c, '\t' | '\n' | '\r'))
    {
        return None;
    }
    Some(decoded)
}

/// Returns `text` without a `name =` or `name:` prefix, the way RSA challenges print their
/// numbers (`m = …`, `c = …`, `flag = …`, `pt: …`). The name is a letter or `_` followed by
/// letters, digits and `_`, at most `MAX_NAME_LEN` of them, and spaces may surround the
/// `=` or `:`. Text that starts with a digit is returned as it is. Anything else is `None`.
fn strip_name_prefix(text: &[u8]) -> Option<&[u8]> {
    match text.first()? {
        b'0'..=b'9' => Some(text),
        b'a'..=b'z' | b'A'..=b'Z' | b'_' => {
            let name_len = text
                .iter()
                .take(MAX_NAME_LEN + 1)
                .take_while(|&&byte| byte.is_ascii_alphanumeric() || byte == b'_')
                .count();
            if name_len > MAX_NAME_LEN {
                return None;
            }
            match skip_spaces(&text[name_len..]) {
                [b'=' | b':', rest @ ..] => Some(skip_spaces(rest)),
                _ => None,
            }
        }
        _ => None,
    }
}

/// `text` without the spaces at its start.
fn skip_spaces(text: &[u8]) -> &[u8] {
    let spaces = text.iter().take_while(|&&byte| byte == b' ').count();
    &text[spaces..]
}

#[cfg(test)]
mod tests {
    use super::{decode_big_integer, BigIntegerDecoder, MAX_DIGITS};
    use crate::checkers::athena::Athena;
    use crate::checkers::checker_type::{Check, Checker};
    use crate::checkers::CheckerTypes;
    use crate::decoders::crack_results::CrackResult;
    use crate::decoders::interface::{Crack, Decoder};
    use crate::decoders::{DecoderType, DECODER_MAP};
    use crate::filtration_system::get_decoder_by_name;

    // Every vector was made with Python 3.9's `int.from_bytes(data, "big")`, which is what
    // PyCryptodome's `bytes_to_long` does, and decoded back with
    // `n.to_bytes((n.bit_length() + 7) // 8, "big")`, which is `long_to_bytes`. The issue
    // plan also made them with PyCryptodome 3.23 and decoded them with CyberChef 10.24
    // `From Base` (10) → `To Base` (16) → `From Hex`.
    // https://github.com/bee-san/Ciphey/issues/952

    /// The issue example
    const SPHINX: &str =
        "41496199872461863022222116254391861095445975299447768243887778995190997863590821188564782";
    const SPHINX_PLAINTEXT: &str = "Sphinx of black quartz, judge my vow.";

    const HELLO_WORLD: &str = "126207244316550804821666916";

    const FOX: &str = "11815744420664747200359014215611078249874077418792906203758916158211866334739307190174417697959789752167";
    const FOX_PLAINTEXT: &str = "The quick brown fox jumps over the lazy dog";

    /// The bench `medium` input (202 digits)
    const MEDIUM: &str = "5924286894360222175456110753752027428824911406952436191673549997864792617447030598048630620176057525265340209895115724741248167312932204479423391834119139432169971560672548040885900086328159414572509230";
    const MEDIUM_PLAINTEXT: &str =
        "Meet me at the old lighthouse after midnight and bring the map, the key and a torch.";

    /// The bench `long` input: the 576-character plaintext in 1387 digits
    const LONG: &str = "3687367625251368244499181675087148919532362862307301551705081364777717211798394876232923994771409877031107864238750404693410442466857471030470667831213285650849390535353869661867680827743625001790066489951088818273303369599010919967957946226676566662347954342741540948929967321969103964150963826015580590801898642200157766085431372278955169069182770335696224500308330843729497871353208232845982198301342098643485481994963969547506152627033605068721690141870851196599888375860308238170218581481983492796655751710165708551395755521270312975504883009912998007452685972442115169470229690956917597563341695679501521524381426270929579575092623013588434149463733531933152647801036618128150658077414097533965874705649882082974008478852561072091712278094457814819924589128248844965425388650420263006068974733178692478492093826089955521824411711300597738118769262754261868322079550588842532738511784967407658703734926877314933715909664822254387953474603738463847560616757101663832411897653397118460565240926316422607108230097062209907325331854624354525129532394366270045834395219011958911099346894739097703998413779528243268838856472703876500658438982032005782824657157318077155799048874207345457776153520277834496595312818560580405487045798816333945431683735025291345989866831560727854368130489335152522775999673588990832982441822130671920235239920972307786452623381445409657775703617045384684846";
    const LONG_PLAINTEXT: &str = "Ciphey is an automated decoding tool. You give it encrypted or encoded text and it tries to work out what was done to it, without you having to know the key or even the cipher. It searches through many possible decodings, checks each candidate to see whether it looks like English or matches a known pattern such as an email address, and stops when it finds something that reads like plaintext. Most of the time this takes less than a second, which makes it handy for capture the flag challenges, puzzle hunts and for anyone who stumbles across a strange string in a log file.";

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn crack_result(text: &str) -> CrackResult {
        Decoder::<BigIntegerDecoder>::new().crack(text, &get_athena_checker())
    }

    // Runs the decoder with the Athena checker and returns the decoded text, if any
    fn crack(text: &str) -> Option<String> {
        let result = crack_result(text);
        if result.unencrypted_text.is_none() {
            assert!(!result.success, "{text:?} failed but was marked successful");
        }
        result.unencrypted_text.map(|texts| texts[0].clone())
    }

    // Asserts that Athena accepts what `text` decodes to, and that it is `plaintext`
    fn assert_identified(text: &str, plaintext: &str) {
        let result = crack_result(text);
        assert!(result.success, "Athena should accept {plaintext:?}");
        assert_eq!(result.unencrypted_text.unwrap()[0], plaintext);
    }

    #[test]
    fn decodes_the_issue_example() {
        // Decoded, but Athena doesn't take this pangram for English
        assert_eq!(crack(SPHINX).as_deref(), Some(SPHINX_PLAINTEXT));
    }

    #[test]
    fn decodes_the_issue_example_with_a_name() {
        assert_eq!(
            crack(&format!("m = {SPHINX}")).as_deref(),
            Some(SPHINX_PLAINTEXT)
        );
    }

    #[test]
    fn decodes_the_issue_example_with_python_2_suffix() {
        assert_eq!(
            crack(&format!("{SPHINX}L")).as_deref(),
            Some(SPHINX_PLAINTEXT)
        );
    }

    #[test]
    fn decodes_hello_world() {
        assert_identified(HELLO_WORLD, "hello world");
    }

    #[test]
    fn decodes_the_shortest_accepted_input() {
        // Twelve digits, the minimum. Athena accepts `hello` with its password checker, so
        // only the decoded text is checked here.
        assert_eq!(crack("448378203247").as_deref(), Some("hello"));
    }

    #[test]
    fn decodes_pangram() {
        assert_identified(FOX, FOX_PLAINTEXT);
    }

    #[test]
    fn decodes_ctf_flag() {
        // LemmeKnow identifies the result as a "Capture The Flag (CTF) Flag"
        assert_identified(
            "flag = 50937517511040843800057610630687734629648772740622533002167079526478786571835272839786109",
            "flag{long_to_bytes_is_not_encryption}",
        );
    }

    #[test]
    fn decodes_bench_medium() {
        assert_identified(MEDIUM, MEDIUM_PLAINTEXT);
    }

    #[test]
    fn decodes_bench_long() {
        assert_eq!(LONG.len(), 1387);
        assert_identified(LONG, LONG_PLAINTEXT);
    }

    #[test]
    fn decodes_name_prefixes() {
        for prefix in [
            "m = ",
            "m=",
            "c:",
            "pt: ",
            "FLAG =  ",
            "_m1 = ",
            "ciphertext_bytes = ",
        ] {
            assert_identified(&format!("{prefix}{HELLO_WORLD}"), "hello world");
        }
        assert_identified(&format!("flag = {HELLO_WORLD}L"), "hello world");
    }

    #[test]
    fn decodes_leading_zero_digits() {
        assert_eq!(
            decode_big_integer(&format!("000{HELLO_WORLD}")).as_deref(),
            Some("hello world")
        );
    }

    #[test]
    fn decodes_surrounding_whitespace() {
        assert_identified(&format!("  {HELLO_WORLD}\n"), "hello world");
    }

    #[test]
    fn decodes_tabs_line_breaks_and_utf8() {
        assert_eq!(
            decode_big_integer("126207244316525516054228068").as_deref(),
            Some("hello\tworld")
        );
        assert_eq!(
            decode_big_integer("36890637770766366516095288339040600094575").as_deref(),
            Some("line one\nline two")
        );
        assert_eq!(
            decode_big_integer("30756767067498977847098764645").as_deref(),
            Some("café crème")
        );
        assert_eq!(
            decode_big_integer("5654108587922388824838614153382045059018663199312972055432")
                .as_deref(),
            Some("日本語のテキスト")
        );
    }

    #[test]
    fn decode_big_integer_caps_the_length() {
        // Zero digits in front don't change the value, so both inputs are the medium
        // plaintext; only the length differs.
        let at_limit = format!("{}{MEDIUM}", "0".repeat(MAX_DIGITS - MEDIUM.len()));
        assert_eq!(at_limit.len(), 2000);
        assert_eq!(
            decode_big_integer(&at_limit).as_deref(),
            Some(MEDIUM_PLAINTEXT)
        );

        let over_limit = format!("0{at_limit}");
        assert_eq!(over_limit.len(), 2001);
        assert_eq!(decode_big_integer(&over_limit), None);
    }

    #[test]
    fn a_changed_digit_is_left_to_the_checker() {
        // There's no checksum: the issue example with its last digit changed is text too
        assert_eq!(
            decode_big_integer(
                "41496199872461863022222116254391861095445975299447768243887778995190997863590821188564783"
            )
            .as_deref(),
            Some("Sphinx of black quartz, judge my vow/")
        );
    }

    #[test]
    fn fails_on_zero() {
        assert_eq!(crack("0"), None);
        assert_eq!(crack("000000000000"), None);
    }

    #[test]
    fn fails_with_fewer_than_twelve_digits() {
        // 0A 70 8A D7 A4: `hello` without its last digit
        assert_eq!(crack("44837820324"), None);
        // Leading zeros don't count
        assert_eq!(crack("000044837820324"), None);
        // dCode's "Base 36 cipher" of HELLO
        assert_eq!(crack("29234652"), None);
        // 65 53 F1 00: a Unix timestamp
        assert_eq!(crack("1700000000"), None);
        // 49 96 02 D2
        assert_eq!(crack("1234567890"), None);
    }

    #[test]
    fn fails_when_the_bytes_are_not_utf8() {
        // 01 8B CF E5 68 00: a Unix timestamp in milliseconds
        assert_eq!(crack("1700000000000"), None);
        // 0E 9B 08 A5 68 F1 C7: a test card number
        assert_eq!(crack("4111111111111111"), None);
        // 05 21 F0 D2 ...: Decimal's 3-digit form of "hello world"
        assert_eq!(crack("104101108108111032119111114108100"), None);
    }

    #[test]
    fn fails_on_control_characters() {
        // "hello\x07world"
        assert_eq!(crack("126207244316523317030972516"), None);
        // "\x1bhello world"
        assert_eq!(crack("8482302509492867660390755428"), None);
    }

    #[test]
    fn fails_on_hex() {
        // The issue example's hex form is the Hexadecimal decoder's
        assert_eq!(crack("0x537068696e78"), None);
        assert_eq!(crack("537068696e78206f6620626c61636b"), None);
    }

    #[test]
    fn fails_on_signs_and_separators() {
        // num-bigint accepts a leading `+` and skips `_`
        assert_eq!(crack(&format!("+{HELLO_WORLD}")), None);
        assert_eq!(crack(&format!("-{HELLO_WORLD}")), None);
        assert_eq!(crack("126_207_244_316_550_804_821_666_916"), None);
        assert_eq!(crack("126,207,244,316,550,804,821,666,916"), None);
        assert_eq!(crack("1262072443165508.04821666916"), None);
    }

    #[test]
    fn fails_on_more_than_one_number() {
        assert_eq!(crack(&format!("{HELLO_WORLD} 1")), None);
        assert_eq!(crack(&format!("n = {HELLO_WORLD}\ne = 65537")), None);
        assert_eq!(crack("123456789012 345678901234"), None);
    }

    #[test]
    fn fails_on_other_prefixes() {
        // 17 characters, one more than the longest name
        assert_eq!(crack(&format!("ciphertext_bytes1 = {HELLO_WORLD}")), None);
        assert_eq!(crack(&format!("my-message = {HELLO_WORLD}")), None);
        assert_eq!(crack(&format!("key.m = {HELLO_WORLD}")), None);
        assert_eq!(crack(&format!("m == {HELLO_WORLD}")), None);
        assert_eq!(crack(&format!("m {HELLO_WORLD}")), None);
        assert_eq!(crack(&format!("= {HELLO_WORLD}")), None);
        assert_eq!(crack(&format!("1m = {HELLO_WORLD}")), None);
        assert_eq!(crack("m = "), None);
    }

    #[test]
    fn fails_on_other_suffixes() {
        assert_eq!(crack(&format!("{HELLO_WORLD}LL")), None);
        assert_eq!(crack(&format!("{HELLO_WORLD}l")), None);
        assert_eq!(crack(&format!("{HELLO_WORLD} L")), None);
        assert_eq!(crack("L"), None);
    }

    #[test]
    fn fails_on_the_bench_miss_input() {
        assert_eq!(
            crack("T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV"),
            None
        );
    }

    #[test]
    fn fails_on_english() {
        assert_eq!(crack("hello world"), None);
        assert_eq!(crack("hello my name is panicky mc panic face!"), None);
    }

    #[test]
    fn handles_panic_if_empty_string() {
        assert_eq!(crack(""), None);
    }

    #[test]
    fn handles_panic_if_whitespace() {
        assert_eq!(crack("   "), None);
    }

    #[test]
    fn handles_panic_if_emoji() {
        assert_eq!(crack("😀"), None);
        assert_eq!(crack(&format!("{HELLO_WORLD}😀")), None);
        assert_eq!(crack(&format!("m = 😀{HELLO_WORLD}")), None);
        // Full-width digits aren't ASCII digits
        assert_eq!(
            crack("１２６２０７２４４３１６５５０８０４８２１６６６９１６"),
            None
        );
    }

    #[test]
    fn is_registered() {
        // Exactly one decoder by that name runs in the search
        let decoders = get_decoder_by_name("Big integer to bytes");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Big integer to bytes");
        // Cached results name the decoder; reading them back looks it up here
        let decoder = DECODER_MAP
            .get("Big integer to bytes")
            .expect("Big integer to bytes should be in DECODER_MAP")
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "Big integer to bytes");
    }
}
