//! Decompress bzip2 data.
//!
//! A bzip2 stream is the header `BZh` and a block-size digit from `1` to `9`, then one or
//! more blocks, each starting with the 48-bit magic `31 41 59 26 53 59` (π in BCD) and
//! the block's CRC, then the end-of-stream magic `17 72 45 38 50 90` (√π) and a CRC of
//! the whole stream. The blocks are Burrows–Wheeler transformed and Huffman coded, and
//! are not byte-aligned. A file can be several streams back to back, as `pbzip2` writes
//! them; `bzip2 -d` decompresses them all, and so does this decoder.
//!
//! Ciphey passes text between decoders, and bzip2 is binary, so this decoder reads the
//! bzip2 bytes from three textual forms itself:
//! * Base64 (standard or URL-safe, line breaks allowed), which starts with `QlpoM`,
//!   `QlpoN` or `QlpoO` (`BZh1` to `BZh3`, `BZh4` to `BZh7`, `BZh8` and `BZh9`),
//! * hex (`425a68…`, optionally split into bytes by whitespace, `:`, `,`, `;`, `-` or
//!   `%`, or prefixed with `0x` or `\x`),
//! * the raw bytes as Latin-1 text, which is what the Hexadecimal and Binary decoders
//!   emit for bytes that aren't UTF-8.
//!
//! Each form is recognised from its first few characters, so other text is rejected
//! without decoding or copying it. Decompression stops at [`MAX_OUTPUT`] bytes, so a
//! bzip2 bomb fails quickly instead of eating memory, and output the checker doesn't
//! accept is only passed on for more decoding up to [`MAX_CANDIDATE`] bytes.
//!
//! Call `bzip2_decoder.crack` to use. It returns a [`CrackResult`]; check
//! `result.unencrypted_text.is_some()` to see if it decoded.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;
use base64::{engine::general_purpose, Engine as _};
use bzip2::{Decompress, Status};

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// Decompressed output above this many bytes is rejected rather than truncated: a
/// fragment of the plaintext isn't the plaintext.
const MAX_OUTPUT: usize = 1024 * 1024;

/// Output the checker didn't accept is only handed on for more decoding up to this many
/// bytes. Bzip2 output isn't bounded by the input's size (a few dozen bytes can hold
/// megabytes of one repeated byte), and every decoder runs on every node of the search,
/// so a short input could otherwise make a megabyte node. The Gzip decoder uses the same
/// limit.
const MAX_CANDIDATE: usize = 16 * 1024;

/// Anything shorter can't be a complete stream. The shortest, `bz2.compress(b"")`, is the
/// 4-byte header, the 6-byte end-of-stream magic and the 4-byte stream CRC.
const MIN_STREAM_LEN: usize = 14;

/// The first three bytes of every bzip2 stream. The block-size digit follows.
const MAGIC: [u8; 3] = *b"BZh";

/// The magic at the start of every block, `1AY&SY`: the first twelve digits of π in BCD.
const BLOCK_MAGIC: [u8; 6] = [0x31, 0x41, 0x59, 0x26, 0x53, 0x59];

/// The magic bytes as hex digits.
const MAGIC_HEX_DIGITS: [u8; 6] = [0x4, 0x2, 0x5, 0xa, 0x6, 0x8];

/// The magic bytes as Base64. Three bytes fill exactly four Base64 characters.
const MAGIC_BASE64: &str = "Qlpo";

/// The possible fifth Base64 characters, the top six bits of the block-size digit: `M`
/// for `1` to `3`, `N` for `4` to `7` and `O` for `8` and `9`.
const BLOCK_SIZE_BASE64: [u8; 3] = *b"MNO";

/// ID1, ID2 and CM of a gzip member, which the Gzip decoder reads from raw bytes.
const GZIP_MAGIC: [u8; 3] = [0x1f, 0x8b, 0x08];

/// The magic of an xz stream.
const XZ_MAGIC: [u8; 6] = [0xfd, 0x37, 0x7a, 0x58, 0x5a, 0x00];

/// The Bzip2 decoder, call:
/// `let bzip2_decoder = Decoder::<Bzip2Decoder>::new()` to create a new instance
/// And then call:
/// `result = bzip2_decoder.crack(input)` to decompress bzip2 given as Base64, hex or raw bytes
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::bzip2_decoder::Bzip2Decoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_bzip2 = Decoder::<Bzip2Decoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // Python: base64.b64encode(bz2.compress(b"The quick brown fox jumps over the lazy dog"))
/// let result = decode_bzip2
///     .crack(
///         "QlpoOTFBWSZTWUWd7mEAAAQTgEAABAA////wIAAxRoaAAAAx6ammTIYRtG1HYmIISe16oVNlZbEl4+JgsfiYOd1MCW+c6F3JFOFCQRZ3uYQ=",
///         &checker,
///     )
///     .unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "The quick brown fox jumps over the lazy dog");
/// ```
pub struct Bzip2Decoder;

impl Crack for Decoder<Bzip2Decoder> {
    fn new() -> Decoder<Bzip2Decoder> {
        Decoder {
            name: "Bzip2",
            description: "Bzip2 compresses data with the Burrows–Wheeler transform and Huffman coding. Every stream starts with BZh and a block-size digit, which is Qlpo in Base64. Ciphey reads the compressed bytes from Base64, hex or raw text and decompresses them, including files with several streams.",
            link: "https://en.wikipedia.org/wiki/Bzip2",
            tags: vec!["bzip2", "compression", "decoder"],
            // Less common in CTFs than gzip and zlib (0.5)
            popularity: 0.4,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decompresses `text` if it is bzip2 as Base64, hex or raw bytes, and checks the
    /// decompressed text. Fails (with `unencrypted_text` set to `None`) if `text` isn't
    /// bzip2, doesn't decompress, decompresses to something that is neither text nor
    /// compressed data, or decompresses to more than [`MAX_CANDIDATE`] bytes that the
    /// checker doesn't accept.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Bzip2 with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(compressed) = bzip2_bytes(text) else {
            debug!("Bzip2 failed: input is not bzip2 as Base64, hex or raw bytes");
            return results;
        };
        let Some(decompressed) = bunzip_bounded(&compressed) else {
            debug!("Bzip2 failed: the data did not decompress");
            return results;
        };

        let decoded_text = match as_plaintext(decompressed) {
            Ok(decoded_text) => decoded_text,
            Err(binary) => {
                // Compressed again (bzip2 inside bzip2, or gzip, zlib or xz inside it):
                // hand it back as raw bytes for another step. It is binary, so there is
                // nothing for the checker to look at.
                if !is_compressed(&binary) {
                    info!("Failed to decode Bzip2: the output is binary, not text");
                } else if binary.len() > MAX_CANDIDATE {
                    debug!("Bzip2 output is compressed again, but too long to decode further");
                } else {
                    debug!("Bzip2 output is compressed again; returning it unchecked");
                    results.unencrypted_text = Some(vec![latin1_to_string(&binary)]);
                }
                return results;
            }
        };
        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Bzip2 because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        if !checker_result.is_identified && decoded_text.len() > MAX_CANDIDATE {
            debug!(
                "Bzip2 output is not plaintext and too long ({} bytes) to decode further",
                decoded_text.len()
            );
            return results;
        }
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Finds bzip2 bytes in `text`: Base64, hex, or raw bytes as Latin-1 characters.
/// Only the first few characters are looked at unless they spell the bzip2 magic.
fn bzip2_bytes(text: &str) -> Option<Vec<u8>> {
    let bytes = base64_view(text)
        .or_else(|| hex_view(text))
        .or_else(|| raw_view(text))?;
    has_stream_header(&bytes).then_some(bytes)
}

/// Base64, standard or URL-safe, that starts with `QlpoM`, `QlpoN` or `QlpoO`.
/// Whitespace (line breaks) is ignored and padding is optional.
fn base64_view(text: &str) -> Option<Vec<u8>> {
    let text = text.trim();
    let starts_like_bzip2 = text.starts_with(MAGIC_BASE64)
        && text
            .as_bytes()
            .get(MAGIC_BASE64.len())
            .is_some_and(|c| BLOCK_SIZE_BASE64.contains(c));
    if !starts_like_bzip2 {
        return None;
    }
    let body: String = text.chars().filter(|c| !c.is_whitespace()).collect();
    let unpadded = body.trim_end_matches('=');
    if body.len() - unpadded.len() > 2 {
        return None;
    }
    // The Base64 decoder's engines. Both reject '=' inside the text.
    general_purpose::STANDARD_NO_PAD
        .decode(unpadded)
        .or_else(|_| general_purpose::URL_SAFE_NO_PAD.decode(unpadded))
        .ok()
}

/// Hex that starts with `425a68`, in any case. Bytes can be separated by whitespace,
/// `:`, `,`, `;`, `-` or `%`, and each can have a `0x` or `\x` prefix.
fn hex_view(text: &str) -> Option<Vec<u8>> {
    let text = text.trim();
    // Cheap gate: the first six digits have to be the magic, otherwise stop here.
    let mut digits = HexDigits::new(text.as_bytes());
    for expected in MAGIC_HEX_DIGITS {
        if digits.next() != Some(Some(expected)) {
            return None;
        }
    }

    let mut bytes = Vec::with_capacity(text.len() / 2);
    let mut digits = HexDigits::new(text.as_bytes());
    while let Some(high) = digits.next() {
        // A character that isn't hex or a separator, or an odd number of digits
        let (high, low) = (high?, digits.next()??);
        bytes.push((high << 4) | low);
    }
    Some(bytes)
}

/// Bzip2 bytes as Latin-1 text, one character per byte. The Hexadecimal and Binary
/// decoders turn bytes that aren't UTF-8 (bzip2 streams practically never are) into this,
/// and so does this decoder for compressed data inside bzip2. Not trimmed: the stream can
/// end with bytes that look like whitespace.
fn raw_view(text: &str) -> Option<Vec<u8>> {
    if !text.as_bytes().starts_with(&MAGIC) {
        return None;
    }
    text.chars().map(|c| u8::try_from(c).ok()).collect()
}

/// Iterates over the hex digits of a hex string, skipping the separators and prefixes
/// [`hex_view`] allows. Yields `Some(digit)` for each digit, and `None` for a character
/// that doesn't belong in hex. Separators and prefixes are only allowed between bytes.
struct HexDigits<'a> {
    /// The text being read.
    bytes: &'a [u8],
    /// Index of the next unread byte.
    position: usize,
    /// Whether the last digit read was the first half of a byte.
    mid_byte: bool,
}

impl<'a> HexDigits<'a> {
    /// Starts reading at the beginning of `bytes`.
    fn new(bytes: &'a [u8]) -> Self {
        HexDigits {
            bytes,
            position: 0,
            mid_byte: false,
        }
    }
}

impl Iterator for HexDigits<'_> {
    type Item = Option<u8>;

    fn next(&mut self) -> Option<Self::Item> {
        loop {
            let byte = *self.bytes.get(self.position)?;
            let next = self.bytes.get(self.position + 1).copied();
            if let Some(digit) = char::from(byte).to_digit(16) {
                if !self.mid_byte && byte == b'0' && matches!(next, Some(b'x' | b'X')) {
                    // A 0x prefix
                    self.position += 2;
                    continue;
                }
                self.position += 1;
                self.mid_byte = !self.mid_byte;
                return Some(Some(digit as u8));
            }
            let is_prefix = byte == b'\\' && matches!(next, Some(b'x' | b'X'));
            let is_separator = byte.is_ascii_whitespace() || b":,;-%".contains(&byte);
            if self.mid_byte || !(is_prefix || is_separator) {
                // Stop for good after the first bad character
                self.position = self.bytes.len();
                return Some(None);
            }
            self.position += if is_prefix { 2 } else { 1 };
        }
    }
}

/// Whether `bytes` start like a bzip2 stream with data in it: `BZh`, a block-size digit
/// from `1` to `9` and the magic of the first block. An empty stream (`bz2.compress(b"")`)
/// has no block, so it is rejected here: it could only decompress to nothing.
fn has_stream_header(bytes: &[u8]) -> bool {
    bytes.len() >= MIN_STREAM_LEN
        && bytes.starts_with(&MAGIC)
        && (b'1'..=b'9').contains(&bytes[3])
        && bytes[4..10] == BLOCK_MAGIC
}

/// Decompresses a bzip2 file of one or more streams, as `bzip2 -d` does.
///
/// Every stream has to decompress and pass its block and stream CRCs, and the next one
/// has to start right after it. Unlike `bzip2 -d`, which warns about "trailing garbage"
/// and ignores it, bytes after the last stream are an error. Returns `None` if the data
/// isn't bzip2, is corrupt or truncated, has anything after its last stream, or
/// decompresses to more than [`MAX_OUTPUT`] bytes. In that case decompression stops at
/// the limit, so a bzip2 bomb costs about as much as decompressing [`MAX_OUTPUT`] bytes.
fn bunzip_bounded(compressed: &[u8]) -> Option<Vec<u8>> {
    if !has_stream_header(compressed) {
        return None;
    }

    // Room for typical text in one go; it grows when it fills up.
    let mut output = Vec::with_capacity((compressed.len() * 4).clamp(64, MAX_OUTPUT + 1));
    let mut rest = compressed;
    while !rest.is_empty() {
        // Like bzip2 -d, anything starting with the magic is another stream and has to
        // decompress. Unlike the first stream it may be empty.
        if !rest.starts_with(&MAGIC) {
            debug!("Bzip2: {} bytes after the last stream", rest.len());
            return None;
        }
        let stream_len = bunzip_stream(rest, &mut output)?;
        rest = &rest[stream_len..];
    }
    Some(output)
}

/// Decompresses the bzip2 stream at the start of `input`, appending to `output`, and
/// returns the stream's length in bytes. Returns `None` if the stream is corrupt or
/// truncated, or if `output` would grow past [`MAX_OUTPUT`] bytes.
fn bunzip_stream(input: &[u8], output: &mut Vec<u8>) -> Option<usize> {
    // The fast mode. The `small` one is about half as fast and still needs over 2 MB for
    // a level 9 block.
    let mut stream = Decompress::new(false);
    loop {
        // Never more than input.len(), which is a usize
        let read = stream.total_in() as usize;
        let written = output.len();
        let status = match stream.decompress_vec(&input[read..], output) {
            Ok(status) => status,
            Err(error) => {
                // A bad CRC, a corrupt block or a bad magic
                debug!("Bzip2 stream failed to decompress: {}", error);
                return None;
            }
        };
        if output.len() > MAX_OUTPUT {
            debug!("Bzip2 output is over {} bytes, giving up", MAX_OUTPUT);
            return None;
        }
        match status {
            Status::StreamEnd => return Some(stream.total_in() as usize),
            // The output is full. Make room, up to one byte over the limit, which tells an
            // output of exactly MAX_OUTPUT bytes apart from a longer one.
            Status::Ok if output.len() == output.capacity() => {
                let capacity = (output.capacity() * 2).min(MAX_OUTPUT + 1);
                output.reserve_exact(capacity - output.len());
            }
            // No progress with room left for output: the input ends inside the stream.
            Status::Ok if stream.total_in() as usize == read && output.len() == written => {
                debug!("Bzip2 stream is truncated");
                return None;
            }
            Status::Ok => {}
            // MemNeeded means libbzip2 couldn't allocate its buffers. The other statuses
            // are only returned when compressing.
            status => {
                debug!("Bzip2 stream stopped with {:?}", status);
                return None;
            }
        }
    }
}

/// Whether binary output is itself compressed, in a form one of the decoders reads from
/// raw bytes: another bzip2 stream, a gzip member, a zlib stream with a `78` header (as
/// the Zlib decoder's raw view expects) or an xz stream.
fn is_compressed(bytes: &[u8]) -> bool {
    has_stream_header(bytes)
        || bytes.starts_with(&GZIP_MAGIC)
        || bytes.starts_with(&XZ_MAGIC)
        || has_zlib_header(bytes)
}

/// Whether `bytes` start with a zlib header (RFC 1950 section 2.2) that the Zlib decoder
/// reads from raw bytes: `78` (DEFLATE with a 32 KiB window), a FLG byte that makes the
/// two a multiple of 31, and no preset dictionary.
fn has_zlib_header(bytes: &[u8]) -> bool {
    let &[cmf @ 0x78, flg, ..] = bytes else {
        return false;
    };
    u16::from_be_bytes([cmf, flg]) % 31 == 0 && flg & 0x20 == 0
}

/// The decompressed bytes as text, if they are UTF-8 text without control characters
/// other than tab, line feed and carriage return. Otherwise the bytes are handed back.
fn as_plaintext(data: Vec<u8>) -> Result<String, Vec<u8>> {
    let text = String::from_utf8(data).map_err(|error| error.into_bytes())?;
    let is_text = !text
        .chars()
        .any(|c| c.is_control() && !matches!(c, '\t' | '\n' | '\r'));
    if is_text {
        Ok(text)
    } else {
        Err(text.into_bytes())
    }
}

/// One character per byte, U+0000 to U+00FF. The inverse of [`raw_view`].
fn latin1_to_string(bytes: &[u8]) -> String {
    bytes.iter().map(|&byte| char::from(byte)).collect()
}

#[cfg(test)]
mod tests {
    use super::{
        bunzip_bounded, bzip2_bytes, hex_view, latin1_to_string, Bzip2Decoder, MAX_CANDIDATE,
        MAX_OUTPUT,
    };
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::{
            crack_results::CrackResult,
            gzip_decoder::GzipDecoder,
            hexadecimal_decoder::HexadecimalDecoder,
            interface::{Crack, Decoder},
            zlib_decoder::ZlibDecoder,
        },
    };
    use base64::{engine::general_purpose, Engine as _};
    use bzip2::{write::BzEncoder, Compression};
    use std::io::Write;
    use std::time::{Duration, Instant};

    // Unless noted otherwise, the vectors were made with Python 3.9's bz2.compress(data)
    // (level 9) and decompress to the same text with Python's bz2.decompress and
    // bzip2 1.0.8 (`bzip2 -dc`). The issue's plan also checked them with CyberChef 10.24's
    // Bzip2 Decompress.

    const SPHINX: &str = "Sphinx of black quartz, judge my vow.";
    /// The example in https://github.com/bee-san/Ciphey/issues/1023
    const SPHINX_BASE64: &str = "QlpoOTFBWSZTWX8PrZ8AAAQTgEAFCAA///fwIAAxQADQAAFGpiPQJkeoD9IZH/uFU+ROpY849TVELpy9lQD59QFyLuSKcKEg/h9bPg==";
    /// The same, as hex
    const SPHINX_HEX: &str = "425a68393141592653597f0fad9f0000041380400508003ffff7f02000314000d0000146a623d02647a80fd2191ffb8553e44ea58f38f535442e9cbd9500f9f501722ee48a70a120fe1f5b3e";

    const FOX: &str = "The quick brown fox jumps over the lazy dog";
    const FOX_BASE64: &str = "QlpoOTFBWSZTWUWd7mEAAAQTgEAABAA////wIAAxRoaAAAAx6ammTIYRtG1HYmIISe16oVNlZbEl4+JgsfiYOd1MCW+c6F3JFOFCQRZ3uYQ=";
    const FOX_HEX: &str = "425a6839314159265359459dee610000041380400004003ffffff0200031468680000031e9a9a64c8611b46d4762620849ed7aa1536565b125e3e260b1f89839dd4c096f9ce85dc914e142411677b984";

    /// The input every decoder sees in the benchmarks' `miss` cases
    const BENCH_MISS: &str =
        "T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV";

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn crack(text: &str) -> CrackResult {
        Decoder::<Bzip2Decoder>::new().crack(text, &get_athena_checker())
    }

    /// Runs the decoder and returns the first decoded string, if any
    fn decode(text: &str) -> Option<String> {
        crack(text).unencrypted_text.map(|texts| texts[0].clone())
    }

    fn hex_to_bytes(hex: &str) -> Vec<u8> {
        hex_view(hex).expect("valid bzip2 hex")
    }

    fn base64_to_bytes(text: &str) -> Vec<u8> {
        general_purpose::STANDARD.decode(text).unwrap()
    }

    /// Compresses `data` with libbz2-rs-sys, the pure-Rust libbzip2 the decoder uses
    fn compress(data: &[u8], level: u32) -> Vec<u8> {
        let mut encoder = BzEncoder::new(Vec::new(), Compression::new(level));
        encoder.write_all(data).unwrap();
        encoder.finish().unwrap()
    }

    #[test]
    fn decodes_issue_example_base64() {
        // Athena doesn't recognise this sentence as English (#1031), so only the text is
        // checked
        assert_eq!(decode(SPHINX_BASE64).as_deref(), Some(SPHINX));
    }

    #[test]
    fn decodes_issue_example_hex() {
        assert_eq!(decode(SPHINX_HEX).as_deref(), Some(SPHINX));
    }

    #[test]
    fn decodes_and_identifies_fox_base64() {
        let result = crack(FOX_BASE64);
        assert!(result.success, "Athena should identify the plaintext");
        assert_eq!(result.unencrypted_text.unwrap(), [FOX]);
        assert_eq!(result.decoder, "Bzip2");
        assert!(result.key.is_none(), "bzip2 has no key");
    }

    #[test]
    fn decodes_and_identifies_fox_hex() {
        let result = crack(FOX_HEX);
        assert!(result.success, "Athena should identify the plaintext");
        assert_eq!(result.unencrypted_text.unwrap(), [FOX]);
    }

    #[test]
    fn decodes_and_identifies_the_benchmark_texts() {
        // benches/data/decoders.toml: base64.b64encode(bz2.compress(text)) of the 84 and
        // 576 character texts
        let medium = "QlpoOTFBWSZTWWMBlygAAAkVgEAFAAI/794gIABIap5TNE9IwmyBEGQaGgDSU96PsiI3NPoK9qUAyQVg2dJPrHtnqvgZALhY1snmgBge3nckj1SElkwWxL4u5IpwoSDGAy5Q";
        let result = crack(medium);
        assert!(result.success, "Athena should identify the plaintext");
        assert_eq!(
            result.unencrypted_text.unwrap(),
            ["Meet me at the old lighthouse after midnight and bring the map, the key and a torch."]
        );

        let long = "QlpoOTFBWSZTWV1uyQEAADiXgEAFCiIAID/v3/AwAXWCQanoImFB5J6RppoET1J5MoNAeoNABpkKZNNNExENMml1UONSBOIUWjyEXOvQMSyYLFJe9GDQ4qzNygdIGlhJJTbelG6SE61osm0dzZX53RyHKJOCLQmbQ2awd6duAAiC/6TPAlh5VZiKLbITY+pj1Djx1Di91p0WySIJJyeB2ghXiB4vuT7T977RTGFnenVNQqhKYuhRxkVcLbWLRrWoeu0MNlgNvCHLX2VpPKQDuuXDouCRE3423GPFaqac1FL/dcrINfFuhmJbPiDrv7+Td6tpZD6LW71RlpxhM7SZKCAIvC+QdHGYYOIW7VDbPniLjI0he+efs2j19hMAjvG6qBknq2r3YRjipTU1pI+GBmHiwumy2g7JaAQmHyQJt8dbBTlDW1fsQ2gNCGqbAmaqugRz3KEznZ4zZiXGCLB+POv+LuSKcKEgut2SAg==";
        let result = crack(long);
        assert!(result.success, "Athena should identify the plaintext");
        let text = &result.unencrypted_text.unwrap()[0];
        assert_eq!(text.len(), 576);
        assert!(text.starts_with("Ciphey is an automated decoding tool."));
        assert!(text.ends_with("a strange string in a log file."));
    }

    #[test]
    fn decodes_and_identifies_a_ctf_flag() {
        // base64.b64encode(bz2.compress(b"flag{bzip2_block_sorting}"))
        let result = crack("QlpoOTFBWSZTWWimefAAAAOLgBAAAAC5rdwaIAAxTJiZBkYUABso2o0tbq4WS6BPmU+BXUPi7kinChINFM8+AA==");
        assert!(result.success, "LemmeKnow should identify the CTF flag");
        assert_eq!(
            result.unencrypted_text.unwrap(),
            ["flag{bzip2_block_sorting}"]
        );
    }

    #[test]
    fn decodes_url_safe_wrapped_and_unpadded_base64() {
        // base64.urlsafe_b64encode(bz2.compress(FOX))
        let url_safe = "QlpoOTFBWSZTWUWd7mEAAAQTgEAABAA____wIAAxRoaAAAAx6ammTIYRtG1HYmIISe16oVNlZbEl4-JgsfiYOd1MCW-c6F3JFOFCQRZ3uYQ=";
        let wrapped: String = FOX_BASE64
            .as_bytes()
            .chunks(20)
            .map(|line| format!("{}\r\n", std::str::from_utf8(line).unwrap()))
            .collect();
        let forms = [
            url_safe.to_string(),
            url_safe.trim_end_matches('=').to_string(),
            wrapped,
            FOX_BASE64.trim_end_matches('=').to_string(),
            format!("  {FOX_BASE64}\n"),
        ];
        for form in forms {
            assert_eq!(decode(&form).as_deref(), Some(FOX), "{form}");
        }
    }

    #[test]
    fn decodes_uppercase_and_delimited_hex() {
        let bytes = hex_to_bytes(FOX_HEX);
        let spaced: Vec<String> = bytes.iter().map(|b| format!("{b:02x}")).collect();
        let forms = [
            FOX_HEX.to_uppercase(),
            spaced.join(" "),
            spaced.join(":"),
            spaced.join("\n"),
            // xxd -i
            bytes
                .iter()
                .map(|b| format!("0x{b:02x}"))
                .collect::<Vec<_>>()
                .join(", "),
            // Python / C escapes
            bytes.iter().map(|b| format!("\\x{b:02X}")).collect(),
            format!("0x{FOX_HEX}"),
            format!("  {FOX_HEX}\n"),
        ];
        for form in forms {
            assert_eq!(decode(&form).as_deref(), Some(FOX), "{form}");
        }
    }

    #[test]
    fn decodes_every_block_size() {
        // bz2.compress(FOX, 1): only the block-size digit differs from level 9 here
        let level_1 = "QlpoMTFBWSZTWUWd7mEAAAQTgEAABAA////wIAAxRoaAAAAx6ammTIYRtG1HYmIISe16oVNlZbEl4+JgsfiYOd1MCW+c6F3JFOFCQRZ3uYQ=";
        assert_eq!(decode(level_1).as_deref(), Some(FOX));

        for level in 1..=9 {
            let compressed = compress(FOX.as_bytes(), level);
            assert!(compressed.starts_with(format!("BZh{level}").as_bytes()));
            let base64 = general_purpose::STANDARD.encode(&compressed);
            let expected_fifth = match level {
                1..=3 => 'M',
                4..=7 => 'N',
                _ => 'O',
            };
            assert_eq!(base64.chars().nth(4), Some(expected_fifth), "{base64}");
            assert_eq!(decode(&base64).as_deref(), Some(FOX), "level {level}");
        }
    }

    #[test]
    fn decodes_raw_bytes_from_the_hexadecimal_decoder() {
        // The Hexadecimal decoder turns bzip2 hex into Latin-1 text, one char per byte
        let hexadecimal =
            Decoder::<HexadecimalDecoder>::new().crack(FOX_HEX, &get_athena_checker());
        let raw = hexadecimal.unencrypted_text.expect("hex decodes")[0].clone();
        assert_eq!(raw, latin1_to_string(&hex_to_bytes(FOX_HEX)));
        assert_eq!(decode(&raw).as_deref(), Some(FOX));
    }

    #[test]
    fn decodes_concatenated_streams() {
        // bz2.compress(b"The quick brown fox ") + bz2.compress(b"jumps over the lazy dog").
        // CyberChef stops after the first stream; bzip2 -dc and Python read both.
        let two_streams = "QlpoOTFBWSZTWQgcCrAAAAITgEAABAAbabLAIAAxTAATQiBpo9Rp+qG1GGStHkE5kG+LuSKcKEgEDgVYAEJaaDkxQVkmU1k7GV5oAAAFEYBAACbW3zAgADFNMjExMQoGhpmptIcgdRSIdCLw5wVmfi7kinChIHYyvNA=";
        assert_eq!(decode(two_streams).as_deref(), Some(FOX));

        // bz2.compress(FOX) + bz2.compress(b""): an empty stream is fine after the first
        let fox_then_empty = "QlpoOTFBWSZTWUWd7mEAAAQTgEAABAA////wIAAxRoaAAAAx6ammTIYRtG1HYmIISe16oVNlZbEl4+JgsfiYOd1MCW+c6F3JFOFCQRZ3uYRCWmg5F3JFOFCQAAAAAA==";
        assert_eq!(decode(fox_then_empty).as_deref(), Some(FOX));

        // The same stream three times, at different levels
        let fox = FOX.as_bytes();
        let three = [compress(fox, 1), compress(fox, 5), compress(fox, 9)].concat();
        assert_eq!(bunzip_bounded(&three), Some(fox.repeat(3)));
    }

    #[test]
    fn rejects_bytes_after_the_last_stream() {
        // bz2.compress(FOX) + b"GARBAGE". bzip2 -dc warns "trailing garbage after EOF
        // ignored" and Python ignores it too; this decoder wants every byte to be bzip2.
        let garbage = "QlpoOTFBWSZTWUWd7mEAAAQTgEAABAA////wIAAxRoaAAAAx6ammTIYRtG1HYmIISe16oVNlZbEl4+JgsfiYOd1MCW+c6F3JFOFCQRZ3uYRHQVJCQUdF";
        assert_eq!(decode(garbage), None);

        let fox = hex_to_bytes(FOX_HEX);
        for tail in [
            &b"\0\0\0\0"[..],
            b"BZh",
            b"BZh9",
            // A second stream cut off: bzip2 -dc says "Compressed file ends unexpectedly"
            &fox[..30],
        ] {
            let compressed = [fox.as_slice(), tail].concat();
            assert_eq!(bunzip_bounded(&compressed), None, "{tail:?}");
            assert_eq!(decode(&latin1_to_string(&compressed)), None, "{tail:?}");
        }
    }

    #[test]
    fn rejects_bad_crcs_and_truncated_streams() {
        // One bit of the block CRC flipped. Python: "Invalid data stream", bzip2 -dc:
        // "Data integrity error when decompressing", CyberChef: an error.
        let bad_block_crc = "QlpoOTFBWSZTWUWd72EAAAQTgEAABAA////wIAAxRoaAAAAx6ammTIYRtG1HYmIISe16oVNlZbEl4+JgsfiYOd1MCW+c6F3JFOFCQRZ3uYQ=";
        // One bit of the stream CRC flipped (in the second-to-last byte, which is all CRC
        // bits). Python and bzip2 -dc fail the same way.
        let bad_stream_crc = "425a6839314159265359459dee610000041380400004003ffffff0200031468680000031e9a9a64c8611b46d4762620849ed7aa1536565b125e3e260b1f89839dd4c096f9ce85dc914e142411677b884";
        // The fox stream without its last bytes. Python: "Compressed data ended before
        // the end-of-stream marker was reached".
        let truncated = "QlpoOTFBWSZTWUWd7mEAAAQTgEAABAA////wIAAxRoaAAAAx6ammTIYRtG1HYmIISe16oVNlZbEl4+JgsfiYOd1MCW+c6F3JFOE=";

        for text in [bad_block_crc, bad_stream_crc, truncated] {
            assert_eq!(decode(text), None, "{text}");
            let bytes = bzip2_bytes(text).expect("the views read it");
            assert_eq!(bunzip_bounded(&bytes), None, "{text}");
        }

        // Every shorter prefix of the fox stream is truncated too
        let fox = hex_to_bytes(FOX_HEX);
        for len in 0..fox.len() {
            assert_eq!(bunzip_bounded(&fox[..len]), None, "{len} bytes");
        }
    }

    #[test]
    fn rejects_header_only_and_empty_streams() {
        for text in [
            // The stream header and the first block's magic, and nothing else
            "BZh91AY&SY",
            "QlpoOTFBWSZTWQ==",
            "QlpoOTFBWSZTW",
            "425a68393141592653",
            "QlpoO",
            "Qlpo",
            // bz2.compress(b""): a valid stream with no block, which can only be empty
            "425a683917724538509000000000",
            "QlpoORdyRThQkAAAAAA=",
        ] {
            assert_eq!(decode(text), None, "{text}");
        }
        assert_eq!(
            bunzip_bounded(&hex_to_bytes("425a683917724538509000000000")),
            None
        );
        assert_eq!(bunzip_bounded(b""), None);
    }

    #[test]
    fn rejects_binary_output() {
        // bz2.compress(bytes(range(256))): not UTF-8
        let binary = "QlpoOTFBWSZTWba17pUAAAB/////////////////////////////////////////////sADFUgAAAAAAAAAAAAAAAAAAAAABMAmAAAAAAAAAAAAAAEwABMAEmAAmAAJgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkwAEwABMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwCAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ent8fX5/gIGCg4SFhoeIiYqLjI2Oj5CRkpWWl5iZmpucnZ6foKGio6SlpqeoqaqrrK2ur7CxsrO0tba3uLm6u7y9vr/AwcLDxMXGxcbHyMnKy8zNzs/Q0dLT1NXW19jZ2tvc3d7f4OHi4+Tl5ufo6err7O3u7/Dx8vP09fb3+Pn6+/z9F3JFOFCQtrXulQ=";
        let bytes = bunzip_bounded(&base64_to_bytes(binary)).expect("it decompresses");
        assert_eq!(bytes, (0..=255).collect::<Vec<u8>>());
        assert_eq!(decode(binary), None);
        // bz2.compress(b"\x1b[31mred alert\x1b[0m"): UTF-8 with control characters
        assert_eq!(
            decode("QlpoOTFBWSZTWcM4SKcAAAC7gAAIQABoAAAIJgYUACAAIoabU0e1CAaAB+qtThfAY0rF3JFOFCQwzhIpwA=="),
            None
        );
    }

    #[test]
    fn returns_nested_bzip2_for_another_bzip2_step() {
        // base64.b64encode(bz2.compress(bz2.compress(FOX)))
        let nested = "QlpoOTFBWSZTWZmZ/HkAAA5//8RgLQBDACAg86QIMnJCgJBFAABGISAkIAAgAAI4Y0BAoABUYAAAAAAAABpkGAAAADQDQANAAACuUkQYQNG/UWJzzOR5EYNxKwIdr0CrHdhSiZrT548BablhwG4NFwK9Bc7d+iX83ADLoXgbwi+6I+/F3JFOFCQmZn8eQA==";
        let result = crack(nested);
        assert!(!result.success, "the inner stream is binary, not plaintext");
        let inner = result.unencrypted_text.expect("the inner bzip2 stream");
        assert_eq!(inner, [latin1_to_string(&hex_to_bytes(FOX_HEX))]);

        // Second step, on the first step's output
        let result = crack(&inner[0]);
        assert!(result.success);
        assert_eq!(result.unencrypted_text.unwrap(), [FOX]);
    }

    #[test]
    fn returns_other_compressed_data_for_its_decoder() {
        let checker = get_athena_checker();
        // base64.b64encode(bz2.compress(gzip.compress(FOX, mtime=0)))
        let gzip_inside = crack("QlpoOTFBWSZTWbzcZ80AAAd+VfhIAACEXoAgIFzbAAAIDICAe4SAAACgAFRjRoNGEYjRoaNMTahU9RkHqAyAaNNMmjahwEDGQFSGcEgl8qDR2tnqzwrZ3B2LBfBMUjFqmvcRRJGzEUpqAA/F3JFOFCQvNxnzQA==");
        let gzip = &gzip_inside.unencrypted_text.expect("the gzip member")[0];
        assert!(gzip.starts_with("\u{1f}\u{8b}\u{8}"), "{gzip:?}");
        let gunzipped = Decoder::<GzipDecoder>::new().crack(gzip, &checker);
        assert_eq!(gunzipped.unencrypted_text.unwrap(), [FOX]);

        // base64.b64encode(bz2.compress(zlib.compress(FOX)))
        let zlib_inside = crack("QlpoOTFBWSZTWfxa3BEAABBWt2gIhFaAXFsIAEAABASAgHuAFASAIABIxoaGhpoBiNHo09UMMjAmmBMhiaMKrXNMcdMRrBUeay7LzZ15LNajexs5QAPD5OSInvKYGBdyRThQkPxa3BE=");
        let zlib = &zlib_inside.unencrypted_text.expect("the zlib stream")[0];
        assert!(zlib.starts_with("x\u{9c}"), "{zlib:?}");
        let inflated = Decoder::<ZlibDecoder>::new().crack(zlib, &checker);
        assert_eq!(inflated.unencrypted_text.unwrap(), [FOX]);

        // base64.b64encode(bz2.compress(lzma.compress(FOX))): there is no xz decoder yet,
        // but the stream is handed on for one
        let xz_inside = crack("QlpoOTFBWSZTWX/T3yAAADJ/n/QAAQDgGICACRBE+T////IoAgVAFAABAAMACAIgAHQ5k/URoYhiaDCGgyMajanmqaZ6QinqDUM0jEYAgxNMGhqD0QARBUdwyvJgQiYH7FUcEFnpz9DzGE2oIr/xUeESMojo50549DLGxJXO9SkPay4msCI6Mkv1PMBHXj4oFVxfitIHFXl4UWAu5IpwoSD/p75A");
        let xz = &xz_inside.unencrypted_text.expect("the xz stream")[0];
        assert!(xz.starts_with("\u{fd}7zXZ\0"), "{xz:?}");
    }

    #[test]
    fn stops_a_bzip2_bomb_at_the_size_limit() {
        // base64.b64encode(bz2.compress(b"A" * 64 * 1024 * 1024)): 83 bytes of bzip2.
        // Decompressing stops one byte past MAX_OUTPUT, which takes ~30 ms per call in an
        // unoptimised build.
        let bomb = "QlpoOTFBWSZTWXlGrZMBX44EAKAAAAggADCATUZCoCWpCoCXMUFZJlNZ7C9A/ACidcQAwAAgAAAIIAAgpTQZjjVFRCbFRUQni7kinChID1EN7QA=";
        let start = Instant::now();
        assert_eq!(bunzip_bounded(&base64_to_bytes(bomb)), None);
        assert_eq!(decode(bomb), None);
        assert!(
            start.elapsed() < Duration::from_secs(1),
            "took {:?}",
            start.elapsed()
        );
    }

    #[test]
    fn output_size_limit_is_inclusive() {
        let at_limit = compress(&vec![b'A'; MAX_OUTPUT], 9);
        assert_eq!(bunzip_bounded(&at_limit).unwrap().len(), MAX_OUTPUT);

        let over_limit = compress(&vec![b'A'; MAX_OUTPUT + 1], 9);
        assert_eq!(bunzip_bounded(&over_limit), None);

        // The limit is for all streams together
        let half = compress(&vec![b'A'; MAX_OUTPUT / 2 + 1], 9);
        assert_eq!(bunzip_bounded(&[half.clone(), half].concat()), None);
    }

    #[test]
    fn long_output_is_only_kept_if_the_checker_accepts_it() {
        let crack_compressed =
            |data: &[u8]| crack(&general_purpose::STANDARD.encode(compress(data, 9)));

        // Not plaintext: handed on for more decoding up to the limit, dropped above it
        let result = crack_compressed(&vec![b'A'; MAX_CANDIDATE]);
        assert!(!result.success);
        assert_eq!(result.unencrypted_text.unwrap()[0].len(), MAX_CANDIDATE);
        assert!(crack_compressed(&vec![b'A'; MAX_CANDIDATE + 1])
            .unencrypted_text
            .is_none());

        // Plaintext is returned whatever its length (up to MAX_OUTPUT)
        let english = format!("{FOX}. ").repeat(MAX_CANDIDATE / FOX.len() + 1);
        assert!(english.len() > MAX_CANDIDATE);
        let result = crack_compressed(english.as_bytes());
        assert!(result.success, "Athena should identify the plaintext");
        assert_eq!(result.unencrypted_text.unwrap(), [english]);
    }

    #[test]
    fn long_nested_bzip2_is_not_handed_on() {
        // Pseudo-random bytes (xorshift64) don't compress, so the inner bzip2 stream is
        // longer than the limit
        let mut state = 0x2545_f491_4f6c_dd1d_u64;
        let noise: Vec<u8> = (0..MAX_CANDIDATE)
            .map(|_| {
                state ^= state << 13;
                state ^= state >> 7;
                state ^= state << 17;
                state as u8
            })
            .collect();
        let inner = compress(&noise, 9);
        assert!(inner.len() > MAX_CANDIDATE);
        assert_eq!(bunzip_bounded(&inner), Some(noise));
        let nested = general_purpose::STANDARD.encode(compress(&inner, 9));
        assert!(crack(&nested).unencrypted_text.is_none());
    }

    #[test]
    fn rejects_text_that_is_not_bzip2() {
        // None of these are bzip2 as Base64, hex or raw bytes, so nothing is decompressed
        for text in [
            "",
            "   ",
            "😀",
            "hello world",
            "hello my name is panicky mc panic face!",
            BENCH_MISS,
            "BZh is a compression format",
            "BZh91AY&SY",
            // Base64 and hex that aren't bzip2
            "aGVsbG8gd29ybGQ=",
            "68656c6c6f20776f726c64",
            "Qlpo",
            "QlpoA is not how bzip2 starts",
            // Starts like bzip2 in Base64, but isn't Base64 (37 characters without spaces)
            "QlpoOTFBWSZTW is how bzip2 starts in Base64",
            "425a68 is the bzip2 magic in hex",
            "425a6g393141592653597f0fad9f0000041380400508003ffff7f0",
            // A separator inside a byte
            "425a6 8393141592653597f0fad9f0000041380400508003ffff7f0",
            // Block size 0
            "425a6830314159265359459dee610000041380400004003ffffff0200031468680000031e9a9a64c8611b46d4762620849ed7aa1536565b125e3e260b1f89839dd4c096f9ce85dc914e142411677b984",
            // Too much padding
            "QlpoOTFBWSZTWUWd7mEAAAQTgEAABAA////wIAAxRoaAAAAx6ammTIYRtG1HYmIISe16oVNlZbEl4+JgsfiYOd1MCW+c6F3JFOFCQRZ3uYQ===",
            // The fox sentence compressed by the other formats: zlib.compress (#1021),
            // gzip.compress(mtime=0) (#1020), raw DEFLATE (zlib.compressobj(wbits=-15),
            // #1022) and lzma.compress (xz, #1024)
            "eJwLyUhVKCzNTM5WSCrKL89TSMuvUMgqzS0oVsgvSy1SKAFK5yRWVSqk5KcDAFvcD9o=",
            "H4sIAAAAAAAC/wvJSFUoLM1MzlZIKsovz1NIy69QyCrNLShWyC9LLVIoAUrnJFZVKqTkpwMAOaNPQSsAAAA=",
            "C8lIVSgszUzOVkgqyi/PU0jLr1DIKs0tKFbIL0stUigBSuckVlUqpOSnAwA=",
            "/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAxKFK5cK4XlsAAUMrrVBuVx+2830BAAAAAARZWg==",
        ] {
            assert_eq!(bzip2_bytes(text), None, "{text}");
            assert_eq!(decode(text), None, "{text}");
        }

        // These have a stream header but don't decompress
        for text in [
            // base64.b64encode(b"BZh91AY&SY" + bytes(30))
            "QlpoOTFBWSZTWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
            "425a68393141592653590000000000000000000000000000000000000000",
            "BZh91AY&SY and then some text that is not a block",
        ] {
            assert!(bzip2_bytes(text).is_some(), "{text}");
            assert_eq!(decode(text), None, "{text}");
        }
    }

    #[test]
    fn rejects_latin1_text_with_characters_above_u00ff() {
        let mut raw = latin1_to_string(&hex_to_bytes(FOX_HEX));
        raw.push('€');
        assert_eq!(bzip2_bytes(&raw), None);
    }

    #[test]
    fn bzip2_handles_panic_if_empty_string() {
        let result = crack("").unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn bzip2_handles_panic_if_emoji() {
        let result = crack("😂").unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn is_registered() {
        let decoders = crate::filtration_system::get_decoder_by_name("Bzip2");
        assert_eq!(decoders.components.len(), 1);
        // Cached search paths name their decoders, and are read back through the map
        assert!(crate::decoders::DECODER_MAP.contains_key("Bzip2"));
    }
}
