//! Decode the Core Socialist Values encoding (社会主义核心价值观编码), which writes the
//! UTF-8 bytes of a message as base-12 digits, each digit one of the twelve two-character
//! values:
//!
//! ```text
//! 0 富强  1 民主  2 文明  3 和谐  4 自由  5 平等  6 公正  7 法治  8 爱国  9 敬业  10 诚信  11 友善
//! ```
//!
//! The encoder takes the upper-case hex of the bytes. A hex digit from 0 to 9 is one value.
//! A digit from A to F is two: 诚信 (10) and then the digit minus 10, or 友善 (11) and then
//! the digit minus 6, chosen at random for each digit, so one text has many encodings. In
//! `hello world`, which starts 公正爱国公正平等公正友善公正, `h` is 0x68 (公正 爱国) and
//! `l` is 0x6C (公正, then 友善 公正 for C).
//!
//! The reference decoder skips every character that isn't one of the 24 and reads only the
//! first character of each value. This one is strict, so that it only fires on text that
//! is this encoding: ASCII whitespace is skipped, but any other character, a value split
//! across two others (`强民`), an escape followed by a digit the encoder never writes after
//! it, or a leftover digit fails.
//!
//! Reference: `valuesEncode` and `valuesDecode` in sym233/core-values-encoder
//! <https://github.com/sym233/core-values-encoder/blob/a419ea532629782ebe7442a8682b72bb5ae3eab5/src/index.js>
//! (ISC; the algorithm is ported, not copied) and its web page
//! <https://sym233.github.io/core-values-encoder/>.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The Core Socialist Values decoder, call:
/// `let decoder = Decoder::<CoreSocialistValuesDecoder>::new()` to create a new instance
/// And then call:
/// `result = decoder.crack(input)` to decode a Core Socialist Values string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::core_socialist_values_decoder::CoreSocialistValuesDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decoder = Decoder::<CoreSocialistValuesDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decoder
///     .crack(
///         "公正爱国公正平等公正友善公正公正友善公正公正诚信平等文明富强法治法治公正诚信平等法治文明公正诚信文明公正自由",
///         &checker,
///     )
///     .unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hello world");
/// ```
pub struct CoreSocialistValuesDecoder;

/// The fewest characters (four values) the decoder accepts. One byte takes two to four
/// values, and the search rejects results of two bytes or fewer anyway.
const MIN_CHARS: usize = 8;

impl Crack for Decoder<CoreSocialistValuesDecoder> {
    fn new() -> Decoder<CoreSocialistValuesDecoder> {
        Decoder {
            name: "Core Socialist Values",
            description: "Core Socialist Values encoding (社会主义核心价值观): UTF-8 bytes written as base-12 digits using the twelve two-character values",
            link: "https://github.com/sym233/core-values-encoder",
            tags: vec!["core_socialist_values", "chinese", "ctf", "base", "decoder"],
            // Common in Chinese CTF warm-ups and rare anywhere else. It costs nothing on
            // other input: everything that isn't these 24 characters fails at once.
            popularity: 0.3,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes `text` as Core Socialist Values and checks the result with `checker`.
    /// `unencrypted_text` is `None` when `text` isn't this encoding or doesn't decode to
    /// text.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Core Socialist Values with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(bytes) = decode_core_socialist_values(text) else {
            debug!("Failed to decode Core Socialist Values because the text isn't made of the twelve values");
            return results;
        };

        // Strict UTF-8, as the reference's decodeURIComponent is
        let Ok(decoded_text) = String::from_utf8(bytes) else {
            debug!("Failed to decode Core Socialist Values because the bytes aren't UTF-8");
            return results;
        };
        trace!("Decoded text for Core Socialist Values: {:?}", decoded_text);

        if !is_text(&decoded_text) {
            debug!("Failed to decode Core Socialist Values because the bytes are control characters or only whitespace");
            return results;
        }

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Core Socialist Values because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Reads the values back into the bytes they stand for, or returns `None` if `text` isn't
/// the Core Socialist Values encoding.
///
/// ASCII whitespace anywhere is skipped. Everything else must be one of the 24 characters,
/// in the pairs that make the twelve values, and the values must make whole hex digits
/// and whole bytes.
fn decode_core_socialist_values(text: &str) -> Option<Vec<u8>> {
    // Every value is two Han characters, so ASCII text (Base64, hex, English, ...) isn't
    // this encoding. Almost every text a search tries stops here.
    if text.is_ascii() {
        return None;
    }

    let mut bytes = Vec::new();
    // The first character of the value being read, as its index in `char_index`
    let mut first_half: Option<u8> = None;
    // A 10 or 11 waiting for the digit after it
    let mut escape: Option<u8> = None;
    // The high nibble of the byte being read
    let mut high_nibble: Option<u8> = None;
    let mut chars = 0;

    for c in text.chars() {
        if c.is_ascii_whitespace() {
            continue;
        }
        // Fails on the first character that isn't one of the 24, so Chinese prose, emoji,
        // Braille and Base65536 stop at their first character, before anything is
        // allocated
        let index = char_index(c)?;
        chars += 1;

        let Some(first) = first_half.take() else {
            // 富, 民, 文, ... start a value; 强, 主, 明, ... end one
            if !index.is_multiple_of(2) {
                return None;
            }
            first_half = Some(index);
            continue;
        };
        // The second half of the same value: 富强, not 富民 or 富富
        if index != first + 1 {
            return None;
        }

        let digit = first / 2;
        let nibble = match escape.take() {
            None if digit < 10 => digit,
            None => {
                escape = Some(digit);
                continue;
            }
            // 诚信 then 富强 to 平等 is A to F
            Some(10) if digit <= 5 => digit + 10,
            // 友善 then 自由 to 敬业 is A to F
            Some(11) if (4..=9).contains(&digit) => digit + 6,
            // The encoder never writes these: the reference would make a wrong hex digit or
            // one past F
            Some(_) => return None,
        };
        match high_nibble.take() {
            None => high_nibble = Some(nibble),
            Some(high) => bytes.push(high << 4 | nibble),
        }
    }

    // Half a value, an escape with nothing after it, or half a byte left over
    if chars < MIN_CHARS || first_half.is_some() || escape.is_some() || high_nibble.is_some() {
        return None;
    }
    Some(bytes)
}

/// Where `c` is in 富强民主文明和谐自由平等公正法治爱国敬业诚信友善 (0 to 23), so the value
/// for digit `d` is the characters at `2d` and `2d + 1`. `None` for any other character.
fn char_index(c: char) -> Option<u8> {
    Some(match c {
        '富' => 0,
        '强' => 1,
        '民' => 2,
        '主' => 3,
        '文' => 4,
        '明' => 5,
        '和' => 6,
        '谐' => 7,
        '自' => 8,
        '由' => 9,
        '平' => 10,
        '等' => 11,
        '公' => 12,
        '正' => 13,
        '法' => 14,
        '治' => 15,
        '爱' => 16,
        '国' => 17,
        '敬' => 18,
        '业' => 19,
        '诚' => 20,
        '信' => 21,
        '友' => 22,
        '善' => 23,
        _ => return None,
    })
}

/// Whether decoded bytes are text: no control characters except tabs and line breaks
/// (U+007F and the C1 controls count as control characters), and not only whitespace.
fn is_text(text: &str) -> bool {
    !text.trim().is_empty()
        && !text
            .chars()
            .any(|c| c.is_control() && !matches!(c, '\t' | '\n' | '\r'))
}

#[cfg(test)]
mod tests {
    use super::{decode_core_socialist_values, CoreSocialistValuesDecoder};
    use crate::checkers::athena::Athena;
    use crate::checkers::checker_type::{Check, Checker};
    use crate::checkers::CheckerTypes;
    use crate::decoders::interface::{Crack, Decoder};
    use crate::decoders::{DecoderType, DECODER_MAP};
    use crate::filtration_system::get_decoder_by_name;

    // Unless noted otherwise, the encodings here were made with `valuesEncode` from the
    // reference implementation (sym233/core-values-encoder@a419ea5, src/index.js, run
    // with node 22) and decoded back with its `valuesDecode`. "All 10" and "all 11" mean
    // its random choice of escape was fixed to 诚信 (10) or 友善 (11) for every hex digit
    // from A to F; the others use the random choice as it is.

    /// The issue's example: `hello world` with both escapes
    /// (https://github.com/bee-san/Ciphey/issues/978)
    const HELLO_WORLD: &str = "公正爱国公正平等公正友善公正公正友善公正公正诚信平等文明富强法治法治公正诚信平等法治文明公正诚信文明公正自由";

    /// `hello world`, all 10
    const HELLO_WORLD_TEN: &str = "公正爱国公正平等公正诚信文明公正诚信文明公正诚信平等文明富强法治法治公正诚信平等法治文明公正诚信文明公正自由";

    /// `hello world`, all 11
    const HELLO_WORLD_ELEVEN: &str = "公正爱国公正平等公正友善公正公正友善公正公正友善敬业文明富强法治法治公正友善敬业法治文明公正友善公正公正自由";

    /// `flag{s0c1al_c0r3}`, all 10
    const FLAG: &str = "公正公正公正诚信文明公正民主公正法治法治诚信民主法治和谐和谐富强公正和谐和谐民主公正民主公正诚信文明平等诚信平等公正和谐和谐富强法治文明和谐和谐法治诚信和谐";

    /// `你好，世界` (with a full-width comma), all 10
    const NI_HAO: &str = "诚信自由自由诚信民主诚信和谐诚信富强富强诚信自由平等诚信富强平等诚信民主诚信和谐诚信自由诚信平等诚信民主诚信文明爱国诚信文明诚信自由自由诚信民主爱国敬业公正诚信自由法治敬业平等爱国诚信文明";

    /// The bench `medium` plaintext, and the `search.toml` plaintext
    const MEDIUM: &str =
        "Meet me at the old lighthouse after midnight and bring the map, the key and a torch.";

    /// The bench `long` plaintext
    const LONG: &str = "Ciphey is an automated decoding tool. You give it encrypted or encoded text and it tries to work out what was done to it, without you having to know the key or even the cipher. It searches through many possible decodings, checks each candidate to see whether it looks like English or matches a known pattern such as an email address, and stops when it finds something that reads like plaintext. Most of the time this takes less than a second, which makes it handy for capture the flag challenges, puzzle hunts and for anyone who stumbles across a strange string in a log file.";

    /// The twelve values, in digit order
    const VALUES: [&str; 12] = [
        "富强", "民主", "文明", "和谐", "自由", "平等", "公正", "法治", "爱国", "敬业", "诚信",
        "友善",
    ];

    /// The reference's `valuesEncode` with its random choice fixed: every hex digit from A
    /// to F is written with the escape `escape`, 10 (诚信) or 11 (友善).
    fn encode(text: &str, escape: u8) -> String {
        let mut digits = Vec::new();
        for byte in text.bytes() {
            for nibble in [byte >> 4, byte & 0x0F] {
                match (nibble, escape) {
                    (0..=9, _) => digits.push(nibble),
                    (_, 10) => digits.extend([10, nibble - 10]),
                    _ => digits.extend([11, nibble - 6]),
                }
            }
        }
        digits
            .iter()
            .map(|&digit| VALUES[usize::from(digit)])
            .collect()
    }

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    // Runs the decoder with the Athena checker and returns the decoded text, if any
    fn crack(text: &str) -> Option<String> {
        let decoder = Decoder::<CoreSocialistValuesDecoder>::new();
        let result = decoder.crack(text, &get_athena_checker());
        if result.unencrypted_text.is_none() {
            assert!(!result.success, "{text:?} failed but was marked successful");
        }
        result.unencrypted_text.map(|texts| texts[0].clone())
    }

    // Asserts that Athena accepts what `text` decodes to and returns it
    fn crack_successfully(text: &str) -> String {
        let decoder = Decoder::<CoreSocialistValuesDecoder>::new();
        let result = decoder.crack(text, &get_athena_checker());
        assert!(result.success, "Athena should accept {text:?}: {result:?}");
        result.unencrypted_text.unwrap()[0].clone()
    }

    #[test]
    fn decodes_the_issue_example() {
        assert_eq!(crack_successfully(HELLO_WORLD), "hello world");
    }

    #[test]
    fn decodes_both_escapes() {
        assert_eq!(crack_successfully(HELLO_WORLD_TEN), "hello world");
        assert_eq!(crack_successfully(HELLO_WORLD_ELEVEN), "hello world");
    }

    #[test]
    fn test_encoder_matches_the_reference() {
        // The encoder the other tests use writes what the reference writes
        assert_eq!(encode("hello world", 10), HELLO_WORLD_TEN);
        assert_eq!(encode("hello world", 11), HELLO_WORLD_ELEVEN);
        assert_eq!(encode("flag{s0c1al_c0r3}", 10), FLAG);
        assert_eq!(encode("你好，世界", 10), NI_HAO);
    }

    #[test]
    fn decodes_the_fox_pangram() {
        assert_eq!(
            crack_successfully("平等自由公正爱国公正平等文明富强法治民主法治平等公正敬业公正和谐公正诚信民主文明富强公正文明法治文明公正友善敬业法治法治公正诚信自由文明富强公正公正公正友善敬业法治爱国文明富强公正诚信富强法治平等公正友善法治法治富强法治和谐文明富强公正诚信平等法治公正公正平等法治文明文明富强法治自由公正爱国公正平等文明富强公正诚信文明公正民主法治诚信富强法治敬业文明富强公正自由公正诚信平等公正法治"),
            "The quick brown fox jumps over the lazy dog"
        );
    }

    #[test]
    fn decodes_a_ctf_flag() {
        let decoder = Decoder::<CoreSocialistValuesDecoder>::new();
        let result = decoder.crack(FLAG, &get_athena_checker());
        assert!(
            result.success,
            "LemmeKnow should identify the flag: {result:?}"
        );
        assert_eq!(result.checker_name, "LemmeKnow Checker");
        assert_eq!(result.unencrypted_text.unwrap()[0], "flag{s0c1al_c0r3}");
    }

    #[test]
    fn decodes_the_bench_texts() {
        // benches/data/decoders.toml: medium is all 10, long all 11
        assert_eq!(crack_successfully(&encode(MEDIUM, 10)), MEDIUM);
        assert_eq!(crack_successfully(&encode(LONG, 11)), LONG);
        assert_eq!(encode(MEDIUM, 10).chars().count(), 368);
        assert_eq!(encode(LONG, 11).len(), 7602);
    }

    #[test]
    fn decodes_utf8_text() {
        // Decoded, though Athena doesn't take Chinese for plaintext
        assert_eq!(crack(NI_HAO).unwrap(), "你好，世界");
        // 😀 is F0 9F 98 80, all 10
        assert_eq!(
            crack("诚信平等富强敬业诚信平等敬业爱国爱国富强").unwrap(),
            "😀"
        );
    }

    #[test]
    fn round_trips_every_printable_ascii_character() {
        // Every hex digit, high and low, with both escapes
        let printable: String = (' '..='~').collect();
        for escape in [10, 11] {
            let encoded = encode(&printable, escape);
            assert_eq!(
                decode_core_socialist_values(&encoded),
                Some(printable.as_bytes().to_vec()),
                "escape {escape}"
            );
        }
    }

    #[test]
    fn skips_ascii_whitespace() {
        // The issue's example with a space after each byte
        assert_eq!(
            crack_successfully("公正爱国 公正平等 公正友善公正 公正友善公正 公正诚信平等 文明富强 法治法治 公正诚信平等 法治文明 公正诚信文明 公正自由"),
            "hello world"
        );
        // Wrapped lines, tabs, and whitespace inside a value
        assert_eq!(
            crack_successfully("公正爱国公正平等公正友善公正\r\n公正友善公正公正诚信平等文明\n富强法治法治\t公正诚信平等法治文明公 正诚信文明公正自由\n"),
            "hello world"
        );
    }

    #[test]
    fn decode_returns_the_bytes() {
        // he
        assert_eq!(
            decode_core_socialist_values("公正爱国公正平等"),
            Some(b"he".to_vec())
        );
        // FF FF, which isn't UTF-8
        assert_eq!(
            decode_core_socialist_values("诚信平等诚信平等诚信平等诚信平等"),
            Some(vec![0xFF, 0xFF])
        );
        // 01 23
        assert_eq!(
            decode_core_socialist_values("富强民主文明和谐"),
            Some(vec![0x01, 0x23])
        );
    }

    #[test]
    fn fails_on_too_few_values() {
        // One, two and three values
        assert_eq!(crack("富强"), None);
        assert_eq!(crack("公正爱国"), None);
        assert_eq!(crack("富强民主文明"), None);
        // `h` is two values; four are the fewest accepted
        assert_eq!(decode_core_socialist_values("公正爱国"), None);
    }

    #[test]
    fn fails_on_half_a_value() {
        // An odd number of characters
        assert_eq!(crack("富强民"), None);
        assert_eq!(crack(&HELLO_WORLD[..HELLO_WORLD.len() - 3]), None);
        // The example misaligned by one character: 强民 is not a value
        assert_eq!(crack(&HELLO_WORLD[3..]), None);
    }

    #[test]
    fn fails_on_characters_that_are_not_paired() {
        // 富 and 民 both start a value
        assert_eq!(crack("富民富民富民富民"), None);
        // 强民 ends one value and starts the next
        assert_eq!(crack("强民主文明和谐自"), None);
        // 富富 is one character twice
        assert_eq!(crack("富富强强富富强强"), None);
    }

    #[test]
    fn fails_on_escapes_the_encoder_never_writes() {
        // 诚信 (10) then 友善 (11): the slogan, all twelve values in order
        assert_eq!(
            crack("富强民主文明和谐自由平等公正法治爱国敬业诚信友善"),
            None
        );
        // 友善 (11) then 公正 (6) would be C, but 诚信 (10) then 公正 is past F
        assert_eq!(crack("诚信公正公正公正"), None);
        // 友善 (11) then 民主 (1) would be 7, which the encoder writes as one value
        assert_eq!(crack("友善民主公正公正"), None);
        // An escape at the end
        assert_eq!(crack("公正爱国公正平等诚信"), None);
        // 诚信 followed by 友善 and 敬业: valid pairs, but neither is a digit 10 or 11 can
        // take. The reference reads them as 0x15 and 0x13 followed by `f`.
        assert_eq!(crack("诚信友善公正公正"), None);
        assert_eq!(crack("诚信敬业公正公正"), None);
    }

    #[test]
    fn fails_on_half_a_byte() {
        // Seven values, seven hex digits
        assert_eq!(crack("富强富强富强富强富强富强富强"), None);
    }

    #[test]
    fn fails_on_bytes_that_are_not_utf8() {
        // FF FF
        assert_eq!(crack("诚信平等诚信平等诚信平等诚信平等"), None);
        // The first three bytes of 😀
        assert_eq!(crack("诚信平等富强敬业诚信平等敬业爱国"), None);
    }

    #[test]
    fn fails_on_control_characters() {
        // 01 23 is `\x01#`
        assert_eq!(crack("富强民主文明和谐"), None);
        // `hello` followed by NUL
        assert_eq!(crack(&encode("hello\0", 10)), None);
        // DEL, and U+0085 NEXT LINE (a C1 control character) after `hi`
        assert_eq!(crack(&encode("hi\x7F", 10)), None);
        assert_eq!(crack(&encode("hi\u{85}", 10)), None);
    }

    #[test]
    fn keeps_tabs_and_line_breaks() {
        assert_eq!(
            crack(&encode("Hi\nHi\r\n\t!", 11)).unwrap(),
            "Hi\nHi\r\n\t!"
        );
    }

    #[test]
    fn fails_on_only_whitespace() {
        assert_eq!(crack(&encode("   ", 10)), None);
        assert_eq!(crack(&encode("\n\n", 10)), None);
    }

    #[test]
    fn fails_on_other_separators() {
        // Full-width and ideographic spaces, commas and slashes aren't skipped
        assert_eq!(crack(&HELLO_WORLD_TEN.replace("公正", "，公正")), None);
        assert_eq!(
            crack(&HELLO_WORLD_TEN.replace("公正", "\u{3000}公正")),
            None
        );
        assert_eq!(crack(&HELLO_WORLD_TEN.replace("公正", "/公正")), None);
        assert_eq!(
            crack("富强、民主、文明、和谐、自由、平等、公正、法治、爱国、敬业、诚信、友善"),
            None
        );
    }

    #[test]
    fn fails_on_chinese_prose() {
        // A real phrase made of two values, too short to be a message
        assert_eq!(crack("自由民主"), None);
        // Prose that uses the values
        assert_eq!(crack("倡导富强、民主、文明、和谐"), None);
        assert_eq!(crack("富强民主文明和谐是国家层面的价值目标"), None);
        assert_eq!(crack("你好，世界"), None);
    }

    #[test]
    fn fails_on_other_encodings() {
        // Standard Galactic Alphabet
        assert_eq!(crack("⍑ᒷꖎꖎ𝙹 ∴𝙹∷ꖎ↸"), None);
        // Braille
        assert_eq!(crack("⠓⠑⠇⠇⠕⠀⠺⠕⠗⠇⠙"), None);
        // Base100
        assert_eq!(crack("👟👜👣👣👦🐗👮👦👩👣👛"), None);
        // Base65536, whose alphabet has Han characters
        assert_eq!(crack("𒅓鹨𖡮𒀠啦ꍢ顡啫𓍱𓁡𠁴唬𓍪鱤啥𖥭𔐠𔕯ᔮ"), None);
        // Base64 of the issue's example
        assert_eq!(
            crack("5YWs5q2j54ix5Zu95YWs5q2j5bmz562J5YWs5q2j5Y+L5ZaE"),
            None
        );
    }

    #[test]
    fn fails_on_the_bench_miss_input() {
        assert_eq!(
            crack("T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV"),
            None
        );
    }

    #[test]
    fn handles_panic_if_empty_string() {
        assert_eq!(crack(""), None);
    }

    #[test]
    fn handles_panic_if_whitespace() {
        assert_eq!(crack("   "), None);
        assert_eq!(crack(" \t\r\n "), None);
    }

    #[test]
    fn handles_panic_if_emoji() {
        assert_eq!(crack("😀"), None);
        assert_eq!(crack("😂😂😂😂😂😂😂😂"), None);
    }

    #[test]
    fn fails_on_english() {
        assert_eq!(crack("hello world"), None);
        assert_eq!(crack("hello my name is panicky mc panic face!"), None);
    }

    #[test]
    fn is_registered() {
        // Exactly one decoder by that name runs in the search
        let decoders = get_decoder_by_name("Core Socialist Values");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Core Socialist Values");
        // Cached results name the decoder; reading them back looks it up here
        let decoder = DECODER_MAP
            .get("Core Socialist Values")
            .expect("Core Socialist Values should be in DECODER_MAP")
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "Core Socialist Values");
    }
}
