//! Decode text written as decimal character codes, such as `104 101 108 108 111` for `hello`.
//! Performs error handling and returns a string
//! Call decimal_decoder.crack to use. It returns a `CrackResult` whose `unencrypted_text` is
//! `None` when the input isn't decimal.
//!
//! Two forms are decoded:
//! * Bytes: every number is 0–255 and the bytes are UTF-8, or Latin-1 when they aren't valid
//!   UTF-8. This is CyberChef's `From Decimal`, dCode's "ASCII code" and Python's
//!   `list(b"...")`.
//! * Char codes: some number is above 255. Numbers are UTF-16 code units, with surrogate pairs
//!   joined, or code points, as with JavaScript's `String.fromCharCode(...)` and CyberChef's
//!   `From Charcode` in base 10.
//!
//! The numbers are separated by runs of whitespace, `,`, `;`, `:` or `-`. A
//! `String.fromCharCode(...)` or `[...]` wrapper is removed first. A single run of digits
//! with no separators is read as zero-padded 3-digit bytes, so `104105033` is `hi!`.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::{bytes_to_string, check_string_success};

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The Decimal decoder, call:
/// `let decimal_decoder = Decoder::<DecimalDecoder>::new()` to create a new instance
/// And then call:
/// `result = decimal_decoder.crack(input)` to decode a decimal string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::decimal_decoder::DecimalDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_decimal = Decoder::<DecimalDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_decimal
///     .crack("104 101 108 108 111 32 119 111 114 108 100", &checker)
///     .unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hello world");
///
/// // JavaScript's String.fromCharCode(...) form
/// let result = decode_decimal
///     .crack("String.fromCharCode(104,101,108,108,111,32,119,111,114,108,100)", &checker)
///     .unencrypted_text;
/// assert_eq!(result.unwrap()[0], "hello world");
/// ```
pub struct DecimalDecoder;

/// Numbers longer than this aren't character codes. Seven digits hold every code point
/// (U+10FFFF is 1114111) and leave room for leading zeros like `072`.
const MAX_DIGITS: usize = 7;

/// Fewer numbers than this are too likely to be something else, like a score (`3-1`) or a
/// time (`12:30`).
const MIN_CODES: usize = 3;

impl Crack for Decoder<DecimalDecoder> {
    fn new() -> Decoder<DecimalDecoder> {
        Decoder {
            name: "Decimal",
            description: "Decimal encoding writes each character as its character code in base 10, for example 104 101 108 108 111 for \"hello\". When every number is 255 or less they are read as the bytes of UTF-8 text; otherwise they are read as Unicode character codes, as with JavaScript's String.fromCharCode.",
            link: "https://www.dcode.fr/ascii-code",
            tags: vec!["decimal", "charcode", "base", "decoder"],
            popularity: 0.6,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes `text` as decimal character codes and checks the result with `checker`.
    /// `unencrypted_text` is `None` when `text` isn't decimal.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Decimal with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_decimal(text) else {
            debug!("Failed to decode Decimal because the text isn't decimal character codes");
            return results;
        };
        trace!("Decoded text for Decimal: {:?}", decoded_text);

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Decimal because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Decodes decimal character codes to text, or returns `None` if `text` isn't decimal.
fn decode_decimal(text: &str) -> Option<String> {
    let body = strip_wrapper(text.trim()).as_bytes();
    // A single scan that rejects almost every input before anything is allocated
    if !body
        .iter()
        .all(|&byte| byte.is_ascii_digit() || is_separator(byte))
    {
        return None;
    }

    let numbers: Vec<&[u8]> = body
        .split(|&byte| is_separator(byte))
        .filter(|number| !number.is_empty())
        .collect();
    let codes: Vec<u32> = match numbers.as_slice() {
        // No separators at all: zero-padded 3-digit bytes, such as `104101108`
        [digits] => {
            if digits.len() < 3 * MIN_CODES || digits.len() % 3 != 0 {
                return None;
            }
            let codes: Vec<u32> = digits.chunks(3).map(parse_digits).collect();
            if codes.iter().any(|&code| code > 255) {
                return None;
            }
            codes
        }
        numbers => {
            if numbers.len() < MIN_CODES || numbers.iter().any(|n| n.len() > MAX_DIGITS) {
                return None;
            }
            numbers.iter().map(|number| parse_digits(number)).collect()
        }
    };

    let decoded = match codes
        .iter()
        .map(|&code| u8::try_from(code))
        .collect::<Result<Vec<u8>, _>>()
    {
        Ok(bytes) => bytes_to_string(bytes),
        Err(_) => decode_char_codes(&codes)?,
    };

    // Control characters mean the numbers are something else: A1Z26 `8 5 12 12 15` decodes
    // to backspace, enquiry, form feed..., and octal `150 145 154` to C1 control characters.
    if decoded
        .chars()
        .any(|c| c.is_control() && !matches!(c, '\t' | '\n' | '\r'))
    {
        return None;
    }
    // Only tabs and line breaks, from numbers like `9 10 13`, isn't text either
    if decoded.trim().is_empty() {
        return None;
    }
    Some(decoded)
}

/// Whether `byte` can separate two numbers. These are A1Z26's separators, and cover every
/// delimiter CyberChef's `To Decimal` and `To Charcode` can write.
fn is_separator(byte: u8) -> bool {
    byte.is_ascii_whitespace() || matches!(byte, b',' | b';' | b':' | b'-')
}

/// Removes a JavaScript `String.fromCharCode(...)` wrapper, with or without a trailing `;`,
/// or the `[...]` that Python's `list(b"...")` and JSON arrays print.
fn strip_wrapper(text: &str) -> &str {
    if let Some(inner) = text.strip_prefix("String.fromCharCode(") {
        let inner = inner.strip_suffix(';').unwrap_or(inner).trim_end();
        return inner.strip_suffix(')').unwrap_or(text);
    }
    text.strip_prefix('[')
        .and_then(|inner| inner.strip_suffix(']'))
        .unwrap_or(text)
}

/// Parses ASCII digits. Callers pass at most `MAX_DIGITS` digits, so this can't overflow.
fn parse_digits(digits: &[u8]) -> u32 {
    digits
        .iter()
        .fold(0, |value, &digit| value * 10 + u32::from(digit - b'0'))
}

/// Decodes numbers as UTF-16 code units, joining surrogate pairs, or as code points, the way
/// JavaScript's `String.fromCharCode` and CyberChef's `From Charcode` do.
///
/// Returns `None` for a lone surrogate, a number above U+10FFFF, or when fewer than half the
/// numbers are printable ASCII (32–126). Text is mostly printable ASCII; years
/// (`1999 2000 2001`), phone numbers (`555-123-4567`) and 7-bit binary (`1101000 1100101`)
/// aren't.
fn decode_char_codes(codes: &[u32]) -> Option<String> {
    let printable = codes
        .iter()
        .filter(|code| (32..=126).contains(*code))
        .count();
    if printable * 2 < codes.len() {
        return None;
    }

    let mut decoded = String::with_capacity(codes.len());
    let mut codes = codes.iter().copied();
    while let Some(code) = codes.next() {
        let character = if (0xD800..=0xDBFF).contains(&code) {
            let low = codes.next().filter(|low| (0xDC00..=0xDFFF).contains(low))?;
            char::from_u32(0x10000 + ((code - 0xD800) << 10) + (low - 0xDC00))?
        } else {
            // None for a lone low surrogate or anything above U+10FFFF
            char::from_u32(code)?
        };
        decoded.push(character);
    }
    Some(decoded)
}

#[cfg(test)]
mod tests {
    use super::{decode_decimal, DecimalDecoder};
    use crate::checkers::athena::Athena;
    use crate::checkers::checker_type::{Check, Checker};
    use crate::checkers::CheckerTypes;
    use crate::decoders::a1z26_decoder::A1Z26Decoder;
    use crate::decoders::interface::{Crack, Decoder};
    use crate::decoders::{DecoderType, DECODER_MAP};
    use crate::filtration_system::get_decoder_by_name;

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    // Runs the decoder with the Athena checker and returns the decoded text, if any
    fn crack(text: &str) -> Option<String> {
        let decoder = Decoder::<DecimalDecoder>::new();
        let result = decoder.crack(text, &get_athena_checker());
        if result.unencrypted_text.is_none() {
            assert!(!result.success, "{text:?} failed but was marked successful");
        }
        result.unencrypted_text.map(|texts| texts[0].clone())
    }

    // The vectors from the issue plan were checked with CyberChef 11.5 (`To Decimal` /
    // `From Decimal`, `To Charcode` / `From Charcode` in base 10) when the plan was written.
    // Every vector here was checked with Python 3 (`' '.join(str(b) for b in text.encode())`,
    // `list(b"...")`, `bytes(...).decode()`, `chr`) and the char-code ones with Node's
    // `String.fromCharCode` / `String.fromCodePoint`.

    #[test]
    fn decodes_the_issue_example() {
        // https://github.com/bee-san/Ciphey/issues/951
        let decoder = Decoder::<DecimalDecoder>::new();
        let result = decoder.crack(
            "104 101 108 108 111 32 119 111 114 108 100",
            &get_athena_checker(),
        );
        assert!(result.success, "Athena should accept the plaintext");
        assert_eq!(result.unencrypted_text.unwrap()[0], "hello world");
    }

    #[test]
    fn decodes_string_from_char_code() {
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode
        let decoder = Decoder::<DecimalDecoder>::new();
        let result = decoder.crack(
            "String.fromCharCode(104,101,108,108,111,32,119,111,114,108,100)",
            &get_athena_checker(),
        );
        assert!(result.success, "Athena should accept the plaintext");
        assert_eq!(result.unencrypted_text.unwrap()[0], "hello world");
    }

    #[test]
    fn decodes_string_from_char_code_statement() {
        assert_eq!(
            crack("String.fromCharCode(104, 101, 108, 108, 111);").unwrap(),
            "hello"
        );
        assert_eq!(
            crack("String.fromCharCode(104, 101, 108, 108, 111) ;").unwrap(),
            "hello"
        );
    }

    #[test]
    fn decodes_comma_separated_codes() {
        assert_eq!(
            crack("72,101,108,108,111,44,32,87,111,114,108,100,33").unwrap(),
            "Hello, World!"
        );
    }

    #[test]
    fn decodes_python_byte_list() {
        // Python 3: list(b"hello")
        assert_eq!(crack("[104, 101, 108, 108, 111]").unwrap(), "hello");
    }

    #[test]
    fn decodes_zero_padded_codes_without_separators() {
        assert_eq!(
            crack("104101108108111032119111114108100").unwrap(),
            "hello world"
        );
    }

    #[test]
    fn decodes_utf8_split_across_numbers() {
        // "é" is the two UTF-8 bytes 195 169
        assert_eq!(
            crack("67 97 102 195 169 32 97 117 32 108 97 105 116").unwrap(),
            "Café au lait"
        );
    }

    #[test]
    fn decodes_latin1_bytes_that_are_not_utf8() {
        // "é" is 233 in Latin-1, which on its own isn't valid UTF-8
        assert_eq!(crack("67 97 102 233").unwrap(), "Café");
    }

    #[test]
    fn decodes_char_codes_above_255() {
        // String.fromCharCode(67,97,102,233,32,9749)
        assert_eq!(crack("67,97,102,233,32,9749").unwrap(), "Café ☕");
    }

    #[test]
    fn decodes_surrogate_pairs() {
        // "😀" is the UTF-16 surrogate pair 55357 56832 (0xD83D 0xDE00)
        assert_eq!(crack("55357,56832,32,104,105").unwrap(), "😀 hi");
    }

    #[test]
    fn decodes_code_points_above_ffff() {
        // 128512 is U+1F600, "😀", written as one code point instead of a surrogate pair
        assert_eq!(crack("128512 32 104 105").unwrap(), "😀 hi");
    }

    #[test]
    fn decodes_pangram() {
        // CyberChef: To Decimal (Space) of "The quick brown fox jumps over the lazy dog"
        assert_eq!(
            crack("84 104 101 32 113 117 105 99 107 32 98 114 111 119 110 32 102 111 120 32 106 117 109 112 115 32 111 118 101 114 32 116 104 101 32 108 97 122 121 32 100 111 103").unwrap(),
            "The quick brown fox jumps over the lazy dog"
        );
    }

    #[test]
    fn decodes_mixed_separators_and_crlf() {
        assert_eq!(
            crack(",72;101:108-108 111\r\n32\t119\n111  114,,108;100\r\n").unwrap(),
            "Hello world"
        );
    }

    #[test]
    fn decodes_leading_zeros() {
        assert_eq!(crack("072 101 108 108 111").unwrap(), "Hello");
        assert_eq!(crack("0000072 0101 121").unwrap(), "Hey");
    }

    #[test]
    fn keeps_tabs_and_line_breaks() {
        assert_eq!(
            crack("72 105 10 72 105 13 10 9 33").unwrap(),
            "Hi\nHi\r\n\t!"
        );
    }

    #[test]
    fn decode_decimal_returns_the_text() {
        assert_eq!(decode_decimal("104 105 33").as_deref(), Some("hi!"));
    }

    #[test]
    fn fails_on_a1z26() {
        // Every number is 1-26, so A1Z26 decodes it and Decimal must not
        let text = "8 5 12 12 15";
        assert_eq!(crack(text), None);
        let a1z26 = Decoder::<A1Z26Decoder>::new();
        let result = a1z26.crack(text, &get_athena_checker());
        assert_eq!(result.unencrypted_text.unwrap()[0], "HELLO");
    }

    #[test]
    fn fails_on_octal() {
        // "hello world" in octal; as decimal bytes these are C1 control characters
        assert_eq!(crack("150 145 154 154 157 40 167 157 162 154 144"), None);
    }

    #[test]
    fn fails_on_numbers_that_are_not_text() {
        assert_eq!(crack("555-123-4567"), None);
        assert_eq!(crack("1999 2000 2001"), None);
        assert_eq!(crack("2023-10-01"), None);
        assert_eq!(crack("12:30:45"), None);
        assert_eq!(crack("4111 1111 1111 1111"), None);
        // 7-bit binary "hello"
        assert_eq!(crack("1101000 1100101 1101100 1101100 1101111"), None);
    }

    #[test]
    fn fails_on_all_zeros() {
        assert_eq!(crack("0 0 0"), None);
        assert_eq!(crack("000000000"), None);
    }

    #[test]
    fn fails_on_control_characters() {
        assert_eq!(crack("104 101 0 108 108 111"), None);
        // U+0085 NEXT LINE, a C1 control character, as UTF-8
        assert_eq!(crack("104 194 133 105"), None);
    }

    #[test]
    fn fails_on_only_whitespace_output() {
        assert_eq!(crack("32 32 32"), None);
        assert_eq!(crack("9 10 13"), None);
    }

    #[test]
    fn fails_above_the_last_code_point() {
        // 1114112 is 0x110000, one past U+10FFFF
        assert_eq!(crack("1114112 65 66"), None);
    }

    #[test]
    fn fails_on_lone_surrogates() {
        // High surrogate followed by a letter
        assert_eq!(crack("55357 65 66"), None);
        // High surrogate at the end
        assert_eq!(crack("65 66 55357"), None);
        // Low surrogate on its own
        assert_eq!(crack("56832 65 66"), None);
    }

    #[test]
    fn fails_on_numbers_of_eight_or_more_digits() {
        assert_eq!(crack("104 101 10800000"), None);
        assert_eq!(
            crack("104 101 1234567890123456789012345678901234567890"),
            None
        );
    }

    #[test]
    fn fails_with_fewer_than_three_numbers() {
        assert_eq!(crack("104"), None);
        assert_eq!(crack("104 105"), None);
        assert_eq!(crack("String.fromCharCode(104,105)"), None);
    }

    #[test]
    fn fails_on_bad_runs_of_digits_without_separators() {
        // Not a multiple of 3
        assert_eq!(crack("1041011081"), None);
        // Fewer than three bytes
        assert_eq!(crack("104105"), None);
        // 999 isn't a byte
        assert_eq!(crack("104101999"), None);
    }

    #[test]
    fn fails_on_other_characters() {
        assert_eq!(crack("104.101.108"), None);
        assert_eq!(crack("104 101 108 x"), None);
        assert_eq!(crack("0x68 0x65 0x6c"), None);
        assert_eq!(crack("&#104;&#101;&#108;"), None);
        assert_eq!(crack("104 101 108\u{a0}108"), None);
    }

    #[test]
    fn fails_on_unclosed_wrappers() {
        assert_eq!(crack("String.fromCharCode(104,101,108"), None);
        assert_eq!(crack("[104, 101, 108"), None);
        assert_eq!(crack("104, 101, 108]"), None);
    }

    #[test]
    fn fails_on_separators_only() {
        assert_eq!(crack(" \t-:,;\n \r\n "), None);
        assert_eq!(crack("[]"), None);
        assert_eq!(crack("String.fromCharCode()"), None);
    }

    #[test]
    fn handles_panic_if_empty_string() {
        assert_eq!(crack(""), None);
    }

    #[test]
    fn handles_panic_if_whitespace() {
        assert_eq!(crack("   "), None);
    }

    #[test]
    fn handles_panic_if_emoji() {
        assert_eq!(crack("😀"), None);
    }

    #[test]
    fn fails_on_english() {
        assert_eq!(crack("hello world"), None);
        assert_eq!(crack("hello my name is panicky mc panic face!"), None);
    }

    #[test]
    fn is_registered() {
        // Exactly one decoder by that name runs in the search
        let decoders = get_decoder_by_name("Decimal");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Decimal");
        // Cached results name the decoder; reading them back looks it up here
        let decoder = DECODER_MAP
            .get("Decimal")
            .expect("Decimal should be in DECODER_MAP")
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "Decimal");
    }
}
