//! Decode DNA and RNA codons: triplets of nucleotides translated to one-letter amino-acid
//! codes with the standard genetic code (NCBI translation table 1).
//!
//! The 64 codons stand for the 20 letters `A C D E F G H I K L M N P Q R S T V W Y`
//! (there is no `B J O U X Z`) and for the three stop codons `TAA`, `TAG` and `TGA`:
//! `TGC ATA CCA` is `CIP`. The rules:
//!
//! * Codons can be separated by ASCII whitespace or `, ; : -`, or written as one run.
//!   The separators are skipped, so only the number of nucleotides matters.
//! * `U` is read as `T`, so RNA decodes the same as DNA, and the case doesn't matter.
//!   The ambiguity codes (`N`, `R`, `Y`, ...) are not accepted.
//! * A stop codon becomes a space. Puzzles use stops as word breaks; biology writes `*`
//!   and Python Ciphey wrote `.`, but `CIPHEY IS FAST` reads as English where
//!   `CIPHEY.IS.FAST` and `CIPHEYISFAST` don't. Runs of stops make one space, and stops at
//!   the start or the end are dropped.
//! * At least three codons, and a whole number of them.
//!
//! The 2-bit encoding that packs four nucleotides into a byte (`CGGA` is `h`) is a
//! different code with its own decoder, see
//! <https://github.com/bee-san/Ciphey/issues/967>.
//!
//! References: <https://en.wikipedia.org/wiki/DNA_and_RNA_codon_tables> (the standard
//! table), <https://www.dcode.fr/codons-genetic-code> and the NCBI's translation table 1,
//! <https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi#SG1>.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, trace};

/// The fewest nucleotides worth decoding: three codons. One or two amino-acid letters
/// aren't a message, and short words like `GATTACA` are made of the same letters.
const MIN_NUCLEOTIDES: usize = 9;

/// Stands for a stop codon in [`AMINO_ACIDS`].
const STOP: u8 = b'*';

/// The standard genetic code in the classic `TCAG` layout. Each nucleotide is two bits,
/// `T` = 0, `C` = 1, `A` = 2 and `G` = 3, and a codon is indexed by
/// 16 × first + 4 × second + third: `TTT` (0) is `F`, `ATG` (35) is `M`, `GGG` (63) is `G`.
const AMINO_ACIDS: &[u8; 64] = b"FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG";

/// The DNA Codon decoder, call:
/// `let dna_codon_decoder = Decoder::<DnaCodonDecoder>::new()` to create a new instance
/// And then call:
/// `result = dna_codon_decoder.crack(input)` to decode DNA or RNA codons
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::dna_codon_decoder::DnaCodonDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_dna_codon = Decoder::<DnaCodonDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // The stop codon TAA is a space
/// let result = decode_dna_codon.crack(
///     "ATG GAA GAA ACA TAA ATG GAA TAA GCA ACA TAA GAC GCA TGG AAC",
///     &checker,
/// );
/// assert!(result.success);
/// assert_eq!(result.unencrypted_text.unwrap()[0], "MEET ME AT DAWN");
///
/// // RNA (U for T), unspaced, decodes the same
/// let result = decode_dna_codon.crack("AUGGAAGAAACAUAAAUGGAAUAAGCAACAUAAGACGCAUGGAAC", &checker);
/// assert_eq!(result.unencrypted_text.unwrap()[0], "MEET ME AT DAWN");
/// ```
pub struct DnaCodonDecoder;

impl Crack for Decoder<DnaCodonDecoder> {
    fn new() -> Decoder<DnaCodonDecoder> {
        Decoder {
            name: "DNA Codon",
            description: "DNA/RNA codons (ACGT/ACGU triplets) translated to one-letter amino-acid codes with the standard genetic code; stop codons become spaces. Cannot represent B, J, O, U, X, Z or digits.",
            link: "https://en.wikipedia.org/wiki/DNA_and_RNA_codon_tables",
            tags: vec!["dna", "codon", "genetic", "decoder"],
            popularity: 0.3,
            phantom: std::marker::PhantomData,
        }
    }

    /// Translates the codons and checks the result: one candidate, one checker call.
    /// Input that isn't codons fails in [`translate`], usually on its first bytes.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying DNA Codon with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = translate(text) else {
            debug!("Failed to decode DNA Codon: the input isn't at least three whole codons, or is only stop codons");
            return results;
        };

        if !check_string_success(&decoded_text, text) {
            debug!(
                "Failed to decode DNA Codon because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }
    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// The pre-check and the translation in one pass over the bytes: the amino acids of
/// `text`, stop codons as single spaces, or `None` if `text` isn't codons.
///
/// It stops at the first byte that isn't a nucleotide or a separator, so ordinary text
/// fails on its first other letter and most encodings on their first digit or symbol.
/// Then the nucleotides must make at least [`MIN_NUCLEOTIDES`] and a whole number of
/// codons, and at least one codon must not be a stop. The output string is the only
/// allocation, and it is only made once a whole codon has been read.
fn translate(text: &str) -> Option<String> {
    let mut protein = String::new();
    // The codon being read, two bits per nucleotide, and the nucleotides read so far
    let mut codon = 0;
    let mut nucleotides = 0;
    for &byte in text.as_bytes() {
        let nucleotide = match byte {
            b'T' | b't' | b'U' | b'u' => 0,
            b'C' | b'c' => 1,
            b'A' | b'a' => 2,
            b'G' | b'g' => 3,
            b',' | b';' | b':' | b'-' => continue,
            byte if byte.is_ascii_whitespace() => continue,
            _ => return None,
        };
        codon = (codon << 2) | nucleotide;
        nucleotides += 1;
        if nucleotides % 3 != 0 {
            continue;
        }
        if protein.capacity() == 0 {
            // One letter per codon at most, and a codon takes at least three bytes
            protein.reserve(text.len() / 3);
        }
        match AMINO_ACIDS[codon] {
            // A space between words: none at the start and none twice in a row
            STOP => {
                if !protein.is_empty() && !protein.ends_with(' ') {
                    protein.push(' ');
                }
            }
            amino_acid => protein.push(char::from(amino_acid)),
        }
        codon = 0;
    }
    if nucleotides % 3 != 0 || nucleotides < MIN_NUCLEOTIDES {
        return None;
    }
    // A trailing stop left a space; stops alone left nothing
    if protein.ends_with(' ') {
        protein.pop();
    }
    if protein.is_empty() {
        return None;
    }
    Some(protein)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::athena::Athena;
    use crate::checkers::checker_type::{Check, Checker};

    /// The Athena checker, as the search uses it
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    /// Runs the decoder with the Athena checker
    fn crack(text: &str) -> CrackResult {
        Decoder::<DnaCodonDecoder>::new().crack(text, &get_athena_checker())
    }

    /// Asserts `text` decodes to `plaintext`, whether or not Athena identifies it
    fn assert_decodes(text: &str, plaintext: &str) -> CrackResult {
        let result = crack(text);
        assert_eq!(
            result.unencrypted_text,
            Some(vec![plaintext.to_string()]),
            "{text:?}"
        );
        result
    }

    /// Asserts `text` decodes to `plaintext` and Athena identifies it as plaintext
    fn assert_cracks(text: &str, plaintext: &str) {
        let result = assert_decodes(text, plaintext);
        assert!(result.success, "{text:?} was not identified: {result:?}");
        assert!(!result.checker_name.is_empty());
    }

    // Every decoding below was computed with a Python prototype of the rules in the module
    // docs and cross-checked with Biopython 1.85, `Seq(...).translate()` with the standard
    // table (stops written `*`, here spaces). The encodings use the first codon of each
    // letter in alphabetical order, and `TAA` for a space.

    /// CIPHEYISFAST, the example in issue #966. It has no stop codons, so no spaces.
    const ISSUE_EXAMPLE: &str = "TGC ATA CCA CAC GAA TAC ATA AGC TTC GCA AGC ACA";
    /// MEET ME AT DAWN
    const MEET_ME_AT_DAWN: &str = "ATG GAA GAA ACA TAA ATG GAA TAA GCA ACA TAA GAC GCA TGG AAC";
    /// THIS IS A SECRET MESSAGE
    const SECRET_MESSAGE: &str = "ACA CAC ATA AGC TAA ATA AGC TAA GCA TAA AGC GAA TGC AGA GAA ACA TAA ATG GAA AGC AGC GCA GGA GAA";
    /// The bench `miss` string
    const MISS: &str =
        "T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV";

    #[test]
    fn decodes_issue_example() {
        // Athena doesn't identify CIPHEYISFAST, which has no word breaks, so only the
        // decoding is asserted
        assert_decodes(ISSUE_EXAMPLE, "CIPHEYISFAST");
    }

    #[test]
    fn decodes_rna() {
        assert_decodes(
            "UGC AUA CCA CAC GAA UAC AUA AGC UUC GCA AGC ACA",
            "CIPHEYISFAST",
        );
    }

    #[test]
    fn decodes_t_and_u_mixed() {
        // Both are read as T
        assert_decodes(
            "UGC ATA CCA CAC GAA TAC AUA AGC UUC GCA AGC ACA",
            "CIPHEYISFAST",
        );
    }

    #[test]
    fn decodes_lowercase_and_mixed_case() {
        assert_decodes(
            "tgc ata cca cac gaa tac ata agc ttc gca agc aca",
            "CIPHEYISFAST",
        );
        assert_decodes(
            "Tgc aTa ccA CAC gaa tAC ata AGC ttc Gca agc aCa",
            "CIPHEYISFAST",
        );
    }

    #[test]
    fn decodes_unspaced_run() {
        assert_decodes("TGCATACCACACGAATACATAAGCTTCGCAAGCACA", "CIPHEYISFAST");
    }

    #[test]
    fn decodes_other_separators() {
        for text in [
            "TGC,ATA,CCA,CAC,GAA,TAC,ATA,AGC,TTC,GCA,AGC,ACA",
            "TGC, ATA, CCA, CAC, GAA, TAC, ATA, AGC, TTC, GCA, AGC, ACA",
            "TGC;ATA;CCA;CAC;GAA;TAC;ATA;AGC;TTC;GCA;AGC;ACA",
            "TGC:ATA:CCA:CAC:GAA:TAC:ATA:AGC:TTC:GCA:AGC:ACA",
            "TGC-ATA-CCA-CAC-GAA-TAC-ATA-AGC-TTC-GCA-AGC-ACA",
            "TGC ATA CCA\nCAC GAA TAC\r\nATA AGC TTC\n\tGCA AGC ACA\n",
            "  TGC  ATA  CCA  CAC  GAA  TAC  ATA  AGC  TTC  GCA  AGC  ACA  ",
        ] {
            assert_decodes(text, "CIPHEYISFAST");
        }
    }

    #[test]
    fn stop_codons_are_spaces() {
        assert_cracks(
            "TGC ATA CCA CAC GAA TAC TAA ATA AGC TAA TTC GCA AGC ACA",
            "CIPHEY IS FAST",
        );
    }

    #[test]
    fn all_three_stop_codons_are_spaces() {
        // TAA, TAG and TGA (UAA, UAG and UGA in RNA)
        assert_decodes("ATG GAA TAA ATG GAA TAG ATG GAA TGA ATG GAA", "ME ME ME ME");
        assert_decodes("AUG GAA UAA AUG GAA UAG AUG GAA UGA AUG GAA", "ME ME ME ME");
    }

    #[test]
    fn leading_trailing_and_repeated_stops_are_trimmed_and_collapsed() {
        assert_decodes(
            "TAA TAG ATG GAA GAA ACA TAA TGA TAA ATG GAA TAA TAA",
            "MEET ME",
        );
    }

    #[test]
    fn decodes_meet_me_at_dawn() {
        assert_cracks(MEET_ME_AT_DAWN, "MEET ME AT DAWN");
    }

    #[test]
    fn decodes_attack_at_dawn() {
        assert_cracks(
            "GCA ACA ACA GCA TGC AAA TAA GCA ACA TAA GAC GCA TGG AAC",
            "ATTACK AT DAWN",
        );
    }

    #[test]
    fn decodes_secret_message() {
        assert_cracks(SECRET_MESSAGE, "THIS IS A SECRET MESSAGE");
    }

    #[test]
    fn decodes_rna_secret_message() {
        assert_cracks(
            &SECRET_MESSAGE.replace('T', "U"),
            "THIS IS A SECRET MESSAGE",
        );
    }

    #[test]
    fn real_gene_decodes_to_protein() {
        // The example open reading frame on Wikipedia's codon table page, start codon to
        // stop codon. The TGA in the middle and the closing TAG are stops. Athena doesn't
        // identify the protein, so only the decoding is asserted.
        assert_decodes("ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG", "MAIVMGR KGAR");
    }

    #[test]
    fn four_nucleotide_groups_pass_but_are_not_plaintext() {
        // A #967-style input (2-bit nucleotides, four per byte) of 12 nucleotides is four
        // codons, ACG TAC GTA CGT. Harmless: Athena rejects TYVR.
        let result = assert_decodes("ACGT ACGT ACGT", "TYVR");
        assert!(!result.success, "{result:?}");
    }

    #[test]
    fn rejects_input_that_is_not_codons() {
        for text in [
            "",
            " , ; : - \n\t ",
            "😀",
            "hello world",
            MISS,
            // Fewer than three codons
            "TGC ATA",
            "GATTACA",
            // Not a whole number of codons: 8 and 10 nucleotides. CGGACGGC is #967's
            // example, 2-bit nucleotides for `hh`.
            "TGC ATA CC",
            "CGGACGGC",
            "TGC ATA CCA C",
            // IUPAC ambiguity codes and other letters
            "ACGN ACG",
            "ACG RAC GTA",
            "ACG YAC GTA",
            "ACG TAC GTX",
            // Digits, other separators, non-ASCII whitespace
            "ACG TAC GT1",
            "ACG.TAC.GTA",
            "ACG/TAC/GTA",
            "ACG TAC\u{a0}GTA",
        ] {
            assert!(translate(text).is_none(), "{text:?} passed the pre-check");
            let result = crack(text);
            assert!(!result.success, "{text:?}: {result:?}");
            assert!(result.unencrypted_text.is_none(), "{text:?}: {result:?}");
        }
    }

    #[test]
    fn rejects_only_stop_codons() {
        for text in ["TAA TAA TAA", "TAA TAG TGA", "UAA UAG UGA UAA"] {
            assert!(translate(text).is_none(), "{text:?}");
            let result = crack(text);
            assert!(!result.success, "{text:?}: {result:?}");
            assert!(result.unencrypted_text.is_none(), "{text:?}: {result:?}");
        }
    }

    #[test]
    fn miss_input_is_rejected_in_its_first_bytes() {
        // The bench `miss` string starts with T, a nucleotide. The 0 after it is the first
        // byte that isn't one, and translate returns there, before allocating anything.
        assert_eq!(MISS.as_bytes()[1], b'0');
        assert!(translate(MISS).is_none());
    }

    /// The index of a codon in `AMINO_ACIDS`
    fn codon_index(codon: &str) -> usize {
        codon.bytes().fold(0, |index, nucleotide| {
            let bits = match nucleotide {
                b'T' => 0,
                b'C' => 1,
                b'A' => 2,
                b'G' => 3,
                _ => panic!("not a nucleotide: {codon}"),
            };
            index * 4 + bits
        })
    }

    #[test]
    fn table_is_the_standard_genetic_code() {
        // Wikipedia's inverse table (amino acid to codons) for the standard code, an
        // independent check of the TCAG-ordered string
        let inverse: [(u8, &[&str]); 21] = [
            (b'A', &["GCT", "GCC", "GCA", "GCG"]),
            (b'R', &["CGT", "CGC", "CGA", "CGG", "AGA", "AGG"]),
            (b'N', &["AAT", "AAC"]),
            (b'D', &["GAT", "GAC"]),
            (b'C', &["TGT", "TGC"]),
            (b'Q', &["CAA", "CAG"]),
            (b'E', &["GAA", "GAG"]),
            (b'G', &["GGT", "GGC", "GGA", "GGG"]),
            (b'H', &["CAT", "CAC"]),
            (b'I', &["ATT", "ATC", "ATA"]),
            (b'L', &["CTT", "CTC", "CTA", "CTG", "TTA", "TTG"]),
            (b'K', &["AAA", "AAG"]),
            (b'M', &["ATG"]),
            (b'F', &["TTT", "TTC"]),
            (b'P', &["CCT", "CCC", "CCA", "CCG"]),
            (b'S', &["TCT", "TCC", "TCA", "TCG", "AGT", "AGC"]),
            (b'T', &["ACT", "ACC", "ACA", "ACG"]),
            (b'W', &["TGG"]),
            (b'Y', &["TAT", "TAC"]),
            (b'V', &["GTT", "GTC", "GTA", "GTG"]),
            (STOP, &["TAA", "TAG", "TGA"]),
        ];
        let mut listed = [false; 64];
        for (amino_acid, codons) in inverse {
            for codon in codons {
                let index = codon_index(codon);
                assert_eq!(
                    char::from(AMINO_ACIDS[index]),
                    char::from(amino_acid),
                    "{codon}"
                );
                assert!(!listed[index], "{codon} is listed twice");
                listed[index] = true;
            }
        }
        assert!(listed.iter().all(|&is_listed| is_listed));
    }

    #[test]
    fn table_cannot_write_these_letters() {
        for letter in *b"BJOUXZ0123456789" {
            assert!(!AMINO_ACIDS.contains(&letter), "{}", char::from(letter));
        }
    }

    #[test]
    fn is_registered() {
        let decoders = crate::filtration_system::get_decoder_by_name("DNA Codon");
        assert_eq!(decoders.components.len(), 1);
        assert!(crate::decoders::DECODER_MAP.contains_key("DNA Codon"));
    }
}
