//! Decode DTMF (touch-tone) frequency pairs, such as `852-1336` for the telephone key `8`.
//! Performs error handling and returns a string
//! Call dtmf_decoder.crack to use. It returns a `CrackResult` whose `unencrypted_text` is
//! `None` when the input isn't DTMF.
//!
//! DTMF plays each key as two tones at once: one from the low group (697, 770, 852 or 941 Hz,
//! the keypad row) and one from the high group (1209, 1336, 1477 or 1633 Hz, the column).
//!
//! ```text
//!          1209  1336  1477  1633
//!    697     1     2     3     A
//!    770     4     5     6     B
//!    852     7     8     9     C
//!    941     *     0     #     D
//! ```
//!
//! The two frequencies of a key can come in either order (dCode writes the high one first)
//! and are separated by whitespace, `-`, `/`, `+`, `,`, `;`, `:` or `|`, with or without
//! `Hz` after each one. They can also be glued together, 7 digits per key (`8521336`), the
//! form Python Ciphey decoded. The output is the keys `0`-`9`, `*`, `#` and `A`-`D`.
//!
//! A line break, a `|` or two or more whitespace characters between two keys is a word gap
//! and becomes a space, so the keys of each word stay together for decoders that read
//! them next, such as Multi-tap.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The DTMF decoder, call:
/// `let dtmf_decoder = Decoder::<DtmfDecoder>::new()` to create a new instance
/// And then call:
/// `result = dtmf_decoder.crack(input)` to decode DTMF frequency pairs
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::dtmf_decoder::DtmfDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_dtmf = Decoder::<DtmfDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_dtmf
///     .crack("852-1336 770-1477 852-1209 770-1336 697-1477 941-1336 852-1477", &checker)
///     .unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "8675309");
///
/// // The high frequency first, as dCode writes it
/// let result = decode_dtmf
///     .crack("1633-941/1633-852/1336-941/1633-941/1477-697", &checker)
///     .unencrypted_text;
/// assert_eq!(result.unwrap()[0], "DC0D3");
/// ```
pub struct DtmfDecoder;

/// The low-group frequencies in Hz, one per keypad row.
const LOW: [u32; 4] = [697, 770, 852, 941];

/// The high-group frequencies in Hz, one per keypad column.
const HIGH: [u32; 4] = [1209, 1336, 1477, 1633];

/// The key in each row (low frequency) and column (high frequency).
const KEYPAD: [[char; 4]; 4] = [
    ['1', '2', '3', 'A'],
    ['4', '5', '6', 'B'],
    ['7', '8', '9', 'C'],
    ['*', '0', '#', 'D'],
];

/// Digits per key when the two frequencies are written with nothing between them.
const GLUED_KEY_DIGITS: usize = 7;

/// Fewer keys than this aren't worth returning: the search drops results of 2 characters
/// or fewer.
const MIN_KEYS: usize = 3;

impl Crack for Decoder<DtmfDecoder> {
    fn new() -> Decoder<DtmfDecoder> {
        Decoder {
            name: "DTMF",
            description: "DTMF (touch-tone) writes each telephone key as a pair of frequencies, one of 697/770/852/941 Hz and one of 1209/1336/1477/1633 Hz, for example 852-1336 for 8. The output is the keys 0-9, *, # and A-D.",
            link: "https://en.wikipedia.org/wiki/Dual-tone_multi-frequency_signaling",
            tags: vec!["dtmf", "phone", "telephone", "substitution", "decoder"],
            popularity: 0.3,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes `text` as DTMF frequency pairs and checks the result with `checker`.
    /// `unencrypted_text` is `None` when `text` isn't DTMF.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying DTMF with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_dtmf(text) else {
            debug!("Failed to decode DTMF because the text isn't DTMF frequency pairs");
            return results;
        };
        trace!("Decoded text for DTMF: {:?}", decoded_text);

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode DTMF because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        // The keys are returned even when the checker doesn't identify them: a string of
        // digits is what decoders such as Multi-tap, T9 or A1Z26 read next.
        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// One of the two frequencies of a key.
#[derive(Clone, Copy)]
enum Tone {
    /// A low-group frequency, by keypad row
    Low(usize),
    /// A high-group frequency, by keypad column
    High(usize),
}

/// Decodes DTMF frequency pairs to keys, or returns `None` if `text` isn't DTMF.
///
/// This is a single pass over the bytes that fails at the first byte or number that can't
/// be DTMF, and allocates nothing before the first key is decoded.
fn decode_dtmf(text: &str) -> Option<String> {
    let bytes = text.trim().as_bytes();
    // DTMF starts with a frequency, so almost every other input fails here
    if !bytes.first()?.is_ascii_digit() {
        return None;
    }

    let mut keys = String::new();
    let mut key_count = 0;
    // The first frequency of a key whose second one hasn't been read yet, and whether a
    // word gap came before it
    let mut first_tone: Option<(Tone, bool)> = None;
    // Whether the separators before the current number are a word gap
    let mut gap = false;
    let mut i = 0;
    while i < bytes.len() {
        // A number. Each turn of the loop starts on a digit, so it has at least one.
        let start = i;
        while i < bytes.len() && bytes[i].is_ascii_digit() {
            i += 1;
        }
        let digits = &bytes[start..i];
        match digits.len() {
            3 | 4 => {
                let tone = tone(digits)?;
                match first_tone.take() {
                    None => first_tone = Some((tone, gap)),
                    Some((first, gap_before)) => {
                        push_key(&mut keys, key(first, tone)?, gap_before);
                        key_count += 1;
                    }
                }
            }
            length if length.is_multiple_of(GLUED_KEY_DIGITS) => {
                // A key can't be split between a lone frequency and glued digits
                if first_tone.is_some() {
                    return None;
                }
                for (index, glued) in digits.chunks(GLUED_KEY_DIGITS).enumerate() {
                    push_key(&mut keys, glued_key(glued)?, gap && index == 0);
                    key_count += 1;
                }
            }
            // Not a frequency: `8-5-12`, `104 101 108`, `555-1234`, `0697`
            _ => return None,
        }

        // The separators before the next number
        gap = false;
        let mut after_whitespace = false;
        while i < bytes.len() && !bytes[i].is_ascii_digit() {
            let byte = bytes[i];
            if !is_separator(byte) {
                return None;
            }
            let whitespace = byte.is_ascii_whitespace();
            gap |= matches!(byte, b'\n' | b'\r' | b'|') || (whitespace && after_whitespace);
            after_whitespace = whitespace;
            i += 1;
        }
    }

    // An odd number of frequencies, or too few keys to be worth returning
    if first_tone.is_some() || key_count < MIN_KEYS {
        return None;
    }
    Some(keys)
}

/// Whether `byte` can come between two frequencies: whitespace, punctuation, or a letter
/// of an `Hz` suffix.
fn is_separator(byte: u8) -> bool {
    byte.is_ascii_whitespace()
        || matches!(
            byte,
            b'-' | b'/' | b'+' | b',' | b';' | b':' | b'|' | b'H' | b'h' | b'z' | b'Z'
        )
}

/// The frequency that the ASCII digits in `digits` stand for: 3 digits for a low-group
/// one, 4 for a high-group one. A zero-padded number like `0697` isn't a frequency.
fn tone(digits: &[u8]) -> Option<Tone> {
    let position = |group: &[u32; 4]| {
        let value = digits
            .iter()
            .fold(0, |value, &digit| value * 10 + u32::from(digit - b'0'));
        group.iter().position(|&frequency| frequency == value)
    };
    match digits.len() {
        3 => position(&LOW).map(Tone::Low),
        4 => position(&HIGH).map(Tone::High),
        _ => None,
    }
}

/// The key for two frequencies in either order, or `None` unless one is from each group.
fn key(first: Tone, second: Tone) -> Option<char> {
    match (first, second) {
        (Tone::Low(row), Tone::High(column)) | (Tone::High(column), Tone::Low(row)) => {
            Some(KEYPAD[row][column])
        }
        _ => None,
    }
}

/// The key for 7 glued digits: a low frequency then a high one (`8521336`), or a high one
/// then a low one (`1336852`). At most one of them can match, because the low
/// frequencies start with 6 to 9 and the high ones with 1.
fn glued_key(digits: &[u8]) -> Option<char> {
    [3, 4].into_iter().find_map(|split| {
        let (first, second) = digits.split_at(split);
        key(tone(first)?, tone(second)?)
    })
}

/// Appends `key` to `keys`, after a space if a word gap came before it.
fn push_key(keys: &mut String, key: char, gap_before: bool) {
    if gap_before {
        keys.push(' ');
    }
    keys.push(key);
}

#[cfg(test)]
mod tests {
    use super::{decode_dtmf, DtmfDecoder, HIGH, KEYPAD, LOW};
    use crate::checkers::athena::Athena;
    use crate::checkers::checker_type::{Check, Checker};
    use crate::checkers::CheckerTypes;
    use crate::decoders::a1z26_decoder::A1Z26Decoder;
    use crate::decoders::big_integer_decoder::BigIntegerDecoder;
    use crate::decoders::decimal_decoder::DecimalDecoder;
    use crate::decoders::interface::{Crack, Decoder};
    use crate::decoders::octal_decoder::OctalDecoder;
    use crate::decoders::{DecoderType, DECODER_MAP};
    use crate::filtration_system::get_decoder_by_name;

    // The vectors from the issue plan (https://github.com/bee-san/Ciphey/issues/959) were
    // decoded with a Python 3 prototype written from the Wikipedia keypad table
    // (https://en.wikipedia.org/wiki/Dual-tone_multi-frequency_signaling), and every pair
    // was checked against the `cipheydists` table below. I re-ran that prototype on every
    // vector here. dCode (https://www.dcode.fr/dtmf-code) writes the high frequency first.

    /// `cipheydists/translate/dtmf.json`, the table Python Ciphey's DTMF decoder used:
    /// <https://github.com/Ciphey/CipheyDists/blob/master/cipheydists/translate/dtmf.json>
    const CIPHEYDISTS_TABLE: [(&str, char); 32] = [
        ("1209697", '1'),
        ("6971209", '1'),
        ("1336697", '2'),
        ("6971336", '2'),
        ("1477697", '3'),
        ("6971477", '3'),
        ("1633697", 'A'),
        ("6971633", 'A'),
        ("1209770", '4'),
        ("7701209", '4'),
        ("1336770", '5'),
        ("7701336", '5'),
        ("1477770", '6'),
        ("7701477", '6'),
        ("1633770", 'B'),
        ("7701633", 'B'),
        ("1209852", '7'),
        ("8521209", '7'),
        ("1336852", '8'),
        ("8521336", '8'),
        ("1477852", '9'),
        ("8521477", '9'),
        ("1633852", 'C'),
        ("8521633", 'C'),
        ("1209941", '*'),
        ("9411209", '*'),
        ("1336941", '0'),
        ("9411336", '0'),
        ("1477941", '#'),
        ("9411477", '#'),
        ("1633941", 'D'),
        ("9411633", 'D'),
    ];

    // The issue example: 8675309 as low-high pairs
    const ISSUE_EXAMPLE: &str = "852-1336 770-1477 852-1209 770-1336 697-1477 941-1336 852-1477";

    // The bench's `miss` input (benches/data/decoders.toml)
    const BENCH_MISS: &str =
        "T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV";

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    // Runs the decoder with the Athena checker and returns the decoded text, if any
    fn crack(text: &str) -> Option<String> {
        let decoder = Decoder::<DtmfDecoder>::new();
        let result = decoder.crack(text, &get_athena_checker());
        if result.unencrypted_text.is_none() {
            assert!(!result.success, "{text:?} failed but was marked successful");
        }
        result.unencrypted_text.map(|texts| texts[0].clone())
    }

    // Asserts that the decoder turns `text` into `expected` and that Athena accepts it
    fn assert_cracks(text: &str, expected: &str) {
        let decoder = Decoder::<DtmfDecoder>::new();
        let result = decoder.crack(text, &get_athena_checker());
        assert_eq!(
            result.unencrypted_text.as_deref(),
            Some(&[expected.to_string()][..]),
            "decoding {text:?}"
        );
        assert!(result.success, "Athena should accept {expected:?}");
    }

    #[test]
    fn decodes_the_issue_example() {
        // Athena takes 8675309 for a common password
        assert_cracks(ISSUE_EXAMPLE, "8675309");
    }

    #[test]
    fn decodes_high_low_order() {
        assert_cracks(
            "1336-852 1477-770 1209-852 1336-770 1477-697 1336-941 1477-852",
            "8675309",
        );
    }

    #[test]
    fn decodes_spaces_inside_pairs() {
        assert_cracks(
            "852 1336 770 1477 852 1209 770 1336 697 1477 941 1336 852 1477",
            "8675309",
        );
    }

    #[test]
    fn decodes_glued_frequencies() {
        // 7 digits per key, the form Python Ciphey decoded
        assert_cracks(
            "8521336770147785212097701336697147794113368521477",
            "8675309",
        );
        // High frequency first
        assert_cracks(
            "1336852147777012098521336770147769713369411477852",
            "8675309",
        );
    }

    #[test]
    fn decodes_hz_suffixes() {
        assert_cracks(
            "852Hz+1336Hz 770Hz+1477Hz 852Hz+1209Hz 770Hz+1336Hz 697Hz+1477Hz 941Hz+1336Hz 852Hz+1477Hz",
            "8675309",
        );
        assert_eq!(
            crack("697 hz 1209 HZ, 697 hZ 1336 Hz, 697 Hz 1477 hz").unwrap(),
            "123"
        );
    }

    #[test]
    fn decodes_a_phone_number() {
        // Athena takes 18005551234 for a phone number
        assert_cracks(
            "697-1209 852-1336 941-1336 941-1336 770-1336 770-1336 770-1336 697-1209 697-1336 697-1477 770-1209",
            "18005551234",
        );
    }

    #[test]
    fn decodes_dcode_example() {
        // dCode's own example, high frequency first and `/` between keys
        assert_eq!(
            crack("1633-941/1633-852/1336-941/1633-941/1477-697").unwrap(),
            "DC0D3"
        );
    }

    #[test]
    fn decodes_the_whole_keypad() {
        assert_eq!(
            crack("697-1209 697-1336 697-1477 697-1633 770-1209 770-1336 770-1477 770-1633 852-1209 852-1336 852-1477 852-1633 941-1209 941-1336 941-1477 941-1633").unwrap(),
            "123A456B789C*0#D"
        );
    }

    #[test]
    fn decodes_every_entry_of_the_cipheydists_table() {
        for (glued, expected) in CIPHEYDISTS_TABLE {
            let three_keys = expected.to_string().repeat(3);
            // Glued, as in the table
            assert_eq!(
                decode_dtmf(&[glued; 3].join(" ")).as_deref(),
                Some(three_keys.as_str()),
                "{glued}"
            );
            // Split into its two frequencies
            let split = if glued.starts_with('1') { 4 } else { 3 };
            let pair = format!("{}-{}", &glued[..split], &glued[split..]);
            assert_eq!(
                decode_dtmf(&[pair.as_str(); 3].join(" ")).as_deref(),
                Some(three_keys.as_str()),
                "{pair}"
            );
        }
    }

    #[test]
    fn cipheydists_table_is_the_keypad() {
        // Every key, in both orders, is in the table exactly once
        for (row, &low) in LOW.iter().enumerate() {
            for (column, &high) in HIGH.iter().enumerate() {
                let key = KEYPAD[row][column];
                for glued in [format!("{low}{high}"), format!("{high}{low}")] {
                    let matches: Vec<char> = CIPHEYDISTS_TABLE
                        .iter()
                        .filter(|(entry, _)| *entry == glued)
                        .map(|&(_, key)| key)
                        .collect();
                    assert_eq!(matches, [key], "{glued}");
                }
            }
        }
    }

    #[test]
    fn line_breaks_are_word_gaps() {
        // The Multi-tap keys for MEET ME AT DAWN (0 is a space), one letter per line
        assert_eq!(
            crack("770-1477\n697-1477 697-1477\n697-1477 697-1477\n852-1336\n941-1336\n770-1477\n697-1477 697-1477\n941-1336\n697-1336\n852-1336\n941-1336\n697-1477\n697-1336\n852-1477\n770-1477 770-1477").unwrap(),
            "6 33 33 8 0 6 33 0 2 8 0 3 2 9 66"
        );
        // Windows line breaks
        assert_eq!(
            crack("770-1209 770-1209\r\n697-1477 697-1477\r\n770-1336 770-1336 770-1336").unwrap(),
            "44 33 555"
        );
    }

    #[test]
    fn pipes_are_word_gaps() {
        assert_eq!(
            crack("770-1209 770-1209 | 697-1477 697-1477 | 770-1336 770-1336 770-1336").unwrap(),
            "44 33 555"
        );
        assert_eq!(
            crack("770-1209 770-1209|697-1477 697-1477|770-1336 770-1336 770-1336").unwrap(),
            "44 33 555"
        );
    }

    #[test]
    fn two_whitespace_characters_are_a_word_gap() {
        assert_eq!(
            crack("770-1209 770-1209  697-1477 697-1477 \t770-1336 770-1336 770-1336").unwrap(),
            "44 33 555"
        );
        // Several markers in a row are still one gap
        assert_eq!(
            crack("770-1209 770-1209 \n | \n 697-1477 697-1477").unwrap(),
            "44 33"
        );
    }

    #[test]
    fn single_separators_are_not_word_gaps() {
        assert_eq!(
            crack("697-1209 697-1336\t697-1477/770-1209-770-1336").unwrap(),
            "12345"
        );
        assert_eq!(crack("697-1209 / 697-1336 / 697-1477").unwrap(), "123");
    }

    #[test]
    fn line_breaks_inside_a_pair_are_not_word_gaps() {
        assert_eq!(crack("697\n1209 697\n1336 697\n1477").unwrap(), "123");
    }

    #[test]
    fn glued_runs_take_the_gap_before_them() {
        assert_eq!(crack("69712096971336\n6971477 7701209").unwrap(), "12 34");
    }

    #[test]
    fn decodes_other_separators() {
        assert_eq!(crack("697,1209;697:1336,697;1477").unwrap(), "123");
        assert_eq!(crack("697+1209, 697+1336, 697+1477").unwrap(), "123");
    }

    #[test]
    fn decodes_glued_and_split_keys_together() {
        assert_eq!(crack("6971209 697-1336 1477697").unwrap(), "123");
    }

    #[test]
    fn ignores_surrounding_whitespace_and_trailing_separators() {
        assert_eq!(crack("  \n697-1209 697-1336 697-1477/\n").unwrap(), "123");
        assert_eq!(crack("697-1209 697-1336 697-1477 |").unwrap(), "123");
    }

    #[test]
    fn fails_on_other_letters() {
        assert_eq!(crack("697Hx+1209Hx 697Hx+1336Hx 697Hx+1477Hx"), None);
        assert_eq!(
            crack("697 kHz 1209 kHz 697 kHz 1336 kHz 697 kHz 1477 kHz"),
            None
        );
        assert_eq!(crack("697-1209 697-1336 697-1477 x"), None);
    }

    #[test]
    fn fails_on_other_punctuation() {
        assert_eq!(crack("697.1209 697.1336 697.1477"), None);
        assert_eq!(crack("697_1209 697_1336 697_1477"), None);
        assert_eq!(crack("(697,1209) (697,1336) (697,1477)"), None);
        // A non-breaking space isn't an ASCII separator
        assert_eq!(crack("697-1209\u{a0}697-1336 697-1477"), None);
    }

    #[test]
    fn fails_unless_the_first_byte_is_a_digit() {
        assert_eq!(crack("Hz697-1209 697-1336 697-1477"), None);
        assert_eq!(crack("-697-1209 697-1336 697-1477"), None);
        assert_eq!(crack("|697-1209 697-1336 697-1477"), None);
    }

    #[test]
    fn fails_on_two_frequencies_from_one_group() {
        // Low-low and high-high
        assert_eq!(crack("697-770"), None);
        assert_eq!(crack("1209/1336"), None);
        assert_eq!(crack("697-770 852-941 697-770"), None);
        assert_eq!(crack("697-1209 697-1336 1209-1477"), None);
    }

    #[test]
    fn fails_on_an_odd_number_of_frequencies() {
        assert_eq!(crack("697-1209 697-1336 697"), None);
        assert_eq!(crack("697-1209 697-1336 697-1477 852"), None);
        assert_eq!(crack("697-1209 697-1336 697-1477 1209"), None);
    }

    #[test]
    fn fails_with_fewer_than_three_keys() {
        assert_eq!(crack("697-1209"), None);
        assert_eq!(crack("697-1209 697-1336"), None);
        assert_eq!(crack("69712096971336"), None);
    }

    #[test]
    fn fails_on_numbers_that_are_not_frequencies() {
        // Zero-padded
        assert_eq!(crack("0697-1209 0697-1336 0697-1477"), None);
        // Close, but not DTMF
        assert_eq!(crack("697-1210 697-1336 697-1477"), None);
        assert_eq!(crack("698-1209 697-1336 697-1477"), None);
        // 5 digits are neither a frequency nor glued keys
        assert_eq!(crack("69712 09697 13369"), None);
    }

    #[test]
    fn fails_on_glued_digits_that_are_not_keys() {
        assert_eq!(crack("1234567 1234567 1234567"), None);
        // Not a multiple of 7 digits
        assert_eq!(crack("69712096971336697147"), None);
        // A key can't be half a lone frequency and half glued digits
        assert_eq!(crack("697 1209697 1336697 1477"), None);
        // Long runs of digits fail without overflowing
        assert_eq!(crack(&"1".repeat(7 * 1000)), None);
        assert_eq!(crack(&"9".repeat(7 * 1000 + 1)), None);
        assert_eq!(crack(&format!("{}1", "6971209".repeat(1000))), None);
    }

    #[test]
    fn fails_on_other_numeric_encodings() {
        // A1Z26
        assert_eq!(crack("8-5-12-12-15"), None);
        // Decimal
        assert_eq!(crack("104 101 108 108 111"), None);
        // Multi-tap
        assert_eq!(crack("44 33 555 555 666 0 9 666 777 555 3"), None);
        // T9
        assert_eq!(crack("43556 96753"), None);
        // Binary, 7 and 8 bits
        assert_eq!(crack("1101000 1100101 1101100 1101100 1101111"), None);
        assert_eq!(crack("01101000 01100101 01101100"), None);
    }

    #[test]
    fn fails_on_phone_and_card_numbers() {
        assert_eq!(crack("555-1234"), None);
        assert_eq!(crack("0800 123 456"), None);
        assert_eq!(crack("1234 5678 9012 3456"), None);
    }

    #[test]
    fn other_numeric_decoders_reject_dtmf() {
        // DTMF passes Decimal's byte scan, but every number is above 255 and none is
        // printable ASCII. A1Z26 only reads 1 to 26, and Octal values are at most 3 digits
        // (or 4 with a leading 0) and 377, so no other number decoder returns a result for
        // the same input.
        for text in [
            ISSUE_EXAMPLE,
            "8521336770147785212097701336697147794113368521477",
            // Only digits 0-7 and spaces, so Octal gets past its byte scan
            "770 1336 770 1477 770 1633",
        ] {
            let checker = get_athena_checker();
            let decimal = Decoder::<DecimalDecoder>::new().crack(text, &checker);
            assert_eq!(decimal.unencrypted_text, None, "Decimal decoded {text:?}");
            let a1z26 = Decoder::<A1Z26Decoder>::new().crack(text, &checker);
            assert_eq!(a1z26.unencrypted_text, None, "A1Z26 decoded {text:?}");
            let octal = Decoder::<OctalDecoder>::new().crack(text, &checker);
            assert_eq!(octal.unencrypted_text, None, "Octal decoded {text:?}");
        }
        // Big integer reads one run of digits, like the glued form, as bytes. Those bytes
        // aren't text.
        let glued = "8521336770147785212097701336697147794113368521477";
        let big_integer = Decoder::<BigIntegerDecoder>::new().crack(glued, &get_athena_checker());
        assert_eq!(
            big_integer.unencrypted_text, None,
            "Big integer decoded {glued:?}"
        );
        assert_eq!(crack("770 1336 770 1477 770 1633").unwrap(), "56B");
    }

    #[test]
    fn handles_panic_if_empty_string() {
        assert_eq!(crack(""), None);
    }

    #[test]
    fn handles_panic_if_whitespace() {
        assert_eq!(crack(" \t\r\n "), None);
    }

    #[test]
    fn handles_panic_if_emoji() {
        assert_eq!(crack("😀"), None);
        assert_eq!(crack("697-1209 😀 697-1336 697-1477"), None);
    }

    #[test]
    fn fails_on_english() {
        assert_eq!(crack("hello world"), None);
        assert_eq!(crack("hello my name is panicky mc panic face!"), None);
    }

    #[test]
    fn fails_on_the_bench_miss_input() {
        assert_eq!(crack(BENCH_MISS), None);
    }

    #[test]
    fn is_registered() {
        // Exactly one decoder by that name runs in the search
        let decoders = get_decoder_by_name("DTMF");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "DTMF");
        // Cached results name the decoder; reading them back looks it up here
        let decoder = DECODER_MAP
            .get("DTMF")
            .expect("DTMF should be in DECODER_MAP")
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "DTMF");
    }
}
