//! Decompress gzip (RFC 1952) data.
//!
//! Ciphey passes text between decoders, and gzip is binary, so this decoder reads the
//! gzip bytes from three textual forms itself:
//! * Base64 (standard or URL-safe, line breaks allowed), which starts with `H4sI`,
//! * hex (`1f8b08…`, optionally split into bytes by whitespace, `:`, `,`, `;`, `-` or
//!   `%`, or prefixed with `0x` or `\x`),
//! * the raw bytes as Latin-1 text, which is what the Hexadecimal and Binary decoders
//!   emit for bytes that aren't UTF-8.
//!
//! Each form is recognised from its first few characters, so other text is rejected
//! without decoding or copying it. Decompression stops at [`MAX_OUTPUT`] bytes, so a
//! gzip bomb fails quickly instead of eating memory, and output the checker doesn't
//! accept is only passed on for more decoding up to [`MAX_CANDIDATE`] bytes.
//!
//! Call `gzip_decoder.crack` to use. It returns a [`CrackResult`]; check
//! `result.unencrypted_text.is_some()` to see if it decoded.

use std::io::Read;

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;
use base64::{engine::general_purpose, Engine as _};
use flate2::bufread::GzDecoder;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// Decompressed output above this many bytes is rejected rather than truncated: a
/// fragment of the plaintext isn't the plaintext.
const MAX_OUTPUT: usize = 1024 * 1024;

/// Output the checker didn't accept is only handed on for more decoding up to this many
/// bytes. Gzip output isn't bounded by the input's size, and every decoder runs on every
/// node of the search, so a few hundred bytes of gzip could otherwise make a megabyte
/// node. A 64 KiB input already keeps the search running well past its 5 second
/// timeout, and a 1 MiB one keeps it running for minutes.
const MAX_CANDIDATE: usize = 16 * 1024;

/// The smallest possible gzip member: a 10-byte header and an 8-byte trailer.
const MIN_MEMBER_LEN: usize = 18;

/// ID1, ID2 and CM (8 = deflate), the first three bytes of every gzip member.
const MAGIC: [u8; 3] = [0x1f, 0x8b, 0x08];

/// The magic bytes as hex digits.
const MAGIC_HEX_DIGITS: [u8; 6] = [0x1, 0xf, 0x8, 0xb, 0x0, 0x8];

/// The magic bytes as Base64. Three bytes fill exactly four Base64 characters.
const MAGIC_BASE64: &str = "H4sI";

/// The Gzip decoder, call:
/// `let gzip_decoder = Decoder::<GzipDecoder>::new()` to create a new instance
/// And then call:
/// `result = gzip_decoder.crack(input)` to decompress gzip given as Base64 or hex
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::gzip_decoder::GzipDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_gzip = Decoder::<GzipDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // Python: base64.b64encode(gzip.compress(b"The quick brown fox jumps over the lazy dog", mtime=0))
/// let result = decode_gzip
///     .crack(
///         "H4sIAAAAAAAC/wvJSFUoLM1MzlZIKsovz1NIy69QyCrNLShWyC9LLVIoAUrnJFZVKqTkpwMAOaNPQSsAAAA=",
///         &checker,
///     )
///     .unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "The quick brown fox jumps over the lazy dog");
/// ```
pub struct GzipDecoder;

impl Crack for Decoder<GzipDecoder> {
    fn new() -> Decoder<GzipDecoder> {
        Decoder {
            name: "Gzip",
            description: "Gzip is a file format for data compressed with DEFLATE. Every gzip member starts with the bytes 1F 8B 08, which is H4sI in Base64. This decoder decompresses gzip given as Base64, as hex or as the raw bytes, including files with several members.",
            link: "https://datatracker.ietf.org/doc/html/rfc1952",
            tags: vec!["gzip", "compression", "decoder"],
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decompresses `text` if it is gzip as Base64, hex or raw bytes, and checks the
    /// decompressed text. Fails (with `unencrypted_text` set to `None`) if `text` isn't
    /// gzip, doesn't decompress, decompresses to something that isn't text, or
    /// decompresses to more than [`MAX_CANDIDATE`] bytes that the checker doesn't accept.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Gzip with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(compressed) = gzip_bytes(text) else {
            debug!("Gzip failed: input is not gzip as Base64, hex or raw bytes");
            return results;
        };
        let Some(gunzipped) = gunzip_bounded(&compressed) else {
            debug!("Gzip failed: the data did not decompress");
            return results;
        };

        // Another gzip stream inside: hand it back as raw bytes for another Gzip step.
        // It is binary, so there is nothing for the checker to look at.
        if gunzipped.data.starts_with(&MAGIC) {
            if gunzipped.data.len() > MAX_CANDIDATE {
                debug!("Gzip output is gzip again, but too long to decode further");
                return results;
            }
            debug!("Gzip output is gzip again; returning it as an unchecked candidate");
            results.unencrypted_text = Some(vec![latin1_to_string(&gunzipped.data)]);
            results.key = gunzipped.filename;
            return results;
        }

        let Some(decoded_text) = as_plaintext(gunzipped.data) else {
            info!("Failed to decode Gzip: the output is binary, not text");
            return results;
        };
        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Gzip because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        if !checker_result.is_identified && decoded_text.len() > MAX_CANDIDATE {
            debug!(
                "Gzip output is not plaintext and too long ({} bytes) to decode further",
                decoded_text.len()
            );
            return results;
        }
        results.unencrypted_text = Some(vec![decoded_text]);
        // gzip has no key, but the header can carry the original file name (FNAME)
        results.key = gunzipped.filename;
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// The result of decompressing a gzip file.
#[derive(Debug, PartialEq)]
struct Gunzipped {
    /// The decompressed bytes of every member, in order.
    data: Vec<u8>,
    /// The original file name from the first member's header (FNAME), if it has one
    /// that is printable.
    filename: Option<String>,
}

/// Finds gzip bytes in `text`: Base64, hex, or raw bytes as Latin-1 characters.
/// Only the first few characters are looked at unless they spell the gzip magic.
fn gzip_bytes(text: &str) -> Option<Vec<u8>> {
    let bytes = base64_view(text)
        .or_else(|| hex_view(text))
        .or_else(|| raw_view(text))?;
    (bytes.len() >= MIN_MEMBER_LEN).then_some(bytes)
}

/// Base64, standard or URL-safe, that starts with `H4sI`. Whitespace (line breaks) is
/// ignored and padding is optional.
fn base64_view(text: &str) -> Option<Vec<u8>> {
    let text = text.trim();
    if !text.starts_with(MAGIC_BASE64) {
        return None;
    }
    let body: String = text.chars().filter(|c| !c.is_whitespace()).collect();
    let unpadded = body.trim_end_matches('=');
    if body.len() - unpadded.len() > 2 {
        return None;
    }
    // The Base64 decoder's engines. Both reject '=' inside the text.
    general_purpose::STANDARD_NO_PAD
        .decode(unpadded)
        .or_else(|_| general_purpose::URL_SAFE_NO_PAD.decode(unpadded))
        .ok()
}

/// Hex that starts with `1f8b08`, in any case. Bytes can be separated by whitespace,
/// `:`, `,`, `;`, `-` or `%`, and each can have a `0x` or `\x` prefix.
fn hex_view(text: &str) -> Option<Vec<u8>> {
    let text = text.trim();
    // Cheap gate: the first six digits have to be the magic, otherwise stop here.
    let mut digits = HexDigits::new(text.as_bytes());
    for expected in MAGIC_HEX_DIGITS {
        if digits.next() != Some(Some(expected)) {
            return None;
        }
    }

    let mut bytes = Vec::with_capacity(text.len() / 2);
    let mut digits = HexDigits::new(text.as_bytes());
    while let Some(high) = digits.next() {
        // A character that isn't hex or a separator, or an odd number of digits
        let (high, low) = (high?, digits.next()??);
        bytes.push((high << 4) | low);
    }
    Some(bytes)
}

/// Gzip bytes as Latin-1 text, one character per byte. The Hexadecimal and Binary
/// decoders turn bytes that aren't UTF-8 (gzip never is) into this.
fn raw_view(text: &str) -> Option<Vec<u8>> {
    let mut chars = text.chars();
    if !MAGIC
        .iter()
        .all(|&byte| chars.next() == Some(char::from(byte)))
    {
        return None;
    }
    text.chars().map(|c| u8::try_from(c).ok()).collect()
}

/// Iterates over the hex digits of a hex string, skipping the separators and prefixes
/// [`hex_view`] allows. Yields `Some(digit)` for each digit, and `None` for a character
/// that doesn't belong in hex. Separators and prefixes are only allowed between bytes.
struct HexDigits<'a> {
    /// The text being read.
    bytes: &'a [u8],
    /// Index of the next unread byte.
    position: usize,
    /// Whether the last digit read was the first half of a byte.
    mid_byte: bool,
}

impl<'a> HexDigits<'a> {
    /// Starts reading at the beginning of `bytes`.
    fn new(bytes: &'a [u8]) -> Self {
        HexDigits {
            bytes,
            position: 0,
            mid_byte: false,
        }
    }
}

impl Iterator for HexDigits<'_> {
    type Item = Option<u8>;

    fn next(&mut self) -> Option<Self::Item> {
        loop {
            let byte = *self.bytes.get(self.position)?;
            let next = self.bytes.get(self.position + 1).copied();
            if let Some(digit) = char::from(byte).to_digit(16) {
                if !self.mid_byte && byte == b'0' && matches!(next, Some(b'x' | b'X')) {
                    // A 0x prefix
                    self.position += 2;
                    continue;
                }
                self.position += 1;
                self.mid_byte = !self.mid_byte;
                return Some(Some(digit as u8));
            }
            let is_prefix = byte == b'\\' && matches!(next, Some(b'x' | b'X'));
            let is_separator = byte.is_ascii_whitespace() || b":,;-%".contains(&byte);
            if self.mid_byte || !(is_prefix || is_separator) {
                // Stop for good after the first bad character
                self.position = self.bytes.len();
                return Some(None);
            }
            self.position += if is_prefix { 2 } else { 1 };
        }
    }
}

/// Decompresses a gzip file of one or more members (RFC 1952 section 2.2), the way
/// `gzip -d` does.
///
/// Every member has to decompress, pass its CRC-32 and length check and start right
/// after the previous one. Anything after the last member that isn't another member,
/// such as zero padding, is ignored, also like `gzip -d`. Returns `None` if the data
/// isn't gzip, is corrupt or truncated, or decompresses to more than [`MAX_OUTPUT`]
/// bytes. In that case decompression stops at the limit, so a gzip bomb costs about as
/// much as decompressing [`MAX_OUTPUT`] bytes.
fn gunzip_bounded(compressed: &[u8]) -> Option<Gunzipped> {
    if compressed.len() < MIN_MEMBER_LEN || !compressed.starts_with(&MAGIC) {
        return None;
    }

    let mut data = Vec::new();
    let mut filename = None;
    let mut rest = compressed;
    let mut first_member = true;
    // Like gzip -d, anything starting with the two ID bytes is another member and has to
    // decode. A different CM byte is an error there too.
    while first_member || rest.starts_with(&MAGIC[..2]) {
        let mut member = GzDecoder::new(rest);
        // One byte over the limit tells an output of exactly MAX_OUTPUT bytes apart from
        // a longer one.
        let budget = (MAX_OUTPUT + 1 - data.len()) as u64;
        if let Err(error) = (&mut member).take(budget).read_to_end(&mut data) {
            debug!("Gzip member failed to decompress: {}", error);
            return None;
        }
        if data.len() > MAX_OUTPUT {
            debug!("Gzip output is over {} bytes, giving up", MAX_OUTPUT);
            return None;
        }
        if first_member {
            filename = member
                .header()
                .and_then(|header| header.filename())
                .and_then(printable_filename);
            first_member = false;
        }
        rest = member.into_inner();
    }

    Some(Gunzipped { data, filename })
}

/// The header's file name as text, if it has any characters and none of them are
/// control characters. RFC 1952 says it is Latin-1, but gzip writes whatever bytes the
/// file system uses, which today is UTF-8, so UTF-8 is tried first.
fn printable_filename(name: &[u8]) -> Option<String> {
    let name = match std::str::from_utf8(name) {
        Ok(name) => name.to_string(),
        Err(_) => latin1_to_string(name),
    };
    (!name.is_empty() && !name.chars().any(char::is_control)).then_some(name)
}

/// The decompressed bytes as text, if they are UTF-8 text without control characters
/// other than tab, line feed and carriage return. Binary files are rejected.
fn as_plaintext(data: Vec<u8>) -> Option<String> {
    let text = String::from_utf8(data).ok()?;
    let is_text = !text
        .chars()
        .any(|c| c.is_control() && !matches!(c, '\t' | '\n' | '\r'));
    is_text.then_some(text)
}

/// One character per byte, U+0000 to U+00FF. The inverse of [`raw_view`].
fn latin1_to_string(bytes: &[u8]) -> String {
    bytes.iter().map(|&byte| char::from(byte)).collect()
}

#[cfg(test)]
mod tests {
    use super::{
        gunzip_bounded, gzip_bytes, hex_view, latin1_to_string, printable_filename, Gunzipped,
        GzipDecoder, MAX_CANDIDATE, MAX_OUTPUT,
    };
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::interface::{Crack, Decoder},
    };
    use base64::{engine::general_purpose, Engine as _};
    use flate2::{write::GzEncoder, Compression, GzBuilder};
    use std::io::Write;
    use std::time::{Duration, Instant};

    // Unless noted otherwise, the vectors were made with Python 3's
    // gzip.compress(data, mtime=0) and decompress to the same text with GNU gzip 1.12
    // (gzip -dc) and CyberChef's Gunzip.

    const SPHINX: &str = "Sphinx of black quartz, judge my vow.";
    /// The example in https://github.com/bee-san/Ciphey/issues/1020
    const SPHINX_BASE64: &str =
        "H4sIAAAAAAACAwsuyMjMq1DIT1NIyklMzlYoLE0sKqnSUcgqTUlPVcitVCjLL9cDAN+jOaglAAAA";
    /// The same, as hex (from the issue)
    const SPHINX_HEX: &str = "1f8b08000000000002030b2ec8c8ccab50c84f5348ca494cce56282c4d2c2aa9d251c82a4d494f55c8ad5428cb2fd70300dfa339a825000000";

    const FOX: &str = "The quick brown fox jumps over the lazy dog";
    const FOX_BASE64: &str =
        "H4sIAAAAAAAC/wvJSFUoLM1MzlZIKsovz1NIy69QyCrNLShWyC9LLVIoAUrnJFZVKqTkpwMAOaNPQSsAAAA=";
    const FOX_HEX: &str = "1f8b08000000000002ff0bc94855282ccd4cce56482aca2fcf5348cbaf50c82acd2d2856c82f4b2d5228014ae72456552aa4e4a7030039a34f412b000000";

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    /// Runs the decoder and returns the first decoded string, if any
    fn decode(text: &str) -> Option<String> {
        Decoder::<GzipDecoder>::new()
            .crack(text, &get_athena_checker())
            .unencrypted_text
            .map(|texts| texts[0].clone())
    }

    fn hex_to_bytes(hex: &str) -> Vec<u8> {
        hex_view(hex).expect("valid gzip hex")
    }

    fn gzip(data: &[u8]) -> Vec<u8> {
        let mut encoder = GzEncoder::new(Vec::new(), Compression::default());
        encoder.write_all(data).unwrap();
        encoder.finish().unwrap()
    }

    #[test]
    fn decodes_issue_example_base64() {
        // Athena doesn't recognise this sentence as English, so only the text is checked
        assert_eq!(decode(SPHINX_BASE64).as_deref(), Some(SPHINX));
    }

    #[test]
    fn decodes_issue_example_hex() {
        assert_eq!(decode(SPHINX_HEX).as_deref(), Some(SPHINX));
    }

    #[test]
    fn decodes_and_identifies_fox_base64() {
        let result = Decoder::<GzipDecoder>::new().crack(FOX_BASE64, &get_athena_checker());
        assert!(result.success, "Athena should identify the plaintext");
        assert_eq!(result.unencrypted_text.unwrap(), [FOX]);
        assert_eq!(result.decoder, "Gzip");
        assert!(result.key.is_none(), "this file has no FNAME");
    }

    #[test]
    fn decodes_and_identifies_fox_hex() {
        let result = Decoder::<GzipDecoder>::new().crack(FOX_HEX, &get_athena_checker());
        assert!(result.success, "Athena should identify the plaintext");
        assert_eq!(result.unencrypted_text.unwrap(), [FOX]);
    }

    #[test]
    fn decodes_uppercase_and_delimited_hex() {
        let bytes = hex_to_bytes(FOX_HEX);
        let spaced: Vec<String> = bytes.iter().map(|b| format!("{b:02x}")).collect();
        let forms = [
            FOX_HEX.to_uppercase(),
            spaced.join(" "),
            spaced.join(":"),
            spaced.join("\n"),
            // xxd -i
            bytes
                .iter()
                .map(|b| format!("0x{b:02x}"))
                .collect::<Vec<_>>()
                .join(", "),
            // Python / C escapes
            bytes.iter().map(|b| format!("\\x{b:02X}")).collect(),
            format!("0x{FOX_HEX}"),
            format!("  {FOX_HEX}\n"),
        ];
        for form in forms {
            assert_eq!(decode(&form).as_deref(), Some(FOX), "{form}");
        }
    }

    #[test]
    fn decodes_wrapped_unpadded_and_url_safe_base64() {
        let bytes = general_purpose::STANDARD.decode(FOX_BASE64).unwrap();
        let wrapped: String = FOX_BASE64
            .as_bytes()
            .chunks(20)
            .map(|line| format!("{}\r\n", std::str::from_utf8(line).unwrap()))
            .collect();
        let forms = [
            wrapped,
            FOX_BASE64.trim_end_matches('=').to_string(),
            general_purpose::URL_SAFE.encode(&bytes),
        ];
        assert!(forms[2].contains('_'), "the URL-safe form should differ");
        for form in forms {
            assert_eq!(decode(&form).as_deref(), Some(FOX), "{form}");
        }
    }

    #[test]
    fn decodes_raw_latin1_bytes_from_the_hexadecimal_decoder() {
        // The Hexadecimal decoder turns gzip hex into this
        let raw = latin1_to_string(&hex_to_bytes(FOX_HEX));
        assert_eq!(decode(&raw).as_deref(), Some(FOX));
    }

    #[test]
    fn decodes_two_members() {
        // gzip.compress(b"The quick brown fox ") + gzip.compress(b"jumps over the lazy dog")
        let two_members = "H4sIAAAAAAAC/wvJSFUoLM1MzlZIKsovz1NIy69QAADidbCIFAAAAB+LCAAAAAAAAv/LKs0tKFbIL0stUijJSFXISayqVEjJTwcAlGd4GBcAAAA=";
        assert_eq!(decode(two_members).as_deref(), Some(FOX));
    }

    #[test]
    fn ignores_zero_padding_and_trailing_garbage() {
        // gzip -dc accepts all of these (it warns about the garbage)
        let fox = hex_to_bytes(FOX_HEX);
        let twice = [fox.clone(), fox.clone()].concat();
        let cases = [
            ([fox.as_slice(), &[0; 16]].concat(), FOX.to_string()),
            ([fox.as_slice(), &[0; 3]].concat(), FOX.to_string()),
            ([fox.as_slice(), b"trailing junk"].concat(), FOX.to_string()),
            // MultiGzDecoder fails on this and GzDecoder stops after the first member
            ([twice.as_slice(), &[0; 16]].concat(), FOX.repeat(2)),
        ];
        for (compressed, expected) in cases {
            let gunzipped = gunzip_bounded(&compressed).expect("should decompress");
            assert_eq!(gunzipped.data, expected.as_bytes());
        }
    }

    #[test]
    fn decodes_every_optional_header_field() {
        // FHCRC, FEXTRA (one "Cp" subfield), FNAME "fox.txt" and FCOMMENT "made by hand",
        // put together in Python with zlib.compressobj(wbits=-15) and checked with gzip -dc
        let all_fields = "H4sIHgAAAAAC/wgAQ3AEAAECAwRmb3gudHh0AG1hZGUgYnkgaGFuZABQFwvJSFUoLM1MzlZIKsovz1NIy69QyCrNLShWyC9LLVIoAUrnJFZVKqTkpwMAOaNPQSsAAAA=";
        let result = Decoder::<GzipDecoder>::new().crack(all_fields, &get_athena_checker());
        assert_eq!(result.unencrypted_text.unwrap(), [FOX]);
        assert_eq!(result.key.as_deref(), Some("fox.txt"));

        // The same with the header CRC-16 changed. gzip -dc: "header checksum 0x17af !=
        // computed checksum 0x1750"
        let bad_header_crc = "H4sIHgAAAAAC/wgAQ3AEAAECAwRmb3gudHh0AG1hZGUgYnkgaGFuZACvFwvJSFUoLM1MzlZIKsovz1NIy69QyCrNLShWyC9LLVIoAUrnJFZVKqTkpwMAOaNPQSsAAAA=";
        assert_eq!(decode(bad_header_crc), None);
    }

    #[test]
    fn puts_the_file_name_in_the_key() {
        // GzipFile(filename="flag.txt", mtime=0) around b"flag{gunzip_me}"
        let result = Decoder::<GzipDecoder>::new().crack(
            "H4sICAAAAAAC/2ZsYWcudHh0AEvLSUyvTi/Nq8osiM9NrQUA3xCTdA8AAAA=",
            &get_athena_checker(),
        );
        assert!(result.success, "LemmeKnow should identify the CTF flag");
        assert_eq!(result.unencrypted_text.unwrap(), ["flag{gunzip_me}"]);
        assert_eq!(result.key.as_deref(), Some("flag.txt"));
    }

    #[test]
    fn ignores_file_names_with_control_characters() {
        let mut encoder = GzBuilder::new()
            .filename("\u{1b}[2Jevil.txt")
            .write(Vec::new(), Compression::default());
        encoder.write_all(FOX.as_bytes()).unwrap();
        let compressed = encoder.finish().unwrap();

        let gunzipped = gunzip_bounded(&compressed).unwrap();
        assert_eq!(gunzipped.data, FOX.as_bytes());
        assert_eq!(gunzipped.filename, None);
    }

    #[test]
    fn returns_nested_gzip_for_another_gzip_step() {
        // base64(gzip.compress(gzip.compress(FOX, mtime=0), mtime=0))
        let nested = "H4sIAAAAAAAC/5Pv5mAAAab/3Cc9QjV0zvqcC/PQOqV/Ptjj9PqAE1pndTXCTuh76wZpMHo9VwkL1VryZDkzg+Vif0dtoC4AOcZqCD4AAAA=";
        let result = Decoder::<GzipDecoder>::new().crack(nested, &get_athena_checker());
        assert!(!result.success, "the inner gzip is binary, not plaintext");
        let inner = result.unencrypted_text.expect("the inner gzip stream");
        assert_eq!(inner[0], latin1_to_string(&hex_to_bytes(FOX_HEX)));

        // Second step, on the first step's output
        let result = Decoder::<GzipDecoder>::new().crack(&inner[0], &get_athena_checker());
        assert!(result.success);
        assert_eq!(result.unencrypted_text.unwrap(), [FOX]);
    }

    #[test]
    fn rejects_bad_crc_and_truncated_streams() {
        // CyberChef Gunzip: "invalid CRC-32 checksum"
        let bad_crc = "1f8b08000000000002ff0bc94855282ccd4cce56482aca2fcf5348cbaf50c82acd2d2856c82f4b2d5228014ae72456552aa4e4a70300c6a34f412b000000";
        // The same stream without its last 6 bytes, so the trailer is cut off inside the
        // CRC-32 (from the issue)
        let truncated = "1f8b08000000000002ff0bc94855282ccd4cce56482aca2fcf5348cbaf50c82acd2d2856c82f4b2d5228014ae72456552aa4e4a7030039a3";
        // A wrong ISIZE
        let bad_length = FOX_HEX.replace("2b000000", "2c000000");
        // A complete member followed by a truncated one: gzip -dc says "unexpected end
        // of file"
        let fox = hex_to_bytes(FOX_HEX);
        let truncated_second_member = [fox.as_slice(), &fox[..30]].concat();

        for hex in [bad_crc, truncated, bad_length.as_str()] {
            assert_eq!(decode(hex), None, "{hex}");
            assert_eq!(gunzip_bounded(&hex_to_bytes(hex)), None, "{hex}");
        }
        assert_eq!(gunzip_bounded(&truncated_second_member), None);
    }

    #[test]
    fn rejects_header_only_and_empty_streams() {
        // gzip.compress(b"", mtime=0)[:10]
        assert_eq!(decode("H4sIAAAAAAAC/w=="), None);
        assert_eq!(decode("1f8b08000000000002ff"), None);
        assert_eq!(decode("H4sI"), None);
        // gzip.compress(b"", mtime=0) is valid but has no text in it
        assert_eq!(decode("H4sIAAAAAAAC/wMAAAAAAAAAAAA="), None);
    }

    #[test]
    fn rejects_binary_output() {
        // gzip.compress(bytes(range(256)), mtime=0): not UTF-8
        let binary = "H4sIAAAAAAAC/wEAAf/+AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna29zd3t/g4eLj5OXm5+jp6uvs7e7v8PHy8/T19vf4+fr7/P3+/3OMBSkAAQAA";
        assert_eq!(decode(binary), None);
        // gzip.compress(b"\x1b[31mred alert\x1b[0m", mtime=0): UTF-8 with control characters
        assert_eq!(
            decode("H4sIAAAAAAAC/5OONjbMLUpNUUjMSS0qkY42yAUAAtuOTBIAAAA="),
            None
        );
    }

    #[test]
    fn stops_a_gzip_bomb_at_the_size_limit() {
        // 64 MiB of "A" compresses to about 300 KB at this level (65 KB at best)
        let bomb = {
            let mut encoder = GzEncoder::new(Vec::new(), Compression::fast());
            let chunk = vec![b'A'; 1024 * 1024];
            for _ in 0..64 {
                encoder.write_all(&chunk).unwrap();
            }
            encoder.finish().unwrap()
        };
        let base64_bomb = general_purpose::STANDARD.encode(&bomb);

        let start = Instant::now();
        assert_eq!(gunzip_bounded(&bomb), None);
        assert_eq!(decode(&base64_bomb), None);
        assert!(
            start.elapsed() < Duration::from_secs(5),
            "took {:?}",
            start.elapsed()
        );
    }

    #[test]
    fn output_size_limit_is_inclusive() {
        let at_limit = gzip(&vec![b'A'; MAX_OUTPUT]);
        assert_eq!(gunzip_bounded(&at_limit).unwrap().data.len(), MAX_OUTPUT);

        let over_limit = gzip(&vec![b'A'; MAX_OUTPUT + 1]);
        assert_eq!(gunzip_bounded(&over_limit), None);

        // The limit is for all members together
        let half = gzip(&vec![b'A'; MAX_OUTPUT / 2 + 1]);
        assert_eq!(gunzip_bounded(&[half.clone(), half].concat()), None);
    }

    #[test]
    fn long_output_is_only_kept_if_the_checker_accepts_it() {
        let crack = |data: &[u8]| {
            let base64 = general_purpose::STANDARD.encode(gzip(data));
            Decoder::<GzipDecoder>::new().crack(&base64, &get_athena_checker())
        };

        // Not plaintext: handed on for more decoding up to the limit, dropped above it
        let result = crack(&vec![b'A'; MAX_CANDIDATE]);
        assert!(!result.success);
        assert_eq!(result.unencrypted_text.unwrap()[0].len(), MAX_CANDIDATE);
        assert!(crack(&vec![b'A'; MAX_CANDIDATE + 1])
            .unencrypted_text
            .is_none());

        // Plaintext is returned whatever its length (up to MAX_OUTPUT)
        let english = format!("{FOX}. ").repeat(MAX_CANDIDATE / FOX.len() + 1);
        assert!(english.len() > MAX_CANDIDATE);
        let result = crack(english.as_bytes());
        assert!(result.success, "Athena should identify the plaintext");
        assert_eq!(result.unencrypted_text.unwrap(), [english]);
    }

    #[test]
    fn long_nested_gzip_is_not_handed_on() {
        // Pseudo-random bytes (xorshift64) don't compress, so the inner gzip stream is
        // longer than the limit
        let mut state = 0x2545_f491_4f6c_dd1d_u64;
        let noise: Vec<u8> = (0..MAX_CANDIDATE)
            .map(|_| {
                state ^= state << 13;
                state ^= state >> 7;
                state ^= state << 17;
                state as u8
            })
            .collect();
        let inner = gzip(&noise);
        assert!(inner.len() > MAX_CANDIDATE);
        let nested = general_purpose::STANDARD.encode(gzip(&inner));
        let result = Decoder::<GzipDecoder>::new().crack(&nested, &get_athena_checker());
        assert!(result.unencrypted_text.is_none());
    }

    #[test]
    fn gunzip_returns_the_header_file_name() {
        let mut encoder = GzBuilder::new()
            .filename("café.txt")
            .write(Vec::new(), Compression::default());
        encoder.write_all(b"hello").unwrap();
        let compressed = encoder.finish().unwrap();
        assert_eq!(
            gunzip_bounded(&compressed),
            Some(Gunzipped {
                data: b"hello".to_vec(),
                filename: Some("café.txt".to_string()),
            })
        );
    }

    #[test]
    fn rejects_text_that_is_not_gzip() {
        // None of these get past the prefix checks
        for text in [
            "",
            "😀",
            "hello world",
            "hello my name is panicky mc panic face!",
            // Base64 and hex that aren't gzip
            "aGVsbG8gd29ybGQ=",
            "68656c6c6f20776f726c64",
            "1f8b08 is the gzip magic number",
            "1f8b0g000000000002ff0bc94855282ccd4cce56482aca2fcf5348cbaf50c8",
            // A separator inside a byte
            "1f8b0 8000000000002ff0bc94855282ccd4cce56482aca2fcf5348cbaf50c8",
            // Python zlib.compress(FOX) (#1021): 78 9c ...
            "eJwLyUhVKCzNTM5WSCrKL89TSMuvUMgqzS0oVsgvSy1SKAFK5yRWVSqk5KcDAFvcD9o=",
            // Too much padding
            "H4sIAAAAAAAC/wvJSFUoLM1MzlZIKsovz1NIy69QyCrNLShWyC9LLVIoAUrnJFZVKqTkpwMAOaNPQSsAAAA===",
        ] {
            assert_eq!(gzip_bytes(text), None, "{text}");
            assert_eq!(decode(text), None, "{text}");
        }

        // These start like gzip but don't decompress
        for text in [
            "H4sI is how gzip starts in Base64",
            "H4sIAAAAAAAC/wvJSFUoLM1MzlZIKsovz1NIy69Q",
            "1f8b0800000000000000000000000000000000000000000000",
        ] {
            assert_eq!(decode(text), None, "{text}");
        }
    }

    #[test]
    fn file_names_can_be_utf8_or_latin1() {
        assert_eq!(printable_filename(b"flag.txt").as_deref(), Some("flag.txt"));
        assert_eq!(
            printable_filename("café.txt".as_bytes()).as_deref(),
            Some("café.txt")
        );
        // "été.txt" in Latin-1, which isn't UTF-8
        assert_eq!(
            printable_filename(b"\xe9t\xe9.txt").as_deref(),
            Some("été.txt")
        );
        assert_eq!(printable_filename(b""), None);
        assert_eq!(printable_filename(b"two\nlines"), None);
    }

    #[test]
    fn gzip_handles_panic_if_empty_string() {
        let result = Decoder::<GzipDecoder>::new()
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn gzip_handles_panic_if_emoji() {
        let result = Decoder::<GzipDecoder>::new()
            .crack("😂", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn rejects_latin1_text_with_characters_above_u00ff() {
        let mut raw = latin1_to_string(&hex_to_bytes(FOX_HEX));
        raw.push('€');
        assert_eq!(gzip_bytes(&raw), None);
    }

    #[test]
    fn is_registered() {
        let decoders = crate::filtration_system::get_decoder_by_name("Gzip");
        assert_eq!(decoders.components.len(), 1);
        // Cached search paths name their decoders, and are read back through the map
        assert!(crate::decoders::DECODER_MAP.contains_key("Gzip"));
    }
}
