//! Decode a hex dump back to the bytes that were dumped: the output of `xxd`,
//! `hexdump -C`, `od -A x -t x1z`, `od -t x1`, plain `hexdump` or `od -x`, and the octal
//! dumps of plain `od` and `od -b`.
//!
//! Every line of a dump is an offset, a run of groups and an optional column of ASCII,
//! which is ignored:
//!
//! * `xxd`: `00000000: 5370 6869 … 6b20  Sphinx of black `. Groups of 4 hex digits
//!   (2 with `-g1`, 8 with `-g4`) in byte order; the last group of the dump can be
//!   shorter.
//! * `hexdump -C`: `00000000  53 70 … 6f  66 20 … 20  |Sphinx of black |`.
//! * `od -A x -t x1z` and `od -t x1`: `000000 53 70 … 20  >Sphinx of black <`, or
//!   `0000000 53 70 … 20` with octal (or, with `-A d`, decimal) offsets.
//! * Plain `hexdump`, `hexdump -x`, `od -x` and `od -t x2`: `0000000 7053 6968 …`,
//!   16-bit little-endian words, so `7053` is the bytes `53 70`.
//! * `od -b` and `hexdump -b`: `0000000 123 160 150 …`, one byte per 3 octal digits.
//! * Plain `od`, `od -o` and `hexdump -o`: `0000000 070123 064550 …`, 16-bit
//!   little-endian words in 6 octal digits, so `070123` is `0x7053`, the bytes `53 70`.
//!
//! A dump of words pads an odd trailing byte with `00`, which is dropped. `hexdump` and
//! `od` end with a line holding only the offset after the last byte. Offsets have to
//! increase from line to line, and every line has as many bytes as the first except the
//! last one. A `*` line, which stands for repeated lines that were left out, fails the
//! decode. Line breaks at the end of dumped text are dropped, as `ciphey -f` drops them
//! from a file.
//!
//! Call hexdump_decoder.crack to use. It returns a `CrackResult` whose `unencrypted_text`
//! is `None` when the input isn't a hex dump.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::{bytes_to_string, check_string_success};

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The Hexdump decoder, call:
/// `let hexdump_decoder = Decoder::<HexdumpDecoder>::new()` to create a new instance
/// And then call:
/// `result = hexdump_decoder.crack(input)` to decode a hex dump
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::hexdump_decoder::HexdumpDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_hexdump = Decoder::<HexdumpDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // xxd
/// let result = decode_hexdump
///     .crack("00000000: 4865 6c6c 6f2c 2057 6f72 6c64 21         Hello, World!", &checker)
///     .unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "Hello, World!");
///
/// // hexdump -C
/// let dump = "00000000  48 65 6c 6c 6f 2c 20 57  6f 72 6c 64 21           |Hello, World!|\n\
///             0000000d";
/// let result = decode_hexdump.crack(dump, &checker).unencrypted_text;
/// assert_eq!(result.unwrap()[0], "Hello, World!");
/// ```
pub struct HexdumpDecoder;

/// The fewest digits an offset has (`od -A x`). `hexdump` and `od` write 7, `xxd` and
/// `hexdump -C` 8.
const MIN_OFFSET_DIGITS: usize = 6;

/// The most digits an offset has.
const MAX_OFFSET_DIGITS: usize = 8;

/// Fewer bytes than this aren't worth checking: the search drops results this short.
const MIN_BYTES: usize = 3;

impl Crack for Decoder<HexdumpDecoder> {
    fn new() -> Decoder<HexdumpDecoder> {
        Decoder {
            name: "Hexdump",
            description: "The output of xxd, hexdump -C, od and plain hexdump: an offset, hex or octal bytes or 16-bit words, and an ASCII column that is ignored",
            link: "https://en.wikipedia.org/wiki/Hex_dump",
            tags: vec!["hexdump", "xxd", "hex", "decoder"],
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes `text` as a hex dump and checks the result with `checker`.
    /// `unencrypted_text` is `None` when `text` isn't a hex dump.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Hexdump with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(bytes) = decode_hexdump(text) else {
            debug!("Failed to decode Hexdump because the text isn't a hex dump");
            return results;
        };
        // UTF-8, or Latin-1 when the bytes aren't UTF-8, like Hexadecimal. Bytes that
        // aren't text are kept, so a dump of compressed data can go on to Gzip or Zlib.
        let decoded_text = bytes_to_string(bytes);
        trace!("Decoded text for Hexdump: {:?}", decoded_text);

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Hexdump because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Decodes a hex dump to the bytes that were dumped, or returns `None` if `text` isn't
/// one.
fn decode_hexdump(text: &str) -> Option<Vec<u8>> {
    // `ciphey -f` keeps leading blank lines, and a copied dump can end in a blank line
    let text = text.trim();
    let offset_digits = first_offset_digits(text.as_bytes())?;
    // xxd puts a colon after the offset, hexdump and od don't. Every line has to agree.
    let colon = text.as_bytes()[offset_digits] == b':';

    let mut bytes = Vec::with_capacity(text.len() / 3);
    // What the groups hold and how many digits each has, set by the first group of the dump
    let mut format = None;
    let mut group_digits = 0;
    // Bytes on the first line. Every later line has as many, except the last data line.
    let mut line_bytes = 0;
    let mut previous_offset = None;
    // A data line with fewer bytes than the first one was the last data line
    let mut short_line_seen = false;
    // A line with only an offset ends the dump
    let mut end_seen = false;
    // xxd -b writes each byte as 8 binary digits, which read as an 8-digit hex group
    let mut only_binary_digits = true;

    for line in text.lines() {
        if end_seen {
            return None;
        }
        // hexdump pads its last data line with spaces
        let (offset, mut rest) = split_offset(line.trim_end().as_bytes(), offset_digits)?;
        // Octal and decimal offsets are compared as hex, which keeps their order
        if previous_offset.is_some_and(|previous| offset <= previous) {
            return None;
        }
        previous_offset = Some(offset);

        if rest.is_empty() {
            end_seen = true;
            continue;
        }
        if short_line_seen {
            return None;
        }
        if colon {
            rest = rest.strip_prefix(b":")?;
        }
        if rest.first() != Some(&b' ') {
            return None;
        }

        let line_start = bytes.len();
        // xxd's last group can be shorter than the others: `2e` in `2076 6f77 2e`
        let mut short_group = false;
        loop {
            let spaces = rest.iter().take_while(|&&byte| byte == b' ').count();
            rest = &rest[spaces..];
            let on_line = bytes.len() - line_start;
            let Some(&next) = rest.first() else {
                break;
            };
            if colon {
                // xxd separates groups with one space and the ASCII column with two or more
                if spaces >= 2 && on_line > 0 {
                    break;
                }
                if short_group {
                    return None;
                }
            } else if matches!(next, b'|' | b'>') || (line_bytes > 0 && on_line == line_bytes) {
                // The ASCII column of hexdump -C starts with `|`, od -z's with `>`
                break;
            }

            let digits = rest
                .iter()
                .take_while(|byte| byte.is_ascii_hexdigit())
                .count();
            let whole_token = rest.get(digits).is_none_or(|&byte| byte == b' ');
            let group_format = match format {
                Some(group_format) => group_format,
                None => {
                    // The first group of the dump sets the format
                    let group_format = whole_token
                        .then(|| Format::from_first_group(digits, colon))
                        .flatten()?;
                    format = Some(group_format);
                    group_digits = digits;
                    group_format
                }
            };
            if !whole_token || digits != group_digits {
                if !colon {
                    // Not a group, so the hex ends here and the rest of the line is ignored
                    break;
                }
                if !whole_token || digits > group_digits || digits < 2 || digits % 2 != 0 {
                    return None;
                }
                short_group = true;
            }

            let (group, after) = rest.split_at(digits);
            // An octal group with a digit that isn't octal, or too big for its size
            if !push_group(&mut bytes, group, group_format) {
                return None;
            }
            only_binary_digits &= group.iter().all(|&digit| matches!(digit, b'0' | b'1'));
            rest = after;
        }

        let on_line = bytes.len() - line_start;
        if on_line == 0 {
            return None;
        }
        if line_bytes == 0 {
            line_bytes = on_line;
        } else if on_line > line_bytes {
            return None;
        }
        short_line_seen = short_group || on_line < line_bytes;
    }

    let format = format?;
    // Octal digits are 0 to 7, so text like `HAHA` (110 101 110 101) is all 0s and 1s
    if only_binary_digits && !format.is_octal() {
        return None;
    }
    if format.is_words() && bytes.last() == Some(&0) {
        // The pad byte of a dump of an odd number of bytes
        bytes.pop();
    }
    // A text file ends in a line break, which `ciphey -f` leaves out of a file it reads
    // too, and which would stop Base64 inside the dump from decoding. Bytes that aren't
    // UTF-8, like compressed data, are kept as they are.
    if std::str::from_utf8(&bytes).is_ok() {
        let end = bytes
            .iter()
            .rposition(|&byte| !matches!(byte, b'\n' | b'\r'))
            .map_or(0, |last| last + 1);
        bytes.truncate(end);
    }
    (bytes.len() >= MIN_BYTES).then_some(bytes)
}

/// What the groups of a dump hold.
#[derive(Clone, Copy, PartialEq)]
enum Format {
    /// Bytes in hex, in order, one or more per group: xxd, `hexdump -C`, `od -t x1`
    HexBytes,
    /// 16-bit little-endian words, 4 hex digits each: plain `hexdump`, `od -x`
    HexWords,
    /// Bytes, 3 octal digits each: `od -b`, `hexdump -b`
    OctalBytes,
    /// 16-bit little-endian words, 6 octal digits each: plain `od`, `hexdump -o`
    OctalWords,
}

impl Format {
    /// The format of a dump whose first group has `digits` digits. xxd (with a colon) only
    /// writes hex bytes. 32-bit words without a colon (`od -t x4`) are out of scope: they
    /// are in the byte order of the machine that wrote them.
    fn from_first_group(digits: usize, colon: bool) -> Option<Format> {
        match (digits, colon) {
            (2 | 4 | 8, true) | (2, false) => Some(Format::HexBytes),
            (4, false) => Some(Format::HexWords),
            (3, false) => Some(Format::OctalBytes),
            (6, false) => Some(Format::OctalWords),
            _ => None,
        }
    }

    /// Whether the groups are octal.
    fn is_octal(self) -> bool {
        matches!(self, Format::OctalBytes | Format::OctalWords)
    }

    /// Whether the groups are 16-bit words, whose last one is padded with a zero byte when
    /// the dump has an odd number of bytes.
    fn is_words(self) -> bool {
        matches!(self, Format::HexWords | Format::OctalWords)
    }
}

/// Appends the bytes `group`, a run of hex digits, stands for. Returns false when it is an
/// octal group with a digit that isn't octal or a value too big for its size.
fn push_group(bytes: &mut Vec<u8>, group: &[u8], format: Format) -> bool {
    match format {
        Format::HexBytes | Format::HexWords => {
            // Groups have an even number of digits, so nothing is left over
            let (pairs, _) = group.as_chunks::<2>();
            bytes.extend(
                pairs
                    .iter()
                    .map(|&[high, low]| (hex_value(high) << 4) | hex_value(low)),
            );
            if format == Format::HexWords {
                // A little-endian 16-bit word: `7053` is the bytes `53 70`
                let len = bytes.len();
                bytes.swap(len - 2, len - 1);
            }
        }
        Format::OctalBytes | Format::OctalWords => {
            if !group.iter().all(|digit| (b'0'..=b'7').contains(digit)) {
                return false;
            }
            let value = parse_digits(group, 8);
            if format == Format::OctalBytes {
                let Ok(byte) = u8::try_from(value) else {
                    return false;
                };
                bytes.push(byte);
            } else {
                // `062510` is the word 0x6548, the bytes `48 65`
                let Ok(word) = u16::try_from(value) else {
                    return false;
                };
                bytes.extend(word.to_le_bytes());
            }
        }
    }
    true
}

/// The value of a run of at most 8 digits in base 16 or 8. Callers only pass digits.
fn parse_digits(digits: &[u8], radix: u32) -> u32 {
    digits.iter().fold(0, |value, &digit| {
        value * radix + u32::from(hex_value(digit))
    })
}

/// The cheap first check, which rejects almost every input that isn't a dump within its
/// first nine bytes, without allocating: the text has to start with an offset of 6 to 8
/// hex digits followed by `:` or a space. Returns the number of digits.
fn first_offset_digits(text: &[u8]) -> Option<usize> {
    let digits = text
        .iter()
        .take(MAX_OFFSET_DIGITS + 1)
        .take_while(|byte| byte.is_ascii_hexdigit())
        .count();
    if !(MIN_OFFSET_DIGITS..=MAX_OFFSET_DIGITS).contains(&digits) {
        return None;
    }
    matches!(text.get(digits), Some(b':' | b' ')).then_some(digits)
}

/// Splits a line into its offset, which has to be `digits` hex digits like the first
/// line's, and the rest of the line.
fn split_offset(line: &[u8], digits: usize) -> Option<(u32, &[u8])> {
    let (offset, rest) = line.split_at_checked(digits)?;
    if !offset.iter().all(u8::is_ascii_hexdigit) || rest.first().is_some_and(u8::is_ascii_hexdigit)
    {
        return None;
    }
    let offset = parse_digits(offset, 16);
    Some((offset, rest))
}

/// The value of an ASCII hex digit. Callers only pass hex digits.
fn hex_value(digit: u8) -> u8 {
    match digit {
        b'0'..=b'9' => digit - b'0',
        b'a'..=b'f' => digit - b'a' + 10,
        b'A'..=b'F' => digit - b'A' + 10,
        _ => 0,
    }
}

#[cfg(test)]
mod tests {
    use super::{decode_hexdump, HexdumpDecoder};
    use crate::checkers::athena::Athena;
    use crate::checkers::checker_type::{Check, Checker};
    use crate::checkers::CheckerTypes;
    use crate::decoders::gzip_decoder::GzipDecoder;
    use crate::decoders::interface::{Crack, Decoder};
    use crate::decoders::{DecoderType, DECODER_MAP};
    use crate::filtration_system::get_decoder_by_name;

    // Every dump here was written by the named tool (xxd 2026-06-16, hexdump from
    // util-linux 2.37.4, od from GNU coreutils 8.32) from the plaintext next to it. The xxd
    // ones decode back with `xxd -r`; the byte-order ones (xxd, hexdump -C, od -t x1) with
    // CyberChef's "From Hexdump" too. CyberChef ignores the word order of plain hexdump
    // and od -x, so those are checked against the file that was dumped.

    const SPHINX: &str = "Sphinx of black quartz, judge my vow.";
    const LIGHTHOUSE: &str =
        "Meet me at the old lighthouse after midnight and bring the map, the key and a torch.";

    /// `xxd`, the example in https://github.com/bee-san/Ciphey/issues/946. Line 1 ends in
    /// a space, as xxd writes it.
    const XXD_SPHINX: &str = "\
00000000: 5370 6869 6e78 206f 6620 626c 6163 6b20  Sphinx of black \n\
00000010: 7175 6172 747a 2c20 6a75 6467 6520 6d79  quartz, judge my\n\
00000020: 2076 6f77 2e                              vow.\n";

    /// `hexdump -C`
    const HEXDUMP_C_SPHINX: &str = "\
00000000  53 70 68 69 6e 78 20 6f  66 20 62 6c 61 63 6b 20  |Sphinx of black |\n\
00000010  71 75 61 72 74 7a 2c 20  6a 75 64 67 65 20 6d 79  |quartz, judge my|\n\
00000020  20 76 6f 77 2e                                    | vow.|\n\
00000025\n";

    /// `od -A x -t x1z`
    const OD_Z_SPHINX: &str = "\
000000 53 70 68 69 6e 78 20 6f 66 20 62 6c 61 63 6b 20  >Sphinx of black <\n\
000010 71 75 61 72 74 7a 2c 20 6a 75 64 67 65 20 6d 79  >quartz, judge my<\n\
000020 20 76 6f 77 2e                                   > vow.<\n\
000025\n";

    /// `xxd` of `Hello, World!`
    const XXD_HELLO: &str = "00000000: 4865 6c6c 6f2c 2057 6f72 6c64 21         Hello, World!\n";

    /// Plain `hexdump`: little-endian 16-bit words. The last data line is padded with spaces.
    const HEXDUMP_LIGHTHOUSE: &str = "\
0000000 654d 7465 6d20 2065 7461 7420 6568 6f20\n\
0000010 646c 6c20 6769 7468 6f68 7375 2065 6661\n\
0000020 6574 2072 696d 6e64 6769 7468 6120 646e\n\
0000030 6220 6972 676e 7420 6568 6d20 7061 202c\n\
0000040 6874 2065 656b 2079 6e61 2064 2061 6f74\n\
0000050 6372 2e68                              \n\
0000054\n";

    /// `od -t x1`: octal offsets and no ASCII column
    const OD_X1_LIGHTHOUSE: &str = "\
0000000 4d 65 65 74 20 6d 65 20 61 74 20 74 68 65 20 6f\n\
0000020 6c 64 20 6c 69 67 68 74 68 6f 75 73 65 20 61 66\n\
0000040 74 65 72 20 6d 69 64 6e 69 67 68 74 20 61 6e 64\n\
0000060 20 62 72 69 6e 67 20 74 68 65 20 6d 61 70 2c 20\n\
0000100 74 68 65 20 6b 65 79 20 61 6e 64 20 61 20 74 6f\n\
0000120 72 63 68 2e\n\
0000124\n";

    /// `xxd` of the Base64 of the lighthouse sentence (`base64 -w0`)
    const XXD_BASE64: &str = "\
00000000: 5457 566c 6443 4274 5a53 4268 6443 4230  TWVldCBtZSBhdCB0\n\
00000010: 6147 5567 6232 786b 4947 7870 5a32 6830  aGUgb2xkIGxpZ2h0\n\
00000020: 6147 3931 6332 5567 5957 5a30 5a58 4967  aG91c2UgYWZ0ZXIg\n\
00000030: 6257 6c6b 626d 6c6e 6148 5167 5957 356b  bWlkbmlnaHQgYW5k\n\
00000040: 4947 4a79 6157 356e 4948 526f 5a53 4274  IGJyaW5nIHRoZSBt\n\
00000050: 5958 4173 4948 526f 5a53 4272 5a58 6b67  YXAsIHRoZSBrZXkg\n\
00000060: 5957 356b 4947 4567 6447 3979 5932 6775  YW5kIGEgdG9yY2gu\n";

    /// The Base64 of the lighthouse sentence
    const LIGHTHOUSE_BASE64: &str = "TWVldCBtZSBhdCB0aGUgb2xkIGxpZ2h0aG91c2UgYWZ0ZXIgbWlkbmlnaHQgYW5kIGJyaW5nIHRoZSBtYXAsIHRoZSBrZXkgYW5kIGEgdG9yY2gu";

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    // Runs the decoder with the Athena checker and returns the decoded text, if any
    fn crack(text: &str) -> Option<String> {
        let decoder = Decoder::<HexdumpDecoder>::new();
        let result = decoder.crack(text, &get_athena_checker());
        if result.unencrypted_text.is_none() {
            assert!(!result.success, "{text:?} failed but was marked successful");
        }
        result.unencrypted_text.map(|texts| texts[0].clone())
    }

    #[test]
    fn decodes_the_issue_example() {
        // https://github.com/bee-san/Ciphey/issues/946
        assert_eq!(crack(XXD_SPHINX).unwrap(), SPHINX);
    }

    #[test]
    fn decodes_hexdump_canonical() {
        assert_eq!(crack(HEXDUMP_C_SPHINX).unwrap(), SPHINX);
    }

    #[test]
    fn decodes_od_with_ascii_column() {
        assert_eq!(crack(OD_Z_SPHINX).unwrap(), SPHINX);
    }

    #[test]
    fn decodes_one_line_xxd() {
        let decoder = Decoder::<HexdumpDecoder>::new();
        let result = decoder.crack(XXD_HELLO, &get_athena_checker());
        assert!(result.success, "Athena should accept the plaintext");
        assert_eq!(result.unencrypted_text.unwrap()[0], "Hello, World!");
    }

    #[test]
    fn decodes_plain_hexdump_words() {
        let decoder = Decoder::<HexdumpDecoder>::new();
        let result = decoder.crack(HEXDUMP_LIGHTHOUSE, &get_athena_checker());
        assert!(result.success, "Athena should accept the plaintext");
        assert_eq!(result.unencrypted_text.unwrap()[0], LIGHTHOUSE);
    }

    #[test]
    fn decodes_od_t_x1_with_octal_offsets() {
        let decoder = Decoder::<HexdumpDecoder>::new();
        let result = decoder.crack(OD_X1_LIGHTHOUSE, &get_athena_checker());
        assert!(result.success, "Athena should accept the plaintext");
        assert_eq!(result.unencrypted_text.unwrap()[0], LIGHTHOUSE);
    }

    #[test]
    fn decodes_xxd_of_base64() {
        assert_eq!(crack(XXD_BASE64).unwrap(), LIGHTHOUSE_BASE64);
    }

    #[test]
    fn drops_the_pad_byte_of_an_odd_length_word_dump() {
        // hexdump of `Hello, World!`: 13 bytes, so the last word is `!` and a 00 pad byte
        let dump = "0000000 6548 6c6c 2c6f 5720 726f 646c 0021     \n000000d\n";
        assert_eq!(crack(dump).unwrap(), "Hello, World!");
        // hexdump -x writes the same words further apart
        let dump =
            "0000000    6548    6c6c    2c6f    5720    726f    646c    0021        \n000000d\n";
        assert_eq!(crack(dump).unwrap(), "Hello, World!");
    }

    #[test]
    fn decodes_od_words() {
        // od -x and od -t x2 print the same thing: words, octal offsets, and a pad byte
        let dump = "\
0000000 7053 6968 786e 6f20 2066 6c62 6361 206b\n\
0000020 7571 7261 7a74 202c 756a 6764 2065 796d\n\
0000040 7620 776f 002e\n\
0000045\n";
        assert_eq!(crack(dump).unwrap(), SPHINX);
    }

    #[test]
    fn decodes_octal_bytes() {
        // od -b and od -t o1
        let dump = "\
0000000 123 160 150 151 156 170 040 157 146 040 142 154 141 143 153 040\n\
0000020 161 165 141 162 164 172 054 040 152 165 144 147 145 040 155 171\n\
0000040 040 166 157 167 056\n\
0000045\n";
        assert_eq!(crack(dump).unwrap(), SPHINX);
        // hexdump -b, which pads the last data line and ends in a hex offset
        let dump = "\
0000000 123 160 150 151 156 170 040 157 146 040 142 154 141 143 153 040\n\
0000010 161 165 141 162 164 172 054 040 152 165 144 147 145 040 155 171\n\
0000020 040 166 157 167 056                                            \n\
0000025\n";
        assert_eq!(crack(dump).unwrap(), SPHINX);
        // od -A x -t o1z
        let dump = "\
000000 123 160 150 151 156 170 040 157 146 040 142 154 141 143 153 040  >Sphinx of black <\n\
000010 161 165 141 162 164 172 054 040 152 165 144 147 145 040 155 171  >quartz, judge my<\n\
000020 040 166 157 167 056                                              > vow.<\n\
000025\n";
        assert_eq!(crack(dump).unwrap(), SPHINX);
    }

    #[test]
    fn decodes_octal_words() {
        // Plain od (od -o, od -t o2): little-endian 16-bit words in octal, and a pad byte
        let dump = "\
0000000 070123 064550 074156 067440 020146 066142 061541 020153\n\
0000020 072561 071141 075164 020054 072552 063544 020145 074555\n\
0000040 073040 073557 000056\n\
0000045\n";
        assert_eq!(crack(dump).unwrap(), SPHINX);
        // hexdump -o
        let dump = "\
0000000  070123  064550  074156  067440  020146  066142  061541  020153\n\
0000010  072561  071141  075164  020054  072552  063544  020145  074555\n\
0000020  073040  073557  000056                                        \n\
0000025\n";
        assert_eq!(crack(dump).unwrap(), SPHINX);
    }

    #[test]
    fn decodes_the_internetwache_od_dump() {
        // Internetwache CTF 2016, misc50 "The hidden message": plain `od -b` output of a
        // Base64 string and its line break.
        // https://raw.githubusercontent.com/internetwache/Internetwache-CTF-2016/master/tasks/misc50/task/README.txt
        let dump = "\
0000000 126 062 126 163 142 103 102 153 142 062 065 154 111 121 157 113\n\
0000020 122 155 170 150 132 172 157 147 123 126 144 067 124 152 102 146\n\
0000040 115 107 065 154 130 062 116 150 142 154 071 172 144 104 102 167\n\
0000060 130 063 153 167 144 130 060 113 012\n\
0000071";
        assert_eq!(
            crack(dump).unwrap(),
            "V2VsbCBkb25lIQoKRmxhZzogSVd7TjBfMG5lX2Nhbl9zdDBwX3kwdX0K"
        );
    }

    #[test]
    fn drops_line_breaks_at_the_end_of_text() {
        // `printf 'Hello, World!\r\n\n' | xxd`: as `ciphey -f` reads a file
        let dump = "00000000: 4865 6c6c 6f2c 2057 6f72 6c64 210d 0a0a  Hello, World!...\n";
        assert_eq!(crack(dump).unwrap(), "Hello, World!");
        // Line breaks inside the text stay
        let dump = "00000000: 4869 0a74 6865 7265 0a                   Hi.there.\n";
        assert_eq!(crack(dump).unwrap(), "Hi\nthere");
        // `echo hi | xxd` is only two bytes of text
        assert_eq!(
            crack("00000000: 6869 0a                                  hi.\n"),
            None
        );
    }

    #[test]
    fn decodes_octal_text_of_only_zeros_and_ones() {
        // `HAHA` is 110 101 110 101 in octal, which xxd -b's check mustn't reject
        assert_eq!(
            crack("0000000 110 101 110 101 041\n0000005\n").unwrap(),
            "HAHA!"
        );
    }

    #[test]
    fn decodes_od_with_decimal_offsets() {
        // od -A d -t x1
        let dump = "\
0000000 53 70 68 69 6e 78 20 6f 66 20 62 6c 61 63 6b 20\n\
0000016 71 75 61 72 74 7a 2c 20 6a 75 64 67 65 20 6d 79\n\
0000032 20 76 6f 77 2e\n\
0000037\n";
        assert_eq!(crack(dump).unwrap(), SPHINX);
    }

    #[test]
    fn decodes_xxd_group_sizes() {
        // xxd -g1
        let dump = "\
00000000: 53 70 68 69 6e 78 20 6f 66 20 62 6c 61 63 6b 20  Sphinx of black \n\
00000010: 71 75 61 72 74 7a 2c 20 6a 75 64 67 65 20 6d 79  quartz, judge my\n\
00000020: 20 76 6f 77 2e                                    vow.\n";
        assert_eq!(crack(dump).unwrap(), SPHINX);
        // xxd -g4, whose last group has 2 digits
        let dump = "\
00000000: 53706869 6e78206f 6620626c 61636b20  Sphinx of black \n\
00000010: 71756172 747a2c20 6a756467 65206d79  quartz, judge my\n\
00000020: 20766f77 2e                           vow.\n";
        assert_eq!(crack(dump).unwrap(), SPHINX);
    }

    #[test]
    fn decodes_xxd_uppercase() {
        // xxd -u
        let dump = "\
00000000: 5370 6869 6E78 206F 6620 626C 6163 6B20  Sphinx of black \n\
00000010: 7175 6172 747A 2C20 6A75 6467 6520 6D79  quartz, judge my\n\
00000020: 2076 6F77 2E                              vow.\n";
        assert_eq!(crack(dump).unwrap(), SPHINX);
    }

    #[test]
    fn decodes_other_line_widths() {
        // xxd -c8
        let dump = "\
00000000: 5370 6869 6e78 206f  Sphinx o\n\
00000008: 6620 626c 6163 6b20  f black \n\
00000010: 7175 6172 747a 2c20  quartz, \n\
00000018: 6a75 6467 6520 6d79  judge my\n\
00000020: 2076 6f77 2e          vow.\n";
        assert_eq!(crack(dump).unwrap(), SPHINX);
        // xxd -c32
        let dump = "\
00000000: 5370 6869 6e78 206f 6620 626c 6163 6b20 7175 6172 747a 2c20 6a75 6467 6520 6d79  Sphinx of black quartz, judge my\n\
00000020: 2076 6f77 2e                                                                      vow.\n";
        assert_eq!(crack(dump).unwrap(), SPHINX);
        // od -A x -t x1z -w8
        let dump = "\
000000 53 70 68 69 6e 78 20 6f  >Sphinx o<\n\
000008 66 20 62 6c 61 63 6b 20  >f black <\n\
000010 71 75 61 72 74 7a 2c 20  >quartz, <\n\
000018 6a 75 64 67 65 20 6d 79  >judge my<\n\
000020 20 76 6f 77 2e           > vow.<\n\
000025\n";
        assert_eq!(crack(dump).unwrap(), SPHINX);
    }

    #[test]
    fn decodes_a_dump_that_does_not_start_at_zero() {
        // xxd -s 4
        let dump = "\
00000004: 6e78 206f 6620 626c 6163 6b20 7175 6172  nx of black quar\n\
00000014: 747a 2c20 6a75 6467 6520 6d79 2076 6f77  tz, judge my vow\n\
00000024: 2e                                       .\n";
        assert_eq!(crack(dump).unwrap(), "nx of black quartz, judge my vow.");
    }

    #[test]
    fn ignores_hex_and_pipes_in_the_ascii_column() {
        // The dumped text is `deadbeef cafe babe|ab cd|`
        let expected = "deadbeef cafe babe|ab cd|";
        let xxd = "\
00000000: 6465 6164 6265 6566 2063 6166 6520 6261  deadbeef cafe ba\n\
00000010: 6265 7c61 6220 6364 7c                   be|ab cd|\n";
        assert_eq!(crack(xxd).unwrap(), expected);
        let hexdump_c = "\
00000000  64 65 61 64 62 65 65 66  20 63 61 66 65 20 62 61  |deadbeef cafe ba|\n\
00000010  62 65 7c 61 62 20 63 64  7c                       |be|ab cd||\n\
00000019\n";
        assert_eq!(crack(hexdump_c).unwrap(), expected);
        let od_z = "\
000000 64 65 61 64 62 65 65 66 20 63 61 66 65 20 62 61  >deadbeef cafe ba<\n\
000010 62 65 7c 61 62 20 63 64 7c                       >be|ab cd|<\n\
000019\n";
        assert_eq!(crack(od_z).unwrap(), expected);
    }

    #[test]
    fn decodes_crlf_line_endings() {
        let dump = XXD_SPHINX.replace('\n', "\r\n");
        assert_eq!(crack(&dump).unwrap(), SPHINX);
        let dump = HEXDUMP_C_SPHINX.replace('\n', "\r\n");
        assert_eq!(crack(&dump).unwrap(), SPHINX);
    }

    #[test]
    fn ignores_blank_lines_around_the_dump() {
        let dump = format!("\n\n{HEXDUMP_C_SPHINX}\n   \n");
        assert_eq!(crack(&dump).unwrap(), SPHINX);
    }

    #[test]
    fn keeps_bytes_that_are_not_text() {
        // `printf Hello | gzip -n | xxd`. There is no control-character check, so the bytes
        // reach the Gzip decoder as Latin-1 text, which it reads back as bytes.
        let dump = "\
00000000: 1f8b 0800 0000 0000 0003 f348 cdc9 c907  ...........H....\n\
00000010: 0082 89d1 f705 0000 00                   .........\n";
        assert_eq!(
            decode_hexdump(dump).unwrap(),
            [
                0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0xf3, 0x48, 0xcd, 0xc9,
                0xc9, 0x07, 0x00, 0x82, 0x89, 0xd1, 0xf7, 0x05, 0x00, 0x00, 0x00
            ]
        );
        let gzip = crack(dump).unwrap();
        assert!(gzip.starts_with("\u{1f}\u{8b}\u{8}\0"), "{gzip:?}");
        let gunzipped = Decoder::<GzipDecoder>::new().crack(&gzip, &get_athena_checker());
        assert_eq!(gunzipped.unencrypted_text.unwrap()[0], "Hello");
    }

    #[test]
    fn decodes_utf8() {
        // xxd of `café ☕`
        let dump = "00000000: 6361 66c3 a920 e298 95                   caf.. ...\n"; // codespell:ignore caf
        assert_eq!(crack(dump).unwrap(), "café ☕");
    }

    #[test]
    fn fails_on_text_that_is_not_a_dump() {
        // The bench `miss` input
        assert_eq!(
            crack("T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV"),
            None
        );
        assert_eq!(crack("hello world"), None);
        assert_eq!(crack("hello my name is panicky mc panic face!"), None);
        assert_eq!(crack("deface the facade"), None);
        assert_eq!(crack(LIGHTHOUSE_BASE64), None);
        assert_eq!(
            crack("bc26a681 feat(decoders): add Punycode / IDNA decoder"),
            None
        );
    }

    #[test]
    fn fails_on_hex_without_offsets() {
        // These are Hexadecimal's
        assert_eq!(crack("48 65 6c 6c 6f 20 77 6f 72 6c 64"), None);
        assert_eq!(crack("4865 6c6c 6f20 776f 726c 6421"), None);
        assert_eq!(crack("48656c6c 6f20776f 726c6421"), None);
        assert_eq!(
            crack("537068696e78206f6620626c61636b2071756172747a2c206a75646765206d7920766f772e"),
            None
        );
        // od -A n -t x1
        assert_eq!(
            crack(" 53 70 68 69 6e 78 20 6f 66 20 62 6c 61 63 6b 20\n 71 75 61 72 74 7a 2c 20"),
            None
        );
    }

    #[test]
    fn fails_on_od_c() {
        let dump = "\
0000000   S   p   h   i   n   x       o   f       b   l   a   c   k    \n\
0000020   q   u   a   r   t   z   ,       j   u   d   g   e       m   y\n\
0000040       v   o   w   .\n\
0000045\n";
        assert_eq!(crack(dump), None);
        // Letters that are hex digits are still one digit, not a byte
        assert_eq!(crack("0000000   a   b   c   d   e   f\n0000006\n"), None);
    }

    #[test]
    fn fails_on_xxd_bits() {
        // xxd -b: 8 binary digits per byte read like 8-digit hex groups
        let dump = "\
00000000: 01010011 01110000 01101000 01101001 01101110 01111000  Sphinx\n\
00000006: 00100000 01101111 01100110 00100000 01100010 01101100   of bl\n\
0000000c: 01100001 01100011 01101011 00100000 01110001 01110101  ack qu\n\
00000012: 01100001 01110010 01110100 01111010 00101100 00100000  artz, \n\
00000018: 01101010 01110101 01100100 01100111 01100101 00100000  judge \n\
0000001e: 01101101 01111001 00100000 01110110 01101111 01110111  my vow\n\
00000024: 00101110                                               .\n";
        assert_eq!(crack(dump), None);
    }

    #[test]
    fn fails_on_unsupported_group_sizes() {
        // od -t x4: 32-bit words in host byte order
        let dump = "\
0000000 69687053 6f20786e 6c622066 206b6361\n\
0000020 72617571 202c7a74 6764756a 796d2065\n\
0000040 776f7620 0000002e\n\
0000045\n";
        assert_eq!(crack(dump), None);
        // od -t o4
        assert_eq!(
            crack("0000000 15433062510 12710026157 14433071157 00000000041\n0000015\n"),
            None
        );
        // od -d and od -t d1: decimal words and bytes
        assert_eq!(
            crack("0000000 25928 27756 11375 22304 29295 25708    33\n0000015\n"),
            None
        );
        assert_eq!(
            crack("0000000   72  101  108  108  111   44   32   87  111  114  108  100   33\n0000015\n"),
            None
        );
        // xxd -g3
        assert_eq!(
            crack("00000000: 537068 696e78 206f66 20626c 61636b 20  Sphinx of black \n"),
            None
        );
        // xxd -g8
        assert_eq!(
            crack("00000000: 537068696e78206f 6620626c61636b20  Sphinx of black \n"),
            None
        );
    }

    #[test]
    fn fails_on_groups_that_are_not_octal() {
        // 3- and 6-digit groups are octal, so a digit above 7 or a value too big fails
        assert_eq!(crack("0000000 123 158 150 151\n0000004\n"), None);
        assert_eq!(crack("0000000 123 400 150 151\n0000004\n"), None);
        assert_eq!(crack("0000000 070123 200000 074156\n0000006\n"), None);
        assert_eq!(crack("0000000 abc def 123\n0000003\n"), None);
        // Numbers that only look like a dump
        assert_eq!(crack("5551234 555 1234"), None);
    }

    #[test]
    fn fails_on_squeezed_lines() {
        // hexdump -C writes `*` for lines that repeat the one above, so bytes are missing
        let dump = "\
00000000  41 41 41 41 41 41 41 41  41 41 41 41 41 41 41 41  |AAAAAAAAAAAAAAAA|\n\
*\n\
00000050  41 41 41 41 41 41 41 41  41 41 41 41 0a           |AAAAAAAAAAAA.|\n\
0000005d\n";
        assert_eq!(crack(dump), None);
    }

    #[test]
    fn fails_on_a_short_group_before_the_last_line() {
        assert_eq!(crack("00000000: 4865 6c\n00000003: 6c6f"), None);
        // or before the last group of its line
        assert_eq!(crack("00000000: 4865 6c 6c6f  Hello"), None);
        // and it has to be whole bytes
        assert_eq!(crack("00000000: 4865 6c6c 6"), None);
    }

    #[test]
    fn fails_on_mixed_colon_and_no_colon_lines() {
        let dump = "\
00000000: 5370 6869 6e78 206f 6620 626c 6163 6b20  Sphinx of black \n\
00000010 7175 6172 747a 2c20 6a75 6467 6520 6d79\n";
        assert_eq!(crack(dump), None);
        let dump = "\
0000000 7053 6968 786e 6f20 2066 6c62 6361 206b\n\
0000020: 7571 7261 7a74 202c 756a 6764 2065 796d\n";
        assert_eq!(crack(dump), None);
    }

    #[test]
    fn fails_when_offsets_do_not_increase() {
        let dump = "\
00000010: 5370 6869 6e78 206f 6620 626c 6163 6b20  Sphinx of black \n\
00000000: 7175 6172 747a 2c20 6a75 6467 6520 6d79  quartz, judge my\n";
        assert_eq!(crack(dump), None);
        let dump = "\
00000000: 5370 6869 6e78 206f 6620 626c 6163 6b20  Sphinx of black \n\
00000000: 7175 6172 747a 2c20 6a75 6467 6520 6d79  quartz, judge my\n";
        assert_eq!(crack(dump), None);
    }

    #[test]
    fn fails_when_offsets_change_width() {
        let dump = "\
0000000 4d 65 65 74 20 6d 65 20\n\
00000010 61 74 20 74 68 65 20 6f\n";
        assert_eq!(crack(dump), None);
    }

    #[test]
    fn fails_when_line_lengths_do_not_fit() {
        // A line longer than the first
        let dump = "\
00000000: 4d65 6574  Meet\n\
00000004: 206d 6520 6174  me at\n";
        assert_eq!(crack(dump), None);
        // A full line after a short one
        let dump = "\
0000000 4d 65 65 74 20 6d 65 20\n\
0000010 61 74 20\n\
0000020 74 68 65 20 6f 6c 64 20\n";
        assert_eq!(crack(dump), None);
    }

    #[test]
    fn fails_when_the_offset_line_is_not_last() {
        let dump = "\
0000000 4d 65 65 74 20 6d 65 20\n\
0000010\n\
0000020 61 74 20 74 68 65 20 6f\n";
        assert_eq!(crack(dump), None);
    }

    #[test]
    fn fails_on_lines_without_groups() {
        assert_eq!(crack("00000000:\n00000010:"), None);
        assert_eq!(crack("00000000: |Hello|"), None);
        assert_eq!(crack("00000000  |Hello|"), None);
        assert_eq!(crack("0000000 4d 65 65\n0000003 |abc|\n"), None);
    }

    #[test]
    fn fails_on_fewer_than_three_bytes() {
        // xxd and hexdump of `hi`
        assert_eq!(
            crack("00000000: 6869                                     hi\n"),
            None
        );
        assert_eq!(
            crack("0000000 6968                                   \n0000002\n"),
            None
        );
    }

    #[test]
    fn rejects_hex_words_that_only_look_like_a_dump() {
        // Parses (offset deadbeef, two words), but the bytes aren't text
        let decoder = Decoder::<HexdumpDecoder>::new();
        let result = decoder.crack("deadbeef: cafe babe", &get_athena_checker());
        assert!(!result.success);
    }

    #[test]
    fn little_endian_xxd_is_out_of_scope() {
        // xxd -e writes little-endian 32-bit words, which look like xxd -g4. The bytes
        // come out in the wrong order and the checker rejects them.
        let dump = "\
00000000: 69687053 6f20786e 6c622066 206b6361  Sphinx of black \n\
00000010: 72617571 202c7a74 6764756a 796d2065  quartz, judge my\n\
00000020: 776f7620       2e                     vow.\n";
        let decoder = Decoder::<HexdumpDecoder>::new();
        let result = decoder.crack(dump, &get_athena_checker());
        assert!(!result.success);
        assert_ne!(result.unencrypted_text.unwrap()[0], SPHINX);
    }

    #[test]
    fn handles_panic_if_empty_string() {
        assert_eq!(crack(""), None);
    }

    #[test]
    fn handles_panic_if_whitespace() {
        assert_eq!(crack(" \n\t\r\n "), None);
    }

    #[test]
    fn handles_panic_if_emoji() {
        assert_eq!(crack("😀"), None);
        assert_eq!(crack("00000000: 😀"), None);
        assert_eq!(crack("00000000: 4865 6c6c 6f😀"), None);
    }

    #[test]
    fn is_registered() {
        // Exactly one decoder by that name runs in the search
        let decoders = get_decoder_by_name("Hexdump");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Hexdump");
        // Cached results name the decoder; reading them back looks it up here
        let decoder = DECODER_MAP
            .get("Hexdump")
            .expect("Hexdump should be in DECODER_MAP")
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "Hexdump");
    }
}
