//! Decode HTML entities (HTML/XML character references)
//! Performs error handling and returns a string
//! Call html_entity_decoder.crack to use. It returns a `CrackResult`; check
//! `result.unencrypted_text.is_some()` to see if it decoded anything.
//!
//! Three forms are decoded, each of which has to end with `;`:
//! * decimal references, `&#72;`
//! * hexadecimal references, `&#x48;` or `&#X48;`
//! * the named references of the WHATWG list, such as `&amp;`, `&eacute;` and `&hearts;`
//!
//! The input may be fully or only partly encoded (`Fish &amp; Chips`). One call decodes
//! one layer, so `&amp;lt;` becomes `&lt;`; the search applies the decoder again for
//! double-escaped text.
//!
//! Some references are deliberately not decoded:
//! * legacy references without the trailing `;` (`&lt`, `&#72&#105`). Browsers and Python's
//!   `html.unescape` accept them, but they would match too much ordinary text.
//! * references to invalid code points (`&#0;`, `&#xD800;`, `&#1114112;`) are left as they are.
//! * output containing control characters other than tab, carriage return and newline is
//!   rejected. This includes `&#128;` to `&#159;`, which browsers remap to Windows-1252
//!   characters but which decode to C1 control characters here.
//!
//! References: <https://html.spec.whatwg.org/multipage/named-characters.html> and
//! <https://html.spec.whatwg.org/multipage/syntax.html#character-references>

use std::borrow::Cow;

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The HTML entity decoder, call:
/// `let html_entity_decoder = Decoder::<HtmlEntityDecoder>::new()` to create a new instance
/// And then call:
/// `result = html_entity_decoder.crack(input)` to decode HTML entities
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::html_entity_decoder::HtmlEntityDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_html_entities = Decoder::<HtmlEntityDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_html_entities.crack("&lt;b&gt;Tom &amp; Jerry&lt;/b&gt; say &quot;hi&quot;", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "<b>Tom & Jerry</b> say \"hi\"");
/// ```
pub struct HtmlEntityDecoder;

impl Crack for Decoder<HtmlEntityDecoder> {
    fn new() -> Decoder<HtmlEntityDecoder> {
        Decoder {
            name: "HTML Entities",
            description: "HTML entities, or character references, write a character in HTML or XML as a name (&amp;), a decimal code point (&#38;) or a hexadecimal code point (&#x26;) between an ampersand and a semicolon. They escape characters that have a meaning in markup, such as < and &, and characters that are hard to type.",
            link: "https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references",
            tags: vec!["html_entity", "html", "web", "decoder"],
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns a `CrackResult` holding the decoded text if it was successful
    /// Else `unencrypted_text` is `None` and the reason is logged
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying HTML entities with text {:?}", text);
        let decoded_text: Option<String> = decode_html_entities_no_error_handling(text);

        trace!("Decoded text for HTML entities: {:?}", decoded_text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decoded_text else {
            debug!("Failed to decode HTML entities because the text holds no character reference that decodes to printable text");
            return results;
        };

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode HTML entities because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);

        results.update_checker(&checker_result);

        results
    }
    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// The longest named reference is `&CounterClockwiseContourIntegral;`, with 31 characters
/// between the `&` and the `;`.
const MAX_NAME_LEN: usize = 31;

/// Decodes one layer of HTML entities.
///
/// Returns `None` when there is nothing to decode or when the decoded text contains a
/// control character other than tab, carriage return or newline. The search runs every
/// decoder on every text it finds, so the cheap checks come first:
/// 1. [`contains_reference_shape`] finds each `&` with `memchr` and looks at the bytes after
///    it. Text without an `&` (almost all text), or whose `&`s don't start something shaped
///    like a reference (`AT&T`, `Tom & Jerry;`), is rejected without looking up any name.
/// 2. html-escape decodes the references and returns `Cow::Borrowed`, without allocating,
///    when none of them is real (`&bogus;`, `&#0;`).
fn decode_html_entities_no_error_handling(text: &str) -> Option<String> {
    if !contains_reference_shape(text) {
        return None;
    }

    let Cow::Owned(decoded_text) = html_escape::decode_html_entities(text) else {
        return None;
    };

    // `&#127;`, `&#12;` and the C1 range `&#128;` to `&#159;` decode to control characters,
    // which plaintext doesn't contain.
    if decoded_text
        .chars()
        .any(|c| c.is_control() && !matches!(c, '\t' | '\n' | '\r'))
    {
        return None;
    }

    Some(decoded_text)
}

/// Whether some `&` in `text` starts something shaped like a character reference: `&#` and
/// decimal digits, `&#x` or `&#X` and hex digits, or `&`, a letter and at most 30 more letters
/// and digits, followed by `;`. html-escape decodes nothing else; the test
/// `reference_shape_check_keeps_everything_html_escape_decodes` checks this.
///
/// The number of digits isn't limited: `&#0000072;` is a valid reference to `H`.
fn contains_reference_shape(text: &str) -> bool {
    let bytes = text.as_bytes();
    text.match_indices('&')
        .any(|(index, _)| starts_with_reference_body(&bytes[index + 1..]))
}

/// Whether `rest`, the bytes after an `&`, start with the body of a reference and its `;`.
fn starts_with_reference_body(rest: &[u8]) -> bool {
    let (digits, is_digit): (&[u8], fn(&u8) -> bool) = match rest {
        [b'#', b'x' | b'X', digits @ ..] => (digits, u8::is_ascii_hexdigit),
        [b'#', digits @ ..] => (digits, u8::is_ascii_digit),
        [first, name @ ..] if first.is_ascii_alphabetic() => {
            let len = name
                .iter()
                .take(MAX_NAME_LEN)
                .take_while(|b| b.is_ascii_alphanumeric())
                .count();
            return len < MAX_NAME_LEN && name.get(len) == Some(&b';');
        }
        _ => return false,
    };
    let len = digits.iter().take_while(|b| is_digit(b)).count();
    len > 0 && digits.get(len) == Some(&b';')
}

#[cfg(test)]
mod tests {
    use super::{contains_reference_shape, HtmlEntityDecoder, MAX_NAME_LEN};
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::{
            crack_results::CrackResult,
            interface::{Crack, Decoder},
        },
        filtration_system::get_decoder_by_name,
    };
    use html_escape::NAMED_ENTITIES;
    use std::borrow::Cow;

    // Test vectors come from the implementation plan in
    // https://github.com/bee-san/Ciphey/issues/939, which checked them against CyberChef 11.5
    // "From HTML Entity", Python 3 `html.unescape` and html-escape 0.2.15. Tests marked "Added"
    // are not in the plan. Every expected output was checked with Python 3 `html.unescape`; the
    // tests say where this decoder deliberately differs from it.
    // The first vector is the example from the issue.
    const TOM_AND_JERRY_DECIMAL: &str = "&#60;&#98;&#62;&#84;&#111;&#109;&#32;&#38;&#32;&#74;&#101;&#114;&#114;&#121;&#60;&#47;&#98;&#62;&#32;&#115;&#97;&#121;&#32;&#34;&#104;&#105;&#34;";
    const TOM_AND_JERRY_NAMED: &str = "&lt;b&gt;Tom &amp; Jerry&lt;/b&gt; say &quot;hi&quot;";
    const TOM_AND_JERRY: &str = "<b>Tom & Jerry</b> say \"hi\"";
    const HELLO_DECIMAL: &str =
        "&#72;&#101;&#108;&#108;&#111;&#44;&#32;&#87;&#111;&#114;&#108;&#100;&#33;";
    const HELLO_HEX: &str =
        "&#x48;&#x65;&#x6c;&#x6c;&#x6f;&#x2c;&#x20;&#x57;&#x6f;&#x72;&#x6c;&#x64;&#x21;";

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    // helper for tests: the full CrackResult
    fn crack(text: &str) -> CrackResult {
        Decoder::<HtmlEntityDecoder>::new().crack(text, &get_athena_checker())
    }

    // helper for tests: just the decoded text, `None` if decoding failed
    fn decode(text: &str) -> Option<String> {
        crack(text)
            .unencrypted_text
            .map(|mut texts| texts.remove(0))
    }

    #[test]
    fn html_entities_decodes_issue_example() {
        assert_eq!(decode(TOM_AND_JERRY_DECIMAL).unwrap(), TOM_AND_JERRY);
    }

    #[test]
    fn html_entities_decodes_named_references() {
        assert_eq!(decode(TOM_AND_JERRY_NAMED).unwrap(), TOM_AND_JERRY);
    }

    #[test]
    fn html_entities_decimal_references_are_plaintext() {
        let result = crack(HELLO_DECIMAL);
        assert_eq!(result.unencrypted_text.unwrap()[0], "Hello, World!");
        assert!(result.success, "Athena should accept Hello, World!");
    }

    #[test]
    fn html_entities_decodes_lowercase_hex_references() {
        assert_eq!(decode(HELLO_HEX).unwrap(), "Hello, World!");
    }

    #[test]
    fn html_entities_decodes_uppercase_x_hex_references() {
        assert_eq!(decode("&#X48;&#X49;").unwrap(), "HI");
    }

    #[test]
    fn html_entities_decodes_mixed_forms() {
        assert_eq!(
            decode("&#x48;&#x65;&#x6c;&#x6c;&#x6f; &eacute;t&eacute; &hearts;").unwrap(),
            "Hello été ♥"
        );
    }

    #[test]
    fn html_entities_decodes_one_layer_at_a_time() {
        assert_eq!(decode("&amp;lt;").unwrap(), "&lt;");
    }

    #[test]
    fn html_entities_decodes_partially_encoded_text() {
        assert_eq!(decode("Fish &amp; Chips").unwrap(), "Fish & Chips");
    }

    #[test]
    fn html_entities_decodes_astral_characters() {
        assert_eq!(decode("&#x1F600;").unwrap(), "😀");
        // Added: the decimal form.
        assert_eq!(decode("&#128512;").unwrap(), "😀");
    }

    #[test]
    fn html_entities_decodes_nbsp_and_newlines() {
        assert_eq!(decode("a&nbsp;b").unwrap(), "a\u{a0}b");
        // Added: whitespace references are allowed.
        assert_eq!(decode("line&#10;break").unwrap(), "line\nbreak");
    }

    #[test]
    fn html_entities_decodes_zero_padded_references() {
        // Added: the number of digits is not limited.
        assert_eq!(decode("&#0072;&#x0069;").unwrap(), "Hi");
        assert_eq!(decode("&#00000000072;").unwrap(), "H");
    }

    #[test]
    fn html_entities_fails_without_references() {
        for text in [
            "",
            "hello world",
            "😀",
            "AT&T",
            "&bogus;",
            // Added: malformed references
            "a; b & c",
            "&;",
            "&#;",
            "&#x;",
            "&&&;;;",
            "&#-72;",
            "&#+72;",
            "&#99999999999999999999;",
        ] {
            let result = crack(text);
            assert!(
                result.unencrypted_text.is_none(),
                "{text:?} should not decode"
            );
            assert!(!result.success, "{text:?} should not succeed");
        }
    }

    #[test]
    fn html_entities_fails_on_invalid_code_points() {
        // Browsers and Python decode these to U+FFFD; html-escape leaves them unchanged.
        // Added: `&#x110000;`.
        for text in ["&#0;", "&#xD800;", "&#1114112;", "&#x110000;"] {
            assert!(decode(text).is_none(), "{text:?} should not decode");
        }
    }

    #[test]
    fn html_entities_ignores_references_without_semicolon() {
        // Browsers and Python decode these legacy forms; we deliberately don't.
        // Added: `&amp` and the hex form.
        for text in ["&lt", "&amp", "&#72&#105", "&#x48&#x49"] {
            assert!(decode(text).is_none(), "{text:?} should not decode");
        }
    }

    #[test]
    fn html_entities_fails_on_control_characters() {
        // Added: DEL, a C1 control and a form feed. Python drops DEL and remaps `&#x85;` to
        // the Windows-1252 "…"; this decoder rejects all three.
        for text in ["Hi&#127;", "Hi&#x85;", "Hi&#12;there"] {
            assert!(decode(text).is_none(), "{text:?} should not decode");
        }
    }

    #[test]
    fn html_entities_is_registered() {
        let decoders = get_decoder_by_name("HTML Entities");
        assert_eq!(decoders.components.len(), 1);

        // The cache stores paths as JSON and looks decoders up in DECODER_MAP to load them.
        let json = crack(HELLO_DECIMAL).get_json().unwrap();
        let restored: CrackResult = serde_json::from_str(&json).unwrap();
        assert_eq!(restored.decoder, "HTML Entities");
        assert_eq!(restored.unencrypted_text.unwrap()[0], "Hello, World!");
    }

    #[test]
    fn reference_shape_check_rejects_text_without_references() {
        for text in [
            "",
            "hello world",
            "AT&T",
            "Tom & Jerry; Spike",
            "&;",
            "&#;",
            "&#x;",
            "&#-72;",
            "&#xG;",
            "&1;",
            "&lt",
            "&#72",
            "&é;",
            // 32 characters, one more than the longest name
            "&CounterClockwiseContourIntegralX;",
        ] {
            assert!(!contains_reference_shape(text), "{text:?}");
        }
        // Shaped like references; html-escape then decides whether they are real.
        for text in [
            "&#72;",
            "&#x48;",
            "&#X48;",
            "&#0000072;",
            "&lt;",
            "AT&T; &bogus;",
            "&CounterClockwiseContourIntegral;",
        ] {
            assert!(contains_reference_shape(text), "{text:?}");
        }
    }

    #[test]
    fn reference_shape_check_covers_every_named_reference() {
        let longest = NAMED_ENTITIES
            .iter()
            .map(|(name, _)| name.len())
            .max()
            .unwrap();
        assert_eq!(longest, MAX_NAME_LEN);
        for (name, _) in NAMED_ENTITIES.iter() {
            let text = format!("x&{};y", std::str::from_utf8(name).unwrap());
            assert!(contains_reference_shape(&text), "{text:?}");
        }
    }

    #[test]
    fn reference_shape_check_keeps_everything_html_escape_decodes() {
        // Every string of up to 6 characters over this alphabet. It forms named references
        // (`&lt;`, `&amp;`, `&ap;`, `&lap;`), decimal and hex references (`&#9;`, `&#999;`,
        // `&#x99;`, `&#X9;`), runs of them (`&lt;&lt`) and many near misses (`&#x;`, `&&lt`).
        const ALPHABET: [char; 11] = ['&', '#', 'x', 'X', '9', ';', 'a', 'm', 'p', 'l', 't'];

        fn check_all(text: &mut String, more_chars: usize, decoded_count: &mut usize) {
            if let Cow::Owned(_) = html_escape::decode_html_entities(text.as_str()) {
                *decoded_count += 1;
                assert!(contains_reference_shape(text), "{text:?}");
            }
            if more_chars == 0 {
                return;
            }
            for c in ALPHABET {
                text.push(c);
                check_all(text, more_chars - 1, decoded_count);
                text.pop();
            }
        }

        let mut decoded_count = 0;
        check_all(&mut String::new(), 6, &mut decoded_count);
        // 2,534 of them decode. This guards against the test silently checking much less.
        assert!(
            decoded_count > 2_000,
            "only {decoded_count} strings decoded"
        );
    }
}
