//! Decode JSFuck: JavaScript written with only the six characters `[]()!+`.
//! Call jsfuck_decoder.crack to use. It returns a `CrackResult` whose `unencrypted_text` is
//! `None` unless the text is a JSFuck expression the evaluator understands, and otherwise
//! holds the one string it evaluates to.
//!
//! JSFuck builds values out of almost nothing: `[]` is an array, `![]` is `false`, `+[]` is
//! `0`, `[][[]]` is `undefined` and `[]+[]` is `""`. Characters are picked out of the strings
//! of those values and of built-in functions (`(![]+[])[+[]]` is `"false"[0]`, `f`) and
//! joined with `+`. Characters with no such source come from `String.fromCharCode`,
//! `unescape("%48")` or escapes in `Function('return"\110"')()`. With "Eval Source" the
//! string is a program handed to `Function(...)()` to run.
//!
//! **No JavaScript is ever run.** A small evaluator works out the value of the expression,
//! knowing only the parts of JavaScript that JSFuck uses. A string handed to `Function(...)()`
//! or `eval(...)` comes back as the source it is, so a JSFuck'd program decodes to its
//! source. The function bodies jsfuck.js writes to reach a built-in (`return escape`,
//! `return/0/`, `return"\110"` and so on) are read by a fixed table, not run.
//!
//! It reads the output of every version of [jsfuck.js], the encoder behind
//! <https://jsfuck.com>. They differ in where they get the `Function` constructor and the
//! characters the basic values don't spell:
//!
//! | jsfuck.js | `Function` from | Other characters |
//! | --- | --- | --- |
//! | npm 0.4.0 (2015) | `[]["filter"]` | `unescape("%48")`, `String.fromCharCode`, `new Date(…)` |
//! | 2018 | `[]["fill"]` | `slice("-1")`, `[]["slice"]["call"]`, `link`, `Function("return{}")()` |
//! | 2019 | `[]["fill"]` | `\uXXXX` escapes in `Function('return"…"')()` |
//! | 2020 to 2024 | `[]["flat"]` | `[]["entries"]()["constructor"]` read as `Object` |
//! | 0.5.0 (2025, jsfuck.com today) | `[]["at"]` | `at("-1")`, `\ooo` escapes, `split` and `join` |
//!
//! Anything else is out of scope: other built-ins or property names, `Function` bodies
//! outside the table (they come back as source), `new`, assignment, `toString` with a radix
//! of a fraction. The evaluator gives up on them instead of guessing, so hand-written
//! JSFuck (such as JScrewIt's) that uses other built-ins fails cleanly.
//!
//! The values follow V8 and a browser: built-in functions read as
//! `function at() { [native code] }`, `Function("return this")()` is `[object Window]` and
//! dates are in UTC. `Date()` is always 1 January 1970 rather than the time of the run;
//! jsfuck.js only reads the `GMT` in it. Since engines added Iterator helpers (ES2025)
//! `[]["entries"]()["constructor"]` is `Iterator`; jsfuck.js read `Object` there until 2024,
//! so the evaluator gives `Object`, as the engines of that time did.
//!
//! Before anything is parsed, one pass over the bytes rejects text with any other character,
//! unbalanced brackets, `++` (the increment operator) or nesting deeper than
//! [`MAX_NESTING`]. Every text a search sees that isn't JSFuck stops at its first byte that
//! isn't one of `[]()!+` or whitespace. The evaluator stops after [`MAX_STEPS`] steps or at
//! a string over [`MAX_STRING_LEN`] characters.
//!
//! References: [jsfuck.js] (its `MAPPING`, `SIMPLE` and `CONSTRUCTORS` tables list what has
//! to be modelled), [ECMA-262](https://tc39.es/ecma262/) and
//! <https://github.com/bee-san/Ciphey/issues/987>.
//!
//! [jsfuck.js]: https://github.com/aemkei/jsfuck/blob/6f8fdf31f18a4f2df3bf2576f313b3abeca4c89d/jsfuck.js

use std::borrow::Cow;
use std::fmt;

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, trace};

/// The JSFuck decoder, call:
/// `let jsfuck_decoder = Decoder::<JsFuckDecoder>::new()` to create a new instance
/// And then call:
/// `result = jsfuck_decoder.crack(input)` to evaluate a JSFuck expression
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::jsfuck_decoder::JsFuckDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_jsfuck = Decoder::<JsFuckDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // "false"[0] + "undefined"[0] + "undefined"[1]
/// let text = "(![]+[])[+[]]+([][[]]+[])[+[]]+([][[]]+[])[+!+[]]";
/// let result = decode_jsfuck.crack(text, &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "fun");
/// ```
pub struct JsFuckDecoder;

/// Texts with fewer symbols than this are not worth evaluating. `(![]+[])[+[]]`, one
/// letter, has 13, and jsfuck.js needs at least 33 for two characters.
const MIN_SYMBOLS: usize = 20;

/// Brackets and parentheses nested deeper than this are rejected before parsing. jsfuck.js
/// never nests deeper than 12.
const MAX_NESTING: usize = 64;

/// The most steps the evaluator takes: one per symbol, one per character of every string
/// it makes and [`STEPS_PER_ELEMENT`] per array element. That is about two per symbol of
/// what jsfuck.js writes: the longest test vector, 260,869 symbols, takes 531,422.
const MAX_STEPS: usize = 5_000_000;

/// What making one array element costs in steps. Elements take far more memory than
/// characters, and `split` makes one per character.
const STEPS_PER_ELEMENT: usize = 16;

/// The longest string the evaluator makes, in UTF-16 code units.
const MAX_STRING_LEN: usize = 1_000_000;

impl Crack for Decoder<JsFuckDecoder> {
    fn new() -> Decoder<JsFuckDecoder> {
        Decoder {
            name: "JSFuck",
            description: "JSFuck writes JavaScript with only the six characters []()!+. The expression is evaluated by a small built-in evaluator (no JavaScript engine); code wrapped in Function()() is returned as source, never run.",
            link: "https://github.com/aemkei/jsfuck",
            tags: vec!["jsfuck", "javascript", "esoteric", "decoder", "program"],
            popularity: 0.2,
            phantom: std::marker::PhantomData,
        }
    }

    /// Evaluates `text` as a JSFuck expression and checks the string it gives with
    /// `checker`. The source of a program handed to `Function(...)()` or `eval(...)` is
    /// returned as it is, without running it.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying JSFuck with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let decoded = match decode(text) {
            Ok(decoded) => decoded,
            Err(Error::NotJsFuck) => return results,
            Err(error) => {
                debug!("Failed to decode JSFuck because {error}");
                return results;
            }
        };
        if !check_string_success(&decoded, text) {
            debug!("Failed to decode JSFuck because it evaluates to an empty string");
            return results;
        }

        let checker_result = checker.check(&decoded);
        results.unencrypted_text = Some(vec![decoded]);
        results.update_checker(&checker_result);
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Why a text didn't decode
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Error {
    /// Rejected without parsing: a character other than `[]()!+` and whitespace, unbalanced
    /// brackets, `++`, nesting deeper than [`MAX_NESTING`] or under [`MIN_SYMBOLS`] symbols
    NotJsFuck,
    /// Not one expression: `([)]`, `()`, `[]+`, `[](`, or more after the expression
    Syntax,
    /// JavaScript the evaluator doesn't know, or that would throw, like calling `undefined`
    Unsupported,
    /// Over [`MAX_STEPS`] steps, or a string over [`MAX_STRING_LEN`] characters
    TooBig,
    /// The value isn't text: an array, a function, `undefined` and so on
    NotText,
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Error::NotJsFuck => "it isn't JSFuck",
            Error::Syntax => "it isn't one JavaScript expression",
            Error::Unsupported => "it uses JavaScript the evaluator doesn't know",
            Error::TooBig => "it takes too long to evaluate or makes too long a string",
            Error::NotText => "its value isn't a string",
        })
    }
}

/// The text `text` evaluates to as a JSFuck expression: the string it gives, or the source
/// of the program it hands to `Function(...)()` or `eval(...)`.
fn decode(text: &str) -> Result<String, Error> {
    let code = symbols(text)?;
    match Evaluator::new(&code).program()? {
        Value::Str(units) | Value::Code(units) => Ok(String::from_utf16_lossy(&units)),
        Value::Num(number) => Ok(number_to_string(number)),
        Value::Bool(boolean) => Ok(boolean.to_string()),
        _ => Err(Error::NotText),
    }
}

/// The symbols of `text` without its whitespace, if one pass over its bytes finds nothing
/// that rules out JSFuck. Text that isn't JSFuck is rejected at its first byte that isn't
/// one of `[]()!+` or whitespace, without allocating.
fn symbols(text: &str) -> Result<Cow<'_, [u8]>, Error> {
    let bytes = text.as_bytes();
    let (mut count, mut square, mut round) = (0usize, 0usize, 0usize);
    let mut spaces = false;
    let mut previous = 0u8;
    for &byte in bytes {
        match byte {
            b'[' => square += 1,
            b'(' => round += 1,
            b']' => square = square.checked_sub(1).ok_or(Error::NotJsFuck)?,
            b')' => round = round.checked_sub(1).ok_or(Error::NotJsFuck)?,
            // `++` is the increment operator, which JSFuck never uses
            b'+' if previous == b'+' => return Err(Error::NotJsFuck),
            b'!' | b'+' => {}
            b' ' | b'\t' | b'\n' | b'\r' | 0x0B | 0x0C => {
                spaces = true;
                previous = byte;
                continue;
            }
            _ => return Err(Error::NotJsFuck),
        }
        if square + round > MAX_NESTING {
            return Err(Error::NotJsFuck);
        }
        previous = byte;
        count += 1;
    }
    if square != 0 || round != 0 || count < MIN_SYMBOLS {
        return Err(Error::NotJsFuck);
    }
    Ok(if spaces {
        Cow::Owned(
            bytes
                .iter()
                .copied()
                .filter(|byte| b"[]()!+".contains(byte))
                .collect(),
        )
    } else {
        Cow::Borrowed(bytes)
    })
}

/// A JavaScript value, as far as JSFuck needs them
#[derive(Debug, PartialEq)]
enum Value {
    /// `undefined`
    Undefined,
    /// `true` or `false`
    Bool(bool),
    /// A number
    Num(f64),
    /// A string, in UTF-16 code units as JavaScript keeps it
    Str(Vec<u16>),
    /// An array
    Arr(Vec<Value>),
    /// A built-in function. A method keeps the value it was read from, which it is called on.
    Native(Builtin, Option<Box<Value>>),
    /// A function made by `Function(body)`, with its body, not run
    Func(Vec<u16>),
    /// What running this JavaScript source gives: unknown, since it is never run. Only the
    /// value of the whole expression may be one.
    Code(Vec<u16>),
    /// A regular expression with this source, from `/0/` or `RegExp("/")`
    RegExp(Vec<u16>),
    /// A `Date`, in milliseconds since 1970
    Date(i64),
    /// What `[]["entries"]()` gives
    ArrayIterator,
    /// An empty object, from `Function("return{}")()` or `Object()`
    Object,
    /// The global object, from `Function("return this")()`
    Global,
}

/// The built-in functions the evaluator knows. The methods (`At` onwards) are called on the
/// value they were read from.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Builtin {
    /// `Array`, the constructor of `[]`
    Array,
    /// `Boolean`, the constructor of `![]`
    Boolean,
    /// `Date`, from `Function("return Date")()`
    Date,
    /// `Function`, the constructor of every function
    Function,
    /// `Number`, the constructor of `+[]`
    Number,
    /// `Object`, the constructor of `{}`
    Object,
    /// `RegExp`, the constructor of `/0/`
    RegExp,
    /// `String`, the constructor of `[]+[]`
    String,
    /// `escape`, from `Function("return escape")()`
    Escape,
    /// `eval`, from `Function("return eval")()`
    Eval,
    /// `unescape`, from `Function("return unescape")()`
    Unescape,
    /// `String.fromCharCode`
    FromCharCode,
    /// `Array.prototype.at` and `String.prototype.at`
    At,
    /// `Function.prototype.call`
    Call,
    /// `Array.prototype.concat` and `String.prototype.concat`
    Concat,
    /// `Array.prototype.entries`
    Entries,
    /// `Array.prototype.fill`, which jsfuck.js only reads the source of
    Fill,
    /// `Array.prototype.filter`, which jsfuck.js only reads the source of
    Filter,
    /// `Array.prototype.flat`, which jsfuck.js only reads the source of
    Flat,
    /// `String.prototype.fontcolor`
    Fontcolor,
    /// `String.prototype.italics`
    Italics,
    /// `Array.prototype.join`
    Join,
    /// `String.prototype.link`
    Link,
    /// `Array.prototype.slice` and `String.prototype.slice`
    Slice,
    /// `String.prototype.split`
    Split,
    /// `toString` of numbers, strings, booleans, arrays and objects
    ToString,
}

impl Builtin {
    /// The function's name, as its `name` and its source give it
    fn name(self) -> &'static str {
        match self {
            Builtin::Array => "Array",
            Builtin::Boolean => "Boolean",
            Builtin::Date => "Date",
            Builtin::Function => "Function",
            Builtin::Number => "Number",
            Builtin::Object => "Object",
            Builtin::RegExp => "RegExp",
            Builtin::String => "String",
            Builtin::Escape => "escape",
            Builtin::Eval => "eval",
            Builtin::Unescape => "unescape",
            Builtin::FromCharCode => "fromCharCode",
            Builtin::At => "at",
            Builtin::Call => "call",
            Builtin::Concat => "concat",
            Builtin::Entries => "entries",
            Builtin::Fill => "fill",
            Builtin::Filter => "filter",
            Builtin::Flat => "flat",
            Builtin::Fontcolor => "fontcolor",
            Builtin::Italics => "italics",
            Builtin::Join => "join",
            Builtin::Link => "link",
            Builtin::Slice => "slice",
            Builtin::Split => "split",
            Builtin::ToString => "toString",
        }
    }
}

/// What reading a property of a value gives
enum Property {
    /// A value that doesn't depend on the object
    Value(Value),
    /// A method, to be called on the object
    Method(Builtin),
    /// A name the evaluator doesn't know for this kind of value
    Unknown,
}

/// The built-in function `builtin`, not read from a value
fn native(builtin: Builtin) -> Value {
    Value::Native(builtin, None)
}

/// The property `name` of `object`, other than an index
fn property(object: &Value, name: &str) -> Property {
    use Builtin::*;
    let found = |builtin| Property::Value(native(builtin));
    match (object, name) {
        (Value::Native(..) | Value::Func(_), "constructor") => found(Function),
        (Value::Str(_), "constructor") => found(String),
        (Value::Arr(_), "constructor") => found(Array),
        (Value::Num(_), "constructor") => found(Number),
        (Value::Bool(_), "constructor") => found(Boolean),
        (Value::RegExp(_), "constructor") => found(RegExp),
        (Value::Date(_), "constructor") => found(Date),
        // `Iterator` in engines with Iterator helpers (ES2025); see the module docs
        (Value::ArrayIterator | Value::Object, "constructor") => found(Object),
        (Value::Str(units), "length") => Property::Value(Value::Num(units.len() as f64)),
        (Value::Arr(elements), "length") => Property::Value(Value::Num(elements.len() as f64)),
        (Value::Native(builtin, _), "name") => Property::Value(Value::Str(utf16(builtin.name()))),
        (Value::Func(_), "name") => Property::Value(Value::Str(utf16("anonymous"))),
        (Value::Native(String, _), "fromCharCode") => found(FromCharCode),
        // Not on `call` itself, so methods can't wrap each other without end
        (Value::Native(builtin, _), "call") if *builtin != Call => Property::Method(Call),
        (Value::Str(_) | Value::Arr(_), "at") => Property::Method(At),
        (Value::Str(_) | Value::Arr(_), "concat") => Property::Method(Concat),
        (Value::Str(_) | Value::Arr(_), "slice") => Property::Method(Slice),
        (
            Value::Str(_) | Value::Arr(_) | Value::Num(_) | Value::Bool(_) | Value::Object,
            "toString",
        ) => Property::Method(ToString),
        (Value::Str(_), "fontcolor") => Property::Method(Fontcolor),
        (Value::Str(_), "italics") => Property::Method(Italics),
        (Value::Str(_), "link") => Property::Method(Link),
        (Value::Str(_), "split") => Property::Method(Split),
        (Value::Arr(_), "entries") => Property::Method(Entries),
        (Value::Arr(_), "fill") => Property::Method(Fill),
        (Value::Arr(_), "filter") => Property::Method(Filter),
        (Value::Arr(_), "flat") => Property::Method(Flat),
        (Value::Arr(_), "join") => Property::Method(Join),
        _ => Property::Unknown,
    }
}

/// Evaluates a JSFuck expression in one pass, as it parses it:
///
/// ```text
/// additive := unary ('+' unary)*
/// unary    := ('!' | '+')* postfix
/// postfix  := primary ('[' additive ']' | '(' additive? ')')*
/// primary  := '[' additive? ']' | '(' additive ')'
/// ```
///
/// With no variables and nothing to run twice, every part is evaluated once, in order.
struct Evaluator<'a> {
    /// The symbols, without whitespace
    code: &'a [u8],
    /// Where the next symbol is
    pos: usize,
    /// The steps taken so far
    steps: usize,
    /// How many brackets and parentheses are open
    depth: usize,
    /// The most steps to take, [`MAX_STEPS`] outside tests
    max_steps: usize,
    /// The longest string to make, [`MAX_STRING_LEN`] outside tests
    max_string_len: usize,
}

impl<'a> Evaluator<'a> {
    /// An evaluator for `code`, which holds only the six symbols
    fn new(code: &'a [u8]) -> Self {
        Evaluator {
            code,
            pos: 0,
            steps: 0,
            depth: 0,
            max_steps: MAX_STEPS,
            max_string_len: MAX_STRING_LEN,
        }
    }

    /// The value of the whole of `code`
    fn program(&mut self) -> Result<Value, Error> {
        let value = self.additive()?;
        if self.pos != self.code.len() {
            return Err(Error::Syntax);
        }
        Ok(value)
    }

    /// The next symbol
    fn peek(&self) -> Option<u8> {
        self.code.get(self.pos).copied()
    }

    /// Takes `count` steps
    fn step(&mut self, count: usize) -> Result<(), Error> {
        self.steps = self.steps.saturating_add(count);
        if self.steps > self.max_steps {
            return Err(Error::TooBig);
        }
        Ok(())
    }

    /// Steps over the next symbol, a `[` or `(`
    fn open(&mut self) -> Result<(), Error> {
        self.depth += 1;
        if self.depth > MAX_NESTING {
            return Err(Error::TooBig);
        }
        self.pos += 1;
        self.step(1)
    }

    /// Steps over `symbol`, which has to come next
    fn close(&mut self, symbol: u8) -> Result<(), Error> {
        if self.peek() != Some(symbol) {
            return Err(Error::Syntax);
        }
        self.depth -= 1;
        self.pos += 1;
        self.step(1)
    }

    /// `unary ('+' unary)*`
    fn additive(&mut self) -> Result<Value, Error> {
        let mut value = self.unary()?;
        while self.peek() == Some(b'+') {
            self.pos += 1;
            self.step(1)?;
            let right = self.unary()?;
            value = self.add(value, right)?;
        }
        Ok(value)
    }

    /// `('!' | '+')* postfix`. The operators are applied innermost first, without recursion,
    /// so a long run of them can't overflow the stack.
    fn unary(&mut self) -> Result<Value, Error> {
        let start = self.pos;
        while matches!(self.peek(), Some(b'!' | b'+')) {
            self.pos += 1;
            self.step(1)?;
        }
        let code = self.code;
        let operators = &code[start..self.pos];
        let mut value = self.postfix()?;
        for &operator in operators.iter().rev() {
            value = if operator == b'!' {
                Value::Bool(!truthy(&value)?)
            } else {
                Value::Num(self.number_of(value)?)
            };
        }
        Ok(value)
    }

    /// `primary ('[' additive ']' | '(' additive? ')')*`
    fn postfix(&mut self) -> Result<Value, Error> {
        let mut value = self.primary()?;
        loop {
            match self.peek() {
                Some(b'[') => {
                    self.open()?;
                    let key = self.additive()?;
                    self.close(b']')?;
                    value = self.member(value, key)?;
                }
                Some(b'(') => {
                    self.open()?;
                    let argument = if self.peek() == Some(b')') {
                        None
                    } else {
                        Some(self.additive()?)
                    };
                    self.close(b')')?;
                    value = self.call(value, argument)?;
                }
                _ => return Ok(value),
            }
        }
    }

    /// `'[' additive? ']' | '(' additive ')'`: an array literal or a parenthesised expression
    fn primary(&mut self) -> Result<Value, Error> {
        match self.peek() {
            Some(b'[') => {
                self.open()?;
                let elements = if self.peek() == Some(b']') {
                    Vec::new()
                } else {
                    vec![self.additive()?]
                };
                self.close(b']')?;
                self.step(STEPS_PER_ELEMENT * elements.len())?;
                Ok(Value::Arr(elements))
            }
            Some(b'(') => {
                self.open()?;
                let value = self.additive()?;
                self.close(b')')?;
                Ok(value)
            }
            _ => Err(Error::Syntax),
        }
    }

    /// Accounts for a string the evaluator made
    fn made(&mut self, units: Vec<u16>) -> Result<Vec<u16>, Error> {
        if units.len() > self.max_string_len {
            return Err(Error::TooBig);
        }
        self.step(units.len())?;
        Ok(units)
    }

    /// Fails if a string of `len` code units would be too long
    fn fits(&self, len: usize) -> Result<(), Error> {
        if len > self.max_string_len {
            return Err(Error::TooBig);
        }
        Ok(())
    }

    /// The string `value` becomes (ToString in ECMA-262)
    fn string_of(&mut self, value: Value) -> Result<Vec<u16>, Error> {
        let text: Cow<'static, str> = match value {
            Value::Str(units) => return Ok(units),
            Value::Arr(elements) => return self.join(elements, &[u16::from(b',')]),
            Value::Code(_) => return Err(Error::Unsupported),
            Value::Func(body) => {
                self.fits(body.len() + 24)?;
                let mut units = utf16("function anonymous(\n) {\n");
                units.extend_from_slice(&body);
                units.extend(utf16("\n}"));
                return self.made(units);
            }
            Value::RegExp(source) => {
                self.fits(source.len() + 6)?;
                let mut units = vec![u16::from(b'/')];
                if source.is_empty() {
                    units.extend(utf16("(?:)"));
                } else {
                    units.extend_from_slice(&source);
                }
                units.push(u16::from(b'/'));
                return self.made(units);
            }
            Value::Undefined => "undefined".into(),
            Value::Bool(true) => "true".into(),
            Value::Bool(false) => "false".into(),
            Value::Num(number) => number_to_string(number).into(),
            Value::Native(builtin, _) => {
                format!("function {}() {{ [native code] }}", builtin.name()).into()
            }
            Value::Date(ms) => date_string(ms).into(),
            Value::ArrayIterator => "[object Array Iterator]".into(),
            Value::Object => "[object Object]".into(),
            Value::Global => "[object Window]".into(),
        };
        self.made(utf16(&text))
    }

    /// The number `value` becomes (ToNumber in ECMA-262)
    fn number_of(&mut self, value: Value) -> Result<f64, Error> {
        Ok(match value {
            Value::Undefined => f64::NAN,
            Value::Bool(boolean) => f64::from(u8::from(boolean)),
            Value::Num(number) => number,
            Value::Date(ms) => ms as f64,
            Value::Code(_) => return Err(Error::Unsupported),
            other => {
                let text = self.string_of(other)?;
                string_to_number(&text)?
            }
        })
    }

    /// The primitive `value` becomes as `+` asks for it (ToPrimitive with no hint): objects
    /// become strings
    fn primitive_of(&mut self, value: Value) -> Result<Value, Error> {
        match value {
            Value::Undefined | Value::Bool(_) | Value::Num(_) | Value::Str(_) => Ok(value),
            Value::Code(_) => Err(Error::Unsupported),
            object => Ok(Value::Str(self.string_of(object)?)),
        }
    }

    /// `left + right`: string concatenation if either side is a string once objects have
    /// become strings, otherwise addition
    fn add(&mut self, left: Value, right: Value) -> Result<Value, Error> {
        let left = self.primitive_of(left)?;
        let right = self.primitive_of(right)?;
        if !matches!(left, Value::Str(_)) && !matches!(right, Value::Str(_)) {
            return Ok(Value::Num(self.number_of(left)? + self.number_of(right)?));
        }
        let mut text = self.string_of(left)?;
        let tail = self.string_of(right)?;
        self.fits(text.len() + tail.len())?;
        self.step(tail.len())?;
        text.extend_from_slice(&tail);
        Ok(Value::Str(text))
    }

    /// The elements of an array as strings joined with `separator`, as `join` does it
    fn join(&mut self, elements: Vec<Value>, separator: &[u16]) -> Result<Vec<u16>, Error> {
        let mut out = Vec::new();
        for (i, element) in elements.into_iter().enumerate() {
            if i > 0 {
                self.fits(out.len() + separator.len())?;
                self.step(separator.len())?;
                out.extend_from_slice(separator);
            }
            if !matches!(element, Value::Undefined) {
                let part = self.string_of(element)?;
                self.fits(out.len() + part.len())?;
                self.step(part.len())?;
                out.extend_from_slice(&part);
            }
        }
        Ok(out)
    }

    /// `object[key]`
    fn member(&mut self, object: Value, key: Value) -> Result<Value, Error> {
        // Reading a property of undefined throws
        if matches!(object, Value::Undefined | Value::Code(_)) {
            return Err(Error::Unsupported);
        }
        let key = self.string_of(key)?;
        let object = match (object, array_index(&key)) {
            (Value::Str(units), Some(index)) => {
                return Ok(units
                    .get(index)
                    .map_or(Value::Undefined, |&unit| Value::Str(vec![unit])))
            }
            (Value::Arr(elements), Some(index)) => {
                return Ok(elements.into_iter().nth(index).unwrap_or(Value::Undefined))
            }
            (object, _) => object,
        };
        let mut buffer = [0; 16];
        let name = short_ascii(&key, &mut buffer).unwrap_or_default();
        match property(&object, name) {
            Property::Value(value) => Ok(value),
            Property::Method(builtin) => Ok(Value::Native(builtin, Some(Box::new(object)))),
            // Built-in functions and the global object have properties of every name
            Property::Unknown if matches!(object, Value::Native(..) | Value::Global) => {
                Err(Error::Unsupported)
            }
            Property::Unknown if !may_be_built_in(&key) => Ok(Value::Undefined),
            Property::Unknown => Err(Error::Unsupported),
        }
    }

    /// `callee(argument)`. JSFuck has no comma, so there is at most one argument.
    fn call(&mut self, callee: Value, argument: Option<Value>) -> Result<Value, Error> {
        match callee {
            Value::Func(body) => {
                self.step(body.len())?;
                Ok(run_function(body))
            }
            Value::Native(builtin, receiver) => {
                self.call_builtin(builtin, receiver.map(|receiver| *receiver), argument)
            }
            _ => Err(Error::Unsupported),
        }
    }

    /// ToString of an argument, `undefined` if there is none
    fn string_argument(&mut self, argument: Option<Value>) -> Result<Vec<u16>, Error> {
        self.string_of(argument.unwrap_or(Value::Undefined))
    }

    /// ToIntegerOrInfinity of an argument, 0 if there is none
    fn integer_argument(&mut self, argument: Option<Value>) -> Result<f64, Error> {
        let number = self.number_of(argument.unwrap_or(Value::Undefined))?;
        Ok(to_integer_or_infinity(number))
    }

    /// Calls the built-in `builtin`, on `receiver` if it is a method
    fn call_builtin(
        &mut self,
        builtin: Builtin,
        receiver: Option<Value>,
        argument: Option<Value>,
    ) -> Result<Value, Error> {
        match (builtin, receiver) {
            // Only makes the function; calling it is `run_function`
            (Builtin::Function, _) => Ok(Value::Func(match argument {
                Some(body) => self.string_of(body)?,
                None => Vec::new(),
            })),
            (Builtin::Eval, _) => Ok(match argument {
                // The program is never run: it comes back as source
                Some(Value::Str(source)) => Value::Code(source),
                // `eval` gives back anything that isn't a string
                Some(other) => other,
                None => Value::Undefined,
            }),
            (Builtin::Escape, _) => {
                let text = self.string_argument(argument)?;
                self.fits(escaped_len(&text))?;
                Ok(Value::Str(self.made(escape(&text))?))
            }
            (Builtin::Unescape, _) => {
                let text = self.string_argument(argument)?;
                Ok(Value::Str(self.made(unescape(&text))?))
            }
            // Called as a function, `Date` gives the time now as a string; see the module docs
            (Builtin::Date, _) => Ok(Value::Str(self.made(utf16(&date_string(0)))?)),
            (Builtin::RegExp, _) => {
                let pattern = match argument {
                    None | Some(Value::Undefined) => Vec::new(),
                    Some(pattern) => self.string_of(pattern)?,
                };
                // Escaping can make the source up to six times as long as the pattern
                self.fits(6 * pattern.len())?;
                let source = regexp_source(&pattern).ok_or(Error::Unsupported)?;
                Ok(Value::RegExp(self.made(source)?))
            }
            (Builtin::Object, _) => match argument {
                None | Some(Value::Undefined) => Ok(Value::Object),
                Some(_) => Err(Error::Unsupported),
            },
            (Builtin::FromCharCode, _) => Ok(Value::Str(match argument {
                Some(code) => vec![to_uint16(self.number_of(code)?)],
                None => Vec::new(),
            })),
            (Builtin::At, Some(Value::Str(units))) => {
                let index = self.integer_argument(argument)?;
                Ok(at_index(index, units.len())
                    .map_or(Value::Undefined, |index| Value::Str(vec![units[index]])))
            }
            (Builtin::At, Some(Value::Arr(elements))) => {
                let index = self.integer_argument(argument)?;
                Ok(at_index(index, elements.len())
                    .and_then(|index| elements.into_iter().nth(index))
                    .unwrap_or(Value::Undefined))
            }
            (Builtin::Slice, Some(Value::Str(units))) => {
                let start = slice_start(self.integer_argument(argument)?, units.len());
                Ok(Value::Str(self.made(units[start..].to_vec())?))
            }
            (Builtin::Slice, Some(Value::Arr(elements))) => {
                let start = slice_start(self.integer_argument(argument)?, elements.len());
                self.step(STEPS_PER_ELEMENT * (elements.len() - start))?;
                Ok(Value::Arr(elements.into_iter().skip(start).collect()))
            }
            (Builtin::Concat, Some(Value::Str(mut units))) => {
                if let Some(tail) = argument {
                    let tail = self.string_of(tail)?;
                    self.fits(units.len() + tail.len())?;
                    self.step(tail.len())?;
                    units.extend_from_slice(&tail);
                }
                Ok(Value::Str(units))
            }
            (Builtin::Concat, Some(Value::Arr(mut elements))) => {
                match argument {
                    Some(Value::Arr(more)) => elements.extend(more),
                    Some(element) => elements.push(element),
                    None => {}
                }
                self.step(STEPS_PER_ELEMENT * elements.len())?;
                Ok(Value::Arr(elements))
            }
            (Builtin::Entries, Some(Value::Arr(_))) => Ok(Value::ArrayIterator),
            (Builtin::Join, Some(Value::Arr(elements))) => {
                let separator = match argument {
                    None | Some(Value::Undefined) => vec![u16::from(b',')],
                    Some(separator) => self.string_of(separator)?,
                };
                Ok(Value::Str(self.join(elements, &separator)?))
            }
            (Builtin::Split, Some(Value::Str(units))) => {
                let separator = match argument {
                    None | Some(Value::Undefined) => {
                        return Ok(Value::Arr(vec![Value::Str(units)]));
                    }
                    Some(Value::RegExp(_)) => return Err(Error::Unsupported),
                    Some(separator) => self.string_of(separator)?,
                };
                let pieces = split(&units, &separator);
                self.step(units.len() + STEPS_PER_ELEMENT * pieces.len())?;
                Ok(Value::Arr(pieces.into_iter().map(Value::Str).collect()))
            }
            (Builtin::ToString, Some(Value::Num(number))) => {
                let radix = match argument {
                    None | Some(Value::Undefined) => 10.0,
                    Some(radix) => to_integer_or_infinity(self.number_of(radix)?),
                };
                // Any other radix throws a RangeError
                if !(2.0..=36.0).contains(&radix) {
                    return Err(Error::Unsupported);
                }
                let text = if radix == 10.0 {
                    number_to_string(number)
                } else {
                    integer_to_radix(number, radix as u32).ok_or(Error::Unsupported)?
                };
                Ok(Value::Str(self.made(utf16(&text))?))
            }
            (Builtin::ToString, Some(Value::Object)) => {
                Ok(Value::Str(self.made(utf16("[object Object]"))?))
            }
            (
                Builtin::ToString,
                Some(receiver @ (Value::Str(_) | Value::Bool(_) | Value::Arr(_))),
            ) => Ok(Value::Str(self.string_of(receiver)?)),
            (Builtin::Fontcolor, Some(Value::Str(units))) => {
                let color = self.string_argument(argument)?;
                self.html(&units, "font", Some(("color", &color)))
            }
            (Builtin::Link, Some(Value::Str(units))) => {
                let url = self.string_argument(argument)?;
                self.html(&units, "a", Some(("href", &url)))
            }
            (Builtin::Italics, Some(Value::Str(units))) => self.html(&units, "i", None),
            (Builtin::Call, Some(Value::Native(target, receiver))) => {
                self.call_with_this(target, receiver.map(|receiver| *receiver), argument)
            }
            // Calling Array, Boolean, Number, String, fill, filter or flat, or a method on
            // a value it doesn't belong to
            _ => Err(Error::Unsupported),
        }
    }

    /// `target.call(this)`, for the two that jsfuck.js uses
    fn call_with_this(
        &mut self,
        target: Builtin,
        receiver: Option<Value>,
        this: Option<Value>,
    ) -> Result<Value, Error> {
        match (target, receiver, this) {
            // Array.prototype.slice on a string: its characters
            (Builtin::Slice, Some(Value::Arr(_)), Some(Value::Str(units))) => {
                self.step(STEPS_PER_ELEMENT * units.len())?;
                Ok(Value::Arr(
                    units
                        .into_iter()
                        .map(|unit| Value::Str(vec![unit]))
                        .collect(),
                ))
            }
            // Object.prototype.toString: what kind of value `this` is
            (Builtin::ToString, Some(Value::Object), this) => {
                let tag = match this.unwrap_or(Value::Undefined) {
                    Value::Undefined => "Undefined",
                    Value::Bool(_) => "Boolean",
                    Value::Num(_) => "Number",
                    Value::Str(_) => "String",
                    Value::Arr(_) => "Array",
                    Value::Native(..) | Value::Func(_) => "Function",
                    Value::RegExp(_) => "RegExp",
                    Value::Date(_) => "Date",
                    Value::ArrayIterator => "Array Iterator",
                    Value::Object => "Object",
                    Value::Global => "Window",
                    Value::Code(_) => return Err(Error::Unsupported),
                };
                Ok(Value::Str(self.made(utf16(&format!("[object {tag}]")))?))
            }
            _ => Err(Error::Unsupported),
        }
    }

    /// `text` in an HTML element, as `fontcolor`, `link` and `italics` write it
    fn html(
        &mut self,
        text: &[u16],
        tag: &str,
        attribute: Option<(&str, &[u16])>,
    ) -> Result<Value, Error> {
        let attribute_len = attribute.map_or(0, |(_, value)| 6 * value.len());
        self.fits(text.len() + attribute_len + 32)?;
        let mut out = utf16("<");
        out.extend(utf16(tag));
        if let Some((name, value)) = attribute {
            out.push(u16::from(b' '));
            out.extend(utf16(name));
            out.extend(utf16("=\""));
            for &unit in value {
                if unit == u16::from(b'"') {
                    out.extend(utf16("&quot;"));
                } else {
                    out.push(unit);
                }
            }
            out.push(u16::from(b'"'));
        }
        out.push(u16::from(b'>'));
        out.extend_from_slice(text);
        out.extend(utf16("</"));
        out.extend(utf16(tag));
        out.push(u16::from(b'>'));
        Ok(Value::Str(self.made(out)?))
    }
}

/// ToBoolean
fn truthy(value: &Value) -> Result<bool, Error> {
    Ok(match value {
        Value::Undefined => false,
        Value::Bool(boolean) => *boolean,
        Value::Num(number) => !(*number == 0.0 || number.is_nan()),
        Value::Str(units) => !units.is_empty(),
        Value::Code(_) => return Err(Error::Unsupported),
        _ => true,
    })
}

/// What calling a function made by `Function(body)` gives, for the bodies jsfuck.js writes.
/// Any other body comes back as [`Value::Code`]: it is never run.
fn run_function(body: Vec<u16>) -> Value {
    function_value(&body).unwrap_or(Value::Code(body))
}

/// The value `return …` gives, if `body` is one of the function bodies jsfuck.js writes:
/// `return escape`, `unescape`, `eval`, `Date`, `this` or `{}`, a string literal, a regular
/// expression literal or `new Date(<milliseconds>)`.
fn function_value(body: &[u16]) -> Option<Value> {
    let body = trim_js_space(body);
    if body.is_empty() {
        return Some(Value::Undefined);
    }
    let rest = strip_ascii_prefix(body, "return")?;
    // `returned` is a different word, and a line break after `return` ends the statement
    if rest.first().is_some_and(|&unit| is_identifier_part(unit)) {
        return None;
    }
    let rest = &rest[rest
        .iter()
        .take_while(|&&unit| unit == u16::from(b' ') || unit == u16::from(b'\t'))
        .count()..];
    if rest.first().is_some_and(|&unit| is_line_terminator(unit)) {
        return None;
    }
    let expression = strip_statement_end(rest);
    let value = match expression.first().and_then(|&unit| u8::try_from(unit).ok()) {
        None if expression.is_empty() => Value::Undefined,
        Some(b'"' | b'\'') => Value::Str(string_literal(expression)?),
        Some(b'/') => Value::RegExp(regexp_literal(expression)?),
        _ => {
            let mut buffer = [0; 16];
            match short_ascii(expression, &mut buffer) {
                Some("escape") => native(Builtin::Escape),
                Some("unescape") => native(Builtin::Unescape),
                Some("eval") => native(Builtin::Eval),
                Some("Date") => native(Builtin::Date),
                Some("this") => Value::Global,
                Some("{}") => Value::Object,
                _ => Value::Date(new_date(expression)?),
            }
        }
    };
    Some(value)
}

/// `expression` without the whitespace and `;` that can end a statement
fn strip_statement_end(expression: &[u16]) -> &[u16] {
    let expression = trim_js_space(expression);
    match expression.split_last() {
        Some((&last, rest)) if last == u16::from(b';') => trim_js_space(rest),
        _ => expression,
    }
}

/// The milliseconds in `new Date(<digits>)`, for dates that V8 and chrono write the same way
fn new_date(expression: &[u16]) -> Option<i64> {
    let digits = strip_ascii_prefix(expression, "new Date(")?.strip_suffix(&[u16::from(b')')])?;
    if digits.is_empty() || digits.len() > 15 || !digits.iter().all(|&unit| is_digit(unit)) {
        return None;
    }
    let ms = digits.iter().fold(0i64, |ms, &unit| {
        ms * 10 + i64::from(unit - u16::from(b'0'))
    });
    // The end of the year 9999: later years are written differently
    (ms <= 253_402_300_799_999).then_some(ms)
}

/// The string a JavaScript string literal stands for, if `literal` is exactly one, in
/// sloppy mode: legacy octal escapes such as `\101` and `\40` are allowed.
fn string_literal(literal: &[u16]) -> Option<Vec<u16>> {
    let (&quote, mut rest) = literal.split_first()?;
    let mut out = Vec::with_capacity(rest.len());
    loop {
        let (&unit, tail) = rest.split_first()?;
        rest = tail;
        if unit == quote {
            return rest.is_empty().then_some(out);
        }
        if unit == u16::from(b'\n') || unit == u16::from(b'\r') {
            // A line break before the closing quote is a syntax error
            return None;
        }
        if unit != u16::from(b'\\') {
            out.push(unit);
            continue;
        }
        let (&escaped, tail) = rest.split_first()?;
        rest = tail;
        match u8::try_from(escaped) {
            Ok(b'b') => out.push(0x08),
            Ok(b't') => out.push(0x09),
            Ok(b'n') => out.push(0x0A),
            Ok(b'v') => out.push(0x0B),
            Ok(b'f') => out.push(0x0C),
            Ok(b'r') => out.push(0x0D),
            // A line continuation
            Ok(b'\n') => {}
            Ok(b'\r') => {
                if rest.first() == Some(&u16::from(b'\n')) {
                    rest = &rest[1..];
                }
            }
            Ok(b'x') => {
                let (value, tail) = hex_digits(rest, 2)?;
                out.push(value as u16);
                rest = tail;
            }
            Ok(b'u') => {
                let (value, tail) = if rest.first() == Some(&u16::from(b'{')) {
                    let end = rest.iter().position(|&unit| unit == u16::from(b'}'))?;
                    let (value, after) = hex_digits(&rest[1..end], end - 1)?;
                    if end == 1 || !after.is_empty() || value > 0x10FFFF {
                        return None;
                    }
                    (value, &rest[end + 1..])
                } else {
                    hex_digits(rest, 4)?
                };
                rest = tail;
                // A surrogate on its own is allowed: an emoji is written as two of them
                if let Ok(unit) = u16::try_from(value) {
                    out.push(unit);
                } else {
                    let mut buffer = [0; 2];
                    out.extend_from_slice(char::from_u32(value)?.encode_utf16(&mut buffer));
                }
            }
            // Legacy octal escapes: three digits if the first is 0 to 3, otherwise two
            Ok(first @ b'0'..=b'7') => {
                let mut value = u16::from(first - b'0');
                let most = if first <= b'3' { 3 } else { 2 };
                for _ in 1..most {
                    match rest.first() {
                        Some(&digit) if (u16::from(b'0')..=u16::from(b'7')).contains(&digit) => {
                            value = value * 8 + (digit - u16::from(b'0'));
                            rest = &rest[1..];
                        }
                        _ => break,
                    }
                }
                out.push(value);
            }
            // Line and paragraph separators continue the line too
            _ if escaped == 0x2028 || escaped == 0x2029 => {}
            // Anything else, `\8`, `\9`, `\"` and `\\` included, stands for itself
            _ => out.push(escaped),
        }
    }
}

/// The value of the first `count` hex digits of `units`, and what follows them
fn hex_digits(units: &[u16], count: usize) -> Option<(u32, &[u16])> {
    if units.len() < count {
        return None;
    }
    let mut value = 0u32;
    for &unit in &units[..count] {
        let digit = char::from_u32(u32::from(unit))?.to_digit(16)?;
        value = value.checked_mul(16)? + digit;
    }
    Some((value, &units[count..]))
}

/// The source of a regular expression literal `/…/` without flags, if its pattern is one
/// that can't be a syntax error
fn regexp_literal(literal: &[u16]) -> Option<Vec<u16>> {
    let source = literal
        .strip_prefix(&[u16::from(b'/')])?
        .strip_suffix(&[u16::from(b'/')])?;
    // `//` starts a comment, and a `/` inside would end the literal early
    if source.is_empty() || source.contains(&u16::from(b'/')) {
        return None;
    }
    simple_pattern(source).then(|| source.to_vec())
}

/// The source `RegExp(pattern)` writes, if `pattern` can't be a syntax error: a `/` is
/// escaped as `\/` and line breaks as `\n`, `\r`, `\u2028` and `\u2029`
fn regexp_source(pattern: &[u16]) -> Option<Vec<u16>> {
    if !simple_pattern(pattern) {
        return None;
    }
    let mut source = Vec::with_capacity(pattern.len());
    for &unit in pattern {
        match unit {
            0x2F => source.extend(utf16("\\/")),
            0x0A => source.extend(utf16("\\n")),
            0x0D => source.extend(utf16("\\r")),
            0x2028 => source.extend(utf16("\\u2028")),
            0x2029 => source.extend(utf16("\\u2029")),
            _ => source.push(unit),
        }
    }
    Some(source)
}

/// Whether a regular expression pattern has none of the characters that can make it a
/// syntax error: escapes, groups, classes and quantifiers
fn simple_pattern(pattern: &[u16]) -> bool {
    !pattern
        .iter()
        .any(|&unit| u8::try_from(unit).is_ok_and(|byte| b"\\()[]{}*+?".contains(&byte)))
}

/// The pieces of `text` between the occurrences of `separator`, as `split` gives them
fn split(text: &[u16], separator: &[u16]) -> Vec<Vec<u16>> {
    if separator.is_empty() {
        return text.iter().map(|&unit| vec![unit]).collect();
    }
    let mut pieces = Vec::new();
    let mut start = 0;
    let mut i = 0;
    while i + separator.len() <= text.len() {
        if &text[i..i + separator.len()] == separator {
            pieces.push(text[start..i].to_vec());
            i += separator.len();
            start = i;
        } else {
            i += 1;
        }
    }
    pieces.push(text[start..].to_vec());
    pieces
}

/// The index `key` stands for, if it is a canonical array index like `0` or `12`
fn array_index(key: &[u16]) -> Option<usize> {
    if key.is_empty() || key.len() > 10 || !key.iter().all(|&unit| is_digit(unit)) {
        return None;
    }
    if key.len() > 1 && key[0] == u16::from(b'0') {
        return None;
    }
    let index = key.iter().fold(0u64, |index, &unit| {
        index * 10 + u64::from(unit - u16::from(b'0'))
    });
    // 2^32 - 1 isn't an array index
    if index >= u64::from(u32::MAX) {
        return None;
    }
    usize::try_from(index).ok()
}

/// Whether `key` could name a property of a built-in prototype, which are all identifiers.
/// The names of the basic values aren't the names of any.
fn may_be_built_in(key: &[u16]) -> bool {
    let Some((&first, rest)) = key.split_first() else {
        return false;
    };
    if !is_identifier_start(first) || !rest.iter().all(|&unit| is_identifier_part(unit)) {
        return false;
    }
    let mut buffer = [0; 16];
    !matches!(
        short_ascii(key, &mut buffer),
        Some("undefined" | "null" | "true" | "false" | "NaN" | "Infinity")
    )
}

/// `units` as a `&str`, if it is ASCII and fits in `buffer`
fn short_ascii<'b>(units: &[u16], buffer: &'b mut [u8; 16]) -> Option<&'b str> {
    if units.len() > buffer.len() {
        return None;
    }
    for (slot, &unit) in buffer.iter_mut().zip(units) {
        *slot = u8::try_from(unit).ok().filter(u8::is_ascii)?;
    }
    std::str::from_utf8(&buffer[..units.len()]).ok()
}

/// `units` after `prefix`, if it starts with it
fn strip_ascii_prefix<'u>(units: &'u [u16], prefix: &str) -> Option<&'u [u16]> {
    if units.len() < prefix.len()
        || !units
            .iter()
            .zip(prefix.bytes())
            .all(|(&unit, byte)| unit == u16::from(byte))
    {
        return None;
    }
    Some(&units[prefix.len()..])
}

/// `text` in UTF-16
fn utf16(text: &str) -> Vec<u16> {
    text.encode_utf16().collect()
}

/// An ASCII digit
fn is_digit(unit: u16) -> bool {
    (u16::from(b'0')..=u16::from(b'9')).contains(&unit)
}

/// A character an identifier can start with, as far as built-in names go
fn is_identifier_start(unit: u16) -> bool {
    u8::try_from(unit).is_ok_and(|byte| byte.is_ascii_alphabetic() || byte == b'_' || byte == b'$')
}

/// A character an identifier can go on with. Anything outside ASCII counts, to be safe.
fn is_identifier_part(unit: u16) -> bool {
    is_identifier_start(unit) || is_digit(unit) || unit > 0x7F
}

/// A JavaScript line terminator
fn is_line_terminator(unit: u16) -> bool {
    matches!(unit, 0x0A | 0x0D | 0x2028 | 0x2029)
}

/// JavaScript whitespace or a line terminator, as `trim` and ToNumber skip them
fn is_js_space(unit: u16) -> bool {
    matches!(
        unit,
        0x09 | 0x0B | 0x0C | 0x20 | 0xA0 | 0x1680 | 0x2000
            ..=0x200A | 0x202F | 0x205F | 0x3000 | 0xFEFF
    ) || is_line_terminator(unit)
}

/// `units` without the JavaScript whitespace at either end
fn trim_js_space(units: &[u16]) -> &[u16] {
    let start = units.iter().take_while(|&&unit| is_js_space(unit)).count();
    let end = units.len()
        - units[start..]
            .iter()
            .rev()
            .take_while(|&&unit| is_js_space(unit))
            .count();
    &units[start..end]
}

/// ToNumber of a string: a decimal, hex, octal or binary literal, `Infinity`, or NaN
fn string_to_number(units: &[u16]) -> Result<f64, Error> {
    let units = trim_js_space(units);
    if units.is_empty() {
        return Ok(0.0);
    }
    let Ok(text) = String::from_utf16(units) else {
        return Ok(f64::NAN);
    };
    match text.as_str() {
        "Infinity" | "+Infinity" => return Ok(f64::INFINITY),
        "-Infinity" => return Ok(f64::NEG_INFINITY),
        _ => {}
    }
    let radix = match text.get(..2) {
        Some("0x" | "0X") => 16,
        Some("0o" | "0O") => 8,
        Some("0b" | "0B") => 2,
        _ => 10,
    };
    if radix != 10 {
        let digits = &text[2..];
        if digits.is_empty() || !digits.chars().all(|c| c.is_digit(radix)) {
            return Ok(f64::NAN);
        }
        // Exact up to 2^53; longer ones would need correct rounding
        return match u64::from_str_radix(digits, radix) {
            Ok(value) if value <= 1 << 53 => Ok(value as f64),
            _ => Err(Error::Unsupported),
        };
    }
    if !is_decimal_literal(&text) {
        return Ok(f64::NAN);
    }
    Ok(text.parse().unwrap_or(f64::NAN))
}

/// Whether `text` is a StrDecimalLiteral without `Infinity`:
/// `[+-]?(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?`. Rust's float parser also takes `inf` and `nan`,
/// which JavaScript reads as NaN.
fn is_decimal_literal(text: &str) -> bool {
    let bytes = text.as_bytes();
    let mut i = usize::from(matches!(bytes.first(), Some(b'+' | b'-')));
    let digits = |i: &mut usize| {
        let start = *i;
        while bytes.get(*i).is_some_and(u8::is_ascii_digit) {
            *i += 1;
        }
        *i - start
    };
    let mut mantissa = digits(&mut i);
    if bytes.get(i) == Some(&b'.') {
        i += 1;
        mantissa += digits(&mut i);
    }
    if mantissa == 0 {
        return false;
    }
    if matches!(bytes.get(i), Some(b'e' | b'E')) {
        i += 1;
        if matches!(bytes.get(i), Some(b'+' | b'-')) {
            i += 1;
        }
        if digits(&mut i) == 0 {
            return false;
        }
    }
    i == bytes.len()
}

/// Number::toString(x) in base 10, as ECMA-262 defines it: the shortest digits that read
/// back as `x`, written as an integer, a decimal or with an exponent
fn number_to_string(x: f64) -> String {
    if x.is_nan() {
        return "NaN".to_string();
    }
    if x == 0.0 {
        return "0".to_string();
    }
    if x.is_infinite() {
        return if x > 0.0 { "Infinity" } else { "-Infinity" }.to_string();
    }
    if x < 0.0 {
        return format!("-{}", number_to_string(-x));
    }
    // Rust writes the shortest round-trip digits too: `1.1e21`, `5e-324`
    let scientific = format!("{x:e}");
    let (mantissa, exponent) = scientific
        .split_once('e')
        .expect("{:e} always writes an exponent");
    let exponent: i32 = exponent.parse().expect("{:e} writes an integer exponent");
    let digits: String = mantissa.chars().filter(|&c| c != '.').collect();
    let k = digits.len() as i32;
    let n = exponent + 1;
    if k <= n && n <= 21 {
        format!("{digits}{}", "0".repeat((n - k) as usize))
    } else if 0 < n && n <= 21 {
        format!("{}.{}", &digits[..n as usize], &digits[n as usize..])
    } else if -6 < n && n <= 0 {
        format!("0.{}{digits}", "0".repeat((-n) as usize))
    } else {
        let sign = if n - 1 < 0 { '-' } else { '+' };
        let exponent = (n - 1).abs();
        if k == 1 {
            format!("{digits}e{sign}{exponent}")
        } else {
            format!("{}.{}e{sign}{exponent}", &digits[..1], &digits[1..])
        }
    }
}

/// `x.toString(radix)` for a radix other than 10, if `x` is an integer below 2^53 (or NaN
/// or infinite). V8 writes fractions and larger numbers in ways this doesn't model.
fn integer_to_radix(x: f64, radix: u32) -> Option<String> {
    if x.is_nan() {
        return Some("NaN".to_string());
    }
    if x.is_infinite() {
        return Some(if x > 0.0 { "Infinity" } else { "-Infinity" }.to_string());
    }
    if x.fract() != 0.0 || x.abs() >= 9_007_199_254_740_992.0 {
        return None;
    }
    let mut value = x.abs() as u64;
    let mut digits = Vec::new();
    loop {
        digits.push(char::from_digit((value % u64::from(radix)) as u32, radix)?);
        value /= u64::from(radix);
        if value == 0 {
            break;
        }
    }
    if x < 0.0 {
        digits.push('-');
    }
    Some(digits.into_iter().rev().collect())
}

/// ToIntegerOrInfinity
fn to_integer_or_infinity(x: f64) -> f64 {
    if x.is_nan() {
        0.0
    } else {
        // `+ 0.0` turns -0 into 0
        x.trunc() + 0.0
    }
}

/// ToUint16, as `String.fromCharCode` takes its argument
fn to_uint16(x: f64) -> u16 {
    if x.is_finite() {
        x.trunc().rem_euclid(65536.0) as u16
    } else {
        0
    }
}

/// The index `at(relative)` reads in a sequence of `len`, if it is in range: a negative
/// one counts from the end
fn at_index(relative: f64, len: usize) -> Option<usize> {
    let index = if relative < 0.0 {
        len as f64 + relative
    } else {
        relative
    };
    (0.0..len as f64).contains(&index).then_some(index as usize)
}

/// Where `slice(relative)` starts in a sequence of `len`: a negative start counts from
/// the end
fn slice_start(relative: f64, len: usize) -> usize {
    let start = if relative < 0.0 {
        (len as f64 + relative).max(0.0)
    } else {
        relative.min(len as f64)
    };
    start as usize
}

/// Whether `escape` leaves `unit` as it is
fn escape_keeps(unit: u16) -> bool {
    u8::try_from(unit).is_ok_and(|byte| byte.is_ascii_alphanumeric() || b"@*_+-./".contains(&byte))
}

/// How long `escape(text)` is
fn escaped_len(text: &[u16]) -> usize {
    text.iter()
        .map(|&unit| match unit {
            _ if escape_keeps(unit) => 1,
            0..=0xFF => 3,
            _ => 6,
        })
        .sum()
}

/// `escape(text)`: `%XX` for other characters below 256, `%uXXXX` above
fn escape(text: &[u16]) -> Vec<u16> {
    let mut out = String::with_capacity(escaped_len(text));
    for &unit in text {
        match unit {
            _ if escape_keeps(unit) => out.push(char::from(unit as u8)),
            0..=0xFF => out.push_str(&format!("%{unit:02X}")),
            _ => out.push_str(&format!("%u{unit:04X}")),
        }
    }
    utf16(&out)
}

/// `unescape(text)`: `%XX` and `%uXXXX` become the character, anything else stays
fn unescape(text: &[u16]) -> Vec<u16> {
    let mut out = Vec::with_capacity(text.len());
    let mut i = 0;
    while i < text.len() {
        if text[i] == u16::from(b'%') {
            if text.get(i + 1) == Some(&u16::from(b'u')) {
                if let Some((value, _)) = hex_digits(&text[i + 2..], 4) {
                    out.push(value as u16);
                    i += 6;
                    continue;
                }
            }
            if let Some((value, _)) = hex_digits(&text[i + 1..], 2) {
                out.push(value as u16);
                i += 3;
                continue;
            }
        }
        out.push(text[i]);
        i += 1;
    }
    out
}

/// What `String(new Date(ms))` gives in UTC, as V8 writes it
fn date_string(ms: i64) -> String {
    chrono::DateTime::from_timestamp_millis(ms).map_or_else(
        || "Invalid Date".to_string(),
        |time| {
            time.format("%a %b %d %Y %H:%M:%S GMT+0000 (Coordinated Universal Time)")
                .to_string()
        },
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };
    use serde::Deserialize;

    /// The test vectors and the single expressions in `tests/test_fixtures/jsfuck.toml`,
    /// made by jsfuck.js and checked with node (see the comments in the file)
    #[derive(Deserialize)]
    struct Fixture {
        vector: Vec<Vector>,
        case: Vec<Case>,
    }

    /// `JSFuck.encode(plaintext, wrap, parent_scope)` from the jsfuck.js of `dialect`
    #[derive(Deserialize)]
    struct Vector {
        dialect: String,
        plaintext: String,
        wrap: bool,
        #[serde(default)]
        parent_scope: bool,
        code: String,
    }

    /// One expression, and what node says it gives: its `typeof` and `String()`, or that
    /// it throws
    #[derive(Deserialize)]
    struct Case {
        name: String,
        #[serde(default)]
        throws: bool,
        #[serde(rename = "type")]
        kind: Option<String>,
        string: Option<String>,
        code: String,
    }

    fn fixture() -> Fixture {
        toml::from_str(include_str!("../../tests/test_fixtures/jsfuck.toml"))
            .expect("tests/test_fixtures/jsfuck.toml parses")
    }

    /// The code of the vector for `plaintext` from `dialect`
    fn vector(dialect: &str, plaintext: &str, wrap: bool) -> String {
        fixture()
            .vector
            .into_iter()
            .find(|v| v.dialect == dialect && v.plaintext == plaintext && v.wrap == wrap)
            .unwrap_or_else(|| panic!("no {dialect} vector for {plaintext:?}"))
            .code
    }

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn crack(text: &str) -> CrackResult {
        Decoder::<JsFuckDecoder>::new().crack(text, &get_athena_checker())
    }

    /// The value of `code`, without the first check, and the steps it took
    fn evaluate(code: &str) -> (Result<Value, Error>, usize) {
        let mut evaluator = Evaluator::new(code.as_bytes());
        let value = evaluator.program();
        (value, evaluator.steps)
    }

    /// `typeof value`
    fn type_of(value: &Value) -> &'static str {
        match value {
            Value::Undefined => "undefined",
            Value::Bool(_) => "boolean",
            Value::Num(_) => "number",
            Value::Str(_) => "string",
            Value::Native(..) | Value::Func(_) => "function",
            Value::Code(_) => panic!("the value of a program that isn't run has no type"),
            _ => "object",
        }
    }

    #[test]
    fn issue_example_decodes() {
        // https://github.com/bee-san/Ciphey/issues/987: "false"[0] + "undefined"[0] +
        // "undefined"[1], the same in jsfuck.js 0.4.0 and 0.5.0
        let result = crack("(![]+[])[+[]]+([][[]]+[])[+[]]+([][[]]+[])[+!+[]]");
        assert_eq!(result.unencrypted_text.unwrap(), vec!["fun"]);
    }

    #[test]
    fn every_vector_decodes() {
        let fixture = fixture();
        assert_eq!(fixture.vector.len(), 28);
        for v in fixture.vector {
            assert_eq!(
                decode(&v.code).as_deref(),
                Ok(v.plaintext.as_str()),
                "{} encode({:?}, {}{})",
                v.dialect,
                v.plaintext,
                v.wrap,
                if v.parent_scope { ", true" } else { "" }
            );
        }
    }

    #[test]
    fn every_vector_takes_a_fraction_of_the_step_limit() {
        // The limits must leave plenty of room for real JSFuck: the longest vector (the 95
        // printable characters, 260,869 symbols from jsfuck.js 0.4.0) and the most
        // string-heavy ones stay under a fifth of them
        let mut most = 0;
        for v in fixture().vector {
            let (value, steps) = evaluate(&v.code);
            assert!(value.is_ok(), "{} {:?}", v.dialect, v.plaintext);
            most = most.max(steps);
        }
        assert!(most < MAX_STEPS / 5, "a vector took {most} steps");
    }

    #[test]
    fn both_dialects_are_identified() {
        // The English checker accepts the first two and LemmeKnow takes the last for a flag
        for plaintext in ["hello world", "a nice day", "flag{jsfuck}"] {
            for dialect in ["0.4.0", "0.5.0"] {
                let result = crack(&vector(dialect, plaintext, false));
                assert!(result.success, "{dialect} {plaintext:?}: {result:?}");
                assert_eq!(result.unencrypted_text.unwrap(), vec![plaintext]);
            }
        }
    }

    #[test]
    fn plaintext_athena_does_not_identify_is_still_returned() {
        // Athena counts non-ASCII as unprintable, so this isn't identified, but it decodes
        let result = crack(&vector("0.5.0", "café €", false));
        assert!(!result.success);
        assert_eq!(result.unencrypted_text.unwrap(), vec!["café €"]);
    }

    #[test]
    fn wrapped_programs_come_back_as_source() {
        // "Eval Source" wraps the program in Function(...)(), and 0.5.0's parent-scope
        // option in Function("return eval")()(...). The program's source is the value: it
        // is never run, so nothing calls alert or console.log.
        let mut wrapped = 0;
        for v in fixture().vector.into_iter().filter(|v| v.wrap) {
            let symbols = symbols(&v.code).unwrap();
            let value = Evaluator::new(&symbols).program();
            assert_eq!(
                value,
                Ok(Value::Code(utf16(&v.plaintext))),
                "{} {:?}",
                v.dialect,
                v.plaintext
            );
            wrapped += 1;
        }
        assert_eq!(wrapped, 7);
        let result = crack(&vector("0.4.0", "console.log(\"hello world\")", true));
        assert_eq!(
            result.unencrypted_text.unwrap(),
            vec!["console.log(\"hello world\")"]
        );
    }

    #[test]
    fn every_case_matches_node() {
        let fixture = fixture();
        assert!(fixture.case.len() > 90);
        for case in fixture.case {
            let (value, _) = evaluate(&case.code);
            if case.throws {
                assert_eq!(value, Err(Error::Unsupported), "{}", case.name);
                continue;
            }
            let value = value.unwrap_or_else(|error| panic!("{}: {error}", case.name));
            assert_eq!(Some(type_of(&value)), case.kind.as_deref(), "{}", case.name);
            let text = Evaluator::new(b"").string_of(value).unwrap();
            assert_eq!(
                String::from_utf16(&text).unwrap(),
                case.string.unwrap(),
                "{}",
                case.name
            );
        }
    }

    #[test]
    fn edge_values_are_returned() {
        // Values the checker decides on
        let cases = [
            ("+!+[]+[+[]]+[]+[]+[]+[]", "10"),
            ("!+[]+!+[]+!+[]+!+[]+!+[]+!+[]+!+[]+!+[]+[]", "8"),
            ("(![]+[])[+[]]+(![]+[])[+[]]+(![]+[])[+[]]", "fff"),
            ("[!+[]+!+[]+!+[]+!+[]]+[!+[]+!+[]]", "42"),
            ("[!+[]+!+[]+!+[]+!+[]+!+[]+!+[]+!+[]]+[]", "7"),
            // A number or a boolean is written as a string
            ("+!+[]+!+[]+!+[]+!+[]+!+[]+!+[]+!+[]", "7"),
            ("!![]+!![]+!![]+!![]+!![]+!![]+!![]", "7"),
            ("!(+!+[]+!+[]+!+[]+!+[]+!+[]+!+[])", "false"),
            // Whitespace and line breaks between the symbols don't matter, and `+ +` is
            // two pluses where `++` would be an increment
            (
                "(![] + [])[+[]] +\n([][[]] + [])[+[]] +\r\n([][[]]+[])[+!+[]]",
                "fun",
            ),
            ("[] + + [] + [] + [] + [] + [] + [] + []", "0"),
        ];
        for (code, expected) in cases {
            assert_eq!(decode(code).as_deref(), Ok(expected), "{code}");
        }
    }

    #[test]
    fn text_that_is_not_jsfuck_is_rejected_before_parsing() {
        let miss = "T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV";
        for text in [
            "",
            "   ",
            "😀",
            "hello world",
            miss,
            "++++++++[>+++++++++++++<-]>.+.",
            ".... . .-..",
            "aGVsbG8=",
            // Too short
            "[]",
            "+[]",
            "(![]+[])[+[]]",
            // Unbalanced
            "[[]+[]+[]+[]+[]+[]+[]+[]",
            "(![]+[])[+[]]+(![]+[])[+[]])",
            "]![]+[]+[]+[]+[]+[]+[]+[][",
            // `++` is the increment operator
            "[]++[]+[]+[]+[]+[]+[]+[]",
            // Nested 100 deep
            &format!("{}{}", "[".repeat(100), "]".repeat(100)),
        ] {
            assert_eq!(symbols(text), Err(Error::NotJsFuck), "{text:?}");
            assert!(crack(text).unencrypted_text.is_none(), "{text:?}");
        }
    }

    #[test]
    fn bad_expressions_fail_cleanly() {
        let filter = "(![]+[])[+[]]+([![]]+[][[]])[+!+[]+[+[]]]+(![]+[])[!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+!+[]]";
        let cases = [
            ("([)]+[]+[]+[]+[]+[]+[]+[]", Error::Syntax),
            ("(![]+[])[+[]]+[]![]+[]+[]", Error::Syntax),
            ("()+[]+[]+[]+[]+[]+[]+[]+[]", Error::Syntax),
            ("[][]+[]+[]+[]+[]+[]+[]+[]", Error::Syntax),
            ("[]+[]+[]+[]+[]+[]+[]+[]+", Error::Syntax),
            // Calling undefined and calling filter without a function both throw
            ("[][[]]()+[]+[]+[]+[]+[]", Error::Unsupported),
            (&format!("[][{filter}]()"), Error::Unsupported),
            // A function and an array aren't text
            (&format!("[][{filter}]"), Error::NotText),
            ("[[[[[[[[[[]]]]]]]]]]", Error::NotText),
        ];
        for (code, error) in cases {
            assert_eq!(decode(code), Err(error), "{code}");
            assert!(crack(code).unencrypted_text.is_none(), "{code}");
        }
        // "" is valid, but not a decoding
        let empty = "[]+[]+[]+[]+[]+[]+[]";
        assert_eq!(decode(empty).as_deref(), Ok(""));
        assert!(crack(empty).unencrypted_text.is_none());
    }

    #[test]
    fn limits_stop_the_evaluator() {
        // Every `+[]` is three steps: 2,000,000 of them are over the limit
        let long = format!("[]{}", "+[]".repeat(2_000_000));
        assert_eq!(decode(&long), Err(Error::TooBig));
        // Each `+[][[]]` adds "undefined": 120,000 of them make a string over 1,000,000
        let wide = format!("[][[]]+[]{}", "+[][[]]".repeat(120_000));
        assert_eq!(decode(&wide), Err(Error::TooBig));
        // A tenth as many is fine
        let fine = format!("[][[]]+[]{}", "+[][[]]".repeat(12_000));
        assert_eq!(decode(&fine).map(|text| text.len()), Ok(9 * 12_001));
        // A long run of unary operators is no deeper than one
        let unary = format!("{}[]", "!".repeat(100_001));
        assert_eq!(decode(&unary).as_deref(), Ok("false"));
        // The deepest nesting the first check allows evaluates without running out of
        // stack, in a debug build too, and one level more is rejected
        let deepest = format!("{}[]{}+[]", "([".repeat(31), "])".repeat(31));
        assert_eq!(decode(&deepest).as_deref(), Ok(""));
        let deeper = format!("([{deepest}])+[]");
        assert_eq!(decode(&deeper), Err(Error::NotJsFuck));
    }

    #[test]
    fn smaller_limits_are_enforced_everywhere() {
        // "false" made five times: 25 characters of strings
        let code = b"(![]+[])+(![]+[])+(![]+[])+(![]+[])+(![]+[])";
        let mut evaluator = Evaluator::new(code);
        evaluator.max_string_len = 24;
        assert_eq!(evaluator.program(), Err(Error::TooBig));
        let mut evaluator = Evaluator::new(code);
        evaluator.max_steps = 40;
        assert_eq!(evaluator.program(), Err(Error::TooBig));
        let mut evaluator = Evaluator::new(code);
        assert!(evaluator.program().is_ok());
        assert!(evaluator.steps > 40);
    }

    #[test]
    fn function_bodies_outside_the_table_are_not_run() {
        let body = |text: &str| run_function(utf16(text));
        assert_eq!(body("return escape"), native(Builtin::Escape));
        assert_eq!(body(" return  unescape ; "), native(Builtin::Unescape));
        assert_eq!(body("return eval"), native(Builtin::Eval));
        assert_eq!(body("return Date"), native(Builtin::Date));
        assert_eq!(body("return this"), Value::Global);
        assert_eq!(body("return{}"), Value::Object);
        assert_eq!(body("return/0/"), Value::RegExp(utf16("0")));
        assert_eq!(body("return new Date(200000000)"), Value::Date(200_000_000));
        assert_eq!(body("return\"\\110i\""), Value::Str(utf16("Hi")));
        assert_eq!(body(""), Value::Undefined);
        assert_eq!(body("return;"), Value::Undefined);
        for program in [
            "alert(1)",
            "return alert",
            "returnescape",
            // A line break after `return` ends the statement
            "return\nescape",
            "return escape()",
            "return\"a\"+1",
            "return\"unterminated",
            "return\"a\nb\"",
            "return/a(/",
            "return/0/g",
            "return new Date(1e3)",
            "return new Date(99999999999999999)",
            "return{a:1}",
        ] {
            assert_eq!(body(program), Value::Code(utf16(program)), "{program:?}");
        }
    }

    #[test]
    fn numbers_are_written_as_javascript_writes_them() {
        for (number, text) in [
            (0.0, "0"),
            (-0.0, "0"),
            (36.0, "36"),
            (-5.0, "-5"),
            (0.1, "0.1"),
            (123.456, "123.456"),
            (1e21, "1e+21"),
            (1.1e21, "1.1e+21"),
            (1e100, "1e+100"),
            (1e-6, "0.000001"),
            (1e-7, "1e-7"),
            (1e-10, "1e-10"),
            (2.5e-7, "2.5e-7"),
            (123_456_789_012_345_680_000.0, "123456789012345680000"),
            (5e-324, "5e-324"),
            (f64::MAX, "1.7976931348623157e+308"),
            (f64::INFINITY, "Infinity"),
            (f64::NEG_INFINITY, "-Infinity"),
            (f64::NAN, "NaN"),
        ] {
            assert_eq!(number_to_string(number), text);
        }
        for i in 0..=36 {
            assert_eq!(number_to_string(f64::from(i)), i.to_string());
        }
        assert_eq!(integer_to_radix(101.0, 21).as_deref(), Some("4h"));
        assert_eq!(integer_to_radix(0.0, 2).as_deref(), Some("0"));
        assert_eq!(integer_to_radix(0.5, 2), None);
        assert_eq!(integer_to_radix(1e300, 2), None);
    }

    #[test]
    fn strings_are_read_as_javascript_reads_them() {
        let number = |text: &str| string_to_number(&utf16(text));
        assert_eq!(number(""), Ok(0.0));
        assert_eq!(number(" \n\t12\u{a0}"), Ok(12.0));
        assert_eq!(number("1e1000"), Ok(f64::INFINITY));
        assert_eq!(number(".0000000001"), Ok(1e-10));
        assert_eq!(number("0000000001"), Ok(1.0));
        assert_eq!(number("+Infinity"), Ok(f64::INFINITY));
        assert_eq!(number("0x10"), Ok(16.0));
        assert_eq!(number("0o17"), Ok(15.0));
        for text in [
            "inf", "infinity", "nan", "NaN", "1e", "e5", "1_0", "--1", "-0x10", "0x", "0x1g", "1 2",
        ] {
            assert!(number(text).unwrap().is_nan(), "{text:?}");
        }
        assert_eq!(number("0x20000000000001"), Err(Error::Unsupported));

        let literal = |text: &str| {
            string_literal(&utf16(text)).map(|units| String::from_utf16(&units).unwrap())
        };
        assert_eq!(
            literal(r#""\570\101\40\1011\u0041\x41\u{1F600}\8\q\'\"""#).as_deref(),
            Some("/0A A1AA😀8q'\"")
        );
        assert_eq!(literal("\"a\\\nb\\\r\nc\"").as_deref(), Some("abc"));
        assert_eq!(
            literal(r#""\0\b\f\n\r\t\v""#).as_deref(),
            Some("\0\u{8}\u{c}\n\r\t\u{b}")
        );
        // jsfuck.js 0.5.0 writes an emoji as its two surrogates
        assert_eq!(literal(r#""\ud83d\ude00""#).as_deref(), Some("😀"));
        for bad in [
            r#""\x4""#,
            r#""\u004""#,
            r#""\u{}""#,
            r#""\u{110000}""#,
            r#""a"b""#,
            "\"a",
        ] {
            assert_eq!(literal(bad), None, "{bad:?}");
        }
    }

    #[test]
    fn escape_and_unescape_match_javascript() {
        let text = utf16("Az09@*_+-./ <é€~");
        assert_eq!(
            String::from_utf16(&escape(&text)).unwrap(),
            "Az09@*_+-./%20%3C%E9%u20AC%7E"
        );
        assert_eq!(escaped_len(&text), escape(&text).len());
        assert_eq!(unescape(&escape(&text)), text);
        assert_eq!(
            String::from_utf16(&unescape(&utf16("%4b%u20Ac%%2%u12%"))).unwrap(),
            "K€%%2%u12%"
        );
    }

    #[test]
    fn dates_are_written_in_utc() {
        assert_eq!(
            date_string(200_000_000),
            "Sat Jan 03 1970 07:33:20 GMT+0000 (Coordinated Universal Time)"
        );
        assert_eq!(&date_string(24_000_000_000)[4..7], "Oct");
        // jsfuck.js reads G, M and T at 25 to 27
        assert_eq!(&date_string(0)[25..28], "GMT");
    }

    #[test]
    fn decoder_is_registered() {
        let decoders = crate::filtration_system::get_decoder_by_name("JSFuck");
        assert_eq!(decoders.components.len(), 1);
        let decoder = &decoders.components[0];
        // `program` exempts it from the search's rule that results are at least 5% of
        // the input: "hello world" is 11 characters from 4,103
        assert!(decoder.get_tags().contains(&"program"));
        assert!(decoder.get_tags().contains(&"decoder"));
        assert!(crate::decoders::DECODER_MAP.contains_key("JSFuck"));
    }
}
