//! Decode JSON Web Tokens (JWT, [RFC 7519](https://datatracker.ietf.org/doc/html/rfc7519))
//! in JWS compact serialization
//! ([RFC 7515 §7.1](https://datatracker.ietf.org/doc/html/rfc7515#section-7.1)):
//! `BASE64URL(header).BASE64URL(payload).BASE64URL(signature)`.
//!
//! A JWT is signed, not encrypted, so the header and payload can be read without the key.
//! The payload is returned exactly as it was encoded and the decoded header becomes the
//! result's key. The signature is not verified.
//!
//! The checkers identify hardly any JSON, so a well-formed token is accepted on its
//! structure unless a regex crib is set. `identify` documents the order of the checks.

use crate::checkers::checker_result::CheckResult;
use crate::checkers::checker_type::{Check, Checker};
use crate::checkers::english::EnglishChecker;
use crate::checkers::human_checker::human_checker;
use crate::checkers::CheckerTypes;
use crate::config::get_config;
use base64::{engine::general_purpose, Engine as _};
use gibberish_or_not::Sensitivity;
use lemmeknow::Identifier;
use log::trace;
use serde_json::{Map, Value};

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

/// With a regex crib, at most this many string values of the payload are checked
const MAX_CRIB_VALUES: usize = 32;

/// With a regex crib, string values nested deeper than this are not checked.
/// The payload's own members are at depth 1.
const MAX_CRIB_DEPTH: usize = 3;

/// The JWT decoder, call:
/// `let jwt_decoder = Decoder::<JwtDecoder>::new()` to create a new instance
/// And then call:
/// `result = jwt_decoder.crack(input)` to decode a JWT
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::jwt_decoder::JwtDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_jwt = Decoder::<JwtDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // The example token from jwt.io
/// let token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c";
/// let result = decode_jwt.crack(token, &checker);
/// assert!(result.success);
/// assert_eq!(
///     result.unencrypted_text.unwrap()[0],
///     r#"{"sub":"1234567890","name":"John Doe","iat":1516239022}"#
/// );
/// // The decoded header is kept as the key
/// assert_eq!(result.key.unwrap(), r#"{"alg":"HS256","typ":"JWT"}"#);
/// ```
pub struct JwtDecoder;

impl Crack for Decoder<JwtDecoder> {
    fn new() -> Decoder<JwtDecoder> {
        Decoder {
            name: "JWT",
            description: "A JSON Web Token (JWT) in JWS compact serialization is base64url(header).base64url(payload).base64url(signature), where the header and payload are JSON objects. It is signed, not encrypted, so the payload (the claims) can be read without the key. The signature is not verified; the decoded header is returned as the key.",
            link: "https://datatracker.ietf.org/doc/html/rfc7519",
            tags: vec!["jwt", "json", "web", "token", "decoder"],
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes the payload of a JWT. Text that doesn't start like one is rejected without
    /// further work, so the decoder costs the search next to nothing.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying JWT with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(token) = parse(text) else {
            trace!("Not a JWT: {:?}", text);
            return results;
        };
        identify(&mut results, token, checker, get_config().regex.is_some());

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Marker type for [`jwt_structure_checker`]
pub(crate) struct JwtStructure;

/// The checker named on results that were accepted because the token is well formed: a
/// base64url JSON header with an `alg`, and a base64url JSON payload. Random text can't
/// satisfy that. It's registered in `CHECKER_MAP` so cached results can be read back.
pub(crate) fn jwt_structure_checker() -> Checker<JwtStructure> {
    Checker {
        name: "JWT Structure",
        description: "Well-formed JWT: base64url JSON header with alg + JSON payload",
        link: "https://datatracker.ietf.org/doc/html/rfc7519",
        tags: vec!["jwt", "structure"],
        expected_runtime: 0.0,
        popularity: 0.5,
        lemmeknow_config: Identifier::default(),
        sensitivity: Sensitivity::Medium,
        enhanced_detector: None,
        _phantom: std::marker::PhantomData,
    }
}

/// The decoded parts of a JWT
struct Jwt {
    /// The header JSON, exactly as it was encoded
    header: String,
    /// The payload JSON, exactly as it was encoded
    payload: String,
    /// The payload's members
    claims: Map<String, Value>,
}

/// Parses `text` as a JWS compact serialization whose header and payload are JSON objects
/// and whose header has a string `alg`. Surrounding whitespace and a `Bearer ` prefix are
/// ignored. The cheapest checks come first, so most text is rejected straight away.
fn parse(text: &str) -> Option<Jwt> {
    let token = strip_bearer(text.trim());
    // `eyJ` is base64url for `{"`, which every header starts with
    if !token.starts_with("eyJ") {
        return None;
    }

    // Exactly three parts. A JWE has five, and its payload is encrypted.
    let mut parts = token.split('.');
    let (header, payload, signature) = (parts.next()?, parts.next()?, parts.next()?);
    if parts.next().is_some() {
        return None;
    }
    let header = base64url(header)?;
    let payload = base64url(payload)?;
    // The signature is never decoded, and is empty for `"alg":"none"`
    base64url(signature)?;
    if payload.is_empty() {
        return None;
    }

    let (header, header_fields) = decode_object(header)?;
    if !header_fields.get("alg").is_some_and(Value::is_string) {
        return None;
    }
    let (payload, claims) = decode_object(payload)?;
    Some(Jwt {
        header,
        payload,
        claims,
    })
}

/// `token` without a leading `Bearer ` (the HTTP authentication scheme for these tokens,
/// RFC 6750 §2.1), which is matched case-insensitively
fn strip_bearer(token: &str) -> &str {
    let bytes = token.as_bytes();
    if bytes.len() > 7
        && bytes[..6].eq_ignore_ascii_case(b"bearer")
        && bytes[6].is_ascii_whitespace()
    {
        // The first seven bytes are ASCII, so this slices on a character boundary
        token[7..].trim_start()
    } else {
        token
    }
}

/// `part` without trailing `=` padding, if what's left is base64url (`[A-Za-z0-9_-]*`)
fn base64url(part: &str) -> Option<&str> {
    let part = part.trim_end_matches('=');
    part.bytes()
        .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-' || byte == b'_')
        .then_some(part)
}

/// Decodes a base64url part that holds a JSON object in UTF-8. Returns the JSON text
/// and the parsed object.
fn decode_object(part: &str) -> Option<(String, Map<String, Value>)> {
    let bytes = general_purpose::URL_SAFE_NO_PAD.decode(part).ok()?;
    let json = String::from_utf8(bytes).ok()?;
    let object = serde_json::from_str(&json).ok()?;
    Some((json, object))
}

/// Fills in `results` for a decoded token. Its payload is the plaintext if, in this order:
/// 1. the checker identifies the payload;
/// 2. with a regex crib (`crib`), the checker identifies one of the payload's string
///    values, e.g. a flag that a crib anchored with `^` and `$` matches;
/// 3. without a crib, always, as the token is well formed. The human checker is asked first.
///
/// Step 3 is what lets the search finish on a JWT. It's skipped with a crib, because then
/// only text that matches the crib may end the search.
///
/// The payload is returned either way, so the search can carry on from it.
fn identify(results: &mut CrackResult, token: Jwt, checker: &CheckerTypes, crib: bool) {
    let payload_result = checker.check(&token.payload);
    if counts(&payload_result) {
        results.update_checker(&payload_result);
    } else if crib {
        let value_result = string_values(&token.claims)
            .into_iter()
            .map(|value| checker.check(value))
            .find(counts);
        if let Some(value_result) = value_result {
            results.update_checker(&value_result);
        }
    } else {
        let structure_result = structure_result(&token.payload);
        if human_checker(&structure_result) {
            results.update_checker(&structure_result);
        }
    }

    results.unencrypted_text = Some(vec![token.payload]);
    results.key = Some(token.header);
}

/// Whether a checker's result for the payload or one of its values identifies the
/// plaintext. English-checker hits don't count: the search discards English results that
/// are over a third punctuation, which JSON with short values is, and "JSON Web Token"
/// describes the payload better anyway.
fn counts(result: &CheckResult) -> bool {
    result.is_identified && result.checker_name != Checker::<EnglishChecker>::new().name
}

/// The result for a well-formed token that no checker identified
pub(crate) fn structure_result(payload: &str) -> CheckResult {
    let mut result = CheckResult::new(&jwt_structure_checker());
    result.is_identified = true;
    result.text = payload.to_string();
    result.description = "JSON Web Token".to_string();
    result
}

/// The payload's non-empty string values in document order: at most [`MAX_CRIB_VALUES`] of
/// them, nested at most [`MAX_CRIB_DEPTH`] deep
fn string_values(claims: &Map<String, Value>) -> Vec<&str> {
    let mut strings = Vec::new();
    for value in claims.values() {
        collect_strings(value, 1, &mut strings);
    }
    strings
}

/// Adds the non-empty strings in `value`, which is nested `depth` deep, to `strings`
fn collect_strings<'a>(value: &'a Value, depth: usize, strings: &mut Vec<&'a str>) {
    if strings.len() == MAX_CRIB_VALUES {
        return;
    }
    match value {
        Value::String(string) if !string.is_empty() => strings.push(string),
        Value::Array(items) if depth < MAX_CRIB_DEPTH => {
            for item in items {
                collect_strings(item, depth + 1, strings);
            }
        }
        Value::Object(members) if depth < MAX_CRIB_DEPTH => {
            for member in members.values() {
                collect_strings(member, depth + 1, strings);
            }
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::{identify, parse, string_values, JwtDecoder, MAX_CRIB_VALUES};
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            lemmeknow_checker::LemmeKnow,
            CheckerTypes, CHECKER_MAP,
        },
        decoders::{
            crack_results::CrackResult,
            interface::{Crack, Decoder},
            DECODER_MAP,
        },
        filtration_system::get_decoder_by_name,
    };
    use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};

    /// The example token from jwt.io (and the issue): HS256 with the secret
    /// `your-256-bit-secret`. Its signature was checked with PyJWT and with HMAC-SHA256.
    const JWT_IO: &str = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c";
    /// The payload of [`JWT_IO`]
    const JWT_IO_PAYLOAD: &str = r#"{"sub":"1234567890","name":"John Doe","iat":1516239022}"#;
    /// The header of [`JWT_IO`]
    const JWT_IO_HEADER: &str = r#"{"alg":"HS256","typ":"JWT"}"#;

    /// `"alg":"none"` with an empty signature (CyberChef `JWT Sign`, from the issue's plan)
    const ALG_NONE: &str = "eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJzdWIiOiJjdGYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3OTA4NzY1NDB9.";
    /// The payload of [`ALG_NONE`]
    const ALG_NONE_PAYLOAD: &str = r#"{"sub":"ctf","role":"admin","iat":1790876540}"#;

    /// A CTF-style flag claim, `"alg":"none"` (from the issue's plan)
    const FLAG: &str =
        "eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJmbGFnIjoiZmxhZ3tqd3RfaXNfbm90X2VuY3J5cHRpb259In0.";
    /// The payload of [`FLAG`]
    const FLAG_PAYLOAD: &str = r#"{"flag":"flag{jwt_is_not_encryption}"}"#;

    /// Helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    /// Runs the JWT decoder on `text` with the Athena checker
    fn crack(text: &str) -> CrackResult {
        Decoder::<JwtDecoder>::new().crack(text, &get_athena_checker())
    }

    /// Runs the JWT decoder on `text` as if a regex crib was set, with `checker` standing
    /// in for the regex checker (which reads the crib from the global config)
    fn crack_with_crib(text: &str, checker: &CheckerTypes) -> CrackResult {
        let decoder = Decoder::<JwtDecoder>::new();
        let mut results = CrackResult::new(&decoder, text.to_string());
        identify(&mut results, parse(text).expect("not a JWT"), checker, true);
        results
    }

    /// Asserts `text` is decoded to `payload` and accepted as plaintext
    fn assert_decodes_to(text: &str, payload: &str) {
        let result = crack(text);
        assert_eq!(
            result.unencrypted_text,
            Some(vec![payload.to_string()]),
            "{text:?}"
        );
        assert!(result.success, "{text:?} was not accepted: {result:?}");
    }

    /// Asserts the decoder rejects `text` without decoding anything
    fn assert_not_decoded(text: &str) {
        let result = crack(text);
        assert!(!result.success, "{text:?}");
        assert!(result.unencrypted_text.is_none(), "{text:?}: {result:?}");
        assert!(result.key.is_none(), "{text:?}");
    }

    #[test]
    fn jwt_io_example_decodes() {
        let result = crack(JWT_IO);
        assert_eq!(
            result.unencrypted_text,
            Some(vec![JWT_IO_PAYLOAD.to_string()])
        );
        assert_eq!(result.key.as_deref(), Some(JWT_IO_HEADER));
        // No checker identifies the payload, so it's accepted on the token's structure
        assert!(result.success);
        assert_eq!(result.checker_name, "JWT Structure");
        assert_eq!(result.decoder, "JWT");
    }

    #[test]
    fn rfc_7519_example_payload_is_returned_verbatim() {
        // RFC 7519 §3.1 (HS256, also RFC 7515 Appendix A.1). The JSON has CRLF line breaks,
        // which must survive: the payload is returned as encoded, not re-serialized.
        let token = "eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJqb2UiLA0KICJleHAiOjEzMDA4MTkzODAsDQogImh0dHA6Ly9leGFtcGxlLmNvbS9pc19yb290Ijp0cnVlfQ.dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk";
        let payload =
            "{\"iss\":\"joe\",\r\n \"exp\":1300819380,\r\n \"http://example.com/is_root\":true}";
        assert_decodes_to(token, payload);
        assert_eq!(
            crack(token).key.as_deref(),
            Some("{\"typ\":\"JWT\",\r\n \"alg\":\"HS256\"}")
        );
    }

    #[test]
    fn unsecured_jwt_with_empty_signature_decodes() {
        assert_decodes_to(ALG_NONE, ALG_NONE_PAYLOAD);
        // RFC 7519 §6.1, the example Unsecured JWT
        assert_decodes_to(
            "eyJhbGciOiJub25lIn0.eyJpc3MiOiJqb2UiLA0KICJleHAiOjEzMDA4MTkzODAsDQogImh0dHA6Ly9leGFtcGxlLmNvbS9pc19yb290Ijp0cnVlfQ.",
            "{\"iss\":\"joe\",\r\n \"exp\":1300819380,\r\n \"http://example.com/is_root\":true}",
        );
    }

    #[test]
    fn flag_claim_decodes() {
        assert_decodes_to(FLAG, FLAG_PAYLOAD);
    }

    #[test]
    fn surrounding_whitespace_and_bearer_prefix_are_ignored() {
        for text in [
            format!("  {JWT_IO}\n"),
            format!("\t{JWT_IO} \r\n"),
            format!("Bearer {JWT_IO}"),
            format!("bearer {JWT_IO}"),
            format!("BEARER   {JWT_IO}"),
            format!(" Bearer\t{JWT_IO}\n"),
        ] {
            assert_decodes_to(&text, JWT_IO_PAYLOAD);
            assert_eq!(crack(&text).key.as_deref(), Some(JWT_IO_HEADER), "{text:?}");
        }
        // Only as a separate word
        assert_not_decoded(&format!("Bearer{JWT_IO}"));
    }

    #[test]
    fn base64_padding_is_tolerated() {
        // {"alg":"none"} and {"y":2}, both padded
        assert_decodes_to("eyJhbGciOiJub25lIn0=.eyJ5IjoyfQ==.", r#"{"y":2}"#);
    }

    #[test]
    fn wrong_number_of_parts_is_not_decoded() {
        // One part: the header alone, or base64 of a JSON object
        assert_not_decoded("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9");
        assert_not_decoded("eyJmb28iOiJiYXIifQ==");
        assert_not_decoded("eyJ");
        // Two parts
        assert_not_decoded(
            "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ",
        );
        // Four parts
        assert_not_decoded(&format!("{JWT_IO}.c2ln"));
        // A JWE (five parts, RFC 7516 Appendix A.3.7): the payload is encrypted
        assert_not_decoded("eyJhbGciOiJBMTI4S1ciLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0.6KB707dM9YTIgHtLvtgWQ8mKwboJW3of9locizkDTHzBC2IlrT1oOQ.AxY8DCtDaGlsbGljb3RoZQ.KDlTtXchhZTGufMYmOYGS4HffxPSUrfmqCHXaI9wOGY.U0m_YmjN04DJvceFICbCVQ");
        // Empty payload
        assert_not_decoded("eyJhbGciOiJub25lIn0..c2ln");
    }

    #[test]
    fn invalid_base64url_is_not_decoded() {
        // `+` and `/` are standard base64, not base64url
        assert_not_decoded("eyJhbGciOiJub25lIn0.eyJ5Ijoy+Q.");
        assert_not_decoded("eyJhbGciOiJub25lIn0.eyJ5IjoyfQ.c2l/Zw");
        // Padding is only allowed at the end of a part
        assert_not_decoded("eyJhbGciOiJub25lIn0.eyJ5I=joyfQ.");
        // A length that no base64 encoding has
        assert_not_decoded("eyJhbGciOiJub25lIn0.eyJ5IjoyfQAAA.");
        // Whitespace inside the token
        assert_not_decoded("eyJhbGciOiJub25lIn0. eyJ5IjoyfQ.");
    }

    #[test]
    fn header_without_a_string_alg_is_not_decoded() {
        // {"x":1} (from the issue's plan)
        assert_not_decoded("eyJ4IjoxfQ.eyJ5IjoyfQ.sig");
        // {"alg":1}
        assert_not_decoded("eyJhbGciOjF9.eyJ5IjoyfQ.");
        // {"alg":"none" (truncated)
        assert_not_decoded("eyJhbGciOiJub25lIg.eyJ5IjoyfQ.");
    }

    #[test]
    fn payload_that_is_not_a_json_object_is_not_decoded() {
        // [1,2]
        assert_not_decoded("eyJhbGciOiJub25lIn0.WzEsMl0.");
        // "eyJ"
        assert_not_decoded("eyJhbGciOiJub25lIn0.ImV5SiI.");
        // {"y":2 (truncated)
        assert_not_decoded("eyJhbGciOiJub25lIn0.eyJ5Ijoy.");
    }

    #[test]
    fn non_utf8_is_not_decoded() {
        // Header {"a<0xff>":1}
        assert_not_decoded("eyJh_yI6MX0.eyJ5IjoyfQ.");
        // Payload {"y":"<0xff>"}
        assert_not_decoded("eyJhbGciOiJub25lIn0.eyJ5Ijoi_yJ9.");
    }

    #[test]
    fn empty_string_emoji_and_english_are_not_decoded() {
        assert_not_decoded("");
        assert_not_decoded("😀");
        assert_not_decoded("eyJ😀.eyJ5IjoyfQ.");
        assert_not_decoded("hello world");
        assert_not_decoded("hello my name is panicky mc panic face!");
    }

    #[test]
    fn deeply_nested_payload_is_rejected_without_overflowing_the_stack() {
        // serde_json gives up after 128 levels of nesting, so a hostile token can't make
        // the decoder overflow the stack (which aborts the process in release builds)
        let payload = format!("{{\"a\":{}{}}}", "[".repeat(100_000), "]".repeat(100_000));
        assert_not_decoded(&format!(
            "eyJhbGciOiJub25lIn0.{}.",
            URL_SAFE_NO_PAD.encode(payload)
        ));
    }

    #[test]
    fn english_checker_hit_on_the_payload_is_reported_as_a_jwt() {
        // {"message":"hello there my good friend, how are you doing today"}, which the
        // English checker identifies
        let result = crack("eyJhbGciOiJub25lIn0.eyJtZXNzYWdlIjoiaGVsbG8gdGhlcmUgbXkgZ29vZCBmcmllbmQsIGhvdyBhcmUgeW91IGRvaW5nIHRvZGF5In0.");
        assert!(result.success);
        assert_eq!(result.checker_name, "JWT Structure");
    }

    #[test]
    fn with_a_crib_a_string_value_must_be_identified() {
        // The LemmeKnow checker stands in for the regex checker here
        let checker = CheckerTypes::CheckLemmeKnow(Checker::<LemmeKnow>::new());

        // The flag is a value, so a crib anchored to it doesn't match the whole payload
        let result = crack_with_crib(FLAG, &checker);
        assert!(result.success);
        assert_eq!(result.checker_name, "LemmeKnow Checker");
        assert_eq!(
            result.unencrypted_text,
            Some(vec![FLAG_PAYLOAD.to_string()])
        );

        // Nothing matches, so the token is not accepted on its structure, but the payload
        // is still returned for the search to carry on from
        let result = crack_with_crib(ALG_NONE, &checker);
        assert!(!result.success);
        assert_eq!(result.checker_name, "");
        assert_eq!(
            result.unencrypted_text,
            Some(vec![ALG_NONE_PAYLOAD.to_string()])
        );
    }

    #[test]
    fn string_values_are_bounded() {
        // Values nested more than three deep are skipped, as are numbers and empty strings:
        // {"a":"one","b":{"c":"two","d":{"e":"three","f":{"g":"four"}}},
        //  "h":["five",["six",["seven"]],"",1]}
        let token = parse(
            "eyJhbGciOiJub25lIn0.eyJhIjoib25lIiwiYiI6eyJjIjoidHdvIiwiZCI6eyJlIjoidGhyZWUiLCJmIjp7ImciOiJmb3VyIn19fSwiaCI6WyJmaXZlIixbInNpeCIsWyJzZXZlbiJdXSwiIiwxXX0.",
        )
        .expect("a JWT");
        assert_eq!(
            string_values(&token.claims),
            ["one", "two", "three", "five", "six"]
        );

        // At most MAX_CRIB_VALUES of them
        let claims = (0..MAX_CRIB_VALUES + 8)
            .map(|i| format!("\"k{i}\":\"v{i}\""))
            .collect::<Vec<_>>()
            .join(",");
        let claims = serde_json::from_str(&format!("{{{claims}}}")).unwrap();
        let values = string_values(&claims);
        assert_eq!(values.len(), MAX_CRIB_VALUES);
        assert_eq!(values[0], "v0");
    }

    #[test]
    fn result_can_be_read_back_from_the_cache() {
        // The cache stores results as JSON and looks the decoder and checker up by name
        let result = crack(JWT_IO);
        let json = result.get_json().unwrap();
        let cached: CrackResult = serde_json::from_str(&json).unwrap();
        assert_eq!(cached.decoder, "JWT");
        assert_eq!(cached.checker_name, "JWT Structure");
        assert!(cached.success);
        assert_eq!(cached.key, result.key);
        assert_eq!(cached.unencrypted_text, result.unencrypted_text);
    }

    #[test]
    fn decoder_and_checker_are_registered() {
        let decoders = get_decoder_by_name("JWT");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "JWT");
        assert!(DECODER_MAP.contains_key("JWT"));
        assert!(CHECKER_MAP.contains_key("JWT Structure"));
    }
}
