//! Crack the keyboard shift cipher, where every key was replaced by a neighbouring key on
//! the same keyboard: one or two keys to the right or left in its row, or the key above or
//! below it. `hello world` shifted one key to the right on US QWERTY is `jr;;p ept;f`.
//! Case is kept (`H` becomes `J`), spaces are kept, and a key at the end of a row wraps
//! round to the other end, as on dCode.
//! References: <https://www.dcode.fr/keyboard-shift-cipher>, and the key rows of
//! xkeyboard-config's `symbols/us`, `symbols/fr` and `symbols/de`
//! (<https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config>).
//!
//! The decoder undoes 14 shifts, each of them a fixed table:
//! * US QWERTY, every key of the four rows (`` `1234567890-= ``, `qwertyuiop[]\`,
//!   `asdfghjkl;'`, `zxcvbnm,./` and the same keys with Shift): 1 or 2 keys to the right
//!   or left.
//! * US QWERTY, the key above or below, in the 4 × 10 grid `1234567890` / `qwertyuiop` /
//!   `asdfghjkl;` / `zxcvbnm,./` (and with Shift). Columns wrap round too, so `z` up is
//!   `a` and `1` up is `z`. The keys outside the grid stay as they are.
//! * US QWERTY letters only (dCode's "no symbols"), rows `qwertyuiop` / `asdfghjkl` /
//!   `zxcvbnm`: 1 or 2 keys to the right or left, so `p` right is `q`.
//! * The letters of AZERTY (`azertyuiop` / `qsdfghjklm` / `wxcvbn`) and of QWERTZ
//!   (`qwertzuiop` / `asdfghjkl` / `yxcvbnm`): 1 key to the right or left.
//!
//! Reading the keys typed on one layout as another (QWERTY typed, Dvorak read) is a
//! different cipher, and not this decoder's.
//!
//! All 14 decodings are cheap byte lookups, but checking each of them for plaintext isn't,
//! so they are ranked first, best first, by how English their pairs of adjacent characters
//! look, and only the best two are checked, with Low sensitivity for gibberish detection.
//! The key of a result is the name of the shift that encrypted it, such as
//! `QWERTY right 1`. Ciphey runs every decoder on every text the search expands, so text
//! that can't be a shift of English (non-ASCII text, Base64 and the other encodings, text
//! that changes case inside its words) is turned away first, in one pass over its bytes.

use crate::checkers::CheckerTypes;
use crate::decoders::affine_decoder::BIGRAM_LOG_PROBS;
use crate::decoders::interface::check_string_success;
use gibberish_or_not::Sensitivity;
use once_cell::sync::Lazy;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::trace;

/// The Keyboard shift cracker, call:
/// `let keyboard_shift_decoder = Decoder::<KeyboardShiftDecoder>::new()` to create a new
/// instance
/// And then call:
/// `result = keyboard_shift_decoder.crack(input, &checker)` to crack a keyboard shift
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::keyboard_shift_decoder::KeyboardShiftDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_keyboard_shift = Decoder::<KeyboardShiftDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // `hello world`, every key moved one to the right on a US QWERTY keyboard
/// let result = decode_keyboard_shift.crack("jr;;p ept;f", &checker);
/// assert!(result.success);
/// // If it succeeds, the 0th element is the plaintext, else it contains up to 3
/// // decodings with the best-ranked shifts
/// assert_eq!(result.unencrypted_text.unwrap()[0], "hello world");
/// assert_eq!(result.key.unwrap(), "QWERTY right 1");
/// ```
pub struct KeyboardShiftDecoder;

/// US QWERTY, every key of each row from left to right, without Shift.
const QWERTY_ROWS: [&str; 4] = [
    "`1234567890-=",
    "qwertyuiop[]\\",
    "asdfghjkl;'",
    "zxcvbnm,./",
];

/// [`QWERTY_ROWS`] with Shift held.
const QWERTY_SHIFTED_ROWS: [&str; 4] = [
    "~!@#$%^&*()_+",
    "QWERTYUIOP{}|",
    "ASDFGHJKL:\"",
    "ZXCVBNM<>?",
];

/// The 4 × 10 grid of US QWERTY keys that shift up and down, top row first.
const QWERTY_GRID: [&str; 4] = ["1234567890", "qwertyuiop", "asdfghjkl;", "zxcvbnm,./"];

/// [`QWERTY_GRID`] with Shift held.
const QWERTY_SHIFTED_GRID: [&str; 4] = ["!@#$%^&*()", "QWERTYUIOP", "ASDFGHJKL:", "ZXCVBNM<>?"];

/// The letter rows of US QWERTY, in both cases.
const QWERTY_LETTERS: [&str; 6] = [
    "qwertyuiop",
    "asdfghjkl",
    "zxcvbnm",
    "QWERTYUIOP",
    "ASDFGHJKL",
    "ZXCVBNM",
];

/// The letter rows of French AZERTY, in both cases.
const AZERTY_LETTERS: [&str; 6] = [
    "azertyuiop",
    "qsdfghjklm",
    "wxcvbn",
    "AZERTYUIOP",
    "QSDFGHJKLM",
    "WXCVBN",
];

/// The letter rows of German QWERTZ, in both cases.
const QWERTZ_LETTERS: [&str; 6] = [
    "qwertzuiop",
    "asdfghjkl",
    "yxcvbnm",
    "QWERTZUIOP",
    "ASDFGHJKL",
    "YXCVBNM",
];

/// How many of the best-ranked decodings are run through the checker. A Python prototype
/// of this ranking put the plaintext first for 139 and second for 1 of 140 ciphertexts
/// (10 English texts under each of the 14 shifts, see #976).
const CANDIDATES_CHECKED: usize = 2;

/// How many decodings are returned for the search to keep exploring when none of the
/// checked ones is plaintext.
const CANDIDATES_RETURNED: usize = 3;

/// Pre-check: the fewest ASCII letters worth cracking. Every shift moves every letter.
const MIN_LETTERS: usize = 1;

/// Pre-check: the fewest characters other than whitespace worth cracking. Shorter text
/// can't be ranked, and the search drops results that short anyway.
const MIN_NON_WHITESPACE: usize = 4;

/// Pre-check: with at least this many pairs of adjacent ASCII letters, at most one pair in
/// [`MAX_LOWER_UPPER_PAIRS_ONE_IN`] may be a lowercase letter followed by an uppercase one
/// (`aB`). Fewer pairs say too little to tell.
const MIN_PAIRS_FOR_CASE_CHECK: usize = 20;

/// A shift keeps the case of every letter, and English almost never changes case inside a
/// word, so a keyboard shift of English doesn't either: at most one pair in 11 in Project
/// Gutenberg books and Ciphey's docs (see the Affine cracker, which has the same check).
/// Base64 and its Caesar and rot47 shifts, the commonest text the search hands every
/// decoder, do it about one pair in four, and so does the gibberish of the benchmarks.
const MAX_LOWER_UPPER_PAIRS_ONE_IN: usize = 8;

/// One word at least this long, made only of the characters of Base64 and with a digit in
/// it (see [`is_encoded_word`]), is far more often Base64, Base32, Base36, Base58 or hex,
/// which the search sees all the time, than a keyboard shift. Its decodings are still
/// checked, so a shifted flag or password in one word is found, but the ones the checker
/// doesn't accept aren't handed back: they would look like encodings too and send the
/// search down dead ends, which costs far more than the decodings themselves.
const MIN_ENCODED_WORD_LEN: usize = 16;

/// The score of a pair of adjacent characters that aren't both letters, such as `;` or `[`
/// inside a word, which a shift that went the wrong way leaves behind. It is about the
/// `ln P` of a rare English letter pair, so a flag's `_` and `{}` don't drown it.
const OTHER_PAIR_LOG_PROB: f32 = -10.0;

/// A keyboard shift this decoder undoes.
struct Table {
    /// The layout and the way the encoder moved each key, such as `QWERTY right 1`. It is
    /// the key of the results this table decodes.
    name: &'static str,
    /// The byte each ASCII byte decodes to. Bytes that aren't keys of the table decode to
    /// themselves.
    decode: [u8; 128],
}

/// Every shift this decoder undoes. When two give the same decoding, or tie in the
/// ranking, the one listed first wins, so the commoner shifts come first.
static TABLES: Lazy<Vec<Table>> = Lazy::new(|| {
    let qwerty_rows: Vec<&str> = QWERTY_ROWS
        .iter()
        .chain(QWERTY_SHIFTED_ROWS.iter())
        .copied()
        .collect();
    let mut qwerty_columns = columns(&QWERTY_GRID);
    qwerty_columns.extend(columns(&QWERTY_SHIFTED_GRID));
    let qwerty_columns: Vec<&str> = qwerty_columns.iter().map(String::as_str).collect();

    vec![
        Table::new("QWERTY right 1", &qwerty_rows, 1),
        Table::new("QWERTY left 1", &qwerty_rows, -1),
        Table::new("QWERTY right 2", &qwerty_rows, 2),
        Table::new("QWERTY left 2", &qwerty_rows, -2),
        // Columns run from the top row down, so moving up is moving back one
        Table::new("QWERTY up", &qwerty_columns, -1),
        Table::new("QWERTY down", &qwerty_columns, 1),
        Table::new("QWERTY letters right 1", &QWERTY_LETTERS, 1),
        Table::new("QWERTY letters left 1", &QWERTY_LETTERS, -1),
        Table::new("QWERTY letters right 2", &QWERTY_LETTERS, 2),
        Table::new("QWERTY letters left 2", &QWERTY_LETTERS, -2),
        Table::new("AZERTY letters right 1", &AZERTY_LETTERS, 1),
        Table::new("AZERTY letters left 1", &AZERTY_LETTERS, -1),
        Table::new("QWERTZ letters right 1", &QWERTZ_LETTERS, 1),
        Table::new("QWERTZ letters left 1", &QWERTZ_LETTERS, -1),
    ]
});

impl Table {
    /// The table that undoes an encoder which replaced every key in `cycles` by the key
    /// `offset` places further along its cycle, wrapping round at the end. A cycle is a row
    /// of keys from left to right, or a column from top to bottom.
    fn new(name: &'static str, cycles: &[&str], offset: isize) -> Self {
        let mut decode = [0u8; 128];
        for (byte, plain) in (0u8..).zip(decode.iter_mut()) {
            *plain = byte;
        }
        for cycle in cycles {
            let keys = cycle.as_bytes();
            let len = keys.len() as isize;
            for (position, &key) in (0isize..).zip(keys) {
                let cipher = keys[(position + offset).rem_euclid(len) as usize];
                decode[usize::from(cipher)] = key;
            }
        }
        Table { name, decode }
    }
}

/// The columns of `grid`, each read from the top row down.
fn columns(grid: &[&str]) -> Vec<String> {
    let width = grid.iter().map(|row| row.len()).min().unwrap_or(0);
    (0..width)
        .map(|column| {
            grid.iter()
                .map(|row| char::from(row.as_bytes()[column]))
                .collect()
        })
        .collect()
}

impl Crack for Decoder<KeyboardShiftDecoder> {
    fn new() -> Decoder<KeyboardShiftDecoder> {
        Decoder {
            name: "Keyboard shift",
            description: "Keyboard shift cipher: every key replaced by a neighbouring key (left, right, up or down, 1–2 keys) on a US QWERTY, AZERTY or QWERTZ keyboard. Uses Low sensitivity for gibberish detection.",
            link: "https://www.dcode.fr/keyboard-shift-cipher",
            tags: vec!["keyboard", "substitution", "decryption", "classic"],
            popularity: 0.4,
            phantom: std::marker::PhantomData,
        }
    }

    /// Ranks the 14 decodings, then checks the best `CANDIDATES_CHECKED` in order and stops
    /// at the first one the checker identifies, reporting the name of its shift as the key.
    /// Otherwise returns the best `CANDIDATES_RETURNED` decodings, unidentified, unless the
    /// text looks like an encoding (see [`MIN_ENCODED_WORD_LEN`]).
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Keyboard shift with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let ranked = rank_candidates(text);
        if ranked.is_empty() {
            trace!("Failed to crack keyboard shift: the text is not worth trying");
            return results;
        }

        // Use the checker with Low sensitivity, like the Caesar cracker
        let checker_with_sensitivity = checker.with_sensitivity(Sensitivity::Low);
        for (_, table, candidate) in ranked.iter().take(CANDIDATES_CHECKED) {
            let checker_result = checker_with_sensitivity.check(candidate);
            if checker_result.is_identified {
                trace!("Found a match with keyboard shift {}", table);
                results.unencrypted_text = Some(vec![candidate.clone()]);
                results.update_checker(&checker_result);
                results.key = Some(table.to_string());
                return results;
            }
        }

        if is_encoded_word(text) {
            trace!("Keyboard shift: the text looks like an encoding, so nothing is handed on");
            return results;
        }
        results.unencrypted_text = Some(
            ranked
                .into_iter()
                .take(CANDIDATES_RETURNED)
                .map(|(_, _, candidate)| candidate)
                .collect(),
        );
        results
    }
    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Whether `text` could be a keyboard shift worth cracking, in one pass over its bytes
/// without allocating:
/// * printable ASCII, tabs and line breaks only, which rejects emoji and any non-ASCII text,
/// * at least [`MIN_LETTERS`] ASCII letters and at least [`MIN_NON_WHITESPACE`] other
///   characters than whitespace,
/// * few lowercase letters followed by uppercase ones (see
///   [`MAX_LOWER_UPPER_PAIRS_ONE_IN`]).
fn passes_pre_checks(text: &str) -> bool {
    let mut letters = 0usize;
    let mut non_whitespace = 0usize;
    let mut letter_pairs = 0usize;
    let mut lower_upper_pairs = 0usize;
    let mut previous = b' ';
    for &byte in text.as_bytes() {
        match byte {
            b' ' | b'\t' | b'\n' | b'\r' => {}
            0x21..=0x7E => {
                non_whitespace += 1;
                if byte.is_ascii_alphabetic() {
                    letters += 1;
                    if previous.is_ascii_alphabetic() {
                        letter_pairs += 1;
                        if previous.is_ascii_lowercase() && byte.is_ascii_uppercase() {
                            lower_upper_pairs += 1;
                        }
                    }
                }
            }
            _ => return false,
        }
        previous = byte;
    }
    letters >= MIN_LETTERS
        && non_whitespace >= MIN_NON_WHITESPACE
        && (letter_pairs < MIN_PAIRS_FOR_CASE_CHECK
            || lower_upper_pairs * MAX_LOWER_UPPER_PAIRS_ONE_IN <= letter_pairs)
}

/// Whether `text`, leading and trailing whitespace aside, is one word of at least
/// [`MIN_ENCODED_WORD_LEN`] characters of Base64's alphabet (`A-Z`, `a-z`, `0-9`, `+`, `/`,
/// `=`) with a digit in it: Base64, Base32, Base36, Base58 or hex, more likely than a
/// keyboard shift.
fn is_encoded_word(text: &str) -> bool {
    let word = text.trim_matches(|c: char| c.is_ascii_whitespace());
    word.len() >= MIN_ENCODED_WORD_LEN
        && word.bytes().any(|byte| byte.is_ascii_digit())
        && word
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'+' | b'/' | b'='))
}

/// Decodes `text` with `table`. Bytes that aren't keys of the table, and anything that
/// isn't ASCII, are copied.
fn decode_with(text: &str, table: &Table) -> String {
    let bytes: Vec<u8> = text
        .bytes()
        .map(|byte| table.decode.get(usize::from(byte)).copied().unwrap_or(byte))
        .collect();
    // ASCII bytes decode to ASCII bytes and every other byte is copied, so this is UTF-8
    match String::from_utf8(bytes) {
        Ok(decoded) => decoded,
        Err(error) => String::from_utf8_lossy(error.as_bytes()).into_owned(),
    }
}

/// Every decoding of `text`, best first, as `(score, shift, decoding)`, or nothing if `text`
/// fails the pre-checks (see [`passes_pre_checks`]). Decodings that leave the text as it
/// is, or repeat an earlier shift's decoding (the US QWERTY and QWERTZ letter shifts agree
/// on text without `y` and `z`), are left out.
///
/// The score is [`english_score`]. The sort is stable, so ties keep the order of
/// [`TABLES`].
fn rank_candidates(text: &str) -> Vec<(f32, &'static str, String)> {
    if !passes_pre_checks(text) {
        return Vec::new();
    }
    let mut ranked: Vec<(f32, &'static str, String)> = Vec::with_capacity(TABLES.len());
    for table in TABLES.iter() {
        let candidate = decode_with(text, table);
        if !check_string_success(&candidate, text)
            || ranked.iter().any(|(_, _, seen)| *seen == candidate)
        {
            continue;
        }
        ranked.push((english_score(&candidate), table.name, candidate));
    }
    ranked.sort_by(|left, right| right.0.total_cmp(&left.0));
    ranked
}

/// How English `text` looks: the mean score of its pairs of adjacent characters. A pair of
/// ASCII letters scores its English `ln P` from [`BIGRAM_LOG_PROBS`], in either case; a
/// pair with whitespace in it doesn't count; any other pair scores
/// [`OTHER_PAIR_LOG_PROB`]. Text without a pair that counts scores
/// [`OTHER_PAIR_LOG_PROB`].
fn english_score(text: &str) -> f32 {
    let log_probs = &*BIGRAM_LOG_PROBS;
    let mut total = 0.0f32;
    let mut pairs = 0u32;
    for pair in text.as_bytes().windows(2) {
        let (first, second) = (pair[0], pair[1]);
        if first.is_ascii_whitespace() || second.is_ascii_whitespace() {
            continue;
        }
        pairs += 1;
        total += match (letter_index(first), letter_index(second)) {
            (Some(first), Some(second)) => log_probs[first][second],
            _ => OTHER_PAIR_LOG_PROB,
        };
    }
    if pairs == 0 {
        OTHER_PAIR_LOG_PROB
    } else {
        total / pairs as f32
    }
}

/// The position in the alphabet (0..26) of an ASCII letter, in either case.
fn letter_index(byte: u8) -> Option<usize> {
    if byte.is_ascii_alphabetic() {
        Some(usize::from(byte.to_ascii_lowercase() - b'a'))
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };
    use crate::decoders::interface::{Crack, Decoder};

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    /// The table called `name`.
    fn table(name: &str) -> &'static Table {
        TABLES
            .iter()
            .find(|table| table.name == name)
            .unwrap_or_else(|| panic!("no table named {name:?}"))
    }

    /// The rows of keys an encoder table moves, and how far: written out again from the
    /// plan in #976, independently of `TABLES`, so the tests check the tables against it.
    fn encoder_cycles(name: &str) -> (Vec<String>, isize) {
        let all_rows = || -> Vec<String> {
            [
                "`1234567890-=",
                "qwertyuiop[]\\",
                "asdfghjkl;'",
                "zxcvbnm,./",
                "~!@#$%^&*()_+",
                "QWERTYUIOP{}|",
                "ASDFGHJKL:\"",
                "ZXCVBNM<>?",
            ]
            .map(String::from)
            .to_vec()
        };
        // The grid's columns, top to bottom: `1qaz`, `2wsx`, ... and with Shift `!QAZ`, ...
        let grid_columns = || -> Vec<String> {
            let mut columns = Vec::new();
            for grid in [
                ["1234567890", "qwertyuiop", "asdfghjkl;", "zxcvbnm,./"],
                ["!@#$%^&*()", "QWERTYUIOP", "ASDFGHJKL:", "ZXCVBNM<>?"],
            ] {
                for column in 0..10 {
                    columns.push(grid.iter().map(|row| &row[column..=column]).collect());
                }
            }
            columns
        };
        let letters = |rows: [&str; 3]| -> Vec<String> {
            rows.iter()
                .map(|row| row.to_string())
                .chain(rows.iter().map(|row| row.to_ascii_uppercase()))
                .collect()
        };
        let qwerty = ["qwertyuiop", "asdfghjkl", "zxcvbnm"];
        let azerty = ["azertyuiop", "qsdfghjklm", "wxcvbn"];
        let qwertz = ["qwertzuiop", "asdfghjkl", "yxcvbnm"];
        match name {
            "QWERTY right 1" => (all_rows(), 1),
            "QWERTY left 1" => (all_rows(), -1),
            "QWERTY right 2" => (all_rows(), 2),
            "QWERTY left 2" => (all_rows(), -2),
            "QWERTY up" => (grid_columns(), -1),
            "QWERTY down" => (grid_columns(), 1),
            "QWERTY letters right 1" => (letters(qwerty), 1),
            "QWERTY letters left 1" => (letters(qwerty), -1),
            "QWERTY letters right 2" => (letters(qwerty), 2),
            "QWERTY letters left 2" => (letters(qwerty), -2),
            "AZERTY letters right 1" => (letters(azerty), 1),
            "AZERTY letters left 1" => (letters(azerty), -1),
            "QWERTZ letters right 1" => (letters(qwertz), 1),
            "QWERTZ letters left 1" => (letters(qwertz), -1),
            _ => panic!("no encoder for {name:?}"),
        }
    }

    /// Encrypts `text` with the shift called `name`, walking its rows of keys.
    fn encode(text: &str, name: &str) -> String {
        let (cycles, offset) = encoder_cycles(name);
        text.chars()
            .map(|c| {
                for cycle in &cycles {
                    let keys: Vec<char> = cycle.chars().collect();
                    if let Some(position) = keys.iter().position(|&key| key == c) {
                        let len = keys.len() as isize;
                        return keys[(position as isize + offset).rem_euclid(len) as usize];
                    }
                }
                c
            })
            .collect()
    }

    /// (ciphertext, shift, plaintext). Each ciphertext was generated with a Python 3
    /// prototype of the 14 tables in #976 and decoded back with the inverse table, and
    /// again with a second, independent prototype for this PR. The first is the issue's
    /// own example, generated independently by its author, which cross-checks
    /// `QWERTY right 1`. Ciphey's checks accept every plaintext at Low sensitivity.
    const VECTORS: [(&str, &str, &str); 12] = [
        ("jr;;p ept;f", "QWERTY right 1", "hello world"),
        ("gwkki qieks", "QWERTY left 1", "hello world"),
        ("y3oo9 294oe", "QWERTY up", "hello world"),
        ("nd..l slf.c", "QWERTY down", "hello world"), // codespell:ignore nd
        // `a` is the first key of its row, so one to the left wraps round to `'`
        ("'rr'xj 'r s'qb", "QWERTY left 1", "attack at dawn"),
        (
            "yjr ytrsditr od nitorf imfrt yjr paf psl ytrr",
            "QWERTY letters right 1",
            "the treasure is buried under the old oak tree",
        ),
        (
            "g;sh}lrunpstf+djogy+od+rsdu|",
            "QWERTY right 1",
            "flag{keyboard_shift_is_easy}",
        ),
        (
            "<[ukp,j u[ ftt ktyt/ .[nt d'[,j ]'tdft",
            "QWERTY right 2",
            "Nothing to see here, move along please",
        ),
        (
            "Gnd ajk3, 5fls6 vl2 mj7;x l4df gnd .z1h clb",
            "QWERTY down",
            "The quick brown fox jumps over the lazy dog",
        ),
        (
            "O yjowl yjr azddxptf od joffrw ow amzow dohjy",
            "AZERTY letters right 1",
            "I think the password is hidden in plain sight",
        ),
        (
            "aww miz rinieeiq lr rgw zazlk oklxw",
            "QWERTZ letters left 1",
            "see you tomorrow at the usual place",
        ),
        (
            "<rry ,r sy yjr p;f ;ohjyjpidr sgyrt ,ofmohjy smf ntomh yjr ,s[. yjr lru smf s yptvj/",
            "QWERTY right 1",
            "Meet me at the old lighthouse after midnight and bring the map, the key and a torch.",
        ),
    ];

    /// (ciphertext, shift, plaintext) from two CTF challenges: CTFlearn's "Modern Gaius
    /// Julius Caesar"
    /// (<https://github.com/rishitsaiya/CTFlearn-Writeups/blob/master/Cryptography/Modern%20Gaius%20Julius%20Caesar/README.md>)
    /// and TJCTF 2022's "flimsy-fingered-latin-teacher" (<https://ctftime.org/writeup/33821>).
    /// Ciphey's checks don't take either flag for plaintext without a crib.
    const CTF_VECTORS: [(&str, &str, &str); 2] = [
        (
            "BUH'tdy,|Bim5y~Bdt76yQ",
            "QWERTY right 2",
            "CTFlearn{Cyb3r_Cae54r}",
        ),
        (
            "ykvyg}pp[djp,rtpelru[pdoyopm|",
            "QWERTY right 1",
            "tjctf{oopshomerowkeyposition}",
        ),
    ];

    /// Every printable ASCII character, so the round trips cover every key of every table.
    fn printable_ascii() -> String {
        (0x20u8..=0x7E).map(char::from).collect()
    }

    #[test]
    fn tables_are_the_fourteen_shifts_in_order() {
        let names: Vec<&str> = TABLES.iter().map(|table| table.name).collect();
        assert_eq!(
            names,
            [
                "QWERTY right 1",
                "QWERTY left 1",
                "QWERTY right 2",
                "QWERTY left 2",
                "QWERTY up",
                "QWERTY down",
                "QWERTY letters right 1",
                "QWERTY letters left 1",
                "QWERTY letters right 2",
                "QWERTY letters left 2",
                "AZERTY letters right 1",
                "AZERTY letters left 1",
                "QWERTZ letters right 1",
                "QWERTZ letters left 1",
            ]
        );
    }

    #[test]
    fn every_table_is_a_permutation_that_moves_every_letter() {
        for table in TABLES.iter() {
            let mut decoded = table.decode;
            decoded.sort_unstable();
            let identity: Vec<u8> = (0u8..128).collect();
            assert_eq!(decoded.to_vec(), identity, "{}", table.name);
            for letter in (b'a'..=b'z').chain(b'A'..=b'Z') {
                let plain = table.decode[usize::from(letter)];
                assert_ne!(plain, letter, "{} keeps {}", table.name, char::from(letter));
                // Case is kept: a letter decodes to a letter of the same case, or to the
                // punctuation key next to it
                if plain.is_ascii_alphabetic() {
                    assert_eq!(
                        plain.is_ascii_uppercase(),
                        letter.is_ascii_uppercase(),
                        "{}",
                        table.name
                    );
                }
            }
            // Whitespace and control characters are never keys
            for byte in [b' ', b'\t', b'\n', b'\r', 0, 0x7F] {
                assert_eq!(table.decode[usize::from(byte)], byte, "{}", table.name);
            }
        }
    }

    #[test]
    fn decode_with_undoes_every_encoder() {
        let printable = printable_ascii();
        let pangram = "The Quick Brown Fox, 42 jumps over THE lazy dog! [flag{x_y}] \"a\" 'b'";
        for table in TABLES.iter() {
            for text in [printable.as_str(), pangram] {
                let encoded = encode(text, table.name);
                assert_eq!(decode_with(&encoded, table), text, "{}", table.name);
            }
        }
    }

    #[test]
    fn decode_with_test_vectors() {
        for (ciphertext, name, plaintext) in VECTORS {
            assert_eq!(decode_with(ciphertext, table(name)), plaintext, "{name}");
            assert_eq!(encode(plaintext, name), ciphertext, "{name}");
        }
    }

    #[test]
    fn edge_keys_wrap_round() {
        // Ends of rows, from the plan in #976
        assert_eq!(encode("p", "QWERTY letters right 1"), "q");
        assert_eq!(encode("l", "QWERTY letters right 1"), "a");
        assert_eq!(encode("m", "QWERTY letters right 1"), "z");
        assert_eq!(encode("hlHL", "QWERTY right 1"), "j;J:");
        assert_eq!(encode("=+\\|'\"/?", "QWERTY right 1"), "`~qQaAzZ");
        // Ends of columns: `z` up is `a`, `1` up is `z`
        assert_eq!(encode("z1Z!", "QWERTY up"), "azAZ");
        assert_eq!(encode("z/?", "QWERTY down"), "10)");
        // Keys outside the grid don't move up or down
        assert_eq!(encode("`-=[]\\'~_+{}|\"", "QWERTY up"), "`-=[]\\'~_+{}|\"");
        assert_eq!(
            encode("`-=[]\\'~_+{}|\"", "QWERTY down"),
            "`-=[]\\'~_+{}|\""
        );
        // The letter-only shifts leave every other key alone
        assert_eq!(encode("1;,.[ ]", "QWERTY letters left 2"), "1;,.[ ]");
    }

    #[test]
    fn decode_with_copies_what_isnt_a_key() {
        let table = table("QWERTY right 1");
        assert_eq!(decode_with("", table), "");
        assert_eq!(decode_with("jr;;p é 攻 😀\t\n", table), "hello é 攻 😀\t\n");
    }

    #[test]
    fn case_is_preserved() {
        assert_eq!(decode_with("<rry", table("QWERTY right 1")), "Meet");
        assert_eq!(decode_with("JR:;P", table("QWERTY right 1")), "HELlO");
    }

    #[test]
    fn vectors_rank_in_the_top_two() {
        for (ciphertext, name, plaintext) in VECTORS {
            let ranked = rank_candidates(ciphertext);
            let rank = ranked
                .iter()
                .position(|(_, _, candidate)| candidate == plaintext)
                .unwrap_or_else(|| panic!("{ciphertext:?}: the plaintext isn't ranked"));
            assert!(rank < CANDIDATES_CHECKED, "{ciphertext:?} ranked {rank}");
            assert_eq!(ranked[rank].1, name, "{ciphertext:?}");
        }
    }

    #[test]
    fn long_text_ranks_first() {
        let plaintext = "Ciphey is an automated decoding tool. You give it encrypted or encoded text and it tries to work out what was done to it, without you having to know the key or even the cipher.";
        for table in TABLES.iter() {
            let ranked = rank_candidates(&encode(plaintext, table.name));
            assert_eq!(ranked[0].2, plaintext, "{}", table.name);
            assert_eq!(ranked[0].1, table.name);
        }
    }

    #[test]
    fn vectors_are_cracked() {
        let decoder = Decoder::<KeyboardShiftDecoder>::new();
        for (ciphertext, name, plaintext) in VECTORS {
            let result = decoder.crack(ciphertext, &get_athena_checker());
            assert!(result.success, "{ciphertext:?} was not cracked: {result:?}");
            assert_eq!(result.unencrypted_text.unwrap(), vec![plaintext]);
            assert_eq!(result.key.as_deref(), Some(name), "{ciphertext:?}");
            assert_eq!(result.decoder, "Keyboard shift");
        }
    }

    #[test]
    fn ctf_flags_rank_first_and_are_handed_on() {
        // The checks don't accept these flags, so the decoder can't report success, but
        // the plaintext ranks first and is the first candidate handed back to the search
        let decoder = Decoder::<KeyboardShiftDecoder>::new();
        for (ciphertext, name, plaintext) in CTF_VECTORS {
            assert_eq!(decode_with(ciphertext, table(name)), plaintext, "{name}");
            assert_eq!(encode(plaintext, name), ciphertext, "{name}");
            let ranked = rank_candidates(ciphertext);
            assert_eq!(ranked[0].1, name, "{ciphertext:?}");
            assert_eq!(ranked[0].2, plaintext, "{ciphertext:?}");

            let result = decoder.crack(ciphertext, &get_athena_checker());
            let candidates = result.unencrypted_text.unwrap();
            assert_eq!(candidates[0], plaintext, "{ciphertext:?}");
            if result.success {
                assert_eq!(result.key.as_deref(), Some(name));
            } else {
                assert_eq!(candidates.len(), CANDIDATES_RETURNED);
                assert!(result.key.is_none());
            }
        }
    }

    #[test]
    fn issue_example_is_cracked() {
        let result =
            Decoder::<KeyboardShiftDecoder>::new().crack("jr;;p ept;f", &get_athena_checker());
        assert!(result.success);
        assert_eq!(result.unencrypted_text.unwrap()[0], "hello world");
        assert_eq!(result.key.as_deref(), Some("QWERTY right 1"));
    }

    #[test]
    fn up_and_down_are_cracked() {
        let decoder = Decoder::<KeyboardShiftDecoder>::new();
        // Digits take part: the top row is the digits
        let result = decoder.crack("y3oo9 294oe", &get_athena_checker());
        assert_eq!(result.unencrypted_text.unwrap(), vec!["hello world"]);
        assert_eq!(result.key.as_deref(), Some("QWERTY up"));
        let result = decoder.crack("nd..l slf.c", &get_athena_checker()); // codespell:ignore nd
        assert_eq!(result.unencrypted_text.unwrap(), vec!["hello world"]);
        assert_eq!(result.key.as_deref(), Some("QWERTY down"));
    }

    #[test]
    fn flag_is_identified_by_lemmeknow() {
        let result = Decoder::<KeyboardShiftDecoder>::new()
            .crack("g;sh}lrunpstf+djogy+od+rsdu|", &get_athena_checker());
        assert!(result.success);
        assert_eq!(
            result.unencrypted_text.unwrap()[0],
            "flag{keyboard_shift_is_easy}"
        );
        assert_eq!(result.checker_name, "LemmeKnow Checker");
    }

    #[test]
    fn identical_decodings_are_kept_once() {
        // `jraap eptaf` has no `u`, `x`, `y` or `z`, the keys where one key to the right
        // differs between the US QWERTY and QWERTZ letter rows, so both decode it to
        // `hello world`; the decoding is kept once, under the shift listed first
        let ciphertext = encode("hello world", "QWERTY letters right 1");
        assert_eq!(ciphertext, "jraap eptaf");
        assert_eq!(
            decode_with(&ciphertext, table("QWERTZ letters right 1")),
            "hello world"
        );
        let ranked = rank_candidates(&ciphertext);
        let names: Vec<&str> = ranked.iter().map(|(_, name, _)| *name).collect();
        assert!(names.contains(&"QWERTY letters right 1"), "{names:?}");
        assert!(!names.contains(&"QWERTZ letters right 1"), "{names:?}");
        assert_eq!(ranked[0].1, "QWERTY letters right 1");
        let mut texts: Vec<&String> = ranked.iter().map(|(_, _, text)| text).collect();
        let count = texts.len();
        texts.sort();
        texts.dedup();
        assert_eq!(texts.len(), count, "a decoding is listed twice");
        assert!(ranked.iter().all(|(_, _, text)| *text != ciphertext));
        // With a `y` in the plaintext (`u` in the ciphertext) they differ, and both are
        // kept. `urd dot` has none of the keys at the ends of the rows either, so the
        // letter-only US QWERTY shift gives what the full-row one gives, and only the
        // full-row one, listed first, is kept.
        let ciphertext = encode("yes sir", "QWERTY letters right 1");
        assert_eq!(ciphertext, "urd dot");
        let ranked = rank_candidates(&ciphertext);
        let names: Vec<&str> = ranked.iter().map(|(_, name, _)| *name).collect();
        assert_eq!(ranked[0].1, "QWERTY right 1");
        assert_eq!(ranked[0].2, "yes sir");
        assert!(names.contains(&"QWERTZ letters right 1"), "{names:?}");
        assert!(!names.contains(&"QWERTY letters right 1"), "{names:?}");
    }

    #[test]
    fn ranking_is_best_first() {
        let ranked = rank_candidates("jr;;p ept;f");
        assert!(ranked.len() > CANDIDATES_RETURNED && ranked.len() <= TABLES.len());
        assert!(ranked.windows(2).all(|pair| pair[0].0 >= pair[1].0));
        assert_eq!(ranked[0].2, "hello world");
    }

    #[test]
    fn english_score_counts_letter_pairs_and_penalises_the_rest() {
        let log_probs = &*BIGRAM_LOG_PROBS;
        let th = log_probs[usize::from(b't' - b'a')][usize::from(b'h' - b'a')];
        let he = log_probs[usize::from(b'h' - b'a')][usize::from(b'e' - b'a')];
        assert!((english_score("the") - (th + he) / 2.0).abs() < 1e-5);
        // Case doesn't matter, and pairs with a space don't count
        assert!((english_score("THE") - english_score("the")).abs() < 1e-6);
        assert!((english_score("th he") - (th + he) / 2.0).abs() < 1e-5);
        // `t;` and `;h` are not letter pairs
        assert!((english_score("t;h") - OTHER_PAIR_LOG_PROB).abs() < 1e-6);
        assert!((english_score("a b c") - OTHER_PAIR_LOG_PROB).abs() < 1e-6);
        assert!(english_score("hello world") > english_score("he;;o wor;d"));
    }

    #[test]
    fn pre_checks_reject_input_that_cannot_be_a_keyboard_shift() {
        let decoder = Decoder::<KeyboardShiftDecoder>::new();
        for text in [
            "",
            "😀",
            "é",
            "ab",
            "   ",
            // No letter
            "1234 5678",
            "!@#$%^&*()",
            // 3 characters other than whitespace
            "a b c",
            // Non-ASCII anywhere
            "jr;;p ept;f é",
            "jr;;p\u{a0}ept;f",
            // Control characters other than tabs and line breaks
            "jr;;p\u{0}ept;f",
            "jr;;p\u{c}ept;f",
            "jr;;p\u{7f}ept;f",
        ] {
            assert!(!passes_pre_checks(text), "{text:?} passed the pre-checks");
            assert!(rank_candidates(text).is_empty(), "{text:?}");
            let result = decoder.crack(text, &get_athena_checker());
            assert!(!result.success, "{text:?}");
            assert!(result.unencrypted_text.is_none(), "{text:?}");
            assert!(result.key.is_none(), "{text:?}");
        }
        // Just enough: one letter, four characters other than whitespace
        for text in ["a123", "a 1 2 3", "ab\tcd\r\n"] {
            assert!(passes_pre_checks(text), "{text:?}");
            assert!(!rank_candidates(text).is_empty(), "{text:?}");
        }
    }

    #[test]
    fn text_that_changes_case_inside_words_is_rejected() {
        let decoder = Decoder::<KeyboardShiftDecoder>::new();
        for text in [
            // Base64 of "The quick brown fox jumps over the lazy dog": 12 of 49 pairs are `aB`
            "VGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZw==",
            // Base64 with spaces in it, as the search meets it after other decoders
            "VGhl IHF1aWNr IGJyb3du IGZveCBq dW1wcyBv dmVyIHRo ZSBsYXp5 IGRvZw==",
            // The decoder benchmarks' miss input (benches/data/decoders.toml): 7 of 23
            "T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV",
        ] {
            assert!(!passes_pre_checks(text), "{text:?}");
            let result = decoder.crack(text, &get_athena_checker());
            assert!(!result.success, "{text:?}");
            assert!(result.unencrypted_text.is_none(), "{text:?}");
        }
        // Every vector keeps its case inside words, and so does English with identifiers in
        // it (7 of 73 pairs here, and a shift keeps them)
        for (ciphertext, _, _) in VECTORS.iter().chain(CTF_VECTORS.iter()) {
            assert!(passes_pre_checks(ciphertext), "{ciphertext:?}");
        }
        let identifiers = encode(
            "The CheckerTypes::CheckWaitAthena function returns a ThreadSafePriorityQueue of SearchNodes",
            "QWERTY right 1",
        );
        assert!(passes_pre_checks(&identifiers), "{identifiers:?}");
        // Short texts aren't checked: too few pairs to tell
        assert!(passes_pre_checks("aBcDeF gHiJ"));
    }

    #[test]
    fn long_encoded_words_are_checked_but_not_handed_on() {
        for text in [
            // Base64, hex and Base32 of "hello world", and Base64 of the bench plaintext
            "aGVsbG8gd29ybGQ=",
            "68656c6c6f20776f726c64",
            "NBSWY3DPEB3W64TMMQ======",
            "TWVldCBtZSBhdCB0aGUgb2xkIGxpZ2h0aG91c2UgYWZ0ZXIgbWlkbmlnaHQgYW5kIGJyaW5nIHRoZSBtYXAsIHRoZSBrZXkgYW5kIGEgdG9yY2gu",
            " aGVsbG8gd29ybGQ=\n",
        ] {
            assert!(is_encoded_word(text), "{text:?}");
        }
        for text in [
            // Shorter than 16 characters, no digit, more than one word, or other characters
            "aGVsbG8=",
            "abcdefghijklmnopqrstuvwxyz",
            "aGVsbG8g d29ybGQ=",
            "jr;;p ept;f",
            "g;sh}lrunpstf+djogy+od+rsdu|",
            "BUH'tdy,|Bim5y~Bdt76yQ",
            "ykvyg}pp[djp,rtpelru[pdoyopm|",
        ] {
            assert!(!is_encoded_word(text), "{text:?}");
        }

        let decoder = Decoder::<KeyboardShiftDecoder>::new();
        // Its decodings are ranked and the best checked, but none is handed back
        let base64 = "aGVsbG8gd29ybGQ=";
        assert!(!rank_candidates(base64).is_empty());
        let result = decoder.crack(base64, &get_athena_checker());
        assert!(!result.success, "{result:?}");
        assert!(result.unencrypted_text.is_none(), "{result:?}");
        // A shorter word is handed back as usual
        let result = decoder.crack("aGVsbG8=", &get_athena_checker());
        assert!(!result.success, "{result:?}");
        assert_eq!(result.unencrypted_text.unwrap().len(), CANDIDATES_RETURNED);
    }

    #[test]
    fn plain_english_is_not_cracked() {
        // Plain English isn't a keyboard shift of English: its decodings are gibberish,
        // handed back as candidates
        let decoder = Decoder::<KeyboardShiftDecoder>::new();
        let result = decoder.crack("hello world", &get_athena_checker());
        assert!(!result.success, "{result:?}");
        assert!(result.key.is_none());
        let candidates = result.unencrypted_text.unwrap();
        assert_eq!(candidates.len(), CANDIDATES_RETURNED);
        assert!(!candidates.iter().any(|c| c == "hello world"));
        let expected: Vec<String> = rank_candidates("hello world")
            .into_iter()
            .take(CANDIDATES_RETURNED)
            .map(|(_, _, candidate)| candidate)
            .collect();
        assert_eq!(candidates, expected);
    }

    #[test]
    fn other_ciphers_are_not_cracked() {
        let decoder = Decoder::<KeyboardShiftDecoder>::new();
        for text in [
            // ROT13, Atbash and Base64
            "Zrrg zr ng gur byq yvtugubhfr",
            "svool dliow",
            "aGVsbG8=",
            // The decoder benchmarks' miss input (benches/data/decoders.toml)
            "T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV",
        ] {
            let result = decoder.crack(text, &get_athena_checker());
            assert!(!result.success, "{text:?} was cracked: {result:?}");
            assert!(result.key.is_none(), "{text:?}");
            let candidates = result.unencrypted_text.unwrap_or_default();
            assert!(candidates.len() <= CANDIDATES_RETURNED, "{text:?}");
        }
    }

    #[test]
    fn decoder_metadata() {
        let decoder = Decoder::<KeyboardShiftDecoder>::new();
        assert_eq!(decoder.get_name(), "Keyboard shift");
        assert_eq!(decoder.get_popularity(), 0.4);
        assert_eq!(
            decoder.get_link(),
            "https://www.dcode.fr/keyboard-shift-cipher"
        );
        // A cracker that ranks candidates, not a decoder, and not reciprocal: shifting
        // twice is another shift, and right 2 is a table of its own
        let tags = decoder.get_tags();
        assert_eq!(
            tags,
            &vec!["keyboard", "substitution", "decryption", "classic"]
        );
        assert!(!tags.contains(&"decoder"));
        assert!(!tags.contains(&"reciprocal"));
    }

    #[test]
    fn registered_once() {
        let decoders = crate::filtration_system::get_decoder_by_name("Keyboard shift");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Keyboard shift");
        let decoder = crate::decoders::DECODER_MAP
            .get("Keyboard shift")
            .expect("Keyboard shift is in DECODER_MAP")
            .get::<()>();
        assert_eq!(decoder.get_name(), "Keyboard shift");
    }
}
