//! Decode MIME encoded-words ([RFC 2047](https://datatracker.ietf.org/doc/html/rfc2047)),
//! which carry non-ASCII text in email headers. `=?charset?B?…?=` holds the Base64 of the
//! text's bytes and `=?charset?Q?…?=` a Quoted-Printable variant in which `=XX` is a byte
//! and `_` is a space. The bytes are read in the charset the word names, which may carry an
//! RFC 2231 `*language` suffix. Text around the encoded-words is kept, and whitespace
//! between two encoded-words is removed (RFC 2047 §6.2), which is how long subjects are
//! folded onto several lines.
//! Call mime_encoded_word_decoder.crack to use. It returns `Option<String>` and check with
//! `result.is_some()` to see if it returned okay.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use base64::{engine::general_purpose, Engine as _};
use encoding_rs::Encoding;
use log::{debug, info, trace};

/// The MIME encoded-word decoder, call:
/// `let mime_encoded_word_decoder = Decoder::<MimeEncodedWordDecoder>::new()` to create a new instance
/// And then call:
/// `result = mime_encoded_word_decoder.crack(input)` to decode a header with encoded-words
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::mime_encoded_word_decoder::MimeEncodedWordDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_mime_encoded_word = Decoder::<MimeEncodedWordDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_mime_encoded_word
///     .crack("=?utf-8?b?Q2Fmw6kgb2zDqSDigJMgcsOpc3Vtw6k=?=", &checker)
///     .unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "Café olé – résumé");
/// ```
pub struct MimeEncodedWordDecoder;

impl Crack for Decoder<MimeEncodedWordDecoder> {
    fn new() -> Decoder<MimeEncodedWordDecoder> {
        Decoder {
            name: "MIME Encoded-Word",
            description: "MIME encoded-words (RFC 2047) carry non-ASCII text in email headers such as the subject. Each one names a charset and holds the text's bytes in Base64 (=?charset?B?...?=) or in a Quoted-Printable variant where _ is a space (=?charset?Q?...?=).",
            link: "https://datatracker.ietf.org/doc/html/rfc2047",
            tags: vec!["mime", "rfc2047", "encoded_word", "email", "decoder"],
            popularity: 0.4,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an `Option<String>` if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying MIME encoded-word with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_encoded_words(text) else {
            debug!("Failed to decode MIME encoded-word because decode_encoded_words returned None");
            return results;
        };

        // `=?utf-8?B?AA==?=` is a valid encoded-word, but U+0000 isn't header text
        if has_control_characters(&decoded_text) {
            debug!(
                "Failed to decode MIME encoded-word because the result has control characters: {:?}",
                decoded_text
            );
            return results;
        }

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode MIME encoded-word because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);

        results.update_checker(&checker_result);

        results
    }
    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// The longest charset name accepted, `*language` included. The longest IANA charset name
/// is 45 characters, but the ones mail uses are far shorter.
const MAX_CHARSET_LEN: usize = 40;

/// Decodes every encoded-word in `text` and keeps the text between them, or returns `None`
/// if `text` has no encoded-word or has an `=?` that doesn't start a valid one.
///
/// An `=?` that isn't an encoded-word, as in `=?utf-8?X?abc?=` or an unterminated
/// `=?utf-8?B?SGVsbG8=`, fails the whole decode: text with a broken `=?…` isn't a MIME
/// header. (Python's `email.header` keeps such tokens literally; this is stricter on
/// purpose, so the search doesn't get a child that only differs in one decoded word.)
fn decode_encoded_words(text: &str) -> Option<String> {
    // Fast path: almost nothing the search tries contains `=?`
    if !text.contains("=?") {
        return None;
    }

    let bytes = text.as_bytes();
    let mut decoded = String::with_capacity(text.len());
    let mut decoded_a_word = false;
    // `i` and `start` always sit on an ASCII byte or the end, so slicing `text` is safe
    let mut i = 0;
    while let Some(offset) = text[i..].find("=?") {
        let start = i + offset;
        decoded.push_str(&text[i..start]);
        let end = start + decode_encoded_word(&bytes[start..], &mut decoded)?;
        decoded_a_word = true;

        // RFC 2047 §6.2: whitespace between two encoded-words is dropped, so a folded header
        // reads as one line. Whitespace before ordinary text is kept.
        let next = end
            + bytes[end..]
                .iter()
                .take_while(|byte| matches!(byte, b' ' | b'\t' | b'\r' | b'\n'))
                .count();
        i = if next > end && bytes[next..].starts_with(b"=?") {
            next
        } else {
            end
        };
    }
    decoded.push_str(&text[i..]);

    decoded_a_word.then_some(decoded)
}

/// Decodes the encoded-word at the start of `word`, which starts with `=?`, and appends
/// its text to `decoded`. Returns how many bytes the encoded-word takes up, or `None` if
/// `word` doesn't start with a valid encoded-word.
///
/// RFC 2047 §2: `=?` charset `?` encoding `?` encoded-text `?=`, where the charset is a
/// token (printable ASCII except space and `()<>@,;:"/[]?.=`), the encoding is `B` or `Q`
/// in either case, and the encoded-text is printable ASCII other than `?` and space.
fn decode_encoded_word(word: &[u8], decoded: &mut String) -> Option<usize> {
    let rest = &word[2..];

    let charset_len = rest
        .iter()
        .take(MAX_CHARSET_LEN + 1)
        .take_while(|&&byte| is_token_byte(byte))
        .count();
    if charset_len == 0 || charset_len > MAX_CHARSET_LEN || rest.get(charset_len) != Some(&b'?') {
        return None;
    }
    let encoding = *rest.get(charset_len + 1)?;
    if rest.get(charset_len + 2) != Some(&b'?') {
        return None;
    }

    let text_start = charset_len + 3;
    let text_len = rest[text_start..]
        .iter()
        .take_while(|&&byte| byte.is_ascii_graphic() && byte != b'?')
        .count();
    let text_end = text_start + text_len;
    if text_len == 0 || !rest[text_end..].starts_with(b"?=") {
        return None;
    }

    let encoded_text = &rest[text_start..text_end];
    let bytes = match encoding {
        b'B' | b'b' => decode_b(encoded_text)?,
        b'Q' | b'q' => decode_q(encoded_text)?,
        _ => return None,
    };

    // RFC 2231 §5: `charset*language`, as in `US-ASCII*EN`. The language isn't needed.
    let charset = &rest[..charset_len];
    let label = charset.split(|&byte| byte == b'*').next()?;
    // WHATWG labels, so `iso-8859-1` and `us-ascii` read as windows-1252, a superset
    let text =
        Encoding::for_label(label)?.decode_without_bom_handling_and_without_replacement(&bytes)?;
    decoded.push_str(&text);

    // `=?` + charset `?` encoding `?` + encoded-text + `?=`
    Some(2 + text_end + 2)
}

/// Whether `byte` may appear in an RFC 2047 token: printable ASCII other than the
/// especials `()<>@,;:"/[]?.=`.
fn is_token_byte(byte: u8) -> bool {
    byte.is_ascii_graphic() && !b"()<>@,;:\"/[]?.=".contains(&byte)
}

/// The `B` encoding (RFC 2047 §4.1): Base64, with or without its `=` padding.
fn decode_b(encoded_text: &[u8]) -> Option<Vec<u8>> {
    let mut unpadded = encoded_text;
    while let Some(rest) = unpadded.strip_suffix(b"=") {
        unpadded = rest;
    }
    // Padding on its own decodes to nothing, which proves nothing
    if unpadded.is_empty() {
        return None;
    }
    general_purpose::STANDARD_NO_PAD.decode(unpadded).ok()
}

/// The `Q` encoding (RFC 2047 §4.2): `=XX` is the byte with that hex value (either case),
/// `_` is a space (0x20) and every other character stands for itself. An `=` that isn't
/// followed by two hex digits fails.
fn decode_q(encoded_text: &[u8]) -> Option<Vec<u8>> {
    let mut decoded = Vec::with_capacity(encoded_text.len());
    let mut bytes = encoded_text.iter();
    while let Some(&byte) = bytes.next() {
        match byte {
            b'_' => decoded.push(b' '),
            b'=' => {
                let high = hex_value(bytes.next())?;
                let low = hex_value(bytes.next())?;
                decoded.push((high << 4) | low);
            }
            _ => decoded.push(byte),
        }
    }
    Some(decoded)
}

/// The value of an ASCII hex digit, upper or lower case.
fn hex_value(byte: Option<&u8>) -> Option<u8> {
    char::from(*byte?).to_digit(16).map(|digit| digit as u8)
}

/// Whether `text` has a control character other than tab, CR and LF, including the C1
/// range U+0080–U+009F.
fn has_control_characters(text: &str) -> bool {
    text.chars()
        .any(|c| c.is_control() && !matches!(c, '\t' | '\r' | '\n'))
}

#[cfg(test)]
mod tests {
    use super::{decode_encoded_words, MimeEncodedWordDecoder};
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::{
            crack_results::CrackResult,
            interface::{Crack, Decoder},
            DecoderType, DECODER_MAP,
        },
        filtration_system::get_decoder_by_name,
    };

    // Test vectors: unless a test says otherwise, Python 3.9's
    // `email.header.make_header(email.header.decode_header(text))` and nodemailer's
    // libmime 5.3.6 `decodeWords` both decode each input to the expected text. RFC 2047 §8
    // is the source of the examples marked with it. See the implementation plan on
    // https://github.com/bee-san/Ciphey/issues/945.

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    /// Runs the decoder with the Athena checker
    fn crack(text: &str) -> CrackResult {
        Decoder::<MimeEncodedWordDecoder>::new().crack(text, &get_athena_checker())
    }

    /// Runs the decoder and returns its decoded text, if any
    fn decode(text: &str) -> Option<String> {
        crack(text).unencrypted_text.map(|texts| texts[0].clone())
    }

    #[test]
    fn mime_encoded_word_decodes_issue_b_example() {
        // The example in the issue: Python's `email.header.Header(pt, 'utf-8').encode()`,
        // with a lower-case `b`
        assert_eq!(
            decode("=?utf-8?b?Q2Fmw6kgb2zDqSDigJMgcsOpc3Vtw6k=?=").unwrap(),
            "Café olé – résumé"
        );
    }

    #[test]
    fn mime_encoded_word_decodes_issue_q_example() {
        assert_eq!(
            decode("=?ISO-8859-1?Q?Andr=E9_Pirard?=").unwrap(),
            "André Pirard"
        );
    }

    #[test]
    fn mime_encoded_word_decodes_rfc_2047_examples() {
        // RFC 2047 §8
        assert_eq!(
            decode("=?ISO-8859-1?Q?Keld_J=F8rn_Simonsen?=").unwrap(),
            "Keld Jørn Simonsen"
        );
        assert_eq!(
            decode("=?ISO-8859-1?Q?Patrik_F=E4ltstr=F6m?=").unwrap(),
            "Patrik Fältström"
        );
        assert_eq!(decode("=?US-ASCII?Q?Keith_Moore?=").unwrap(), "Keith Moore");
    }

    #[test]
    fn mime_encoded_word_joins_words_in_different_charsets() {
        // RFC 2047 §8: each word is decoded on its own, in its own charset, and the space
        // between the two words is dropped. Athena accepts the result.
        let result = crack(
            "=?ISO-8859-1?B?SWYgeW91IGNhbiByZWFkIHRoaXMgeW8=?= =?ISO-8859-2?B?dSB1bmRlcnN0YW5kIHRoZSBleGFtcGxlLg==?=",
        );
        assert_eq!(
            result.unencrypted_text.unwrap()[0],
            "If you can read this you understand the example."
        );
        assert!(result.success, "Athena should accept the plaintext");
    }

    #[test]
    fn mime_encoded_word_handles_whitespace_like_rfc_2047_section_8() {
        // Whitespace between two encoded-words is dropped, also when the header is folded
        assert_eq!(
            decode("=?ISO-8859-1?Q?a?= =?ISO-8859-1?Q?b?=").unwrap(),
            "ab"
        );
        assert_eq!(
            decode("=?ISO-8859-1?Q?a?=\r\n    =?ISO-8859-1?Q?b?=").unwrap(),
            "ab"
        );
        assert_eq!(
            decode("=?ISO-8859-1?Q?a?=\n\t=?ISO-8859-1?Q?b?=").unwrap(),
            "ab"
        );
        // Whitespace before ordinary text stays, and `_` is a space
        assert_eq!(decode("=?ISO-8859-1?Q?a?= b").unwrap(), "a b");
        assert_eq!(decode("=?ISO-8859-1?Q?a_b?=").unwrap(), "a b");
        assert_eq!(
            decode("=?ISO-8859-1?Q?a?= =?ISO-8859-2?Q?_b?=").unwrap(),
            "a b"
        );
    }

    #[test]
    fn mime_encoded_word_keeps_surrounding_text() {
        assert_eq!(
            decode("Subject: =?utf-8?Q?Caf=C3=A9_ol=C3=A9?= and more").unwrap(), // codespell:ignore caf
            "Subject: Café olé and more"
        );
    }

    #[test]
    fn mime_encoded_word_decodes_english_with_athena() {
        for (text, expected) in [
            ("=?utf-8?B?SGVsbG8sIFdvcmxkIQ==?=", "Hello, World!"),
            (
                "=?utf-8?Q?The_quick_brown_fox_jumps_over_the_lazy_dog?=",
                "The quick brown fox jumps over the lazy dog",
            ),
            (
                "=?utf-8?B?VGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZw==?=",
                "The quick brown fox jumps over the lazy dog",
            ),
            (
                "=?utf-8?B?TWVldCBtZSBhdCB0aGUgY2Fmw6kgYXQgbm9vbg==?=",
                "Meet me at the café at noon",
            ),
        ] {
            let result = crack(text);
            assert_eq!(result.unencrypted_text.unwrap()[0], expected);
            assert!(result.success, "Athena should accept {expected:?}");
        }
    }

    #[test]
    fn mime_encoded_word_accepts_unpadded_base64() {
        assert_eq!(
            decode("=?utf-8?B?SGVsbG8sIFdvcmxkIQ?=").unwrap(),
            "Hello, World!"
        );
    }

    #[test]
    fn mime_encoded_word_reads_the_named_charset() {
        // WHATWG labels: ISO-8859-1 and windows-1252 are the same decoder, so 0x96 is an en dash
        assert_eq!(
            decode("=?windows-1252?Q?caf=E9_=96_r=E9sum=E9?=").unwrap(), // codespell:ignore caf
            "café – résumé"
        );
        assert_eq!(decode("=?gb2312?B?sbG+qbTz0ac=?=").unwrap(), "北京大学");
        assert_eq!(decode("=?shift_jis?B?k/qWe4zq?=").unwrap(), "日本語");
        assert_eq!(
            decode("=?koi8-r?B?8NLJ18XULCDNydI=?=").unwrap(),
            "Привет, мир"
        );
    }

    #[test]
    fn mime_encoded_word_ignores_case_of_charset_and_encoding() {
        assert_eq!(
            decode("=?Utf-8?q?Caf=c3=a9?=").unwrap(), // codespell:ignore caf
            "Café"
        );
        assert_eq!(decode("=?UTF-8?B?Q2Fmw6k=?=").unwrap(), "Café");
    }

    #[test]
    fn mime_encoded_word_drops_rfc_2231_language() {
        // libmime decodes it; Python raises LookupError on the charset `us-ascii*en`
        assert_eq!(
            decode("=?US-ASCII*EN?Q?Keith_Moore?=").unwrap(),
            "Keith Moore"
        );
    }

    #[test]
    fn mime_encoded_word_rejects_text_without_encoded_words() {
        for text in [
            "hello world",
            "E=mc2",
            "aGVsbG8=",
            "https://example.com/?a=b",
            "what?= no",
        ] {
            assert!(decode(text).is_none(), "{text:?} should not decode");
        }
    }

    #[test]
    fn mime_encoded_word_rejects_broken_encoded_words() {
        for text in [
            "=?",
            "a=?b",
            "=?utf-8?X?abc?=",
            "=?bogus-charset?Q?abc?=",
            "=?utf-8?B?!!!?=",
            "=?utf-8?Q?a=ZZ?=",
            "=?utf-8?Q?a=4?=",
            "=?utf-8?Q??=",
            "=?utf-8?Q?a b?=",
            "=?utf-8?B?SGVsbG8=",
            "=??Q?abc?=",
            "=?utf-8??abc?=",
            "=?utf-8?QQ?abc?=",
            "=?utf.8?Q?abc?=",
            "=?*EN?Q?abc?=",
            "=?utf-8?B?==?=",
            "=?utf-8?B?S?=",
            // A valid word does not make up for a broken one
            "=?utf-8?Q?ok?= =?utf-8?X?abc?=",
        ] {
            assert!(decode(text).is_none(), "{text:?} should not decode");
        }
    }

    #[test]
    fn mime_encoded_word_rejects_long_charsets() {
        let charset = "a".repeat(41);
        assert!(decode(&format!("=?{charset}?Q?abc?=")).is_none());
    }

    #[test]
    fn mime_encoded_word_rejects_bytes_the_charset_cannot_read() {
        // 0xFF on its own isn't UTF-8
        assert!(decode("=?utf-8?B?/w==?=").is_none());
        assert!(decode("=?utf-8?Q?=FF?=").is_none());
    }

    #[test]
    fn mime_encoded_word_rejects_control_characters() {
        // U+0000, and the C1 control U+0080 that UTF-8 C2 80 decodes to
        for text in [
            "=?utf-8?B?AA==?=",
            "=?utf-8?Q?a=00b?=",
            "=?utf-8?Q?=C2=80abc?=",
        ] {
            assert!(decode(text).is_none(), "{text:?} should not decode");
        }
        // Tab, CR and LF are allowed
        assert_eq!(decode("=?utf-8?Q?a=09b=0D=0Ac?=").unwrap(), "a\tb\r\nc");
    }

    #[test]
    fn mime_encoded_word_returns_none_without_words() {
        assert!(decode_encoded_words("no encoded words here").is_none());
        assert_eq!(
            decode_encoded_words("x =?utf-8?Q?y?=").as_deref(),
            Some("x y")
        );
    }

    #[test]
    fn mime_encoded_word_handles_panics() {
        // This tests if MIME encoded-word can handle panics
        // It should return None
        for text in [
            "hello my name is panicky mc panic face!",
            "=?=?=?",
            "=?utf-8",
            "=?utf-8?",
            "=?utf-8?Q",
            "=?utf-8?Q?",
            "=?utf-8?Q?abc",
            "=?utf-8?Q?abc?",
            "=?utf-8?Q?=",
            "=?é?Q?abc?=",
            "=?utf-8?Q?é?=",
        ] {
            assert!(decode(text).is_none(), "{text:?} should not decode");
        }
    }

    #[test]
    fn mime_encoded_word_handles_panic_if_empty_string() {
        // This tests if MIME encoded-word can handle an empty string
        // It should return None
        assert!(decode("").is_none());
    }

    #[test]
    fn mime_encoded_word_handles_panic_if_emoji() {
        // This tests if MIME encoded-word can handle an emoji
        // It should return None
        assert!(decode("😀").is_none());
        assert!(decode("😀=?😀?=").is_none());
    }

    #[test]
    fn mime_encoded_word_is_registered() {
        let decoders = get_decoder_by_name("MIME Encoded-Word");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "MIME Encoded-Word");

        // The cache stores the path as JSON and finds decoders by name in DECODER_MAP
        let decoder = DECODER_MAP
            .get("MIME Encoded-Word")
            .unwrap()
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "MIME Encoded-Word");
        let mime_encoded_word_decoder = Decoder::<MimeEncodedWordDecoder>::new();
        let json = CrackResult::new(&mime_encoded_word_decoder, "=?utf-8?Q?a?=".to_string())
            .get_json()
            .unwrap();
        let crack_result: CrackResult = serde_json::from_str(&json).unwrap();
        assert_eq!(crack_result.decoder, "MIME Encoded-Word");
    }
}
