//! Decode Multi-tap, the "ABC" text entry of keypad phones. Each letter is written as its
//! ITU-T E.161 key pressed once per position on the key: `2` is ABC, `3` DEF, `4` GHI, `5`
//! JKL, `6` MNO, `7` PQRS, `8` TUV and `9` WXYZ, so `44` is H, `555` is L and `7777` is S.
//! References: <https://en.wikipedia.org/wiki/Multi-tap>,
//! <https://www.dcode.fr/multitap-abc-cipher> and <https://www.dcode.fr/phone-keypad-cipher>.
//!
//! The letters can be written as:
//! * key presses separated by whitespace, with `0` (or `1`, as on some phones) for a space:
//!   `44 33 555 555 666 0 9 666 777 555 3` is `HELLO WORLD`. Python Ciphey and most CTF
//!   writeups use this form.
//! * key presses joined by `-`, `,`, `;`, `:` or `.`, with whitespace between words, as dCode
//!   writes them: `222-666-3-33 9-666-777-555-3` is `CODE WORLD`.
//! * dCode's count notation, `4*2` or `4^2` for `44`.
//!
//! `/`, `|` and line breaks always separate words. The output is upper case, with one space
//! between words and none at either end.
//!
//! Key presses written without separators (`3222666333`) can't be split without a
//! dictionary, so they aren't decoded. Neither is T9 predictive text (one press per
//! letter, `43556` for HELLO), which also needs a dictionary.
//!
//! Call multi_tap_decoder.crack to use. It returns a `CrackResult` whose `unencrypted_text`
//! is `None` when the input isn't Multi-tap.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The Multi-tap decoder, call:
/// `let multi_tap_decoder = Decoder::<MultiTapDecoder>::new()` to create a new instance
/// And then call:
/// `result = multi_tap_decoder.crack(input)` to decode a Multi-tap string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::multi_tap_decoder::MultiTapDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_multi_tap = Decoder::<MultiTapDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_multi_tap
///     .crack("44 33 555 555 666 0 9 666 777 555 3", &checker)
///     .unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "HELLO WORLD");
///
/// // dCode's form: letters joined by hyphens, words separated by spaces
/// let result = decode_multi_tap
///     .crack("44-33-555-555-666 9-666-777-555-3", &checker)
///     .unencrypted_text;
/// assert_eq!(result.unwrap()[0], "HELLO WORLD");
/// ```
pub struct MultiTapDecoder;

/// The letters on keys 2 to 9 (ITU-T E.161). Pressing key `k` `n` times types
/// `KEYS[k - 2][n - 1]`.
const KEYS: [&str; 8] = ["ABC", "DEF", "GHI", "JKL", "MNO", "PQRS", "TUV", "WXYZ"];

/// Fewer letters than this are too likely to be something else, like a score or a date.
const MIN_LETTERS: usize = 3;

impl Crack for Decoder<MultiTapDecoder> {
    fn new() -> Decoder<MultiTapDecoder> {
        Decoder {
            name: "Multi-tap",
            description: "Multi-tap (ABC mode) SMS text: each letter is its phone keypad key pressed once per position, 2=ABC … 9=WXYZ, so 44 is H and 7777 is S; letters are separated by spaces or hyphens and 0 is a space.",
            link: "https://en.wikipedia.org/wiki/Multi-tap",
            tags: vec![
                "multi-tap",
                "multitap",
                "sms",
                "phone",
                "keypad",
                "substitution",
                "decoder",
            ],
            popularity: 0.3,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes `text` as Multi-tap and checks the result with `checker`.
    /// `unencrypted_text` is `None` when `text` isn't Multi-tap.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Multi-tap with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_multi_tap(text) else {
            debug!("Failed to decode Multi-tap because the text isn't Multi-tap key presses");
            return results;
        };
        trace!("Decoded text for Multi-tap: {:?}", decoded_text);

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Multi-tap because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Decodes Multi-tap key presses to text, or returns `None` if `text` isn't Multi-tap.
fn decode_multi_tap(text: &str) -> Option<String> {
    let bytes = text.trim().as_bytes();
    // Rejects almost every input, on its first byte
    if !bytes.first()?.is_ascii_digit() {
        return None;
    }

    // Pass 1 checks every token without allocating
    let mut tokens = 0;
    let mut letters = 0;
    let mut pressed_twice = false;
    let mut letters_joined = false;
    for token in Tokens::new(bytes) {
        let Token { gap, press } = token.ok()?;
        tokens += 1;
        if let Press::Letter { presses, .. } = press {
            letters += 1;
            pressed_twice |= presses >= 2;
        }
        // A separator on its own between two tokens, as in `44-33`
        letters_joined |= gap.letter_separator && !gap.whitespace && !gap.word_break;
    }
    // Text averages about two presses a letter. Short runs of single digits like `2 3 4 5`
    // are much more likely to be something else.
    if letters < MIN_LETTERS || !pressed_twice {
        return None;
    }

    // Pass 2 writes the text. When separators join the letters of a word (`44-33-555`),
    // whitespace separates words; otherwise whitespace separates letters.
    let mut decoded = String::with_capacity(2 * tokens);
    let mut space = false;
    for Token { gap, press } in Tokens::new(bytes).flatten() {
        space |= gap.word_break || (gap.whitespace && letters_joined);
        match press {
            Press::Space => space = true,
            Press::Letter { letter, .. } => {
                if space && !decoded.is_empty() {
                    decoded.push(' ');
                }
                space = false;
                decoded.push(char::from(letter));
            }
        }
    }
    Some(decoded)
}

/// What one token types.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Press {
    /// An upper-case ASCII letter, and how many times its key was pressed
    Letter {
        /// The letter
        letter: u8,
        /// How many times the key was pressed, 1 to 4
        presses: usize,
    },
    /// `0` or `1`: a space
    Space,
}

/// The separators and whitespace between a token and the one before it.
#[derive(Clone, Copy, Debug, Default)]
struct Gap {
    /// Has `-`, `,`, `;`, `:` or `.`
    letter_separator: bool,
    /// Has a space, tab or form feed
    whitespace: bool,
    /// Has `/`, `|` or a line break
    word_break: bool,
}

/// A token and the gap before it. The first token's gap is empty.
#[derive(Clone, Copy, Debug)]
struct Token {
    /// The gap before the token
    gap: Gap,
    /// What the token types
    press: Press,
}

/// The text has a byte or a token that Multi-tap doesn't write.
#[derive(Debug)]
struct NotMultiTap;

/// Splits Multi-tap text into tokens: a run of one digit (`555`), or a digit with a count
/// (`5*3`). After the first error it returns `None`.
struct Tokens<'a> {
    /// The text
    bytes: &'a [u8],
    /// Where the next gap starts
    pos: usize,
}

impl<'a> Tokens<'a> {
    /// Tokens of `bytes`
    fn new(bytes: &'a [u8]) -> Self {
        Tokens { bytes, pos: 0 }
    }

    /// Reads the next gap and token, or returns `Ok(None)` at the end of the text.
    fn read(&mut self) -> Result<Option<Token>, NotMultiTap> {
        let mut gap = Gap::default();
        let key = loop {
            let Some(&byte) = self.bytes.get(self.pos) else {
                // Separators after the last token, like a final `.`, aren't a gap
                return Ok(None);
            };
            self.pos += 1;
            match byte {
                b'0'..=b'9' => break byte,
                b'-' | b',' | b';' | b':' | b'.' => gap.letter_separator = true,
                b'/' | b'|' | b'\n' | b'\r' => gap.word_break = true,
                b' ' | b'\t' | b'\x0c' => gap.whitespace = true,
                _ => return Err(NotMultiTap),
            }
        };

        // `self.pos` is one past the token's first digit
        let mut presses = 1;
        while self.bytes.get(self.pos) == Some(&key) {
            presses += 1;
            self.pos += 1;
        }
        let press = match self.bytes.get(self.pos) {
            // dCode's count notation: `2*3` or `2^3` is `222`
            Some(b'*' | b'^') if presses == 1 => {
                let count = *self.bytes.get(self.pos + 1).ok_or(NotMultiTap)?;
                if !count.is_ascii_digit() {
                    return Err(NotMultiTap);
                }
                self.pos += 2;
                letter(key, usize::from(count - b'0'))
            }
            _ if matches!(key, b'0' | b'1') => (presses == 1).then_some(Press::Space),
            _ => letter(key, presses),
        };
        // A token ends at a separator or at the end of the text, so mixed digits like `23`
        // and longer counts like `2*33` aren't tokens
        if matches!(self.bytes.get(self.pos), Some(b'0'..=b'9' | b'*' | b'^')) {
            return Err(NotMultiTap);
        }
        let press = press.ok_or(NotMultiTap)?;
        Ok(Some(Token { gap, press }))
    }
}

impl Iterator for Tokens<'_> {
    type Item = Result<Token, NotMultiTap>;

    fn next(&mut self) -> Option<Self::Item> {
        let token = self.read();
        if token.is_err() {
            self.pos = self.bytes.len();
        }
        token.transpose()
    }
}

/// The letter typed by pressing `key` (an ASCII digit) `presses` times, if there is one.
fn letter(key: u8, presses: usize) -> Option<Press> {
    let letters = KEYS.get(usize::from(key.checked_sub(b'2')?))?.as_bytes();
    let letter = *letters.get(presses.checked_sub(1)?)?;
    Some(Press::Letter { letter, presses })
}

#[cfg(test)]
mod tests {
    use super::{decode_multi_tap, MultiTapDecoder, KEYS};
    use crate::checkers::athena::Athena;
    use crate::checkers::checker_type::{Check, Checker};
    use crate::checkers::CheckerTypes;
    use crate::decoders::a1z26_decoder::A1Z26Decoder;
    use crate::decoders::decimal_decoder::DecimalDecoder;
    use crate::decoders::interface::{Crack, Decoder};
    use crate::decoders::octal_decoder::OctalDecoder;
    use crate::decoders::{DecoderType, DECODER_MAP};
    use crate::filtration_system::get_decoder_by_name;

    // The vectors were worked out from the ITU-T E.161 table (2 = ABC ... 9 = WXYZ) with a
    // Python prototype of this decoder. The space-separated ones with `0` for a space were
    // also decoded with the logic of Python Ciphey 5.14.0's `Decoders/multi_tap.py`, which
    // gives the same text. `222-666-3-33` (CODE) and `3 222 666 3 33` (DCODE) are dCode's
    // examples: https://www.dcode.fr/phone-keypad-cipher

    /// The issue's example: https://github.com/bee-san/Ciphey/issues/960
    const HELLO_WORLD: &str = "44 33 555 555 666 0 9 666 777 555 3";

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    // Runs the decoder with the Athena checker and returns the decoded text, if any
    fn crack(text: &str) -> Option<String> {
        let decoder = Decoder::<MultiTapDecoder>::new();
        let result = decoder.crack(text, &get_athena_checker());
        if result.unencrypted_text.is_none() {
            assert!(!result.success, "{text:?} failed but was marked successful");
        }
        result.unencrypted_text.map(|texts| texts[0].clone())
    }

    // Asserts that Athena accepts the decoded text
    fn assert_cracks(text: &str, expected: &str) {
        let decoder = Decoder::<MultiTapDecoder>::new();
        let result = decoder.crack(text, &get_athena_checker());
        assert_eq!(
            result.unencrypted_text.as_deref(),
            Some(&[expected.to_string()][..]),
            "{text:?}"
        );
        assert!(result.success, "Athena should accept {expected:?}");
    }

    #[test]
    fn decodes_the_issue_example() {
        assert_cracks(HELLO_WORLD, "HELLO WORLD");
    }

    #[test]
    fn decodes_comma_separated_presses() {
        assert_eq!(
            crack("44,33,555,555,666,0,9,666,777,555,3").unwrap(),
            "HELLO WORLD"
        );
    }

    #[test]
    fn decodes_comma_and_space_separated_presses() {
        assert_eq!(
            crack("44, 33, 555, 555, 666, 0, 9, 666, 777, 555, 3").unwrap(),
            "HELLO WORLD"
        );
    }

    #[test]
    fn decodes_dcode_hyphens_with_spaces_between_words() {
        assert_eq!(
            crack("44-33-555-555-666 9-666-777-555-3").unwrap(),
            "HELLO WORLD"
        );
        assert_eq!(crack("222-666-3-33 9-666-777-555-3").unwrap(), "CODE WORLD");
    }

    #[test]
    fn decodes_line_breaks_as_word_gaps() {
        assert_eq!(
            crack("44 33 555 555 666\n9 666 777 555 3").unwrap(),
            "HELLO WORLD"
        );
        assert_eq!(
            crack("44 33 555 555 666\r\n9 666 777 555 3\r\n").unwrap(),
            "HELLO WORLD"
        );
    }

    #[test]
    fn decodes_slash_and_bar_as_word_gaps() {
        assert_eq!(
            crack("44 33 555 555 666 / 9 666 777 555 3").unwrap(),
            "HELLO WORLD"
        );
        assert_eq!(
            crack("44-33-555-555-666|9-666-777-555-3").unwrap(),
            "HELLO WORLD"
        );
    }

    #[test]
    fn decodes_one_as_a_space() {
        assert_eq!(
            crack("44 33 555 555 666 1 9 666 777 555 3").unwrap(),
            "HELLO WORLD"
        );
    }

    #[test]
    fn decodes_dcode_count_notation() {
        assert_eq!(
            crack("4*2 3*2 5*3 5*3 6*3 0 9 6*3 7*3 5*3 3").unwrap(),
            "HELLO WORLD"
        );
        assert_eq!(
            crack("4^2 3^2 5^3 5^3 6^3 0 9 6^3 7^3 5^3 3").unwrap(),
            "HELLO WORLD"
        );
        // A count of one, and four presses on the keys with four letters
        assert_eq!(crack("2*1 2*2 2*3").unwrap(), "ABC");
        assert_eq!(crack("7*4 9*4 2").unwrap(), "SZA");
    }

    #[test]
    fn decodes_meet_me_at_dawn() {
        assert_cracks("6 33 33 8 0 6 33 0 2 8 0 3 2 9 66", "MEET ME AT DAWN");
    }

    #[test]
    fn decodes_dcode_examples() {
        assert_cracks("222-666-3-33", "CODE");
        // Athena doesn't take DCODE for plaintext
        assert_eq!(crack("3 222 666 3 33").unwrap(), "DCODE");
    }

    #[test]
    fn decodes_four_presses_on_7_and_9() {
        assert_eq!(crack("7777 666 7777").unwrap(), "SOS");
        assert_eq!(crack("7777 9999 2").unwrap(), "SZA");
    }

    #[test]
    fn decodes_every_letter() {
        let mut encoded = Vec::new();
        for (key, letters) in (2..).zip(KEYS) {
            for presses in 1..=letters.len() {
                encoded.push(key.to_string().repeat(presses));
            }
        }
        assert_eq!(
            decode_multi_tap(&encoded.join(" ")).as_deref(),
            Some("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
        );
    }

    #[test]
    fn decodes_the_ctf_example() {
        // IBTeam Blackvalentine CTF 2015, Crypto2:
        // https://raw.githubusercontent.com/ctfs/write-ups-2015/master/ibteam-blackvalentine-ctf-2015/crypto/crypto-2/README.md
        assert_eq!(
            crack("3 444 0 22 2 555 444 55 0 8 444 777 2 444 0 6 33 777 2 44").unwrap(),
            "DI BALIK TIRAI MERAH"
        );
    }

    #[test]
    fn writes_one_space_between_words_and_none_at_the_ends() {
        assert_eq!(
            crack("44-33-555-555-666 0 9-666-777-555-3").unwrap(),
            "HELLO WORLD"
        );
        assert_eq!(
            crack("44 33 555 555 666 / 0 / 9 666 777 555 3").unwrap(),
            "HELLO WORLD"
        );
        assert_eq!(crack("0 44 33 555 555 666 0").unwrap(), "HELLO");
        assert_eq!(crack("44 33 555 555 666 / ").unwrap(), "HELLO");
        assert_eq!(crack("44|33|555|555|666").unwrap(), "H E L L O");
    }

    #[test]
    fn ignores_separators_after_the_last_letter() {
        // A final `.` isn't a separator between letters, so the spaces still separate letters
        assert_eq!(
            crack("44 33 555 555 666 0 9 666 777 555 3.").unwrap(),
            "HELLO WORLD"
        );
        assert_eq!(crack("  44-33-555-555-666, ").unwrap(), "HELLO");
    }

    #[test]
    fn reads_hyphenated_digit_pairs_as_letters() {
        // The issue writes `4-2` for `44`, but dCode uses `-` between letters, so this is
        // G A, D A, J E
        assert_eq!(crack("4-2 3-2 5-33").unwrap(), "GA DA JE");
    }

    #[test]
    fn decodes_a1z26_text_made_of_single_digits_and_22() {
        // A1Z26 VEE; both decoders give a candidate
        assert_eq!(crack("22-5-5").unwrap(), "BJJ");
    }

    #[test]
    fn sets_unencrypted_text_when_athena_rejects_it() {
        let decoder = Decoder::<MultiTapDecoder>::new();
        let result = decoder.crack("7777 9999 2", &get_athena_checker());
        assert!(!result.success);
        assert_eq!(result.unencrypted_text.unwrap()[0], "SZA");
    }

    #[test]
    fn fails_on_too_many_presses() {
        assert_eq!(crack("2222 6666 7777"), None);
        assert_eq!(crack("99999 666 7777"), None);
        assert_eq!(crack("2*4 3*3 4*3"), None);
        assert_eq!(crack("7*5 666 7777"), None);
    }

    #[test]
    fn fails_on_mixed_digits() {
        assert_eq!(crack("23 45 67"), None);
        assert_eq!(crack("3222666333"), None);
        assert_eq!(crack("12 34 56"), None);
    }

    #[test]
    fn fails_on_repeated_zero_or_one() {
        assert_eq!(crack("55 55 55 00"), None);
        assert_eq!(crack("11 44 55 66"), None);
    }

    #[test]
    fn fails_with_fewer_than_three_letters() {
        assert_eq!(crack("44 33"), None);
        assert_eq!(crack("7777 0 9999"), None);
        assert_eq!(crack("0 1 0 1"), None);
    }

    #[test]
    fn fails_when_no_key_is_pressed_twice() {
        assert_eq!(crack("2 3 4 5"), None);
        assert_eq!(crack("4-2 3-2"), None);
        assert_eq!(crack("4-2 3-2 5-3"), None);
        assert_eq!(crack("2*1 3*1 4*1"), None);
    }

    #[test]
    fn fails_on_bad_count_notation() {
        // On 0 or 1, after more than one digit, without a count, a longer count, a count of
        // zero, two operators, or with spaces around the operator
        assert_eq!(crack("0*2 44 33 555"), None);
        assert_eq!(crack("22*3 44 55"), None);
        assert_eq!(crack("44 55 2*"), None);
        assert_eq!(crack("2*33 44 55"), None);
        assert_eq!(crack("2*0 44 55"), None);
        assert_eq!(crack("2*3*3 44 55"), None);
        assert_eq!(crack("2**3 44 55"), None);
        assert_eq!(crack("2 * 3 44 55"), None);
        assert_eq!(crack("44 33 555 *"), None);
    }

    #[test]
    fn fails_on_other_characters() {
        assert_eq!(crack(&format!("{HELLO_WORLD} x")), None);
        assert_eq!(crack("44 33 555\u{a0}555 666"), None);
        assert_eq!(crack("44\u{b}33 555"), None);
        assert_eq!(crack("44 33 555 555 666!"), None);
    }

    #[test]
    fn fails_on_a_leading_separator() {
        assert_eq!(crack("-44 33 555"), None);
        assert_eq!(crack("/ 44 33 555"), None);
    }

    #[test]
    fn fails_on_other_decoders_inputs() {
        // T9
        assert_eq!(crack("43556 96753"), None);
        // Decimal
        assert_eq!(crack("104 101 108 108 111"), None);
        // A1Z26
        assert_eq!(crack("8-5-12-12-15"), None);
        // Binary
        assert_eq!(crack("01101000 01101001"), None);
        // Octal
        assert_eq!(crack("150 145 154"), None);
        // DTMF frequency pairs
        assert_eq!(crack("852-1336 770-1477 852-1209"), None);
        // The bench's gibberish `miss` string
        assert_eq!(
            crack("T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV"),
            None
        );
    }

    #[test]
    fn other_numeric_decoders_reject_multi_tap() {
        // So the search doesn't get a competing candidate from them
        let checker = get_athena_checker();
        for text in [HELLO_WORLD, "6 33 33 8 0 6 33 0 2 8 0 3 2 9 66"] {
            let decimal = Decoder::<DecimalDecoder>::new().crack(text, &checker);
            assert_eq!(decimal.unencrypted_text, None, "Decimal decoded {text:?}");
            let a1z26 = Decoder::<A1Z26Decoder>::new().crack(text, &checker);
            assert_eq!(a1z26.unencrypted_text, None, "a1z26 decoded {text:?}");
            let octal = Decoder::<OctalDecoder>::new().crack(text, &checker);
            assert_eq!(octal.unencrypted_text, None, "Octal decoded {text:?}");
        }
    }

    #[test]
    fn handles_panic_if_empty_string() {
        assert_eq!(crack(""), None);
    }

    #[test]
    fn handles_panic_if_whitespace() {
        assert_eq!(crack("   "), None);
        assert_eq!(crack(" \t\r\n "), None);
    }

    #[test]
    fn handles_panic_if_emoji() {
        assert_eq!(crack("😀"), None);
        assert_eq!(crack("44 33 😀 555"), None);
    }

    #[test]
    fn fails_on_english() {
        assert_eq!(crack("hello world"), None);
        assert_eq!(crack("hello my name is panicky mc panic face!"), None);
    }

    #[test]
    fn handles_long_runs_of_one_digit() {
        assert_eq!(crack(&"2".repeat(10_000)), None);
        assert_eq!(crack(&format!("44 33 {}", "5".repeat(10_000))), None);
    }

    #[test]
    fn is_registered() {
        // Exactly one decoder by that name runs in the search
        let decoders = get_decoder_by_name("Multi-tap");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Multi-tap");
        // Cached results name the decoder; reading them back looks it up here
        let decoder = DECODER_MAP
            .get("Multi-tap")
            .expect("Multi-tap should be in DECODER_MAP")
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "Multi-tap");
        assert!((decoder.get_popularity() - 0.3).abs() < f32::EPSILON);
    }
}
