//! Decode text spelled out with the NATO phonetic alphabet, the ICAO radiotelephony
//! spelling alphabet: `Hotel Echo Lima Lima Oscar` is `hello`.
//! Call nato_phonetic_decoder.crack to use. It returns a `CrackResult` whose
//! `unencrypted_text` is `None` when the input isn't NATO text.
//!
//! Every code word stands for one character: the first letter of the 26 letter words, the
//! digit of the digit words. These spellings are read, in any case:
//! * letters: the ICAO words, plus `Alpha`, `Juliet`, `Whisky`, and `Xray` or `X-ray`;
//! * digits: the ICAO words (`Zero` … `Nine`), the ITU/IMO compounds (`Nadazero`, `Unaone`,
//!   `Bissotwo`, `Terrathree`, `Kartefour`, `Pantafive`, `Soxisix`, `Setteseven`,
//!   `Oktoeight`, `Novenine`) and the spoken forms (`Wun`, `Too`, `Tree`, `Fower`, `Fife`,
//!   `Ait`, `Niner`);
//! * punctuation: `Comma` is `,`; `Stop`, `Full stop`, `Decimal` and `Point` are `.`;
//!   `Hyphen` and `Dash` are `-`; `Slant` and `Fraction bar` are `/`; `Space` is a space.
//!
//! Two layouts are read:
//! * Code words separated by single spaces or tabs, with a wider gap between words: two or
//!   more spaces, a line break, or a `/`, `|` or `(space)` on its own. CyberChef's
//!   `Convert to NATO alphabet` writes `Hotel Echo Lima Lima Oscar  Whiskey Oscar Romeo
//!   Lima Delta `, other translators `Hotel India / Two Five` and
//!   `Hotel Echo Lima Lima Oscar (space) Whiskey Oscar Romeo Lima Delta`.
//! * The code words of each word joined with `-`, `/` or `|`, and whitespace between words:
//!   `Hotel-Echo-Lima-Lima-Oscar Whiskey-Oscar-Romeo-Lima-Delta`.
//!
//! When every word would be one character long and there is no `/` or `(space)` gap, the
//! gaps were between letters: `Hotel  Echo  Lima  Lima  Oscar` is `hello`.
//!
//! The decoded text is lower case. Any other token, or any other character, means the text
//! isn't NATO, so ordinary English is rejected at its first word.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The NATO phonetic alphabet decoder, call:
/// `let nato_decoder = Decoder::<NatoPhoneticDecoder>::new()` to create a new instance
/// And then call:
/// `result = nato_decoder.crack(input)` to decode text spelled with the NATO alphabet
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::nato_phonetic_decoder::NatoPhoneticDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_nato = Decoder::<NatoPhoneticDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // CyberChef's `Convert to NATO alphabet`: two spaces between words
/// let result = decode_nato
///     .crack("Hotel Echo Lima Lima Oscar  Whiskey Oscar Romeo Lima Delta", &checker)
///     .unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hello world");
///
/// // The code words of each word joined with hyphens
/// let result = decode_nato
///     .crack("Hotel-Echo-Lima-Lima-Oscar Whiskey-Oscar-Romeo-Lima-Delta", &checker)
///     .unencrypted_text;
/// assert_eq!(result.unwrap()[0], "hello world");
/// ```
pub struct NatoPhoneticDecoder;

/// The longest code words, `terrathree` and `setteseven`. A longer run of letters isn't a
/// code word, so the scan stops there.
const MAX_CODE_WORD_LEN: usize = 10;

/// Decoded texts shorter than this are dropped by the search anyway, and two code words
/// are as likely to be two ordinary words (`Golf Hotel`, `Romeo Juliet`).
const MIN_DECODED_LEN: usize = 3;

// Markers between the characters decoded from two tokens, replaced once the whole text has
// been read. No code word decodes to one of these bytes.
/// A single space or tab
const LETTER_GAP: u8 = 1;
/// Any other run of whitespace: two or more spaces or tabs, or a line break
const WIDE_GAP: u8 = 2;
/// A `/`, `|` or `(space)` on its own, which only ever separates words
const WORD_GAP: u8 = 3;

impl Crack for Decoder<NatoPhoneticDecoder> {
    fn new() -> Decoder<NatoPhoneticDecoder> {
        Decoder {
            name: "NATO Phonetic Alphabet",
            description: "Text spelled out with the NATO/ICAO radiotelephony alphabet (Alfa Bravo Charlie …), one code word per letter or digit; decodes to the first letter of each word.",
            link: "https://en.wikipedia.org/wiki/NATO_phonetic_alphabet",
            tags: vec!["nato", "phonetic", "spelling_alphabet", "decoder"],
            popularity: 0.4,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes `text` as NATO phonetic alphabet code words and checks the result with
    /// `checker`. `unencrypted_text` is `None` when `text` isn't NATO text.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying NATO Phonetic Alphabet with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_nato(text) else {
            debug!("Failed to decode NATO Phonetic Alphabet because the text isn't code words");
            return results;
        };
        trace!(
            "Decoded text for NATO Phonetic Alphabet: {:?}",
            decoded_text
        );

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode NATO Phonetic Alphabet because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Decodes NATO phonetic alphabet code words to lower-case text, or returns `None` if
/// `text` isn't NATO text.
fn decode_nato(text: &str) -> Option<String> {
    let mut tokens = Tokens {
        rest: text.as_bytes(),
    }
    .peekable();
    // The decoded characters, with a gap marker between the characters of two tokens
    let mut decoded: Vec<u8> = Vec::new();
    // Whether the code words of a word are joined with `-`, `/` or `|`
    let mut joined = false;
    // The widest gap since the last code word
    let mut gap = 0;

    while let Some(token) = tokens.next() {
        let token = token.ok()?;
        gap = gap.max(if token.narrow_gap_before {
            LETTER_GAP
        } else {
            WIDE_GAP
        });
        if token.kind == TokenKind::WordGap {
            gap = WORD_GAP;
            continue;
        }
        if !decoded.is_empty() {
            decoded.push(gap);
        }
        gap = 0;

        if token.kind == TokenKind::Letters {
            let next = tokens
                .peek()
                .and_then(|next| next.as_ref().ok())
                .filter(|next| next.kind == TokenKind::Letters)
                .map(|next| next.text);
            let (character, used_next) = decode_code_word(token.text, next)?;
            decoded.push(character);
            if used_next {
                tokens.next();
            }
        } else if token.text.eq_ignore_ascii_case(b"x-ray") {
            // One code word, not two joined ones, so it doesn't make the text a joined one
            decoded.push(b'x');
        } else {
            joined = true;
            decode_joined(token.text, &mut decoded)?;
        }
    }

    // A joined text has whitespace only between words. Otherwise a single space or tab
    // separates two letters of a word.
    let is_word_gap = |byte: u8| match byte {
        WIDE_GAP | WORD_GAP => true,
        LETTER_GAP => joined,
        _ => false,
    };
    // Every word one character long: the wide gaps were between letters. Not with a `/`
    // or `(space)`, which always separates words.
    let gaps_are_letter_gaps = !decoded.contains(&WORD_GAP)
        && decoded.split(|&byte| is_word_gap(byte)).all(|word| {
            word.iter()
                .filter(|&&byte| byte != LETTER_GAP)
                .take(2)
                .count()
                == 1
        });

    let mut plaintext = String::with_capacity(decoded.len());
    for &byte in &decoded {
        if is_word_gap(byte) {
            if !gaps_are_letter_gaps {
                plaintext.push(' ');
            }
        } else if byte != LETTER_GAP {
            plaintext.push(char::from(byte));
        }
    }
    // `Space` code words at either end
    let plaintext = plaintext.trim_matches(' ');
    (plaintext.len() >= MIN_DECODED_LEN).then(|| plaintext.to_string())
}

/// Decodes code words joined with `-`, `/` or `|`, such as `Hotel-Echo`, onto `decoded`.
/// Returns `None` if a piece isn't a code word, including the empty pieces of `--`.
fn decode_joined(token: &[u8], decoded: &mut Vec<u8>) -> Option<()> {
    let mut pieces = token.split(|&byte| is_separator(byte));
    let mut piece = pieces.next();
    while let Some(word) = piece {
        let next = pieces.next();
        let (character, used_next) = decode_code_word(word, next)?;
        decoded.push(character);
        piece = if used_next { pieces.next() } else { next };
    }
    Some(())
}

/// Decodes one code word of ASCII letters. `next` is the code word after it at the same
/// level: the next piece of a joined token, or the next token of letters. When `word` and
/// `next` are the two halves of `X ray`, `Full stop` or `Fraction bar`, the second value
/// returned is `true`.
fn decode_code_word(word: &[u8], next: Option<&[u8]>) -> Option<(u8, bool)> {
    let mut buffer = [0; MAX_CODE_WORD_LEN];
    let lower = buffer.get_mut(..word.len())?;
    for (lower, byte) in lower.iter_mut().zip(word) {
        *lower = byte.to_ascii_lowercase();
    }
    if let Some(character) = code_word(lower) {
        return Some((character, false));
    }
    let (second_half, character): (&[u8], u8) = match &*lower {
        b"x" => (b"ray", b'x'),
        b"full" => (b"stop", b'.'),
        b"fraction" => (b"bar", b'/'),
        _ => return None,
    };
    next.filter(|next| next.eq_ignore_ascii_case(second_half))
        .map(|_| (character, true))
}

/// The character a lower-case code word stands for.
/// Sources: <https://en.wikipedia.org/wiki/NATO_phonetic_alphabet> (the ICAO letters and
/// digits, the ITU/IMO digit compounds, the spoken digit forms and the CCEB punctuation),
/// CyberChef's `Convert to NATO alphabet` and <https://www.dcode.fr/nato-phonetic-alphabet>.
fn code_word(word: &[u8]) -> Option<u8> {
    let character = match word {
        b"alfa" | b"alpha" => b'a',
        b"bravo" => b'b',
        b"charlie" => b'c',
        b"delta" => b'd',
        b"echo" => b'e',
        b"foxtrot" => b'f',
        b"golf" => b'g',
        b"hotel" => b'h',
        b"india" => b'i',
        b"juliett" | b"juliet" => b'j',
        b"kilo" => b'k',
        b"lima" => b'l',
        b"mike" => b'm',
        b"november" => b'n',
        b"oscar" => b'o',
        b"papa" => b'p',
        b"quebec" => b'q',
        b"romeo" => b'r',
        b"sierra" => b's',
        b"tango" => b't',
        b"uniform" => b'u',
        b"victor" => b'v',
        b"whiskey" | b"whisky" => b'w',
        // `X-ray` and `X ray` are read as two halves, see `decode_code_word`
        b"xray" => b'x',
        b"yankee" => b'y',
        b"zulu" => b'z',
        // The ICAO word, the ITU/IMO compound and the way it's said
        b"zero" | b"nadazero" => b'0',
        b"one" | b"unaone" | b"wun" => b'1',
        b"two" | b"bissotwo" | b"too" => b'2',
        b"three" | b"terrathree" | b"tree" => b'3',
        b"four" | b"kartefour" | b"fower" => b'4',
        b"five" | b"pantafive" | b"fife" => b'5',
        b"six" | b"soxisix" => b'6',
        b"seven" | b"setteseven" => b'7',
        b"eight" | b"oktoeight" | b"ait" => b'8',
        b"nine" | b"novenine" | b"niner" => b'9',
        b"comma" => b',',
        // `Full stop` is read as two halves, see `decode_code_word`
        b"stop" | b"decimal" | b"point" => b'.',
        b"hyphen" | b"dash" => b'-',
        // `Fraction bar` is read as two halves, see `decode_code_word`
        b"slant" => b'/',
        b"space" => b' ',
        _ => return None,
    };
    Some(character)
}

/// Whether `byte` joins the code words of a word, as in `Hotel-Echo`
fn is_separator(byte: u8) -> bool {
    matches!(byte, b'-' | b'/' | b'|')
}

/// What a token is made of
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum TokenKind {
    /// Only letters: one code word, or one half of `X ray`, `Full stop` or `Fraction bar`
    Letters,
    /// Letters joined with `-`, `/` or `|`, like `Hotel-Echo`. Also `-` on its own, which
    /// has only empty pieces and so fails to decode.
    Joined,
    /// A `/`, `|` or `(space)` on its own: the gap between two words
    WordGap,
}

/// A run of bytes between two runs of whitespace
#[derive(Debug)]
struct Token<'a> {
    /// The bytes of the token
    text: &'a [u8],
    /// What the token is made of
    kind: TokenKind,
    /// Whether the whitespace before the token is a single space or tab
    narrow_gap_before: bool,
}

/// The text can't be NATO text: it has a byte no code word or separator has, or a run of
/// letters longer than any code word
#[derive(Debug)]
struct NotNato;

/// Splits text into tokens. It stops with `Err(NotNato)` as soon as it reaches a byte that
/// can't be in NATO text, or a run of letters too long to be a code word, so most text
/// is rejected within its first few bytes.
struct Tokens<'a> {
    /// The text after the last token
    rest: &'a [u8],
}

impl<'a> Iterator for Tokens<'a> {
    type Item = Result<Token<'a>, NotNato>;

    fn next(&mut self) -> Option<Self::Item> {
        let gap_len = self
            .rest
            .iter()
            .take_while(|byte| byte.is_ascii_whitespace())
            .count();
        let (gap, rest) = self.rest.split_at(gap_len);
        if rest.is_empty() {
            self.rest = rest;
            return None;
        }
        let narrow_gap_before = matches!(gap, b" " | b"\t");

        match scan_token(rest) {
            Ok((len, kind)) => {
                let (text, rest) = rest.split_at(len);
                self.rest = rest;
                Some(Ok(Token {
                    text,
                    kind,
                    narrow_gap_before,
                }))
            }
            Err(not_nato) => {
                self.rest = &[];
                Some(Err(not_nato))
            }
        }
    }
}

/// Measures the token at the start of `text` and works out its kind. Fails at the first
/// byte that can't be in NATO text, and at the first run of letters too long to be a
/// code word.
fn scan_token(text: &[u8]) -> Result<(usize, TokenKind), NotNato> {
    const SPACE_WORD: &[u8] = b"(space)";
    if text
        .get(..SPACE_WORD.len())
        .is_some_and(|start| start.eq_ignore_ascii_case(SPACE_WORD))
        && text
            .get(SPACE_WORD.len())
            .is_none_or(|byte| byte.is_ascii_whitespace())
    {
        return Ok((SPACE_WORD.len(), TokenKind::WordGap));
    }

    let mut len = 0;
    // Letters since the last separator
    let mut run = 0;
    let mut has_letters = false;
    let mut has_hyphen = false;
    let mut has_separator = false;
    for &byte in text {
        if byte.is_ascii_alphabetic() {
            run += 1;
            if run > MAX_CODE_WORD_LEN {
                return Err(NotNato);
            }
            has_letters = true;
        } else if is_separator(byte) {
            run = 0;
            has_separator = true;
            has_hyphen |= byte == b'-';
        } else if byte.is_ascii_whitespace() {
            break;
        } else {
            return Err(NotNato);
        }
        len += 1;
    }

    let kind = if !has_separator {
        TokenKind::Letters
    } else if !has_letters && !has_hyphen {
        TokenKind::WordGap
    } else {
        TokenKind::Joined
    };
    Ok((len, kind))
}

#[cfg(test)]
mod tests {
    use super::{code_word, decode_nato, NatoPhoneticDecoder, MAX_CODE_WORD_LEN};
    use crate::checkers::athena::Athena;
    use crate::checkers::checker_type::{Check, Checker};
    use crate::checkers::CheckerTypes;
    use crate::decoders::crack_results::CrackResult;
    use crate::decoders::interface::{Crack, Decoder};
    use crate::decoders::{DecoderType, DECODER_MAP};
    use crate::filtration_system::get_decoder_by_name;

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    /// Runs the decoder with the Athena checker
    fn crack(text: &str) -> CrackResult {
        let result = Decoder::<NatoPhoneticDecoder>::new().crack(text, &get_athena_checker());
        if result.unencrypted_text.is_none() {
            assert!(!result.success, "{text:?} failed but was marked successful");
        }
        result
    }

    /// Asserts that Athena identifies what `text` decodes to, and that it is `expected`
    fn assert_identified(text: &str, expected: &str) {
        let result = crack(text);
        assert_eq!(
            result.unencrypted_text.as_deref(),
            Some(&[expected.to_string()][..]),
            "decoding {text:?}"
        );
        assert!(result.success, "Athena should identify {expected:?}");
    }

    /// Asserts that `text` decodes to `expected`, whether or not Athena identifies it
    fn assert_decodes(text: &str, expected: &str) {
        assert_eq!(
            crack(text).unencrypted_text.as_deref(),
            Some(&[expected.to_string()][..]),
            "decoding {text:?}"
        );
    }

    /// Asserts that `text` isn't decoded at all
    fn assert_rejected(text: &str) {
        assert_eq!(crack(text).unencrypted_text, None, "decoding {text:?}");
    }

    // The CyberChef vectors are the output of CyberChef's `Convert to NATO alphabet`: the
    // issue plan used CyberChef 10.24, and they were generated again for this module by
    // running that operation's `run` and `lookup` from CyberChef's source
    // (src/core/operations/ConvertToNATOAlphabet.mjs) in Node 22. It writes `Word ` for
    // every character, so a space in the plaintext becomes two spaces and the output ends
    // with a space.

    #[test]
    fn decodes_the_issue_example() {
        // https://github.com/bee-san/Ciphey/issues/964 (CyberChef)
        assert_identified(
            "Hotel Echo Lima Lima Oscar  Whiskey Oscar Romeo Lima Delta",
            "hello world",
        );
        assert_identified(
            "Hotel Echo Lima Lima Oscar  Whiskey Oscar Romeo Lima Delta ",
            "hello world",
        );
    }

    #[test]
    fn decodes_cyberchef_sentences() {
        assert_identified(
            "Alfa Tango Tango Alfa Charlie Kilo  Alfa Tango  Delta Alfa Whiskey November ",
            "attack at dawn",
        );
        // `X-ray` among space-separated code words is one code word, not two joined ones
        assert_identified(
            "Tango Hotel Echo  Quebec Uniform India Charlie Kilo  Bravo Romeo Oscar Whiskey November  Foxtrot Oscar X-ray  Juliett Uniform Mike Papa Sierra  Oscar Victor Echo Romeo  Tango Hotel Echo  Lima Alfa Zulu Yankee  Delta Oscar Golf ",
            "the quick brown fox jumps over the lazy dog",
        );
    }

    #[test]
    fn decodes_cyberchef_punctuation() {
        // `Full stop` and `Fraction bar` are two tokens each
        assert_identified(
            "Hotel Echo Lima Lima Oscar Comma  Whiskey Oscar Romeo Lima Delta Full stop  One Fraction bar Two ",
            "hello, world. 1/2",
        );
    }

    #[test]
    fn decodes_every_character_cyberchef_writes() {
        // The test string of CyberChef's own test for the operation
        assert_decodes(
            "Alfa Bravo Charlie Delta Echo Foxtrot Golf Hotel India Juliett Kilo Lima Mike November Oscar Papa Quebec Romeo Sierra Tango Uniform Victor Whiskey X-ray Yankee Zulu Zero One Two Three Four Five Six Seven Eight Nine Comma Fraction bar Full stop ",
            "abcdefghijklmnopqrstuvwxyz0123456789,/.",
        );
    }

    #[test]
    fn decodes_code_words_joined_with_separators() {
        assert_identified(
            "Hotel-Echo-Lima-Lima-Oscar Whiskey-Oscar-Romeo-Lima-Delta",
            "hello world",
        );
        assert_identified(
            "Hotel/Echo/Lima/Lima/Oscar  Whiskey/Oscar/Romeo/Lima/Delta",
            "hello world",
        );
        assert_identified(
            "Hotel|Echo|Lima|Lima|Oscar Whiskey|Oscar|Romeo|Lima|Delta",
            "hello world",
        );
        // https://en.wikipedia.org/wiki/NATO_phonetic_alphabet
        assert_decodes("Delta-Hotel-Niner-Eight", "dh98");
        // `X-ray` inside a joined word is two pieces
        assert_decodes("Foxtrot-Oscar-X-ray", "fox");
        // A one-letter word between joined ones
        assert_identified(
            "Mike-Echo-Echo-Tango Mike-Echo Alfa-Tango Tango-Hotel-Echo Oscar-Lima-Delta Lima-India-Golf-Hotel-Tango-Hotel-Oscar-Uniform-Sierra-Echo Alfa-Foxtrot-Tango-Echo-Romeo Mike-India-Delta-November-India-Golf-Hotel-Tango Alfa-November-Delta Bravo-Romeo-India-November-Golf Tango-Hotel-Echo Mike-Alfa-Papa-Comma Tango-Hotel-Echo Kilo-Echo-Yankee Alfa-November-Delta Alfa Tango-Oscar-Romeo-Charlie-Hotel-Stop",
            "meet me at the old lighthouse after midnight and bring the map, the key and a torch.",
        );
    }

    #[test]
    fn decodes_upper_case_and_line_breaks() {
        assert_identified(
            "HOTEL ECHO LIMA LIMA OSCAR\nWHISKEY OSCAR ROMEO LIMA DELTA",
            "hello world",
        );
        assert_identified(
            "hOtEl EcHo LiMa LiMa OsCaR\r\nwHiSkEy OsCaR rOmEo LiMa DeLtA\n",
            "hello world",
        );
    }

    #[test]
    fn decodes_other_translators_word_gaps() {
        // https://www.wordcounttool.com/nato-phonetic-translator: `Hi 25`
        assert_decodes("Hotel India / Two Five", "hi 25");
        // https://www.omnicalculator.com/everyday-life/nato-phonetic-alphabet: `Hello world`
        assert_identified(
            "Hotel Echo Lima Lima Oscar (space) Whiskey Oscar Romeo Lima Delta",
            "hello world",
        );
        assert_identified(
            "Hotel Echo Lima Lima Oscar (SPACE) Whiskey Oscar Romeo Lima Delta",
            "hello world",
        );
        assert_identified(
            "Hotel Echo Lima Lima Oscar | Whiskey Oscar Romeo Lima Delta",
            "hello world",
        );
        // Unlike a wide gap, a `/` or `(space)` is always between words
        assert_decodes("Alfa / Bravo / Charlie", "a b c");
        assert_decodes("Alfa (space) Bravo (space) Charlie", "a b c");
        // Gaps at either end are dropped
        assert_decodes("/ Alfa Bravo Charlie /", "abc");
        // The `Space` code word
        assert_identified(
            "Hotel Echo Lima Lima Oscar Space Whiskey Oscar Romeo Lima Delta",
            "hello world",
        );
    }

    #[test]
    fn decodes_other_spellings() {
        assert_decodes("Alpha Bravo Charlie", "abc");
        assert_decodes("Xray Yankee Zulu", "xyz");
        assert_decodes("Foxtrot Oscar X-ray", "fox");
        assert_decodes("Foxtrot Oscar X ray", "fox");
        assert_decodes("Juliet Uniform Lima India Echo Tango Tango", "juliett");
        assert_decodes("Tree Fower Fife Niner", "3459");
        assert_decodes("Nadazero Unaone Bissotwo", "012");
        // The longest code words
        assert_decodes("Terrathree Setteseven Oktoeight", "378");
    }

    #[test]
    fn decodes_letters_separated_by_wide_gaps() {
        // Every word would be one letter long, so the double spaces are between letters
        assert_decodes("Hotel  Echo  Lima  Lima  Oscar", "hello");
        // A single word: dCode's example
        let result = crack("Alfa Lima Papa Hotel Alfa Bravo Echo Tango");
        assert_eq!(result.unencrypted_text.unwrap()[0], "alphabet");
        assert!(result.success, "Athena should identify `alphabet`");
    }

    #[test]
    fn decodes_a_real_ctf_challenge() {
        // TFC CTF 2023 "MAYDAY!": https://raw.githubusercontent.com/sajjadium/ctf-archives/main/ctfs/TFC/2023/crypto/MAYDAY/README.md
        // The flag was TFCCTF{WH4T-AR3-YOU-S1NKING-4B0U7}
        assert_decodes(
            "Whiskey Hotel Four Tango Dash Alpha Romeo Three Dash Yankee Oscar Uniform Dash Sierra One November Kilo India November Golf Dash Four Bravo Zero Uniform Seven",
            "wh4t-ar3-you-s1nking-4b0u7",
        );
    }

    #[test]
    fn decodes_the_bench_inputs() {
        // CyberChef of the bench `medium` plaintext
        assert_identified(
            "Mike Echo Echo Tango  Mike Echo  Alfa Tango  Tango Hotel Echo  Oscar Lima Delta  Lima India Golf Hotel Tango Hotel Oscar Uniform Sierra Echo  Alfa Foxtrot Tango Echo Romeo  Mike India Delta November India Golf Hotel Tango  Alfa November Delta  Bravo Romeo India November Golf  Tango Hotel Echo  Mike Alfa Papa Comma  Tango Hotel Echo  Kilo Echo Yankee  Alfa November Delta  Alfa  Tango Oscar Romeo Charlie Hotel Full stop ",
            "meet me at the old lighthouse after midnight and bring the map, the key and a torch.",
        );
    }

    #[test]
    fn every_spelling_is_a_code_word() {
        let spellings: &[(&str, u8)] = &[
            ("alfa", b'a'),
            ("alpha", b'a'),
            ("bravo", b'b'),
            ("charlie", b'c'),
            ("delta", b'd'),
            ("echo", b'e'),
            ("foxtrot", b'f'),
            ("golf", b'g'),
            ("hotel", b'h'),
            ("india", b'i'),
            ("juliett", b'j'),
            ("juliet", b'j'),
            ("kilo", b'k'),
            ("lima", b'l'),
            ("mike", b'm'),
            ("november", b'n'),
            ("oscar", b'o'),
            ("papa", b'p'),
            ("quebec", b'q'),
            ("romeo", b'r'),
            ("sierra", b's'),
            ("tango", b't'),
            ("uniform", b'u'),
            ("victor", b'v'),
            ("whiskey", b'w'),
            ("whisky", b'w'),
            ("xray", b'x'),
            ("yankee", b'y'),
            ("zulu", b'z'),
            ("zero", b'0'),
            ("nadazero", b'0'),
            ("one", b'1'),
            ("unaone", b'1'),
            ("wun", b'1'),
            ("two", b'2'),
            ("bissotwo", b'2'),
            ("too", b'2'),
            ("three", b'3'),
            ("terrathree", b'3'),
            ("tree", b'3'),
            ("four", b'4'),
            ("kartefour", b'4'),
            ("fower", b'4'),
            ("five", b'5'),
            ("pantafive", b'5'),
            ("fife", b'5'),
            ("six", b'6'),
            ("soxisix", b'6'),
            ("seven", b'7'),
            ("setteseven", b'7'),
            ("eight", b'8'),
            ("oktoeight", b'8'),
            ("ait", b'8'),
            ("nine", b'9'),
            ("novenine", b'9'),
            ("niner", b'9'),
            ("comma", b','),
            ("stop", b'.'),
            ("decimal", b'.'),
            ("point", b'.'),
            ("hyphen", b'-'),
            ("dash", b'-'),
            ("slant", b'/'),
            ("space", b' '),
        ];
        for &(spelling, character) in spellings {
            assert_eq!(
                code_word(spelling.as_bytes()),
                Some(character),
                "{spelling}"
            );
            assert!(
                spelling.len() <= MAX_CODE_WORD_LEN,
                "{spelling} is too long"
            );
        }
        assert!(spellings.iter().any(|(s, _)| s.len() == MAX_CODE_WORD_LEN));

        // The halves of the two-word code words aren't code words on their own
        for half in ["x", "ray", "full", "fraction", "bar"] {
            assert_eq!(code_word(half.as_bytes()), None, "{half}");
        }
    }

    #[test]
    fn two_word_code_words_need_both_halves() {
        assert_rejected("Alfa Bravo X");
        assert_rejected("Alfa Bravo Full");
        assert_rejected("Alfa Bravo Fraction");
        assert_rejected("Alfa Bravo Ray");
        assert_rejected("Alfa Bravo Full / stop");
        // A joined word's halves have to be in the same word: in a joined text `stop` is
        // the next word and `Full` on its own isn't a code word
        assert_rejected("Tango-Oscar-Romeo-Charlie-Hotel-Full stop");
        assert_decodes("Tango-Oscar-Romeo-Charlie-Hotel-Full-stop", "torch.");
        assert_decodes("Alfa-Bravo-Fraction-Bar", "ab/");
    }

    #[test]
    fn x_ray_does_not_make_the_text_joined() {
        // If `X-ray` made this a joined text, the single spaces would separate words
        assert_decodes("Alfa Bravo X-ray  Charlie Delta Echo", "abx cde");
    }

    #[test]
    fn spaces_in_the_plaintext_become_one_space() {
        // CyberChef of `a  b cd`: three spaces for the two between `a` and `b`
        assert_decodes("Alfa   Bravo  Charlie Delta ", "a b cd");
    }

    #[test]
    fn rejects_text_that_is_not_nato() {
        for text in [
            "",
            " ",
            " \t\r\n ",
            "😀",
            "Hotel Echo Lima Lima Oscar 😀",
            "hello world",
            "The quick brown fox jumps over the lazy dog",
            // The bench `miss` input
            "T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV",
            "Hotel Echo Lima Lima Oscar!",
            "Hotel Echo Lime Lima Oscar",
            "aGVsbG8gd29ybGQ=",
            "SG90ZWwgRWNobyBMaW1hIExpbWEgT3NjYXIgIFdoaXNrZXkgT3NjYXIgUm9tZW8gTGltYSBEZWx0YQ==",
            ".... . .-.. .-.. ---",
            "68656c6c6f20776f726c64",
            "Hotel, Echo, Lima",
            "Hotel_Echo_Lima",
            // A run of letters longer than any code word
            "Hotelecholima Lima Oscar",
            // Empty pieces
            "Hotel--Echo-Lima",
            "Hotel-Echo-Lima-",
            "-Hotel-Echo-Lima",
            "Hotel Echo - Lima",
            // `(space)` has to be a token of its own
            "Hotel Echo (space)Lima",
            "Hotel Echo (spaces) Lima",
            "Hotel Echo ( space ) Lima",
        ] {
            assert_rejected(text);
        }
    }

    #[test]
    fn rejects_fewer_than_three_characters() {
        assert_rejected("Alfa Bravo");
        assert_rejected("Bravo Zulu");
        assert_rejected("Alfa  Bravo");
        assert_rejected("Space Alfa Space");
        assert_rejected("/ / /");
        assert_rejected("(space)");
        assert_eq!(decode_nato("Alfa Bravo Charlie").as_deref(), Some("abc"));
    }

    #[test]
    fn is_registered() {
        // Exactly one decoder by that name runs in the search
        let decoders = get_decoder_by_name("NATO Phonetic Alphabet");
        assert_eq!(decoders.components.len(), 1);
        let decoder = &decoders.components[0];
        assert_eq!(decoder.get_name(), "NATO Phonetic Alphabet");
        assert!((decoder.get_popularity() - 0.4).abs() < f32::EPSILON);
        assert_eq!(
            decoder.get_tags(),
            &vec!["nato", "phonetic", "spelling_alphabet", "decoder"]
        );
        // Cached results name the decoder; reading them back looks it up here
        let decoder = DECODER_MAP
            .get("NATO Phonetic Alphabet")
            .expect("NATO Phonetic Alphabet should be in DECODER_MAP")
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "NATO Phonetic Alphabet");
    }
}
