//! Run an [Ook!](https://esolangs.org/wiki/Ook!) program and return what it prints.
//! Call ook_decoder.crack to use. It returns a `CrackResult` whose `unencrypted_text` is
//! `None` when the input isn't an Ook! program this decoder can run.
//!
//! Ook! (David Morgan-Mar, 2001) is Brainfuck with each instruction written as a pair of
//! the tokens `Ook.`, `Ook?` and `Ook!`:
//!
//! ```text
//! Ook. Ook?  >     Ook? Ook.  <     Ook. Ook.  +     Ook! Ook!  -
//! Ook! Ook.  .     Ook. Ook!  ,     Ook! Ook?  [     Ook? Ook!  ]
//! Ook? Ook?  does nothing
//! ```
//!
//! "Short Ook!" leaves out the `Ook`s and keeps the punctuation (`. ? . .`). Both are read,
//! also mixed, in any case (`ook.`), with any whitespace or none between the tokens
//! (`Ook.Ook?`). The program is translated to Brainfuck and run with the same interpreter
//! and instruction limit as the [Brainfuck decoder](super::brainfuck_interpreter); what it
//! prints is the plaintext.
//!
//! Programs that read input (`Ook. Ook!`), have unmatched loops, print nothing printable,
//! print more than 10,000 bytes or don't stop within the instruction limit are not decoded.

use crate::checkers::CheckerTypes;
use crate::decoders::brainfuck_interpreter::BRAINFUCK_INSTRUCTION_LIMIT;
use crate::decoders::interface::{bytes_to_string, check_string_success};

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use brainfuck_exe::Brainfuck;
use log::{debug, info, trace};

/// The Ook! decoder, call:
/// `let ook_decoder = Decoder::<OokDecoder>::new()` to create a new instance
/// And then call:
/// `result = ook_decoder.crack(input)` to run an Ook! program
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::ook_decoder::OokDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let ook_decoder = Decoder::<OokDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // The Brainfuck program `++++++++[>+++++++++++++<-]>.+.`, from issue #984
/// let program = "Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. \
///     Ook! Ook? Ook. Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. \
///     Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook? Ook. \
///     Ook! Ook! Ook? Ook! Ook. Ook? Ook! Ook. Ook. Ook. Ook! Ook.";
/// let result = ook_decoder.crack(program, &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hi");
///
/// // The same program in short Ook!, with only the punctuation
/// let short = program.replace("Ook", "");
/// let result = ook_decoder.crack(&short, &checker).unencrypted_text;
/// assert_eq!(result.unwrap()[0], "hi");
/// ```
pub struct OokDecoder;

/// Programs with fewer symbols than this, 8 instructions, aren't run. The shortest useful
/// one, issue #984's `hi`, has 60.
const MIN_SYMBOLS: usize = 16;

/// Output longer than this, in bytes, isn't checked, which keeps the checker call cheap.
/// The instruction limit already bounds it at about 1 MB.
const MAX_OUTPUT_BYTES: usize = 10_000;

impl Crack for Decoder<OokDecoder> {
    fn new() -> Decoder<OokDecoder> {
        Decoder {
            name: "Ook!",
            description: "Ook! is Brainfuck written as pairs of Ook. Ook? Ook! tokens (also the short form with only . ? !). The program is run with the Brainfuck interpreter and its output is the plaintext.",
            link: "https://esolangs.org/wiki/Ook!",
            tags: vec!["ook", "brainfuck", "esoteric", "decoder", "program"],
            popularity: 0.2,
            phantom: std::marker::PhantomData,
        }
    }

    /// Runs `text` as an Ook! program and checks what it prints with `checker`.
    /// `unencrypted_text` is `None` when `text` isn't a program this decoder runs.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Ook! with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(program) = to_brainfuck(text) else {
            debug!("Failed to decode Ook! because the text isn't an Ook! program it can run");
            return results;
        };

        let mut output = Vec::new();
        if let Err(e) = Brainfuck::new(&program)
            .with_instructions_limit(BRAINFUCK_INSTRUCTION_LIMIT)
            .with_output_ref(&mut output)
            .execute()
        {
            debug!("Failed to run Ook! because of error {:?}", e);
            return results;
        }

        // `.` prints every cell, control characters too: output with nothing printable in
        // it, such as the NULs of a program that never sets a cell, isn't text
        if output.len() > MAX_OUTPUT_BYTES || !output.iter().any(|b| (b' '..=b'~').contains(b)) {
            debug!(
                "Failed to decode Ook! because its {} byte output has nothing printable or is too long",
                output.len()
            );
            return results;
        }
        // brainfuck-exe writes each cell as a UTF-8 char, so this is always UTF-8 and cells
        // 128 to 255 come out as U+0080 to U+00FF
        let decoded_text = bytes_to_string(output);

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Ook! because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Translates an Ook! program into Brainfuck. `None` if `text` isn't a program this
/// decoder runs: it isn't made of Ook! tokens, is too short, reads input, has an unmatched
/// loop or never prints.
fn to_brainfuck(text: &str) -> Option<String> {
    let bytes = text.as_bytes();
    let count = count_symbols(bytes)?;
    if count % 2 != 0 || count < MIN_SYMBOLS {
        return None;
    }

    // Every byte is whitespace, part of an `Ook` or a symbol, so the symbols are the bytes
    // that are `.`, `?` or `!`
    let mut symbols = bytes
        .iter()
        .copied()
        .filter(|&b| matches!(b, b'.' | b'?' | b'!'));
    let mut program = String::with_capacity(count / 2);
    let mut depth: usize = 0;
    let mut prints = false;
    while let (Some(first), Some(second)) = (symbols.next(), symbols.next()) {
        let instruction = match (first, second) {
            (b'.', b'?') => '>',
            (b'?', b'.') => '<',
            (b'.', b'.') => '+',
            (b'!', b'!') => '-',
            (b'!', b'.') => {
                prints = true;
                '.'
            }
            (b'!', b'?') => {
                depth += 1;
                '['
            }
            (b'?', b'!') => {
                // A `]` before its `[`. brainfuck-exe only checks that the counts match, and
                // would step back past the start of the program looking for the `[`.
                depth = depth.checked_sub(1)?;
                ']'
            }
            (b'?', b'?') => continue,
            // `Ook. Ook!`, `,`, reads input, which there is none of. The Brainfuck decoder
            // doesn't run such programs either.
            _ => return None,
        };
        program.push(instruction);
    }
    (depth == 0 && prints).then_some(program)
}

/// Counts the symbols (`.`, `?` and `!`) in `text`, written as long tokens (`Ook.`), short
/// ones (`.`) or both. `None` at the first byte that isn't whitespace, an `Ook` followed by
/// a symbol, or a symbol, so most text is turned away at its first byte. Allocates nothing.
fn count_symbols(text: &[u8]) -> Option<usize> {
    let mut count = 0;
    let mut i = 0;
    while i < text.len() {
        if text[i].is_ascii_whitespace() {
            i += 1;
            continue;
        }
        if text
            .get(i..i + 3)
            .is_some_and(|word| word.eq_ignore_ascii_case(b"ook"))
        {
            i += 3;
        }
        match text.get(i) {
            Some(b'.' | b'?' | b'!') => {
                count += 1;
                i += 1;
            }
            _ => return None,
        }
    }
    Some(count)
}

#[cfg(test)]
mod tests {
    use super::{count_symbols, to_brainfuck, OokDecoder, MAX_OUTPUT_BYTES};
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::interface::{Crack, Decoder},
        decoders::{DecoderType, DECODER_MAP},
        filtration_system::get_decoder_by_name,
    };

    /// The example in issue #984: `++++++++[>+++++++++++++<-]>.+.`, which prints `hi`
    const ISSUE_EXAMPLE: &str = "\
        Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. \
        Ook! Ook? Ook. Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. \
        Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook? Ook. \
        Ook! Ook! Ook? Ook! Ook. Ook? Ook! Ook. Ook. Ook. Ook! Ook.";

    /// The Hello World program on <https://esolangs.org/wiki/Ook!>, with its 18 lines.
    /// It prints `Hello World!`.
    const ESOLANGS_HELLO_WORLD: &str = "\
        Ook. Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook.\n\
        Ook. Ook. Ook. Ook. Ook! Ook? Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook.\n\
        Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook? Ook! Ook! Ook? Ook! Ook? Ook.\n\
        Ook! Ook. Ook. Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook.\n\
        Ook. Ook. Ook! Ook? Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook?\n\
        Ook! Ook! Ook? Ook! Ook? Ook. Ook. Ook. Ook! Ook. Ook. Ook. Ook. Ook. Ook. Ook.\n\
        Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook! Ook. Ook! Ook. Ook. Ook. Ook. Ook.\n\
        Ook. Ook. Ook! Ook. Ook. Ook? Ook. Ook? Ook. Ook? Ook. Ook. Ook. Ook. Ook. Ook.\n\
        Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook! Ook? Ook? Ook. Ook. Ook.\n\
        Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook? Ook! Ook! Ook? Ook! Ook? Ook. Ook! Ook.\n\
        Ook. Ook? Ook. Ook? Ook. Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook.\n\
        Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook! Ook? Ook? Ook. Ook. Ook.\n\
        Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook.\n\
        Ook. Ook? Ook! Ook! Ook? Ook! Ook? Ook. Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook.\n\
        Ook? Ook. Ook? Ook. Ook? Ook. Ook? Ook. Ook! Ook. Ook. Ook. Ook. Ook. Ook. Ook.\n\
        Ook! Ook. Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook.\n\
        Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook!\n\
        Ook! Ook. Ook. Ook? Ook. Ook? Ook. Ook. Ook! Ook.";

    /// `><++++++++[>+++++++++++++<-]>.---.+++++++..+++.[-]<++++[>++++++++<-]>.[-]<++++++++++[>++++++++++++<-]>-.--------.+++.------.--------.`
    /// written with the table on <https://esolangs.org/wiki/Ook!>, one space between
    /// tokens. It prints `hello world`.
    const HELLO_WORLD: &str = "\
        Ook. Ook? Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. \
        Ook. Ook. Ook. Ook. Ook! Ook? Ook. Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. \
        Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. \
        Ook. Ook. Ook? Ook. Ook! Ook! Ook? Ook! Ook. Ook? Ook! Ook. Ook! Ook! Ook! Ook! \
        Ook! Ook! Ook! Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. \
        Ook. Ook. Ook! Ook. Ook! Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook! Ook. Ook! Ook? \
        Ook! Ook! Ook? Ook! Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook! Ook? \
        Ook. Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. \
        Ook. Ook. Ook? Ook. Ook! Ook! Ook? Ook! Ook. Ook? Ook! Ook. Ook! Ook? Ook! Ook! \
        Ook? Ook! Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. \
        Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook! Ook? Ook. Ook? Ook. Ook. Ook. Ook. \
        Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. \
        Ook. Ook. Ook. Ook. Ook? Ook. Ook! Ook! Ook? Ook! Ook. Ook? Ook! Ook! Ook! Ook. \
        Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! \
        Ook! Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook! Ook. Ook! Ook! Ook! Ook! Ook! Ook! \
        Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook. Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! \
        Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook! Ook.";

    /// `><++++++++[>+++++++++++++<-]>.---.+++++++..+++.[-]<++++[>++++++++<-]>+.`, written
    /// like [`HELLO_WORLD`]. It prints `hello!`.
    const HELLO: &str = "\
        Ook. Ook? Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. \
        Ook. Ook. Ook. Ook. Ook! Ook? Ook. Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. \
        Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. \
        Ook. Ook. Ook? Ook. Ook! Ook! Ook? Ook! Ook. Ook? Ook! Ook. Ook! Ook! Ook! Ook! \
        Ook! Ook! Ook! Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. \
        Ook. Ook. Ook! Ook. Ook! Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook! Ook. Ook! Ook? \
        Ook! Ook! Ook? Ook! Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook! Ook? \
        Ook. Ook? Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. Ook. \
        Ook. Ook. Ook? Ook. Ook! Ook! Ook? Ook! Ook. Ook? Ook. Ook. Ook! Ook.";

    /// Pragyan CTF 2016, "K": short Ook! in 29 lines, from
    /// <https://raw.githubusercontent.com/shiltemann/CTF-writeups-public/master/Pragyan_2016/writeup.md>.
    /// It prints the flag Caesar-shifted by 14, `hvstzouwgccywgbchgcsogm`.
    const PRAGYAN_CTF_2016_K: &str = "\
        . . . . . . . . . . . . . . .\n\
        . . . . . ! ? ! ! . ? . . . .\n\
        . . . . . . . . . . . . . . .\n\
        . ? . ? ! . ? . . . . . . . .\n\
        ! . ? . . . . . . . ! ? ! ! .\n\
        ? . . . . . . ? . ? ! . ? . .\n\
        . . . . . . . . ! . ! ! ! ! !\n\
        ! ! . . . ! . . . . . . . . .\n\
        . . . . ! . ? . . . . . . . !\n\
        ? ! ! . ? ! ! ! ! ! ! ? . ? !\n\
        . ? ! ! ! ! ! . . . . . . . .\n\
        . . . . . ! . . . . . ! . ? .\n\
        . . . . . . . . ! ? ! ! . ? !\n\
        ! ! ! ! ! ! ! ? . ? ! . ? ! .\n\
        ! ! ! ! ! ! ! ! ! . ! . ? . .\n\
        . . . . . . . ! ? ! ! . ? . .\n\
        . . . . . . ? . ? ! . ? . . .\n\
        . . . . . . . . . ! . ! ! ! !\n\
        ! . ? . . . . . . . . . ! ? !\n\
        ! . ? ! ! ! ! ! ! ! ! ? . ? !\n\
        . ? ! . ! ! ! ! ! ! ! ! ! ! !\n\
        . . . ! . . . . . . . . . . .\n\
        ! . ! ! ! . ! ! ! ! ! ! ! ! !\n\
        . ? . . . . . . . . . ! ? ! !\n\
        . ? . . . . . . . . ? . ? ! .\n\
        ? ! . ! ! ! ! ! ! ! ! ! . ! !\n\
        ! ! ! ! ! ! ! ! ! ! ! ! ! ! !\n\
        . . . . . . . . . . . . . ! .\n\
        ? .";

    /// The text the decoder benchmarks use for every decoder's miss
    const BENCH_MISS: &str =
        "T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV";

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    /// What the decoder prints for `text`, whether or not the checker accepts it
    fn decode(text: &str) -> Option<String> {
        Decoder::<OokDecoder>::new()
            .crack(text, &get_athena_checker())
            .unencrypted_text
            .map(|texts| texts[0].clone())
    }

    /// Asserts that `text` prints `expected` and that Athena takes it for plaintext
    #[track_caller]
    fn assert_identified(text: &str, expected: &str) {
        let result = Decoder::<OokDecoder>::new().crack(text, &get_athena_checker());
        assert_eq!(
            result.unencrypted_text.as_deref(),
            Some(&[expected.to_string()][..])
        );
        assert!(result.success, "Athena didn't identify {expected:?}");
    }

    /// Asserts that `text` is turned away
    #[track_caller]
    fn assert_not_decoded(text: &str) {
        let result = Decoder::<OokDecoder>::new().crack(text, &get_athena_checker());
        assert_eq!(result.unencrypted_text, None, "{text:?}");
        assert!(!result.success);
    }

    /// `brainfuck` in Ook!, with the table on <https://esolangs.org/wiki/Ook!>. `short`
    /// leaves out the `Ook`s.
    fn from_brainfuck(brainfuck: &str, short: bool) -> String {
        let word = if short { "" } else { "Ook" };
        brainfuck
            .chars()
            .map(|instruction| {
                let (first, second) = match instruction {
                    '>' => ('.', '?'),
                    '<' => ('?', '.'),
                    '+' => ('.', '.'),
                    '-' => ('!', '!'),
                    '.' => ('!', '.'),
                    ',' => ('.', '!'),
                    '[' => ('!', '?'),
                    ']' => ('?', '!'),
                    other => panic!("{other:?} isn't Brainfuck"),
                };
                format!("{word}{first} {word}{second}")
            })
            .collect::<Vec<_>>()
            .join(" ")
    }

    #[test]
    fn issue_example_prints_hi() {
        // `hi` is too short for Athena to identify, so only the output is checked
        assert_eq!(decode(ISSUE_EXAMPLE).as_deref(), Some("hi"));
        assert_eq!(
            to_brainfuck(ISSUE_EXAMPLE).as_deref(),
            Some("++++++++[>+++++++++++++<-]>.+.")
        );
    }

    #[test]
    fn short_ook_prints_hi() {
        let short = ISSUE_EXAMPLE.replace("Ook", "");
        assert!(short.starts_with(". . . . "));
        assert_eq!(decode(&short).as_deref(), Some("hi"));
    }

    #[test]
    fn lower_case_ook_prints_hi() {
        assert_eq!(
            decode(&ISSUE_EXAMPLE.replace("Ook", "ook")).as_deref(),
            Some("hi")
        );
        assert_eq!(
            decode(&ISSUE_EXAMPLE.replace("Ook", "OOK")).as_deref(),
            Some("hi")
        );
    }

    #[test]
    fn tokens_without_spaces_print_hi() {
        let joined = ISSUE_EXAMPLE.replace(' ', "");
        assert!(joined.starts_with("Ook.Ook.Ook."));
        assert_eq!(decode(&joined).as_deref(), Some("hi"));
        assert_eq!(
            decode(&joined.replace("Ook", "")).as_deref(),
            Some("hi"),
            "short Ook! without spaces"
        );
    }

    #[test]
    fn long_and_short_tokens_can_be_mixed() {
        // Every other token without its `Ook`: `Ook. . Ook. . ...`
        let mixed: Vec<String> = ISSUE_EXAMPLE
            .split(' ')
            .enumerate()
            .map(|(i, token)| {
                if i % 2 == 0 {
                    token.to_string()
                } else {
                    token.replace("Ook", "")
                }
            })
            .collect();
        assert_eq!(decode(&mixed.join(" ")).as_deref(), Some("hi"));
    }

    #[test]
    fn no_ops_are_skipped() {
        // `Ook? Ook?` does nothing: one before every instruction
        let tokens: Vec<&str> = ISSUE_EXAMPLE.split(' ').collect();
        let padded = tokens
            .chunks(2)
            .map(|instruction| format!("Ook? Ook? {}", instruction.join(" ")))
            .collect::<Vec<_>>()
            .join(" ");
        assert_eq!(decode(&padded).as_deref(), Some("hi"));
        assert_eq!(
            to_brainfuck(&padded).as_deref(),
            Some("++++++++[>+++++++++++++<-]>.+.")
        );
    }

    #[test]
    fn every_instruction_is_translated() {
        // The table on esolangs, in its order: > < + - . , [ ] and the no-op. `,` stops the
        // decoder, so it is left out here.
        assert_eq!(
            to_brainfuck(
                "Ook. Ook? Ook? Ook. Ook. Ook. Ook! Ook! Ook! Ook. Ook! Ook? Ook? Ook! Ook? Ook?"
            )
            .as_deref(),
            Some("><+-.[]")
        );
        // The helper the other tests use agrees with the hand-written vectors
        assert_eq!(
            from_brainfuck("++++++++[>+++++++++++++<-]>.+.", false),
            ISSUE_EXAMPLE
        );
        assert_eq!(
            from_brainfuck("><++++++++[>+++++++++++++<-]>.---.+++++++..+++.[-]<++++[>++++++++<-]>.[-]<++++++++++[>++++++++++++<-]>-.--------.+++.------.--------.", false),
            HELLO_WORLD
        );
    }

    #[test]
    fn esolangs_hello_world_is_identified() {
        assert_identified(ESOLANGS_HELLO_WORLD, "Hello World!");
    }

    #[test]
    fn esolangs_hello_world_with_crlf_is_identified() {
        assert_identified(&ESOLANGS_HELLO_WORLD.replace('\n', "\r\n"), "Hello World!");
    }

    #[test]
    fn hello_world_is_identified() {
        assert_eq!(HELLO_WORLD.len(), 1_329);
        assert_identified(HELLO_WORLD, "hello world");
    }

    #[test]
    fn short_hello_world_is_identified() {
        let short = HELLO_WORLD.replace("Ook", "");
        assert_eq!(short.len(), 531);
        assert_identified(&short, "hello world");
    }

    #[test]
    fn hello_is_identified() {
        assert_eq!(HELLO.len(), 709);
        assert_identified(HELLO, "hello!");
    }

    #[test]
    fn pragyan_ctf_2016_k_prints_the_shifted_flag() {
        // The flag is `theflagisookisnotsoeasy`; the Caesar shift is another decoder's job
        assert_eq!(
            decode(PRAGYAN_CTF_2016_K).as_deref(),
            Some("hvstzouwgccywgbchgcsogm")
        );
        // The challenge file has CRLF line endings
        assert_eq!(
            decode(&PRAGYAN_CTF_2016_K.replace('\n', "\r\n")).as_deref(),
            Some("hvstzouwgccywgbchgcsogm")
        );
    }

    #[test]
    fn cells_above_127_are_latin_1() {
        // c a f, then cell 233: é
        let brainfuck = format!("{}.--.+++++.{}.", "+".repeat(99), "+".repeat(233 - 102));
        assert_eq!(
            decode(&from_brainfuck(&brainfuck, true)).as_deref(),
            Some("café")
        );
    }

    #[test]
    fn empty_and_blank_input_is_not_decoded() {
        assert_not_decoded("");
        assert_not_decoded("   ");
        assert_not_decoded("\n\r\n\t");
    }

    #[test]
    fn other_text_is_not_decoded() {
        assert_not_decoded("😀");
        assert_not_decoded("hello world");
        assert_not_decoded(BENCH_MISS);
        assert_not_decoded("aGVsbG8gd29ybGQ=");
        // Ook as a word, without its punctuation
        assert_not_decoded("Ook Ook Ook Ook Ook Ook Ook Ook Ook Ook Ook Ook Ook Ook Ook Ook");
        assert_not_decoded("Ook . Ook ? Ook . Ook . Ook . Ook . Ook . Ook . Ook . Ook .");
    }

    #[test]
    fn text_is_turned_away_at_its_first_byte_that_isnt_ook() {
        assert_eq!(count_symbols(BENCH_MISS.as_bytes()), None);
        assert_eq!(count_symbols(b"hello world"), None);
        // Morse stops at its first `-`, Brainfuck at its first `+`
        assert_eq!(count_symbols(b".... . .-.. .-.. ---"), None);
        assert_eq!(count_symbols(b"++++++++[>+++++++++++++<-]>.+."), None);
        assert_eq!(count_symbols(b"Ook. Ook, Ook. Ook."), None);
        assert_eq!(count_symbols(b"Ook. Ook"), None);
        // Morse with only dots is all symbols, but too short to run
        assert_eq!(count_symbols(b"... . ..."), Some(7));
        assert_eq!(count_symbols(b".... ...."), Some(8));
        assert_eq!(count_symbols(ISSUE_EXAMPLE.as_bytes()), Some(60));
    }

    #[test]
    fn morse_and_brainfuck_are_not_decoded() {
        assert_not_decoded(".... . .-.. .-.. ---");
        assert_not_decoded(".... . .-.. .-.. --- / .-- --- .-. .-.. -..");
        assert_not_decoded("... . ...");
        assert_not_decoded(".... ....");
        assert_not_decoded("++++++++[>+++++++++++++<-]>.+.");
    }

    #[test]
    fn odd_symbol_counts_are_not_decoded() {
        assert_not_decoded("Ook. Ook. Ook. Ook. Ook! Ook. Ook.");
        assert_not_decoded(&format!("{ISSUE_EXAMPLE} Ook."));
    }

    #[test]
    fn bad_tokens_are_not_decoded() {
        // `Ook. Ook, Ook. Ook. ...`
        assert_not_decoded(&ISSUE_EXAMPLE.replacen("Ook. Ook.", "Ook. Ook,", 1));
        assert_not_decoded(&ISSUE_EXAMPLE.replacen("Ook.", "Ook,", 2));
        assert_not_decoded(&ISSUE_EXAMPLE.replacen("Ook.", "Oak.", 1));
        assert_not_decoded(&format!("{ISSUE_EXAMPLE} banana"));
    }

    #[test]
    fn programs_that_read_input_are_not_decoded() {
        // `,.......`
        assert_not_decoded(&format!("Ook. Ook! {}", ["Ook! Ook."; 7].join(" ")));
        assert_not_decoded(&from_brainfuck("++++++++[>+++++++++++++<-]>.,.", false));
    }

    #[test]
    fn unmatched_loops_are_not_decoded() {
        // `]` before `[`: the bracket counts match, but brainfuck-exe would step back past
        // the start of the program
        assert_not_decoded(&from_brainfuck("][+++++++++++++.", false));
        assert_not_decoded(&from_brainfuck("+++++++++[>++++++++<-]]>.[", false));
        // A `[` that is never closed
        assert_not_decoded(&from_brainfuck("[+++++++++++++.", false));
        assert_not_decoded(&from_brainfuck("++++++++[[>+++++++++++++<-]>.+.", true));
    }

    #[test]
    fn programs_that_print_nothing_printable_are_not_decoded() {
        // `++++++++` prints nothing
        assert_not_decoded(&["Ook."; 16].join(" "));
        // No-ops only
        assert_not_decoded(&["Ook?"; 16].join(" "));
        // `........` prints eight NULs
        assert_not_decoded(&["Ook! Ook."; 8].join(" "));
        // A cell of 7, the bell
        assert_not_decoded(&from_brainfuck("+++++++.......", true));
    }

    #[test]
    fn programs_that_never_stop_are_not_decoded() {
        // Sets the cell to 65 (`A`) and prints it forever: the instruction limit stops it
        let forever = from_brainfuck("++++++++[>++++++++<-]>+[.].", false);
        assert!(forever.starts_with("Ook. Ook. Ook. Ook. "));
        assert_not_decoded(&forever);
        // The vector from the issue's plan, `+[.].`, padded to eight instructions
        assert_not_decoded(&from_brainfuck("+[.].+++", false));
    }

    #[test]
    fn output_over_10000_bytes_is_not_checked() {
        // Prints `A` 100 times `outer` times
        let program = |outer: usize| {
            from_brainfuck(
                &format!(
                    "{}>{}[>{}[<<.>>-]<-]",
                    "+".repeat(65),
                    "+".repeat(outer),
                    "+".repeat(100)
                ),
                true,
            )
        };
        assert_eq!(MAX_OUTPUT_BYTES, 10_000);
        assert_eq!(decode(&program(100)), Some("A".repeat(10_000)));
        assert_not_decoded(&program(101));
    }

    #[test]
    fn crack_keeps_the_input() {
        let result = Decoder::<OokDecoder>::new().crack(HELLO, &get_athena_checker());
        assert_eq!(result.encrypted_text, HELLO);
        assert_eq!(result.decoder, "Ook!");
    }

    #[test]
    fn is_registered() {
        // Exactly one decoder by that name runs in the search
        let decoders = get_decoder_by_name("Ook!");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Ook!");
        let tags = decoders.components[0].get_tags();
        assert!(tags.contains(&"decoder"));
        // The search lets interpreters' results be much shorter than their input
        assert!(tags.contains(&"program"));
        assert!((decoders.components[0].get_popularity() - 0.2).abs() < f32::EPSILON);
        // Cached results name the decoder; reading them back looks it up here
        let decoder = DECODER_MAP
            .get("Ook!")
            .expect("Ook! should be in DECODER_MAP")
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "Ook!");
    }
}
