//! Decode the Polybius square cipher.
//!
//! Each letter is written as its row and column in a grid, usually as two digits. In the
//! standard 5×5 square I and J share a cell, so `23` is H and `24` is I or J:
//!
//! ```text
//!       1 2 3 4 5
//!   1   A B C D E
//!   2   F G H I K
//!   3   L M N O P
//!   4   Q R S T U
//!   5   V W X Y Z
//! ```
//!
//! Also decoded:
//!
//! * coordinates written as letters, `ABCDE` or `ADFGX` (`BC` or `DF` for H),
//! * the 6×6 square of `A`–`Z` then `0`–`9`, when a `6` occurs or the letters are `ADFGVX`,
//! * column then row, which dCode calls the unusual order,
//! * the tap code square, with K in C's cell and J at `25`, when a `25` occurs. Tap code
//!   written as `2,3` comma pairs or as knocks is left to the Tap Code decoder.
//!
//! The pairs can be spaced (`23 15 31`), separated by `,` `;` `:` or `-` (`23,15,31`), or
//! run together (`231531`, `2 3 1 5 3 1`). Words are separated by two or more spaces, a line
//! break, `/` or `|`. When the coordinates of each word are run together and separated by
//! single spaces (`2315313134 5234423114`), each run is a word, unless the runs are groups
//! of one length (`2315 3131 3452 3442 3114`).
//!
//! The decoder tries at most three readings and checks them in this order: row-column on
//! the standard (or 6×6) square, the tap code square, then column-row. The first one the
//! checker identifies is returned. Otherwise the row-column readings go to the search,
//! which can try Monoalphabetic Substitution on them for a keyed square.
//!
//! References: <https://en.wikipedia.org/wiki/Polybius_square>,
//! <https://www.dcode.fr/polybius-cipher> and pycipher's `PolybiusSquare`.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, trace};

/// The standard square, row by row: the alphabet without J, which is written as I.
const STANDARD: &[u8; 25] = b"ABCDEFGHIKLMNOPQRSTUVWXYZ";

/// The tap code square: the alphabet without K, which is written as C. It only differs
/// from `STANDARD` at row 2, column 5, which is J here and K there.
const TAP: &[u8; 25] = b"ABCDEFGHIJLMNOPQRSTUVWXYZ";

/// The 6×6 square: the alphabet, then the digits.
const SQUARE6: &[u8; 36] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

/// Digit coordinates for the 5×5 squares. `coordinates[i]` is row or column `i + 1`.
const DIGITS5: &[u8] = b"12345";

/// Digit coordinates for the 6×6 square.
const DIGITS6: &[u8] = b"123456";

/// Every letter that can be a coordinate: the letters of `LETTER_SETS`.
const COORDINATE_LETTERS: &[u8] = b"ABCDEFGVX";

/// Letter coordinates, in the order they are tried: the first set that has every letter of
/// the input is used. `ABCDE` and `ADFGX` are for the 5×5 square, `ADFGVX` for the 6×6 one.
const LETTER_SETS: [&[u8]; 3] = [b"ABCDE", b"ADFGX", b"ADFGVX"];

/// The fewest letters a message needs. Shorter runs of digits, or of these letters, are too
/// often something else.
const MIN_LETTERS: usize = 3;

/// The fewest distinct coordinates a message needs. With two only four cells can be
/// reached (A, B, F and G for 1 and 2), and text made of two symbols is something else:
/// Bacon's cipher (`AABBB AABAA`) or binary.
const MIN_SYMBOLS: u32 = 3;

/// The Polybius Square decoder, call:
/// `let polybius_decoder = Decoder::<PolybiusDecoder>::new()` to create a new instance
/// And then call:
/// `result = polybius_decoder.crack(input)` to decode a Polybius square ciphertext
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::polybius_decoder::PolybiusDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_polybius = Decoder::<PolybiusDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // Two spaces between words
/// let result = decode_polybius.crack("23 15 31 31 34  52 34 42 31 14", &checker);
/// assert!(result.success);
/// assert_eq!(result.unencrypted_text.unwrap()[0], "HELLO WORLD");
/// // The square and the coordinate order
/// assert_eq!(result.key.unwrap(), "5x5 I=J, row-column");
///
/// // Coordinates written as letters
/// let result = decode_polybius.crack("BC AE CA CA CD  EB CD DB CA AD", &checker);
/// assert_eq!(result.unencrypted_text.unwrap()[0], "HELLO WORLD");
///
/// // Without word breaks the letters run together
/// let result = decode_polybius.crack("23 15 31 31 34 52 34 42 31 14", &checker);
/// assert_eq!(result.unencrypted_text.unwrap()[0], "HELLOWORLD");
/// ```
pub struct PolybiusDecoder;

impl Crack for Decoder<PolybiusDecoder> {
    fn new() -> Decoder<PolybiusDecoder> {
        Decoder {
            name: "Polybius Square",
            description: "Polybius square: each letter is written as its row and column in a 5×5 grid (I=J), as digit pairs like 23 15 31 or letter pairs like BC AE CA; also the 6×6 alphanumeric grid and column-row order.",
            link: "https://en.wikipedia.org/wiki/Polybius_square",
            tags: vec!["polybius", "substitution", "classic", "decoder"],
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// Checks each reading of the coordinates and returns the first one the checker
    /// identifies. If none is, returns the row-column readings without a key.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Polybius Square with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(scan) = scan(text) else {
            debug!("Failed to decode Polybius Square: the text isn't Polybius coordinates");
            return results;
        };
        let readings = readings(&scan);

        for reading in &readings {
            if !check_string_success(&reading.text, text) {
                continue;
            }
            let checker_result = checker.check(&reading.text);
            // If checkers return true, exit early with the correct result
            if checker_result.is_identified {
                trace!("Found a match with Polybius square {}", reading.key);
                results.unencrypted_text = Some(vec![reading.text.clone()]);
                results.update_checker(&checker_result);
                results.key = Some(reading.key.clone());
                return results;
            }
        }

        // Column-row readings are rare, and each candidate adds to the search's edge cost,
        // so only the row-column ones are handed on.
        let candidates: Vec<String> = readings
            .into_iter()
            .filter(|reading| !reading.column_row && check_string_success(&reading.text, text))
            .map(|reading| reading.text)
            .collect();
        if !candidates.is_empty() {
            results.unencrypted_text = Some(candidates);
        }
        results
    }
    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Where the words of a message end.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum WordBreaks {
    /// At gaps: two or more spaces or tabs, a line break, `/` or `|`. Inside a word the
    /// coordinates are read two at a time, across single spaces and `,;:-`.
    Gaps,
    /// At every space or tab as well: each run of coordinates is a word, as written by an
    /// encoder that keeps the spaces between words (`2315313134 5234423114`).
    Tokens,
}

/// An input that passed the pre-checks, and how to read it.
#[derive(Debug)]
struct Scan<'a> {
    /// The input without leading and trailing whitespace.
    body: &'a [u8],
    /// The coordinate symbols: `coordinates[i]` stands for row or column `i + 1`. Five of
    /// them for a 5×5 square, six for the 6×6 one.
    coordinates: &'static [u8],
    /// Where the words end.
    word_breaks: WordBreaks,
}

/// The pre-checks: one pass over the input, without allocating, that stops at the first
/// byte that rules it out. Returns how to read the input, or `None` if it isn't Polybius
/// coordinates.
///
/// The first byte has to be a digit `1`–`6` (digit mode) or one of the letters of
/// `COORDINATE_LETTERS` in either case (letter mode), which turns away almost every input.
/// After that every byte has to be a coordinate, whitespace, `/` or `|`, or in digit mode
/// one of `,;:-`. There must be at least `MIN_LETTERS` pairs, `MIN_SYMBOLS` distinct
/// coordinates and an even number of coordinates in every word. Single digits with
/// separators (`2,3 1,5`) are tap code and are turned away.
fn scan(text: &str) -> Option<Scan<'_>> {
    let body = text.trim().as_bytes();
    let first = *body.first()?;
    let digits = match first {
        b'1'..=b'6' => true,
        _ if COORDINATE_LETTERS.contains(&first.to_ascii_uppercase()) => false,
        _ => return None,
    };

    let mut lengths = Lengths::default();
    let mut separator = false;
    // Bit `digit - b'0'` or `letter - b'A'` is set for every coordinate seen.
    let mut seen: u32 = 0;
    // Spaces and tabs since the last other byte.
    let mut spaces = 0;
    for &byte in body {
        let upper = byte.to_ascii_uppercase();
        let is_coordinate = if digits {
            matches!(byte, b'1'..=b'6')
        } else {
            COORDINATE_LETTERS.contains(&upper)
        };
        if is_coordinate {
            seen |= symbol_bit(upper);
            lengths.coordinate();
            spaces = 0;
            continue;
        }

        lengths.end_token();
        match byte {
            b' ' | b'\t' => {
                spaces += 1;
                if spaces == 2 {
                    lengths.end_word();
                }
            }
            b'\n' | b'\r' | b'\x0c' | b'/' | b'|' => {
                lengths.end_word();
                spaces = 0;
            }
            b',' | b';' | b':' | b'-' if digits => {
                separator = true;
                spaces = 0;
            }
            _ => return None,
        }
    }
    lengths.end_word();

    if lengths.total < 2 * MIN_LETTERS || seen.count_ones() < MIN_SYMBOLS {
        return None;
    }
    let coordinates = if !digits {
        LETTER_SETS
            .into_iter()
            .find(|set| seen & !symbol_bits(set) == 0)?
    } else if seen & symbol_bit(b'6') != 0 {
        DIGITS6
    } else {
        DIGITS5
    };
    let word_breaks = if !lengths.not_all_pairs {
        // `23 15 31`, `23,15,31`
        WordBreaks::Gaps
    } else if separator {
        // `2,3 1,5`: tap code
        return None;
    } else if !lengths.odd_token && !lengths.fixed_groups() {
        // `2315313134 5234423114`
        WordBreaks::Tokens
    } else if !lengths.odd_word {
        // `2 3 1 5`, `231531`, `23153 13134 52344 23114`
        WordBreaks::Gaps
    } else {
        return None;
    };
    Some(Scan {
        body,
        coordinates,
        word_breaks,
    })
}

/// The bit for a coordinate in [`scan`]'s set of coordinates seen: a digit `1`–`6` or an
/// upper-case letter `A`–`X`. Digits and letters never share a set.
fn symbol_bit(symbol: u8) -> u32 {
    if symbol.is_ascii_digit() {
        1 << (symbol - b'0')
    } else {
        1 << (symbol - b'A')
    }
}

/// The bits for every coordinate of `set`.
fn symbol_bits(set: &[u8]) -> u32 {
    set.iter()
        .fold(0, |bits, &symbol| bits | symbol_bit(symbol))
}

/// The lengths [`scan`] has seen, counted in coordinates. A token is a run of coordinates
/// between whitespace, `/`, `|` or `,;:-`, and a word is a run of tokens between gaps.
#[derive(Debug, Default)]
struct Lengths {
    /// Coordinates in the current token.
    token: usize,
    /// Coordinates in the current word.
    word: usize,
    /// Coordinates in the whole input.
    total: usize,
    /// Tokens ended so far.
    tokens: usize,
    /// The length of the first token.
    first_token: usize,
    /// The length of the latest token.
    last_token: usize,
    /// Some token before the latest one isn't as long as the first.
    ragged: bool,
    /// Some token isn't exactly one pair.
    not_all_pairs: bool,
    /// Some token has an odd length.
    odd_token: bool,
    /// Some word has an odd length.
    odd_word: bool,
}

impl Lengths {
    /// Counts one coordinate.
    fn coordinate(&mut self) {
        self.token += 1;
        self.word += 1;
        self.total += 1;
    }

    /// Ends the current token, if it has started.
    fn end_token(&mut self) {
        if self.token == 0 {
            return;
        }
        if self.tokens == 0 {
            self.first_token = self.token;
        } else if self.last_token != self.first_token {
            self.ragged = true;
        }
        self.tokens += 1;
        self.last_token = self.token;
        self.not_all_pairs |= self.token != 2;
        self.odd_token |= self.token % 2 == 1;
        self.token = 0;
    }

    /// Ends the current token and word.
    fn end_word(&mut self) {
        self.end_token();
        self.odd_word |= self.word % 2 == 1;
        self.word = 0;
    }

    /// Whether the tokens are groups of one length rather than words: at least three of
    /// them, all as long as the first except perhaps a shorter last one.
    fn fixed_groups(&self) -> bool {
        self.tokens >= 3 && !self.ragged && self.last_token <= self.first_token
    }
}

/// One reading of the coordinates.
#[derive(Debug, PartialEq, Eq)]
struct Reading {
    /// The decoded text: upper case, with one space between words.
    text: String,
    /// The square and the coordinate order, such as `5x5 I=J, row-column`.
    key: String,
    /// Whether the coordinates were read column first.
    column_row: bool,
}

/// Reads the coordinates of `scan` every way that applies, in the order they are checked:
///
/// 1. row-column on the standard square, or on the 6×6 one,
/// 2. row-column on the tap code square, if a pair is row 2, column 5 (5×5 only),
/// 3. column-row on the same square as 1, if some pair isn't its own mirror image.
///
/// [`scan`] has made sure every word has an even number of coordinates.
fn readings(scan: &Scan) -> Vec<Reading> {
    let size = scan.coordinates.len();
    let (square, square_name): (&[u8], &str) = if size == 6 {
        (SQUARE6, "6x6 A-Z 0-9")
    } else {
        (STANDARD, "5x5 I=J")
    };
    let capacity = scan.body.len() / 2 + 1;
    let mut row_column = String::with_capacity(capacity);
    let mut column_row = String::with_capacity(capacity);
    // The tap code reading, for the 5×5 square only, and whether it differs from the
    // standard one: the squares only differ at row 2, column 5.
    let mut tap = (size == 5).then(|| String::with_capacity(capacity));
    let mut tap_differs = false;
    // The row of a pair whose column hasn't been read yet.
    let mut row: Option<usize> = None;
    // Whether a word ended since the last letter.
    let mut word_ended = false;
    // Spaces and tabs since the last other byte.
    let mut spaces = 0;
    for &byte in scan.body {
        let upper = byte.to_ascii_uppercase();
        if let Some(coordinate) = scan.coordinates.iter().position(|&c| c == upper) {
            spaces = 0;
            let Some(r) = row.take() else {
                row = Some(coordinate);
                continue;
            };
            if word_ended && !row_column.is_empty() {
                row_column.push(' ');
                column_row.push(' ');
                if let Some(tap) = tap.as_mut() {
                    tap.push(' ');
                }
            }
            word_ended = false;
            let cell = r * size + coordinate;
            row_column.push(char::from(square[cell]));
            column_row.push(char::from(square[coordinate * size + r]));
            if let Some(tap) = tap.as_mut() {
                tap.push(char::from(TAP[cell]));
                tap_differs |= TAP[cell] != STANDARD[cell];
            }
            continue;
        }
        word_ended |= match byte {
            b' ' | b'\t' => {
                spaces += 1;
                scan.word_breaks == WordBreaks::Tokens || spaces >= 2
            }
            b',' | b';' | b':' | b'-' => {
                spaces = 0;
                false
            }
            // A line break, `/` or `|`
            _ => {
                spaces = 0;
                true
            }
        };
    }

    // Letter coordinates are part of the key: the same pairs mean different letters with
    // ABCDE and with ADFGX.
    let coordinates = if scan.coordinates[0] == b'1' {
        String::new()
    } else {
        format!(", letters {}", String::from_utf8_lossy(scan.coordinates))
    };
    let tap = tap.filter(|_| tap_differs);
    let mirrored = column_row != row_column;

    let mut readings = vec![Reading {
        text: row_column,
        key: format!("{square_name}, row-column{coordinates}"),
        column_row: false,
    }];
    if let Some(tap) = tap {
        readings.push(Reading {
            text: tap,
            key: format!("5x5 C=K (tap code), row-column{coordinates}"),
            column_row: false,
        });
    }
    if mirrored {
        readings.push(Reading {
            text: column_row,
            key: format!("{square_name}, column-row{coordinates}"),
            column_row: true,
        });
    }
    readings
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::athena::Athena;
    use crate::checkers::checker_type::{Check, Checker};

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    /// Runs the decoder with the Athena checker
    fn crack(text: &str) -> CrackResult {
        Decoder::<PolybiusDecoder>::new().crack(text, &get_athena_checker())
    }

    /// Asserts the decoder identifies `text` as `plaintext`, read with `key`
    fn assert_cracks(text: &str, plaintext: &str, key: &str) {
        let result = crack(text);
        assert!(result.success, "{text:?} was not cracked: {result:?}");
        assert_eq!(result.unencrypted_text, Some(vec![plaintext.to_string()]));
        assert_eq!(result.key.as_deref(), Some(key), "{text:?}");
        assert!(!result.checker_name.is_empty());
    }

    /// The readings of `text`, in the order they are checked
    fn reading_texts(text: &str) -> Vec<String> {
        let scan = scan(text).unwrap_or_else(|| panic!("{text:?} failed the pre-checks"));
        readings(&scan).into_iter().map(|r| r.text).collect()
    }

    /// The first reading of `text`, which `crack` returns first whether or not the checker
    /// identifies it
    fn first_reading(text: &str) -> String {
        let result = crack(text);
        let candidates = result
            .unencrypted_text
            .unwrap_or_else(|| panic!("{text:?} returned no candidates"));
        candidates[0].clone()
    }

    // Unless noted, the vectors below are pycipher 0.5.2's
    // `PolybiusSquare("ABCDEFGHIKLMNOPQRSTUVWXYZ", 5, "12345")` (`"ABCDE"` and `"ADFGX"` for
    // letter coordinates), applied word by word, and decode back to the same text with its
    // `decipher`. The 6×6 ones use `PolybiusSquare(SQUARE6, 6, "123456")` and
    // `"ADFGVX"`; that square has no external reference, it is the usual A–Z then 0–9 grid.

    #[test]
    fn issue_example_runs_the_letters_together() {
        // The example in issue #963. Without word breaks the checker doesn't take
        // HELLOWORLD for English, so the readings are returned for the search.
        assert_eq!(first_reading("23 15 31 31 34 52 34 42 31 14"), "HELLOWORLD");
        assert_eq!(
            reading_texts("23 15 31 31 34 52 34 42 31 14"),
            ["HELLOWORLD", "MVCCSKSICQ"]
        );
    }

    #[test]
    fn issue_example_with_letter_coordinates() {
        // pycipher: PolybiusSquare(..., 5, "ABCDE").decipher("BCAECACACDEBCDDBCAAD")
        assert_eq!(first_reading("BC AE CA CA CD EB CD DB CA AD"), "HELLOWORLD");
        assert_eq!(first_reading("BCAECACACDEBCDDBCAAD"), "HELLOWORLD");
    }

    #[test]
    fn unspaced_and_separated_digits() {
        // pycipher's encipher("HELLOWORLD") output, as is
        assert_eq!(first_reading("23153131345234423114"), "HELLOWORLD");
        // dCode's comma form, and other separators
        assert_eq!(first_reading("23,15,31,31,34,52,34,42,31,14"), "HELLOWORLD");
        assert_eq!(first_reading("23-15-31-31-34-52-34-42-31-14"), "HELLOWORLD");
        assert_eq!(first_reading("23;15;31;31;34;52;34;42;31;14"), "HELLOWORLD");
        assert_eq!(first_reading("23:15:31:31:34:52:34:42:31:14"), "HELLOWORLD");
        assert_eq!(
            first_reading("23, 15, 31, 31, 34, 52, 34, 42, 31, 14"),
            "HELLOWORLD"
        );
    }

    #[test]
    fn dcode_example() {
        // The default input of dCode's decoder
        assert_eq!(
            first_reading("14 13 34 14 15 35 34 31 54 12 24 45 43"),
            "DCODEPOLYBIUS"
        );
    }

    #[test]
    fn decodes_words() {
        assert_cracks(
            "23 15 31 31 34  52 34 42 31 14",
            "HELLO WORLD",
            "5x5 I=J, row-column",
        );
        assert_cracks(
            "32 15 15 44  32 15  11 44  32 24 14 33 24 22 23 44",
            "MEET ME AT MIDNIGHT",
            "5x5 I=J, row-column",
        );
        assert_cracks(
            "52 15  11 42 15  14 24 43 13 34 51 15 42 15 14  21 31 15 15  11 44  34 33 13 15",
            "WE ARE DISCOVERED FLEE AT ONCE",
            "5x5 I=J, row-column",
        );
    }

    #[test]
    fn decodes_pangram_with_j_as_i() {
        // J is written as I, and the 25 of QUICK makes a tap code reading too, which comes
        // second
        let text = "44 23 15  41 45 24 13 25  12 42 34 52 33  21 34 53  24 45 32 35 43  34 51 15 42  44 23 15  31 11 55 54  14 34 22";
        assert_cracks(
            text,
            "THE QUICK BROWN FOX IUMPS OVER THE LAZY DOG",
            "5x5 I=J, row-column",
        );
        assert_eq!(
            reading_texts(text)[1],
            "THE QUICJ BROWN FOX IUMPS OVER THE LAZY DOG"
        );
    }

    #[test]
    fn decodes_single_digits() {
        assert_cracks(
            "2 3 1 5 3 1 3 1 3 4  5 2 3 4 4 2 3 1 1 4",
            "HELLO WORLD",
            "5x5 I=J, row-column",
        );
    }

    #[test]
    fn word_breaks() {
        for text in [
            "23 15 31 31 34 / 52 34 42 31 14",
            "23 15 31 31 34/52 34 42 31 14",
            "23 15 31 31 34 | 52 34 42 31 14",
            "23 15 31 31 34\n52 34 42 31 14",
            "23 15 31 31 34\r\n52 34 42 31 14",
            "23 15 31 31 34\t\t52 34 42 31 14",
            "23 15 31 31 34      52 34 42 31 14",
            "  23 15 31 31 34  52 34 42 31 14\n",
            "2315313134  5234423114",
        ] {
            assert_eq!(reading_texts(text)[0], "HELLO WORLD", "{text:?}");
        }
    }

    #[test]
    fn each_run_of_pairs_is_a_word() {
        // Each word's coordinates written together, with a space between words, as by an
        // encoder that keeps the spaces of the plaintext
        assert_cracks(
            "2315313134 5234423114",
            "HELLO WORLD",
            "5x5 I=J, row-column",
        );
        assert_eq!(reading_texts("24 1132 23154215")[0], "I AM HERE");
        assert_eq!(reading_texts("DFAXFAFAFG XDFGGDFAAG")[0], "HELLO WORLD");
    }

    #[test]
    fn groups_of_one_length_are_not_words() {
        // Groups of four and of five coordinates, the last one shorter
        assert_eq!(reading_texts("2315 3131 3452 3442 3114")[0], "HELLOWORLD");
        assert_eq!(reading_texts("23153 13134 52344 23114")[0], "HELLOWORLD");
        assert_eq!(reading_texts("231531 313452 344231 14")[0], "HELLOWORLD");
        // A run with an odd length: the words are read whole
        assert_eq!(reading_texts("24 1132 2315421 5")[0], "IAMHERE");
    }

    #[test]
    fn decodes_adfgx_letters() {
        assert_cracks(
            "DF AX FA FA FG  XD FG GD FA AG",
            "HELLO WORLD",
            "5x5 I=J, row-column, letters ADFGX",
        );
        assert_cracks(
            "df ax fa fa fg  xd fg gd fa ag",
            "HELLO WORLD",
            "5x5 I=J, row-column, letters ADFGX",
        );
    }

    #[test]
    fn decodes_abcde_letters_with_words() {
        assert_cracks(
            "BC AE CA CA CD  EB CD DB CA AD",
            "HELLO WORLD",
            "5x5 I=J, row-column, letters ABCDE",
        );
    }

    #[test]
    fn tap_code_square_is_second() {
        // K is 25 in the standard square and J in the tap code square. ATTACK AT DAWN is
        // identified first.
        let text = "11 44 44 11 13 25  11 44  14 11 52 33";
        assert_cracks(text, "ATTACK AT DAWN", "5x5 I=J, row-column");
        assert_eq!(
            reading_texts(text),
            ["ATTACK AT DAWN", "ATTACJ AT DAWN", "ATTALW AT QAKN"]
        );
    }

    #[test]
    fn both_row_column_readings_are_returned() {
        // JUMP OVER in the tap code square. The checker accepts none of the readings, so
        // both row-column ones go to the search; the column-row one is checked but not
        // returned.
        let text = "25 45 32 35  34 51 15 42";
        assert_eq!(reading_texts(text), ["KUMP OVER", "JUMP OVER", "WYHX SEVI"]);
        let result = crack(text);
        assert!(!result.success, "{result:?}");
        assert_eq!(
            result.unencrypted_text,
            Some(vec!["KUMP OVER".to_string(), "JUMP OVER".to_string()])
        );
        assert_eq!(result.key, None);
    }

    #[test]
    fn decodes_column_row() {
        // HELLO WORLD with each pair written column first. Row-column reads MVCCS KSICQ.
        let text = "32 51 13 13 43  25 43 24 13 41";
        assert_cracks(text, "HELLO WORLD", "5x5 I=J, column-row");
        assert_eq!(
            reading_texts(text),
            ["MVCCS KSICQ", "MVCCS JSICQ", "HELLO WORLD"]
        );
    }

    #[test]
    fn decodes_6x6_square() {
        assert_cracks(
            "22 15 26 26 33  45 33 36 26 14  55 53 55 61",
            "HELLO WORLD 2024",
            "6x6 A-Z 0-9, row-column",
        );
        assert_cracks(
            "31 15 15 42  31 15  11 42  54 65 53 53",
            "MEET ME AT 1800",
            "6x6 A-Z 0-9, row-column",
        );
    }

    #[test]
    fn decodes_adfgvx_letters() {
        assert_cracks(
            "DD AV DX DX FF  GV FF FX DX AG  VV VF VV XA",
            "HELLO WORLD 2024",
            "6x6 A-Z 0-9, row-column, letters ADFGVX",
        );
    }

    #[test]
    fn symmetric_pairs_have_one_reading() {
        // AGN: every pair is its own mirror image and none is 25
        assert_eq!(reading_texts("11 22 33"), ["AGN"]);
    }

    #[test]
    fn tap_code_square_differs_only_at_25() {
        let differences: Vec<usize> = (0..25).filter(|&i| STANDARD[i] != TAP[i]).collect();
        // Row 2, column 5: K in the standard square, J in the tap code one
        assert_eq!(differences, [9]);
        assert_eq!((STANDARD[9], TAP[9]), (b'K', b'J'));
    }

    #[test]
    fn letter_set_is_the_first_that_fits() {
        let pick = |text: &str| scan(text).map(|scan| scan.coordinates);
        assert_eq!(pick("AB CD EA"), Some(&b"ABCDE"[..]));
        // These letters fit ADFGVX too: the 5×5 set comes first
        assert_eq!(pick("AF GX DA"), Some(&b"ADFGX"[..]));
        assert_eq!(pick("AV GX DA"), Some(&b"ADFGVX"[..]));
        // B and F: no set has both
        assert_eq!(pick("AB FA AA"), None);
        assert_eq!(pick("23 15 31"), Some(&b"12345"[..]));
        assert_eq!(pick("23 15 36"), Some(&b"123456"[..]));
    }

    #[test]
    fn needs_three_distinct_coordinates() {
        // Two symbols: Bacon's cipher (HELLO, issue #996) and the like
        for text in [
            "AABBB AABAA ABABA ABABA ABBAB",
            "AABBBAABAAABABAABABAABBAB",
            "AD DA AA",
            "12 21 12 21",
            "112211",
        ] {
            assert!(scan(text).is_none(), "{text:?} passed the pre-checks");
        }
        assert!(scan("12 21 13").is_some());
    }

    #[test]
    fn junk_letter_readings_are_candidates() {
        // English made only of coordinate letters gets through the pre-checks; the
        // checker rejects what it decodes to
        let result = crack("CAB BAD");
        assert!(!result.success);
        assert_eq!(reading_texts("CAB BAD")[0], "LGD");
    }

    #[test]
    fn rejects_invalid_input() {
        for text in [
            "",
            " ",
            " \t\n ",
            "😀",
            "hello world",
            "Hello World",
            "The quick brown fox jumps over the lazy dog",
            // The bench miss input
            "T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV",
            // Tap code comma pairs
            "2,3 1,5 3,1 3,1 3,4",
            "2,3 1,5 3,1 3,1 3,4  5,2 3,4 4,2 3,1 1,4",
            // A1Z26, decimal, octal, binary
            "8 5 12 12 15",
            "104 101 108 108 111",
            "150 145 154 154 157",
            "01101000 01101001",
            "13-5-5-20 13-5",
            // An odd number of coordinates
            "23 15 3",
            "23 15 31 31 34 52 34 42 31 1",
            "2315313",
            "23 15 31 31 3  52 34 42 31 14",
            // 0, 7, 8 and 9 are never coordinates
            "60 15 31",
            "23 15 31 37",
            // A letter outside every set
            "BC AE CA CA CZ",
            "DEAD BEEF",
            // Digits and letters mixed
            "23 15 3A",
            "BC AE C1",
            // Fewer than 3 letters
            "12 34",
            "1234",
            "BC AE",
            // Separators only work with digits
            "BC,AE,CA",
            // Base64 and hex
            "aGVsbG8gd29ybGQ=",
            "68656c6c6f20776f726c64",
            "4d656574206d65",
        ] {
            assert!(scan(text).is_none(), "{text:?} passed the pre-checks");
            let result = crack(text);
            assert!(!result.success, "{text:?}: {result:?}");
            assert!(result.unencrypted_text.is_none(), "{text:?}: {result:?}");
        }
    }

    #[test]
    fn pre_check_stops_at_the_first_byte() {
        // Neither a digit 1-6 nor a coordinate letter
        for text in [
            "T00 l3=",
            "hello",
            "0110",
            "7",
            "Zm9v",
            "{",
            "-23 15 31",
            "😀",
        ] {
            let first = text.trim().as_bytes()[0];
            assert!(
                !matches!(first, b'1'..=b'6')
                    && !COORDINATE_LETTERS.contains(&first.to_ascii_uppercase()),
                "{text:?}"
            );
            assert!(scan(text).is_none(), "{text:?}");
        }
    }

    #[test]
    fn lengths_tell_groups_from_words() {
        let lengths = |tokens: &[usize]| {
            let mut lengths = Lengths::default();
            for &token in tokens {
                for _ in 0..token {
                    lengths.coordinate();
                }
                lengths.end_token();
            }
            lengths.end_word();
            lengths
        };
        assert!(lengths(&[4, 4, 4, 2]).fixed_groups());
        assert!(lengths(&[5, 5, 5]).fixed_groups());
        assert!(!lengths(&[10, 10]).fixed_groups());
        assert!(!lengths(&[2, 4, 8]).fixed_groups());
        assert!(!lengths(&[4, 4, 6]).fixed_groups());
        assert!(!lengths(&[4, 2, 4]).fixed_groups());
        assert!(!lengths(&[2, 2, 2]).not_all_pairs);
        assert!(lengths(&[2, 1, 2]).odd_token);
    }

    #[test]
    fn is_registered() {
        let decoders = crate::filtration_system::get_decoder_by_name("Polybius Square");
        assert_eq!(decoders.components.len(), 1);
        assert!(crate::decoders::DECODER_MAP.contains_key("Polybius Square"));
    }
}
