//! Decode Punycode (RFC 3492) and the IDNA `xn--` labels of internationalised domain names.
//!
//! Punycode writes Unicode text in ASCII. The ASCII characters are copied as they are, then
//! come a `-` and the other characters, written as base 36 numbers (`a` to `z` are 0 to 25,
//! `0` to `9` are 26 to 35, in either case) that say which character to insert where.
//! `bücher` becomes `bcher-kva`. Domain names apply it label by label and mark each encoded
//! label with the prefix `xn--`, so `bücher.example` is `xn--bcher-kva.example`.
//!
//! The decoder reads two forms:
//!
//! * **IDNA labels.** Every `xn--` label in the text is decoded and everything around it is
//!   kept, so domains, URLs, email addresses and sentences with `xn--` labels in them all
//!   decode: `https://xn--bcher-kva.example.com/` gives `https://bücher.example.com/`.
//! * **Raw Punycode.** Text without an `xn--` label is read as one Punycode string, which is
//!   what CyberChef's "To Punycode" writes with "Internationalised domain name" off:
//!   `Schne Gre aus Mnchen-iwb41ctei` gives `Schöne Grüße aus München`.
//!
//! Text without a `-` is never decoded: Punycode of text that has no non-ASCII character
//! is that text plus a `-`, so every word would otherwise qualify. Most text with a `-` in
//! it is valid raw Punycode too, though (`hello-world` decodes to Thai), so a raw decoding
//! is only kept if it looks like a Latin-script language with accents: see
//! [`decode_raw_punycode`].
//!
//! References:
//! * RFC 3492, Punycode: <https://datatracker.ietf.org/doc/html/rfc3492>
//! * RFC 5891 section 4.4, Punycode in IDNA labels:
//!   <https://datatracker.ietf.org/doc/html/rfc5891#section-4.4>
//! * CyberChef "From Punycode":
//!   <https://gchq.github.io/CyberChef/#recipe=From_Punycode(true)>

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use idna::punycode;
use log::{debug, info, trace};

/// The prefix of an IDNA label that holds Punycode, the "ACE prefix" (RFC 5890 section
/// 2.3.2.5). Matched in either case.
const ACE_PREFIX: &[u8] = b"xn--";

/// The most base 36 digits after the last `-` that are decoded.
///
/// Every digit can insert a character, and the `idna` crate shifts all earlier insertions
/// for each new one, so decoding takes time quadratic in the number of insertions: about
/// 0.25 ms for 1,024 and 165 ms for 16,384 in a release build. Real text needs far fewer
/// digits (a 3,400 character German text with 176 accented letters has 303), and DNS
/// labels are at most 63 bytes, so this only stops crafted input such as `a-` followed by
/// thousands of `a`s.
const MAX_DIGITS: usize = 1024;

/// The Punycode decoder, call:
/// `let punycode_decoder = Decoder::<PunycodeDecoder>::new()` to create a new instance
/// And then call:
/// `result = punycode_decoder.crack(input)` to decode Punycode
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::punycode_decoder::PunycodeDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decoder = Decoder::<PunycodeDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decoder.crack("xn--bcher-kva", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "bücher");
/// ```
pub struct PunycodeDecoder;

impl Crack for Decoder<PunycodeDecoder> {
    fn new() -> Decoder<PunycodeDecoder> {
        Decoder {
            name: "Punycode",
            description: "Punycode (RFC 3492) and IDNA `xn--` labels: Unicode text written in ASCII, used for internationalised domain names",
            link: "https://datatracker.ietf.org/doc/html/rfc3492",
            tags: vec!["punycode", "idna", "unicode", "web", "decoder"],
            popularity: 0.3,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes the `xn--` labels in `text` or, if it has none, all of `text` as raw
    /// Punycode (see the module docs), and runs the checker on the result.
    ///
    /// Fails on text that is not ASCII or has no `-`, on an `xn--` label that is not valid
    /// Punycode of a non-ASCII label, on raw Punycode that doesn't decode to accented
    /// Latin-script text, and on results with control characters other than tab,
    /// carriage return and line feed.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Punycode with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_punycode(text) else {
            trace!("Failed to decode Punycode: not Punycode, or the result is not text");
            return results;
        };

        if has_unexpected_control_character(&decoded_text) {
            debug!(
                "Failed to decode Punycode: {:?} has control characters",
                decoded_text
            );
            return results;
        }

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Punycode because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);

        results.update_checker(&checker_result);

        results
    }
    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Decodes the `xn--` labels in `text` or, if it has none, all of it as raw Punycode.
///
/// Trailing whitespace is dropped: Punycode ends in digits, but text that went through
/// another encoding often ends in a line break. Leading whitespace is kept, because it
/// belongs to the ASCII characters: `À bientôt` is ` bientt-` followed by digits.
fn decode_punycode(text: &str) -> Option<String> {
    let text = text.trim_end();
    // Rejects almost every text the search tries, with one fast pass for each check
    if !text.contains('-') || !text.is_ascii() {
        return None;
    }
    match decode_idna_labels(text) {
        Labels::Decoded(decoded) => Some(decoded),
        Labels::Invalid => None,
        Labels::NotFound => decode_raw_punycode(text),
    }
}

/// What [`decode_idna_labels`] found
enum Labels {
    /// No `xn--` label, so the text may be raw Punycode
    NotFound,
    /// An `xn--` label that is not Punycode of a label with a non-ASCII character
    Invalid,
    /// The text with every `xn--` label decoded
    Decoded(String),
}

/// Replaces every `xn--` label in `text` with its decoding and copies the rest unchanged.
///
/// A label is a maximal run of ASCII letters, digits and `-`, so the dots of a domain, the
/// `/` and `:` of a URL, the `@` of an email address and the spaces of a sentence all end
/// one. Runs that start with `xn--` (or `XN--`, in any mix of case) and have more after it
/// are decoded; all other runs are kept as they are. `text` must be ASCII.
fn decode_idna_labels(text: &str) -> Labels {
    let bytes = text.as_bytes();
    let mut decoded = String::new();
    let mut found = false;
    // Everything before this byte offset has been written to `decoded`
    let mut copied_up_to = 0;
    let mut i = 0;

    while i < bytes.len() {
        if !is_label_byte(bytes[i]) {
            i += 1;
            continue;
        }
        let start = i;
        while i < bytes.len() && is_label_byte(bytes[i]) {
            i += 1;
        }
        let label = &bytes[start..i];
        if label.len() <= ACE_PREFIX.len()
            || !label[..ACE_PREFIX.len()].eq_ignore_ascii_case(ACE_PREFIX)
        {
            continue;
        }

        // `text` is ASCII, so every byte offset is a char boundary
        let Some(unicode) = decode_bounded(&text[start + ACE_PREFIX.len()..i]) else {
            return Labels::Invalid;
        };
        // `xn--abc-` decodes to `abc`, which is not an internationalised label
        if unicode.is_ascii() {
            return Labels::Invalid;
        }
        decoded.push_str(&text[copied_up_to..start]);
        decoded.push_str(&unicode);
        copied_up_to = i;
        found = true;
    }

    if !found {
        return Labels::NotFound;
    }
    decoded.push_str(&text[copied_up_to..]);
    Labels::Decoded(decoded)
}

/// Whether `byte` can be part of a domain label: an ASCII letter, an ASCII digit or `-`
fn is_label_byte(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || byte == b'-'
}

/// Decodes all of `text` (ASCII, with a `-`) as one raw Punycode string, if the result
/// looks like text in a Latin-script language with accents.
///
/// Almost every hyphenated word, date, UUID and URL-safe Base64 string is valid Punycode,
/// so the result has to pass all of these:
///
/// * the digits after the last `-` are letters and digits only (rejects Morse code,
///   `self-driving car` and `abc-`);
/// * it has at least one non-ASCII character, and every one of them is a letter from
///   Latin-1 Supplement or Latin Extended-A (`hello-world` decodes to Thai);
/// * it has no more non-ASCII characters than ASCII letters;
/// * at most 2 non-ASCII characters for every 3 digits. A real encoder spends about 2 to 6
///   digits on each inserted character, while a hyphenated English word read as Punycode
///   inserts many characters from few digits.
///
/// Vietnamese, Romanian with comma-below letters (`ș`, `ț`) and non-Latin scripts fail
/// these checks; they still decode as `xn--` labels.
fn decode_raw_punycode(text: &str) -> Option<String> {
    let (_, digits) = text.rsplit_once('-')?;
    if digits.is_empty() || !digits.bytes().all(|byte| byte.is_ascii_alphanumeric()) {
        return None;
    }
    let decoded = decode_bounded(text)?;

    // The text before the last `-` is ASCII, so every non-ASCII character was inserted
    let mut inserted = 0;
    let mut letters = 0;
    for c in decoded.chars() {
        if c.is_ascii_alphabetic() {
            letters += 1;
        } else if !c.is_ascii() {
            if !is_latin_letter(c) {
                return None;
            }
            inserted += 1;
        }
    }
    ((1..=letters).contains(&inserted) && 3 * inserted <= 2 * digits.len()).then_some(decoded)
}

/// Whether `c` is a letter from Latin-1 Supplement or Latin Extended-A (U+00C0 to U+017F
/// without `×` and `÷`): the accented letters of Western and Central European languages
/// and Turkish.
fn is_latin_letter(c: char) -> bool {
    matches!(c, '\u{C0}'..='\u{17F}') && !matches!(c, '×' | '÷')
}

/// [`punycode::decode_to_string`], or `None` if there are more than [`MAX_DIGITS`] digits
/// after the last `-`.
///
/// The crate keeps the case of the ASCII characters, reads digits in either case and
/// returns `None` on a character that isn't a digit, on overflow and on code points that
/// aren't characters.
fn decode_bounded(encoded: &str) -> Option<String> {
    // The crate reads everything after the last `-` as digits, or all of the text if the
    // only `-` is the first character
    let digits = match encoded.rfind('-') {
        Some(position) if position > 0 => encoded.len() - position - 1,
        _ => encoded.len(),
    };
    if digits > MAX_DIGITS {
        return None;
    }
    punycode::decode_to_string(encoded)
}

/// Whether `text` has a control character other than tab, carriage return or line feed.
/// The first code points Punycode can insert, U+0080 to U+009F, are control characters.
fn has_unexpected_control_character(text: &str) -> bool {
    text.chars()
        .any(|c| c.is_control() && !matches!(c, '\t' | '\r' | '\n'))
}

#[cfg(test)]
mod tests {
    use super::{decode_bounded, decode_punycode, PunycodeDecoder, MAX_DIGITS};
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::{
            crack_results::CrackResult,
            interface::{Crack, Decoder},
            DECODER_MAP,
        },
        filtration_system::get_decoder_by_name,
    };
    use idna::punycode;

    // The comment on each test says which references give the same output:
    // * Python 3.9 codecs: `text.encode().decode("punycode")` for raw Punycode and the same
    //   label by label for `xn--` labels. Encoding the plaintext with `.encode("idna")`
    //   (bare domains) or `.encode("punycode")` gives the ciphertext back.
    // * punycode.js 2.1.0 as bundled with Node 22, the library behind CyberChef's "From
    //   Punycode": `punycode.decode` (IDN off) for raw Punycode, `punycode.toUnicode` (IDN
    //   on) for `xn--` labels. `toUnicode` only decodes bare domains and the domain part of
    //   an email address, and only a lower-case `xn--`.

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    // helper for tests: the result of cracking `text` with the Athena checker
    fn crack(text: &str) -> CrackResult {
        Decoder::<PunycodeDecoder>::new().crack(text, &get_athena_checker())
    }

    // helper for tests: the decoded candidate, if the decoder returned one
    fn decode(text: &str) -> Option<String> {
        crack(text)
            .unencrypted_text
            .and_then(|candidates| candidates.into_iter().next())
    }

    // helper for tests: asserts that Athena takes the decoding of `text` for plaintext
    fn assert_cracked(text: &str, plaintext: &str) {
        let result = crack(text);
        assert_eq!(
            result.unencrypted_text.as_deref(),
            Some([plaintext.to_string()].as_slice()),
            "{text}"
        );
        assert!(result.success, "Athena should identify {plaintext:?}");
    }

    #[test]
    fn punycode_decodes_issue_example() {
        // Issue #938. Python and punycode.js agree. Athena does not identify "bücher".
        assert_eq!(decode("xn--bcher-kva").as_deref(), Some("bücher"));
    }

    #[test]
    fn punycode_decodes_multi_label_domains() {
        // Issue #938. Python and punycode.js agree.
        assert_eq!(decode("xn--mnchen-3ya.de").as_deref(), Some("münchen.de"));
        assert_eq!(decode("xn--i-7iq.ws").as_deref(), Some("i❤.ws"));
        assert_eq!(
            decode("xn--1lq90ic7fzpc.cn").as_deref(),
            Some("北京大学.cn")
        );
        // Python and punycode.js agree
        assert_eq!(decode("xn--wgv71a119e.jp").as_deref(), Some("日本語.jp"));
    }

    #[test]
    fn punycode_domains_are_found_by_athena() {
        // Python and punycode.js agree
        assert_cracked("xn--bcher-kva.example.com", "bücher.example.com");
        assert_cracked(
            "hello.xn--mller-kva.example.com",
            "hello.müller.example.com",
        );
        assert_cracked(
            "login.xn--bcher-kva.example.com",
            "login.bücher.example.com",
        );
        assert_cracked(
            "hello.xn--bcher-kva.example.com",
            "hello.bücher.example.com",
        );
    }

    #[test]
    fn punycode_decodes_labels_in_an_email_address() {
        // Python agrees. punycode.js keeps the part before the @ as it is.
        assert_cracked("xn--mller-kva@example.com", "müller@example.com");
    }

    #[test]
    fn punycode_decodes_labels_inside_urls_and_sentences() {
        // Python agrees label by label. punycode.js only decodes bare domains and returns
        // both unchanged.
        assert_eq!(
            decode("https://xn--bcher-kva.example.com/").as_deref(),
            Some("https://bücher.example.com/")
        );
        assert_eq!(
            decode("Visit xn--mnchen-3ya.de and xn--zrich-kva.ch today").as_deref(),
            Some("Visit münchen.de and zürich.ch today")
        );
    }

    #[test]
    fn punycode_reads_an_upper_case_prefix() {
        // Python agrees. punycode.js only reads a lower-case xn-- and returns it unchanged.
        // The ASCII characters keep their case and the inserted ü is lower case: mixed-case
        // annotation (RFC 3492 section 3.4) is implemented by neither reference.
        assert_eq!(decode("XN--BCHER-KVA").as_deref(), Some("BüCHER"));
        assert_eq!(decode("Xn--Bcher-Kva").as_deref(), Some("Bücher"));
    }

    #[test]
    fn punycode_decodes_raw_punycode() {
        // Issue #938. Python and punycode.js agree.
        assert_eq!(decode("bcher-kva").as_deref(), Some("bücher"));
        assert_eq!(decode("Bcher-Kva").as_deref(), Some("Bücher"));
        // A `-` that belongs to the text: only the last one ends the ASCII characters
        assert_eq!(
            decode("zrich-airport-wob").as_deref(),
            Some("zürich-airport")
        );
        assert_eq!(
            decode("Mnchen ist schn-mtb2g").as_deref(), // codespell:ignore ist
            Some("München ist schön")                   // codespell:ignore ist
        );
        assert_eq!(
            decode("Schne Gre aus Mnchen-iwb41ctei").as_deref(),
            Some("Schöne Grüße aus München")
        );
        // 6 insertions, and two spaces in a row where "à" was taken out
        assert_eq!(
            decode("Les lves tudient  l'cole franaise-0xc1xka9agm").as_deref(),
            Some("Les élèves étudient à l'école française")
        );
    }

    #[test]
    fn punycode_raw_sentences_are_found_by_athena() {
        // Python and punycode.js agree
        assert_cracked("The flag is caf-pnb", "The flag is café"); // codespell:ignore caf
        assert_cracked(
            "Bring the old map to the caf in Zrich-2jd06e", // codespell:ignore caf
            "Bring the old map to the café in Zürich",
        );
    }

    #[test]
    fn punycode_raw_mode_accepts_accented_european_text() {
        // German, French, Spanish, Portuguese, Polish, Czech, Turkish, Norwegian, Hungarian
        // and English with accents, encoded with the idna crate's encoder
        for plaintext in [
            "Falsches Üben von Xylophonmusik quält jeden größeren Zwerg",
            "Le cœur déçu mais l'âme plutôt naïve, Louÿs rêva de crapaüter en canoë au delà des îles",
            "El pingüino Wenceslao hizo kilómetros bajo exhaustiva lluvia y frío, añoraba a su querido cachorro.",
            "À noite, vovô Kowalsky vê o ímã cair no pé do pingüim queixoso e vovó põe açúcar no chá de tâmaras do jabuti feliz.",
            "Dzień dobry, jak się masz? Wszystko w porządku.",
            "Příliš žluťoučký kůň úpěl ďábelské ódy",
            "Pijamalı hasta yağız şoföre çabucak güvendi",
            "Blåbærsyltetøy er godt på brødskiva",
            "Árvíztűrő tükörfúrógép",
            "The naïve café owner in Zürich served a crème brûlée to the fiancée",
        ] {
            let ciphertext = punycode::encode_str(plaintext).unwrap();
            assert_eq!(
                decode(&ciphertext).as_deref(),
                Some(plaintext),
                "{ciphertext}"
            );
        }
    }

    #[test]
    fn punycode_raw_mode_rejects_other_scripts() {
        // Valid Punycode, but not Latin-1 Supplement or Latin Extended-A letters
        for plaintext in [
            "Привет, мир",
            "Tiếng Việt",
            "Înjurând pițigăiat",
            "日本語のテキスト",
            "café\u{85}",
        ] {
            let ciphertext = punycode::encode_str(plaintext).unwrap();
            assert_eq!(decode(&ciphertext), None, "{ciphertext}");
        }
        // The same text decodes as an IDNA label, which isn't limited to Latin letters
        let label = format!("xn--{}", punycode::encode_str("Привет").unwrap());
        assert_eq!(decode(&label).as_deref(), Some("Привет"));
    }

    #[test]
    fn punycode_drops_trailing_whitespace_only() {
        assert_eq!(decode("xn--bcher-kva\n").as_deref(), Some("bücher"));
        assert_eq!(decode("bcher-kva \r\n").as_deref(), Some("bücher"));
        // Leading whitespace belongs to the ASCII characters. Python agrees on both;
        // punycode.js agrees on the raw one and leaves the label with spaces unchanged.
        assert_eq!(decode("  xn--bcher-kva").as_deref(), Some("  bücher"));
        assert_eq!(decode(" bientt-woa88b").as_deref(), Some("À bientôt"));
    }

    #[test]
    fn punycode_fails_on_text_that_is_not_punycode() {
        for text in [
            "",
            "   ",
            "😀",
            "hello world",
            "hello my name is panicky mc panic face!",
            // Valid Punycode, but not text: Python decodes it to Thai
            "hello-world",
            "well-known",
            "e-mail",
            "self-driving car",
            "abc-",
            "-kva",
            "2024-01-15",
            "550e8400-e29b-41d4-a716-446655440000",
            // a1z26, dashed hex, URL-safe Base64 and Morse code
            "8-5-12-12-15",
            "4d-65-65-74",
            "SGVsbG8-d29ybGQ_",
            "--..-- -.-.",
            ".... . .-.. .-.. ---",
            // Valid Punycode of "üüü", but without a `-` every word would qualify
            "tdaaa",
            // Not ASCII
            "bücher-kva",
        ] {
            let result = crack(text);
            assert_eq!(result.unencrypted_text, None, "{text:?}");
            assert!(!result.success, "{text:?}");
        }
    }

    #[test]
    fn punycode_fails_on_invalid_idna_labels() {
        for text in [
            // Just the prefix: not a label, and not raw Punycode either
            "xn--",
            // Decodes to "abc", which has no non-ASCII character
            "xn--abc-",
            "xn--bcher-",
            // Overflow
            "xn--99999999999",
            // `-` can't start the digits
            "xn---kva",
            // One bad label fails the whole text
            "xn--bcher-kva.xn--99999999999.com",
            "xn--bcher-kva.xn--abc-.com",
        ] {
            let result = crack(text);
            assert_eq!(result.unencrypted_text, None, "{text:?}");
            assert!(!result.success, "{text:?}");
        }
    }

    #[test]
    fn punycode_fails_on_control_characters() {
        // "xn--ab-ba" is the label "a\u{80}b", and U+0080 to U+009F are control characters
        for text in [
            "xn--ab-ba",
            "xn--caf-xa31c",
            "xn--bcher-kva\u{0}",
            "b\u{7}cher-kva",
        ] {
            assert_eq!(decode(text), None, "{text:?}");
        }
        // Tabs and line breaks are kept
        assert_eq!(
            decode("xn--bcher-kva\txn--mller-kva\r\n").as_deref(),
            Some("bücher\tmüller")
        );
    }

    #[test]
    fn punycode_limits_the_number_of_digits() {
        // Every `a` inserts a U+0080, so this is valid Punycode of 2,000 insertions
        let many_insertions = format!("x-{}", "a".repeat(2000));
        assert_eq!(decode_bounded(&many_insertions), None);
        assert_eq!(decode(&many_insertions), None);
        assert_eq!(decode(&format!("xn--{many_insertions}")), None);

        // The limit counts the digits after the last `-`, not the ASCII characters
        let long_text = format!("{} caf-pnb", "word ".repeat(500));
        assert!(decode_bounded(&long_text).is_some());
        let at_limit = format!("x-{}", "a".repeat(MAX_DIGITS));
        assert!(decode_bounded(&at_limit).is_some());
        let over_limit = format!("x-{}", "a".repeat(MAX_DIGITS + 1));
        assert_eq!(decode_bounded(&over_limit), None);
        // With no `-`, or only a leading one, the crate reads every character as a digit
        assert_eq!(decode_bounded(&"a".repeat(MAX_DIGITS + 1)), None);
        assert_eq!(
            decode_bounded(&format!("-{}", "a".repeat(MAX_DIGITS))),
            None
        );
    }

    #[test]
    fn punycode_handles_arbitrary_ascii_without_panicking() {
        // Every string of up to 5 characters over an alphabet with the delimiter, digits
        // that overflow and characters that aren't digits, on its own and as a label.
        // Without the checker, which would make this slow.
        let alphabet = ['-', 'a', 'z', '0', '9', 'X', '.', ' '];
        let mut texts = vec![String::new()];
        for _ in 0..5 {
            texts = texts
                .iter()
                .flat_map(|text| alphabet.iter().map(move |c| format!("{text}{c}")))
                .collect();
            for text in &texts {
                let _ = decode_punycode(text);
                let _ = decode_punycode(&format!("xn--{text}"));
                let _ = decode_punycode(&format!("a.xn--{text}.b"));
            }
        }
    }

    #[test]
    fn punycode_handles_panic_if_empty_string() {
        // This tests if the decoder can handle an empty string
        // It should return None
        assert_eq!(decode(""), None);
    }

    #[test]
    fn punycode_handles_panic_if_emoji() {
        // This tests if the decoder can handle an emoji
        // It should return None
        assert_eq!(decode("😀"), None);
    }

    #[test]
    fn punycode_plain_english_is_not_decoded() {
        let result = crack("hello world");
        assert!(result.unencrypted_text.is_none());
        assert!(!result.success);
    }

    #[test]
    fn punycode_metadata() {
        let decoder = Decoder::<PunycodeDecoder>::new();
        assert_eq!(decoder.get_name(), "Punycode");
        assert_eq!(
            decoder.get_link(),
            "https://datatracker.ietf.org/doc/html/rfc3492"
        );
        assert!((decoder.get_popularity() - 0.3).abs() < f32::EPSILON);
        assert_eq!(
            decoder.get_tags(),
            &vec!["punycode", "idna", "unicode", "web", "decoder"]
        );
    }

    #[test]
    fn punycode_is_registered() {
        let decoders = get_decoder_by_name("Punycode");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Punycode");
        assert!(DECODER_MAP.contains_key("Punycode"));
    }

    #[test]
    fn punycode_crack_result_round_trips_through_json() {
        // The cache stores paths as JSON and finds the decoder again through DECODER_MAP
        let decoder = Decoder::<PunycodeDecoder>::new();
        let json = CrackResult::new(&decoder, "xn--bcher-kva".to_string())
            .get_json()
            .unwrap();
        let crack_result: CrackResult = serde_json::from_str(&json).unwrap();
        assert_eq!(crack_result.decoder, "Punycode");
        assert_eq!(crack_result.link, decoder.link);
    }
}
