//! Decode Quoted-Printable, the MIME content-transfer-encoding from
//! [RFC 2045 §6.7](https://datatracker.ietf.org/doc/html/rfc2045#section-6.7).
//! A byte is written as `=XX` (two hex digits) and an `=` at the end of a line is a
//! soft line break, which is removed. Every other character stands for itself.
//! Call quoted_printable_decoder.crack to use. It returns `Option<String>` and check with
//! `result.is_some()` to see if it returned okay.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::{bytes_to_string, check_string_success};

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The Quoted-Printable decoder, call:
/// `let quoted_printable_decoder = Decoder::<QuotedPrintableDecoder>::new()` to create a new instance
/// And then call:
/// `result = quoted_printable_decoder.crack(input)` to decode a Quoted-Printable string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::quoted_printable_decoder::QuotedPrintableDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_quoted_printable = Decoder::<QuotedPrintableDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_quoted_printable
///     .crack("Cr=C3=A8me br=C3=BBl=C3=A9e =3D burnt cream", &checker)
///     .unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "Crème brûlée = burnt cream");
/// ```
pub struct QuotedPrintableDecoder;

impl Crack for Decoder<QuotedPrintableDecoder> {
    fn new() -> Decoder<QuotedPrintableDecoder> {
        Decoder {
            name: "Quoted-Printable",
            description: "Quoted-Printable, or QP encoding, is a binary-to-text encoding system using printable ASCII characters (alphanumeric and the equals sign =) to transmit 8-bit data over a 7-bit data path or, generally, over a medium which is not 8-bit clean. It is defined as a MIME content transfer encoding for use in e-mail.",
            link: "https://en.wikipedia.org/wiki/Quoted-printable",
            tags: vec!["quoted_printable", "qp", "mime", "email", "decoder"],
            popularity: 0.4,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an `Option<String>` if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Quoted-Printable with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_bytes) = decode_quoted_printable(text) else {
            debug!(
                "Failed to decode Quoted-Printable because decode_quoted_printable returned None"
            );
            return results;
        };

        // Mail is often Latin-1 (`=E9` for "é"), so bytes that aren't UTF-8 are read as Latin-1.
        let decoded_text = bytes_to_string(decoded_bytes);
        if has_control_characters(&decoded_text) {
            debug!(
                "Failed to decode Quoted-Printable because the result has control characters: {:?}",
                decoded_text
            );
            return results;
        }

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Quoted-Printable because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);

        results.update_checker(&checker_result);

        results
    }
    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Decodes Quoted-Printable `text` into bytes, or returns `None` if it isn't Quoted-Printable.
///
/// Every `=` must start either an escape, `=XX` with two hex digits in either case, or a
/// soft line break: `=`, then optional spaces or tabs (RFC 2045 rule 3: transport can add
/// them), then CRLF, LF or the end of the input. Any other `=`, as in `E=mc2` or the `==`
/// of Base64 padding, fails. The text must also have an escape or a soft line break with
/// more text after it, so the trailing `=` of padded Base64 (`aGVsbG8=`) is not enough.
fn decode_quoted_printable(text: &str) -> Option<Vec<u8>> {
    // Fast path: almost nothing the search tries contains an `=`.
    if !text.contains('=') {
        return None;
    }

    let bytes = text.as_bytes();
    let mut decoded = Vec::with_capacity(bytes.len());
    let mut looks_encoded = false;
    let mut i = 0;
    while let Some(offset) = bytes[i..].iter().position(|&byte| byte == b'=') {
        let equals = i + offset;
        decoded.extend_from_slice(&bytes[i..equals]);

        if let (Some(high), Some(low)) = (
            hex_value(bytes.get(equals + 1)),
            hex_value(bytes.get(equals + 2)),
        ) {
            decoded.push((high << 4) | low);
            looks_encoded = true;
            i = equals + 3;
            continue;
        }

        let mut end = equals + 1;
        while matches!(bytes.get(end), Some(b' ' | b'\t')) {
            end += 1;
        }
        i = match bytes.get(end) {
            None => end,
            Some(b'\n') => end + 1,
            Some(b'\r') if bytes.get(end + 1) == Some(&b'\n') => end + 2,
            _ => return None,
        };
        // A soft line break that joins two lines; one at the very end proves nothing.
        looks_encoded = looks_encoded || bytes[i..].iter().any(|b| !b.is_ascii_whitespace());
    }
    decoded.extend_from_slice(&bytes[i..]);

    looks_encoded.then_some(decoded)
}

/// The value of an ASCII hex digit, upper or lower case.
fn hex_value(byte: Option<&u8>) -> Option<u8> {
    char::from(*byte?).to_digit(16).map(|digit| digit as u8)
}

/// Whether `text` has a control character other than tab, CR and LF. That includes the C1
/// range U+0080–U+009F, which the Latin-1 fallback produces from bytes that aren't text.
fn has_control_characters(text: &str) -> bool {
    text.chars()
        .any(|c| c.is_control() && !matches!(c, '\t' | '\r' | '\n'))
}

#[cfg(test)]
mod tests {
    use super::{decode_quoted_printable, QuotedPrintableDecoder};
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::{
            crack_results::CrackResult,
            interface::{Crack, Decoder},
            DecoderType, DECODER_MAP,
        },
        filtration_system::get_decoder_by_name,
    };

    // Test vectors: each input was decoded with Python 3 `quopri.decodestring`, quopri's
    // pure-Python decoder and Perl's `MIME::QuotedPrint::decode_qp`, which all agree unless
    // a test says otherwise. CyberChef's "From Quoted Printable" gives the same results
    // (see the implementation plan on https://github.com/bee-san/Ciphey/issues/937).

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    /// Runs the decoder and returns its decoded text, if any
    fn decode(text: &str) -> Option<String> {
        let quoted_printable_decoder = Decoder::<QuotedPrintableDecoder>::new();
        quoted_printable_decoder
            .crack(text, &get_athena_checker())
            .unencrypted_text
            .map(|texts| texts[0].clone())
    }

    #[test]
    fn quoted_printable_decodes_successfully() {
        // The example from the issue, made with Python's `quopri.encodestring`
        let quoted_printable_decoder = Decoder::<QuotedPrintableDecoder>::new();
        let result = quoted_printable_decoder.crack(
            "Caf=C3=A9 au lait =3D coffee with milk", // codespell:ignore caf
            &get_athena_checker(),
        );
        assert_eq!(
            result.unencrypted_text.unwrap()[0],
            "Café au lait = coffee with milk"
        );
        assert!(result.success, "Athena should accept the plaintext");
    }

    #[test]
    fn quoted_printable_decodes_every_byte_escaped() {
        assert_eq!(
            decode("=48=65=6C=6C=6F=20=57=6F=72=6C=64").unwrap(),
            "Hello World"
        );
    }

    #[test]
    fn quoted_printable_accepts_lowercase_hex() {
        // RFC 2045 §6.7 note 1: a robust decoder accepts lowercase hex
        assert_eq!(decode("Caf=c3=a9 au lait").unwrap(), "Café au lait"); // codespell:ignore caf
    }

    #[test]
    fn quoted_printable_falls_back_to_latin1() {
        // "é" is 0xE9 in Latin-1, which on its own isn't valid UTF-8
        assert_eq!(decode("Caf=E9 au lait").unwrap(), "Café au lait"); // codespell:ignore caf
    }

    #[test]
    fn quoted_printable_decodes_utf8_split_across_escapes() {
        assert_eq!(decode("=E2=98=95").unwrap(), "☕");
    }

    #[test]
    fn quoted_printable_removes_soft_line_breaks() {
        let expected = "The quick brown fox jumps over the lazy dog and keeps running far away.";
        assert_eq!(
            decode("The quick brown fox jumps over the lazy dog and keeps running far aw=\r\nay.")
                .unwrap(),
            expected
        );
        assert_eq!(
            decode("The quick brown fox jumps over the lazy dog and keeps running far aw=\nay.")
                .unwrap(),
            expected
        );
    }

    #[test]
    fn quoted_printable_removes_whitespace_before_soft_line_break() {
        // RFC 2045 §6.7 rule 3: trailing whitespace on a line was added in transport.
        // quopri's pure-Python decoder and Perl agree; `binascii.a2b_qp` keeps the `=`.
        assert_eq!(decode("aw= \t\r\nay =3D ok").unwrap(), "away = ok");
    }

    #[test]
    fn quoted_printable_removes_soft_line_break_at_end_of_input() {
        // Python's `quopri.decodestring` and CyberChef drop a final `=`
        assert_eq!(decode("Caf=C3=A9=").unwrap(), "Café"); // codespell:ignore caf
    }

    #[test]
    fn quoted_printable_rejoins_wrapped_base64() {
        // `quopri.encodestring` of unpadded Base64 longer than 76 characters: a soft line
        // break is its only sign of Quoted-Printable
        assert_eq!(
            decode("UXVvdGVkLVByaW50YWJsZSB3cmFwcyBsb25nIGxpbmVzIGF0IDc2IGNoYXJhY3RlcnMgd2l0aCB=\r\nzb2Z0IGxpbmUgYnJlYWtz")
                .unwrap(),
            "UXVvdGVkLVByaW50YWJsZSB3cmFwcyBsb25nIGxpbmVzIGF0IDc2IGNoYXJhY3RlcnMgd2l0aCBzb2Z0IGxpbmUgYnJlYWtz"
        );
    }

    #[test]
    fn quoted_printable_passes_non_ascii_literals_through() {
        assert_eq!(decode("Ünïcödé =3D ok").unwrap(), "Ünïcödé = ok");
    }

    #[test]
    fn quoted_printable_decodes_layered_input() {
        assert_eq!(decode("=3D41").unwrap(), "=41");
        assert_eq!(decode("=41").unwrap(), "A");
    }

    #[test]
    fn quoted_printable_returns_raw_bytes() {
        // "naïve" in Latin-1
        assert_eq!(decode_quoted_printable("na=EFve").unwrap(), b"na\xEFve");
        assert_eq!(decode_quoted_printable("=ff=00").unwrap(), b"\xFF\x00");
    }

    #[test]
    fn quoted_printable_rejects_base64_padding() {
        // CyberChef and quopri turn `aGVsbG8=` into `aGVsbG8`; that must not become a child
        // node for every padded Base64 string the search sees
        for text in [
            "aGVsbG8=",
            "aGVsbG8gd29ybGQ=",
            "SGVsbG8gV29ybGQ=",
            "TXIgUm9ib3QgaXMgZ3JlYXQ=",
            "aGVsbG8gdGhlcmUgZ2VuZXJhbA==",
            "NBSWY3DPEB3W64TMMQ======",
            "aGVsbG8=\n",
            "aGVsbG8=\r\n",
            "SGVsbG8+Pz8/Cg==",
        ] {
            assert!(decode(text).is_none(), "{text:?} should not decode");
        }
    }

    #[test]
    fn quoted_printable_rejects_invalid_escapes() {
        for text in [
            "E=mc2",
            "a=b",
            "=4",
            "=G1",
            "x == y",
            "key=value",
            "Hello= World",
            "a=\rb",
        ] {
            assert!(decode(text).is_none(), "{text:?} should not decode");
        }
    }

    #[test]
    fn quoted_printable_rejects_control_characters() {
        // `x=10` decodes to "x\x10"; 0x80 on its own becomes the C1 control U+0080
        for text in [
            "x=10",
            "=00abc",
            "=FF=00abc",
            "=80 abc",
            "=C2=80abc",
            "=1B[31m",
        ] {
            assert!(decode(text).is_none(), "{text:?} should not decode");
        }
    }

    #[test]
    fn quoted_printable_handles_panics() {
        // This tests if Quoted-Printable can handle panics
        // It should return None
        for text in [
            "hello my name is panicky mc panic face!",
            "=",
            "=\r\n",
            "= \n",
        ] {
            assert!(decode(text).is_none(), "{text:?} should not decode");
        }
    }

    #[test]
    fn quoted_printable_handles_panic_if_empty_string() {
        // This tests if Quoted-Printable can handle an empty string
        // It should return None
        assert!(decode("").is_none());
    }

    #[test]
    fn quoted_printable_handles_panic_if_emoji() {
        // This tests if Quoted-Printable can handle an emoji
        // It should return None
        assert!(decode("😀").is_none());
    }

    #[test]
    fn quoted_printable_is_registered() {
        let decoders = get_decoder_by_name("Quoted-Printable");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Quoted-Printable");

        // The cache stores the path as JSON and finds decoders by name in DECODER_MAP
        let decoder = DECODER_MAP
            .get("Quoted-Printable")
            .unwrap()
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "Quoted-Printable");
        let quoted_printable_decoder = Decoder::<QuotedPrintableDecoder>::new();
        let json = CrackResult::new(&quoted_printable_decoder, "=41".to_string())
            .get_json()
            .unwrap();
        let crack_result: CrackResult = serde_json::from_str(&json).unwrap();
        assert_eq!(crack_result.decoder, "Quoted-Printable");
    }
}
