//! Inflate raw DEFLATE streams (RFC 1951): the compressed data inside zlib and gzip,
//! without their header and checksum. PHP's `gzdeflate()`, .NET's `DeflateStream`, Java's
//! `Deflater` with `nowrap`, Python's `zlib.compressobj(wbits=-15)` and CyberChef's Raw
//! Deflate write it.
//! Call raw_deflate_decoder.crack to use. It returns a `CrackResult`; check
//! `result.unencrypted_text.is_some()` to see if it decoded.
//!
//! Raw DEFLATE has no magic bytes: the only test is that it inflates cleanly. Compressed
//! data is binary and Ciphey passes text between decoders (the Base64 decoder drops output
//! that isn't UTF-8), so, like the Zlib and Gzip decoders, this one reads the compressed
//! bytes itself, from the first of these views of its input that holds a stream:
//!
//! * Base64, standard or URL-safe, with or without padding and line breaks,
//! * hex, optionally split by whitespace, `:` or `,`, with or without `0x` / `\x` prefixes,
//! * raw bytes, as the text the Hexadecimal and Binary decoders produce for binary data
//!   (one Latin-1 character per byte, or UTF-8 when the bytes happen to be UTF-8).
//!
//! Which views apply is decided by the alphabet, in one pass that stops at the first
//! character that doesn't fit, before anything is allocated. A view's bytes then have to
//! start with a plausible block header (RFC 1951 section 3.2.3: not the reserved block
//! type, a stored block's length matching its complement, a dynamic block's code counts
//! in range) and not be a zlib stream, which is the Zlib decoder's. That rejects about
//! half of all byte strings without inflating them. The rest has to inflate without error,
//! end with a final block exactly where the input ends and inflate to at most
//! [`MAX_OUTPUT`] bytes of text, so random bytes almost never get through.

use std::cell::RefCell;

use base64::{engine::general_purpose, Engine as _};
use flate2::{Decompress, FlushDecompress, Status};

use crate::checkers::checker_result::CheckResult;
use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, trace};

/// Largest output we inflate, in bytes. Anything longer is treated as a failure (a zip
/// bomb, or text far too long to be the answer) instead of being truncated.
const MAX_OUTPUT: usize = 1 << 20;

/// Output the checker doesn't accept is only handed on for more decoding up to this many
/// bytes, as in the Gzip decoder: every decoder runs on every node of the search, so a few
/// hundred bytes of compressed data could otherwise make a megabyte node.
const MAX_CANDIDATE: usize = 16 * 1024;

/// Shorter byte strings aren't tried. Six bytes inflate to a few letters at most (the
/// stream for "abc" is 5 bytes, for "hello" 7), too few for the checkers to tell text from
/// noise, and short random byte strings are far more often a complete stream than long
/// ones.
const MIN_STREAM_LEN: usize = 6;

/// The fewest characters, not counting whitespace, the Base64 view reads: 6 bytes are 8
/// characters.
const MIN_BASE64_CHARS: usize = 8;

/// The fewest digits the hex view reads: 6 bytes are 12 digits.
const MIN_HEX_DIGITS: usize = 12;

/// The shortest zlib stream: a 2-byte header, an empty final block (2 bytes) and the
/// 4-byte Adler-32 checksum. Shorter input with a zlib header is no zlib stream.
const MIN_ZLIB_STREAM_LEN: usize = 8;

thread_local! {
    /// One inflater per thread, reset before each stream. Making a new one allocates and
    /// zeroes about 42 KiB (a 32 KiB window and the Huffman tables), which takes longer
    /// than rejecting most streams does, and this decoder runs on every node of the search
    /// that looks like Base64 or hex.
    static INFLATER: RefCell<Decompress> = RefCell::new(Decompress::new(false));
}

/// The Raw DEFLATE decoder, call:
/// `let raw_deflate_decoder = Decoder::<RawDeflateDecoder>::new()` to create a new instance
/// And then call:
/// `result = raw_deflate_decoder.crack(input)` to inflate a raw DEFLATE stream
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::raw_deflate_decoder::RawDeflateDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_raw_deflate = Decoder::<RawDeflateDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // Python: deflate = zlib.compressobj(9, zlib.DEFLATED, -15)
/// // base64.b64encode(deflate.compress(b"The quick brown fox jumps over the lazy dog") + deflate.flush())
/// let result = decode_raw_deflate
///     .crack("C8lIVSgszUzOVkgqyi/PU0jLr1DIKs0tKFbIL0stUigBSuckVlUqpOSnAwA=", &checker)
///     .unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "The quick brown fox jumps over the lazy dog");
/// ```
pub struct RawDeflateDecoder;

impl Crack for Decoder<RawDeflateDecoder> {
    fn new() -> Decoder<RawDeflateDecoder> {
        Decoder {
            name: "Raw DEFLATE",
            description: "Raw DEFLATE (RFC 1951) is zlib/gzip's compressed body without header or checksum, as produced by PHP gzdeflate, .NET DeflateStream and CyberChef Raw Deflate. Ciphey reads the bytes from Base64, hex or raw text and inflates them.",
            link: "https://datatracker.ietf.org/doc/html/rfc1951",
            tags: vec!["deflate", "compression", "decoder"],
            popularity: 0.4,
            phantom: std::marker::PhantomData,
        }
    }

    /// Inflates the raw DEFLATE stream in `text` and runs the checker on the output.
    /// The result has no text unless a view of `text` (Base64, hex or raw bytes) is
    /// exactly one complete stream that inflates to text, or to another compressed stream.
    /// Text the checker doesn't accept is only returned up to [`MAX_CANDIDATE`] bytes.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Raw DEFLATE with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        match first_output(text, checker) {
            Some(Output::Text(plaintext, checker_result)) => {
                results.unencrypted_text = Some(vec![plaintext]);
                results.update_checker(&checker_result);
            }
            // Compressed twice. The inner stream goes on one character per byte (Latin-1),
            // which the next decoder reads back as raw bytes. It is binary, so there is
            // nothing for the checker to look at.
            Some(Output::Compressed(inner)) => {
                debug!("Raw DEFLATE output is another compressed stream");
                results.unencrypted_text = Some(vec![inner]);
            }
            None => trace!("Raw DEFLATE: no view of the input is a usable stream"),
        }

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// What a stream inflated to, if it is worth handing on.
enum Output {
    /// Text, and what the checker made of it.
    Text(String, CheckResult),
    /// Another compressed stream, one Latin-1 character per byte.
    Compressed(String),
}

/// Tries the views of `text` in turn (Base64, hex, then the raw bytes as Latin-1 and as
/// UTF-8) and returns what the first stream worth handing on inflated to. A view that
/// doesn't hold one doesn't stop the next being tried: hex is in the Base64 alphabet too.
fn first_output(text: &str, checker: &CheckerTypes) -> Option<Output> {
    let trimmed = text.trim();
    let output = |stream: Vec<u8>| output_of(&stream, text, checker);
    base64_view(trimmed)
        .and_then(output)
        .or_else(|| hex_view(trimmed).and_then(output))
        .or_else(|| {
            // Raw bytes are not trimmed: the stream can end with bytes that look like
            // whitespace.
            if !looks_binary(text) {
                return None;
            }
            latin1_bytes(text).and_then(output).or_else(|| {
                // Hexadecimal and Binary return UTF-8 instead of Latin-1 when the bytes
                // happen to be UTF-8
                if text.is_ascii() {
                    return None;
                }
                output_of(text.as_bytes(), text, checker)
            })
        })
}

/// Inflates `stream` and returns its output if it is worth handing on: text, which has
/// to be at most [`MAX_CANDIDATE`] bytes unless the checker accepts it, or another
/// compressed stream of at most [`MAX_CANDIDATE`] bytes.
fn output_of(stream: &[u8], text: &str, checker: &CheckerTypes) -> Option<Output> {
    let inflated = raw_inflate_bounded(stream)?;
    let plaintext = match into_text(inflated) {
        Ok(plaintext) => plaintext,
        Err(binary) if is_compressed(&binary) && binary.len() <= MAX_CANDIDATE => {
            return Some(Output::Compressed(
                binary.into_iter().map(char::from).collect(),
            ));
        }
        Err(_) => {
            debug!("Raw DEFLATE output is binary, not text");
            return None;
        }
    };
    if !check_string_success(&plaintext, text) {
        debug!("Raw DEFLATE output is empty");
        return None;
    }

    // The checker runs after the inflater is given back: it can use the thread pool, and
    // a task stolen meanwhile could be this decoder again on the same thread.
    let checker_result = checker.check(&plaintext);
    if !checker_result.is_identified && plaintext.len() > MAX_CANDIDATE {
        debug!(
            "Raw DEFLATE output is not plaintext and too long ({} bytes) to decode further",
            plaintext.len()
        );
        return None;
    }
    Some(Output::Text(plaintext, checker_result))
}

/// Base64, standard or URL-safe, with or without padding and line breaks, decoded with
/// the Base64 decoder's engines. Nothing is allocated unless [`looks_like_base64`].
fn base64_view(text: &str) -> Option<Vec<u8>> {
    if !looks_like_base64(text) {
        return None;
    }
    let compact: String = text.chars().filter(|c| !c.is_ascii_whitespace()).collect();
    let unpadded = compact.trim_end_matches('=');
    let engine = if unpadded.contains(['-', '_']) {
        &general_purpose::URL_SAFE_NO_PAD
    } else {
        &general_purpose::STANDARD_NO_PAD
    };
    // Both engines reject a last character with bits left over, which most English
    // that fits the alphabet ("hello world") has.
    engine.decode(unpadded).ok()
}

/// Whether every character of `text` is a Base64 character (standard or URL-safe) or
/// whitespace, with at most two `=` and only at the end, and at least
/// [`MIN_BASE64_CHARS`] of them aren't whitespace. Stops at the first character that
/// doesn't fit.
fn looks_like_base64(text: &str) -> bool {
    let mut chars = 0;
    let mut padding = 0;
    for byte in text.bytes() {
        if byte.is_ascii_whitespace() {
            continue;
        }
        if byte == b'=' {
            padding += 1;
            if padding > 2 {
                return false;
            }
        } else if padding > 0
            || !(byte.is_ascii_alphanumeric() || matches!(byte, b'+' | b'/' | b'-' | b'_'))
        {
            return false;
        }
        chars += 1;
    }
    chars >= MIN_BASE64_CHARS
}

/// Hex of at least [`MIN_HEX_DIGITS`] digits, an even number of them. Whitespace, `:` and
/// `,` between them and `0x` / `\x` prefixes are skipped. Nothing is allocated unless
/// every character fits.
fn hex_view(text: &str) -> Option<Vec<u8>> {
    let count = hex_digits(text).try_fold(0, |count: usize, digit| digit.map(|_| count + 1))?;
    if count < MIN_HEX_DIGITS || count % 2 != 0 {
        return None;
    }
    let mut digits = hex_digits(text).flatten();
    Some(std::iter::from_fn(|| Some((digits.next()? << 4) | digits.next()?)).collect())
}

/// The values of the hex digits in `text`, skipping whitespace, `:`, `,` and `0x` / `\x`
/// prefixes. The first character that is none of those ends it, with a `None`.
fn hex_digits(text: &str) -> impl Iterator<Item = Option<u8>> + '_ {
    let mut rest = text.as_bytes();
    std::iter::from_fn(move || loop {
        let (&first, tail) = rest.split_first()?;
        if matches!(first, b'0' | b'\\') && matches!(tail.first(), Some(b'x' | b'X')) {
            rest = &tail[1..];
            continue;
        }
        rest = tail;
        if let Some(digit) = char::from(first).to_digit(16) {
            return Some(Some(digit as u8));
        }
        if !(first.is_ascii_whitespace() || matches!(first, b':' | b',')) {
            rest = &[];
            return Some(None);
        }
    })
}

/// Whether `text` contains a character that ordinary text doesn't but compressed bytes
/// almost always do: a control character other than tab and line breaks, or non-ASCII.
/// This keeps text away from the raw view.
fn looks_binary(text: &str) -> bool {
    text.bytes().any(|byte| {
        !byte.is_ascii() || (byte.is_ascii_control() && !matches!(byte, b'\t' | b'\n' | b'\r'))
    })
}

/// One byte per character, if every character is at most U+00FF (Latin-1).
fn latin1_bytes(text: &str) -> Option<Vec<u8>> {
    text.chars().map(|c| u8::try_from(c).ok()).collect()
}

/// Checks on the first block header that about half of all byte strings fail, so most of
/// what isn't raw DEFLATE is rejected without inflating it (RFC 1951 section 3.2.3 to
/// 3.2.7). Zlib streams fail too: they are the Zlib decoder's.
fn starts_like_raw_deflate(stream: &[u8]) -> bool {
    if stream.len() < MIN_STREAM_LEN || has_zlib_header(stream) {
        return false;
    }
    // The block header is the low three bits: BFINAL, then the two bits of BTYPE
    let header = stream[0];
    match (header >> 1) & 0b11 {
        // Stored: LEN, then NLEN, its one's complement, both little-endian from the next
        // byte on, then LEN bytes of data
        0 => {
            let len = u16::from_le_bytes([stream[1], stream[2]]);
            let nlen = u16::from_le_bytes([stream[3], stream[4]]);
            len ^ nlen == 0xFFFF && usize::from(len) <= stream.len() - 5
        }
        // Fixed Huffman codes: nothing else to check without inflating
        1 => true,
        // Dynamic Huffman codes: HLIT + 257 literal/length codes, at most 286, and
        // HDIST + 1 distance codes, at most 30
        2 => header >> 3 <= 29 && stream[1] & 0x1F <= 29,
        // 3 is reserved. Gzip's first byte, 1F, has it.
        _ => false,
    }
}

/// The RFC 1950 header check the Zlib decoder makes (section 2.2): compression method 8
/// (DEFLATE), a window of at most 32 KiB (CINFO <= 7), the two header bytes a multiple of
/// 31 as a big-endian number, no preset dictionary, and long enough to be a zlib stream.
fn has_zlib_header(stream: &[u8]) -> bool {
    let &[cmf, flg, ..] = stream else {
        return false;
    };
    stream.len() >= MIN_ZLIB_STREAM_LEN
        && cmf & 0x0F == 8
        && cmf >> 4 <= 7
        && u16::from_be_bytes([cmf, flg]) % 31 == 0
        && flg & 0x20 == 0
}

/// Inflates `stream` if it is exactly one complete raw DEFLATE stream: a first block that
/// passes [`starts_like_raw_deflate`], blocks that inflate without error to at most
/// [`MAX_OUTPUT`] bytes, a final block, and nothing after it.
///
/// This is flate2's low-level API: its readers can't tell a stream whose final block has
/// been read from one that was cut short, which they return as if it were complete.
fn raw_inflate_bounded(stream: &[u8]) -> Option<Vec<u8>> {
    if !starts_like_raw_deflate(stream) {
        return None;
    }
    INFLATER.with_borrow_mut(|inflater| {
        inflater.reset(false);
        let mut output = Vec::with_capacity((4 * stream.len()).clamp(64, MAX_OUTPUT + 1));
        loop {
            let (read, written) = (inflater.total_in(), output.len());
            // total_in counts from the reset, so it is where the unread input starts
            let unread = &stream[read as usize..];
            match inflater
                .decompress_vec(unread, &mut output, FlushDecompress::None)
                .ok()?
            {
                Status::StreamEnd => break,
                Status::Ok | Status::BufError if output.len() == output.capacity() => {
                    // Out of room. Growing to one byte over the cap tells an output of
                    // exactly MAX_OUTPUT bytes from a longer one.
                    if output.len() > MAX_OUTPUT {
                        debug!("Raw DEFLATE output is over {MAX_OUTPUT} bytes");
                        return None;
                    }
                    let room = (2 * output.capacity()).min(MAX_OUTPUT + 1) - output.len();
                    output.reserve_exact(room);
                }
                // Room to spare and no progress: the input ended before a final block did,
                // because it was cut short or only flushed (Z_SYNC_FLUSH)
                Status::Ok | Status::BufError
                    if inflater.total_in() == read && output.len() == written =>
                {
                    return None;
                }
                Status::Ok | Status::BufError => {}
            }
        }
        // The inflater stops at the end of the final block without looking at what
        // follows it, so check that the stream used up the whole input.
        (inflater.total_in() == stream.len() as u64 && output.len() <= MAX_OUTPUT).then_some(output)
    })
}

/// `bytes` as text, if they are UTF-8 without control characters other than tab and line
/// breaks. Otherwise the bytes, given back.
fn into_text(bytes: Vec<u8>) -> Result<String, Vec<u8>> {
    let text = String::from_utf8(bytes).map_err(|error| error.into_bytes())?;
    if text
        .chars()
        .all(|c| !c.is_control() || matches!(c, '\t' | '\n' | '\r'))
    {
        Ok(text)
    } else {
        Err(text.into_bytes())
    }
}

/// Whether binary output is itself compressed, so worth handing on: a zlib stream starting
/// with `78` (the only first byte the Zlib decoder's raw view reads), a gzip member
/// (`1F 8B 08`), bzip2 (`BZh`) or XZ (`FD 37 7A 58 5A 00`). Raw DEFLATE inside raw
/// DEFLATE can't be told from other binary data, so it isn't.
fn is_compressed(bytes: &[u8]) -> bool {
    (bytes.first() == Some(&0x78) && has_zlib_header(bytes))
        || bytes.starts_with(&[0x1F, 0x8B, 0x08])
        || bytes.starts_with(b"BZh")
        || bytes.starts_with(&[0xFD, b'7', b'z', b'X', b'Z', 0x00])
}

#[cfg(test)]
mod tests {
    use super::{
        raw_inflate_bounded, starts_like_raw_deflate, RawDeflateDecoder, MAX_CANDIDATE, MAX_OUTPUT,
    };
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::{
            crack_results::CrackResult,
            gzip_decoder::GzipDecoder,
            hexadecimal_decoder::HexadecimalDecoder,
            interface::{Crack, Decoder},
            zlib_decoder::ZlibDecoder,
            DECODER_MAP,
        },
        filtration_system::get_decoder_by_name,
    };
    use base64::{engine::general_purpose, Engine as _};
    use flate2::{write::DeflateEncoder, Compression};
    use rayon::prelude::*;
    use std::io::Write;
    use std::time::{Duration, Instant};

    const FOX: &str = "The quick brown fox jumps over the lazy dog";
    const SPHINX: &str = "Sphinx of black quartz, judge my vow.";
    const MEDIUM: &str =
        "Meet me at the old lighthouse after midnight and bring the map, the key and a torch.";

    // Unless noted, the vectors are Python 3.9's raw DEFLATE at level 9,
    // `d = zlib.compressobj(9, zlib.DEFLATED, -15); d.compress(data) + d.flush()`, shown
    // as `base64.b64encode` or `.hex()`. Every one inflates back to its text with
    // `zlib.decompressobj(-15)`, which ends with `eof` set and no `unused_data`; the plan
    // in https://github.com/bee-san/Ciphey/issues/1022 also checked them with CyberChef
    // 10.24's Raw Inflate.

    /// FOX, one block with fixed Huffman codes
    const FOX_B64: &str = "C8lIVSgszUzOVkgqyi/PU0jLr1DIKs0tKFbIL0stUigBSuckVlUqpOSnAwA=";
    /// The same, as hex
    const FOX_HEX: &str =
        "0bc94855282ccd4cce56482aca2fcf5348cbaf50c82acd2d2856c82f4b2d5228014ae72456552aa4e4a70300";

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn crack(text: &str) -> CrackResult {
        Decoder::<RawDeflateDecoder>::new().crack(text, &get_athena_checker())
    }

    /// What the decoder returns for `text`, if anything
    fn decoded(text: &str) -> Option<String> {
        crack(text).unencrypted_text.map(|texts| texts[0].clone())
    }

    fn compress(data: &[u8]) -> Vec<u8> {
        let mut encoder = DeflateEncoder::new(Vec::new(), Compression::default());
        encoder.write_all(data).unwrap();
        encoder.finish().unwrap()
    }

    fn b64(data: &[u8]) -> String {
        general_purpose::STANDARD.encode(data)
    }

    fn bytes_of(hex: &str) -> Vec<u8> {
        (0..hex.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
            .collect()
    }

    /// One char per byte, the way the Hexadecimal decoder writes bytes that aren't UTF-8
    fn latin1(bytes: &[u8]) -> String {
        bytes.iter().copied().map(char::from).collect()
    }

    #[test]
    fn issue_example_decodes() {
        // The example in the issue, as Base64 and hex. Athena doesn't recognise this
        // sentence as English (#1031), so only the output is checked.
        assert_eq!(
            decoded("Cy7IyMyrUMhPU0jKSUzOVigsTSwqqdJRyCpNSU9VyK1UKMsv1wMA").as_deref(),
            Some(SPHINX)
        );
        assert_eq!(
            decoded(
                "0b2ec8c8ccab50c84f5348ca494cce56282c4d2c2aa9d251c82a4d494f55c8ad5428cb2fd70300"
            )
            .as_deref(),
            Some(SPHINX)
        );
    }

    #[test]
    fn fox_is_identified() {
        let result = crack(FOX_B64);
        assert_eq!(result.unencrypted_text.unwrap(), [FOX]);
        assert!(result.success, "Athena should accept the pangram");
        assert_eq!(result.decoder, "Raw DEFLATE");
        assert!(result.key.is_none());
    }

    #[test]
    fn hex_is_identified() {
        let result = crack(FOX_HEX);
        assert_eq!(result.unencrypted_text.unwrap(), [FOX]);
        assert!(result.success);
    }

    #[test]
    fn every_block_type_decodes() {
        for (input, block) in [
            (FOX_B64, "fixed Huffman codes"),
            // Level 0: one stored block, LEN 43 (2b 00) and NLEN (d4 ff)
            (
                "012b00d4ff54686520717569636b2062726f776e20666f78206a756d7073206f76657220746865206c617a7920646f67",
                "stored",
            ),
            // CyberChef 10.24's Raw Deflate with "Dynamic Huffman Coding", a different
            // encoder from zlib's
            (
                "DcnXAYAgDATQVW4oF7BEwXYQCKjTx+83BEG2OB+YlP3Gyge7XamATRT153P8XizcHA==",
                "dynamic Huffman codes",
            ),
            // Three blocks: d.compress(FOX[:20]) + d.flush(zlib.Z_FULL_FLUSH) +
            // d.compress(FOX[20:]) + d.flush(): a fixed block, an empty stored block and
            // the final fixed block
            (
                "CslIVSgszUzOVkgqyi/PU0jLr1AAAAAA///LKs0tKFbIL0stUijJSFXISayqVEjJTwcA",
                "three blocks",
            ),
        ] {
            let result = crack(input);
            assert_eq!(result.unencrypted_text.unwrap(), [FOX], "{block}");
            assert!(result.success, "{block}");
        }
    }

    #[test]
    fn url_safe_base64_decodes() {
        let input = "C8lIVSgszUzOVkgqyi_PU0jLr1DIKs0tKFbIL0stUigBSuckVlUqpOSnAwA=";
        let result = crack(input);
        assert_eq!(result.unencrypted_text.unwrap(), [FOX]);
        assert!(result.success);
        assert_eq!(decoded(input.trim_end_matches('=')).as_deref(), Some(FOX));
    }

    #[test]
    fn wrapped_and_unpadded_base64_decodes() {
        let wrapped: String = FOX_B64
            .as_bytes()
            .chunks(20)
            .map(|line| format!("{}\r\n", std::str::from_utf8(line).unwrap()))
            .collect();
        for input in [
            wrapped,
            FOX_B64.trim_end_matches('=').to_string(),
            format!("  {FOX_B64}\n"),
        ] {
            assert_eq!(decoded(&input).as_deref(), Some(FOX), "{input:?}");
        }
    }

    #[test]
    fn hex_with_separators_and_prefixes_decodes() {
        let pairs: Vec<&str> = (0..FOX_HEX.len())
            .step_by(2)
            .map(|i| &FOX_HEX[i..i + 2])
            .collect();
        for input in [
            FOX_HEX.to_uppercase(),
            pairs.join(" "),
            pairs.join(":"),
            pairs.join("\n"),
            format!("0x{FOX_HEX}"),
            // xxd -i
            pairs
                .iter()
                .map(|p| format!("0x{p}"))
                .collect::<Vec<_>>()
                .join(", "),
            pairs.iter().map(|p| format!("\\x{p}")).collect::<String>(),
            format!("  {}\n", pairs.join(" ")),
        ] {
            assert_eq!(decoded(&input).as_deref(), Some(FOX), "{input}");
        }
    }

    #[test]
    fn benchmark_texts_are_identified() {
        // The medium and long inputs in benches/data/decoders.toml
        let medium =
            crack("HYrREYAwCMVWeQN4buIQaLFwltZD/HB7lb9ckoU5YAwKhDBGK2haJWTc12f3YIdp6b8D9YLVtdd8jc4p4eAnEyGGbzK/");
        assert_eq!(medium.unencrypted_text.unwrap(), [MEDIUM]);
        assert!(medium.success);

        let long = crack("PZFBktwwCEWvwgGm+hKpLLKYA2RJJNqiLAuXwO1xn34+Tiob2Srg/8fXD92bXKROPIiPsI1DKlUpVnUsFGb9Qb/toEVfQhoko8xrzyabebGK35CvgELNhpgqjkE6ba5kR9DZGAc7VRuSFY0POjVaFi9oN379NaN12EnRhFZQpcFLxn0vCTof9CvIhWdp6dGmHUujjcdFu7nrny7/2f2D0FVWJ+HSqABPK7ZLGxcBlUB4JnI3Q1vXVejnWLp6S29EcdvwTTVo5wiZg/yAHN+JycbaiWud4vDLBDxs9xQfqfzUUZ3cNnjdK2YUU7j+s9s768j0HvRpHmTPe9vQDUfDswSvQOiQz1m8EdiLjYoAm5bcPetwQrFe9AR34T2OKbfQs/OCGLh3GYsAcT/eb4TUjhF+8+YE8suXORuSiWNDiqiViUTTLyZjNr+5gSZDtwWrdXl8Aw==");
        assert!(long.success);
        assert!(long.unencrypted_text.unwrap()[0].starts_with("Ciphey is an automated"));
    }

    #[test]
    fn flag_is_identified() {
        let result = crack("S8tJTK8uSiyPT0lNy0ksSY3PSCyOz8uPz0hNTEktqgUA");
        assert_eq!(
            result.unencrypted_text.unwrap(),
            ["flag{raw_deflate_has_no_header}"]
        );
        assert!(result.success, "the checkers should recognise the CTF flag");
    }

    #[test]
    fn hexadecimal_output_is_read_as_raw_bytes() {
        let hexadecimal = Decoder::<HexadecimalDecoder>::new();
        let raw = |hex: &str| {
            hexadecimal
                .crack(hex, &get_athena_checker())
                .unencrypted_text
                .unwrap()
                .remove(0)
        };

        // The fox stream isn't UTF-8, so the Hexadecimal decoder writes it as Latin-1
        let one_char_per_byte = raw(FOX_HEX);
        assert_eq!(one_char_per_byte, latin1(&bytes_of(FOX_HEX)));
        assert_eq!(decoded(&one_char_per_byte).as_deref(), Some(FOX));

        // Level 1 of b"data fox" happens to be UTF-8 ("˯" is U+02EF), so the Hexadecimal
        // decoder writes it as UTF-8 instead
        let utf8 = raw("4b492c495448cbaf0000");
        assert!(utf8.contains('\u{2EF}'));
        assert_eq!(decoded(&utf8).as_deref(), Some("data fox"));
    }

    #[test]
    fn nested_compression_is_passed_on_as_raw_bytes() {
        // Raw DEFLATE of zlib.compress(FOX)
        let outer =
            crack("ATIAzf94nAvJSFUoLM1MzlZIKsovz1NIy69QyCrNLShWyC9LLVIoAUrnJFZVKqTkpwMAW9wP2g==");
        assert!(!outer.success);
        let inner = outer.unencrypted_text.unwrap().remove(0);
        assert!(inner.starts_with("x\u{9c}"), "{inner:?}");
        let zlib = Decoder::<ZlibDecoder>::new().crack(&inner, &get_athena_checker());
        assert_eq!(zlib.unencrypted_text.unwrap(), [FOX]);

        // Raw DEFLATE of gzip.compress(FOX, mtime=0)
        let outer = crack(
            "k+/mYAABpv/cJz1CNXTO+pwL89A6pX8+2OP0+oATWmd1NcJO6HvrBmkwej1XCQvVWvJkOTOD5WJ/R22gLgA=",
        );
        let inner = outer.unencrypted_text.unwrap().remove(0);
        let gzip = Decoder::<GzipDecoder>::new().crack(&inner, &get_athena_checker());
        assert_eq!(gzip.unencrypted_text.unwrap(), [FOX]);

        // Raw DEFLATE of bz2.compress(SPHINX) and of lzma.compress(SPHINX, format=FORMAT_XZ),
        // for the bzip2 and XZ decoders (#1023, #1024)
        for (input, magic) in [
            (
                "AUwAs/9CWmg5MUFZJlNZfw+tnwAABBOAQAUIAD//9/AgADFAANAAAUamI9AmR6gP0hkf+4VT5E6ljzj1NUQunL2VAPn1AXIu5IpwoSD+H1s+",
                &b"BZh"[..],
            ),
            (
                "+2teFRHFwMDy7NoWNyYGRUYxBgaGEv2nixkZVIILMjLzKhTy0xSSchKTsxUKSxOLSqp0FLJKU9JTFXIrFcryy/WAyhnybB8e0vhwtYWB0Vb1kmYWo/y2z7WMIAmWyCgA",
                &[0xFD, b'7', b'z', b'X', b'Z', 0x00],
            ),
        ] {
            let inner = decoded(input).expect("the inner stream");
            assert!(inner.starts_with(&latin1(magic)), "{inner:?}");
        }
    }

    #[test]
    fn incomplete_streams_and_trailing_bytes_fail() {
        for input in [
            // FOX_B64 cut short; CyberChef's Raw Inflate errors and Python's
            // decompressobj never reaches eof
            "C8lIVSgszUzOVkgqyi/PU0jLr1DIKs0tKFbIL0stUigBSuckVlUqpA==",
            // FOX_B64 followed by "GARBAGE", which CyberChef ignores and Python reports as
            // unused_data
            "C8lIVSgszUzOVkgqyi/PU0jLr1DIKs0tKFbIL0stUigBSuckVlUqpOSnAwBHQVJCQUdF",
            // d.compress(FOX) + d.flush(zlib.Z_SYNC_FLUSH): every byte of FOX is there,
            // but the stream ends with an empty stored block that isn't the final block
            "CslIVSgszUzOVkgqyi/PU0jLr1DIKs0tKFbIL0stUigBSuckVlUqpOSnAwAAAP//",
        ] {
            assert_eq!(decoded(input), None, "{input}");
        }
    }

    #[test]
    fn every_truncation_fails() {
        let stream = bytes_of(FOX_HEX);
        assert_eq!(raw_inflate_bounded(&stream), Some(FOX.as_bytes().to_vec()));
        for length in 0..stream.len() {
            assert_eq!(
                raw_inflate_bounded(&stream[..length]),
                None,
                "{length} bytes"
            );
        }
        assert_eq!(decoded(&FOX_HEX[..FOX_HEX.len() - 2]), None);
        // And any byte after the end, including a zero
        for byte in [0x00, 0x03, 0xff] {
            let longer = [stream.as_slice(), &[byte]].concat();
            assert_eq!(raw_inflate_bounded(&longer), None, "{byte:02x}");
        }
    }

    #[test]
    fn other_compression_formats_fail() {
        for input in [
            // zlib.compress(FOX, 9) and gzip.compress(FOX, mtime=0): the Zlib and Gzip
            // decoders' (78 DA is a zlib header; 1F has the reserved block type)
            "eNoLyUhVKCzNTM5WSCrKL89TSMuvUMgqzS0oVsgvSy1SKAFK5yRWVSqk5KcDAFvcD9o=",
            "H4sIAAAAAAAC/wvJSFUoLM1MzlZIKsovz1NIy69QyCrNLShWyC9LLVIoAUrnJFZVKqTkpwMAOaNPQSsAAAA=",
            "789c0bc94855282ccd4cce56482aca2fcf5348cbaf50c82acd2d2856c82f4b2d5228014ae72456552aa4e4a703005bdc0fda",
            // The examples in #1023 (bzip2, "BZh" reads as fixed Huffman codes and fails
            // to inflate) and #1024 (XZ, whose first byte claims 288 literal/length
            // codes; and the legacy .lzma container)
            "QlpoOTFBWSZTWX8PrZ8AAAQTgEAFCAA///fwIAAxQADQAAFGpiPQJkeoD9IZH/uFU+ROpY849TVELpy9lQD59QFyLuSKcKEg/h9bPg==",
            "/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQAkU3BoaW54IG9mIGJsYWNrIHF1YXJ0eiwganVkZ2UgbXkgdm93LgAAAABuPeHCKPDVhAABPSXSKWoBH7bzfQEAAAAABFla",
            "XQAAgAD//////////wApnAkGs6iqYK0+rdZrCbrHCjNiT/hoUVL3L+59llK2C4kmTlnCHFQNG///xv0AAA==",
        ] {
            assert_eq!(decoded(input), None, "{input}");
        }
    }

    #[test]
    fn block_headers_are_checked_before_inflating() {
        let fox = bytes_of(FOX_HEX);
        assert!(starts_like_raw_deflate(&fox));
        let stored = bytes_of("012b00d4ff54686520717569636b2062726f776e20666f78206a756d7073206f76657220746865206c617a7920646f67");
        assert!(starts_like_raw_deflate(&stored));

        for (stream, why) in [
            (&b"\x07abcdef"[..], "BTYPE 3 is reserved"),
            (b"\x1f\x8b\x08\x00\x00\x00", "so gzip fails"),
            (
                b"\x01\x02\x00\xfc\xffab",
                "a stored block's NLEN has to be LEN's complement",
            ),
            (
                b"\x01\x03\x00\xfc\xffab",
                "a stored block can't be longer than the input",
            ),
            (
                b"\xf5\x00\x00\x00\x00\x00",
                "HLIT 30 is too many literal/length codes",
            ),
            (
                b"\x05\x1e\x00\x00\x00\x00",
                "HDIST 30 is too many distance codes",
            ),
            (
                b"\x78\x9c\x03\x00\x00\x00\x00\x01",
                "a zlib stream is the Zlib decoder's",
            ),
            (b"\x03\x00", "too short"),
        ] {
            assert!(!starts_like_raw_deflate(stream), "{why}");
        }
        // The largest counts are allowed, and LEN can be all that is left
        assert!(starts_like_raw_deflate(b"\xed\x1d\x00\x00\x00\x00"));
        assert!(starts_like_raw_deflate(b"\x01\x01\x00\xfe\xffa"));
        // A zlib header on something too short for a zlib stream doesn't count
        assert!(!super::has_zlib_header(b"\x78\x9c\x01\x00\xff\xff"));
    }

    #[test]
    fn back_references_before_the_start_fail() {
        // A hand-made fixed Huffman block: a 3-byte copy from distance 1 before any
        // output, then the literals "hello world". zlib rejects it ("invalid distance too
        // far back"); miniz_oxide copies zeroes instead, which makes the output binary.
        let stream = bytes_of("03828cd49c9c7c85f2fca29c1400");
        if let Some(output) = raw_inflate_bounded(&stream) {
            assert!(output.contains(&0), "{output:?}");
        }
        assert_eq!(decoded("A4KM1JycfIXy/KKcFAA="), None);
    }

    #[test]
    fn binary_output_fails() {
        // bytes(range(256)) is a valid stream, but not of text
        let binary: Vec<u8> = (0..=255).collect();
        assert_eq!(
            raw_inflate_bounded(&compress(&binary)),
            Some(binary.clone())
        );
        assert_eq!(decoded(&b64(&compress(&binary))), None);
        // "café au lait" in Latin-1 isn't UTF-8
        assert_eq!(decoded("S05Me6mQWKqQk5hZAgA="), None);
        // UTF-8, but with a control character
        assert_eq!(decoded("K8rMS1coyUhVSErNyVFgVygpz0xOBQA="), None);
        // "café au lait" in UTF-8
        assert_eq!(
            decoded("S05MO7xSIbFUIScxswQA").as_deref(),
            Some("café au lait")
        );
    }

    #[test]
    fn streams_under_six_bytes_are_not_tried() {
        // "a" (3 bytes, SwQA) and "abc" (5 bytes) are complete streams, "hello" (7) too
        assert_eq!(raw_inflate_bounded(&bytes_of("4b0400")), None);
        assert_eq!(decoded("SwQA"), None);
        assert_eq!(raw_inflate_bounded(&bytes_of("4b4c4a0600")), None);
        assert_eq!(
            raw_inflate_bounded(&bytes_of("cb48cdc9c90700")),
            Some(b"hello".to_vec())
        );
        // The empty stream, 03 00
        assert_eq!(decoded("AwA="), None);
    }

    #[test]
    fn output_is_capped_at_one_mebibyte() {
        let at_cap = raw_inflate_bounded(&compress(&vec![b'a'; MAX_OUTPUT]));
        assert_eq!(at_cap.map(|output| output.len()), Some(MAX_OUTPUT));
        assert_eq!(
            raw_inflate_bounded(&compress(&vec![b'a'; MAX_OUTPUT + 1])),
            None
        );
    }

    #[test]
    fn zip_bomb_fails_quickly() {
        // 64 MiB of "A" is about 65 KB of raw DEFLATE; inflating stops at the cap
        let mut encoder = DeflateEncoder::new(Vec::new(), Compression::default());
        let chunk = vec![b'A'; 1 << 16];
        for _ in 0..1024 {
            encoder.write_all(&chunk).unwrap();
        }
        let bomb = encoder.finish().unwrap();
        assert!(bomb.len() < 100_000, "{}", bomb.len());
        let base64_bomb = b64(&bomb);

        let start = Instant::now();
        assert_eq!(raw_inflate_bounded(&bomb), None);
        assert_eq!(decoded(&base64_bomb), None);
        // About 16 ms in a debug build
        assert!(
            start.elapsed() < Duration::from_secs(1),
            "took {:?}",
            start.elapsed()
        );
    }

    #[test]
    fn long_output_is_only_kept_if_the_checker_accepts_it() {
        // Not plaintext: handed on for more decoding up to the limit, dropped above it
        let result = crack(&b64(&compress(&vec![b'A'; MAX_CANDIDATE])));
        assert!(!result.success);
        assert_eq!(result.unencrypted_text.unwrap()[0].len(), MAX_CANDIDATE);
        assert_eq!(
            decoded(&b64(&compress(&vec![b'A'; MAX_CANDIDATE + 1]))),
            None
        );

        // Plaintext is returned whatever its length (up to MAX_OUTPUT)
        let english = format!("{FOX}. ").repeat(MAX_CANDIDATE / FOX.len() + 1);
        assert!(english.len() > MAX_CANDIDATE);
        let result = crack(&b64(&compress(english.as_bytes())));
        assert!(result.success, "Athena should identify the plaintext");
        assert_eq!(result.unencrypted_text.unwrap(), [english]);
    }

    #[test]
    fn inflater_is_reset_between_streams() {
        let fox = bytes_of(FOX_HEX);
        // Leave the per-thread inflater in the middle of a stream, failed, and at the cap
        assert_eq!(raw_inflate_bounded(&fox[..20]), None);
        assert_eq!(
            raw_inflate_bounded(b"\x0b\xff\xff\xff\xff\xff\xff\xff"),
            None
        );
        assert_eq!(
            raw_inflate_bounded(&compress(&vec![0; MAX_OUTPUT + 1])),
            None
        );
        assert_eq!(raw_inflate_bounded(&fox), Some(FOX.as_bytes().to_vec()));

        // Every thread of the pool, each with its own inflater, many times over
        let streams = [compress(FOX.as_bytes()), compress(SPHINX.as_bytes())];
        let outputs: Vec<Option<Vec<u8>>> = (0..2000)
            .into_par_iter()
            .map(|i| raw_inflate_bounded(&streams[i % 2]))
            .collect();
        for (i, output) in outputs.into_iter().enumerate() {
            let expected = if i % 2 == 0 { FOX } else { SPHINX };
            assert_eq!(output.as_deref(), Some(expected.as_bytes()), "{i}");
        }
    }

    #[test]
    fn random_bytes_do_not_inflate_to_text() {
        // Pseudo-random bytes (xorshift64), 12 to 64 of them, as the Base64 and hex views
        // read them. The plan in #1022 measured 0 text outputs in 200,000 tries per length.
        let mut state = 0x2545_f491_4f6c_dd1d_u64;
        let mut next_byte = || {
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            state as u8
        };
        let mut complete = 0;
        for i in 0..20_000 {
            let stream: Vec<u8> = (0..12 + i % 53).map(|_| next_byte()).collect();
            if let Some(output) = raw_inflate_bounded(&stream) {
                complete += 1;
                assert!(super::into_text(output).is_err(), "{stream:02x?}");
            }
        }
        // 9 of them are complete streams, all of binary output
        assert!(complete < 40, "{complete} complete streams");
    }

    #[test]
    fn text_that_is_not_raw_deflate_fails() {
        for input in [
            "",
            "   ",
            "\t\n",
            "😀",
            "x😀",
            "hello world",
            "hello my name is panicky mc panic face!",
            // Base64 and hex of text
            "TXIgUm9ib3QgaXMgZ3JlYXQ=",
            "68656c6c6f20776f726c64",
            "0x",
            "\\x",
            "=",
            // The miss input in benches/data/decoders.toml
            "T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV",
            "Ciphey is an automated decoding tool. You give it encrypted or encoded text.",
            "éèêëàâäôöûüçéèêëàâäôöûüçéèêëàâäôöûüç",
        ] {
            assert!(crack(input).unencrypted_text.is_none(), "{input}");
        }
    }

    #[test]
    fn raw_deflate_is_registered() {
        let decoders = get_decoder_by_name("Raw DEFLATE");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Raw DEFLATE");
        assert!(DECODER_MAP.contains_key("Raw DEFLATE"));
    }
}
