//! Decode the Standard Galactic Alphabet (SGA), the 26-letter alphabet of Commander Keen
//! that Minecraft's enchanting table uses, written with look-alike Unicode characters.
//! Call standard_galactic_alphabet_decoder.crack to use. It returns a `CrackResult` whose
//! `unencrypted_text` is `None` when the input isn't SGA.
//!
//! The table is the one everyone copies, LingoJam's translator, which is also Python
//! Ciphey's (`cipheydists::translate::galactic`). Twenty-two letters are one character:
//!
//! ```text
//! a ᔑ U+1511   b ʖ U+0296   c ᓵ U+14F5   d ↸ U+21B8   e ᒷ U+14B7   f ⎓ U+2393
//! g ⊣ U+22A3   h ⍑ U+2351   i ╎ U+254E   j ⋮ U+22EE   k ꖌ U+A58C   l ꖎ U+A58E
//! m ᒲ U+14B2   n リ U+30EA   o 𝙹 U+1D679  q ᑑ U+1451   r ∷ U+2237   s ᓭ U+14ED
//! u ⚍ U+268D   v ⍊ U+234A   w ∴ U+2234   z ⨅ U+2A05
//! ```
//!
//! The other four are written with ASCII punctuation and combining marks, differently by
//! different tools:
//!
//! ```text
//!     LingoJam                          others                     cipheydists
//! p   !¡    U+0021 U+00A1                                          !
//! t   ℸ ̣    U+2138 U+0020 U+0323 U+0020  ℸ ̣ (U+2138 U+0020 U+0323)  ℸ
//!                                       ℸ̣ (U+2138 U+0323)
//! x    ̇/   U+0020 U+0307 U+002F         ̇/ (U+0307 U+002F)          (none; Python Ciphey
//!                                                                  read a lone U+0307)
//! y   ||    U+007C U+007C                                          |
//! ```
//!
//! Capitals, digits and punctuation aren't letters of the alphabet: LingoJam leaves them
//! alone (`Sꖎ╎↸ᒷ` is `Slide`), and so does this decoder. The letters it outputs are lower
//! case.
//!
//! Known quirk: text written with the cipheydists table (no `!¡`, `||`, ` ̇/` or dotted
//! `ℸ`) can't tell a `!` that is p from an exclamation mark, so `⍑ᒷꖎꖎ𝙹 ∴𝙹∷ꖎ↸!` decodes to
//! `hello worldp`. When the text has any of LingoJam's forms, a lone `!` or `|` is
//! punctuation: `ᓭℸ ̣ 𝙹!¡! ||ᒷᓭ` is `stop! yes`.
//!
//! `𝙹` (U+1D679) is outside the Basic Multilingual Plane, so everything here compares
//! `char`s, never bytes or UTF-16 units. The combining marks don't compose with the
//! characters before them under NFC, so no normalisation is needed.
//!
//! References: Wikipedia <https://en.wikipedia.org/wiki/Commander_Keen#Standard_Galactic_Alphabet>,
//! LingoJam's translator <https://lingojam.com/StandardGalacticAlphabet>, cipheydists'
//! table <https://github.com/Ciphey/CipheyDists/blob/master/cipheydists/translate/galactic.json>
//! and Python Ciphey 5.14.0's decoder
//! <https://github.com/bee-san/Ciphey/blob/5.14.0/ciphey/basemods/Decoders/galactic.py>.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The Standard Galactic Alphabet decoder, call:
/// `let sga_decoder = Decoder::<StandardGalacticAlphabetDecoder>::new()` to create a new instance
/// And then call:
/// `result = sga_decoder.crack(input)` to decode Standard Galactic Alphabet text
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::standard_galactic_alphabet_decoder::StandardGalacticAlphabetDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_sga = Decoder::<StandardGalacticAlphabetDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_sga.crack("⍑ᒷꖎꖎ𝙹 ∴𝙹∷ꖎ↸", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hello world");
/// ```
pub struct StandardGalacticAlphabetDecoder;

/// U+2138 DALET SIGN, t. LingoJam follows it with ` ̣ `.
const T: char = '\u{2138}';
/// U+0323 COMBINING DOT BELOW, the dot under t
const DOT_BELOW: char = '\u{0323}';
/// U+0307 COMBINING DOT ABOVE, the dot of x
const DOT_ABOVE: char = '\u{0307}';
/// U+00A1 INVERTED EXCLAMATION MARK, the second half of LingoJam's p (`!¡`)
const INVERTED_EXCLAMATION: char = '\u{00A1}';
/// What follows `ℸ` in `ℸ ̣` and LingoJam's `ℸ ̣ `
const SPACE_DOT_BELOW: &str = " \u{0323}";
/// What follows the space in x, ` ̇/`
const DOT_ABOVE_SLASH: &str = "\u{0307}/";

impl Crack for Decoder<StandardGalacticAlphabetDecoder> {
    fn new() -> Decoder<StandardGalacticAlphabetDecoder> {
        Decoder {
            name: "Standard Galactic Alphabet",
            description: "Standard Galactic Alphabet (Minecraft enchanting table) written with look-alike Unicode symbols",
            link: "https://en.wikipedia.org/wiki/Commander_Keen#Standard_Galactic_Alphabet",
            tags: vec![
                "standard_galactic_alphabet",
                "galactic",
                "minecraft",
                "substitution",
                "decoder",
            ],
            // Rarer than Braille (0.4), but common enough in puzzle Discords. Text that
            // isn't SGA is rejected the same way whatever this is.
            popularity: 0.3,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes `text` from the Standard Galactic Alphabet and checks the result with
    /// `checker`. `unencrypted_text` is `None` when `text` isn't mostly SGA letters.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Standard Galactic Alphabet with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_galactic(text) else {
            debug!("Failed to decode Standard Galactic Alphabet because too few characters are SGA letters");
            return results;
        };
        trace!(
            "Decoded text for Standard Galactic Alphabet: {:?}",
            decoded_text
        );

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Standard Galactic Alphabet because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// The letter a one-character SGA symbol stands for: 22 letters, and `ℸ` for t.
fn letter(c: char) -> Option<char> {
    Some(match c {
        '\u{1511}' => 'a',  // ᔑ
        '\u{0296}' => 'b',  // ʖ
        '\u{14F5}' => 'c',  // ᓵ
        '\u{21B8}' => 'd',  // ↸
        '\u{14B7}' => 'e',  // ᒷ
        '\u{2393}' => 'f',  // ⎓
        '\u{22A3}' => 'g',  // ⊣
        '\u{2351}' => 'h',  // ⍑
        '\u{254E}' => 'i',  // ╎
        '\u{22EE}' => 'j',  // ⋮
        '\u{A58C}' => 'k',  // ꖌ
        '\u{A58E}' => 'l',  // ꖎ
        '\u{14B2}' => 'm',  // ᒲ
        '\u{30EA}' => 'n',  // リ
        '\u{1D679}' => 'o', // 𝙹
        '\u{1451}' => 'q',  // ᑑ
        '\u{2237}' => 'r',  // ∷
        '\u{14ED}' => 's',  // ᓭ
        T => 't',           // ℸ
        '\u{268D}' => 'u',  // ⚍
        '\u{234A}' => 'v',  // ⍊
        '\u{2234}' => 'w',  // ∴
        '\u{2A05}' => 'z',  // ⨅
        _ => return None,
    })
}

/// What one pass over a text finds before anything is decoded.
#[derive(Debug, PartialEq, Eq)]
struct Census {
    /// Characters that are one of the 23 one-character letters, `ℸ` included
    letters: usize,
    /// ASCII letters, and characters outside ASCII that aren't letters or the marks of
    /// p, t and x: SGA text has few of these
    other: usize,
    /// Whether the text writes p, t, x or y with more than one character (`!¡`, a dotted
    /// `ℸ`, `̇/` or `||`). If it does, a lone `!` or `|` is punctuation.
    multi_char_letters: bool,
}

/// Counts the letters and other characters of `text` in one pass, without allocating.
fn census(text: &str) -> Census {
    let mut census = Census {
        letters: 0,
        other: 0,
        multi_char_letters: false,
    };
    let mut previous = '\0';
    for c in text.chars() {
        if letter(c).is_some() {
            census.letters += 1;
        } else if c.is_ascii_alphabetic()
            || !(c.is_ascii() || matches!(c, DOT_BELOW | DOT_ABOVE | INVERTED_EXCLAMATION))
        {
            census.other += 1;
        }
        // A bare U+0307 is the one-character x, so only the pair with `/` counts
        census.multi_char_letters |= matches!(c, INVERTED_EXCLAMATION | DOT_BELOW)
            || (c == '|' && previous == '|')
            || (c == '/' && previous == DOT_ABOVE);
        previous = c;
    }
    census
}

/// Decodes `text` from the Standard Galactic Alphabet, or returns `None` if it isn't
/// mostly SGA letters.
fn decode_galactic(text: &str) -> Option<String> {
    // Every letter except `!` and `|` is outside ASCII, so Base64, hex, English and almost
    // every other text the search tries stop here
    if text.is_ascii() {
        return None;
    }
    // Braille, CJK, emoji, Japanese (`リンゴ` has one letter and two other characters) and
    // the Latin-1 text Hexadecimal makes of random bytes stop here. Every letter is above
    // U+00FF, so Latin-1 never has one.
    let census = census(text);
    if census.letters < 2 || census.letters < census.other {
        return None;
    }
    Some(translate(text, census.multi_char_letters))
}

/// Replaces every SGA letter in `text` with its Latin letter, longest form first, and
/// copies everything else. `multi_char_letters` is [`Census::multi_char_letters`].
fn translate(text: &str, multi_char_letters: bool) -> String {
    // Every letter is at least as long in UTF-8 as its Latin letter
    let mut decoded = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(c) = rest.chars().next() {
        rest = &rest[c.len_utf8()..];
        let plain = match c {
            T => {
                if let Some(after_dot) = rest.strip_prefix(DOT_BELOW) {
                    // `ℸ̣` has no spaces of its own, so a space after it is a word space
                    rest = after_dot;
                } else if let Some(after_dot) = rest.strip_prefix(SPACE_DOT_BELOW) {
                    // `ℸ ̣` and LingoJam's `ℸ ̣ ` drop the dot and the spaces around it,
                    // so `ℸ ̣ ⍑ᒷ` is `the`
                    rest = after_dot.strip_prefix(' ').unwrap_or(after_dot);
                }
                't'
            }
            // ` ̇/` is x; any other space is a space, so `ᔑ  ̇/∷ᔑ||` is `a xray`
            ' ' => match rest.strip_prefix(DOT_ABOVE_SLASH) {
                Some(after) => {
                    rest = after;
                    'x'
                }
                None => ' ',
            },
            DOT_ABOVE => {
                rest = rest.strip_prefix('/').unwrap_or(rest);
                'x'
            }
            '!' => match rest.strip_prefix(INVERTED_EXCLAMATION) {
                Some(after) => {
                    rest = after;
                    'p'
                }
                None if multi_char_letters => '!',
                None => 'p',
            },
            '|' => match rest.strip_prefix('|') {
                Some(after) => {
                    rest = after;
                    'y'
                }
                None if multi_char_letters => '|',
                None => 'y',
            },
            _ => letter(c).unwrap_or(c),
        };
        decoded.push(plain);
    }
    decoded
}

#[cfg(test)]
mod tests {
    use super::{census, decode_galactic, letter, Census, StandardGalacticAlphabetDecoder};
    use crate::checkers::athena::Athena;
    use crate::checkers::checker_type::{Check, Checker};
    use crate::checkers::CheckerTypes;
    use crate::decoders::interface::{Crack, Decoder};
    use crate::decoders::{DecoderType, DECODER_MAP};
    use crate::filtration_system::get_decoder_by_name;

    // Unless noted otherwise the vectors are the ones in the implementation plan of
    // https://github.com/bee-san/Ciphey/issues/968: decoded with a Python prototype of
    // this algorithm and, where the plan says so, with the logic of Python Ciphey 5.14.0's
    // `Decoders/galactic.py` on the cipheydists table. The LingoJam sentence is real
    // LingoJam output (https://lingojam.com/StandardGalacticAlphabet).

    /// The bench `medium` plaintext, and the `search.toml` plaintext
    const MEDIUM: &str =
        "Meet me at the old lighthouse after midnight and bring the map, the key and a torch.";

    /// The bench `long` plaintext
    const LONG: &str = "Ciphey is an automated decoding tool. You give it encrypted or encoded text and it tries to work out what was done to it, without you having to know the key or even the cipher. It searches through many possible decodings, checks each candidate to see whether it looks like English or matches a known pattern such as an email address, and stops when it finds something that reads like plaintext. Most of the time this takes less than a second, which makes it handy for capture the flag challenges, puzzle hunts and for anyone who stumbles across a strange string in a log file.";

    /// `MEDIUM` encoded the way LingoJam encodes it
    const MEDIUM_SGA: &str = "Mᒷᒷℸ ̣  ᒲᒷ ᔑℸ ̣  ℸ ̣ ⍑ᒷ 𝙹ꖎ↸ ꖎ╎⊣⍑ℸ ̣ ⍑𝙹⚍ᓭᒷ ᔑ⎓ℸ ̣ ᒷ∷ ᒲ╎↸リ╎⊣⍑ℸ ̣  ᔑリ↸ ʖ∷╎リ⊣ ℸ ̣ ⍑ᒷ ᒲᔑ!¡, ℸ ̣ ⍑ᒷ ꖌᒷ|| ᔑリ↸ ᔑ ℸ ̣ 𝙹∷ᓵ⍑.";

    /// Encodes lower-case letters the way LingoJam does: `t` is `ℸ ̣ `, `x` is ` ̇/`, `p` is
    /// `!¡` and `y` is `||`. Everything else is kept.
    fn encode_lingojam(plaintext: &str) -> String {
        const SINGLE: &str = "ᔑʖᓵ↸ᒷ⎓⊣⍑╎⋮ꖌꖎᒲリ𝙹 ᑑ∷ᓭ ⚍⍊∴  ⨅";
        plaintext
            .chars()
            .map(|c| match c {
                'p' => "!\u{A1}".to_string(),
                't' => "\u{2138} \u{323} ".to_string(),
                'x' => " \u{307}/".to_string(),
                'y' => "||".to_string(),
                'a'..='z' => SINGLE
                    .chars()
                    .nth(c as usize - 'a' as usize)
                    .unwrap()
                    .to_string(),
                _ => c.to_string(),
            })
            .collect()
    }

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    // Runs the decoder with the Athena checker and returns the decoded text, if any
    fn crack(text: &str) -> Option<String> {
        let decoder = Decoder::<StandardGalacticAlphabetDecoder>::new();
        let result = decoder.crack(text, &get_athena_checker());
        if result.unencrypted_text.is_none() {
            assert!(!result.success, "{text:?} failed but was marked successful");
        }
        result.unencrypted_text.map(|texts| texts[0].clone())
    }

    // Asserts that Athena accepts what `text` decodes to and returns it
    fn crack_successfully(text: &str) -> String {
        let decoder = Decoder::<StandardGalacticAlphabetDecoder>::new();
        let result = decoder.crack(text, &get_athena_checker());
        assert!(result.success, "Athena should accept {text:?}: {result:?}");
        result.unencrypted_text.unwrap()[0].clone()
    }

    #[test]
    fn decodes_the_issue_example() {
        // https://github.com/bee-san/Ciphey/issues/968, written with the cipheydists table
        assert_eq!(crack_successfully("⍑ᒷꖎꖎ𝙹 ∴𝙹∷ꖎ↸"), "hello world");
    }

    #[test]
    fn decodes_lingojam_output() {
        // Real LingoJam output: capitals and full stops are kept, t is `ℸ ̣ `, y is `||`
        assert_eq!(
            crack_successfully("Sꖎ╎↸ᒷ ℸ ̣ ⍑ᒷ ʖ╎ꖎꖎ ʖᒷℸ ̣ ∴ᒷᒷリ ℸ ̣ ⍑ᒷ ℸ ̣ ∴𝙹 ꖎᒷᔑ⍊ᒷᓭ. T⍑ᒷ ᓭ⍑ᔑꖌ|| ʖᔑ∷リ ⎓ᒷꖎꖎ ∴╎ℸ ̣ ⍑ ᔑ ꖎ𝙹⚍↸ ᓵ∷ᔑᓭ⍑."),
            "Slide the bill between the two leaves. The shaky barn fell with a loud crash."
        );
    }

    #[test]
    fn decodes_the_fox_pangram_in_lingojam_form() {
        // p, t, x and y in their LingoJam forms. Python Ciphey 5.14.0 moves the space
        // before x to after it, splitting `fox` from `jumps` in the wrong place.
        assert_eq!(
            crack_successfully("ℸ ̣ ⍑ᒷ ᑑ⚍╎ᓵꖌ ʖ∷𝙹∴リ ⎓𝙹 ̇/ ⋮⚍ᒲ!¡ᓭ 𝙹⍊ᒷ∷ ℸ ̣ ⍑ᒷ ꖎᔑ⨅|| ↸𝙹⊣"),
            "the quick brown fox jumps over the lazy dog"
        );
    }

    #[test]
    fn decodes_the_fox_pangram_in_cipheydists_form() {
        // A lone `!` is p and a lone `|` is y; cipheydists has no x, so it stays `x`
        assert_eq!(
            crack_successfully("ℸ⍑ᒷ ᑑ⚍╎ᓵꖌ ʖ∷𝙹∴リ ⎓𝙹x ⋮⚍ᒲ!ᓭ 𝙹⍊ᒷ∷ ℸ⍑ᒷ ꖎᔑ⨅| ↸𝙹⊣"),
            "the quick brown fox jumps over the lazy dog"
        );
    }

    #[test]
    fn decodes_x_and_t_with_any_spacing() {
        // LingoJam. Python Ciphey 5.14.0 gives `e xactly`.
        assert_eq!(crack_successfully("ᒷ ̇/ᔑᓵℸ ̣ ꖎ||"), "exactly");
        // `ℸ ̣` without the space after the dot
        assert_eq!(crack_successfully("ᒷ ̇/ᔑᓵℸ ̣ꖎ||"), "exactly");
        // No spaces at all: `̇/` and `ℸ̣`
        assert_eq!(crack_successfully("ᒷ̇/ᔑᓵℸ̣ꖎ||"), "exactly");
    }

    #[test]
    fn a_space_before_x_is_kept() {
        // `a` then a word space, then x written as ` ̇/`
        assert_eq!(crack("ᔑ  ̇/∷ᔑ||").unwrap(), "a xray");
    }

    #[test]
    fn a_word_space_after_t_is_kept() {
        // LingoJam's `ℸ ̣ ` then the word space
        assert_eq!(crack("ᔑℸ ̣  ℸ ̣ ⍑ᒷ").unwrap(), "at the");
        // `ℸ̣` has no spaces of its own, so the space after it is the word space
        assert_eq!(crack("ᔑℸ̣ ℸ̣⍑ᒷ").unwrap(), "at the");
        // t at the end of the text
        assert_eq!(crack("ᔑℸ ̣ ").unwrap(), "at");
        assert_eq!(crack("ᔑℸ").unwrap(), "at");
    }

    #[test]
    fn decodes_the_alphabet() {
        // Athena doesn't take the alphabet for English, so only the text is checked
        assert_eq!(
            crack("ᔑʖᓵ↸ᒷ⎓⊣⍑╎⋮ꖌꖎᒲリ𝙹!¡ᑑ∷ᓭℸ ̣ ⚍⍊∴ ̇/||⨅").unwrap(),
            "abcdefghijklmnopqrstuvwxyz"
        );
        // The one-character forms: `!`, `ℸ`, a bare U+0307 for x (as Python Ciphey read it)
        // and `|`
        assert_eq!(
            crack("ᔑʖᓵ↸ᒷ⎓⊣⍑╎⋮ꖌꖎᒲリ𝙹!ᑑ∷ᓭℸ⚍⍊∴\u{307}|⨅").unwrap(),
            "abcdefghijklmnopqrstuvwxyz"
        );
    }

    #[test]
    fn lone_marks_are_punctuation_next_to_multi_character_letters() {
        // `!¡` is p, so the `!` after it is an exclamation mark
        assert_eq!(crack("ᓭℸ ̣ 𝙹!¡! ||ᒷᓭ").unwrap(), "stop! yes");
        assert_eq!(crack("⍑ᒷꖎꖎ𝙹 ∴𝙹∷ꖎ↸ | ||ᒷᓭ").unwrap(), "hello world | yes");
    }

    #[test]
    fn a_lone_exclamation_mark_is_p_without_multi_character_letters() {
        // The quirk documented in the module: cipheydists' p is `!`. Athena still takes
        // `hello worldp` for English.
        assert_eq!(crack_successfully("⍑ᒷꖎꖎ𝙹 ∴𝙹∷ꖎ↸!"), "hello worldp");
    }

    #[test]
    fn capitals_digits_and_punctuation_pass_through() {
        assert_eq!(crack_successfully("Hello ∴𝙹∷ꖎ↸"), "Hello world");
        assert_eq!(crack("Sꖎ╎↸ᒷ").unwrap(), "Slide");
        assert_eq!(
            crack("ᒲᒷᒷℸ ̣  ᔑℸ ̣  10:30, ∷𝙹𝙹ᒲ 7?").unwrap(),
            "meet at 10:30, room 7?"
        );
    }

    #[test]
    fn decodes_the_bench_medium_text() {
        // benches/data/decoders.toml, Standard Galactic Alphabet medium
        assert_eq!(encode_lingojam(MEDIUM), MEDIUM_SGA);
        assert_eq!(crack_successfully(MEDIUM_SGA), MEDIUM);
    }

    #[test]
    fn decodes_the_bench_long_text() {
        // benches/data/decoders.toml, Standard Galactic Alphabet long: 740 characters
        let long = encode_lingojam(LONG);
        assert_eq!(long.chars().count(), 740);
        assert_eq!(crack(&long).unwrap(), LONG);
    }

    #[test]
    fn every_letter_round_trips() {
        for c in 'a'..='z' {
            // Alone, and doubled at the start of a word. `!¡`, `||` and ` ̇/` aren't
            // counted as letters, so other letters go around them.
            let word = format!("ab{c} {c}{c}de");
            assert_eq!(
                decode_galactic(&encode_lingojam(&word)).as_deref(),
                Some(word.as_str()),
                "{c}"
            );
        }
        let pangram = "sphinx of black quartz, judge my vow";
        assert_eq!(crack(&encode_lingojam(pangram)).unwrap(), pangram);
    }

    #[test]
    fn the_table_has_23_one_character_letters() {
        // cipheydists' table, plus `ℸ`; p, x and y are ASCII or combining marks
        let letters: Vec<char> = (0..=0x10FFFF)
            .filter_map(char::from_u32)
            .filter(|&c| letter(c).is_some())
            .collect();
        assert_eq!(letters.len(), 23);
        // All of them are above U+00FF, so the Latin-1 text Hexadecimal makes never has one
        assert!(letters.iter().all(|&c| u32::from(c) > 0xFF));
    }

    #[test]
    fn reads_the_letter_outside_the_bmp_as_one_character() {
        // 𝙹 is U+1D679, four bytes of UTF-8 and a surrogate pair in UTF-16
        assert_eq!(decode_galactic("𝙹𝙹").as_deref(), Some("oo"));
        assert_eq!(decode_galactic("ᓭ𝙹𝙹リ").as_deref(), Some("soon"));
    }

    #[test]
    fn census_counts_letters_and_other_characters() {
        assert_eq!(
            census("Hello ∴𝙹∷ꖎ↸!"),
            Census {
                letters: 5,
                other: 5,
                multi_char_letters: false
            }
        );
        // The marks of p, t and x are neither letters nor other characters
        assert_eq!(
            census("ℸ ̣ ⍑ᒷ ⎓𝙹 ̇/ ⋮⚍ᒲ!¡ᓭ"),
            Census {
                letters: 9,
                other: 0,
                multi_char_letters: true
            }
        );
        // A bare U+0307 is the one-character x, not a multi-character letter
        assert!(!census("∴\u{307}|").multi_char_letters);
        assert!(census("∴\u{307}/").multi_char_letters);
        assert!(census("ᒷ||").multi_char_letters);
        assert!(!census("ᒷ|").multi_char_letters);
    }

    #[test]
    fn fails_on_too_few_letters() {
        // One letter
        assert_eq!(crack("ᔑ 123"), None);
        // `!` and `|` alone are ASCII
        assert_eq!(crack("!|"), None);
        // Japanese: リ is n, but ン and ゴ aren't letters
        assert_eq!(crack("リンゴ"), None);
        assert_eq!(crack("ᔑ ʖ 日本語の文章です"), None);
        // Text with a few look-alike symbols in it
        assert_eq!(crack("Therefore ∴ the proof is done"), None);
    }

    #[test]
    fn fails_on_other_unicode_encodings() {
        // Braille
        assert_eq!(crack("⠓⠑⠇⠇⠕⠀⠺⠕⠗⠇⠙"), None);
        // Core Socialist Values
        assert_eq!(crack("公正爱国公正平等"), None);
        // Base100 and Base65536
        assert_eq!(crack("👟👜👣👣👦🐗👮👦👩👣👛"), None);
        assert_eq!(crack("𒅓鹨𖡮𒀠啦ꍢ顡啫𓍱𓁡𠁴唬𓍪鱤啥𖥭𔐠𔕯ᔮ"), None);
        // What Hexadecimal makes of random bytes: Latin-1, with an `¡` in it
        assert_eq!(crack("Ã©\u{A1}Ã\u{A7}Â\u{B5}Ã\u{BF}"), None);
    }

    #[test]
    fn fails_on_the_bench_miss_input() {
        assert_eq!(
            crack("T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV"),
            None
        );
    }

    #[test]
    fn handles_panic_if_empty_string() {
        assert_eq!(crack(""), None);
    }

    #[test]
    fn handles_panic_if_emoji() {
        assert_eq!(crack("😀"), None);
    }

    #[test]
    fn fails_on_english() {
        assert_eq!(crack("hello world"), None);
        assert_eq!(crack("hello my name is panicky mc panic face!"), None);
        // Accented Latin text isn't SGA either
        assert_eq!(crack("Crème brûlée, s'il vous plaît!"), None);
    }

    #[test]
    fn handles_lone_marks_without_panicking() {
        // Marks with nothing to attach to are copied
        assert_eq!(crack("ᔑʖ\u{323}\u{A1}").unwrap(), "ab\u{323}\u{A1}");
        assert_eq!(crack("ᔑʖ \u{307}").unwrap(), "ab x");
        assert_eq!(crack("ᔑʖℸ \u{323}").unwrap(), "abt");
        assert_eq!(crack("ᔑʖℸ ").unwrap(), "abt ");
    }

    #[test]
    fn is_registered() {
        // Exactly one decoder by that name runs in the search
        let decoders = get_decoder_by_name("Standard Galactic Alphabet");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(
            decoders.components[0].get_name(),
            "Standard Galactic Alphabet"
        );
        assert!(decoders.components[0].get_tags().contains(&"decoder"));
        // Cached results name the decoder; reading them back looks it up here
        let decoder = DECODER_MAP
            .get("Standard Galactic Alphabet")
            .expect("Standard Galactic Alphabet should be in DECODER_MAP")
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "Standard Galactic Alphabet");
        assert_eq!(decoder.get_popularity(), 0.3);
    }
}
