//! Decode tap code (knock code), such as `2,3 1,5 3,1 3,1 3,4` or
//! `.. ...  . .....  ... .  ... .  ... ....` for `HELLO`.
//! Call tap_code_decoder.crack to use. It returns a `CrackResult` whose `unencrypted_text` is
//! `None` when the input isn't tap code.
//!
//! Tap code sends each letter as two groups of taps: the row, then the column of the letter in
//! this 5×5 square. K has no cell of its own and is sent as C, so it decodes as C.
//!
//! ```text
//!       1 2 3 4 5
//!   1   A B C D E
//!   2   F G H I J
//!   3   L M N O P
//!   4   Q R S T U
//!   5   V W X Y Z
//! ```
//!
//! Two ways of writing it are decoded:
//! * Digit pairs, `row,col`: `2,3` is H. One space or tab separates letters; two or more, a
//!   line break, `/` or `|` separate words.
//! * Knocks: runs of one repeated symbol that isn't a letter or a digit, such as `.`, `•` or
//!   `*`, so `.. ...` is H. The narrowest gap separates the row from the column and the next
//!   one separates letters. A third, wider gap, a line break, `/` or `|` separates words.
//!
//! When every word is a single letter, the word gaps were letter gaps (`.. ... / . ..... /
//! ...`, `2,3  1,5  3,1`) and the letters are joined without spaces. The output is upper case.
//!
//! Digits without commas (`23 15 31`, `231531`) are Polybius square coordinates, not tap code,
//! and are left alone. So are knocks written with a letter or digit (`xx xxx`) and taps
//! written one at a time with spaces between them (`. .  . . .`).

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};
use std::iter::Peekable;
use std::str::Chars;

/// The Tap Code decoder, call:
/// `let tap_code_decoder = Decoder::<TapCodeDecoder>::new()` to create a new instance
/// And then call:
/// `result = tap_code_decoder.crack(input)` to decode tap code
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::tap_code_decoder::TapCodeDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_tap_code = Decoder::<TapCodeDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_tap_code
///     .crack("2,3 1,5 3,1 3,1 3,4  5,2 3,4 4,2 3,1 1,4", &checker)
///     .unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "HELLO WORLD");
///
/// // The same letters as knocks
/// let result = decode_tap_code
///     .crack(".. ...  . .....  ... .  ... .  ... ....", &checker)
///     .unencrypted_text;
/// assert_eq!(result.unwrap()[0], "HELLO");
/// ```
pub struct TapCodeDecoder;

/// The square, row by row. K shares C's cell, so it isn't here.
const SQUARE: &[u8; 25] = b"ABCDEFGHIJLMNOPQRSTUVWXYZ";

/// The most taps in a group: the square has five rows and five columns.
const MAX_TAPS: u8 = 5;

/// Fewer letters than this are too likely to be something else, like the coordinates `2,3`.
const MIN_LETTERS: usize = 3;

impl Crack for Decoder<TapCodeDecoder> {
    fn new() -> Decoder<TapCodeDecoder> {
        Decoder {
            name: "Tap Code",
            description: "Tap code (knock code) sends each letter as two groups of taps, the row and column of a 5×5 Polybius square with K folded into C; written as `2,3` pairs or runs of dots.",
            link: "https://en.wikipedia.org/wiki/Tap_code",
            tags: vec!["tap_code", "knock", "polybius", "substitution", "decoder"],
            popularity: 0.3,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes `text` as tap code and checks the result with `checker`.
    /// `unencrypted_text` is `None` when `text` isn't tap code.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Tap Code with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_tap_code(text) else {
            debug!("Failed to decode Tap Code because the text isn't tap code");
            return results;
        };
        trace!("Decoded text for Tap Code: {:?}", decoded_text);

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Tap Code because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Decodes tap code to upper-case text, or returns `None` if `text` isn't tap code.
fn decode_tap_code(text: &str) -> Option<String> {
    let body = text.trim();
    // The first character picks the notation, and turns away almost every other input: text,
    // Base64, hex, A1Z26, decimal and Polybius digits all fail here.
    let first = body.chars().next()?;
    if matches!(first, '1'..='5') && body.as_bytes().get(1) == Some(&b',') {
        decode_digit_pairs(body)
    } else if is_knock_symbol(first) {
        decode_knocks(body, first)
    } else {
        None
    }
}

/// Whether `c` can stand for one tap. Letters and digits would make ordinary words and numbers
/// look like knocks, and `,`, `/` and `|` are separators.
fn is_knock_symbol(c: char) -> bool {
    !c.is_ascii_alphanumeric() && !c.is_whitespace() && !matches!(c, ',' | '/' | '|')
}

/// Decodes `row,col` digit pairs such as `2,3 1,5 3,1 3,1 3,4  5,2 3,4 4,2 3,1 1,4`.
fn decode_digit_pairs(body: &str) -> Option<String> {
    let mut plaintext = Plaintext::with_capacity(body.len() / 3);
    let mut chars = body.chars().peekable();
    loop {
        let row = coordinate(chars.next()?)?;
        if chars.next()? != ',' {
            return None;
        }
        let col = coordinate(chars.next()?)?;
        plaintext.push(row, col);

        let gap = take_gap(&mut chars);
        if chars.peek().is_none() {
            break;
        }
        if gap.is_empty() {
            // Something other than a separator straight after a pair, as in `1,2,3` or `2,31,5`
            return None;
        }
        if gap.hard || gap.width >= 2 {
            plaintext.end_word();
        }
    }
    plaintext.finish()
}

/// The coordinate a digit stands for, if it is 1 to 5.
fn coordinate(c: char) -> Option<u8> {
    match c {
        '1'..='5' => Some(c as u8 - b'0'),
        _ => None,
    }
}

/// Decodes groups of `symbol`, such as `.. ...  . .....  ... .  ... .  ... ....`.
fn decode_knocks(body: &str, symbol: char) -> Option<String> {
    // First pass: every character is the symbol or a separator, no group has more than five
    // taps, and how wide the gaps are.
    let mut widths = NarrowestWidths::default();
    let mut most_taps = 0;
    for knock in Knocks::new(body, symbol) {
        match knock? {
            Knock::Taps(taps) => most_taps = most_taps.max(taps),
            Knock::Gap(gap) if !gap.hard => widths.insert(gap.width),
            Knock::Gap(_) => {}
        }
    }
    if most_taps == 1 {
        // Nothing but single taps would only spell AAA..., so these are taps written one at a
        // time with spaces between them (`. .  . . .`), which this decoder doesn't read
        return None;
    }
    // The narrowest gap is inside a letter and the next one between letters. Only a third,
    // wider one can separate words: `.. ...  . .....   ..... ..` is two words, while
    // Wikipedia's `•• •••   • •••••` (one and three spaces) is one.
    let word_gap = widths.third();

    // Second pass: pair the groups into letters, word by word
    let mut plaintext = Plaintext::with_capacity(body.len() / 3);
    let mut row = None;
    for knock in Knocks::new(body, symbol) {
        match knock? {
            Knock::Taps(taps) => match row.take() {
                None => row = Some(taps),
                Some(row) => plaintext.push(row, taps),
            },
            Knock::Gap(gap) => {
                if gap.hard || word_gap.is_some_and(|width| gap.width >= width) {
                    if row.is_some() {
                        // A word with an odd number of groups
                        return None;
                    }
                    plaintext.end_word();
                }
            }
        }
    }
    if row.is_some() {
        return None;
    }
    plaintext.finish()
}

/// A run of separators: whitespace, `/` and `|`.
#[derive(Clone, Copy, Debug, PartialEq)]
struct Gap {
    /// Spaces, tabs and other whitespace that isn't a line break.
    width: usize,
    /// Whether the run holds a line break, `/` or `|`, which always separate words.
    hard: bool,
}

impl Gap {
    /// Whether there was no separator at all.
    fn is_empty(self) -> bool {
        self.width == 0 && !self.hard
    }
}

/// Whether `c` always separates words: a line break, `/` or `|`.
fn is_hard_separator(c: char) -> bool {
    matches!(
        c,
        '/' | '|' | '\n' | '\r' | '\u{0B}' | '\u{0C}' | '\u{85}' | '\u{2028}' | '\u{2029}'
    )
}

/// Takes the separators at the front of `chars`.
fn take_gap(chars: &mut Peekable<Chars>) -> Gap {
    let mut gap = Gap {
        width: 0,
        hard: false,
    };
    while let Some(&c) = chars.peek() {
        if is_hard_separator(c) {
            gap.hard = true;
        } else if c.is_whitespace() {
            // Copied from a web page, the gaps can be no-break spaces
            gap.width += 1;
        } else {
            break;
        }
        chars.next();
    }
    gap
}

/// One piece of knock notation.
#[derive(Debug, PartialEq)]
enum Knock {
    /// A group of one to five taps.
    Taps(u8),
    /// The separators after a group.
    Gap(Gap),
}

/// Splits knock notation into groups of taps and the gaps between them. Yields `None`, and
/// then stops, at a character that is neither the symbol nor a separator, or at a group of six
/// or more taps.
struct Knocks<'a> {
    /// What is left of the text.
    chars: Peekable<Chars<'a>>,
    /// The character that stands for one tap.
    symbol: char,
    /// Whether the text turned out not to be knocks.
    failed: bool,
}

impl<'a> Knocks<'a> {
    /// Splits `body`, in which `symbol` stands for one tap.
    fn new(body: &'a str, symbol: char) -> Self {
        Knocks {
            chars: body.chars().peekable(),
            symbol,
            failed: false,
        }
    }

    /// Ends the iteration with a `None` item.
    fn fail(&mut self) -> Option<Option<Knock>> {
        self.failed = true;
        Some(None)
    }
}

impl Iterator for Knocks<'_> {
    type Item = Option<Knock>;

    fn next(&mut self) -> Option<Option<Knock>> {
        if self.failed {
            return None;
        }
        if self.chars.peek()? == &self.symbol {
            let mut taps = 0;
            while self.chars.next_if_eq(&self.symbol).is_some() {
                taps += 1;
                if taps > MAX_TAPS {
                    return self.fail();
                }
            }
            return Some(Some(Knock::Taps(taps)));
        }
        let gap = take_gap(&mut self.chars);
        if gap.is_empty() {
            return self.fail();
        }
        Some(Some(Knock::Gap(gap)))
    }
}

/// The three narrowest gap widths seen, narrowest first. Equal widths count once.
#[derive(Default)]
struct NarrowestWidths([Option<usize>; 3]);

impl NarrowestWidths {
    /// Records a gap of `width`.
    fn insert(&mut self, mut width: usize) {
        for slot in &mut self.0 {
            match *slot {
                None => {
                    *slot = Some(width);
                    return;
                }
                Some(seen) if seen == width => return,
                // Keep the narrower one here and move the wider one along
                Some(seen) if width < seen => *slot = Some(std::mem::replace(&mut width, seen)),
                Some(_) => {}
            }
        }
    }

    /// The third narrowest width, if there were three different ones.
    fn third(&self) -> Option<usize> {
        self.0[2]
    }
}

/// The decoded letters, word by word.
struct Plaintext {
    /// The letters, with one space between words.
    text: String,
    /// Letters so far.
    letters: usize,
    /// Letters in the current word.
    letters_in_word: usize,
    /// Letters in the longest word.
    longest_word: usize,
    /// Whether the next letter starts a new word.
    space_pending: bool,
}

impl Plaintext {
    /// An empty plaintext with room for `capacity` bytes.
    fn with_capacity(capacity: usize) -> Self {
        Plaintext {
            text: String::with_capacity(capacity),
            letters: 0,
            letters_in_word: 0,
            longest_word: 0,
            space_pending: false,
        }
    }

    /// Adds the letter at `row` and `col`, both 1 to 5, to the current word.
    fn push(&mut self, row: u8, col: u8) {
        if self.space_pending {
            self.text.push(' ');
            self.space_pending = false;
        }
        let cell = usize::from(row - 1) * 5 + usize::from(col - 1);
        self.text.push(char::from(SQUARE[cell]));
        self.letters += 1;
        self.letters_in_word += 1;
        self.longest_word = self.longest_word.max(self.letters_in_word);
    }

    /// Ends the current word.
    fn end_word(&mut self) {
        if self.letters_in_word > 0 {
            self.space_pending = true;
            self.letters_in_word = 0;
        }
    }

    /// The decoded text, or `None` if it is too short to be tap code.
    fn finish(mut self) -> Option<String> {
        if self.letters < MIN_LETTERS {
            return None;
        }
        if self.longest_word == 1 {
            // Every word is one letter, so the word gaps were really letter gaps
            self.text.retain(|c| c != ' ');
        }
        Some(self.text)
    }
}

#[cfg(test)]
mod tests {
    use super::{decode_tap_code, Gap, Knock, Knocks, NarrowestWidths, TapCodeDecoder, SQUARE};
    use crate::checkers::athena::Athena;
    use crate::checkers::checker_type::{Check, Checker};
    use crate::checkers::CheckerTypes;
    use crate::decoders::interface::{Crack, Decoder};
    use crate::decoders::{DecoderType, DECODER_MAP};
    use crate::filtration_system::get_decoder_by_name;

    // The square was checked cell by cell against `translate/tap_code.json` in cipheydists
    // 0.3.35, the table Python Ciphey's tap code decoder used, and it matches Wikipedia
    // (https://en.wikipedia.org/wiki/Tap_code) and dCode (https://www.dcode.fr/tap-cipher).
    // The vectors below come from the issue (https://github.com/bee-san/Ciphey/issues/962),
    // whose digit example was round-tripped through Python Ciphey's decoder, or were encoded
    // from that table with a Python 3 script; the knock forms use the same table.

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    // Runs the decoder with the Athena checker and returns the decoded text, if any
    fn crack(text: &str) -> Option<String> {
        let decoder = Decoder::<TapCodeDecoder>::new();
        let result = decoder.crack(text, &get_athena_checker());
        if result.unencrypted_text.is_none() {
            assert!(!result.success, "{text:?} failed but was marked successful");
        }
        result.unencrypted_text.map(|texts| texts[0].clone())
    }

    // Asserts that `text` decodes to `expected` and that Athena takes it for plaintext
    fn assert_identified(text: &str, expected: &str) {
        let decoder = Decoder::<TapCodeDecoder>::new();
        let result = decoder.crack(text, &get_athena_checker());
        assert_eq!(
            result.unencrypted_text.as_deref(),
            Some(&[expected.to_string()][..]),
            "{text:?}"
        );
        assert!(result.success, "Athena should accept {expected:?}");
    }

    #[test]
    fn square_matches_cipheydists() {
        // cipheydists 0.3.35 translate/tap_code.json, row by row
        let pairs = [
            ("1,1", 'A'),
            ("1,2", 'B'),
            ("1,3", 'C'),
            ("1,4", 'D'),
            ("1,5", 'E'),
            ("2,1", 'F'),
            ("2,2", 'G'),
            ("2,3", 'H'),
            ("2,4", 'I'),
            ("2,5", 'J'),
            ("3,1", 'L'),
            ("3,2", 'M'),
            ("3,3", 'N'),
            ("3,4", 'O'),
            ("3,5", 'P'),
            ("4,1", 'Q'),
            ("4,2", 'R'),
            ("4,3", 'S'),
            ("4,4", 'T'),
            ("4,5", 'U'),
            ("5,1", 'V'),
            ("5,2", 'W'),
            ("5,3", 'X'),
            ("5,4", 'Y'),
            ("5,5", 'Z'),
        ];
        for (cell, (pair, letter)) in pairs.iter().enumerate() {
            assert_eq!(char::from(SQUARE[cell]), *letter, "{pair}");
            // Three copies so the text is long enough to decode
            let text = format!("{pair} {pair} {pair}");
            assert_eq!(decode_tap_code(&text), Some(letter.to_string().repeat(3)));
        }
        assert!(!SQUARE.contains(&b'K'));
    }

    #[test]
    fn decodes_the_issue_example() {
        assert_identified("2,3 1,5 3,1 3,1 3,4  5,2 3,4 4,2 3,1 1,4", "HELLO WORLD");
    }

    #[test]
    fn decodes_the_issue_knock_example() {
        assert_identified(".. ...  . .....  ... .  ... .  ... ....", "HELLO");
    }

    #[test]
    fn decodes_wikipedia_bullets() {
        // Wikipedia: one space inside a letter, three between letters, U+2022 bullets
        assert_identified("•• •••   • •••••   ••• •   ••• •   ••• ••••", "HELLO");
    }

    #[test]
    fn decodes_wikipedia_bullets_copied_from_the_page() {
        // The article's wikitext writes the letter gap as ` &nbsp; `, so text copied from the
        // page has a no-break space between two spaces
        assert_identified(
            "•• ••• \u{a0} • ••••• \u{a0} ••• • \u{a0} ••• • \u{a0} ••• ••••",
            "HELLO",
        );
    }

    #[test]
    fn decodes_knocks_with_a_wider_word_gap() {
        assert_identified(
            ".. ...  . .....  ... .  ... .  ... ....   ..... ..  ... ....  .... ..  ... .  . ....",
            "HELLO WORLD",
        );
        // Wikipedia's spacing, with five spaces between the words
        assert_identified(
            "•• •••   • •••••   ••• •   ••• •   ••• ••••     ••••• ••   ••• ••••   •••• ••   ••• •   • ••••",
            "HELLO WORLD",
        );
    }

    #[test]
    fn decodes_knocks_with_a_slash_between_words() {
        assert_identified(
            ".. ...  . .....  ... .  ... .  ... .... / ..... ..  ... ....  .... ..  ... .  . ....",
            "HELLO WORLD",
        );
    }

    #[test]
    fn decodes_knocks_with_a_slash_between_letters() {
        // Every "word" is one letter, so the slashes separate letters
        assert_identified(".. ... / . ..... / ... . / ... . / ... ....", "HELLO");
    }

    #[test]
    fn decodes_pairs_with_two_spaces_between_letters() {
        assert_identified("2,3  1,5  3,1  3,1  3,4", "HELLO");
    }

    #[test]
    fn decodes_meet_me_at_midnight() {
        assert_identified(
            "3,2 1,5 1,5 4,4  3,2 1,5  1,1 4,4  3,2 2,4 1,4 3,3 2,4 2,2 2,3 4,4",
            "MEET ME AT MIDNIGHT",
        );
    }

    #[test]
    fn decodes_meet_me_at_midnight_as_knocks() {
        // Morse Code reads these dots too, as `SIE5E5HH...`, which isn't identified
        assert_identified(
            "... ..  . .....  . .....  .... ....   ... ..  . .....   . .  .... ....   ... ..  .. ....  . ....  ... ...  .. ....  .. ..  .. ...  .... ....",
            "MEET ME AT MIDNIGHT",
        );
    }

    #[test]
    fn decodes_k_as_c() {
        // ATTACK AT DAWN: K is sent as C
        assert_identified(
            "1,1 4,4 4,4 1,1 1,3 1,3  1,1 4,4  1,4 1,1 5,2 3,3",
            "ATTACC AT DAWN",
        );
        assert_identified(
            "* *  **** ****  **** ****  * *  * ***  * ***   * *  **** ****   * ****  * *  ***** **  *** ***",
            "ATTACC AT DAWN",
        );
    }

    #[test]
    fn decodes_water() {
        assert_identified("5,2 1,1 4,4 1,5 4,2", "WATER");
        assert_identified("..... ..  . .  .... ....  . .....  .... ..", "WATER");
    }

    #[test]
    fn decodes_the_stale_ports_example() {
        // The test in the earlier port on the python-decoder-migration branch (#851).
        // Athena doesn't take the text for plaintext, but it is decoded.
        assert_eq!(
            crack("4,4 1,5 4,3 4,4  3,4 3,3 1,5").as_deref(),
            Some("TEST ONE")
        );
    }

    #[test]
    fn decodes_j() {
        // J has its own cell, 2,5
        assert_eq!(
            crack("2,5 4,5 3,2 3,5  3,4 5,1 1,5 4,2").as_deref(),
            Some("JUMP OVER")
        );
    }

    #[test]
    fn decodes_line_breaks_between_words() {
        assert_identified("2,3 1,5 3,1 3,1 3,4\n5,2 3,4 4,2 3,1 1,4", "HELLO WORLD");
        assert_identified(
            "2,3 1,5 3,1 3,1 3,4\r\n5,2 3,4 4,2 3,1 1,4\r\n",
            "HELLO WORLD",
        );
        assert_identified(
            ".. ...  . .....  ... .  ... .  ... ....\n..... ..  ... ....  .... ..  ... .  . ....",
            "HELLO WORLD",
        );
    }

    #[test]
    fn decodes_pipes_and_slashes_between_words() {
        assert_eq!(
            decode_tap_code("2,3 1,5 3,1 3,1 3,4 | 5,2 3,4 4,2 3,1 1,4").as_deref(),
            Some("HELLO WORLD")
        );
        assert_eq!(
            decode_tap_code("2,3 1,5 3,1 3,1 3,4/5,2 3,4 4,2 3,1 1,4").as_deref(),
            Some("HELLO WORLD")
        );
        assert_eq!(
            decode_tap_code(".. ...  . .....  ... .  ... .  ... ....|..... ..  ... ....")
                .as_deref(),
            Some("HELLO WO")
        );
    }

    #[test]
    fn decodes_tabs_and_surrounding_whitespace() {
        assert_eq!(
            decode_tap_code("  2,3\t1,5\t3,1\t3,1\t3,4\n").as_deref(),
            Some("HELLO")
        );
        assert_eq!(
            decode_tap_code("\t.. ...\t\t. .....\t\t... .\t\t... .\t\t... ....  ").as_deref(),
            Some("HELLO")
        );
    }

    #[test]
    fn ignores_a_trailing_separator() {
        assert_eq!(
            decode_tap_code("2,3 1,5 3,1 3,1 3,4 /").as_deref(),
            Some("HELLO")
        );
        assert_eq!(
            decode_tap_code(".. ...  . .....  ... .  ... .  ... .... /").as_deref(),
            Some("HELLO")
        );
    }

    #[test]
    fn decodes_other_knock_symbols() {
        // Any symbol that isn't a letter or digit, including dashes and emoji
        assert_eq!(
            decode_tap_code("-- ---  - -----  --- -  --- -  --- ----").as_deref(),
            Some("HELLO")
        );
        assert_eq!(
            decode_tap_code("✊✊ ✊✊✊  ✊ ✊✊✊✊✊  ✊✊✊ ✊  ✊✊✊ ✊  ✊✊✊ ✊✊✊✊")
                .as_deref(),
            Some("HELLO")
        );
    }

    #[test]
    fn decodes_one_letter_words() {
        // "I AM A": not every word is one letter, so the spaces stay
        assert_eq!(
            decode_tap_code("2,4  1,1 3,2  1,1").as_deref(),
            Some("I AM A")
        );
    }

    #[test]
    fn decodes_the_minimum_length() {
        assert_eq!(decode_tap_code("2,3 2,4 4,3").as_deref(), Some("HIS"));
        assert_eq!(
            decode_tap_code(".. ...  .. ....  .... ...").as_deref(),
            Some("HIS")
        );
    }

    #[test]
    fn fails_with_fewer_than_three_letters() {
        assert_eq!(crack("2,3 1,5"), None);
        assert_eq!(crack(".. ...  . ....."), None);
        assert_eq!(crack("2,3"), None);
        assert_eq!(crack("2,4  1,1"), None);
    }

    #[test]
    fn fails_on_coordinates_out_of_range() {
        assert_eq!(crack("2,3 1,5 3,1 3,1 3,6"), None);
        assert_eq!(crack("6,1 1,5 3,1"), None);
        assert_eq!(crack("0,1 1,5 3,1"), None);
        assert_eq!(crack("2,3 1,5 3,0"), None);
    }

    #[test]
    fn fails_on_more_than_five_taps() {
        assert_eq!(crack("...... ."), None);
        assert_eq!(crack(".. ...  . ......  ... ."), None);
    }

    #[test]
    fn fails_on_an_odd_number_of_groups() {
        assert_eq!(crack(". .. ..."), None);
        // HELLO with the column of the last O missing
        assert_eq!(crack(".. ...  . .....  ... .  ... .  ..."), None);
        // One word of HELLO WORLD missing a group
        assert_eq!(
            crack(
                ".. ...  . .....  ... .  ... .  ... .... / ..... ..  ... ....  .... ..  ... .  ."
            ),
            None
        );
    }

    #[test]
    fn fails_on_plain_digits() {
        // Polybius square coordinates, not tap code
        assert_eq!(crack("23 15 31 31 34"), None);
        assert_eq!(crack("2315313134"), None);
        assert_eq!(crack("23,15,31,31,34"), None);
        assert_eq!(crack("2 3 1 5 3 1 3 1 3 4"), None);
    }

    #[test]
    fn fails_on_malformed_pairs() {
        assert_eq!(crack("1,2,3,4"), None);
        assert_eq!(crack("2,31,5 3,1"), None);
        assert_eq!(crack("2,3 1,5 3,1 x"), None);
        assert_eq!(crack("2,3 1,5 3,"), None);
        assert_eq!(crack("2,3 1;5 3,1"), None);
        assert_eq!(crack("2,3 1,5 3,1,"), None);
        assert_eq!(crack("2, 3 1, 5 3, 1"), None);
        assert_eq!(crack("/ 2,3 1,5 3,1"), None);
    }

    #[test]
    fn fails_on_morse_code() {
        // Two different symbols
        assert_eq!(crack(".... . .-.. .-.. ---"), None);
        assert_eq!(crack(".. --- ... ..."), None);
        assert_eq!(crack("-- --- -"), None);
    }

    #[test]
    fn fails_on_letter_and_digit_symbols() {
        assert_eq!(crack("xx xxx  x xxxxx"), None);
        assert_eq!(crack("11 111  1 11111"), None);
    }

    #[test]
    fn fails_on_spaced_single_taps() {
        // dCode's pseudo-code puts a space between taps, so every group is one tap. The first
        // spells H, E, L with an odd number of taps; the second spells T, E, A with an even
        // number, which would otherwise pair up as eight As.
        assert_eq!(crack(". .  . . .  .  . . . . .  . . .  ."), None);
        assert_eq!(crack(". . . .  . . . .  .  . . . . .  .  ."), None);
        assert_eq!(crack(". .  . .  . ."), None);
    }

    #[test]
    fn fails_on_other_characters_among_knocks() {
        assert_eq!(crack(".. ...  . .....  ... .  ,.. .  ... ...."), None);
        assert_eq!(crack(".. ...  . .....x"), None);
        assert_eq!(crack("... and then"), None);
    }

    #[test]
    fn fails_on_the_bench_miss_string() {
        assert_eq!(
            crack("T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV"),
            None
        );
    }

    #[test]
    fn fails_on_other_encodings() {
        // Base64, hex, A1Z26, decimal, binary, URL encoding, Braille
        assert_eq!(crack("aGVsbG8gd29ybGQ="), None);
        assert_eq!(crack("68656c6c6f20776f726c64"), None);
        assert_eq!(crack("8 5 12 12 15"), None);
        assert_eq!(crack("8-5-12-12-15"), None);
        assert_eq!(crack("104 101 108 108 111"), None);
        assert_eq!(crack("01101000 01100101 01101100"), None);
        assert_eq!(crack("%68%65%6C%6C%6F"), None);
        assert_eq!(crack("⠓⠑⠇⠇⠕"), None);
    }

    #[test]
    fn handles_panic_if_empty_string() {
        assert_eq!(crack(""), None);
    }

    #[test]
    fn handles_panic_if_whitespace() {
        assert_eq!(crack(" "), None);
        assert_eq!(crack(" \t\n\r\n "), None);
    }

    #[test]
    fn handles_panic_if_emoji() {
        assert_eq!(crack("😀"), None);
        assert_eq!(crack("😀😀 😀😀😀"), None);
    }

    #[test]
    fn handles_separators_only() {
        assert_eq!(crack("/"), None);
        assert_eq!(crack("| / |"), None);
        assert_eq!(crack(","), None);
    }

    #[test]
    fn fails_on_english() {
        assert_eq!(crack("hello world"), None);
        assert_eq!(crack("Hello, World!"), None);
        assert_eq!(crack("hello my name is panicky mc panic face!"), None);
        assert_eq!(crack("1, 2, 3, go"), None);
    }

    #[test]
    fn knocks_splits_groups_and_gaps() {
        let knocks: Vec<_> = Knocks::new(".. ...  ./|*", '.').collect();
        assert_eq!(
            knocks,
            [
                Some(Knock::Taps(2)),
                Some(Knock::Gap(Gap {
                    width: 1,
                    hard: false
                })),
                Some(Knock::Taps(3)),
                Some(Knock::Gap(Gap {
                    width: 2,
                    hard: false
                })),
                Some(Knock::Taps(1)),
                Some(Knock::Gap(Gap {
                    width: 0,
                    hard: true
                })),
                None,
            ]
        );
    }

    #[test]
    fn knocks_stops_after_a_failure() {
        let knocks: Vec<_> = Knocks::new("...... ..", '.').collect();
        assert_eq!(knocks, [None]);
        let knocks: Vec<_> = Knocks::new(".x..", '.').collect();
        assert_eq!(knocks, [Some(Knock::Taps(1)), None]);
    }

    #[test]
    fn narrowest_widths_keeps_three_distinct_widths() {
        let mut widths = NarrowestWidths::default();
        for width in [3, 1, 3, 1] {
            widths.insert(width);
        }
        assert_eq!(widths.third(), None);
        for width in [5, 2, 4] {
            widths.insert(width);
        }
        assert_eq!(widths.0, [Some(1), Some(2), Some(3)]);
        assert_eq!(widths.third(), Some(3));
    }

    #[test]
    fn crack_keeps_the_input() {
        let decoder = Decoder::<TapCodeDecoder>::new();
        let text = "2,3 1,5 3,1 3,1 3,4";
        let result = decoder.crack(text, &get_athena_checker());
        assert_eq!(result.encrypted_text, text);
        assert_eq!(result.decoder, "Tap Code");
    }

    #[test]
    fn is_registered() {
        // Exactly one decoder by that name runs in the search
        let decoders = get_decoder_by_name("Tap Code");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Tap Code");
        assert!(decoders.components[0].get_tags().contains(&"decoder"));
        assert!((decoders.components[0].get_popularity() - 0.3).abs() < f32::EPSILON);
        // Cached results name the decoder; reading them back looks it up here
        let decoder = DECODER_MAP
            .get("Tap Code")
            .expect("Tap Code should be in DECODER_MAP")
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "Tap Code");
    }
}
