//! Decode Unicode escape sequences: `\u00e9`, `\u{1F600}`, `\U0001F600`, `%u00E9` and
//! `U+00E9`.
//!
//! The text is scanned once. Every well-formed escape is replaced by its character and
//! everything else is copied unchanged, so partly escaped text such as `na\u00efve` decodes
//! too, and a `\u` that isn't followed by hex digits (`C:\users`) is left alone.
//!
//! | Form         | Used by                    | Hex digits                                  |
//! |--------------|----------------------------|---------------------------------------------|
//! | `\uXXXX`     | JSON, JavaScript, Java, C# | 4, a UTF-16 surrogate pair above U+FFFF     |
//! | `\u{X…}`     | JavaScript (ES2015), Rust  | 1 to 6                                      |
//! | `\UXXXXXXXX` | Python, C, C++             | 8                                           |
//! | `%uXXXX`     | JavaScript `escape()`      | 4, a UTF-16 surrogate pair above U+FFFF     |
//! | `U+XXXX`     | Unicode notation           | 4 to 6                                      |
//!
//! References:
//! * ECMA-262 string escapes: <https://tc39.es/ecma262/#prod-UnicodeEscapeSequence>
//! * JSON escapes and surrogate pairs, RFC 8259 section 7:
//!   <https://datatracker.ietf.org/doc/html/rfc8259#section-7>
//! * Python's `unicode_escape` codec:
//!   <https://docs.python.org/3/library/codecs.html#text-encodings>
//! * JavaScript `unescape()`: <https://tc39.es/ecma262/#sec-unescape-string>
//! * CyberChef "Unescape Unicode Characters":
//!   <https://gchq.github.io/CyberChef/#recipe=Unescape_Unicode_Characters('%5C%5Cu')>

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The Unicode escape decoder, call:
/// `let unicode_escape_decoder = Decoder::<UnicodeEscapeDecoder>::new()` to create a new instance
/// And then call:
/// `result = unicode_escape_decoder.crack(input)` to decode Unicode escape sequences
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::unicode_escape_decoder::UnicodeEscapeDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decoder = Decoder::<UnicodeEscapeDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decoder
///     .crack(r"\u0043\u0061\u0066\u00E9\u0020\u2615", &checker)
///     .unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "Café ☕");
/// ```
pub struct UnicodeEscapeDecoder;

impl Crack for Decoder<UnicodeEscapeDecoder> {
    fn new() -> Decoder<UnicodeEscapeDecoder> {
        Decoder {
            name: "Unicode Escapes",
            description: "Unicode escape sequences write each character as its code point in hexadecimal: \\u00E9 (JSON, JavaScript, Java and C#, with UTF-16 surrogate pairs above U+FFFF), \\u{1F600} (JavaScript and Rust), \\U0001F600 (Python and C), %u00E9 (JavaScript escape()) and U+00E9 (Unicode notation).",
            link: "https://en.wikipedia.org/wiki/Escape_sequences_in_C#Universal_character_names",
            tags: vec!["unicode_escape", "unicode", "escape", "decoder"],
            popularity: 0.4,
            phantom: std::marker::PhantomData,
        }
    }

    /// Replaces every escape in `text` with its character (see the module docs for the
    /// forms) and runs the checker on the result.
    ///
    /// Fails unless at least one escape was replaced. Also fails if an escape is not a
    /// character (a lone surrogate, or above U+10FFFF) or the result has control
    /// characters other than tab, carriage return and line feed.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Unicode escapes with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        // One pass over the bytes that rejects almost every input the search tries
        if !has_escape_marker(text) {
            trace!("No Unicode escape marker in text");
            return results;
        }

        let Some(decoded_text) = decode_unicode_escapes(text) else {
            debug!("Failed to decode Unicode escapes: none found, or one is not a character");
            return results;
        };

        if has_unexpected_control_character(&decoded_text) {
            debug!(
                "Failed to decode Unicode escapes: {:?} has control characters",
                decoded_text
            );
            return results;
        }

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Unicode escapes because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);

        results.update_checker(&checker_result);

        results
    }
    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// One escape sequence, as found at some position in the text
struct Escape {
    /// The escaped number: a code point, or a UTF-16 code unit for `\uXXXX` and `%uXXXX`
    value: u32,
    /// Length of the whole escape in bytes, prefix included
    len: usize,
    /// Whether this is a 4 digit `\uXXXX` or `%uXXXX` escape. Only these write UTF-16
    /// code units, so only these can hold half of a surrogate pair.
    utf16: bool,
}

/// Whether `text` contains `\u`, `\U`, `%u`, `%U` or `U+`, one of which starts every escape
fn has_escape_marker(text: &str) -> bool {
    let bytes = text.as_bytes();
    if bytes.len() < 2 {
        return false;
    }
    // This runs on every text the search tries. Checking each pair of neighbouring bytes
    // with no early exit inside a 64 pair chunk lets the compiler vectorise the loop,
    // which is about 10 times faster on long texts than stopping at the first match.
    bytes[..bytes.len() - 1]
        .chunks(64)
        .zip(bytes[1..].chunks(64))
        .any(|(firsts, seconds)| {
            firsts
                .iter()
                .zip(seconds)
                .fold(false, |found, (&first, &second)| {
                    found | is_escape_marker(first, second)
                })
        })
}

/// Whether two neighbouring bytes are `\u`, `\U`, `%u`, `%U` or `U+`. Written without
/// branches for [`has_escape_marker`]; `| 0x20` lowercases an ASCII `U`.
fn is_escape_marker(first: u8, second: u8) -> bool {
    (((first == b'\\') | (first == b'%')) & ((second | 0x20) == b'u'))
        | ((first == b'U') & (second == b'+'))
}

/// Decodes `text`, or returns `None` if it has no escape or an escape is not a character
fn decode_unicode_escapes(text: &str) -> Option<String> {
    decode_code_point_list(text).or_else(|| decode_escapes(text))
}

/// Decodes text made only of `U+XXXX` code points separated by whitespace or commas, such
/// as `U+0048 U+0069`. Each one is a whole character (a space is `U+0020`), so the
/// separators are dropped. CyberChef keeps them and gives `H i`.
///
/// Returns `None` if the text has anything else in it.
fn decode_code_point_list(text: &str) -> Option<String> {
    let mut decoded = String::new();
    for token in text
        .split(|c: char| c.is_whitespace() || c == ',')
        .filter(|token| !token.is_empty())
    {
        let digits = token.strip_prefix("U+")?.as_bytes();
        if !(4..=6).contains(&digits.len()) || hex_digit_count(digits, 6) != digits.len() {
            return None;
        }
        decoded.push(char::from_u32(hex_value(digits))?);
    }
    (!decoded.is_empty()).then_some(decoded)
}

/// Replaces every well-formed escape in `text` with its character and copies the rest
/// unchanged.
///
/// Returns `None` when nothing was replaced, or when an escape does not encode a
/// character: a lone UTF-16 surrogate, or a value above U+10FFFF.
fn decode_escapes(text: &str) -> Option<String> {
    let bytes = text.as_bytes();
    let mut decoded = String::with_capacity(text.len());
    let mut replaced_any = false;
    // Everything before this byte offset has been written to `decoded`
    let mut copied_up_to = 0;
    let mut i = 0;

    while i < bytes.len() {
        let Some(escape) = parse_escape(&bytes[i..]) else {
            i += 1;
            continue;
        };
        let (character, len) = escape_to_char(&escape, &bytes[i + escape.len..])?;
        // An escape starts and ends with an ASCII byte, so both offsets are char boundaries
        decoded.push_str(&text[copied_up_to..i]);
        decoded.push(character);
        replaced_any = true;
        i += len;
        copied_up_to = i;
    }

    if !replaced_any {
        return None;
    }
    decoded.push_str(&text[copied_up_to..]);
    Some(decoded)
}

/// The character `escape` encodes and the number of bytes used for it. A high surrogate
/// is combined with the low surrogate escape at the start of `after`.
fn escape_to_char(escape: &Escape, after: &[u8]) -> Option<(char, usize)> {
    if escape.utf16 && (0xD800..=0xDBFF).contains(&escape.value) {
        let low = parse_escape(after)
            .filter(|low| low.utf16 && (0xDC00..=0xDFFF).contains(&low.value))?;
        let code_point = 0x10000 + ((escape.value - 0xD800) << 10) + (low.value - 0xDC00);
        return char::from_u32(code_point).map(|c| (c, escape.len + low.len));
    }
    // Rejects lone low surrogates and values above U+10FFFF
    char::from_u32(escape.value).map(|c| (c, escape.len))
}

/// Parses the escape at the start of `bytes`, if there is a well-formed one there
fn parse_escape(bytes: &[u8]) -> Option<Escape> {
    match bytes {
        [b'\\', b'u', b'{', rest @ ..] => {
            let digits = hex_digit_count(rest, 7);
            ((1..=6).contains(&digits) && rest.get(digits) == Some(&b'}')).then(|| Escape {
                value: hex_value(&rest[..digits]),
                len: digits + 4,
                utf16: false,
            })
        }
        [b'\\', b'u', rest @ ..] | [b'%', b'u' | b'U', rest @ ..] => {
            (hex_digit_count(rest, 4) == 4).then(|| Escape {
                value: hex_value(&rest[..4]),
                len: 6,
                utf16: true,
            })
        }
        [b'\\', b'U', rest @ ..] => (hex_digit_count(rest, 8) == 8).then(|| Escape {
            value: hex_value(&rest[..8]),
            len: 10,
            utf16: false,
        }),
        [b'U', b'+', rest @ ..] => {
            let digits = hex_digit_count(rest, 6);
            (digits >= 4).then(|| Escape {
                value: hex_value(&rest[..digits]),
                len: digits + 2,
                utf16: false,
            })
        }
        _ => None,
    }
}

/// Number of ASCII hex digits at the start of `bytes`, counting at most `max`
fn hex_digit_count(bytes: &[u8], max: usize) -> usize {
    bytes
        .iter()
        .take(max)
        .take_while(|byte| byte.is_ascii_hexdigit())
        .count()
}

/// The value of up to 8 ASCII hex digits
fn hex_value(digits: &[u8]) -> u32 {
    digits.iter().fold(0, |value, &digit| {
        (value << 4) | char::from(digit).to_digit(16).unwrap_or(0)
    })
}

/// Whether `text` has a control character other than tab, carriage return or line feed.
/// Text whose escapes decode to one, such as `\u0000`, is not plaintext.
fn has_unexpected_control_character(text: &str) -> bool {
    text.chars()
        .any(|c| c.is_control() && !matches!(c, '\t' | '\r' | '\n'))
}

#[cfg(test)]
mod tests {
    use super::{has_escape_marker, UnicodeEscapeDecoder};
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::{
            crack_results::CrackResult,
            interface::{Crack, Decoder},
        },
        filtration_system::get_decoder_by_name,
    };

    // The comment on each test says which reference implementations give the same output:
    // * CyberChef "Unescape Unicode Characters" (UnescapeUnicodeCharacters.mjs on master):
    //   one prefix per run, case-insensitive, 4 hex digits after \u and %u, 4 to 6 after U+
    // * JavaScript (Node 22): JSON.parse for \u, unescape() for %u, string literals for \u{}
    // * Python 3.9: codecs.decode(text, "unicode_escape") for \u and \U

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    // helper for tests: the decoded candidate, if the decoder returned one
    fn decode(text: &str) -> Option<String> {
        Decoder::<UnicodeEscapeDecoder>::new()
            .crack(text, &get_athena_checker())
            .unencrypted_text
            .and_then(|candidates| candidates.into_iter().next())
    }

    #[test]
    fn unicode_escape_decodes_issue_example() {
        // Issue #940. CyberChef (\u), JSON.parse and Python agree.
        // Athena does not accept "Café ☕" as plaintext, so check the candidate itself.
        assert_eq!(
            decode(r"\u0043\u0061\u0066\u00E9\u0020\u2615").as_deref(),
            Some("Café ☕")
        );
    }

    #[test]
    fn unicode_escape_decodes_partly_escaped_lowercase_text() {
        // CyberChef (\u), JSON.parse and Python agree
        assert_eq!(decode(r"caf\u00e9 \u2615").as_deref(), Some("café ☕")); // codespell:ignore caf
    }

    #[test]
    fn unicode_escape_decodes_percent_u() {
        // Issue #940. CyberChef (%u) and unescape() agree.
        assert_eq!(
            decode("%u0043%u0061%u0066%u00E9%u0020%u2615").as_deref(),
            Some("Café ☕")
        );
        // CyberChef (%u) agrees; unescape() only reads a lowercase %u
        assert_eq!(decode("%U0043%U0061%U0066%U00E9").as_deref(), Some("Café"));
    }

    #[test]
    fn unicode_escape_drops_separators_between_code_points() {
        // Issue #940. Deliberately unlike CyberChef (U+), which keeps the separators and
        // gives "C a f é   ☕" and "H, i,!\n": each U+ token is a whole character, and
        // the space is already written as U+0020.
        assert_eq!(
            decode("U+0043 U+0061 U+0066 U+00E9 U+0020 U+2615").as_deref(),
            Some("Café ☕")
        );
        assert_eq!(decode("U+0048, U+0069,U+0021\n").as_deref(), Some("Hi!"));
    }

    #[test]
    fn unicode_escape_keeps_text_around_code_points() {
        // Not only U+ tokens, so the separators stay. CyberChef (U+) agrees.
        assert_eq!(decode("say U+0048 U+0069").as_deref(), Some("say H i"));
    }

    #[test]
    fn unicode_escape_decodes_code_points_above_the_bmp() {
        // CyberChef (U+) agrees
        assert_eq!(decode("U+1F600").as_deref(), Some("😀"));
        // Python agrees. CyberChef (\u) reads 4 digits: U+0001, then "F600".
        assert_eq!(decode(r"\U0001F600").as_deref(), Some("😀"));
        // JavaScript string literals agree. CyberChef leaves braces alone; Python rejects them.
        assert_eq!(decode(r"\u{1F600}").as_deref(), Some("😀"));
        assert_eq!(decode(r"\u{48}\u{69}").as_deref(), Some("Hi"));
    }

    #[test]
    fn unicode_escape_combines_surrogate_pairs() {
        // CyberChef (\u) and JSON.parse agree; Python leaves two lone surrogates
        assert_eq!(
            decode(r"\ud83d\ude00 \u0068\u0069").as_deref(),
            Some("😀 hi")
        );
        // CyberChef (%u) and unescape() agree
        assert_eq!(decode("%uD83D%uDE00").as_deref(), Some("😀"));
        // A pair split across both forms; no reference reads both prefixes at once
        assert_eq!(decode(r"\uD83D%uDE00").as_deref(), Some("😀"));
    }

    #[test]
    fn unicode_escape_accepts_upper_and_lower_case_hex() {
        // Each form on its own agrees with the references above
        assert_eq!(
            decode(r"\u00e9\u00E9%u00e9%u00E9\u{1f600}\u{1F600}\U0001f600").as_deref(),
            Some("éééé😀😀😀")
        );
    }

    #[test]
    fn unicode_escape_decodes_mixed_forms() {
        // No reference reads all five forms at once
        assert_eq!(
            decode(r"\u0048%u0065\u{6c}\U0000006CU+006F").as_deref(),
            Some("Hello")
        );
    }

    #[test]
    fn unicode_escape_keeps_non_ascii_text_around_escapes() {
        // CyberChef (\u) and JSON.parse agree. Python reads non-ASCII input as Latin-1.
        assert_eq!(decode(r"日本\u8a9e é\u0041").as_deref(), Some("日本語 éA"));
    }

    #[test]
    fn unicode_escape_allows_tabs_and_newlines() {
        // CyberChef (\u), JSON.parse and Python agree
        assert_eq!(
            decode(r"one\u000atwo\u0009three\u000d").as_deref(),
            Some("one\ntwo\tthree\r")
        );
    }

    #[test]
    fn unicode_escape_copies_malformed_escapes_unchanged() {
        // CyberChef (\u) agrees, except that it reads \U0001F60 as U+0001 then "F60".
        // JSON.parse and Python reject the whole string.
        assert_eq!(
            decode(r"\u12 \uZZZZ U+123 \U0001F60 \u{} \u{1234567} \u{12 \u0041").as_deref(),
            Some(r"\u12 \uZZZZ U+123 \U0001F60 \u{} \u{1234567} \u{12 A")
        );
    }

    #[test]
    fn unicode_escape_hello_world_is_found_by_athena() {
        // CyberChef (\u), JSON.parse and Python agree
        let result = Decoder::<UnicodeEscapeDecoder>::new().crack(
            r"\u0048\u0065\u006C\u006C\u006F\u002C\u0020\u0057\u006F\u0072\u006C\u0064\u0021",
            &get_athena_checker(),
        );
        assert_eq!(result.unencrypted_text.unwrap()[0], "Hello, World!");
        assert!(result.success);
    }

    #[test]
    fn unicode_escape_percent_u_sentence_is_found_by_athena() {
        // Made with CyberChef "Escape Unicode Characters" (prefix %u, encode all chars).
        // CyberChef (%u) and unescape() agree.
        let result = Decoder::<UnicodeEscapeDecoder>::new().crack(
            "%u0054%u0068%u0065%u0020%u0071%u0075%u0069%u0063%u006B%u0020%u0062%u0072%u006F%u0077%u006E%u0020%u0066%u006F%u0078%u0020%u006A%u0075%u006D%u0070%u0073%u0020%u006F%u0076%u0065%u0072%u0020%u0074%u0068%u0065%u0020%u006C%u0061%u007A%u0079%u0020%u0064%u006F%u0067",
            &get_athena_checker(),
        );
        assert_eq!(
            result.unencrypted_text.unwrap()[0],
            "The quick brown fox jumps over the lazy dog"
        );
        assert!(result.success);
    }

    #[test]
    fn unicode_escape_fails_without_a_well_formed_escape() {
        // CyberChef returns these unchanged, apart from reading \U0001F60 as U+0001 then
        // "F60". JSON.parse and Python reject the ones with a backslash.
        for text in [
            r"C:\users\bob",
            r"\u12",
            r"\uZZZZ",
            "U+123",
            r"\U0001F60",
            r"\u{1F600",
            r"\u{1234567}",
        ] {
            assert_eq!(decode(text), None, "{text}");
        }
    }

    #[test]
    fn unicode_escape_fails_on_lone_surrogates() {
        // JavaScript and Python strings can hold a lone surrogate; a Rust String cannot
        for text in [
            r"\ud83d",
            r"\ude00",
            "%uD83D",
            r"\ud83d\u0041",
            r"\ud83d \ude00",
            // Only \uXXXX and %uXXXX write UTF-16 code units
            r"\ud83d\u{DE00}",
            r"\u{D83D}",
            r"\U0000D83D",
            "U+D83D",
            // One bad escape fails the whole text
            r"\u0048\u0069\ud83d",
        ] {
            assert_eq!(decode(text), None, "{text}");
        }
    }

    #[test]
    fn unicode_escape_fails_above_u10ffff() {
        // JavaScript rejects \u{110000} and Python rejects \U00110000. CyberChef (U+) wraps
        // U+110000 around to U+10000.
        for text in [r"\u{110000}", "U+110000", r"\U00110000", r"\UFFFFFFFF"] {
            assert_eq!(decode(text), None, "{text}");
        }
    }

    #[test]
    fn unicode_escape_fails_on_control_characters() {
        // The references decode these to control characters, which are not plaintext.
        // \u0000 is NUL, ^@ in caret notation; the text \^@ itself has no escape at all.
        for text in [
            r"\u0000",
            r"\^@",
            r"\u0007",
            r"\u001b[31mred",
            "%u007F",
            "U+0085",
        ] {
            assert_eq!(decode(text), None, "{text}");
        }
    }

    #[test]
    fn unicode_escape_handles_markers_at_the_end_of_the_text() {
        for text in [r"abc\", r"abc\u", "abc%u", "abcU+", r"\u{", "%", r"\", "U"] {
            assert_eq!(decode(text), None, "{text}");
        }
    }

    #[test]
    fn unicode_escape_handles_panics() {
        // This tests if the decoder can handle panics
        // It should return None
        let result = Decoder::<UnicodeEscapeDecoder>::new()
            .crack(
                "hello my name is panicky mc panic face!",
                &get_athena_checker(),
            )
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn unicode_escape_handles_panic_if_empty_string() {
        // This tests if the decoder can handle an empty string
        // It should return None
        let result = Decoder::<UnicodeEscapeDecoder>::new()
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn unicode_escape_handles_panic_if_emoji() {
        // This tests if the decoder can handle an emoji
        // It should return None
        let result = Decoder::<UnicodeEscapeDecoder>::new()
            .crack("😀", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn unicode_escape_plain_english_is_not_decoded() {
        let result =
            Decoder::<UnicodeEscapeDecoder>::new().crack("hello world", &get_athena_checker());
        assert!(result.unencrypted_text.is_none());
        assert!(!result.success);
    }

    // helper for tests: the obvious way to write has_escape_marker
    fn has_escape_marker_naive(text: &str) -> bool {
        text.as_bytes()
            .windows(2)
            .any(|pair| matches!(pair, [b'\\' | b'%', b'u' | b'U'] | [b'U', b'+']))
    }

    #[test]
    fn unicode_escape_marker_check_agrees_with_the_naive_check() {
        // Every text of 1 to 6 characters made of marker parts and a filler
        let alphabet = ['\\', '%', 'u', 'U', '+', 'x'];
        let mut texts = vec![String::new()];
        for _ in 0..6 {
            texts = texts
                .iter()
                .flat_map(|text| alphabet.iter().map(move |c| format!("{text}{c}")))
                .collect();
            for text in &texts {
                assert_eq!(
                    has_escape_marker(text),
                    has_escape_marker_naive(text),
                    "{text:?}"
                );
            }
        }
    }

    #[test]
    fn unicode_escape_marker_check_finds_markers_at_any_offset() {
        // has_escape_marker works in chunks of 64; a marker can straddle two of them
        for marker in [r"\u", r"\U", "%u", "%U", "U+"] {
            for filler in ["x", "é"] {
                for count in 0..200 {
                    let text = format!("{}{marker}{}", filler.repeat(count), "x".repeat(count % 3));
                    assert!(has_escape_marker(&text), "{marker} after {count} {filler}");
                }
            }
        }
        assert!(!has_escape_marker(&r"x\x%xU-u+\ +U%+é".repeat(20)));
    }

    #[test]
    fn unicode_escape_is_registered() {
        let decoders = get_decoder_by_name("Unicode Escapes");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Unicode Escapes");
    }

    #[test]
    fn unicode_escape_crack_result_round_trips_through_json() {
        // The cache stores paths as JSON and finds the decoder again through DECODER_MAP
        let decoder = Decoder::<UnicodeEscapeDecoder>::new();
        let json = CrackResult::new(&decoder, r"\u0041".to_string())
            .get_json()
            .unwrap();
        let crack_result: CrackResult = serde_json::from_str(&json).unwrap();
        assert_eq!(crack_result.decoder, "Unicode Escapes");
        assert_eq!(crack_result.link, decoder.link);
    }
}
