//! Decode Unicode "fancy text": letters and digits written with look-alike Unicode
//! characters, as the "fancy font" generators for social media bios and chat write them.
//! Every fancy character stands for one ASCII character, so decoding is a table lookup.
//! The table covers:
//! * Mathematical Alphanumeric Symbols (U+1D400 to U+1D7FF): bold `𝐡𝐞𝐥𝐥𝐨`, italic, bold
//!   italic, script, bold script, fraktur, double-struck `𝕙𝕖𝕝𝕝𝕠`, bold fraktur, sans-serif
//!   and its bold, italic and bold italic, monospace `𝚑𝚎𝚕𝚕𝚘`, and their digits. The
//!   letters the block leaves out are in Letterlike Symbols (`ℎ`, `ℋ`, `ℯ`, `ℌ`, `ℂ` and
//!   so on), which is where generators take them from.
//! * Fullwidth forms `ｈｅｌｌｏ` (U+FF01 to U+FF5E) and the ideographic space U+3000.
//! * Circled `ⓗⓔⓛⓛⓞ`, parenthesized `⒣⒠⒧⒧⒪`, squared `🄷🄴🄻🄻🄾`, negative circled
//!   `🅗🅔🅛🅛🅞` and negative squared `🅷🅴🅻🅻🅾` letters, regional indicators `🇭🇪🇱🇱🇴`, and
//!   the circled, parenthesized and dingbat digits 0 to 9 (`①`, `⑴`, `⒈`, `❶`, `➀`, `➊`).
//! * Small capitals `ʜᴇʟʟᴏ` and superscript letters `ʰᵉˡˡᵒ`, and superscript and subscript
//!   digits except `¹`, `²` and `³`, which ordinary text uses (`5 m²`).
//! * The variation selectors and combining marks that keycap digits (`1️⃣`) and struck
//!   through, underlined or slashed text (`h̶e̶l̶l̶o̶`) add. These are removed.
//!
//! Case is kept where the fancy alphabet has both cases. Squared, negative circled and
//! negative squared letters and regional indicators only exist as capitals, and small
//! capitals are written as lower case.
//!
//! Wherever Unicode's NFKC normalisation turns one of these characters into a single
//! ASCII character, the table gives the same one. The table is hand-written for the rest:
//! NFKC leaves small capitals, negative circled and squared letters, regional indicators
//! and the removed marks alone, and turns `⒜` into `(a)`. Unlike NFKC, it also leaves
//! every other character alone, so ligatures, CJK compatibility forms and accents are
//! kept: `𝐡𝐞𝐥𝐥𝐨 café` is `hello café`.
//!
//! To keep ordinary text in other scripts from being decoded (`北京大学`, `naïve résumé`,
//! `5 m²`, `你好！`), the text has to have at least two fancy characters, and at least twice
//! as many fancy characters as other non-ASCII ones.
//!
//! Not decoded: upside-down text, Zalgo text, multi-digit enclosed numbers like `⑩`,
//! ligatures like `ﬁ`, Roman numerals, and "fonts" made of Greek or Cyrillic look-alikes
//! (`ђєℓℓσ`).
//!
//! References: <https://en.wikipedia.org/wiki/Mathematical_Alphanumeric_Symbols>,
//! <https://en.wikipedia.org/wiki/Enclosed_Alphanumerics>,
//! <https://en.wikipedia.org/wiki/Enclosed_Alphanumeric_Supplement>,
//! <https://en.wikipedia.org/wiki/Halfwidth_and_Fullwidth_Forms_(Unicode_block)> and
//! Unicode's NFKC, <https://unicode.org/reports/tr15/>.
//!
//! Call unicode_fancy_text_decoder.crack to use. It returns a `CrackResult` whose
//! `unencrypted_text` is `None` when the input isn't fancy text.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The Unicode Fancy Text decoder, call:
/// `let fancy_text_decoder = Decoder::<UnicodeFancyTextDecoder>::new()` to create a new
/// instance
/// And then call:
/// `result = fancy_text_decoder.crack(input)` to decode fancy text
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::unicode_fancy_text_decoder::UnicodeFancyTextDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_fancy_text = Decoder::<UnicodeFancyTextDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // Mathematical bold
/// let result = decode_fancy_text.crack("𝐡𝐞𝐥𝐥𝐨 𝐰𝐨𝐫𝐥𝐝", &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hello world");
///
/// // Fullwidth and circled letters
/// let result = decode_fancy_text.crack("ｈｅｌｌｏ ｗｏｒｌｄ", &checker).unencrypted_text;
/// assert_eq!(result.unwrap()[0], "hello world");
/// let result = decode_fancy_text.crack("ⓗⓔⓛⓛⓞ ⓦⓞⓡⓛⓓ", &checker).unencrypted_text;
/// assert_eq!(result.unwrap()[0], "hello world");
///
/// // Ordinary text isn't fancy text
/// let result = decode_fancy_text.crack("naïve résumé", &checker).unencrypted_text;
/// assert!(result.is_none());
/// ```
pub struct UnicodeFancyTextDecoder;

/// Fewer fancy characters than this are more likely a stray symbol, like `①` or `Ａ`.
const MIN_FANCY: usize = 2;

impl Crack for Decoder<UnicodeFancyTextDecoder> {
    fn new() -> Decoder<UnicodeFancyTextDecoder> {
        Decoder {
            name: "Unicode Fancy Text",
            description: "Unicode look-alike 'fonts' (mathematical bold/italic/script/double-struck, fullwidth, circled, squared, small caps, superscript, regional indicators) mapped back to ASCII",
            link: "https://en.wikipedia.org/wiki/Mathematical_Alphanumeric_Symbols",
            tags: vec![
                "unicode",
                "fancy_text",
                "fullwidth",
                "homoglyph",
                "substitution",
                "decoder",
            ],
            // Common in social media and in CTF "weird font" tasks. ASCII input, almost
            // every node of a search, is rejected after one `is_ascii` pass.
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes `text` as fancy text and checks the result with `checker`.
    /// `unencrypted_text` is `None` when `text` isn't fancy text.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Unicode Fancy Text with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_fancy_text(text) else {
            debug!("Failed to decode Unicode Fancy Text because the text isn't fancy text");
            return results;
        };
        trace!("Decoded text for Unicode Fancy Text: {:?}", decoded_text);

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Unicode Fancy Text because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// What one character of the input is.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Kind {
    /// ASCII, kept as it is
    Ascii,
    /// A fancy character, written as this ASCII character
    Fancy(char),
    /// A variation selector or combining mark that fancy text adds, removed
    Stripped,
    /// Any other non-ASCII character, kept as it is
    Other,
}

/// What `c` is.
fn kind(c: char) -> Kind {
    if c.is_ascii() {
        Kind::Ascii
    } else if let Some(ascii) = fancy_to_ascii(c) {
        Kind::Fancy(ascii)
    } else if is_stripped(c) {
        Kind::Stripped
    } else {
        Kind::Other
    }
}

/// Decodes fancy text to ASCII, keeping other characters as they are, or returns `None`
/// if `text` isn't fancy text.
fn decode_fancy_text(text: &str) -> Option<String> {
    // Rejects almost every text a search sees in one pass, without looking at characters
    if text.is_ascii() {
        return None;
    }

    // Pass 1 counts without allocating, so text that isn't fancy costs one more pass
    let mut fancy = 0;
    let mut other = 0;
    for c in text.chars() {
        match kind(c) {
            Kind::Ascii => {}
            Kind::Fancy(_) | Kind::Stripped => fancy += 1,
            Kind::Other => other += 1,
        }
    }
    if fancy < MIN_FANCY || fancy < 2 * other {
        return None;
    }

    // Pass 2 writes the text. Every fancy character is longer in UTF-8 than the ASCII
    // character it becomes, so the text never needs more room than the input.
    let mut decoded = String::with_capacity(text.len());
    for c in text.chars() {
        match kind(c) {
            Kind::Ascii | Kind::Other => decoded.push(c),
            Kind::Fancy(ascii) => decoded.push(ascii),
            Kind::Stripped => {}
        }
    }
    // Fancy characters never decode to control characters, so these were in the input
    if decoded
        .chars()
        .any(|c| c.is_control() && !matches!(c, '\t' | '\r' | '\n'))
    {
        return None;
    }
    Some(decoded)
}

/// The character `n` places after `first`.
fn nth(first: char, n: u32) -> Option<char> {
    char::from_u32(u32::from(first) + n)
}

/// The ASCII character the fancy character `c` stands for, or `None` if `c` isn't one.
///
/// Checked against Python 3.9's `unicodedata` (Unicode 13.0): for every code point here
/// whose NFKC normalisation is one ASCII character, it is the same character.
fn fancy_to_ascii(c: char) -> Option<char> {
    let cp = u32::from(c);
    match c {
        // Mathematical Alphanumeric Symbols: 13 styles of A to Z then a to z (bold, italic,
        // bold italic, script, bold script, fraktur, double-struck, bold fraktur,
        // sans-serif, sans-serif bold, sans-serif italic, sans-serif bold italic,
        // monospace). Its 24 unassigned code points, such as U+1D455 where italic h would
        // be, decode by the same formula: some generators write them instead of the
        // Letterlike Symbols below.
        '\u{1D400}'..='\u{1D6A3}' => {
            let position = (cp - 0x1D400) % 52;
            if position < 26 {
                nth('A', position)
            } else {
                nth('a', position - 26)
            }
        }
        '\u{1D6A4}' => Some('i'), // 𝚤 italic dotless i
        '\u{1D6A5}' => Some('j'), // 𝚥 italic dotless j
        // Mathematical digits: bold, double-struck, sans-serif, sans-serif bold, monospace
        '\u{1D7CE}'..='\u{1D7FF}' => nth('0', (cp - 0x1D7CE) % 10),

        // Letterlike Symbols that stand in for the mathematical letters Unicode left out
        '\u{210E}' => Some('h'), // ℎ italic h (Planck constant)
        '\u{212C}' => Some('B'), // ℬ script B
        '\u{2130}' => Some('E'), // ℰ script E
        '\u{2131}' => Some('F'), // ℱ script F
        '\u{210B}' => Some('H'), // ℋ script H
        '\u{2110}' => Some('I'), // ℐ script I
        '\u{2112}' => Some('L'), // ℒ script L
        '\u{2133}' => Some('M'), // ℳ script M
        '\u{211B}' => Some('R'), // ℛ script R
        '\u{212F}' => Some('e'), // ℯ script e
        '\u{210A}' => Some('g'), // ℊ script g
        '\u{2134}' => Some('o'), // ℴ script o
        '\u{212D}' => Some('C'), // ℭ fraktur C
        '\u{210C}' => Some('H'), // ℌ fraktur H
        '\u{2111}' => Some('I'), // ℑ fraktur I
        '\u{211C}' => Some('R'), // ℜ fraktur R
        '\u{2128}' => Some('Z'), // ℨ fraktur Z
        '\u{2102}' => Some('C'), // ℂ double-struck C
        '\u{210D}' => Some('H'), // ℍ double-struck H
        '\u{2115}' => Some('N'), // ℕ double-struck N
        '\u{2119}' => Some('P'), // ℙ double-struck P
        '\u{211A}' => Some('Q'), // ℚ double-struck Q
        '\u{211D}' => Some('R'), // ℝ double-struck R
        '\u{2124}' => Some('Z'), // ℤ double-struck Z
        // Other Letterlike Symbols that generators use as letters
        '\u{2113}' => Some('l'), // ℓ script small l
        '\u{2139}' => Some('i'), // ℹ information source
        '\u{2145}' => Some('D'), // ⅅ double-struck italic D
        '\u{2146}' => Some('d'), // ⅆ double-struck italic d
        '\u{2147}' => Some('e'), // ⅇ double-struck italic e
        '\u{2148}' => Some('i'), // ⅈ double-struck italic i
        '\u{2149}' => Some('j'), // ⅉ double-struck italic j

        // Fullwidth forms of `!` to `~`, and the ideographic space
        '\u{FF01}'..='\u{FF5E}' => char::from_u32(cp - 0xFEE0),
        '\u{3000}' => Some(' '),

        // Enclosed Alphanumerics. ⒜ is (a) under NFKC; the letter is what it stands for.
        '\u{24B6}'..='\u{24CF}' => nth('A', cp - 0x24B6), // Ⓐ to Ⓩ
        '\u{24D0}'..='\u{24E9}' => nth('a', cp - 0x24D0), // ⓐ to ⓩ
        '\u{249C}'..='\u{24B5}' => nth('a', cp - 0x249C), // ⒜ to ⒵
        '\u{2460}'..='\u{2468}' => nth('1', cp - 0x2460), // ① to ⑨
        '\u{2474}'..='\u{247C}' => nth('1', cp - 0x2474), // ⑴ to ⑼
        '\u{2488}'..='\u{2490}' => nth('1', cp - 0x2488), // ⒈ to ⒐
        '\u{24EA}' => Some('0'),                          // ⓪
        '\u{24FF}' => Some('0'),                          // ⓿
        // Dingbats
        '\u{2776}'..='\u{277E}' => nth('1', cp - 0x2776), // ❶ to ❾
        '\u{2780}'..='\u{2788}' => nth('1', cp - 0x2780), // ➀ to ➈
        '\u{278A}'..='\u{2792}' => nth('1', cp - 0x278A), // ➊ to ➒
        // Enclosed Alphanumeric Supplement
        '\u{1F10B}' => Some('0'),                            // 🄋
        '\u{1F10C}' => Some('0'),                            // 🄌
        '\u{1F110}'..='\u{1F129}' => nth('A', cp - 0x1F110), // 🄐 to 🄩
        '\u{1F130}'..='\u{1F149}' => nth('A', cp - 0x1F130), // 🄰 to 🅉
        '\u{1F150}'..='\u{1F169}' => nth('A', cp - 0x1F150), // 🅐 to 🅩
        '\u{1F170}'..='\u{1F189}' => nth('A', cp - 0x1F170), // 🅰 to 🆉
        '\u{1F1E6}'..='\u{1F1FF}' => nth('A', cp - 0x1F1E6), // 🇦 to 🇿

        // Small capitals, as the generators write them; NFKC leaves them alone. There is
        // no small capital q or x: generators write ǫ (o with ogonek) for q, and x.
        '\u{1D00}' => Some('a'), // ᴀ
        '\u{0299}' => Some('b'), // ʙ
        '\u{1D04}' => Some('c'), // ᴄ
        '\u{1D05}' => Some('d'), // ᴅ
        '\u{1D07}' => Some('e'), // ᴇ
        '\u{A730}' => Some('f'), // ꜰ
        '\u{0262}' => Some('g'), // ɢ
        '\u{029C}' => Some('h'), // ʜ
        '\u{026A}' => Some('i'), // ɪ
        '\u{1D0A}' => Some('j'), // ᴊ
        '\u{1D0B}' => Some('k'), // ᴋ
        '\u{029F}' => Some('l'), // ʟ
        '\u{1D0D}' => Some('m'), // ᴍ
        '\u{0274}' => Some('n'), // ɴ
        '\u{1D0F}' => Some('o'), // ᴏ
        '\u{1D18}' => Some('p'), // ᴘ
        '\u{1D29}' => Some('p'), // ᴩ Greek small capital rho
        '\u{01EB}' => Some('q'), // ǫ
        '\u{0280}' => Some('r'), // ʀ
        '\u{A731}' => Some('s'), // ꜱ
        '\u{1D1B}' => Some('t'), // ᴛ
        '\u{1D1C}' => Some('u'), // ᴜ
        '\u{1D20}' => Some('v'), // ᴠ
        '\u{1D21}' => Some('w'), // ᴡ
        '\u{028F}' => Some('y'), // ʏ
        '\u{1D22}' => Some('z'), // ᴢ

        // Superscript letters. There is no superscript q.
        '\u{1D43}' => Some('a'), // ᵃ
        '\u{1D47}' => Some('b'), // ᵇ
        '\u{1D9C}' => Some('c'), // ᶜ
        '\u{1D48}' => Some('d'), // ᵈ
        '\u{1D49}' => Some('e'), // ᵉ
        '\u{1DA0}' => Some('f'), // ᶠ
        '\u{1D4D}' => Some('g'), // ᵍ
        '\u{02B0}' => Some('h'), // ʰ
        '\u{2071}' => Some('i'), // ⁱ
        '\u{02B2}' => Some('j'), // ʲ
        '\u{1D4F}' => Some('k'), // ᵏ
        '\u{02E1}' => Some('l'), // ˡ
        '\u{1D50}' => Some('m'), // ᵐ
        '\u{207F}' => Some('n'), // ⁿ
        '\u{1D52}' => Some('o'), // ᵒ
        '\u{1D56}' => Some('p'), // ᵖ
        '\u{02B3}' => Some('r'), // ʳ
        '\u{02E2}' => Some('s'), // ˢ
        '\u{1D57}' => Some('t'), // ᵗ
        '\u{1D58}' => Some('u'), // ᵘ
        '\u{1D5B}' => Some('v'), // ᵛ
        '\u{02B7}' => Some('w'), // ʷ
        '\u{02E3}' => Some('x'), // ˣ
        '\u{02B8}' => Some('y'), // ʸ
        '\u{1DBB}' => Some('z'), // ᶻ
        // Superscript and subscript digits. Not ¹ ² ³ (U+00B9, U+00B2, U+00B3), which
        // ordinary text uses: 5 m², 10³.
        '\u{2070}' => Some('0'),                          // ⁰
        '\u{2074}'..='\u{2079}' => nth('4', cp - 0x2074), // ⁴ to ⁹
        '\u{2080}'..='\u{2089}' => nth('0', cp - 0x2080), // ₀ to ₉

        _ => None,
    }
}

/// Whether `c` is a mark that fancy text adds to ASCII characters, and that decoding
/// removes: the emoji and text variation selectors, the enclosing combining marks of
/// keycaps (`1️⃣`) and the combining underlines and overlays of underlined, struck
/// through and slashed text (`h̲`, `h̶`, `h̷`).
fn is_stripped(c: char) -> bool {
    matches!(
        c,
        '\u{FE0E}' | '\u{FE0F}' | '\u{20DD}'..='\u{20E4}' | '\u{0332}'..='\u{0338}'
    )
}

#[cfg(test)]
mod tests {
    use super::{decode_fancy_text, fancy_to_ascii, is_stripped, UnicodeFancyTextDecoder};
    use crate::checkers::athena::Athena;
    use crate::checkers::checker_type::{Check, Checker};
    use crate::checkers::CheckerTypes;
    use crate::decoders::interface::{Crack, Decoder};
    use crate::decoders::{DecoderType, DECODER_MAP};
    use crate::filtration_system::{get_all_decoders, get_decoder_by_name};

    // Unless a test says otherwise, every vector's plaintext is what Python 3.9's
    // `unicodedata.normalize('NFKC', text)` and CyberChef 10.24's "Normalise Unicode"
    // (NFKC) give. The vectors NFKC doesn't decode (negative circled and squared letters,
    // regional indicators, parenthesized letters, small capitals and the removed marks)
    // were built from the code points in the Unicode charts linked in the module docs,
    // and decoded with a Python prototype of the table. The issue's vectors are at
    // https://github.com/bee-san/Ciphey/issues/971

    /// The pangram the vectors use
    const FOX: &str = "The quick brown fox jumps over the lazy dog";

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    // Runs the decoder with the Athena checker and returns the decoded text, if any
    fn crack(text: &str) -> Option<String> {
        let decoder = Decoder::<UnicodeFancyTextDecoder>::new();
        let result = decoder.crack(text, &get_athena_checker());
        if result.unencrypted_text.is_none() {
            assert!(!result.success, "{text:?} failed but was marked successful");
        }
        result.unencrypted_text.map(|texts| texts[0].clone())
    }

    // Asserts that the text decodes to `expected` and that Athena accepts it
    #[track_caller]
    fn assert_cracks(text: &str, expected: &str) {
        let decoder = Decoder::<UnicodeFancyTextDecoder>::new();
        let result = decoder.crack(text, &get_athena_checker());
        assert_eq!(
            result.unencrypted_text.as_deref(),
            Some(&[expected.to_string()][..]),
            "{text:?}"
        );
        assert!(result.success, "Athena should accept {expected:?}");
    }

    // Asserts that the text decodes to `expected`, whether or not Athena accepts it
    #[track_caller]
    fn assert_decodes(text: &str, expected: &str) {
        assert_eq!(crack(text).as_deref(), Some(expected), "{text:?}");
    }

    #[test]
    fn decodes_the_issue_examples() {
        // Mathematical bold, fullwidth and circled
        assert_cracks("𝐡𝐞𝐥𝐥𝐨 𝐰𝐨𝐫𝐥𝐝", "hello world");
        assert_cracks("ｈｅｌｌｏ ｗｏｒｌｄ", "hello world");
        assert_cracks("ⓗⓔⓛⓛⓞ ⓦⓞⓡⓛⓓ", "hello world");
    }

    #[test]
    fn decodes_italic_with_the_planck_constant_for_h() {
        // ℎ is U+210E: there is no mathematical italic small h
        assert_cracks("𝑇ℎ𝑒 𝑞𝑢𝑖𝑐𝑘 𝑏𝑟𝑜𝑤𝑛 𝑓𝑜𝑥 𝑗𝑢𝑚𝑝𝑠 𝑜𝑣𝑒𝑟 𝑡ℎ𝑒 𝑙𝑎𝑧𝑦 𝑑𝑜𝑔", FOX);
    }

    #[test]
    fn decodes_script_with_letterlike_symbols() {
        // ℋ ℯ ℴ are Letterlike Symbols, the rest mathematical script
        assert_cracks("ℋℯ𝓁𝓁ℴ, 𝒲ℴ𝓇𝓁𝒹!", "Hello, World!");
    }

    #[test]
    fn decodes_fraktur_with_letterlike_symbols() {
        // ℌ is U+210C, black-letter capital H
        assert_cracks("ℌ𝔢𝔩𝔩𝔬, 𝔚𝔬𝔯𝔩𝔡!", "Hello, World!");
    }

    #[test]
    fn decodes_double_struck() {
        assert_cracks("𝕋𝕙𝕖 𝕢𝕦𝕚𝕔𝕜 𝕓𝕣𝕠𝕨𝕟 𝕗𝕠𝕩 𝕛𝕦𝕞𝕡𝕤 𝕠𝕧𝕖𝕣 𝕥𝕙𝕖 𝕝𝕒𝕫𝕪 𝕕𝕠𝕘", FOX);
    }

    #[test]
    fn decodes_monospace() {
        assert_cracks("𝚃𝚑𝚎 𝚚𝚞𝚒𝚌𝚔 𝚋𝚛𝚘𝚠𝚗 𝚏𝚘𝚡 𝚓𝚞𝚖𝚙𝚜 𝚘𝚟𝚎𝚛 𝚝𝚑𝚎 𝚕𝚊𝚣𝚢 𝚍𝚘𝚐", FOX);
    }

    #[test]
    fn decodes_sans_serif_bold() {
        assert_cracks("𝗛𝗲𝗹𝗹𝗼, 𝗪𝗼𝗿𝗹𝗱!", "Hello, World!");
    }

    #[test]
    fn decodes_bold_italic_and_keeps_accented_letters() {
        // The é is an ordinary e with an acute accent, which stays
        assert_cracks("𝑴𝒆𝒆𝒕 𝒎𝒆 𝒂𝒕 𝒕𝒉𝒆 𝒄𝒂𝒇é 𝒂𝒕 𝒏𝒐𝒐𝒏", "Meet me at the café at noon");
    }

    #[test]
    fn decodes_fullwidth_punctuation_and_the_ideographic_space() {
        assert_cracks("Ｈｅｌｌｏ，　Ｗｏｒｌｄ！", "Hello, World!");
    }

    #[test]
    fn decodes_mathematical_digits() {
        // Athena doesn't take these for plaintext
        assert_decodes("𝐅𝐥𝐚𝐠 𝟐𝟎𝟐𝟒", "Flag 2024");
        assert_decodes("𝙲𝚃𝙵 𝟷𝟹𝟹𝟽", "CTF 1337");
    }

    #[test]
    fn decodes_circled_letters_in_both_cases() {
        assert_cracks("Ⓗⓔⓛⓛⓞ, Ⓦⓞⓡⓛⓓ!", "Hello, World!");
    }

    #[test]
    fn decodes_squared_letters_as_capitals() {
        assert_cracks("🄷🄴🄻🄻🄾, 🅆🄾🅁🄻🄳!", "HELLO, WORLD!");
    }

    #[test]
    fn decodes_negative_circled_letters_as_capitals() {
        // NFKC leaves these alone
        assert_cracks("🅗🅔🅛🅛🅞 🅦🅞🅡🅛🅓", "HELLO WORLD");
    }

    #[test]
    fn decodes_negative_squared_letters_as_capitals() {
        // NFKC leaves these alone
        assert_cracks(
            "🆃🅷🅴 🆀🆄🅸🅲🅺 🅱🆁🅾🆆🅽 🅵🅾🆇 🅹🆄🅼🅿🆂 🅾🆅🅴🆁 🆃🅷🅴 🅻🅰🆉🆈 🅳🅾🅶",
            "THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG",
        );
    }

    #[test]
    fn decodes_regional_indicators_as_capitals() {
        // NFKC leaves these alone
        assert_cracks("🇭🇪🇱🇱🇴 🇼🇴🇷🇱🇩", "HELLO WORLD");
    }

    #[test]
    fn decodes_parenthesized_letters_to_the_bare_letter() {
        // NFKC gives "(h)(e)(l)(l)(o) (w)(o)(r)(l)(d)"
        assert_cracks("⒣⒠⒧⒧⒪ ⒲⒪⒭⒧⒟", "hello world");
    }

    #[test]
    fn decodes_small_capitals_as_lower_case() {
        // NFKC leaves these alone. The generators write ǫ for q and keep x.
        assert_cracks("ʜᴇʟʟᴏ ᴡᴏʀʟᴅ", "hello world");
        assert_cracks("Tʜᴇ ǫᴜɪᴄᴋ ʙʀᴏᴡɴ ꜰᴏx ᴊᴜᴍᴩꜱ ᴏᴠᴇʀ ᴛʜᴇ ʟᴀᴢʏ ᴅᴏɢ", FOX);
    }

    #[test]
    fn decodes_superscript_letters() {
        assert_cracks("ʰᵉˡˡᵒ ʷᵒʳˡᵈ", "hello world");
    }

    #[test]
    fn removes_strikethrough() {
        // U+0336 after every character; NFKC leaves it alone
        assert_cracks("h̶e̶l̶l̶o̶ ̶w̶o̶r̶l̶d̶", "hello world");
    }

    #[test]
    fn removes_underlines_and_slashes() {
        assert_decodes("h\u{332}e\u{332}l\u{332}l\u{332}o\u{332}", "hello");
        assert_decodes("h\u{333}e\u{333}l\u{333}l\u{333}o\u{333}", "hello");
        assert_decodes("h\u{338}e\u{338}l\u{338}l\u{338}o\u{338}", "hello");
    }

    #[test]
    fn removes_keycaps() {
        // Digit, U+FE0F, U+20E3; NFKC leaves the marks alone
        assert_decodes("1️⃣2️⃣3️⃣", "123");
        assert_decodes("1\u{20E3}2\u{20E3}3\u{20E3}", "123");
    }

    #[test]
    fn decodes_mixed_text_and_keeps_other_characters() {
        assert_cracks("𝐡𝐞𝐥𝐥𝐨 café", "hello café");
        assert_decodes("ＡＢ北", "AB北");
    }

    #[test]
    fn decodes_fancy_words_in_ascii_text() {
        assert_cracks("hello 𝐰𝐨𝐫𝐥𝐝", "hello world");
    }

    #[test]
    fn decodes_the_unassigned_mathematical_code_points() {
        // U+1D455 is where italic h would be. NFKC leaves it alone, but some generators
        // write it instead of ℎ (U+210E).
        assert_decodes("\u{1D455}\u{1D452}\u{1D459}\u{1D459}\u{1D45C}", "hello");
    }

    #[test]
    fn decodes_every_mathematical_letter() {
        let alphabet: String = ('A'..='Z').chain('a'..='z').collect();
        for style in 0..13 {
            let first = 0x1D400 + style * 52;
            let decoded: String = (first..first + 52)
                .map(|cp| fancy_to_ascii(char::from_u32(cp).unwrap()).unwrap())
                .collect();
            assert_eq!(decoded, alphabet, "style {style} at U+{first:X}");
        }
        assert_eq!(fancy_to_ascii('\u{1D6A4}'), Some('i'));
        assert_eq!(fancy_to_ascii('\u{1D6A5}'), Some('j'));
    }

    #[test]
    fn letterlike_symbols_decode_like_the_letters_they_stand_in_for() {
        // The 24 code points Unicode left unassigned in Mathematical Alphanumeric Symbols,
        // and the Letterlike Symbols generators use instead (the charts' notes)
        let holes = [
            ('\u{1D455}', 'ℎ'),
            ('\u{1D49D}', 'ℬ'),
            ('\u{1D4A0}', 'ℰ'),
            ('\u{1D4A1}', 'ℱ'),
            ('\u{1D4A3}', 'ℋ'),
            ('\u{1D4A4}', 'ℐ'),
            ('\u{1D4A7}', 'ℒ'),
            ('\u{1D4A8}', 'ℳ'),
            ('\u{1D4AD}', 'ℛ'),
            ('\u{1D4BA}', 'ℯ'),
            ('\u{1D4BC}', 'ℊ'),
            ('\u{1D4C4}', 'ℴ'),
            ('\u{1D506}', 'ℭ'),
            ('\u{1D50B}', 'ℌ'),
            ('\u{1D50C}', 'ℑ'),
            ('\u{1D515}', 'ℜ'),
            ('\u{1D51D}', 'ℨ'),
            ('\u{1D53A}', 'ℂ'),
            ('\u{1D53F}', 'ℍ'),
            ('\u{1D545}', 'ℕ'),
            ('\u{1D547}', 'ℙ'),
            ('\u{1D548}', 'ℚ'),
            ('\u{1D549}', 'ℝ'),
            ('\u{1D551}', 'ℤ'),
        ];
        for (hole, letterlike) in holes {
            assert!(fancy_to_ascii(hole).is_some(), "{hole:?}");
            assert_eq!(
                fancy_to_ascii(hole),
                fancy_to_ascii(letterlike),
                "{letterlike}"
            );
        }
    }

    #[test]
    fn decodes_every_mathematical_digit() {
        let decoded: String = (0x1D7CE..=0x1D7FF)
            .map(|cp| fancy_to_ascii(char::from_u32(cp).unwrap()).unwrap())
            .collect();
        assert_eq!(decoded, "0123456789".repeat(5));
    }

    #[test]
    fn decodes_the_ends_of_every_block() {
        let ends = [
            ('\u{FF01}', '!'),
            ('\u{FF10}', '0'),
            ('\u{FF21}', 'A'),
            ('\u{FF41}', 'a'),
            ('\u{FF5E}', '~'),
            ('Ⓐ', 'A'),
            ('Ⓩ', 'Z'),
            ('ⓐ', 'a'),
            ('ⓩ', 'z'),
            ('⒜', 'a'),
            ('⒵', 'z'),
            ('①', '1'),
            ('⑨', '9'),
            ('⑴', '1'),
            ('⑼', '9'),
            ('⒈', '1'),
            ('⒐', '9'),
            ('⓪', '0'),
            ('⓿', '0'),
            ('❶', '1'),
            ('❾', '9'),
            ('➀', '1'),
            ('➈', '9'),
            ('➊', '1'),
            ('➒', '9'),
            ('🄋', '0'),
            ('🄌', '0'),
            ('🄐', 'A'),
            ('🄩', 'Z'),
            ('🄰', 'A'),
            ('🅉', 'Z'),
            ('🅐', 'A'),
            ('🅩', 'Z'),
            ('🅰', 'A'),
            ('🆉', 'Z'),
            ('🇦', 'A'),
            ('🇿', 'Z'),
            ('⁰', '0'),
            ('⁴', '4'),
            ('⁹', '9'),
            ('₀', '0'),
            ('₉', '9'),
        ];
        for (fancy, ascii) in ends {
            assert_eq!(fancy_to_ascii(fancy), Some(ascii), "{fancy}");
        }
    }

    #[test]
    fn leaves_the_neighbours_of_every_block_alone() {
        let neighbours = [
            // Greek mathematical letters, the code points around the Latin and digit
            // ranges, and the first unassigned one after the dotless j
            '\u{1D6A6}',
            '\u{1D6A8}',
            '\u{1D7CB}',
            '\u{1D7CD}',
            // Fullwidth: the code points around `!` to `~`, and halfwidth katakana
            '\u{FF00}',
            '\u{FF5F}',
            'ｱ',
            // Multi-digit enclosed numbers
            '⑩',
            '⑳',
            '⑽',
            '⒑',
            '⓫',
            '⓾',
            '❿',
            '➉',
            '➓',
            // Double circled digits
            '⓵',
            // Other enclosed symbols
            '🄪',
            '🄫',
            '🄀',
            '🅪',
            '🆊',
            '🆐',
            // Superscript ¹ ² ³, which ordinary text uses
            '¹',
            '²',
            '³',
            // Letterlike symbols that aren't letters
            '℃',
            '℗',
            '™',
            'Ω',
            // Ligatures, Roman numerals
            'ﬁ',
            'Ⅻ',
            // Real letters that look a bit like small capitals or superscripts
            'é',
            'ı',
            'ȷ',
            'ə',
            'ʊ',
            'ᵻ',
            // Braille, Cyrillic and Greek
            '⠓',
            'П',
            'σ',
        ];
        for c in neighbours {
            assert_eq!(fancy_to_ascii(c), None, "{c} (U+{:04X})", u32::from(c));
            assert!(!is_stripped(c), "{c} (U+{:04X})", u32::from(c));
        }
    }

    #[test]
    fn strips_only_the_marks_fancy_text_adds() {
        for c in ['\u{FE0E}', '\u{FE0F}', '\u{20DD}', '\u{20E3}', '\u{20E4}'] {
            assert!(is_stripped(c), "U+{:04X}", u32::from(c));
        }
        for c in '\u{0332}'..='\u{0338}' {
            assert!(is_stripped(c), "U+{:04X}", u32::from(c));
        }
        // Accents, the zero-width joiner and other variation selectors stay
        for c in [
            '\u{0301}', '\u{0331}', '\u{0339}', '\u{200D}', '\u{FE00}', '\u{20DC}',
        ] {
            assert!(!is_stripped(c), "U+{:04X}", u32::from(c));
            assert_eq!(fancy_to_ascii(c), None, "U+{:04X}", u32::from(c));
        }
    }

    #[test]
    fn decodes_to_ascii_only_from_the_table() {
        // Every character the table knows is non-ASCII and decodes to printable ASCII
        for c in '\0'..=char::MAX {
            if let Some(ascii) = fancy_to_ascii(c) {
                assert!(!c.is_ascii(), "{c:?}");
                assert!(
                    ascii.is_ascii_graphic() || ascii == ' ',
                    "U+{:04X} -> {ascii:?}",
                    u32::from(c)
                );
            }
        }
        // As many as the Python prototype of the table maps: 676 mathematical letters, 2
        // dotless letters, 50 mathematical digits and 460 others
        let known = ('\0'..=char::MAX)
            .filter(|&c| fancy_to_ascii(c).is_some())
            .count();
        assert_eq!(known, 1188);
    }

    #[test]
    fn sets_unencrypted_text_when_athena_rejects_it() {
        let decoder = Decoder::<UnicodeFancyTextDecoder>::new();
        let result = decoder.crack("𝐅𝐥𝐚𝐠 𝟐𝟎𝟐𝟒", &get_athena_checker());
        assert!(!result.success);
        assert_eq!(result.unencrypted_text.unwrap(), ["Flag 2024"]);
    }

    #[test]
    fn needs_two_fancy_characters() {
        assert_eq!(crack("①"), None);
        assert_eq!(crack("Ａ"), None);
        assert_eq!(crack("hello ｗorld"), None);
        // A lone emoji with a variation selector
        assert_eq!(crack("❤\u{FE0F}"), None);
        assert_eq!(crack("ℹ"), None);
        assert_decodes("ＡＢ", "AB");
    }

    #[test]
    fn needs_twice_as_many_fancy_characters_as_other_non_ascii_ones() {
        // One fullwidth `！` and two Han characters
        assert_eq!(crack("你好！"), None);
        // Three fullwidth letters, three kana
        assert_eq!(crack("ＮＨＫの番組"), None);
        assert_eq!(crack("ＡＢＣ商事"), None);
        assert_eq!(crack("ＡＢ北京"), None);
        // Emoji with variation selectors: as many marks as emoji
        assert_eq!(crack("❤\u{FE0F}❤\u{FE0F}❤\u{FE0F}"), None);
        assert_eq!(crack("☀\u{FE0F}☀\u{FE0F}"), None);
        // Exactly twice as many
        assert_decodes("ＡＢ北", "AB北");
        assert_decodes("𝐡𝐞𝐥𝐥𝐨 café", "hello café");
    }

    #[test]
    fn fails_on_control_characters() {
        assert_eq!(crack("𝐡𝐞𝐥𝐥𝐨\u{0}"), None);
        assert_eq!(crack("𝐡𝐞𝐥𝐥𝐨\u{1b}[0m"), None);
        assert_eq!(crack("𝐡𝐞𝐥𝐥𝐨\u{85}"), None);
        // Whitespace is fine
        assert_decodes("𝐡𝐞𝐥𝐥𝐨\t𝐰𝐨𝐫𝐥𝐝\r\n", "hello\tworld\r\n");
    }

    #[test]
    fn fails_when_only_marks_are_left() {
        assert_eq!(crack("\u{FE0F}\u{FE0F}"), None);
        assert_eq!(crack("\u{0336}\u{0336}\u{0336}"), None);
    }

    #[test]
    fn fails_on_ordinary_text_in_other_scripts() {
        for text in [
            "café",
            "naïve résumé",
            "北京大学",
            "Привет, мир",
            "⠓⠑⠇⠇⠕",
            "5 m²",
            "Ⅻ ﬁ",
            "Ελληνικά",
            "ђєℓℓσ ωσяℓ∂",
            "x² + y² = z²",
        ] {
            assert_eq!(crack(text), None, "{text:?}");
        }
    }

    #[test]
    fn fails_on_other_decoders_inputs() {
        // The bench's gibberish `miss` string, Base64, hex and English, which are ASCII
        for text in [
            "T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV",
            "aGVsbG8gd29ybGQ=",
            "68656c6c6f20776f726c64",
            "hello world",
        ] {
            assert_eq!(crack(text), None, "{text:?}");
        }
        // Base65536 and Base100 (the library API's examples), Braille, and the bench's
        // accented `unicode_exhausts` input
        for text in [
            "𒅓鹨𖡮𒀠啦ꍢ顡啫𓍱𓁡𠁴唬𓍪鱤啥𖥭𔐠𔕯ᔮ",
            "👟👜👣👣👦🐗👮👦👩👣👛",
            "⠓⠑⠇⠇⠕⠀⠺⠕⠗⠇⠙",
            "éèêëàâäôöûüçéèêëàâäôöûüçéèêëàâäôöûüçéèêëàâäôöûüç",
        ] {
            assert_eq!(crack(text), None, "{text:?}");
        }
    }

    #[test]
    fn handles_panic_if_empty_string() {
        assert_eq!(crack(""), None);
    }

    #[test]
    fn handles_panic_if_emoji() {
        assert_eq!(crack("😀"), None);
        assert_eq!(crack("😀😀😀"), None);
    }

    #[test]
    fn fails_on_english() {
        assert_eq!(crack("hello world"), None);
        assert_eq!(crack("hello my name is panicky mc panic face!"), None);
    }

    #[test]
    fn decodes_long_text() {
        let fancy = "𝐡𝐞𝐥𝐥𝐨 ".repeat(10_000);
        assert_eq!(
            decode_fancy_text(&fancy).as_deref(),
            Some("hello ".repeat(10_000).as_str())
        );
        assert_eq!(decode_fancy_text(&"北".repeat(10_000)), None);
    }

    #[test]
    fn is_registered() {
        // Exactly one decoder by that name runs in the search
        let decoders = get_decoder_by_name("Unicode Fancy Text");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Unicode Fancy Text");
        // Cached results name the decoder; reading them back looks it up here
        let decoder = DECODER_MAP
            .get("Unicode Fancy Text")
            .expect("Unicode Fancy Text should be in DECODER_MAP")
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "Unicode Fancy Text");
        assert!((decoder.get_popularity() - 0.5).abs() < f32::EPSILON);
        assert!(decoder.get_tags().contains(&"decoder"));
    }

    #[test]
    fn runs_before_rot47() {
        // rot47 reads each character as its low byte, so it turns fullwidth and negative
        // circled letters into ASCII too. When two decoders find plaintext in the same
        // search step, the search reports the one listed first.
        let decoders = get_all_decoders();
        let names: Vec<&str> = decoders
            .components
            .iter()
            .map(|decoder| decoder.get_name())
            .collect();
        let position = |name| names.iter().position(|&n| n == name).unwrap();
        assert!(position("Unicode Fancy Text") < position("rot47"));
    }
}
