//! Decode Uuencode (Unix-to-Unix encoding): every 3 bytes become 4 characters, each 6-bit
//! value `v` written as the character `32 + v` (space to `_`), with the backtick also
//! meaning 0 because many encoders avoid the space. Every line starts with a length
//! character, `32 + n` for the `n` bytes it holds (`!` to `M`, 1 to 45). A file is usually
//! wrapped in a `begin <mode> <name>` header and an `end` line, with a zero-length line (a
//! backtick or a space) before `end`. `+:&5L;&\@=V]R;&0` is `hello world`.
//! Call uuencode_decoder.crack to use. It returns a `CrackResult` whose `unencrypted_text` is
//! `None` when the input isn't uuencoded text.
//!
//! The framing is optional: data lines on their own decode too. Python's `uu` module and
//! `binascii.b2a_uu` write a space for 0 unless asked for backticks, so a line often ends
//! in spaces, and those get lost when the text is copied around. Like `binascii.a2b_uu`,
//! this decoder reads missing characters at the end of a line as zeros.
//!
//! References: <https://en.wikipedia.org/wiki/Uuencoding>,
//! <https://docs.python.org/3/library/binascii.html#binascii.a2b_uu>,
//! <https://man.freebsd.org/cgi/man.cgi?query=uuencode&sektion=5>.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The Uuencode decoder, call:
/// `let uuencode_decoder = Decoder::<UuencodeDecoder>::new()` to create a new instance
/// And then call:
/// `result = uuencode_decoder.crack(input)` to decode uuencoded text
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::uuencode_decoder::UuencodeDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_uuencode = Decoder::<UuencodeDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // What `uuencode` writes for a file called hello.txt that holds "hello world"
/// let encoded = "begin 644 hello.txt\n+:&5L;&\\@=V]R;&0`\n`\nend\n";
/// let result = decode_uuencode.crack(encoded, &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hello world");
/// ```
pub struct UuencodeDecoder;

/// Decoded texts shorter than this are rejected. One or two bytes are too short to
/// identify, and one- and two-byte lines (`!` or `"` and two or three characters from a
/// 65-character alphabet) are easily matched by text that isn't uuencode.
const MIN_DECODED_BYTES: usize = 3;

impl Crack for Decoder<UuencodeDecoder> {
    fn new() -> Decoder<UuencodeDecoder> {
        Decoder {
            name: "Uuencode",
            description: "Unix-to-Unix encoding: 3 bytes to 4 printable chars (value + 32, backtick for zero), each line prefixed with its byte count, optionally wrapped in `begin <mode> <name>` and `end`.",
            link: "https://en.wikipedia.org/wiki/Uuencoding",
            tags: vec!["uuencode", "uu", "decoder", "base"],
            popularity: 0.3,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes `text` as Uuencode and checks the result with `checker`.
    /// `unencrypted_text` is `None` when `text` isn't uuencoded UTF-8 text.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Uuencode with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_uuencode(text) else {
            debug!("Failed to decode Uuencode because the text isn't uuencoded UTF-8 text");
            return results;
        };
        trace!("Decoded text for Uuencode: {:?}", decoded_text);

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode Uuencode because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Decodes uuencoded text, or returns `None` if `text` isn't uuencoded UTF-8 text without
/// control characters (tabs and line breaks are allowed).
///
/// `text` is one or more data lines, optionally after a `begin <mode> <name>` header, and
/// optionally followed by `end`. Zero-length lines (empty, a space or a backtick) can be
/// anywhere, and only those can follow `end`.
fn decode_uuencode(text: &str) -> Option<String> {
    // Trimming loses nothing. A data line can't start with a space, which would be a
    // length of zero, and trailing spaces are zeros, which is what a missing character is
    // read as.
    let text = text.trim();
    let mut lines = text.split('\n');

    // Only a `begin` header or a length character (`!` to `M`) can come first. Most input
    // fails here, at byte 0: lower-case letters, `N` to `Z` (the bench `miss` string starts
    // with `T`), `[` to `_`, and anything that isn't ASCII.
    match *text.as_bytes().first()? {
        b'b' => {
            if !is_begin_line(trim_line(lines.next()?)) {
                return None;
            }
        }
        b'!'..=b'M' => {}
        _ => return None,
    }

    let mut decoded = Vec::with_capacity(text.len() / 4 * 3);
    let mut seen_end = false;
    for line in lines {
        let line = trim_line(line);
        match line {
            // Zero-length lines, like the one before `end`
            b"" | b"`" => {}
            _ if seen_end => return None,
            b"end" => seen_end = true,
            _ => decode_line(line, &mut decoded)?,
        }
    }

    // Also rejects framing without any data lines, like `begin 644 x` and `end` on their own
    if decoded.len() < MIN_DECODED_BYTES {
        return None;
    }
    // Strict UTF-8, like Base64: a uuencoded binary file isn't plaintext
    let decoded = String::from_utf8(decoded).ok()?;
    // This rejects most text that only looks like uuencode, such as upper-case hex, Morse
    // code and A1Z26: their length characters promise more bytes than their lines hold, and
    // the missing characters decode to NULs.
    if decoded
        .chars()
        .any(|c| c.is_control() && !matches!(c, '\t' | '\n' | '\r'))
    {
        return None;
    }
    Some(decoded)
}

/// `line` without the `\r` of a CRLF line break and without trailing spaces. Spaces are
/// zeros, and so are missing characters, so dropping them doesn't change the line's bytes.
fn trim_line(line: &str) -> &[u8] {
    let line = line.strip_suffix('\r').unwrap_or(line);
    line.trim_end_matches(' ').as_bytes()
}

/// Whether `line` is a `begin <mode> <name>` header: `begin`, a space, the file mode as 3
/// or 4 octal digits, a space and the file name. `begin-base64` is Base64, as written by
/// `uuencode -m`, so it isn't one.
fn is_begin_line(line: &[u8]) -> bool {
    let Some(rest) = line.strip_prefix(b"begin ") else {
        return false;
    };
    let mode_digits = rest
        .iter()
        .take_while(|&&byte| (b'0'..=b'7').contains(&byte))
        .count();
    (3..=4).contains(&mode_digits)
        && rest.get(mode_digits) == Some(&b' ')
        && rest.len() > mode_digits + 1
}

/// Decodes a data line, its length character and then up to 60 characters, onto the end
/// of `out`. Returns `None` if `line` isn't a data line.
fn decode_line(line: &[u8], out: &mut Vec<u8>) -> Option<()> {
    let (&length, symbols) = line.split_first()?;
    // `!` to `M`: 1 to 45 bytes, the most a line holds
    if !(b'!'..=b'M').contains(&length) {
        return None;
    }
    let length = usize::from(length - b' ');
    // Every 3 bytes take 4 characters. Fewer is fine (zeros at the end were lost), more
    // isn't.
    if symbols.len() > length.div_ceil(3) * 4 {
        return None;
    }

    let start = out.len();
    for group in symbols.chunks(4) {
        let mut values = [0u8; 4];
        for (value, &symbol) in values.iter_mut().zip(group) {
            // Space to backtick. The backtick is 64, which is 0 in six bits.
            if !(b' '..=b'`').contains(&symbol) {
                return None;
            }
            *value = (symbol - b' ') & 0x3F;
        }
        let [a, b, c, d] = values;
        out.extend_from_slice(&[(a << 2) | (b >> 4), (b << 4) | (c >> 2), (c << 6) | d]);
    }
    // Drops the padding of the last group, or adds the zeros whose characters were lost
    out.resize(start + length, 0);
    Some(())
}

#[cfg(test)]
mod tests {
    use super::{decode_uuencode, UuencodeDecoder};
    use crate::checkers::athena::Athena;
    use crate::checkers::checker_type::{Check, Checker};
    use crate::checkers::CheckerTypes;
    use crate::decoders::crack_results::CrackResult;
    use crate::decoders::interface::{Crack, Decoder};
    use crate::decoders::{DecoderType, DECODER_MAP};
    use crate::filtration_system::get_decoder_by_name;

    // Every vector was made with Python 3.9 (`codecs.encode(data, "uu")`,
    // `uu.encode(..., backtick=...)` or `binascii.b2a_uu`) and decoded back, line by line,
    // with Python's `binascii.a2b_uu` and perl 5.32's `unpack("u", $line)`.
    // https://github.com/bee-san/Ciphey/issues/958

    /// `codecs.encode(b"Sphinx of black quartz, judge my vow.", "uu")` plus a blank line, the
    /// issue example. The data line ends in two spaces (zeros) and the line before `end` is
    /// a single space.
    const ISSUE_EXAMPLE: &str = concat!(
        "begin 666 <data>\n",
        r"E4W!H:6YX(&]F(&)L86-K('%U87)T>BP@:G5D9V4@;7D@=F]W+@  ",
        "\n \nend\n\n",
    );
    const SPHINX: &str = "Sphinx of black quartz, judge my vow.";

    const LIGHTHOUSE: &str =
        "Meet me at the old lighthouse after midnight and bring the map, the key and a torch.";

    /// `uu.encode(..., name="data.txt", mode=0o644, backtick=True)` of `LIGHTHOUSE`, the
    /// bench `medium` input. The backtick in the second line is a zero, not the end.
    const LIGHTHOUSE_FRAMED: &str = r#"begin 644 data.txt
M365E="!M92!A="!T:&4@;VQD(&QI9VAT:&]U<V4@869T97(@;6ED;FEG:'0@
G86YD(&)R:6YG('1H92!M87`L('1H92!K97D@86YD(&$@=&]R8V@N
`
end
"#;

    /// The same with `backtick=False`, Python's default: spaces for zeros, inside the
    /// second line too, and a space line before `end`.
    const LIGHTHOUSE_FRAMED_SPACES: &str = concat!(
        "begin 644 data.txt\n",
        r#"M365E="!M92!A="!T:&4@;VQD(&QI9VAT:&]U<V4@869T97(@;6ED;FEG:'0@"#,
        "\n",
        r"G86YD(&)R:6YG('1H92!M87 L('1H92!K97D@86YD(&$@=&]R8V@N",
        "\n \nend\n",
    );

    /// The two data lines of `LIGHTHOUSE_FRAMED` on their own
    const LIGHTHOUSE_LINES: &str = r#"M365E="!M92!A="!T:&4@;VQD(&QI9VAT:&]U<V4@869T97(@;6ED;FEG:'0@
G86YD(&)R:6YG('1H92!M87`L('1H92!K97D@86YD(&$@=&]R8V@N"#;

    /// `uu.encode(..., name="data.txt", mode=0o644, backtick=True)` of the 576-character bench
    /// `long` plaintext: 16 lines, 819 bytes.
    const LONG: &str = r#"begin 644 data.txt
M0VEP:&5Y(&ES(&%N(&%U=&]M871E9"!D96-O9&EN9R!T;V]L+B!9;W4@9VEV
M92!I="!E;F-R>7!T960@;W(@96YC;V1E9"!T97AT(&%N9"!I="!T<FEE<R!T
M;R!W;W)K(&]U="!W:&%T('=A<R!D;VYE('1O(&ET+"!W:71H;W5T('EO=2!H
M879I;F<@=&\@:VYO=R!T:&4@:V5Y(&]R(&5V96X@=&AE(&-I<&AE<BX@270@
M<V5A<F-H97,@=&AR;W5G:"!M86YY('!O<W-I8FQE(&1E8V]D:6YG<RP@8VAE
M8VMS(&5A8V@@8V%N9&ED871E('1O('-E92!W:&5T:&5R(&ET(&QO;VMS(&QI
M:V4@16YG;&ES:"!O<B!M871C:&5S(&$@:VYO=VX@<&%T=&5R;B!S=6-H(&%S
M(&%N(&5M86EL(&%D9')E<W,L(&%N9"!S=&]P<R!W:&5N(&ET(&9I;F1S('-O
M;65T:&EN9R!T:&%T(')E861S(&QI:V4@<&QA:6YT97AT+B!-;W-T(&]F('1H
M92!T:6UE('1H:7,@=&%K97,@;&5S<R!T:&%N(&$@<V5C;VYD+"!W:&EC:"!M
M86ME<R!I="!H86YD>2!F;W(@8V%P='5R92!T:&4@9FQA9R!C:&%L;&5N9V5S
M+"!P=7IZ;&4@:'5N=',@86YD(&9O<B!A;GEO;F4@=VAO('-T=6UB;&5S(&%C
D<F]S<R!A('-T<F%N9V4@<W1R:6YG(&EN(&$@;&]G(&9I;&4N
`
end
"#;
    const LONG_PLAINTEXT: &str = "Ciphey is an automated decoding tool. You give it encrypted or encoded text and it tries to work out what was done to it, without you having to know the key or even the cipher. It searches through many possible decodings, checks each candidate to see whether it looks like English or matches a known pattern such as an email address, and stops when it finds something that reads like plaintext. Most of the time this takes less than a second, which makes it handy for capture the flag challenges, puzzle hunts and for anyone who stumbles across a strange string in a log file.";

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn crack_result(text: &str) -> CrackResult {
        Decoder::<UuencodeDecoder>::new().crack(text, &get_athena_checker())
    }

    // Runs the decoder with the Athena checker and returns the decoded text, if any
    fn crack(text: &str) -> Option<String> {
        let result = crack_result(text);
        if result.unencrypted_text.is_none() {
            assert!(!result.success, "{text:?} failed but was marked successful");
        }
        result.unencrypted_text.map(|texts| texts[0].clone())
    }

    // Asserts that Athena accepts what `text` decodes to, and that it is `plaintext`
    fn assert_identified(text: &str, plaintext: &str) {
        let result = crack_result(text);
        assert!(result.success, "Athena should accept {plaintext:?}");
        assert_eq!(result.unencrypted_text.unwrap()[0], plaintext);
    }

    #[test]
    fn decodes_the_issue_example() {
        // Decoded, but Athena doesn't take the pangram for English
        assert_eq!(crack(ISSUE_EXAMPLE).unwrap(), SPHINX);
    }

    #[test]
    fn decodes_the_issue_example_without_its_trailing_spaces() {
        assert_eq!(
            crack("begin 666 <data>\nE4W!H:6YX(&]F(&)L86-K('%U87)T>BP@:G5D9V4@;7D@=F]W+@\n\nend\n")
                .unwrap(),
            SPHINX
        );
        // The data line alone, with and without its two padding spaces
        assert_eq!(
            crack("E4W!H:6YX(&]F(&)L86-K('%U87)T>BP@:G5D9V4@;7D@=F]W+@").unwrap(),
            SPHINX
        );
        assert_eq!(
            crack("E4W!H:6YX(&]F(&)L86-K('%U87)T>BP@:G5D9V4@;7D@=F]W+@  ").unwrap(),
            SPHINX
        );
    }

    #[test]
    fn decodes_backticks_for_zeros() {
        assert_identified(LIGHTHOUSE_FRAMED, LIGHTHOUSE);
    }

    #[test]
    fn decodes_spaces_for_zeros() {
        assert_identified(LIGHTHOUSE_FRAMED_SPACES, LIGHTHOUSE);
    }

    #[test]
    fn decodes_crlf_line_breaks() {
        assert_identified(&LIGHTHOUSE_FRAMED.replace('\n', "\r\n"), LIGHTHOUSE);
        assert_identified(&LIGHTHOUSE_FRAMED_SPACES.replace('\n', "\r\n"), LIGHTHOUSE);
    }

    #[test]
    fn decodes_data_lines_without_framing() {
        assert_identified(LIGHTHOUSE_LINES, LIGHTHOUSE);
        assert_identified(&format!("{LIGHTHOUSE_LINES}\n"), LIGHTHOUSE);
    }

    #[test]
    fn decodes_begin_without_end_and_end_without_begin() {
        assert_identified(
            &format!("begin 644 data.txt\n{LIGHTHOUSE_LINES}"),
            LIGHTHOUSE,
        );
        assert_identified(&format!("{LIGHTHOUSE_LINES}\n`\nend\n"), LIGHTHOUSE);
    }

    #[test]
    fn decodes_a_four_digit_mode() {
        assert_identified(
            &format!("begin 0644 data.txt\n{LIGHTHOUSE_LINES}"),
            LIGHTHOUSE,
        );
    }

    #[test]
    fn skips_zero_length_lines_anywhere() {
        let text = format!(
            "begin 644 data.txt\n\n{}\n`\n \n\nend\n\n",
            LIGHTHOUSE_LINES.replace('\n', "\n`\n\n")
        );
        assert_identified(&text, LIGHTHOUSE);
    }

    #[test]
    fn decodes_lines_of_different_lengths() {
        // binascii.b2a_uu of three pieces of LIGHTHOUSE: 15, 29 and 40 bytes
        let text = concat!(
            r#"/365E="!M92!A="!T:&4@"#,
            "\n",
            r"=;VQD(&QI9VAT:&]U<V4@869T97(@;6ED;FEG:'0`",
            "\n",
            r#"H(&%N9"!B<FEN9R!T:&4@;6%P+"!T:&4@:V5Y(&%N9"!A('1O<F-H+@``"#,
        );
        assert_identified(text, LIGHTHOUSE);
    }

    #[test]
    fn decodes_hello_world() {
        // binascii.b2a_uu(b"Hello, World!", backtick=True), and without the padding
        assert_identified(r"-2&5L;&\L(%=O<FQD(0``", "Hello, World!");
        assert_identified(r"-2&5L;&\L(%=O<FQD(0", "Hello, World!");
        // binascii.b2a_uu(b"hello world", backtick=True), and without the padding
        assert_identified(r"+:&5L;&\@=V]R;&0`", "hello world");
        assert_identified(r"+:&5L;&\@=V]R;&0", "hello world");
    }

    #[test]
    fn decodes_the_shortest_accepted_output() {
        // Three bytes, the minimum. Athena doesn't identify `Cat`.
        assert_eq!(crack("#0V%T").unwrap(), "Cat");
    }

    #[test]
    fn decodes_utf8() {
        assert_eq!(crack(")8V%FPZD@XIB5").unwrap(), "café ☕");
    }

    #[test]
    fn decodes_bench_long() {
        assert_eq!(LONG.len(), 819);
        assert_identified(LONG, LONG_PLAINTEXT);
    }

    #[test]
    fn decode_uuencode_returns_the_text() {
        assert_eq!(
            decode_uuencode(LIGHTHOUSE_FRAMED).as_deref(),
            Some(LIGHTHOUSE)
        );
    }

    #[test]
    fn fails_on_english() {
        assert_eq!(crack("hello world"), None);
        assert_eq!(crack("HELLO WORLD"), None);
        assert_eq!(crack("THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG"), None);
        assert_eq!(crack("hello my name is panicky mc panic face!"), None);
    }

    #[test]
    fn fails_on_other_encodings() {
        // Base32 of "Hello"
        assert_eq!(crack("JBSWY3DP"), None);
        // Upper-case hex of "Meet"
        assert_eq!(crack("4D656574"), None);
        // Morse code, A1Z26 and decimal character codes of "hello"
        assert_eq!(crack(".... . .-.. .-.. ---"), None);
        assert_eq!(crack("8-5-12-12-15"), None);
        assert_eq!(crack("104 101 108 108 111"), None);
        // Base64 of "Hello World"
        assert_eq!(crack("SGVsbG8gV29ybGQ="), None);
        // Binary of "Hi"
        assert_eq!(crack("01001000 01101001"), None);
        // Base32 of LIGHTHOUSE: one line, longer than its first character allows
        assert_eq!(crack("JVSWK5BANVSSAYLUEB2GQZJAN5WGIIDMNFTWQ5DIN52XGZJAMFTHIZLSEBWWSZDONFTWQ5BAMFXGIIDCOJUW4ZZAORUGKIDNMFYCYIDUNBSSA23FPEQGC3TEEBQSA5DPOJRWQLQ="), None);
    }

    #[test]
    fn fails_on_bad_data_lines() {
        // Decodes to 86 D0 93, which isn't UTF-8
        assert_eq!(crack("#ABC"), None);
        // Lower-case letters are outside the alphabet
        assert_eq!(crack("+abc"), None);
        // One byte, 0x04
        assert_eq!(crack(" !!!!"), None);
        // A character more than three bytes take
        assert_eq!(crack("#0V%T`"), None);
        // Tabs are outside the alphabet
        assert_eq!(crack("+:&5L;&\t@=V]R;&0"), None);
        assert_eq!(crack("+:&5L;&\\@=V]R;&0\t`"), None);
        // So are emoji
        assert_eq!(crack("+:&5L;&\\@=V]R;&0😀"), None);
    }

    #[test]
    fn fails_on_a_length_character_without_data() {
        // 11 NUL bytes
        assert_eq!(crack("+"), None);
    }

    #[test]
    fn fails_on_framing_without_data() {
        assert_eq!(crack("begin 644 x\nend"), None);
        assert_eq!(crack("begin 644 x\n`\nend\n"), None);
    }

    #[test]
    fn fails_on_a_bad_begin_line() {
        // `uuencode -m` writes Base64
        assert_eq!(crack("begin-base64 644 x"), None);
        assert_eq!(
            crack(&format!(
                "begin-base64 644 data.txt\n{LIGHTHOUSE_LINES}\n===="
            )),
            None
        );
        // The mode isn't 3 or 4 octal digits
        assert_eq!(
            crack(&format!("begin 999 data.txt\n{LIGHTHOUSE_LINES}")),
            None
        );
        assert_eq!(
            crack(&format!("begin 64 data.txt\n{LIGHTHOUSE_LINES}")),
            None
        );
        assert_eq!(
            crack(&format!("begin 10644 data.txt\n{LIGHTHOUSE_LINES}")),
            None
        );
        // No file name
        assert_eq!(crack(&format!("begin 644\n{LIGHTHOUSE_LINES}")), None);
        assert_eq!(crack(&format!("beginning\n{LIGHTHOUSE_LINES}")), None);
    }

    #[test]
    fn fails_on_text_after_end() {
        assert_eq!(crack(&format!("{LIGHTHOUSE_FRAMED}trailing text")), None);
        assert_eq!(crack(&format!("{LIGHTHOUSE_LINES}\n`\nend\nM365E")), None);
    }

    #[test]
    fn fails_on_text_before_begin() {
        assert_eq!(
            crack(&format!("Here is the file:\n{LIGHTHOUSE_FRAMED}")),
            None
        );
    }

    #[test]
    fn fails_with_fewer_than_three_bytes() {
        // binascii.b2a_uu(b"hi", backtick=True)
        assert_eq!(crack("\":&D`"), None);
    }

    #[test]
    fn fails_when_the_bytes_are_not_utf8() {
        // binascii.b2a_uu(b"\xff\xfe\xfdabc", backtick=True)
        assert_eq!(crack("&__[]86)C"), None);
    }

    #[test]
    fn fails_on_control_characters() {
        // binascii.b2a_uu(b"ab\x01cd", backtick=True)
        assert_eq!(crack("%86(!8V0`"), None);
    }

    #[test]
    fn fails_on_the_bench_miss_input() {
        // Rejected at its first byte, `T`
        assert_eq!(
            crack("T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV"),
            None
        );
    }

    #[test]
    fn handles_panic_if_empty_string() {
        assert_eq!(crack(""), None);
    }

    #[test]
    fn handles_panic_if_whitespace() {
        assert_eq!(crack("   "), None);
        assert_eq!(crack(" \n \r\n"), None);
    }

    #[test]
    fn handles_panic_if_emoji() {
        assert_eq!(crack("😀"), None);
    }

    #[test]
    fn is_registered() {
        // Exactly one decoder by that name runs in the search
        let decoders = get_decoder_by_name("Uuencode");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Uuencode");
        // Cached results name the decoder; reading them back looks it up here
        let decoder = DECODER_MAP
            .get("Uuencode")
            .expect("Uuencode should be in DECODER_MAP")
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "Uuencode");
    }
}
