//! Crack single-byte XOR.
//!
//! Every byte of the plaintext is XORed with the same key byte (1 to 255), and the result
//! is usually written out as hex or Base64. It is the first "crypto" step of many CTFs
//! (Cryptopals set 1 challenge 3) and common in malware string obfuscation.
//! There are only 255 keys, so the cracker tries all of them, ranks each output by
//! English byte frequency and sends the best 5 to the checker.
//!
//! Ciphey passes text between decoders as `String`s, and the Base64 decoder drops output
//! that isn't UTF-8, so XORed bytes rarely survive an earlier decoder. Like CyberChef's
//! Magic, this cracker therefore decodes hex and Base64 itself, and also reads text that
//! an earlier decoder produced from raw bytes. Ordinary text has none of these "byte
//! views", so for it the cracker costs one scan of the text.
//! Uses Low sensitivity for gibberish detection.

use crate::checkers::checker_result::CheckResult;
use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;
use base64::{engine::general_purpose, Engine as _};
use gibberish_or_not::Sensitivity;
use once_cell::sync::Lazy;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, trace};

/// A byte view shorter than this is not cracked: there is too little text to rank keys.
const MIN_BYTES: usize = 8;

/// A byte view with fewer distinct byte values than this is not cracked. XOR maps distinct
/// bytes to distinct bytes, so it can only turn such a view into text over a tiny alphabet,
/// such as the "eddedde..." that binary digits give. That text outscores English, but no
/// checker accepts it.
const MIN_DISTINCT_BYTES: usize = 5;

/// Keys are ranked on at most this many bytes of a view.
const RANK_BYTES: usize = 512;

/// A key whose output scores below this is not a candidate.
const MIN_SCORE: f32 = -6.5;

/// How many candidates are sent to the checker.
const MAX_CHECKED: usize = 5;

/// When the checker identifies no candidate, the best one is still handed to the search if
/// it scores at least this and contains a space: English the checker missed, or English
/// under another cipher.
const UNCONFIRMED_MIN_SCORE: f32 = -4.0;

/// The shortest text read as Base64 by the Base64 view.
const MIN_BASE64_VIEW_CHARS: usize = 12;

/// The shortest candidate that counts as the Base64 next layer of a chain.
const MIN_BASE64_LAYER_CHARS: usize = 16;

/// English letter frequencies in percent, `a` to `z`.
const LETTER_PERCENT: [f32; 26] = [
    8.17, 1.49, 2.78, 4.25, 12.70, 2.23, 2.02, 6.09, 6.97, 0.15, 0.77, 4.03, 2.41, 6.75, 7.51,
    1.93, 0.10, 5.99, 6.33, 9.06, 2.76, 0.98, 2.36, 0.15, 1.97, 0.07,
];

/// Bytes other than letters and space that are common in English text. They share 3% of
/// the probability mass.
const COMMON_SYMBOLS: &[u8; 24] = b".,'\"!?;:-()0123456789\n\t\r";

/// Log-probability of each byte in English text. A text's score is the mean of these over
/// its bytes, so English scores about -3.4 to -3.8 and Base64 about -5.5.
static BYTE_WEIGHTS: Lazy<[f32; 256]> = Lazy::new(|| {
    let mut weights = [1e-6_f32.ln(); 256];
    for (offset, percent) in LETTER_PERCENT.iter().enumerate() {
        let frequency = percent / 100.0;
        weights[usize::from(b'a') + offset] = (0.82 * frequency).ln();
        weights[usize::from(b'A') + offset] = (0.82 * frequency * 0.15).ln();
    }
    weights[usize::from(b' ')] = 0.15_f32.ln();
    let symbol_weight = (0.03_f32 / COMMON_SYMBOLS.len() as f32).ln();
    for &symbol in COMMON_SYMBOLS {
        weights[usize::from(symbol)] = symbol_weight;
    }
    weights
});

/// The single-byte XOR cracker, call:
/// `let xor_decoder = Decoder::<XorSingleByteDecoder>::new()` to create a new instance
/// And then call:
/// `result = xor_decoder.crack(input, &checker)` to crack hex, Base64 or raw bytes.
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::xor_single_byte_decoder::XorSingleByteDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decoder = Decoder::<XorSingleByteDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // Cryptopals set 1 challenge 3: hex of bytes XORed with 0x58
/// let result = decoder.crack(
///     "1b37373331363f78151b7f2b783431333d78397828372d363c78373e783a393b3736",
///     &checker,
/// );
/// assert!(result.success);
/// assert_eq!(result.key.as_deref(), Some("0x58"));
/// assert_eq!(result.unencrypted_text.unwrap()[0], "Cooking MC's like a pound of bacon");
/// ```
pub struct XorSingleByteDecoder;

impl Crack for Decoder<XorSingleByteDecoder> {
    fn new() -> Decoder<XorSingleByteDecoder> {
        Decoder {
            name: "Single-byte XOR",
            description: "The XOR cipher combines every byte of the plaintext with a key using the exclusive or operation. With a single-byte key there are only 255 keys, so the cracker reads hex, Base64 or raw bytes, tries every key, ranks the outputs by English byte frequency and checks the best 5. Uses Low sensitivity for gibberish detection.",
            link: "https://en.wikipedia.org/wiki/XOR_cipher",
            tags: vec!["xor", "xor_single_byte", "bitwise", "crypto"],
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// Checks the 5 best candidates and returns the first one the checker identifies.
    /// If none is identified, returns the candidates worth searching further (see
    /// [`unconfirmed`]), or no text at all.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying single-byte XOR with text {:?}", text);
        let candidates = best_candidates(text);
        if candidates.is_empty() {
            debug!("Single-byte XOR found no candidate keys");
            return CrackResult::new(self, text.to_string());
        }
        let checker_with_sensitivity = checker.with_sensitivity(Sensitivity::Low);
        check_candidates(self, text, &candidates, |candidate| {
            checker_with_sensitivity.check(candidate)
        })
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// A key that turned one of the input's byte views into plausible text.
#[derive(Debug)]
struct Candidate {
    /// The key byte
    key: u8,
    /// Mean byte weight of the output, see [`BYTE_WEIGHTS`]
    score: f32,
    /// The output
    text: String,
}

/// Formats a key the way CyberChef's XOR operation takes it, e.g. `0x2a`.
fn format_key(key: u8) -> String {
    format!("0x{key:02x}")
}

/// Runs `check` on each candidate in order and returns the first one it identifies. If it
/// identifies none, returns the [`unconfirmed`] candidates, or no text at all.
fn check_candidates(
    decoder: &Decoder<XorSingleByteDecoder>,
    text: &str,
    candidates: &[Candidate],
    mut check: impl FnMut(&str) -> CheckResult,
) -> CrackResult {
    let mut results = CrackResult::new(decoder, text.to_string());
    for candidate in candidates {
        if !check_string_success(&candidate.text, text) {
            continue;
        }
        let checker_result = check(&candidate.text);
        if checker_result.is_identified {
            trace!("Found a match with single-byte XOR key {}", candidate.key);
            results.unencrypted_text = Some(vec![candidate.text.clone()]);
            results.update_checker(&checker_result);
            results.key = Some(format_key(candidate.key));
            return results;
        }
    }

    let handed_on = unconfirmed(candidates);
    if !handed_on.is_empty() {
        // One key per text, in the same order
        let keys: Vec<String> = handed_on.iter().map(|c| format_key(c.key)).collect();
        results.key = Some(keys.join(", "));
        results.unencrypted_text = Some(handed_on.iter().map(|c| c.text.clone()).collect());
    }
    results
}

/// The best [`MAX_CHECKED`] candidates from every byte view of `text`, best first, with
/// no text twice.
fn best_candidates(text: &str) -> Vec<Candidate> {
    let mut all: Vec<Candidate> = byte_views(text)
        .iter()
        .flat_map(|view| crack_bytes(view))
        .map(|(key, score, text)| Candidate { key, score, text })
        .collect();
    all.sort_by(|a, b| b.score.total_cmp(&a.score).then(a.key.cmp(&b.key)));

    let mut best: Vec<Candidate> = Vec::with_capacity(MAX_CHECKED);
    for candidate in all {
        if best.len() == MAX_CHECKED {
            break;
        }
        if !best.iter().any(|kept| kept.text == candidate.text) {
            best.push(candidate);
        }
    }
    best
}

/// The candidates handed to the search when the checker identified none of them, at most 2:
/// * the best candidate, if it reads like English (it scores at least
///   [`UNCONFIRMED_MIN_SCORE`] and contains a space), as the checker misses some English;
/// * the best candidate that is itself hex or Base64 of UTF-8, the next layer of a chain
///   such as Base64 → XOR → Base64 (#808).
///
/// Both need more than a good score: letter soup such as the "edfglnhxzw..." that a few
/// repeated accented letters XOR to scores better than English, but it has no spaces and
/// isn't Base64 of anything the Base64 decoder accepts.
fn unconfirmed(candidates: &[Candidate]) -> Vec<&Candidate> {
    let mut chosen: Vec<&Candidate> = Vec::new();
    if let Some(best) = candidates.first() {
        if best.score >= UNCONFIRMED_MIN_SCORE && best.text.contains(' ') {
            chosen.push(best);
        }
    }
    if let Some(layer) = candidates.iter().find(|c| is_encoded_layer(&c.text)) {
        if !chosen.iter().any(|kept| std::ptr::eq(*kept, layer)) {
            chosen.push(layer);
        }
    }
    chosen
}

/// Tries every key on `bytes` and returns the candidates, best first, as
/// `(key, score, plaintext)`. Views under [`MIN_BYTES`] bytes, with fewer than
/// [`MIN_DISTINCT_BYTES`] distinct byte values, or that are [`numeric_text`] have none.
///
/// Keys are scored on the first [`RANK_BYTES`] bytes, from a byte histogram, and only keys
/// that pass the score checks are applied to the whole view. A key is a candidate if its
/// output
/// * is UTF-8 without control characters other than tab, CR and LF,
/// * scores at least [`MIN_SCORE`], and
/// * scores higher than `bytes` itself when `bytes` is already printable text. This stops
///   XOR from "improving" text that was fine to begin with, such as Base64 of English.
fn crack_bytes(bytes: &[u8]) -> Vec<(u8, f32, String)> {
    if bytes.len() < MIN_BYTES || numeric_text(bytes) {
        return Vec::new();
    }
    let histogram = Histogram::new(&bytes[..bytes.len().min(RANK_BYTES)]);
    if histogram.present.len() < MIN_DISTINCT_BYTES {
        return Vec::new();
    }
    let own_score = is_printable_utf8(bytes).then(|| histogram.score(0));

    let mut ranked: Vec<(u8, f32)> = (1..=u8::MAX)
        .filter(|&key| !histogram.breaks_text(key))
        .map(|key| (key, histogram.score(key)))
        .filter(|&(_, score)| score >= MIN_SCORE && own_score.is_none_or(|own| score > own))
        .collect();
    ranked.sort_by(|a, b| b.1.total_cmp(&a.1).then(a.0.cmp(&b.0)));

    ranked
        .into_iter()
        .filter_map(|(key, score)| {
            let output = String::from_utf8(bytes.iter().map(|byte| byte ^ key).collect()).ok()?;
            is_printable(&output).then_some((key, score, output))
        })
        .collect()
}

/// Byte counts of the start of a view, so a key is scored by visiting each distinct byte
/// once instead of every byte.
struct Histogram {
    /// How often each byte value occurs
    counts: [u32; 256],
    /// The byte values that occur
    present: Vec<u8>,
    /// Number of bytes counted
    total: usize,
}

impl Histogram {
    /// Counts the bytes of `sample`, which must not be empty.
    fn new(sample: &[u8]) -> Self {
        let mut counts = [0_u32; 256];
        for &byte in sample {
            counts[usize::from(byte)] += 1;
        }
        let present = (0..=u8::MAX)
            .filter(|&byte| counts[usize::from(byte)] > 0)
            .collect();
        Histogram {
            counts,
            present,
            total: sample.len(),
        }
    }

    /// Mean byte weight of the sample XORed with `key`.
    fn score(&self, key: u8) -> f32 {
        let sum: f32 = self
            .present
            .iter()
            .map(|&byte| {
                self.counts[usize::from(byte)] as f32 * BYTE_WEIGHTS[usize::from(byte ^ key)]
            })
            .sum();
        sum / self.total as f32
    }

    /// Whether XOR with `key` turns a sampled byte into an ASCII control character other
    /// than tab, CR and LF, or into a byte that never occurs in UTF-8. Either rules the key
    /// out without building its output.
    fn breaks_text(&self, key: u8) -> bool {
        self.present.iter().any(|&byte| {
            let output = byte ^ key;
            (output.is_ascii_control() && !matches!(output, b'\t' | b'\n' | b'\r'))
                || matches!(output, 0xc0 | 0xc1 | 0xf5..=0xff)
        })
    }
}

/// Whether `text` has no control characters other than tab, CR and LF.
fn is_printable(text: &str) -> bool {
    !text
        .chars()
        .any(|c| c.is_control() && !matches!(c, '\t' | '\n' | '\r'))
}

/// Whether `bytes` is text made only of hex digits (which include the decimal and octal
/// ones), whitespace and the separators `,;:.-`: decimal, octal, hex or binary codes that
/// another decoder takes off, such as Base64 of `150 145 154 154 157`. XOR turns such text
/// into letter soup like `ptqaputaptua…` that can pass the English checker, and no key
/// turns English into it: no byte maps a space, `e`, `t` and `a` all into this set.
fn numeric_text(bytes: &[u8]) -> bool {
    bytes.iter().all(|&byte| {
        byte.is_ascii_hexdigit() || byte.is_ascii_whitespace() || b",;:.-".contains(&byte)
    })
}

/// Whether `bytes` is UTF-8 without control characters other than tab, CR and LF.
fn is_printable_utf8(bytes: &[u8]) -> bool {
    std::str::from_utf8(bytes).is_ok_and(is_printable)
}

/// The byte strings `text` might stand for: its hex or Base64 decoding, and the bytes an
/// earlier decoder turned into characters. Views under [`MIN_BYTES`] bytes are dropped.
///
/// Hex digits are Base64 characters too, so text that is hex is never read as Base64.
fn byte_views(text: &str) -> Vec<Vec<u8>> {
    let mut views = Vec::new();
    match hex_view(text) {
        Some(bytes) => views.push(bytes),
        None => views.extend(base64_view(text)),
    }
    views.extend(raw_views(text));
    views.retain(|view| view.len() >= MIN_BYTES);
    views
}

/// Decodes hex. The digits may be split by whitespace or `:` into groups of whole bytes,
/// each group optionally starting with `0x`.
fn hex_view(text: &str) -> Option<Vec<u8>> {
    let mut nibbles = Vec::with_capacity(text.len());
    for group in text.split(|c: char| c.is_whitespace() || c == ':') {
        let digits = group
            .strip_prefix("0x")
            .or_else(|| group.strip_prefix("0X"))
            .unwrap_or(group);
        if digits.len() % 2 != 0 || (digits.is_empty() && !group.is_empty()) {
            return None;
        }
        for c in digits.chars() {
            nibbles.push(c.to_digit(16)? as u8);
        }
    }
    (!nibbles.is_empty()).then(|| bytes_from_nibbles(&nibbles))
}

/// Decodes text that is nothing but hex digits, at least [`MIN_BYTES`] bytes of them.
fn strict_hex(text: &str) -> Option<Vec<u8>> {
    let nibbles = text
        .chars()
        .map(|c| c.to_digit(16).map(|nibble| nibble as u8))
        .collect::<Option<Vec<u8>>>()?;
    (nibbles.len() >= 2 * MIN_BYTES && nibbles.len() % 2 == 0).then(|| bytes_from_nibbles(&nibbles))
}

/// Pairs up hex digit values into bytes. A trailing odd digit is ignored; callers check
/// the count.
fn bytes_from_nibbles(nibbles: &[u8]) -> Vec<u8> {
    let (pairs, _) = nibbles.as_chunks::<2>();
    pairs.iter().map(|&[high, low]| (high << 4) | low).collect()
}

/// Decodes Base64, ignoring surrounding whitespace.
fn base64_view(text: &str) -> Option<Vec<u8>> {
    let trimmed = text.trim();
    if trimmed.len() < MIN_BASE64_VIEW_CHARS {
        return None;
    }
    decode_base64(trimmed)
}

/// Decodes text matching `[A-Za-z0-9+/_-]+={0,2}` with the engines `base64_decoder.rs`
/// uses: standard Base64, or URL-safe Base64 if that fails.
fn decode_base64(text: &str) -> Option<Vec<u8>> {
    let body = text.trim_end_matches('=');
    let is_base64_char =
        |b: u8| b.is_ascii_alphanumeric() || matches!(b, b'+' | b'/' | b'_' | b'-');
    if body.is_empty() || text.len() - body.len() > 2 || !body.bytes().all(is_base64_char) {
        return None;
    }
    general_purpose::STANDARD_NO_PAD
        .decode(body)
        .or_else(|_| general_purpose::URL_SAFE_NO_PAD.decode(body))
        .ok()
}

/// Whether `text` is, in full, hex or Base64 of UTF-8: a layer the Hexadecimal or Base64
/// decoder can take off next. The Base64 decoder drops anything that isn't UTF-8, and
/// UTF-8 can still hold control characters, so the layer below can be XORed bytes again.
fn is_encoded_layer(text: &str) -> bool {
    let utf8 = |bytes: Vec<u8>| std::str::from_utf8(&bytes).is_ok();
    strict_hex(text).is_some_and(utf8)
        || (text.trim_end_matches('=').len() >= MIN_BASE64_LAYER_CHARS
            && decode_base64(text).is_some_and(utf8))
}

/// The bytes behind text an earlier decoder made from raw bytes, which shows as control
/// characters or Latin-1 symbols (U+0080 to U+00BF, `×` and `÷`). Other text has no raw
/// view, including text whose only non-ASCII characters are accented letters: that is
/// usually just text, such as French. English XORed with a key of 0x80 or more always has
/// one of those characters, for its spaces or for its letters: a space becomes U+0080 to
/// U+00BF for keys 0x80 to 0xBF, and the letters do for keys 0xC0 to 0xFF.
///
/// When every character is at most U+00FF the bytes are its Latin-1 values. If some of
/// those are 0x80 or more, the UTF-8 encoding is tried too: the Hexadecimal decoder turns
/// bytes that happen to be valid UTF-8 into the characters they encode, not into Latin-1.
fn raw_views(text: &str) -> Vec<Vec<u8>> {
    let carries_bytes = text.chars().any(|c| {
        (c.is_control() && !matches!(c, '\t' | '\n' | '\r'))
            || ('\u{80}'..='\u{bf}').contains(&c)
            || matches!(c, '×' | '÷')
    });
    if !carries_bytes {
        return Vec::new();
    }

    let mut views = Vec::new();
    if text.chars().all(|c| u32::from(c) <= 0xff) {
        let latin1: Vec<u8> = text.chars().map(|c| u32::from(c) as u8).collect();
        let has_high_bytes = latin1.iter().any(|&byte| byte >= 0x80);
        views.push(latin1);
        if has_high_bytes {
            views.push(text.as_bytes().to_vec());
        }
    } else {
        views.push(text.as_bytes().to_vec());
    }
    views
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::checkers::{
        athena::Athena,
        checker_type::{Check, Checker},
        CheckerTypes,
    };
    use crate::decoders::interface::{Crack, Decoder};

    /// "Sphinx of black quartz, judge my vow." XORed with 0x2a, as hex (the issue's example)
    const SPHINX_HEX: &str =
        "795a424344520a454c0a48464b49410a5b5f4b585e50060a405f4e4d4f0a47530a5c455d04";
    /// The same bytes as Base64
    const SPHINX_BASE64: &str = "eVpCQ0RSCkVMCkhGS0lBCltfS1heUAYKQF9OTU8KR1MKXEVdBA==";
    /// What the Hexadecimal decoder makes of `SPHINX_HEX`
    const SPHINX_RAW: &str = "yZBCDR\nEL\nHFKIA\n[_KX^P\u{6}\n@_NMO\nGS\n\\E]\u{4}";
    /// The Sphinx pangram
    const SPHINX: &str = "Sphinx of black quartz, judge my vow.";
    /// Cryptopals set 1 challenge 3, key 0x58
    const CRYPTOPALS_HEX: &str =
        "1b37373331363f78151b7f2b783431333d78397828372d363c78373e783a393b3736";
    /// The fox pangram XORed with 0xc3, as Base64. Every byte has its high bit set, so the
    /// Base64 decoder returns nothing for it.
    const FOX_BASE64: &str = "l6um47K2qqCo46GxrLSt46Wsu+Optq6zsOOstaax47erpuOvorm646espA==";
    /// The same bytes as hex
    const FOX_HEX: &str =
        "97aba6e3b2b6aaa0a8e3a1b1acb4ade3a5acbbe3a9b6aeb3b0e3acb5a6b1e3b7aba6e3afa2b9bae3a7aca4";
    /// The fox pangram
    const FOX: &str = "The quick brown fox jumps over the lazy dog";
    /// A CTF flag XORed with 0x5a, as hex
    const FLAG_HEX: &str = "3c363b3d21226a28056b2905346a2e0569343928232a2e6b6a3427";
    /// Base64 of the fox pangram, XORed with 0x42, as Base64 (#808)
    const CHAIN_808: &str =
        "FAUqLgsKBHMjFQwwCwUIOyBxJjcLBRg0JwEAMyYVczUhOwA0Ji8UOwsKEC0YEQAxGxoydwsFEDQYNX9/";
    /// Base64 of the fox pangram
    const FOX_IN_BASE64: &str = "VGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZw==";
    /// Base64 of the hex of "Meet me at the old lighthouse"
    const BASE64_OF_HEX: &str =
        "NGQ2NTY1NzQyMDZkNjUyMDYxNzQyMDc0Njg2NTIwNmY2YzY0MjA2YzY5Njc2ODc0Njg2Zjc1NzM2NQ==";
    /// A few Latin-1 symbols repeated, which XOR (as Latin-1 bytes) to letter soup
    const SYMBOL_SOUP: &str = "¥¤£¢¡¥¤£¢¡¥¤£¢¡¥¤£¢¡¥¤£¢¡¥¤£¢¡";

    /// The checker the search uses
    fn get_athena_checker() -> CheckerTypes {
        CheckerTypes::CheckAthena(Checker::<Athena>::new())
    }

    /// Runs the cracker on `text` with the Athena checker
    fn crack(text: &str) -> CrackResult {
        Decoder::<XorSingleByteDecoder>::new().crack(text, &get_athena_checker())
    }

    /// The best candidate's key and text
    fn top_candidate(text: &str) -> (String, String) {
        let best = best_candidates(text)
            .into_iter()
            .next()
            .unwrap_or_else(|| panic!("no candidate for {text:?}"));
        (format_key(best.key), best.text)
    }

    #[test]
    fn byte_weights_follow_the_table() {
        let close = |a: f32, b: f32| (a - b).abs() < 1e-4;
        assert!(close(
            BYTE_WEIGHTS[usize::from(b'e')],
            (0.82_f32 * 0.1270).ln()
        ));
        assert!(close(
            BYTE_WEIGHTS[usize::from(b'Z')],
            (0.82_f32 * 0.0007 * 0.15).ln()
        ));
        assert!(close(BYTE_WEIGHTS[usize::from(b' ')], 0.15_f32.ln()));
        for symbol in *b".(7\n\t\r" {
            assert!(close(
                BYTE_WEIGHTS[usize::from(symbol)],
                (0.03_f32 / 24.0).ln()
            ));
        }
        for other in [0_u8, b'{', b'_', b'~', 0x7f, 0x80, 0xff] {
            assert!(close(BYTE_WEIGHTS[usize::from(other)], 1e-6_f32.ln()));
        }
    }

    #[test]
    fn issue_example_hex_ranks_key_0x2a_first() {
        // Athena doesn't accept this pangram, so the result is the top candidate rather
        // than a success
        assert_eq!(
            top_candidate(SPHINX_HEX),
            ("0x2a".to_string(), SPHINX.to_string())
        );
    }

    #[test]
    fn issue_example_base64_ranks_key_0x2a_first() {
        assert_eq!(
            top_candidate(SPHINX_BASE64),
            ("0x2a".to_string(), SPHINX.to_string())
        );
    }

    #[test]
    fn issue_example_from_the_hexadecimal_decoder_ranks_key_0x2a_first() {
        assert_eq!(
            top_candidate(SPHINX_RAW),
            ("0x2a".to_string(), SPHINX.to_string())
        );
    }

    #[test]
    fn unidentified_english_is_handed_to_the_search() {
        let result = crack(SPHINX_HEX);
        assert!(!result.success);
        assert_eq!(result.unencrypted_text, Some(vec![SPHINX.to_string()]));
        assert_eq!(result.key.as_deref(), Some("0x2a"));
    }

    #[test]
    fn cryptopals_1_3() {
        let result = crack(CRYPTOPALS_HEX);
        assert!(result.success);
        assert_eq!(result.key.as_deref(), Some("0x58"));
        assert_eq!(
            result.unencrypted_text.unwrap()[0],
            "Cooking MC's like a pound of bacon"
        );
    }

    #[test]
    fn high_bit_key_in_base64() {
        let result = crack(FOX_BASE64);
        assert!(result.success);
        assert_eq!(result.key.as_deref(), Some("0xc3"));
        assert_eq!(result.unencrypted_text.unwrap()[0], FOX);
    }

    #[test]
    fn high_bit_key_in_hex() {
        let result = crack(FOX_HEX);
        assert!(result.success);
        assert_eq!(result.key.as_deref(), Some("0xc3"));
        assert_eq!(result.unencrypted_text.unwrap()[0], FOX);
    }

    #[test]
    fn high_bit_key_from_the_hexadecimal_decoder() {
        // Not UTF-8, so the Hexadecimal decoder falls back to one Latin-1 char per byte
        let latin1: String = strict_hex(FOX_HEX)
            .unwrap()
            .into_iter()
            .map(char::from)
            .collect();
        assert_eq!(
            top_candidate(&latin1),
            ("0xc3".to_string(), FOX.to_string())
        );
    }

    #[test]
    fn flag_is_identified_by_lemmeknow() {
        // Not the best scoring key, but among the 5 that are checked
        let rank = best_candidates(FLAG_HEX)
            .iter()
            .position(|c| c.key == 0x5a)
            .expect("key 0x5a is not among the checked candidates");
        assert!(rank < MAX_CHECKED);

        let result = crack(FLAG_HEX);
        assert!(result.success);
        assert_eq!(result.key.as_deref(), Some("0x5a"));
        assert_eq!(result.checker_name, "LemmeKnow Checker");
        assert_eq!(
            result.unencrypted_text.unwrap()[0],
            "flag{x0r_1s_n0t_3ncrypt10n}"
        );
    }

    #[test]
    fn base64_inside_xor_is_handed_to_the_search() {
        // #808: base64 -> xor -> base64. The middle layer is Base64, which the checker
        // rejects, so it is returned for the Base64 decoder to take off next.
        let result = crack(CHAIN_808);
        assert!(!result.success);
        assert_eq!(result.key.as_deref(), Some("0x42"));
        assert_eq!(
            result.unencrypted_text,
            Some(vec![FOX_IN_BASE64.to_string()])
        );
    }

    #[test]
    fn base64_of_xored_bytes_inside_xor_is_handed_to_the_search() {
        // XOR -> Base64 -> XOR -> Base64. The layer under the outer XOR decodes to bytes
        // with control characters: still UTF-8, so the Base64 decoder can take it off and
        // this cracker can then crack the inner XOR.
        let outer = "JxQyARNyEBEBKRQPASkqBRFyLgABLjYkEXMqJxcDGwkTBHsNFhd6CRBzDwkaBxQmAAN/fw==";
        let result = crack(outer);
        assert!(!result.success);
        assert_eq!(result.key.as_deref(), Some("0x42"));
        assert_eq!(
            result.unencrypted_text,
            Some(vec![SPHINX_BASE64.to_string()])
        );
    }

    #[test]
    fn crack_bytes_ranks_the_true_key_first() {
        let cases: [(&[u8], u8); 3] = [
            (b"Cooking MC's like a pound of bacon", 0x58),
            (FOX.as_bytes(), 0xc3),
            (SPHINX.as_bytes(), 0x2a),
        ];
        for (plaintext, key) in cases {
            let ciphertext: Vec<u8> = plaintext.iter().map(|byte| byte ^ key).collect();
            let candidates = crack_bytes(&ciphertext);
            assert_eq!(candidates[0].0, key);
            assert_eq!(candidates[0].2.as_bytes(), plaintext);
            assert!(candidates.windows(2).all(|pair| pair[0].1 >= pair[1].1));
        }
    }

    #[test]
    fn scores_match_the_plan() {
        let score = |plaintext: &str, key: u8| {
            let ciphertext: Vec<u8> = plaintext.bytes().map(|byte| byte ^ key).collect();
            crack_bytes(&ciphertext)
                .into_iter()
                .find(|c| c.0 == key)
                .map(|c| c.1)
                .unwrap()
        };
        let english = score("Cooking MC's like a pound of bacon", 0x58);
        assert!((-3.45..=-3.35).contains(&english), "{english}");
        let base64 = score(FOX_IN_BASE64, 0x42);
        assert!((-5.6..=-5.4).contains(&base64), "{base64}");
    }

    #[test]
    fn key_0x20_flips_case() {
        // Allowed even though it only flips the case of letters. The view is printable
        // text, so the candidate has to score better than it does.
        let candidates = crack_bytes(b"hELLOwORLDtHISiSatEST");
        assert_eq!(candidates[0].0, 0x20);
        assert_eq!(candidates[0].2, "HelloWorldThisIsATest");
    }

    #[test]
    fn keys_that_make_control_characters_are_skipped() {
        let ciphertext = strict_hex(SPHINX_HEX).unwrap();
        let candidates = crack_bytes(&ciphertext);
        // 0x2a ^ 0x20 = 0x0a turns every space into NUL
        assert!(candidates.iter().all(|c| c.0 != 0x0a));
        assert!(candidates.iter().all(|c| is_printable(&c.2)));
    }

    #[test]
    fn at_most_five_candidates_are_checked() {
        // Repeated Latin-1 symbols XOR to dozens of strings of common letters
        let soup = SYMBOL_SOUP;
        let latin1: Vec<u8> = soup.chars().map(|c| u32::from(c) as u8).collect();
        assert!(crack_bytes(&latin1).len() > MAX_CHECKED);

        let decoder = Decoder::<XorSingleByteDecoder>::new();
        let rejecting = Checker::<Athena>::new();
        let mut checked = Vec::new();
        let result = check_candidates(&decoder, soup, &best_candidates(soup), |candidate| {
            checked.push(candidate.to_string());
            CheckResult::new(&rejecting)
        });
        assert_eq!(checked.len(), MAX_CHECKED);
        assert!(!result.success);
    }

    #[test]
    fn checking_stops_at_the_first_identified_candidate() {
        let decoder = Decoder::<XorSingleByteDecoder>::new();
        let accepting = Checker::<Athena>::new();
        let mut calls = 0;
        let result = check_candidates(
            &decoder,
            FLAG_HEX,
            &best_candidates(FLAG_HEX),
            |candidate| {
                calls += 1;
                let mut check_result = CheckResult::new(&accepting);
                check_result.is_identified = candidate.starts_with("flag{");
                check_result
            },
        );
        assert!(result.success);
        assert_eq!(result.key.as_deref(), Some("0x5a"));
        // The flag isn't the best scoring candidate: the ones before it are checked and
        // rejected, the ones after it are never checked
        let rank = best_candidates(FLAG_HEX)
            .iter()
            .position(|c| c.key == 0x5a)
            .unwrap();
        assert!(rank > 0);
        assert_eq!(calls, rank + 1);
    }

    #[test]
    fn no_candidates() {
        for text in [
            "",
            "😀",
            FOX,
            "SGVsbG8gV29ybGQhIEhvdyBhcmUgeW91Pw==",
            "497420776173207468652062657374206f662074696d6573",
            "5d41402abc4b2a76b9719d911017c592",
            "aGVsbG8gd29ybGQ=",
        ] {
            assert!(
                best_candidates(text).is_empty(),
                "{text:?}: {:?}",
                best_candidates(text)
            );
            let result = crack(text);
            assert!(!result.success, "{text:?}");
            assert!(result.unencrypted_text.is_none(), "{text:?}");
            assert!(result.key.is_none(), "{text:?}");
        }
    }

    #[test]
    fn inputs_under_8_bytes_have_no_candidates() {
        // 7 bytes of the issue example: hex (which must not be re-read as Base64), Base64,
        // and as the Hexadecimal decoder outputs them
        for text in ["795a424344520a", "eVpCQ0RSCg==", "[_KX^P\u{6}"] {
            assert!(byte_views(text).is_empty(), "{text:?}");
            assert!(crack(text).unencrypted_text.is_none(), "{text:?}");
        }
        assert!(crack_bytes(b"yZBCDR\n").is_empty());
    }

    #[test]
    fn tiny_alphabets_are_not_cracked() {
        // XOR can only turn these into text over 2 to 4 letters, like "edueeteeet...",
        // which outscores English but no checker accepts, so no key is tried
        for text in [
            // Binary digits, read as hex: bytes 0x00, 0x01, 0x10 and 0x11
            "01001101 01100101 01100101 01110100 00100000 01101101 01100101 00100000 01100001 01110100",
            // Base64 of the same binary digits: bytes '0', '1' and ' '
            "MDEwMDExMDEgMDExMDAxMDEgMDExMDAxMDEgMDExMTAxMDAgMDAxMDAwMDAgMDExMDExMDEgMDExMDAxMDEgMDAxMDAwMDAgMDExMDAwMDEgMDExMTAxMDA=",
        ] {
            assert!(!byte_views(text).is_empty(), "{text:?}");
            assert!(best_candidates(text).is_empty(), "{text:?}");
            assert!(crack(text).unencrypted_text.is_none(), "{text:?}");
        }
    }

    #[test]
    fn letter_soup_is_not_handed_to_the_search() {
        // Repeated Latin-1 symbols, read as bytes, XOR to strings of common letters that
        // score like English but have no spaces and aren't Base64 or hex of anything. They
        // are checked, and rejected, but none may become a search node.
        assert!(!best_candidates(SYMBOL_SOUP).is_empty());
        let result = crack(SYMBOL_SOUP);
        assert!(!result.success, "{result:?}");
        assert!(result.unencrypted_text.is_none(), "{result:?}");
    }

    #[test]
    fn accented_text_has_no_raw_view() {
        // Accented letters alone are text, not bytes from an earlier decoder. Reading them
        // as bytes made every such node cost five checks; the search suite's
        // `unicode_exhausts` input is 48 of them.
        for text in [
            "éèêëàâäôöûüçéèêëàâäôöûüçéèêëàâäôöûüçéèêëàâäôöûüç",
            "Où est la bibliothèque ? Déjà vu, garçon, à bientôt",
        ] {
            assert!(raw_views(text).is_empty(), "{text:?}");
            assert!(best_candidates(text).is_empty(), "{text:?}");
            assert!(crack(text).unencrypted_text.is_none(), "{text:?}");
        }
        // English XORed with any key of 0x80 or more has a Latin-1 symbol or a C1 control
        // character, for its spaces (keys 0x80 to 0xBF) or for its letters (0xC0 to 0xFF),
        // so it still has a raw view
        for key in 0x80..=u8::MAX {
            let latin1: String = FOX.bytes().map(|byte| char::from(byte ^ key)).collect();
            assert!(!raw_views(&latin1).is_empty(), "key {key:#04x}");
        }
    }

    #[test]
    fn numeric_views_are_not_cracked() {
        // Base64 of decimal, octal or hex codes is another decoder's next layer. XOR turns
        // the digits into letter soup, and the English checker accepted
        // "ptqaputaptuaptua…" (the octal below XORed with 0x41)
        for text in [
            // Base64 of the octal codes of "hello world"
            "MTUwIDE0NSAxNTQgMTU0IDE1NyA0MCAxNjcgMTU3IDE2MiAxNTQgMTQ0",
            // Base64 of the decimal codes of "hello world"
            "MTA0IDEwMSAxMDggMTA4IDExMSAzMiAxMTkgMTExIDExNCAxMDggMTAw",
            BASE64_OF_HEX,
        ] {
            let views = byte_views(text);
            assert!(!views.is_empty(), "{text:?}");
            assert!(views.iter().all(|view| numeric_text(view)), "{text:?}");
            assert!(best_candidates(text).is_empty(), "{text:?}");
            assert!(crack(text).unencrypted_text.is_none(), "{text:?}");
        }
        assert!(numeric_text(b"150 145 154, 4d:65-65.74\n"));
        assert!(!numeric_text(b"150 145 154 lots of letters"));
        // A space, `e`, `t` and `a` never all XOR into numeric text, so English can't
        // become numeric text under any key
        for key in 1..=u8::MAX {
            assert!(!numeric_text(&[
                b' ' ^ key,
                b'e' ^ key,
                b't' ^ key,
                b'a' ^ key
            ]));
        }
    }

    #[test]
    fn hex_view_formats() {
        let bytes = strict_hex(SPHINX_HEX).unwrap();
        let spaced: Vec<String> = bytes.iter().map(|b| format!("{b:02x}")).collect();
        let prefixed: Vec<String> = bytes.iter().map(|b| format!("0x{b:02X}")).collect();
        for text in [
            spaced.join(" "),
            spaced.join(":"),
            prefixed.join(" "),
            format!("0x{SPHINX_HEX}"),
            format!("  {}\n", SPHINX_HEX.to_uppercase()),
        ] {
            assert_eq!(hex_view(&text), Some(bytes.clone()), "{text:?}");
        }
        // Odd digit counts, odd groups, other separators, too short
        for text in [
            &SPHINX_HEX[1..],
            "795 a42434452 0a454c0a",
            "79,5a,42,43,44,52,0a,45",
            "13-5-5-20 13-5 1-20 20-8-5",
            "77 101 101 116 32 109 101",
            "795a4243445",
            "0x 795a424344520a45",
        ] {
            assert_eq!(hex_view(text), None, "{text:?}");
        }
    }

    #[test]
    fn base64_view_formats() {
        let bytes = strict_hex(SPHINX_HEX).unwrap();
        assert_eq!(base64_view(SPHINX_BASE64), Some(bytes.clone()));
        assert_eq!(
            base64_view(SPHINX_BASE64.trim_end_matches('=')),
            Some(bytes)
        );
        // URL-safe alphabet
        let url_safe = FOX_BASE64.replace('+', "-").replace('/', "_");
        assert_eq!(base64_view(&url_safe), base64_view(FOX_BASE64));
        // Mixed alphabets, too much padding, inner whitespace
        for text in [
            "l6um47K2qqCo46Gx+-Optq6zsOOs",
            "eVpCQ0RSCkVMCkhGS0lBCg===",
            "eVpCQ0RS CkVMCkhGS0lBCg==",
        ] {
            assert_eq!(base64_view(text), None, "{text:?}");
        }
    }

    #[test]
    fn raw_views_cover_latin1_and_utf8() {
        // No byte-carrier characters: no view
        assert!(raw_views(FOX).is_empty());
        assert!(raw_views("日本語のテキストです、こんにちは").is_empty());
        // Accented letters alone are text too
        assert!(raw_views("café au lait, s'il vous plaît").is_empty());
        // Latin-1 only: one view, two if a byte is 0x80 or more
        assert_eq!(raw_views(SPHINX_RAW).len(), 1);
        assert_eq!(raw_views("café au lait ¤ 2 ± 1, s'il vous plaît").len(), 2);
        // Wider characters: the UTF-8 bytes
        assert_eq!(
            raw_views("ctrl\u{1}日本語").first().map(Vec::as_slice),
            Some("ctrl\u{1}日本語".as_bytes())
        );
    }

    #[test]
    fn decoder_metadata() {
        let decoder = Decoder::<XorSingleByteDecoder>::new();
        assert_eq!(decoder.get_name(), "Single-byte XOR");
        assert_eq!(
            decoder.get_link(),
            "https://en.wikipedia.org/wiki/XOR_cipher"
        );
        assert!((decoder.get_popularity() - 0.5).abs() < f32::EPSILON);
        // A cracker, not a decoder
        assert!(!decoder.get_tags().contains(&"decoder"));
        assert!(decoder.get_tags().contains(&"xor"));
    }

    #[test]
    fn is_registered() {
        let decoders = crate::filtration_system::get_decoder_by_name("Single-byte XOR");
        assert_eq!(decoders.components.len(), 1);
        // Cached results name their decoders, so the map key must be the name
        let decoder = crate::decoders::DECODER_MAP
            .get("Single-byte XOR")
            .expect("not in DECODER_MAP")
            .get::<()>();
        assert_eq!(decoder.get_name(), "Single-byte XOR");
    }
}
