//! Decompress XZ (`.xz`) and legacy LZMA (`.lzma`, "LZMA-alone") files.
//!
//! Both are containers for LZMA-compressed data:
//! * XZ (xz-utils, 7-Zip, Python's `lzma.compress`) starts with the stream header magic
//!   `FD 37 7A 58 5A 00`, which is `/Td6WFoA` in Base64. Its blocks hold LZMA2 data and a
//!   CRC-32, CRC-64 or SHA-256 check of it (or no check), and streams can be concatenated.
//! * LZMA-alone (`xz --format=lzma`, Python's `FORMAT_ALONE`, the LZMA SDK) is a 13-byte
//!   header, a properties byte, the dictionary size and the uncompressed size (all `FF` if
//!   it isn't known), followed by LZMA data without a checksum. The properties byte is
//!   almost always `5D`, so these files start with `XQ` in Base64 (`XQAAgAD/////////` with
//!   the default 8 MiB dictionary).
//!
//! Ciphey passes text between decoders, and compressed data is binary, so this decoder
//! reads the bytes itself from three textual forms:
//! * Base64 (standard or URL-safe, line breaks allowed),
//! * hex (optionally split into bytes by whitespace, `:`, `,`, `;`, `-` or `%`, or
//!   prefixed with `0x` or `\x`),
//! * the raw bytes as Latin-1 text, which is what the Hexadecimal and Binary decoders
//!   emit for bytes that aren't UTF-8, and what this decoder hands on when an XZ file
//!   holds another compressed file.
//!
//! Each form is recognised from its first few characters, so other text is rejected
//! without decoding or copying it. Decompression refuses dictionaries that need more than
//! [`MEM_LIMIT_KB`] before allocating them and stops at [`MAX_OUTPUT`] bytes, so a bomb
//! fails quickly instead of eating memory, and output the checker doesn't accept is only
//! passed on for more decoding up to [`MAX_CANDIDATE`] bytes.
//!
//! `.lzma` files with a properties byte other than `5D` (other lc/lp/pb settings) are not
//! recognised. xz, 7-Zip, Python and lzma-rust2 all write `5D` unless told otherwise, and
//! accepting any first byte would let far more text that isn't LZMA past the first check.
//!
//! Call `xz_decoder.crack` to use. It returns a [`CrackResult`]; check
//! `result.unencrypted_text.is_some()` to see if it decoded.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;
use base64::{engine::general_purpose, Engine as _};
use lzma_rust2::{Action, LzmaStream, Status, StreamResult, XzStream};

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// Decompressed output above this many bytes is rejected rather than truncated: a
/// fragment of the plaintext isn't the plaintext.
const MAX_OUTPUT: usize = 1024 * 1024;

/// Output the checker didn't accept is only handed on for more decoding up to this many
/// bytes, as in the Gzip decoder: decompressed output isn't bounded by the input's size,
/// and every decoder runs on every node of the search, so a few hundred bytes of XZ could
/// otherwise make a node of a megabyte.
const MAX_CANDIDATE: usize = 16 * 1024;

/// The most memory, in KiB, a file may need to be decompressed, as lzma-rust2 estimates
/// it from the header before allocating anything. It is almost all dictionary: about
/// 8,300 KiB for the default 8 MiB dictionary and 65,640 KiB for the 64 MiB one of
/// `xz -9`, the largest preset, so every preset fits and a header that claims a larger
/// dictionary (96 MiB is already 98,408 KiB) is refused.
const MEM_LIMIT_KB: u32 = 80 * 1024;

/// The magic bytes that start every XZ stream.
const XZ_MAGIC: [u8; 6] = [0xFD, 0x37, 0x7A, 0x58, 0x5A, 0x00];

/// The XZ magic in standard Base64. Six bytes fill exactly eight characters.
const XZ_MAGIC_BASE64: &str = "/Td6WFoA";

/// The XZ magic in URL-safe Base64.
const XZ_MAGIC_BASE64_URL: &str = "_Td6WFoA";

/// The smallest XZ stream: the 12-byte stream header, an index without records (8
/// bytes) and the 12-byte stream footer. `lzma.compress(b"")` is exactly this long.
const MIN_XZ_LEN: usize = 32;

/// The properties byte of an LZMA-alone file this decoder recognises: lc = 3, lp = 0 and
/// pb = 2, the default of every common encoder.
const LZMA_ALONE_PROPS: u8 = 0x5D;

/// The properties byte in Base64: `X` and the first character of the dictionary size,
/// whose low byte is zero for every dictionary size encoders use.
const LZMA_ALONE_BASE64: &str = "XQ";

/// The 13-byte LZMA-alone header and the 5 bytes that start the range decoder.
const MIN_LZMA_ALONE_LEN: usize = 18;

/// The XZ decoder, call:
/// `let xz_decoder = Decoder::<XzDecoder>::new()` to create a new instance
/// And then call:
/// `result = xz_decoder.crack(input)` to decompress XZ or LZMA-alone given as Base64, hex
/// or raw bytes
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::xz_decoder::XzDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_xz = Decoder::<XzDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // Python: base64.b64encode(lzma.compress(b"The quick brown fox jumps over the lazy dog"))
/// let result = decode_xz
///     .crack(
///         "/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAxKFK5cK4XlsAAUMrrVBuVx+2830BAAAAAARZWg==",
///         &checker,
///     )
///     .unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "The quick brown fox jumps over the lazy dog");
/// ```
pub struct XzDecoder;

impl Crack for Decoder<XzDecoder> {
    fn new() -> Decoder<XzDecoder> {
        Decoder {
            name: "XZ",
            description: "XZ and legacy .lzma files compress data with LZMA. XZ starts with FD 37 7A 58 5A 00, which is /Td6WFo in Base64; .lzma starts with 5D and a dictionary size, XQAA in Base64. Ciphey reads the bytes from Base64, hex or raw text and decompresses them.",
            link: "https://tukaani.org/xz/xz-file-format.txt",
            tags: vec!["xz", "lzma", "compression", "decoder"],
            popularity: 0.4,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decompresses `text` if it is an XZ or LZMA-alone file as Base64, hex or raw bytes,
    /// and checks the decompressed text. Fails (with `unencrypted_text` set to `None`) if
    /// `text` isn't one, doesn't decompress, decompresses to something that is neither
    /// text nor another compressed file, or decompresses to more than [`MAX_CANDIDATE`]
    /// bytes that the checker doesn't accept.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying XZ with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some((container, compressed)) = compressed_bytes(text) else {
            debug!("XZ failed: input is not XZ or LZMA-alone as Base64, hex or raw bytes");
            return results;
        };
        let Some(decompressed) = decompress_bounded(&compressed) else {
            debug!("XZ failed: the data did not decompress");
            return results;
        };

        let Some(decoded_text) = as_plaintext(&decompressed) else {
            // Another compressed file inside: hand it on as raw bytes for the next step
            // (this decoder again, or Gzip, Zlib, Bzip2). It is binary, so there is
            // nothing for the checker to look at.
            if is_compressed(&decompressed) && decompressed.len() <= MAX_CANDIDATE {
                debug!("XZ output is another compressed file; returning it unchecked");
                results.unencrypted_text = Some(vec![latin1_to_string(&decompressed)]);
                results.key = container.key();
            } else {
                info!("Failed to decode XZ: the output is binary, not text");
            }
            return results;
        };
        if !check_string_success(decoded_text, text) {
            info!(
                "Failed to decode XZ because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(decoded_text);
        if !checker_result.is_identified && decoded_text.len() > MAX_CANDIDATE {
            debug!(
                "XZ output is not plaintext and too long ({} bytes) to decode further",
                decoded_text.len()
            );
            return results;
        }
        results.unencrypted_text = Some(vec![decoded_text.to_string()]);
        results.key = container.key();
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// The two file formats this decoder reads.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Container {
    /// An `.xz` file: one or more XZ streams.
    Xz,
    /// A legacy `.lzma` file: the LZMA-alone header and LZMA data.
    LzmaAlone,
}

impl Container {
    /// Which format `bytes` are in, judged from their header without decompressing
    /// anything, or `None` if they are in neither.
    ///
    /// An XZ file has to be long enough for a stream header, an index and a stream
    /// footer and start with the XZ magic; lzma-rust2 checks the rest. An LZMA-alone file
    /// has no magic, so its header is checked instead: the properties byte `5D`, a
    /// dictionary of at least 4 KiB (the format's minimum), an uncompressed size that is
    /// unknown (`u64::MAX`) or at most [`MAX_OUTPUT`], and the zero byte every LZMA range
    /// coder starts with.
    fn of(bytes: &[u8]) -> Option<Container> {
        if bytes.len() >= MIN_XZ_LEN && bytes.starts_with(&XZ_MAGIC) {
            return Some(Container::Xz);
        }
        if bytes.len() < MIN_LZMA_ALONE_LEN || bytes[0] != LZMA_ALONE_PROPS {
            return None;
        }
        let dict_size = u32::from_le_bytes([bytes[1], bytes[2], bytes[3], bytes[4]]);
        let mut size = [0; 8];
        size.copy_from_slice(&bytes[5..13]);
        let size = u64::from_le_bytes(size);
        let plausible = dict_size >= lzma_rust2::DICT_SIZE_MIN
            && (size == u64::MAX || size <= MAX_OUTPUT as u64)
            && bytes[13] == 0x00;
        plausible.then_some(Container::LzmaAlone)
    }

    /// The key for a result from this format. XZ has no key; an LZMA-alone file says so,
    /// so the search path shows which of the two formats it was.
    fn key(self) -> Option<String> {
        match self {
            Container::Xz => None,
            Container::LzmaAlone => Some("LZMA-alone".to_string()),
        }
    }
}

/// Finds XZ or LZMA-alone bytes in `text`: Base64, hex, or raw bytes as Latin-1
/// characters. Only the first few characters are looked at unless they spell the start
/// of one of the two formats.
fn compressed_bytes(text: &str) -> Option<(Container, Vec<u8>)> {
    let trimmed = text.trim();
    let bytes = base64_view(trimmed)
        .or_else(|| hex_view(trimmed))
        .or_else(|| raw_view(text))?;
    let container = Container::of(&bytes)?;
    Some((container, bytes))
}

/// Base64, standard or URL-safe, that starts with the XZ magic (`/Td6WFoA`) or the
/// LZMA-alone properties byte (`XQ`). Whitespace (line breaks) is ignored and padding is
/// optional. `text` is already trimmed.
fn base64_view(text: &str) -> Option<Vec<u8>> {
    if ![XZ_MAGIC_BASE64, XZ_MAGIC_BASE64_URL, LZMA_ALONE_BASE64]
        .iter()
        .any(|prefix| text.starts_with(prefix))
    {
        return None;
    }
    let body: String = text.chars().filter(|c| !c.is_whitespace()).collect();
    let unpadded = body.trim_end_matches('=');
    if body.len() - unpadded.len() > 2 {
        return None;
    }
    // The Base64 decoder's engines. Both reject '=' inside the text.
    general_purpose::STANDARD_NO_PAD
        .decode(unpadded)
        .or_else(|_| general_purpose::URL_SAFE_NO_PAD.decode(unpadded))
        .ok()
}

/// Hex that starts with the XZ magic (`fd377a585a00`) or the LZMA-alone properties byte
/// (`5d`), in any case. Bytes can be separated by whitespace, `:`, `,`, `;`, `-` or `%`,
/// and each can have a `0x` or `\x` prefix. `text` is already trimmed.
fn hex_view(text: &str) -> Option<Vec<u8>> {
    // Cheap gate: the first digits have to spell one of the two starts
    if !starts_with_hex(text, &XZ_MAGIC) && !starts_with_hex(text, &[LZMA_ALONE_PROPS]) {
        return None;
    }

    let mut bytes = Vec::with_capacity(text.len() / 2);
    let mut digits = HexDigits::new(text.as_bytes());
    while let Some(high) = digits.next() {
        // A character that isn't hex or a separator, or an odd number of digits
        let (high, low) = (high?, digits.next()??);
        bytes.push((high << 4) | low);
    }
    Some(bytes)
}

/// Whether the hex digits at the start of `text` spell `prefix`. Reads no further than
/// that, and allocates nothing.
fn starts_with_hex(text: &str, prefix: &[u8]) -> bool {
    let mut digits = HexDigits::new(text.as_bytes());
    prefix.iter().all(|&byte| {
        digits.next() == Some(Some(byte >> 4)) && digits.next() == Some(Some(byte & 0x0F))
    })
}

/// XZ or LZMA-alone bytes as Latin-1 text, one character per byte. The Hexadecimal and
/// Binary decoders turn bytes that aren't UTF-8 (these formats never are) into this, and
/// so does this decoder for a compressed file inside a compressed file. Not trimmed: the
/// bytes can end with what looks like whitespace.
fn raw_view(text: &str) -> Option<Vec<u8>> {
    if !starts_with_latin1(text, &XZ_MAGIC) && !starts_with_latin1(text, &[LZMA_ALONE_PROPS]) {
        return None;
    }
    text.chars().map(|c| u8::try_from(c).ok()).collect()
}

/// Whether `text` starts with `prefix`, one Latin-1 character per byte.
fn starts_with_latin1(text: &str, prefix: &[u8]) -> bool {
    let mut chars = text.chars();
    prefix
        .iter()
        .all(|&byte| chars.next() == Some(char::from(byte)))
}

/// Iterates over the hex digits of a hex string, skipping the separators and prefixes
/// [`hex_view`] allows. Yields `Some(digit)` for each digit, and `None` for a character
/// that doesn't belong in hex. Separators and prefixes are only allowed between bytes.
/// The same as the Gzip decoder's.
struct HexDigits<'a> {
    /// The text being read.
    bytes: &'a [u8],
    /// Index of the next unread byte.
    position: usize,
    /// Whether the last digit read was the first half of a byte.
    mid_byte: bool,
}

impl<'a> HexDigits<'a> {
    /// Starts reading at the beginning of `bytes`.
    fn new(bytes: &'a [u8]) -> Self {
        HexDigits {
            bytes,
            position: 0,
            mid_byte: false,
        }
    }
}

impl Iterator for HexDigits<'_> {
    type Item = Option<u8>;

    fn next(&mut self) -> Option<Self::Item> {
        loop {
            let byte = *self.bytes.get(self.position)?;
            let next = self.bytes.get(self.position + 1).copied();
            if let Some(digit) = char::from(byte).to_digit(16) {
                if !self.mid_byte && byte == b'0' && matches!(next, Some(b'x' | b'X')) {
                    // A 0x prefix
                    self.position += 2;
                    continue;
                }
                self.position += 1;
                self.mid_byte = !self.mid_byte;
                return Some(Some(digit as u8));
            }
            let is_prefix = byte == b'\\' && matches!(next, Some(b'x' | b'X'));
            let is_separator = byte.is_ascii_whitespace() || b":,;-%".contains(&byte);
            if self.mid_byte || !(is_prefix || is_separator) {
                // Stop for good after the first bad character
                self.position = self.bytes.len();
                return Some(None);
            }
            self.position += if is_prefix { 2 } else { 1 };
        }
    }
}

/// Decompresses an XZ or LZMA-alone file, the way `xz -d` does.
///
/// The whole input has to be one file: for XZ, one or more complete streams, optionally
/// with stream padding (groups of four zero bytes) between and after them, each passing
/// its checks; for LZMA-alone, the header and LZMA data that ends exactly where the input
/// does. Returns `None` if the bytes are in neither format, are corrupt or truncated, have
/// anything after the end, need more than [`MEM_LIMIT_KB`] of memory (checked against
/// the header before the dictionary is allocated) or decompress to more than
/// [`MAX_OUTPUT`] bytes. Decompression stops at that limit, so a bomb costs about as much
/// as decompressing [`MAX_OUTPUT`] bytes.
fn decompress_bounded(compressed: &[u8]) -> Option<Vec<u8>> {
    match Container::of(compressed)? {
        Container::Xz => {
            // Concatenated streams are one file to `xz -d`, so they are here too. Anything
            // after the last stream that isn't stream padding or another stream is an
            // error.
            let mut stream = XzStream::new_mem_limit(true, MEM_LIMIT_KB);
            decompress_with(compressed, |input, output| {
                stream.process(input, output, Action::Finish)
            })
        }
        Container::LzmaAlone => {
            let mut stream = LzmaStream::new_mem_limit(MEM_LIMIT_KB, None);
            let output = decompress_with(compressed, |input, output| {
                stream.process(input, output, Action::Finish)
            })?;
            // The decoder takes in up to 40 bytes past the end of the LZMA data and hands
            // them back here. Like `xz -d`, a file with anything after its end is refused.
            if !stream.unused_input().is_empty() {
                debug!("LZMA-alone data is followed by trailing bytes");
                return None;
            }
            Some(output)
        }
    }
}

/// Feeds all of `input` to a sans-I/O lzma-rust2 decoder through `process`, collecting at
/// most [`MAX_OUTPUT`] bytes of output.
///
/// The output buffer starts at four times the input's size and doubles when the decoder
/// fills it, up to one byte over the limit, which tells an output of exactly
/// [`MAX_OUTPUT`] bytes apart from a longer one. Fails if the decoder reports an error,
/// stops making progress before the end of the stream (truncated input), stops before the
/// end of the input, or writes more than [`MAX_OUTPUT`] bytes.
fn decompress_with(
    input: &[u8],
    mut process: impl FnMut(&[u8], &mut [u8]) -> lzma_rust2::Result<StreamResult>,
) -> Option<Vec<u8>> {
    const CAPACITY: usize = MAX_OUTPUT + 1;
    let mut output = vec![0; input.len().saturating_mul(4).clamp(64, CAPACITY)];
    let (mut consumed, mut produced) = (0, 0);
    loop {
        let result = match process(&input[consumed..], &mut output[produced..]) {
            Ok(result) => result,
            Err(error) => {
                debug!("XZ data failed to decompress: {}", error);
                return None;
            }
        };
        consumed += result.bytes_consumed;
        produced += result.bytes_produced;
        if result.status == Status::StreamEnd {
            break;
        }
        if produced == output.len() {
            if produced > MAX_OUTPUT {
                debug!("XZ output is over {} bytes, giving up", MAX_OUTPUT);
                return None;
            }
            output.resize((output.len() * 2).min(CAPACITY), 0);
        } else if result.bytes_consumed == 0 && result.bytes_produced == 0 {
            // The decoder has all of the input and room for output, and is stuck
            debug!("XZ data ends before its stream does");
            return None;
        }
    }
    if produced > MAX_OUTPUT {
        debug!("XZ output is over {} bytes, giving up", MAX_OUTPUT);
        return None;
    }
    if consumed != input.len() {
        debug!("XZ data is followed by trailing bytes");
        return None;
    }
    output.truncate(produced);
    Some(output)
}

/// Whether binary output is itself a compressed file that a decoder reads from raw
/// bytes: XZ or LZMA-alone again (as [`Container::of`] judges it), gzip (`1F 8B 08`),
/// bzip2 (`BZh` and a block size digit) or zlib (`78` and a valid RFC 1950 header, the
/// first byte the Zlib decoder's raw view wants).
fn is_compressed(bytes: &[u8]) -> bool {
    let is_bzip2 = bytes.len() > 3 && bytes.starts_with(b"BZh") && matches!(bytes[3], b'1'..=b'9');
    let is_zlib = bytes.len() >= 8
        && bytes[0] == 0x78
        && u16::from_be_bytes([bytes[0], bytes[1]]).is_multiple_of(31)
        && bytes[1] & 0x20 == 0;
    Container::of(bytes).is_some() || bytes.starts_with(&[0x1F, 0x8B, 0x08]) || is_bzip2 || is_zlib
}

/// The decompressed bytes as text, if they are UTF-8 text without control characters
/// other than tab, line feed and carriage return. Binary files are rejected.
fn as_plaintext(data: &[u8]) -> Option<&str> {
    let text = std::str::from_utf8(data).ok()?;
    let is_text = !text
        .chars()
        .any(|c| c.is_control() && !matches!(c, '\t' | '\n' | '\r'));
    is_text.then_some(text)
}

/// One character per byte, U+0000 to U+00FF. The inverse of [`raw_view`].
fn latin1_to_string(bytes: &[u8]) -> String {
    bytes.iter().map(|&byte| char::from(byte)).collect()
}

#[cfg(test)]
mod tests {
    use super::{
        compressed_bytes, decompress_bounded, is_compressed, latin1_to_string, Container,
        XzDecoder, MAX_CANDIDATE, MAX_OUTPUT,
    };
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::{
            bzip2_decoder::Bzip2Decoder,
            crack_results::CrackResult,
            gzip_decoder::GzipDecoder,
            interface::{Crack, Decoder},
            zlib_decoder::ZlibDecoder,
        },
    };
    use base64::{engine::general_purpose, Engine as _};
    use lzma_rust2::{LzmaOptions, LzmaWriter, XzOptions, XzWriter};
    use std::io::Write;
    use std::time::{Duration, Instant};

    // Unless noted otherwise, the vectors were made with Python 3.9's lzma.compress(data)
    // (FORMAT_XZ with the default CRC-64 check and preset 6) or lzma.compress(data,
    // format=lzma.FORMAT_ALONE), written with base64.b64encode or .hex(). Each one
    // decompresses to the same text with Python's lzma.decompress and with xz 5.2.5
    // (`xz -dc --format=xz` or `--format=lzma`).

    const SPHINX: &str = "Sphinx of black quartz, judge my vow.";
    /// The XZ example in https://github.com/bee-san/Ciphey/issues/1024
    const SPHINX_XZ: &str = "/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQAkU3BoaW54IG9mIGJsYWNrIHF1YXJ0eiwganVkZ2UgbXkgdm93LgAAAABuPeHCKPDVhAABPSXSKWoBH7bzfQEAAAAABFla";
    /// The .lzma example in the issue
    const SPHINX_LZMA: &str =
        "XQAAgAD//////////wApnAkGs6iqYK0+rdZrCbrHCjNiT/hoUVL3L+59llK2C4kmTlnCHFQNG///xv0AAA==";
    /// The XZ example as hex
    const SPHINX_XZ_HEX: &str = "fd377a585a000004e6d6b4460200210116000000742fe5a3010024537068696e78206f6620626c61636b2071756172747a2c206a75646765206d7920766f772e000000006e3de1c228f0d58400013d25d2296a011fb6f37d010000000004595a";

    const FOX: &str = "The quick brown fox jumps over the lazy dog";
    /// lzma.compress(FOX)
    const FOX_XZ: &str = "/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAxKFK5cK4XlsAAUMrrVBuVx+2830BAAAAAARZWg==";
    /// lzma.compress(FOX, format=lzma.FORMAT_ALONE): unknown size, so it ends with an end
    /// marker
    const FOX_LZMA: &str =
        "XQAAgAD//////////wAqGgiiAyVm8Ut4xaIF/y7m2dIgGq00+OId6EE2+twGabs85BA0Jwnrs2bsGhcv//zOkAA=";
    /// The same as hex
    const FOX_LZMA_HEX: &str = "5d00008000ffffffffffffffff002a1a08a2032566f14b78c5a205ff2ee6d9d2201aad34f8e21de84136fadc0669bb3ce410342709ebb366ec1a172ffffcce9000";

    const FLAG: &str = "flag{xz_utils_lzma2}";

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn crack(text: &str) -> CrackResult {
        Decoder::<XzDecoder>::new().crack(text, &get_athena_checker())
    }

    /// Runs the decoder and returns the first decoded string, if any
    fn decode(text: &str) -> Option<String> {
        crack(text).unencrypted_text.map(|texts| texts[0].clone())
    }

    fn base64_bytes(text: &str) -> Vec<u8> {
        general_purpose::STANDARD
            .decode(text)
            .expect("valid Base64")
    }

    fn to_hex(bytes: &[u8]) -> String {
        bytes.iter().map(|byte| format!("{byte:02x}")).collect()
    }

    /// `data` as an XZ file made by lzma-rust2's encoder, at preset 0 (a 256 KiB
    /// dictionary) to keep the tests fast
    fn xz(data: &[u8]) -> Vec<u8> {
        let mut writer = XzWriter::new(Vec::new(), XzOptions::with_preset(0)).unwrap();
        writer.write_all(data).unwrap();
        writer.finish().unwrap()
    }

    /// `data` as an LZMA-alone file of unknown size, made by lzma-rust2's encoder
    fn lzma_alone(data: &[u8]) -> Vec<u8> {
        let options = LzmaOptions::with_preset(0);
        let mut writer = LzmaWriter::new_use_header(Vec::new(), &options, None).unwrap();
        writer.write_all(data).unwrap();
        writer.finish().unwrap()
    }

    #[test]
    fn decodes_issue_example_xz() {
        // Athena doesn't recognise this sentence as English, so only the text is checked
        assert_eq!(decode(SPHINX_XZ).as_deref(), Some(SPHINX));
        assert_eq!(decode(SPHINX_XZ_HEX).as_deref(), Some(SPHINX));
    }

    #[test]
    fn decodes_issue_example_lzma() {
        let result = crack(SPHINX_LZMA);
        assert_eq!(result.unencrypted_text.unwrap(), [SPHINX]);
        assert_eq!(result.key.as_deref(), Some("LZMA-alone"));
    }

    #[test]
    fn decodes_and_identifies_fox_xz() {
        let result = crack(FOX_XZ);
        assert!(result.success, "Athena should identify the plaintext");
        assert_eq!(result.unencrypted_text.unwrap(), [FOX]);
        assert_eq!(result.decoder, "XZ");
        assert!(result.key.is_none(), "XZ has no key");
    }

    #[test]
    fn decodes_and_identifies_fox_lzma() {
        for text in [FOX_LZMA, FOX_LZMA_HEX] {
            let result = crack(text);
            assert!(result.success, "Athena should identify the plaintext");
            assert_eq!(result.unencrypted_text.unwrap(), [FOX], "{text}");
            assert_eq!(result.key.as_deref(), Some("LZMA-alone"));
        }
    }

    #[test]
    fn decodes_every_check_type() {
        for (check, xz) in [
            // lzma.compress(FOX, check=lzma.CHECK_NONE)
            ("none", "/Td6WFoAAAD/EtlBAgAhARYAAAB0L+WjAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAAAE7K1OjiLAGcp56AQAAAAAAWVo="),
            // check=lzma.CHECK_CRC32
            ("CRC-32", "/Td6WFoAAAFpIt42AgAhARYAAAB0L+WjAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAOaNPQQABPytXZuTUkEKZDQEAAAAAAVla"),
            ("CRC-64", FOX_XZ),
            // check=lzma.CHECK_SHA256
            ("SHA-256", "/Td6WFoAAArh+wyhAgAhARYAAAB0L+WjAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAA16j7swfXgJRpypq8sAguT41WUeRtPNt2LQLQvzfJ5ZIAAVsr9Mh11RibS5oBAAAAAApZWg=="),
        ] {
            let result = crack(xz);
            assert!(result.success, "{check}");
            assert_eq!(result.unencrypted_text.unwrap(), [FOX], "{check}");
        }
    }

    #[test]
    fn decodes_every_preset() {
        // lzma.compress(FOX, preset=n) and lzma.compress(FOX, format=lzma.FORMAT_ALONE,
        // preset=n) for n = 0 to 9. For this short text the presets only differ in the
        // dictionary size: 256 KiB, 1, 2, 4, 4, 8, 8, 16, 32 and 64 MiB. Presets 3 and 4,
        // and 5 and 6, give the same files, so they are here once. Preset 9 needs a 64 MiB
        // dictionary, the most of any preset, and has to fit the memory limit.
        let xz_presets = [
            "/Td6WFoAAATm1rRGAgAhAQwAAACPmEGcAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAxKFK5cK4XlsAAUMrrVBuVx+2830BAAAAAARZWg==",
            "/Td6WFoAAATm1rRGAgAhARAAAACocI6GAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAxKFK5cK4XlsAAUMrrVBuVx+2830BAAAAAARZWg==",
            "/Td6WFoAAATm1rRGAgAhARIAAAAjuIcsAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAxKFK5cK4XlsAAUMrrVBuVx+2830BAAAAAARZWg==",
            "/Td6WFoAAATm1rRGAgAhARQAAAD/5+wJAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAxKFK5cK4XlsAAUMrrVBuVx+2830BAAAAAARZWg==",
            FOX_XZ,
            "/Td6WFoAAATm1rRGAgAhARgAAABHWDpDAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAxKFK5cK4XlsAAUMrrVBuVx+2830BAAAAAARZWg==",
            "/Td6WFoAAATm1rRGAgAhARoAAADMkDPpAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAxKFK5cK4XlsAAUMrrVBuVx+2830BAAAAAARZWg==",
            "/Td6WFoAAATm1rRGAgAhARwAAAAQz1jMAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAxKFK5cK4XlsAAUMrrVBuVx+2830BAAAAAARZWg==",
        ];
        let lzma_presets = [
            "XQAABAD//////////wAqGgiiAyVm8Ut4xaIF/y7m2dIgGq00+OId6EE2+twGabs85BA0Jwnrs2bsGhcv//zOkAA=",
            "XQAAEAD//////////wAqGgiiAyVm8Ut4xaIF/y7m2dIgGq00+OId6EE2+twGabs85BA0Jwnrs2bsGhcv//zOkAA=",
            "XQAAIAD//////////wAqGgiiAyVm8Ut4xaIF/y7m2dIgGq00+OId6EE2+twGabs85BA0Jwnrs2bsGhcv//zOkAA=",
            "XQAAQAD//////////wAqGgiiAyVm8Ut4xaIF/y7m2dIgGq00+OId6EE2+twGabs85BA0Jwnrs2bsGhcv//zOkAA=",
            FOX_LZMA,
            "XQAAAAH//////////wAqGgiiAyVm8Ut4xaIF/y7m2dIgGq00+OId6EE2+twGabs85BA0Jwnrs2bsGhcv//zOkAA=",
            "XQAAAAL//////////wAqGgiiAyVm8Ut4xaIF/y7m2dIgGq00+OId6EE2+twGabs85BA0Jwnrs2bsGhcv//zOkAA=",
            "XQAAAAT//////////wAqGgiiAyVm8Ut4xaIF/y7m2dIgGq00+OId6EE2+twGabs85BA0Jwnrs2bsGhcv//zOkAA=",
        ];
        for text in xz_presets.into_iter().chain(lzma_presets) {
            assert_eq!(decode(text).as_deref(), Some(FOX), "{text}");
        }
    }

    #[test]
    fn decodes_compressed_lzma2_chunks() {
        // The fox is so short that xz stores it uncompressed inside the LZMA2 block. This
        // one is long enough to be compressed. It is the medium bench input.
        let result = crack("/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4ABTAEpdACaZbOggNplzov9xgoqk/LcqCEHcBaaF/V9XatyFem4QukOy3e++ZSRkk2d2OD8p9MbyvtJXkkg5fXT5gLesThztSoIpxURIAM0AAAAAxd7IaPdknIIAAWZU5+wnfx+2830BAAAAAARZWg==");
        assert!(result.success, "Athena should identify the plaintext");
        assert_eq!(
            result.unencrypted_text.unwrap(),
            ["Meet me at the old lighthouse after midnight and bring the map, the key and a torch."]
        );
    }

    #[test]
    fn decodes_lzma_alone_with_a_known_size() {
        // LzmaWriter::new_use_header(.., Some(43)) in lzma-rust2 0.21.0: the size is in the
        // header and there is no end marker. Python, xz and CyberChef's LZMA Decompress
        // decode it too.
        let result = crack(
            "XQAAgAArAAAAAAAAAAAqGgiiAyVm8Ut4xaIF/y7m2dIgGq00+OId6EE2+twGabs85BA0Jwnrs2bh+c6E",
        );
        assert_eq!(result.unencrypted_text.unwrap(), [FOX]);
        assert_eq!(result.key.as_deref(), Some("LZMA-alone"));
    }

    #[test]
    fn decodes_concatenated_streams() {
        // lzma.compress(b"The quick brown fox ") + lzma.compress(b"jumps over the lazy dog").
        // xz -dc and Python both give the whole sentence.
        let two_streams = "/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQATVGhlIHF1aWNrIGJyb3duIGZveCAAIEFC5acaLXcAASwU+AptAx+2830BAAAAAARZWv03elhaAAAE5ta0RgIAIQEWAAAAdC/lowEAFmp1bXBzIG92ZXIgdGhlIGxhenkgZG9nAADjZCTmHjHqggABLxeBCEmxH7bzfQEAAAAABFla";
        assert_eq!(decode(two_streams).as_deref(), Some(FOX));

        // Stream padding, groups of four zero bytes, may go between and after streams.
        // xz -dc accepts all of these.
        let fox = base64_bytes(FOX_XZ);
        let padded = [
            ([fox.as_slice(), &[0; 4]].concat(), FOX.to_string()),
            ([fox.as_slice(), &[0; 8], &fox].concat(), FOX.repeat(2)),
            ([fox.as_slice(), &fox, &fox].concat(), FOX.repeat(3)),
        ];
        for (compressed, expected) in padded {
            assert_eq!(
                decompress_bounded(&compressed).as_deref(),
                Some(expected.as_bytes())
            );
        }
    }

    #[test]
    fn decodes_uppercase_and_delimited_hex() {
        for compressed in [base64_bytes(FOX_XZ), base64_bytes(FOX_LZMA)] {
            let spaced: Vec<String> = compressed.iter().map(|b| format!("{b:02x}")).collect();
            let hex = to_hex(&compressed);
            let forms = [
                hex.to_uppercase(),
                spaced.join(" "),
                spaced.join(":"),
                spaced.join("\n"),
                // xxd -i
                compressed
                    .iter()
                    .map(|b| format!("0x{b:02x}"))
                    .collect::<Vec<_>>()
                    .join(", "),
                // Python / C escapes
                compressed.iter().map(|b| format!("\\x{b:02X}")).collect(),
                format!("0x{hex}"),
                format!("  {hex}\n"),
            ];
            for form in forms {
                assert_eq!(decode(&form).as_deref(), Some(FOX), "{form}");
            }
        }
    }

    #[test]
    fn decodes_wrapped_unpadded_and_url_safe_base64() {
        // The URL-safe form from the issue plan, with `_` and `-`
        let url_safe = "_Td6WFoAAATm1rRGAgAhARYAAAB0L-WjAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAxKFK5cK4XlsAAUMrrVBuVx-2830BAAAAAARZWg==";
        assert_eq!(
            general_purpose::URL_SAFE.decode(url_safe).unwrap(),
            base64_bytes(FOX_XZ)
        );
        for base64 in [FOX_XZ, FOX_LZMA] {
            let wrapped: String = base64
                .as_bytes()
                .chunks(20)
                .map(|line| format!("{}\r\n", std::str::from_utf8(line).unwrap()))
                .collect();
            let forms = [
                wrapped,
                base64.trim_end_matches('=').to_string(),
                general_purpose::URL_SAFE.encode(base64_bytes(base64)),
                format!("\n{base64}\n"),
            ];
            for form in forms {
                assert_eq!(decode(&form).as_deref(), Some(FOX), "{form}");
            }
        }
        assert_eq!(decode(url_safe).as_deref(), Some(FOX));
    }

    #[test]
    fn decodes_raw_latin1_bytes_from_the_hexadecimal_decoder() {
        // The Hexadecimal and Binary decoders turn XZ or LZMA-alone bytes into this
        for base64 in [FOX_XZ, FOX_LZMA] {
            let raw = latin1_to_string(&base64_bytes(base64));
            assert_eq!(decode(&raw).as_deref(), Some(FOX));
        }
    }

    #[test]
    fn identifies_a_flag() {
        for text in [
            "/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQATZmxhZ3t4el91dGlsc19sem1hMn0ARd5h+uGe/UYAASwU+AptAx+2830BAAAAAARZWg==",
            "XQAAgAD//////////wAzGwhHWEd6K75Ymkebw2KhGkZOeR3p05l//+n3gAA=",
        ] {
            let result = crack(text);
            assert!(result.success, "LemmeKnow should identify the CTF flag");
            assert_eq!(result.unencrypted_text.unwrap(), [FLAG]);
        }
    }

    #[test]
    fn returns_nested_xz_for_another_xz_step() {
        // base64.b64encode(lzma.compress(lzma.compress(FOX)))
        let nested = "/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQBj/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAxKFK5cK4XlsAAUMrrVBuVx+2830BAAAAAARZWgClhZHk7FObSAABfGSQJtPpH7bzfQEAAAAABFla";
        let result = crack(nested);
        assert!(
            !result.success,
            "the inner XZ file is binary, not plaintext"
        );
        let inner = result.unencrypted_text.expect("the inner XZ file");
        assert_eq!(inner[0], latin1_to_string(&base64_bytes(FOX_XZ)));

        // Second step, on the first step's output
        let result = crack(&inner[0]);
        assert!(result.success);
        assert_eq!(result.unencrypted_text.unwrap(), [FOX]);
    }

    #[test]
    fn hands_other_compressed_files_on_as_raw_bytes() {
        let athena = get_athena_checker();
        let unwrap = |text: &str| crack(text).unencrypted_text.expect(text)[0].clone();

        // base64.b64encode(lzma.compress(gzip.compress(FOX, mtime=0))): Gzip reads the
        // raw bytes
        let gzip = unwrap("/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQA9H4sIAAAAAAAC/wvJSFUoLM1MzlZIKsovz1NIy69QyCrNLShWyC9LLVIoAUrnJFZVKqTkpwMAOaNPQSsAAAAAAABn3ytEb7v9YAABVj5SUgYNH7bzfQEAAAAABFla");
        assert!(gzip.starts_with("\u{1f}\u{8b}\u{8}"));
        let result = Decoder::<GzipDecoder>::new().crack(&gzip, &athena);
        assert_eq!(result.unencrypted_text.unwrap(), [FOX]);

        // lzma.compress(zlib.compress(FOX)): so does Zlib
        let zlib = unwrap("/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQAxeJwLyUhVKCzNTM5WSCrKL89TSMuvUMgqzS0oVsgvSy1SKAFK5yRWVSqk5KcDAFvcD9oAAAAy282hgAtv6gABSjIkQ8fiH7bzfQEAAAAABFla");
        let result = Decoder::<ZlibDecoder>::new().crack(&zlib, &athena);
        assert_eq!(result.unencrypted_text.unwrap(), [FOX]);

        // lzma.compress(bz2.compress(FOX)): and Bzip2
        let bzip2 = unwrap("/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQBPQlpoOTFBWSZTWUWd7mEAAAQTgEAABAA////wIAAxRoaAAAAx6ammTIYRtG1HYmIISe16oVNlZbEl4+JgsfiYOd1MCW+c6F3JFOFCQRZ3uYQAu4oHBs1BUbYAAWhQcAXJ5h+2830BAAAAAARZWg==");
        assert!(bzip2.starts_with("BZh9"));
        let result = Decoder::<Bzip2Decoder>::new().crack(&bzip2, &athena);
        assert_eq!(result.unencrypted_text.unwrap(), [FOX]);

        // lzma.compress(lzma.compress(FOX, format=lzma.FORMAT_ALONE)) and the other way
        // round. Each step's key names its own container.
        let result = crack("/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQBAXQAAgAD//////////wAqGgiiAyVm8Ut4xaIF/y7m2dIgGq00+OId6EE2+twGabs85BA0Jwnrs2bsGhcv//zOkAAAAAAA4gxcu//rsncAAVlBMCIkSh+2830BAAAAAARZWg==");
        assert_eq!(result.key, None);
        let result = crack(&result.unencrypted_text.unwrap()[0]);
        assert_eq!(result.unencrypted_text.unwrap(), [FOX]);
        assert_eq!(result.key.as_deref(), Some("LZMA-alone"));

        let result = crack("XQAAgAD//////////wB+jctFguaDOPnh7dL5R18V5H2aDOuBK9cZ6/fgNBT+hnIy0XuxkYVzorIT5KtIIOqRLFu38uhuySsmMrhl4Q2VDm1LF11G6smf/duCIOPWJG1kEBejRlGIYK4vhW3x3q4aN2/t7CvW///Gm0AA");
        assert_eq!(result.key.as_deref(), Some("LZMA-alone"));
        let result = crack(&result.unencrypted_text.unwrap()[0]);
        assert_eq!(result.unencrypted_text.unwrap(), [FOX]);
        assert_eq!(result.key, None);
    }

    #[test]
    fn recognises_compressed_output() {
        let fox = FOX.as_bytes();
        let gzip = base64_bytes(
            "H4sIAAAAAAAC/wvJSFUoLM1MzlZIKsovz1NIy69QyCrNLShWyC9LLVIoAUrnJFZVKqTkpwMAOaNPQSsAAAA=",
        );
        let zlib =
            base64_bytes("eJwLyUhVKCzNTM5WSCrKL89TSMuvUMgqzS0oVsgvSy1SKAFK5yRWVSqk5KcDAFvcD9o=");
        let bzip2 = base64_bytes("QlpoOTFBWSZTWUWd7mEAAAQTgEAABAA////wIAAxRoaAAAAx6ammTIYRtG1HYmIISe16oVNlZbEl4+JgsfiYOd1MCW+c6F3JFOFCQRZ3uYQ=");
        for compressed in [
            base64_bytes(FOX_XZ),
            base64_bytes(FOX_LZMA),
            gzip,
            zlib,
            bzip2,
            xz(fox),
            lzma_alone(fox),
        ] {
            assert!(is_compressed(&compressed), "{compressed:02x?}");
        }
        for binary in [
            &b"\x00\x01\x02\x03\x04\x05\x06\x07"[..],
            b"BZh",
            // bzip2 block sizes are 1 to 9
            b"BZh01AY&SY",
            b"x\x9c",
            // 78 9D fails the RFC 1950 header check
            b"x\x9d\x00\x00\x00\x00\x00\x00",
            b"\x1f\x8b",
        ] {
            assert!(!is_compressed(binary), "{binary:02x?}");
        }
    }

    #[test]
    fn rejects_corrupt_truncated_and_trailing_data() {
        let fox_xz = base64_bytes(FOX_XZ);
        let fox_lzma = base64_bytes(FOX_LZMA);
        for (case, text) in [
            // One byte of the stored text changed (T -> 0x14): Python "Corrupt input
            // data", xz "Compressed data is corrupt" (the CRC-64 doesn't match)
            ("corrupt", "/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQAqFGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAxKFK5cK4XlsAAUMrrVBuVx+2830BAAAAAARZWg=="),
            // Cut off inside the index: xz "Unexpected end of input"
            ("truncated", "/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAxKFK5cK4XlsAAUMrrVBuVx+2830="),
            // + "GARBAGE": xz "Unexpected end of input"
            ("trailing garbage", "/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAxKFK5cK4XlsAAUMrrVBuVx+2830BAAAAAARZWkdBUkJBR0U="),
            // + "GARBAGE": xz "Compressed data is corrupt" (Python ignores it)
            (".lzma trailing garbage", "XQAAgAD//////////wAqGgiiAyVm8Ut4xaIF/y7m2dIgGq00+OId6EE2+twGabs85BA0Jwnrs2bsGhcv//zOkABHQVJCQUdF"),
            // The end marker cut off: xz "Unexpected end of input"
            (".lzma truncated", "XQAAgAD//////////wAqGgiiAyVm8Ut4xaIF/y7m2dIgGq00+OId6EE2+twGabs85BA0Jwnrs2bsGhc="),
        ] {
            assert_eq!(decode(text), None, "{case}");
        }

        for (case, compressed) in [
            // Stream padding has to be a multiple of four bytes: xz "Compressed data is
            // corrupt"
            ("3 bytes of padding", [fox_xz.as_slice(), &[0; 3]].concat()),
            ("XZ + one byte", [fox_xz.as_slice(), b"x"].concat()),
            (
                "XZ + a truncated stream",
                [fox_xz.as_slice(), &fox_xz[..40]].concat(),
            ),
            // xz: "Compressed data is corrupt" for both (Python accepts the "x")
            (".lzma + a zero byte", [fox_lzma.as_slice(), &[0]].concat()),
            (".lzma + one byte", [fox_lzma.as_slice(), b"x"].concat()),
            (".lzma truncated in the header", fox_lzma[..20].to_vec()),
            // The range coder's first byte has to be zero
            ("bad range coder start", {
                let mut bad = fox_lzma.clone();
                bad[13] = 1;
                bad
            }),
        ] {
            assert_eq!(decompress_bounded(&compressed), None, "{case}");
            assert_eq!(decode(&latin1_to_string(&compressed)), None, "{case}");
        }

        // A known size and anything after the data
        let known_size = base64_bytes(
            "XQAAgAArAAAAAAAAAAAqGgiiAyVm8Ut4xaIF/y7m2dIgGq00+OId6EE2+twGabs85BA0Jwnrs2bh+c6E",
        );
        assert!(decompress_bounded(&known_size).is_some());
        for trailing in [&b"\x00"[..], b"x", b"GARBAGE"] {
            let compressed = [known_size.as_slice(), trailing].concat();
            assert_eq!(decompress_bounded(&compressed), None, "{trailing:?}");
        }
    }

    #[test]
    fn refuses_dictionaries_over_the_memory_limit() {
        // xz -dc decodes all of these. They are the fox vectors with the dictionary size
        // raised (and, for XZ, the block header CRC-32 recomputed).
        let start = Instant::now();
        for (case, text) in [
            ("XZ, 96 MiB", "/Td6WFoAAATm1rRGAgAhAR0AAAB1qOR0AQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAxKFK5cK4XlsAAUMrrVBuVx+2830BAAAAAARZWg=="),
            ("XZ, 4 GiB - 1", "/Td6WFoAAATm1rRGAgAhASgAAADmoBGzAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAxKFK5cK4XlsAAUMrrVBuVx+2830BAAAAAARZWg=="),
            (".lzma, 96 MiB", "XQAAAAb//////////wAqGgiiAyVm8Ut4xaIF/y7m2dIgGq00+OId6EE2+twGabs85BA0Jwnrs2bsGhcv//zOkAA="),
            // From the issue plan: Python decodes it too
            (".lzma, 1.5 GiB", "XQAAAGD//////////wAqGgiiAyVm8Ut4xaIF/y7m2dIgGq00+OId6EE2+twGabs85BA0Jwnrs2bsGhcv//zOkAA="),
        ] {
            assert!(compressed_bytes(text).is_some(), "{case}: the header is fine");
            assert_eq!(decode(text), None, "{case}");
        }
        // Refused from the header, before anything is allocated
        assert!(
            start.elapsed() < Duration::from_millis(500),
            "took {:?}",
            start.elapsed()
        );
    }

    #[test]
    fn rejects_empty_files() {
        // lzma.compress(b"") and lzma.compress(b"", format=lzma.FORMAT_ALONE) are valid
        // files without any text in them
        for hex in [
            "fd377a585a000004e6d6b446000000001cdf44211fb6f37d010000000004595a",
            "5d00008000ffffffffffffffff0083fffbffffc0000000",
        ] {
            let compressed: Vec<u8> = (0..hex.len())
                .step_by(2)
                .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
                .collect();
            assert_eq!(decompress_bounded(&compressed), Some(Vec::new()), "{hex}");
            assert_eq!(decode(hex), None, "{hex}");
        }
    }

    #[test]
    fn rejects_binary_output() {
        // lzma.compress(bytes(range(256))): not UTF-8
        let binary = "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj4AD/AOpdAAAAUlAKhPmbsoAhqWnWJ+A+BlpfBI1T1AS6OVcFCcFVJN6duHFZMWChn/lvSXPyyOqMuhqLKWkhgP4zg2avRm3snomKC4PwPA6Jjj/tX+eekNkc/zL0suA5UbLSFBW0xXG62wbjeZqfuzjBsACskwuqBhkDEggVW5vISPAyLv4toIfI8KTg0lHrjWdWkrJNhMXxhjHfamJbwnkt2fc8c7p0dAfYPKlWIiShZvhahF8wZ9L2S0kufyDr2/gQDpR4d8c/a++0zZXib/ZEbgbPC4Iay9t68FeNmP+QwD7mwRJBde4DKJbrCTcOHgAAALA622UvS0FyAAGGAoACAAAtEqGfscRn+wIAAAAABFla";
        assert_eq!(
            decompress_bounded(&base64_bytes(binary)),
            Some((0..=255).collect())
        );
        assert_eq!(decode(binary), None);
        // lzma.compress(b"\x1b[31mred alert\x1b[0m"): UTF-8 with control characters
        assert_eq!(
            decode("/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQARG1szMW1yZWQgYWxlcnQbWzBtAAAATMj+wTpWC9MAASoSSwhUvB+2830BAAAAAARZWg=="),
            None
        );
    }

    #[test]
    fn stops_a_bomb_at_the_size_limit() {
        // lzma.compress(b"A" * 2 MiB) as XZ (440 bytes) and LZMA-alone (385 bytes)
        let xz_bomb = "/Td6WFoAAATm1rRGAgAhARYAAAB0L+Wj//8RAWxdACDv+7/+o7Fe5fg/sqomVfhocEFwFQ+N/R5MG4pCtxn0aRhxrmYjiopNL6MN2X+m44wjEVPgWRjFdYrid/i2lH8MasDedElk4ulcU7IE2PdEDKtfDW1G6eXDdoi3llestk3haR1v+0uIEGxCy4g/XACP0E6vJiiUcR89jyThcJ6nI1/sKMuF0ZWYin4qkfIndfcZwAaYTZj92K/VkA/EJVP49ZE2MQWlsO5vwXBNRwzRkRGqrWAdus6xJxhcWYbpZlJYvul2rFnk5VsFCPnH2q38+1IrdM0eWyBC+d1TPfgpZAk7gMsqbN+1O/DEvS5fqg8+S2ZCkBMO/xCT+HF4WfgLzf+VKEYPqfx83vuaMC5WwI+F84OBwGXEJVP49ZE2MQWlsO5vwXBNRwzRkRGqrWAdus6xJxhcWYbpZlJYvul2rFnk5VsFCPnH2q38+1IrdM0eWyBC+d1TPfgpZAk7gMsqbN+1O/DEvEgn5liAAO0ABQAcpiTxAAAATLXbotLYz9wAAZMDgICAAYbP71+xxGf7AgAAAAAEWVo=";
        let lzma_bomb = "XQAAgAD//////////wAg7/u//qOxXuX4P7KqJlX4aHBBcBUPjf0eTBuKQrcZ9GkYca5mI4qKTS+jDdl/puOMIxFT4FkYxXWK4nf4tpR/DGrA3nRJZOLpXFOyBNj3RAyrXw1tRunlw3aIt5ZXrLZN4Wkdb/tLiBBsQsuIP1wAj9BOryYolHEfPY8k4XCepyNf7CjLhdGVmIp+KpHyJ3X3GcAGmE2Y/div1ZAPxCVT+PWRNjEFpbDub8FwTUcM0ZERqq1gHbrOsScYXFmG6WZSWL7pdqxZ5OVbBQj5x9qt/PtSK3TNHlsgQvndUz34KWQJO4DLKmzftTvwxL0uX6oPPktmQpATDv8Qk/hxeFn4C83/lShGD6n8fN77mjAuVsCPhfODgcBlxCVT+PWRNjEFpbDub8FwTUcM0ZERqq1gHbrOsScYXFmG6WZSWL7pdqxZ5OVbBQj5x9qt/PtSK3TNHlsgQvndUz34KWQJO4DLKmzftTvwxLxkDSXSWP//mggAAA==";
        // Built here: 8 MiB of "A" from lzma-rust2's encoder
        let eight_mib = vec![b'A'; 8 * 1024 * 1024];
        let built = [xz(&eight_mib), lzma_alone(&eight_mib)];

        let start = Instant::now();
        for bomb in [xz_bomb, lzma_bomb] {
            assert_eq!(decompress_bounded(&base64_bytes(bomb)), None);
            assert_eq!(decode(bomb), None);
        }
        for bomb in &built {
            assert_eq!(decompress_bounded(bomb), None);
            assert_eq!(decode(&general_purpose::STANDARD.encode(bomb)), None);
        }
        assert!(
            start.elapsed() < Duration::from_secs(5),
            "took {:?}",
            start.elapsed()
        );
    }

    #[test]
    fn output_size_limit_is_inclusive() {
        let at_limit = vec![b'A'; MAX_OUTPUT];
        let over_limit = vec![b'A'; MAX_OUTPUT + 1];
        for compress in [xz, lzma_alone] {
            assert_eq!(
                decompress_bounded(&compress(&at_limit)).as_deref(),
                Some(at_limit.as_slice())
            );
            assert_eq!(decompress_bounded(&compress(&over_limit)), None);
        }

        // The limit is for all XZ streams together
        let half = xz(&vec![b'A'; MAX_OUTPUT / 2 + 1]);
        assert_eq!(decompress_bounded(&[half.clone(), half].concat()), None);
    }

    #[test]
    fn grows_the_output_buffer_for_data_that_compresses_well() {
        // The buffer starts at four times the input's size, which this is far over
        let text: Vec<u8> = (0..200_000u32)
            .map(|i| b"abcdefghij"[(i % 10) as usize])
            .collect();
        for compressed in [xz(&text), lzma_alone(&text)] {
            assert!(compressed.len() * 4 < text.len() / 100);
            assert_eq!(
                decompress_bounded(&compressed).as_deref(),
                Some(text.as_slice())
            );
        }
    }

    #[test]
    fn long_output_is_only_kept_if_the_checker_accepts_it() {
        let crack_xz = |data: &[u8]| crack(&general_purpose::STANDARD.encode(xz(data)));

        // Not plaintext: handed on for more decoding up to the limit, dropped above it
        let result = crack_xz(&vec![b'A'; MAX_CANDIDATE]);
        assert!(!result.success);
        assert_eq!(result.unencrypted_text.unwrap()[0].len(), MAX_CANDIDATE);
        assert!(crack_xz(&vec![b'A'; MAX_CANDIDATE + 1])
            .unencrypted_text
            .is_none());

        // Plaintext is returned whatever its length (up to MAX_OUTPUT)
        let english = format!("{FOX}. ").repeat(MAX_CANDIDATE / FOX.len() + 1);
        assert!(english.len() > MAX_CANDIDATE);
        let result = crack_xz(english.as_bytes());
        assert!(result.success, "Athena should identify the plaintext");
        assert_eq!(result.unencrypted_text.unwrap(), [english]);
    }

    #[test]
    fn long_nested_files_are_not_handed_on() {
        // Pseudo-random bytes (xorshift64) don't compress, so the inner XZ file is longer
        // than the limit
        let mut state = 0x2545_f491_4f6c_dd1d_u64;
        let noise: Vec<u8> = (0..MAX_CANDIDATE)
            .map(|_| {
                state ^= state << 13;
                state ^= state >> 7;
                state ^= state << 17;
                state as u8
            })
            .collect();
        let inner = xz(&noise);
        assert!(inner.len() > MAX_CANDIDATE);
        let nested = general_purpose::STANDARD.encode(xz(&inner));
        assert!(crack(&nested).unencrypted_text.is_none());
    }

    #[test]
    fn checks_the_lzma_alone_header() {
        let fox = base64_bytes(FOX_LZMA);
        assert_eq!(Container::of(&fox), Some(Container::LzmaAlone));
        assert_eq!(Container::of(&base64_bytes(FOX_XZ)), Some(Container::Xz));

        let with = |position: usize, bytes: &[u8]| {
            let mut header = fox.clone();
            header[position..position + bytes.len()].copy_from_slice(bytes);
            header
        };
        // The smallest dictionary the format allows, and a known size at the limit
        assert!(Container::of(&with(1, &4096u32.to_le_bytes())).is_some());
        assert!(Container::of(&with(5, &(MAX_OUTPUT as u64).to_le_bytes())).is_some());
        for (case, header) in [
            // lc = 0, lp = 2, pb = 0 (xz --lzma1=lc=0,lp=2,pb=0): not recognised
            ("other properties", with(0, &[0x12])),
            ("dictionary under 4 KiB", with(1, &4095u32.to_le_bytes())),
            (
                "size over the limit",
                with(5, &(MAX_OUTPUT as u64 + 1).to_le_bytes()),
            ),
            ("size u64::MAX - 1", with(5, &(u64::MAX - 1).to_le_bytes())),
            ("range coder start", with(13, &[0x80])),
            ("too short", fox[..17].to_vec()),
        ] {
            assert_eq!(Container::of(&header), None, "{case}");
        }
        // An XZ file can't be shorter than a header, an empty index and a footer
        assert_eq!(Container::of(&base64_bytes(FOX_XZ)[..31]), None);
    }

    #[test]
    fn rejects_text_that_is_not_xz() {
        // A raw DEFLATE stream that happens to start with 5D, the .lzma properties byte:
        // Python's zlib.compressobj(9, zlib.DEFLATED, -15) of a sentence of random words
        let deflate_5d = "XY9REsIgDESvkhN4JwopYAtRCNZ6egmp2vErkyz7dqHVQYouRx8YtsgBquHf5d6iXYAy2H4VZSoxe6AHFmAqNsC1pVsd8oI7rOa1H4JaTe58FMKQBRqoVYTUHY68ZqqDA46MesBkF2+v2C8ypkJb/uurBZTwVRIiD78Um+k55uB9XihKok6lJOO0mpn7P4OGX94=";
        let deflate_5d_bytes = base64_bytes(deflate_5d);
        assert_eq!(deflate_5d_bytes[0], 0x5D);

        // None of these get past the header checks
        for text in [
            "",
            "   ",
            "😀",
            "hello world",
            "hello my name is panicky mc panic face!",
            // The bench `miss` input
            "T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV",
            "]ust some text",
            "]]]]]]]]]]]]]]]]]]]]]]]]]]]]",
            "/Td6WFo",
            "/Td6WFoA",
            "XQ",
            "XQAAgAD/",
            "XQ is how .lzma starts in Base64",
            // Base64 and hex that aren't XZ
            "aGVsbG8gd29ybGQ=",
            "68656c6c6f20776f726c64",
            "5d is the .lzma properties byte",
            "fd377a585a00 is the XZ magic number",
            // A separator inside a byte
            "fd377a585a0 0000004e6d6b4460200210116000000742fe5a3010024",
            // Zlib (#1049), gzip (#1050), bzip2 (#1023) and raw DEFLATE (#1022) of the fox
            "eJwLyUhVKCzNTM5WSCrKL89TSMuvUMgqzS0oVsgvSy1SKAFK5yRWVSqk5KcDAFvcD9o=",
            "H4sIAAAAAAAC/wvJSFUoLM1MzlZIKsovz1NIy69QyCrNLShWyC9LLVIoAUrnJFZVKqTkpwMAOaNPQSsAAAA=",
            "QlpoOTFBWSZTWUWd7mEAAAQTgEAABAA////wIAAxRoaAAAAx6ammTIYRtG1HYmIISe16oVNlZbEl4+JgsfiYOd1MCW+c6F3JFOFCQRZ3uYQ=",
            "C8lIVSgszUzOVkgqyi/PU0jLr1DIKs0tKFbIL0stUigBSuckVlUqpOSnAwA=",
            // Raw DEFLATE starting with 5D, as Base64 (XY...), hex (5d8f...) and raw bytes
            deflate_5d,
            &to_hex(&deflate_5d_bytes),
            &latin1_to_string(&deflate_5d_bytes),
            // Too much padding
            "/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZwAAxKFK5cK4XlsAAUMrrVBuVx+2830BAAAAAARZWg===",
        ] {
            assert_eq!(compressed_bytes(text), None, "{text}");
            assert_eq!(decode(text), None, "{text}");
        }

        // These start like XZ but don't decompress
        for text in [
            "/Td6WFoA is how XZ starts in Base64",
            "/Td6WFoAAATm1rRGAgAhARYAAAB0L+WjAQAqVGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVy",
            "fd377a585a0000000000000000000000000000000000000000000000000000000000000000",
        ] {
            assert_eq!(decode(text), None, "{text}");
        }
    }

    #[test]
    fn rejects_latin1_text_with_characters_above_u00ff() {
        let mut raw = latin1_to_string(&base64_bytes(FOX_XZ));
        raw.push('€');
        assert_eq!(compressed_bytes(&raw), None);
    }

    #[test]
    fn xz_handles_panic_if_empty_string() {
        let result = crack("").unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn xz_handles_panic_if_emoji() {
        let result = crack("😂").unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn is_registered() {
        let decoders = crate::filtration_system::get_decoder_by_name("XZ");
        assert_eq!(decoders.components.len(), 1);
        // Cached search paths name their decoders, and are read back through the map
        assert!(crate::decoders::DECODER_MAP.contains_key("XZ"));
    }
}
