//! Decode the 01248 cipher, also called the Yunying (云影, "cloud shadow") cipher, a staple
//! of Chinese CTFs.
//!
//! Each letter is written as its position in the alphabet (A = 1 … Z = 26), spelled as a
//! group of the digits `1`, `2`, `4` and `8` that add up to it, and the groups are separated
//! by `0`: `88421` is 8 + 8 + 4 + 2 + 1 = 23, which is `W`. Encoders usually write the
//! digits largest first, but any order and any choice of digits with the same sum is the
//! same letter, so the decoder only adds them up. There is no symbol for a space or
//! punctuation, so the output is unspaced upper-case letters, like A1Z26's.
//!
//! Reference: CTF Wiki, "01248 密码" (<https://ctf-wiki.org/crypto/classical/others/#01248>),
//! whose worked example, CFF 2016 "影之密码", is `8842101220480224404014224202480122` →
//! `WELLDONE`.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, info, trace};

/// The 01248 (Yunying) decoder, call:
/// `let yunying_decoder = Decoder::<YunyingDecoder>::new()` to create a new instance
/// And then call:
/// `result = yunying_decoder.crack(input)` to decode 01248 text
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::yunying_decoder::YunyingDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_yunying = Decoder::<YunyingDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_yunying.crack(
///     "21084210842042108820108840884108401088408108421084208821",
///     &checker,
/// );
/// assert!(result.success);
/// assert_eq!(result.unencrypted_text.unwrap()[0], "CONGRATULATIONS");
///
/// // CTF Wiki's example: 88421|122|48|2244|4|142242|248|122 is 23 5 12 12 4 15 14 5
/// let result = decode_yunying.crack("8842101220480224404014224202480122", &checker);
/// assert_eq!(result.unencrypted_text.unwrap()[0], "WELLDONE");
/// ```
pub struct YunyingDecoder;

/// Fewer letters than this are too likely to be an ordinary number, like the year `2024`,
/// `1024` or `12048`, rather than a word.
const MIN_LETTERS: usize = 3;

/// The largest sum a group can have: 26 is `Z`.
const MAX_SUM: u8 = 26;

impl Crack for Decoder<YunyingDecoder> {
    fn new() -> Decoder<YunyingDecoder> {
        Decoder {
            name: "01248 (Yunying)",
            description: "01248 / Yunying (云影) cipher: letters as sums of the digits 1, 2, 4 and 8, separated by 0. Cannot represent spaces.",
            link: "https://ctf-wiki.org/crypto/classical/others/#01248",
            tags: vec!["01248", "yunying", "substitution", "decoder"],
            popularity: 0.4,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes `text` as 01248 and checks the result with `checker`. `unencrypted_text` is
    /// `None` when `text` isn't 01248.
    ///
    /// The input may only contain the digits `0`, `1`, `2`, `4` and `8`, apart from
    /// whitespace around it, and needs at least one `2`, `4` or `8` (only `0`s and `1`s is
    /// binary). One `0` before the first letter or after the last is allowed; two `0`s in a
    /// row, a group adding up to more than 26 and fewer than three letters are not.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying 01248 (Yunying) with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(decoded_text) = decode_yunying(text) else {
            debug!("Failed to decode 01248 (Yunying) because the text isn't 01248");
            return results;
        };
        trace!("Decoded text for 01248 (Yunying): {:?}", decoded_text);

        if !check_string_success(&decoded_text, text) {
            info!(
                "Failed to decode 01248 (Yunying) because check_string_success returned false on string {}",
                decoded_text
            );
            return results;
        }

        let checker_result = checker.check(&decoded_text);
        results.unencrypted_text = Some(vec![decoded_text]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Decodes 01248 text to upper-case letters, or returns `None` if `text` isn't 01248.
fn decode_yunying(text: &str) -> Option<String> {
    let digits = text.trim().as_bytes();

    // A scan that stops at the first byte outside the alphabet, before anything is
    // allocated: ordinary text fails on its first byte, and A1Z26 and most Decimal on a
    // `3`, `5`, `6`, `7`, `9` or a separator.
    let mut has_big_digit = false;
    for &byte in digits {
        match byte {
            b'0' | b'1' => {}
            b'2' | b'4' | b'8' => has_big_digit = true,
            _ => return None,
        }
    }
    // Only `0`s and `1`s is binary, which would decode to runs of `A` and `B`
    // (`0101010101` is `AAAAA`). This also rejects empty input.
    if !has_big_digit {
        return None;
    }

    // One `0` before the first letter or after the last is a stray separator. Only one:
    // any other `0` next to it would end an empty group below.
    let digits = digits.strip_prefix(b"0").unwrap_or(digits);
    let digits = digits.strip_suffix(b"0").unwrap_or(digits);

    // Every letter takes at least one digit and a separator
    let mut decoded = String::with_capacity(digits.len() / 2 + 1);
    let mut sum: u8 = 0;
    for &byte in digits {
        if byte == b'0' {
            push_letter(&mut decoded, sum)?;
            sum = 0;
        } else {
            // At most 26 + 8, so this can't overflow
            sum += byte - b'0';
            if sum > MAX_SUM {
                return None;
            }
        }
    }
    push_letter(&mut decoded, sum)?;

    (decoded.len() >= MIN_LETTERS).then_some(decoded)
}

/// Appends the letter for a group of digits adding up to `sum`, or returns `None` for an
/// empty group (two `0`s in a row).
fn push_letter(decoded: &mut String, sum: u8) -> Option<()> {
    if sum == 0 {
        return None;
    }
    decoded.push(char::from(b'A' + sum - 1));
    Some(())
}

#[cfg(test)]
mod tests {
    use super::{decode_yunying, YunyingDecoder};
    use crate::checkers::athena::Athena;
    use crate::checkers::checker_type::{Check, Checker};
    use crate::checkers::CheckerTypes;
    use crate::decoders::a1z26_decoder::A1Z26Decoder;
    use crate::decoders::crack_results::CrackResult;
    use crate::decoders::decimal_decoder::DecimalDecoder;
    use crate::decoders::interface::{Crack, Decoder};
    use crate::decoders::{DecoderType, DECODER_MAP};
    use crate::filtration_system::get_decoder_by_name;

    /// CTF Wiki's worked example (CFF 2016 "影之密码"), the example in the issue:
    /// <https://ctf-wiki.org/crypto/classical/others/#01248>
    const ISSUE_EXAMPLE: &str = "8842101220480224404014224202480122";

    // Unless a comment says otherwise, every vector below was made with an independent
    // Python encoder (each letter as its position written greedily with 8, 4, 2 and 1,
    // largest first, joined with 0) and decoded back with a Python version of the rules in
    // `decode_yunying`. The CTF Wiki example was also added up by hand.

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn crack_result(text: &str) -> CrackResult {
        Decoder::<YunyingDecoder>::new().crack(text, &get_athena_checker())
    }

    // Runs the decoder with the Athena checker and returns the decoded text, if any
    fn crack(text: &str) -> Option<String> {
        let result = crack_result(text);
        if result.unencrypted_text.is_none() {
            assert!(!result.success, "{text:?} failed but was marked successful");
        }
        result.unencrypted_text.map(|texts| texts[0].clone())
    }

    // Asserts that `text` decodes to `plaintext` alone, and that Athena accepts it
    fn assert_identified(text: &str, plaintext: &str) {
        let result = crack_result(text);
        assert!(result.success, "Athena should accept {plaintext:?}");
        assert_eq!(result.unencrypted_text.unwrap(), [plaintext]);
    }

    // Asserts that `text` decodes to `plaintext` alone. Athena doesn't identify every
    // unspaced upper-case plaintext (`WELLDONE` isn't), and that is plaintext detection, not
    // this decoder, so whether it does isn't checked here.
    fn assert_decodes(text: &str, plaintext: &str) {
        let result = crack_result(text);
        assert_eq!(result.unencrypted_text.unwrap(), [plaintext]);
    }

    #[test]
    fn decodes_the_issue_example() {
        // https://github.com/bee-san/Ciphey/issues/965
        assert_decodes(ISSUE_EXAMPLE, "WELLDONE");
    }

    #[test]
    fn decodes_digits_in_any_order() {
        // The same letters as the issue example with the digits of every group shuffled,
        // like 48 / 84 and 2244 / 4422
        assert_decodes("482180410182102280211011184042142101211", "WELLDONE");
        assert_eq!(decode_yunying("48048084").as_deref(), Some("LLL"));
        assert_eq!(decode_yunying("224404422042420").as_deref(), Some("LLL"));
    }

    #[test]
    fn decodes_one_leading_or_trailing_zero() {
        assert_decodes("08842101220480224404014224202480122", "WELLDONE");
        assert_decodes("88421012204802244040142242024801220", "WELLDONE");
        assert_decodes("088421012204802244040142242024801220", "WELLDONE");
    }

    #[test]
    fn decodes_surrounding_whitespace() {
        assert_decodes("  8842101220480224404014224202480122\n", "WELLDONE");
        assert_decodes("8842101220480224404014224202480122\r\n", "WELLDONE");
    }

    #[test]
    fn decodes_congratulations() {
        assert_identified(
            "21084210842042108820108840884108401088408108421084208821",
            "CONGRATULATIONS",
        );
    }

    #[test]
    fn decodes_hello_there_general() {
        assert_identified(
            "804108408408421088408041088204104210410842041088201084",
            "HELLOTHEREGENERAL",
        );
    }

    #[test]
    fn decodes_this_is_the_secret_message() {
        assert_identified(
            "884080810882108108821088408041088210410210882041088408410410882108821010421041",
            "THISISTHESECRETMESSAGE",
        );
    }

    #[test]
    fn decodes_you_have_found_the_secret_message() {
        assert_identified(
            "888108421088410801088420410420842108841084204088408041088210410210882041088408410410882108821010421041",
            "YOUHAVEFOUNDTHESECRETMESSAGE",
        );
    }

    #[test]
    fn decodes_the_whole_alphabet() {
        // Greedy 8/4/2/1 groups for 1 to 26
        assert_eq!(
            decode_yunying(
                "102021040410420421080810820821084084108420842108808810882088210884088410884208842108880888108882",
            )
            .as_deref(),
            Some("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
        );
    }

    #[test]
    fn decodes_long_runs_of_ones() {
        // Any digits adding up to the letter count, even 26 ones for Z
        let z = "1".repeat(26);
        assert_eq!(
            decode_yunying(&format!("{z}0{z}02")).as_deref(),
            Some("ZZB")
        );
    }

    #[test]
    fn decode_yunying_returns_the_text() {
        assert_eq!(decode_yunying(ISSUE_EXAMPLE).as_deref(), Some("WELLDONE"));
    }

    #[test]
    fn decodes_three_letters() {
        // The fewest letters accepted
        assert_eq!(decode_yunying("102012").as_deref(), Some("ABC"));
    }

    #[test]
    fn fails_with_fewer_than_three_letters() {
        assert_eq!(crack("2024"), None);
        assert_eq!(crack("1024"), None);
        assert_eq!(crack("12048"), None);
        assert_eq!(crack("88421"), None);
        // One letter with stray separators around it
        assert_eq!(crack("080"), None);
    }

    #[test]
    fn fails_on_a_group_over_26() {
        assert_eq!(crack("88888"), None);
        assert_eq!(crack("884210884218"), None);
        // 27 ones
        assert_eq!(crack(&format!("{}0202", "1".repeat(27))), None);
    }

    #[test]
    fn fails_on_two_zeros_in_a_row() {
        assert_eq!(crack("88421001220480224"), None);
        assert_eq!(crack("008842101220480224404014224202480122"), None);
        assert_eq!(crack("884210122048022440401422420248012200"), None);
    }

    #[test]
    fn fails_on_binary() {
        // No 2, 4 or 8: binary would decode to runs of A and B
        assert_eq!(crack("0101010101"), None);
        assert_eq!(crack("0100100001100101"), None);
        assert_eq!(crack("01101000 01100101 01101100 01101100 01101111"), None);
    }

    #[test]
    fn fails_on_other_digits() {
        assert_eq!(crack("1234"), None);
        assert_eq!(crack("88421012204802244040142242024801225"), None);
        assert_eq!(crack("9842101220480224404014224202480122"), None);
    }

    #[test]
    fn fails_on_inner_whitespace_and_separators() {
        assert_eq!(crack("104 101 108"), None);
        assert_eq!(crack("88421 122 48 2244 4"), None);
        assert_eq!(crack("88421-122-48-2244-4"), None);
        assert_eq!(crack("88421,122,48,2244,4"), None);
        assert_eq!(crack("8842101220480224\n404014224202480122"), None);
    }

    #[test]
    fn fails_on_a1z26() {
        // A1Z26 decodes this and 01248 must not
        let text = "8 5 12 12 15";
        assert_eq!(crack(text), None);
        let a1z26 = Decoder::<A1Z26Decoder>::new();
        let result = a1z26.crack(text, &get_athena_checker());
        assert_eq!(result.unencrypted_text.unwrap()[0], "HELLO");
    }

    #[test]
    fn a1z26_rejects_the_issue_example() {
        // No delimiters, and the one number overflows: the two decoders don't overlap
        let a1z26 = Decoder::<A1Z26Decoder>::new();
        let result = a1z26.crack(ISSUE_EXAMPLE, &get_athena_checker());
        assert_eq!(result.unencrypted_text, None);
    }

    #[test]
    fn decimal_without_separators_is_left_to_decimal() {
        // `hello` as zero-padded 3-digit decimal only uses 0, 1, 4 and 8, so it is 01248
        // too: `AEBIK`, which Athena doesn't identify, while Decimal finds `hello`
        let text = "104101108108111";
        let result = crack_result(text);
        assert_eq!(result.unencrypted_text.unwrap(), ["AEBIK"]);
        assert!(!result.success);
        let decimal = Decoder::<DecimalDecoder>::new();
        let result = decimal.crack(text, &get_athena_checker());
        assert_eq!(result.unencrypted_text.unwrap()[0], "hello");
    }

    #[test]
    fn handles_panic_if_empty_string() {
        assert_eq!(crack(""), None);
    }

    #[test]
    fn handles_panic_if_whitespace() {
        assert_eq!(crack("   "), None);
        assert_eq!(crack("\n"), None);
    }

    #[test]
    fn handles_panic_if_zeros() {
        assert_eq!(crack("0"), None);
        assert_eq!(crack("00"), None);
        assert_eq!(crack("000000"), None);
    }

    #[test]
    fn handles_panic_if_emoji() {
        assert_eq!(crack("😀"), None);
        assert_eq!(crack("8842101220480224😀"), None);
    }

    #[test]
    fn fails_on_english() {
        assert_eq!(crack("hello world"), None);
        assert_eq!(crack("hello my name is panicky mc panic face!"), None);
    }

    #[test]
    fn fails_on_the_bench_miss_input() {
        // benches/data/decoders.toml `miss`; it fails on its first byte
        assert_eq!(
            crack("T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV"),
            None
        );
    }

    #[test]
    fn is_registered() {
        // Exactly one decoder by that name runs in the search
        let decoders = get_decoder_by_name("01248 (Yunying)");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "01248 (Yunying)");
        // Cached results name the decoder; reading them back looks it up here
        let decoder = DECODER_MAP
            .get("01248 (Yunying)")
            .expect("01248 (Yunying) should be in DECODER_MAP")
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "01248 (Yunying)");
    }
}
