//! Decode zero-width character steganography: a message hidden as invisible Unicode
//! characters inside a visible cover text, or as a bare run of those characters.
//! Call zero_width_decoder.crack to use. It returns a `CrackResult` whose
//! `unencrypted_text` is `None` when the text hides nothing in a scheme it knows, and
//! otherwise holds only the hidden message, never the cover text.
//!
//! Every tool does the same thing: drop the visible text, turn each invisible character
//! into a digit and group the digits. They differ in the characters, the digits and the
//! grouping. The decoder reads these, in this order, and the key says which one it found:
//!
//! | Scheme | Characters and digits | Grouping | Key |
//! | --- | --- | --- | --- |
//! | [330k]'s text mode | U+200C, U+200D, U+202C, U+FEFF = 0 to 3 | 8 digits per UTF-16 code unit | `330k text` |
//! | 330k's binary mode | the same | 4 digits per UTF-8 byte | `330k binary` |
//! | [zwsp-steg] `MODE_FULL` | U+200B to U+200F = 0 to 4 | 7 digits per UTF-16 code unit | `zwsp-steg full` |
//! | zwsp-steg `MODE_ZWSP` | U+200B, U+200C, U+200D = 0 to 2 | 11 digits per UTF-16 code unit | `zwsp-steg zwsp` |
//! | [zero-width-lib] | U+200E, U+200F, U+200C, U+200D, U+FEFF = 0 to 4 | one code point per group, U+200B between groups | `zero-width-lib` |
//! | Plain binary | any 2: a 0 and a 1 | 8 bits per UTF-8 byte | `binary U+200B=0` |
//! | Binary with a separator: the issue's example, [Steganographr], Endrem | any 3: a 0, a 1 and one between the bytes | 1 to 8 bits per UTF-8 byte (Steganographr drops leading zeros) | `separator U+200D, U+200B=0` |
//!
//! Binary is tried with either character as 0, and with each of the three as the
//! separator. Steganographr also puts a U+FEFF before and after the message; the decoder
//! drops them. The digit orders are the tools' own, so there are at most 13 readings of
//! a text and no search over permutations. Readings that aren't valid UTF-8 or UTF-16,
//! or that contain control characters, are dropped before the checker sees them; on real
//! payloads one or two are left. StegCloak (encrypted and compressed) is not read.
//!
//! The zero-width characters are U+200B to U+200F, U+202A to U+202E, U+2060 to U+2064
//! and U+FEFF. They are all outside ASCII, so an ASCII text, which is almost every text
//! the search sees, is rejected by its first check.
//!
//! References: [330k], [zwsp-steg], [zero-width-lib], [Steganographr] and
//! <https://github.com/bee-san/Ciphey/issues/973>.
//!
//! [330k]: https://330k.github.io/misc_tools/unicode_steganography.html
//! [zwsp-steg]: https://www.npmjs.com/package/zwsp-steg
//! [zero-width-lib]: https://www.npmjs.com/package/zero-width-lib
//! [Steganographr]: https://source.tube/neatnik/steganographr/src/branch/main/steganographr.php

use std::collections::HashSet;

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, trace};

/// The Zero-width decoder, call:
/// `let zero_width_decoder = Decoder::<ZeroWidthDecoder>::new()` to create a new instance
/// And then call:
/// `result = zero_width_decoder.crack(input)` to read the message hidden in a text
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::zero_width_decoder::ZeroWidthDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_zero_width = Decoder::<ZeroWidthDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // The bits of "hi", U+200B for 0 and U+200C for 1, with U+200D between the bytes
/// let text = "Nothing\u{200b}\u{200c}\u{200c}\u{200b}\u{200c}\u{200b}\u{200b}\u{200b}\
///             \u{200d}\u{200b}\u{200c}\u{200c}\u{200b}\u{200c}\u{200b}\u{200b}\u{200c} to see here";
/// let result = decode_zero_width.crack(text, &checker).unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "hi");
/// ```
pub struct ZeroWidthDecoder;

/// Texts with fewer zero-width characters than this hide nothing. Eight are one byte in
/// plain binary and two in 330k's binary mode, and a stray byte order mark or the joiners
/// of a few emoji are not a message.
const MIN_HIDDEN: usize = 8;

/// Texts with more distinct zero-width characters than this hide nothing. zero-width-lib
/// uses the most: five digits and a separator.
const MAX_SYMBOLS: usize = 6;

/// 330k's characters for the digits 0 to 3 (its default `setUseChars`)
const DIGITS_330K: [char; 4] = ['\u{200C}', '\u{200D}', '\u{202C}', '\u{FEFF}'];

/// zwsp-steg's characters for the digits 0 to 4 in `MODE_FULL`. `MODE_ZWSP` uses the
/// first three for 0 to 2.
const DIGITS_ZWSP_STEG: [char; 5] = ['\u{200B}', '\u{200C}', '\u{200D}', '\u{200E}', '\u{200F}'];

/// zero-width-lib's characters for the digits 0 to 4
const DIGITS_ZERO_WIDTH_LIB: [char; 5] =
    ['\u{200E}', '\u{200F}', '\u{200C}', '\u{200D}', '\u{FEFF}'];

/// What zero-width-lib puts between the digits of two code points
const ZERO_WIDTH_LIB_SEPARATOR: char = '\u{200B}';

/// zero-width-lib writes code points in base 5 without leading zeros, and U+10FFFF takes
/// 9 digits.
const MAX_ZERO_WIDTH_LIB_DIGITS: usize = 9;

/// One way of reading the hidden characters: the scheme, which becomes the key, and the
/// text it gives.
#[derive(Debug, PartialEq, Eq)]
struct Reading {
    /// The scheme, such as `330k text` or `separator U+200D, U+200B=0`
    key: String,
    /// The hidden message as the scheme reads it
    text: String,
}

impl Crack for Decoder<ZeroWidthDecoder> {
    fn new() -> Decoder<ZeroWidthDecoder> {
        Decoder {
            name: "Zero-width",
            description: "Zero-width character steganography: a message hidden as invisible Unicode characters (U+200B–U+200F, U+2060–U+2064, U+202C, U+FEFF) inside a cover text, in the issue/Steganographr binary schemes, 330k's base-4 scheme, zwsp-steg's base-3/base-5 schemes or zero-width-lib's base-5 scheme.",
            link: "https://330k.github.io/misc_tools/unicode_steganography.html",
            tags: vec!["zero-width", "steganography", "unicode", "decoder", "program"],
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// Reads the message hidden in `text` in every scheme that fits and checks the
    /// readings with `checker`, in the order of the table in the module docs. The first
    /// one the checker accepts is returned alone, with its scheme as the key. If it
    /// accepts none, all of them are returned for the search to decode further.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Zero-width with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let readings = hidden_messages(text);
        if readings.is_empty() {
            debug!("Failed to decode Zero-width because the text hides no message it can read");
            return results;
        }

        for reading in &readings {
            let checker_result = checker.check(&reading.text);
            if checker_result.is_identified {
                trace!(
                    "Found a hidden message with Zero-width scheme {}",
                    reading.key
                );
                results.unencrypted_text = Some(vec![reading.text.clone()]);
                results.key = Some(reading.key.clone());
                results.update_checker(&checker_result);
                return results;
            }
        }

        // A key per reading only works for one reading: the library splits a key on ", "
        // to give each candidate its own, and the separator schemes' keys contain ", "
        if let [reading] = readings.as_slice() {
            results.key = Some(reading.key.clone());
        }
        results.unencrypted_text = Some(readings.into_iter().map(|reading| reading.text).collect());
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// The messages hidden in `text`, one per scheme that reads it as text without control
/// characters, in the order of the table in the module docs and without repeats.
fn hidden_messages(text: &str) -> Vec<Reading> {
    // Every zero-width character is outside ASCII. This one check is the whole miss path
    // for almost every text the search sees.
    if text.is_ascii() {
        return Vec::new();
    }
    let hidden = extract(text);
    if hidden.len() < MIN_HIDDEN {
        return Vec::new();
    }
    // One symbol is what Persian text (U+200C) and emoji sequences (U+200D) are full of
    if !(2..=MAX_SYMBOLS).contains(&symbols(&hidden).len()) {
        return Vec::new();
    }

    let mut readings = Vec::new();
    if let Some(inner) = unwrap(&hidden) {
        readings.extend(candidates(inner));
    }
    readings.extend(candidates(&hidden));

    let mut seen = HashSet::new();
    readings.retain(|reading| {
        check_string_success(&reading.text, text)
            && is_printable(&reading.text)
            && seen.insert(reading.text.clone())
    });
    readings
}

/// Whether `c` is one of the zero-width characters the schemes use.
fn is_zero_width(c: char) -> bool {
    matches!(
        c,
        '\u{200B}'..='\u{200F}' | '\u{202A}'..='\u{202E}' | '\u{2060}'..='\u{2064}' | '\u{FEFF}'
    )
}

/// The zero-width characters of `text`, in order, without the visible text around them.
fn extract(text: &str) -> Vec<char> {
    text.chars().filter(|&c| is_zero_width(c)).collect()
}

/// The distinct characters of `hidden` in the order they first appear, stopping after
/// one more than `MAX_SYMBOLS`.
fn symbols(hidden: &[char]) -> Vec<char> {
    let mut symbols = Vec::new();
    for &c in hidden {
        if !symbols.contains(&c) {
            symbols.push(c);
            if symbols.len() > MAX_SYMBOLS {
                break;
            }
        }
    }
    symbols
}

/// `hidden` without its first and last character if they are the same character and it
/// appears nowhere else, as Steganographr's U+FEFF does around its message. The message
/// is read both with and without them.
fn unwrap(hidden: &[char]) -> Option<&[char]> {
    let (&first, rest) = hidden.split_first()?;
    let (&last, inner) = rest.split_last()?;
    if hidden.len() >= 10 && first == last && !inner.contains(&first) {
        Some(inner)
    } else {
        None
    }
}

/// Every reading of `hidden` (only zero-width characters) whose scheme fits it and that
/// is valid UTF-8 or UTF-16, in the order of the table in the module docs. The readings
/// still have to be checked for control characters.
fn candidates(hidden: &[char]) -> Vec<Reading> {
    let mut readings = Vec::new();
    let mut add = |key: String, text: Option<String>| {
        if let Some(text) = text {
            readings.push(Reading { key, text });
        }
    };

    if let Some(digits) = digits(hidden, &DIGITS_330K) {
        add("330k text".to_string(), utf16_units(&digits, 4, 8));
        add("330k binary".to_string(), utf8_bytes(&digits, 4, 4));
    }
    if let Some(digits) = digits(hidden, &DIGITS_ZWSP_STEG) {
        add("zwsp-steg full".to_string(), utf16_units(&digits, 5, 7));
        if digits.iter().all(|&digit| digit < 3) {
            add("zwsp-steg zwsp".to_string(), utf16_units(&digits, 3, 11));
        }
    }
    add("zero-width-lib".to_string(), zero_width_lib(hidden));

    match *symbols(hidden).as_slice() {
        [first, second] => {
            for (zero, one) in [(first, second), (second, first)] {
                add(
                    format!("binary {}=0", code_point(zero)),
                    binary(hidden, zero, one),
                );
            }
        }
        [first, second, third] => {
            for (separator, a, b) in [
                (first, second, third),
                (second, first, third),
                (third, first, second),
            ] {
                for (zero, one) in [(a, b), (b, a)] {
                    add(
                        format!(
                            "separator {}, {}=0",
                            code_point(separator),
                            code_point(zero)
                        ),
                        separated_binary(hidden, separator, zero, one),
                    );
                }
            }
        }
        _ => {}
    }
    readings
}

/// The digit each character of `hidden` stands for in `alphabet`, or `None` if one of
/// them isn't in it.
fn digits(hidden: &[char], alphabet: &[char]) -> Option<Vec<u32>> {
    hidden
        .iter()
        .map(|c| {
            alphabet
                .iter()
                .position(|digit| digit == c)
                .map(|digit| digit as u32)
        })
        .collect()
}

/// `digits` read as a number in `base`, most significant digit first. The callers' groups
/// are at most 11 digits in base 3 or 9 in base 5, far below `u32::MAX`.
fn number(digits: &[u32], base: u32) -> u32 {
    digits
        .iter()
        .fold(0, |number, &digit| number * base + digit)
}

/// The text whose UTF-16 code units are `digits` in groups of `width` digits in `base`,
/// or `None` if the digits don't divide into groups, a group is over U+FFFF or a
/// surrogate is unpaired.
fn utf16_units(digits: &[u32], base: u32, width: usize) -> Option<String> {
    if digits.is_empty() || !digits.len().is_multiple_of(width) {
        return None;
    }
    let units = digits
        .chunks(width)
        .map(|group| u16::try_from(number(group, base)).ok())
        .collect::<Option<Vec<u16>>>()?;
    String::from_utf16(&units).ok()
}

/// The text whose UTF-8 bytes are `digits` in groups of `width` digits in `base`, or
/// `None` if the digits don't divide into groups or the bytes aren't UTF-8.
fn utf8_bytes(digits: &[u32], base: u32, width: usize) -> Option<String> {
    if digits.is_empty() || !digits.len().is_multiple_of(width) {
        return None;
    }
    let bytes = digits
        .chunks(width)
        .map(|group| u8::try_from(number(group, base)).ok())
        .collect::<Option<Vec<u8>>>()?;
    String::from_utf8(bytes).ok()
}

/// zero-width-lib's reading of `hidden`: code points in base 5, separated by U+200B.
fn zero_width_lib(hidden: &[char]) -> Option<String> {
    if !hidden.contains(&ZERO_WIDTH_LIB_SEPARATOR) {
        return None;
    }
    hidden
        .split(|&c| c == ZERO_WIDTH_LIB_SEPARATOR)
        .map(|group| {
            if group.is_empty() || group.len() > MAX_ZERO_WIDTH_LIB_DIGITS {
                return None;
            }
            char::from_u32(number(&digits(group, &DIGITS_ZERO_WIDTH_LIB)?, 5))
        })
        .collect()
}

/// `hidden` read as UTF-8 bytes of 8 bits each, `zero` for 0 and `one` for 1.
fn binary(hidden: &[char], zero: char, one: char) -> Option<String> {
    if !hidden.len().is_multiple_of(8) {
        return None;
    }
    let bytes = hidden
        .chunks(8)
        .map(|bits| byte(bits, zero, one))
        .collect::<Option<Vec<u8>>>()?;
    String::from_utf8(bytes).ok()
}

/// `hidden` read as UTF-8 bytes with `separator` between them, `zero` for 0 and `one`
/// for 1. A byte has 1 to 8 bits, so leading zeros may be left out as Steganographr does.
/// A separator before the first byte or after the last is ignored.
fn separated_binary(hidden: &[char], separator: char, zero: char, one: char) -> Option<String> {
    let hidden = hidden.strip_prefix(&[separator]).unwrap_or(hidden);
    let hidden = hidden.strip_suffix(&[separator]).unwrap_or(hidden);
    let bytes = hidden
        .split(|&c| c == separator)
        .map(|bits| {
            if bits.is_empty() || bits.len() > 8 {
                return None;
            }
            byte(bits, zero, one)
        })
        .collect::<Option<Vec<u8>>>()?;
    // One byte can't be told from chance
    if bytes.len() < 2 {
        return None;
    }
    String::from_utf8(bytes).ok()
}

/// The byte whose bits are `bits`, most significant first, or `None` if one of them is
/// neither `zero` nor `one`. There are at most 8 bits.
fn byte(bits: &[char], zero: char, one: char) -> Option<u8> {
    bits.iter().try_fold(0u8, |byte, &bit| match bit {
        _ if bit == zero => Some(byte << 1),
        _ if bit == one => Some((byte << 1) | 1),
        _ => None,
    })
}

/// `c` as `U+XXXX`
fn code_point(c: char) -> String {
    format!("U+{:04X}", u32::from(c))
}

/// Whether `text` has no control characters other than tabs and line breaks and no
/// U+FFFD. Reading a scheme's digits in the wrong grouping gives control characters
/// (330k's text mode read as its binary mode has a NUL before every ASCII letter).
fn is_printable(text: &str) -> bool {
    text.chars()
        .all(|c| c != '\u{FFFD}' && (!c.is_control() || matches!(c, '\t' | '\n' | '\r')))
}

#[cfg(test)]
mod tests {
    use super::{
        candidates, extract, hidden_messages, unwrap, Reading, ZeroWidthDecoder, MIN_HIDDEN,
    };
    use crate::checkers::athena::Athena;
    use crate::checkers::checker_type::{Check, Checker};
    use crate::checkers::CheckerTypes;
    use crate::decoders::crack_results::CrackResult;
    use crate::decoders::interface::{Crack, Decoder};
    use crate::decoders::{DecoderType, DECODER_MAP};
    use crate::filtration_system::get_decoder_by_name;

    // The vectors are written with `zw`: text outside `[...]` is copied, and inside the
    // brackets each letter is one zero-width character. Every vector was made by the
    // tool named with it and decoded back by the same tool, then by a Python prototype
    // of this decoder (https://github.com/bee-san/Ciphey/issues/973):
    // * the issue scheme and Endrem's: Python 3.9 (`format(byte, "08b")` per UTF-8 byte),
    // * Steganographr: a Python 3.9 port of its PHP `str2bin`, `bin2hidden` and `wrap`,
    //   inserted at `round(count / 2)` of the cover's characters as the PHP does,
    // * 330k: node 22 running 330k's `unicode_steganography.js` (`encodeText` and
    //   `encodeBinary`, decoded with `decodeText` and `decodeBinary`),
    // * zwsp-steg 1.0.1 and zero-width-lib 1.1.0: node 22 with the npm packages.

    /// The issue example: the bits of `hi` with U+200B for 0, U+200C for 1 and U+200D
    /// between the bytes, in the cover text `Nothing to see here`
    const ISSUE_EXAMPLE: &str = "Nothing[BCCBCBBBDBCCBCBBC] to see here";

    /// `hello world` in the issue scheme, without a cover
    const HELLO_WORLD: &str = "[BCCBCBBBDBCCBBCBCDBCCBCCBBDBCCBCCBBDBCCBCCCCDBBCBBBBBDBCCCBCCCDBCCBCCCCDBCCCBBCBDBCCBCCBBDBCCBBCBB]";

    /// `HELLO_WORLD` with U+200B and U+200C swapped
    const HELLO_WORLD_SWAPPED: &str = "[CBBCBCCCDCBBCCBCBDCBBCBBCCDCBBCBBCCDCBBCBBBBDCCBCCCCCDCBBBCBBBDCBBCBBBBDCBBBCCBCDCBBCBBCCDCBBCCBCC]";

    /// A flag in the issue scheme, without a cover. LemmeKnow takes it for a CTF flag.
    const FLAG: &str = "[BCCBBCCBDBCCBCCBBDBCCBBBBCDBCCBBCCCDBCCCCBCCDBCCCCBCBDBCCBBCBCDBCCCBBCBDBCCBCCCCDBCBCCCCCDBCCCBCCCDBCCBCBBCDBCCBBCBBDBCCCBCBBDBCCBCBBBDBCBCCCCCDBCCBCBBCDBCCCBBCCDBCBCCCCCDBCCBBCCBDBCCCBCBCDBCCBCCCBDBCCCCCBC]";

    /// The cover of the long-cover vector, before and after the hidden flag
    const LONG_COVER: [&str; 2] = [
        "The quick brown fox jumps over the lazy dog while the cat sleeps on the warm windowsill. Nothing about this paragraph is unusual and it reads like any other note you might find in a shared folder. It ",
        "talks about the weather, which was mild for the time of year, and about dinner plans for the weekend. There is really nothing to see here, so move along and do not look too closely at the spaces between words.",
    ];

    /// Endrem's scheme: U+200C for 0, U+200D for 1 and U+200B between the bytes
    const ENDREM: &str = "[CDDCDDCDBCDDCCDCDBCDDCCDCDBCDDDCDCCBCCDCCCCCBCDDCDDCDBCDDCCDCDBCCDCCCCCBCDDCCCCDBCDDDCDCCBCCDCCCCCBCDDCDDCDBCDDCDCCDBCDDCCDCCBCDDCDDDCBCDDCDCCDBCDDCCDDDBCDDCDCCCBCDDDCDCC]";

    /// Steganographr without a cover: bits without leading zeros, U+2060 between the
    /// bytes and U+FEFF around the message
    const STEGANOGRAPHR: &str = "[ZCCBBBBCWCCCBCBBWCCCBCBBWCCBBBBCWCCBBBCCWCCBCBCCWCBBBBBWCCBBBBCWCCCBCBBWCBBBBBWCCBBCBBWCCBBBBCWCCCBCCCWCCBCCCBZ]";

    /// Steganographr in the middle of a cover text
    const STEGANOGRAPHR_COVER: &str = "Nothing to[ZCCCBCBBWCCBCBBBWCCBBCBCWCBBBBBWCCCBBCCWCCBBCBCWCCBBBCCWCCCBBCBWCCBBCBCWCCCBCBBWCBBBBBWCCBCBBCWCCCBBCCWCBBBBBWCCBCBBCWCCBCCCBWCBBBBBWCCCBCBBWCCBCBBBWCCBBCBCWCBBBBBWCCCCBCBWCCBBCBCWCCCBBCBWCCBCCCCWCBBBBBWCCCBCCCWCCBCBBCWCCBBCBBWCCCBCBBWCCBCBBBWCBBBBBWCCBBBCCWCCBCBBBWCCBBBBCWCCCBBCBWCCBBBBCWCCBBBCCWCCCBCBBWCCBBCBCWCCCBBCBWCCCBBCCZ] see here";

    /// 330k's text mode, spread through the cover text as 330k does
    const TEXT_330K: &str = "[CCCCDPCDCCCCDZDC]Nothing[CCCCDZDCCCCCDPCD] [CCCCDPCZ]to [CCCCDPPZ]see[CCCCCPCCCCCCDPCD] [CCCCDZDCCCCCCPCCCCCCDPDCCCCCDPCDCCCCDZDZ]here[CCCCDPZP]";

    /// 330k's binary mode
    const BINARY_330K: &str =
        "Nothing[DPCDDZDCDZDCDPCDDPCZDPPZCPCCDPCD] [DZDCCPCCDPDCDPCDDZDZDPZP]to see here";

    /// zwsp-steg's `MODE_FULL`
    const ZWSP_STEG_FULL: &str = "[BBBBFCFBBBBFBCBBBBFBCBBBBFECBBBBCCDBBBBFCFBBBBFBCBBBBCCDBBBBEFDBBBBFECBBBBCCDBBBBFCFBBBBFCBBBBBFBBBBBBFDBBBBBFCBBBBBFBEBBBBFBFBBBBFEC]";

    /// zwsp-steg's `MODE_ZWSP`
    const ZWSP_STEG_ZWSP: &str = "[BBBBBBCCBBCBBBBBBCBDBDBBBBBBCBDBDBBBBBBCCBDDBBBBBBBCBCDBBBBBBCCBBCBBBBBBCBDBDBBBBBBBCBCDBBBBBBCBCDCBBBBBBCCBDDBBBBBBBCBCDBBBBBBCCBBCBBBBBBCBDDBBBBBBBCBDBCBBBBBBCCBBDBBBBBBCBDDBBBBBBBCBDCCBBBBBBCBDCDBBBBBBCCBDD]";

    /// zero-width-lib, which puts the message after the first character of the cover
    const ZERO_WIDTH_LIB: &str = "N[DFZBZEZBZFEBZDEBFFCBZFEBZDEBFFCBDZCBFFCBZDEBZEFBDZZBZCZBZEFBZDFBFFCBZFZBZEFBZDEBZDEBDZCBZEDBZEF]othing to see here";

    /// `flag{🚩}` in 330k's text mode: the flag is a surrogate pair
    const TEXT_330K_EMOJI: &str = "[CCCCDPDPCCCCDPZC]Nothing[CCCCDPCD] [CCCCDPDZ]to[CCCCDZPZZDPCCZZD] [ZDZPPPPDCCCCDZZD]see here";

    /// `flag{🚩}` in zwsp-steg's `MODE_FULL`
    const ZWSP_STEG_FULL_EMOJI: &str = "[BBBBFBDBBBBFCEBBBBEFDBBBBFBEBBBBFFEEDEDFCDEECCBBCBBBCBBB]";

    /// `flag{🚩}` with zero-width-lib: one code point per group
    const ZERO_WIDTH_LIB_EMOJI: &str = "N[ZECBZFDBDZCBZEDBZZDBFDFEZCFFBFEEE]othing to see here";

    /// `日本語` with zero-width-lib
    const ZERO_WIDTH_LIB_JAPANESE: &str = "N[FDFDDCEBFDCFFCCBCFFDZCF]othing to see here";

    /// The bench `miss` input
    const MISS: &str =
        "T00 l3= ox+#G WKyV pajU6j qxH@ %B4+a 5Pn^ 7p_v1q 9sLvu *+36i R5rL&3 mVJZI iO0 Ut8_m COTV";

    /// The text of the bench `medium` input
    const MEDIUM_PLAINTEXT: &str =
        "Meet me at the old lighthouse after midnight and bring the map, the key and a torch.";

    /// U+200B ZERO WIDTH SPACE, 0 in the issue scheme
    const ZWSP: char = '\u{200B}';
    /// U+200C ZERO WIDTH NON-JOINER, 1 in the issue scheme
    const ZWNJ: char = '\u{200C}';
    /// U+200D ZERO WIDTH JOINER, between the bytes in the issue scheme
    const ZWJ: char = '\u{200D}';

    /// Copies `text`, writing each letter between `[` and `]` as its zero-width character
    fn zw(text: &str) -> String {
        let mut inside = false;
        text.chars()
            .filter_map(|c| match c {
                '[' => {
                    inside = true;
                    None
                }
                ']' => {
                    inside = false;
                    None
                }
                _ if !inside => Some(c),
                'B' => Some('\u{200B}'),
                'C' => Some('\u{200C}'),
                'D' => Some('\u{200D}'),
                'E' => Some('\u{200E}'),
                'F' => Some('\u{200F}'),
                'P' => Some('\u{202C}'),
                'W' => Some('\u{2060}'),
                'Z' => Some('\u{FEFF}'),
                _ => panic!("{c:?} isn't a zero-width letter"),
            })
            .collect()
    }

    /// `bytes` in the issue scheme: the 8 bits of each byte with `zero` for 0 and `one`
    /// for 1, and `separator` between the bytes
    fn issue_scheme(bytes: &[u8], zero: char, one: char, separator: char) -> String {
        bytes
            .iter()
            .map(|byte| {
                format!("{byte:08b}")
                    .chars()
                    .map(|bit| if bit == '0' { zero } else { one })
                    .collect::<String>()
            })
            .collect::<Vec<_>>()
            .join(&separator.to_string())
    }

    /// `text` in the issue scheme, as the issue made its example
    fn issue(text: &str) -> String {
        issue_scheme(text.as_bytes(), ZWSP, ZWNJ, ZWJ)
    }

    /// The Athena checker, as the search uses it
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    /// Runs the decoder with the Athena checker
    fn crack_result(text: &str) -> CrackResult {
        Decoder::<ZeroWidthDecoder>::new().crack(text, &get_athena_checker())
    }

    /// Runs the decoder on `text` and returns what it hands on, checking that a failure
    /// isn't marked successful
    fn crack(text: &str) -> Option<Vec<String>> {
        let result = crack_result(text);
        if result.unencrypted_text.is_none() {
            assert!(!result.success, "{text:?} failed but was marked successful");
            assert!(result.key.is_none(), "{text:?} failed but has a key");
        }
        result.unencrypted_text
    }

    /// Asserts that Athena accepts `plaintext`, hidden in `text` (in `zw` notation) with
    /// the scheme `key`, and that it comes back alone
    #[track_caller]
    fn assert_identified(text: &str, plaintext: &str, key: &str) {
        let result = crack_result(&zw(text));
        assert!(
            result.success,
            "Athena should accept {plaintext:?}: {result:?}"
        );
        assert_eq!(result.unencrypted_text, Some(vec![plaintext.to_string()]));
        assert_eq!(result.key.as_deref(), Some(key));
    }

    /// The readings of `text` (in `zw` notation) that survive the filter
    fn readings(text: &str) -> Vec<(String, String)> {
        hidden_messages(&zw(text))
            .into_iter()
            .map(|Reading { key, text }| (key, text))
            .collect()
    }

    #[test]
    fn decodes_the_issue_example() {
        // Athena doesn't take "hi" for plaintext, so it is handed on to the search
        let result = crack_result(&zw(ISSUE_EXAMPLE));
        assert!(!result.success);
        assert_eq!(result.unencrypted_text, Some(vec!["hi".to_string()]));
        assert_eq!(result.key.as_deref(), Some("separator U+200D, U+200B=0"));
    }

    #[test]
    fn decodes_the_issue_scheme_without_a_cover() {
        assert_identified(HELLO_WORLD, "hello world", "separator U+200D, U+200B=0");
    }

    #[test]
    fn decodes_the_issue_scheme_with_its_digits_swapped() {
        assert_identified(
            HELLO_WORLD_SWAPPED,
            "hello world",
            "separator U+200D, U+200C=0",
        );
    }

    #[test]
    fn decodes_a_flag_in_a_cover_text() {
        assert_identified(
            &format!("Nothing{FLAG} to see here"),
            "flag{zero_width_is_fun}",
            "separator U+200D, U+200B=0",
        );
    }

    #[test]
    fn decodes_endrem() {
        assert_identified(ENDREM, "meet me at midnight", "separator U+200B, U+200C=0");
    }

    #[test]
    fn decodes_steganographr_without_a_cover() {
        assert_identified(
            STEGANOGRAPHR,
            "attack at dawn",
            "separator U+2060, U+200B=0",
        );
    }

    #[test]
    fn decodes_steganographr_in_a_cover_text() {
        assert_identified(
            STEGANOGRAPHR_COVER,
            "the secret is in the zero width characters",
            "separator U+2060, U+200B=0",
        );
    }

    #[test]
    fn decodes_330k_text() {
        assert_identified(TEXT_330K, "attack at dawn", "330k text");
    }

    #[test]
    fn decodes_330k_binary() {
        assert_identified(BINARY_330K, "attack at dawn", "330k binary");
    }

    #[test]
    fn decodes_zwsp_steg_full() {
        assert_identified(ZWSP_STEG_FULL, "meet me at midnight", "zwsp-steg full");
    }

    #[test]
    fn decodes_zwsp_steg_zwsp() {
        assert_identified(ZWSP_STEG_ZWSP, "meet me at midnight", "zwsp-steg zwsp");
    }

    #[test]
    fn decodes_zero_width_lib() {
        assert_identified(ZERO_WIDTH_LIB, "This is a secret message", "zero-width-lib");
    }

    #[test]
    fn decodes_a_long_cover_text() {
        // The flag is 23 characters of 615, under the 5% the search's sanity check wants
        // of most decoders' results
        let text = LONG_COVER.join(FLAG);
        assert_eq!(zw(&text).chars().count(), 615);
        assert_identified(
            &text,
            "flag{zero_width_is_fun}",
            "separator U+200D, U+200B=0",
        );
    }

    #[test]
    fn decodes_non_bmp_text() {
        // UTF-16 schemes keep a surrogate pair together; zero-width-lib writes the code
        // point. LemmeKnow doesn't take `flag{🚩}` for a flag, so it is handed on.
        for (text, key) in [
            (TEXT_330K_EMOJI, "330k text"),
            (ZWSP_STEG_FULL_EMOJI, "zwsp-steg full"),
            (ZERO_WIDTH_LIB_EMOJI, "zero-width-lib"),
        ] {
            assert_eq!(
                readings(text),
                [(key.to_string(), "flag{🚩}".to_string())],
                "{text}"
            );
        }
        assert_eq!(
            readings(ZERO_WIDTH_LIB_JAPANESE),
            [("zero-width-lib".to_string(), "日本語".to_string())]
        );
    }

    #[test]
    fn decodes_the_bench_medium_input() {
        let text = issue(MEDIUM_PLAINTEXT);
        assert_eq!(text.chars().count(), 755);
        let result = crack_result(&text);
        assert!(result.success);
        assert_eq!(
            result.unencrypted_text,
            Some(vec![MEDIUM_PLAINTEXT.to_string()])
        );
    }

    #[test]
    fn decodes_utf8_in_the_issue_scheme() {
        assert_eq!(
            hidden_messages(&issue("café crème")),
            [Reading {
                key: "separator U+200D, U+200B=0".to_string(),
                text: "café crème".to_string(),
            }]
        );
    }

    #[test]
    fn decodes_plain_binary_with_both_assignments() {
        // Two symbols and no separator: 8 bits per byte. Either symbol can be 0.
        let text = issue("hello world").replace(ZWJ, "");
        assert_eq!(
            hidden_messages(&format!("Nothing{text} to see here")),
            [Reading {
                key: "binary U+200B=0".to_string(),
                text: "hello world".to_string(),
            }]
        );
        let swapped = issue_scheme(b"hello world", '\u{FEFF}', '\u{2060}', ZWJ).replace(ZWJ, "");
        assert_eq!(
            hidden_messages(&swapped),
            [Reading {
                key: "binary U+FEFF=0".to_string(),
                text: "hello world".to_string(),
            }]
        );
    }

    #[test]
    fn decodes_a_separator_after_the_last_byte() {
        let readings = hidden_messages(&format!("{}{ZWJ}", issue("hello world")));
        assert!(
            readings.iter().any(|reading| reading.text == "hello world"),
            "{readings:?}"
        );
    }

    #[test]
    fn hands_on_every_reading_if_none_is_plaintext() {
        // A hidden Base64 string isn't plaintext; the search decodes it further
        let result = crack_result(&issue("aGVsbG8gd29ybGQ="));
        assert!(!result.success);
        let texts = result.unencrypted_text.expect("a reading");
        assert!(texts.contains(&"aGVsbG8gd29ybGQ=".to_string()), "{texts:?}");
    }

    #[test]
    fn checks_the_readings_in_order() {
        // The issue scheme also fits zwsp-steg's MODE_FULL alphabet, and 98 characters
        // make 14 groups of 7. That reading is valid UTF-16 but not plaintext, so the
        // checker rejects it and accepts the issue scheme's reading after it.
        let readings = readings(HELLO_WORLD);
        assert_eq!(readings.len(), 2, "{readings:?}");
        assert_eq!(readings[0].0, "zwsp-steg full");
        assert_eq!(
            readings[1],
            (
                "separator U+200D, U+200B=0".to_string(),
                "hello world".to_string()
            )
        );
    }

    #[test]
    fn rejects_control_characters() {
        // 330k's text mode read as its binary mode: a NUL before every ASCII letter
        let all = candidates(&extract(&zw(TEXT_330K)));
        let binary = all
            .iter()
            .find(|reading| reading.key == "330k binary")
            .expect("the 330k binary reading");
        assert!(binary.text.starts_with("\0a\0t"), "{:?}", binary.text);
        assert_eq!(
            readings(TEXT_330K),
            [("330k text".to_string(), "attack at dawn".to_string())]
        );
    }

    #[test]
    fn rejects_invalid_utf16_and_utf8() {
        // A lone high surrogate (U+D800) then `a` in 330k's text mode. Read as 330k's
        // binary mode it is D8 00 00 61, which isn't UTF-8 either.
        assert_eq!(crack(&zw("x[ZDPCCCCCCCCCDPCD]y")), None);
        // C3 starts a two-byte character, and `a` can't end it
        assert_eq!(crack(&issue_scheme(&[0xC3, b'a'], ZWSP, ZWNJ, ZWJ)), None);
    }

    #[test]
    fn unwraps_only_a_character_that_appears_twice() {
        let hidden = extract(&zw(STEGANOGRAPHR));
        assert_eq!(unwrap(&hidden), Some(&hidden[1..hidden.len() - 1]));
        // U+FEFF three times: no wrapper
        let three = extract(&zw("[ZCCBBBBCWZCCCBCBBZ]"));
        assert_eq!(unwrap(&three), None);
        // Too short to be a wrapped message
        let short = extract(&zw("[ZCCBBBBCZ]"));
        assert_eq!(unwrap(&short), None);
    }

    #[test]
    fn fails_with_fewer_than_eight_zero_width_characters() {
        let seven = "\u{200B}\u{200C}\u{200B}\u{200C}\u{200B}\u{200C}\u{200B}";
        assert_eq!(seven.chars().count(), MIN_HIDDEN - 1);
        assert_eq!(crack(&format!("a{seven}b")), None);
        // A byte order mark at the start of a file
        assert_eq!(crack("\u{FEFF}hello world"), None);
    }

    #[test]
    fn fails_with_one_symbol() {
        // Eight U+200B between letters
        assert_eq!(
            crack("a\u{200b}b\u{200b}c\u{200b}d\u{200b}e\u{200b}f\u{200b}g\u{200b}h\u{200b}i"),
            None
        );
        // Family emoji are joined with U+200D
        assert_eq!(crack("👨\u{200d}👩\u{200d}👧\u{200d}👦👨\u{200d}👩\u{200d}👧\u{200d}👦👨\u{200d}👩\u{200d}👧"), None);
        // Persian writes U+200C (ZWNJ) inside words
        assert_eq!(
            crack("می\u{200c}خواهم کتاب\u{200c}ها را بخوانم و می\u{200c}روم. خانه\u{200c}ها و درخت\u{200c}ها و گل\u{200c}ها و می\u{200c}دانم و نمی\u{200c}دانم"),
            None
        );
    }

    #[test]
    fn fails_with_more_than_six_symbols() {
        assert_eq!(crack(&zw("[BCDEFPWZBCDEFPWZ]")), None);
    }

    #[test]
    fn fails_on_the_cover_text_alone() {
        assert_eq!(crack("Nothing to see here"), None);
    }

    #[test]
    fn fails_on_the_bench_miss_input() {
        assert_eq!(crack(MISS), None);
    }

    #[test]
    fn fails_on_english() {
        assert_eq!(crack("hello world"), None);
        assert_eq!(crack("hello my name is panicky mc panic face!"), None);
    }

    #[test]
    fn fails_on_morse() {
        assert_eq!(crack(".... . .-.. .-.. ---"), None);
    }

    #[test]
    fn handles_panic_if_empty_string() {
        assert_eq!(crack(""), None);
    }

    #[test]
    fn handles_panic_if_emoji() {
        assert_eq!(crack("😀"), None);
        assert_eq!(crack(&"😀".repeat(20)), None);
    }

    #[test]
    fn is_registered() {
        // Exactly one decoder by that name runs in the search
        let decoders = get_decoder_by_name("Zero-width");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Zero-width");
        // Cached results name the decoder; reading them back looks it up here
        let decoder = DECODER_MAP
            .get("Zero-width")
            .expect("Zero-width should be in DECODER_MAP")
            .get::<DecoderType>();
        assert_eq!(decoder.get_name(), "Zero-width");
        // The search's sanity check lets its results be much shorter than the input
        assert!(decoder.get_tags().contains(&"program"));
    }
}
