//! Decode zlib streams (RFC 1950): a 2-byte header, a DEFLATE body (RFC 1951) and a
//! big-endian Adler-32 checksum of the uncompressed data.
//! Call zlib_decoder.crack to use. It returns a `CrackResult`; check
//! `result.unencrypted_text.is_some()` to see if it decoded.
//!
//! Zlib turns up in PDF `FlateDecode` streams, git loose objects, Flask session cookies
//! (`.eJ…`) and many CTF challenges. Compressed data is binary and Ciphey passes text
//! between decoders (the Base64 decoder drops output that isn't UTF-8), so this decoder
//! reads the compressed bytes itself, from one of these views of its input:
//!
//! * a signed cookie, `.<payload>.<timestamp>.<signature>` (Flask/itsdangerous) or
//!   `.<payload>:<timestamp>:<signature>` (Django): only the Base64url payload is read,
//!   the signature is not checked,
//! * Base64, standard or URL-safe, with or without padding and line breaks,
//! * hex, optionally split by whitespace, `:` or `,`, with or without `0x` / `\x` prefixes,
//! * raw bytes, as the text the Hexadecimal and Binary decoders produce for binary data
//!   (one Latin-1 character per byte, or UTF-8 when the bytes happen to be UTF-8).
//!
//! Each view has to start with a zlib header, which in practice is `78 01`, `78 5E`,
//! `78 9C` or `78 DA` (`eA`, `eF`, `eJ`, `eN` in Base64), so other text is rejected after
//! looking at its first characters. The stream then has to pass the RFC 1950 header
//! check, inflate without error, match its Adler-32 checksum and end exactly where the
//! input ends, so random text that happens to start like a zlib stream is not "decoded".

use std::io::Read;

use base64::{engine::general_purpose, Engine as _};
use flate2::bufread::ZlibDecoder as Inflater;
use serde_json::Value;

use crate::checkers::checker_result::CheckResult;
use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, trace};

/// Largest output we inflate, in bytes. Anything longer is treated as a failure (a zip
/// bomb, or text far too long to be the answer) instead of being truncated.
const MAX_OUTPUT: u64 = 1 << 20;

/// The shortest zlib stream: 2 header bytes, an empty final DEFLATE block (2 bytes) and
/// the 4-byte Adler-32 checksum. `zlib.compress(b"")` is exactly this long.
const MIN_STREAM_LEN: usize = 8;

/// Most JSON string values the checker is run on.
const MAX_JSON_VALUES: usize = 32;

/// How deep into nested JSON objects and arrays we look for string values.
const MAX_JSON_DEPTH: usize = 3;

/// Shorter JSON string values (`"admin"`, `"true"`) are not worth checking.
const MIN_JSON_VALUE_CHARS: usize = 6;

/// The Zlib decoder, call:
/// `let zlib_decoder = Decoder::<ZlibDecoder>::new()` to create a new instance
/// And then call:
/// `result = zlib_decoder.crack(input)` to inflate a zlib stream
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::zlib_decoder::ZlibDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_zlib = Decoder::<ZlibDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// // Python: base64.b64encode(zlib.compress(b"The quick brown fox jumps over the lazy dog"))
/// let result = decode_zlib
///     .crack("eJwLyUhVKCzNTM5WSCrKL89TSMuvUMgqzS0oVsgvSy1SKAFK5yRWVSqk5KcDAFvcD9o=", &checker)
///     .unencrypted_text;
/// assert!(result.is_some());
/// assert_eq!(result.unwrap()[0], "The quick brown fox jumps over the lazy dog");
/// ```
pub struct ZlibDecoder;

impl Crack for Decoder<ZlibDecoder> {
    fn new() -> Decoder<ZlibDecoder> {
        Decoder {
            name: "Zlib",
            description: "Zlib (RFC 1950) wraps DEFLATE-compressed data in a two-byte header and an Adler-32 checksum. It is used in PDF and PNG streams, git objects and Flask session cookies. Ciphey reads the compressed bytes from Base64, hex or raw text and inflates them.",
            link: "https://datatracker.ietf.org/doc/html/rfc1950",
            tags: vec!["zlib", "deflate", "compression", "decoder"],
            popularity: 0.5,
            phantom: std::marker::PhantomData,
        }
    }

    /// Inflates the zlib stream in `text` and runs the checker on the output.
    /// The result has no text unless `text` holds one complete, valid zlib stream that
    /// inflates to text, or to another compressed stream.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Zlib with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());

        let Some(inflated) = inflate_text(text) else {
            trace!("Zlib: the input is not a zlib stream");
            return results;
        };

        // A git loose object is "<type> <size>\0<body>": the body is the content.
        let (body, git_type) = match split_git_object(&inflated) {
            Some((git_type, body)) => (body, Some(git_type)),
            None => (inflated.as_slice(), None),
        };

        let Some(plaintext) = as_text(body) else {
            if is_compressed(body) {
                // Compressed twice. Pass the inner stream on one character per byte
                // (Latin-1), which the next Zlib step reads back as raw bytes.
                debug!("Zlib output is another compressed stream");
                results.unencrypted_text =
                    Some(vec![body.iter().copied().map(char::from).collect()]);
                results.key = git_type.map(String::from);
            } else {
                debug!("Zlib output is binary, not text");
            }
            return results;
        };

        if !check_string_success(plaintext, text) {
            debug!("Zlib output is empty");
            return results;
        }
        results.key = git_type.map(String::from);

        let mut checker_result = checker.check(plaintext);
        if !checker_result.is_identified {
            // A Flask session is JSON, which the checkers don't recognise as a whole,
            // but a value inside it (a flag, a URL, an email address) they may.
            if let Some(hit) = check_json_values(plaintext, checker) {
                checker_result = hit;
            }
        }
        results.unencrypted_text = Some(vec![plaintext.to_string()]);
        results.update_checker(&checker_result);

        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Finds a zlib stream in `text` (cookie, Base64, hex or raw bytes) and inflates it.
///
/// Which view applies is decided by the first characters, before anything is allocated.
fn inflate_text(text: &str) -> Option<Vec<u8>> {
    let trimmed = text.trim();
    if let Some(cookie) = trimmed.strip_prefix('.') {
        // itsdangerous (Flask) and Django mark a compressed payload with a leading `.`
        let payload = cookie.split(['.', ':']).next()?;
        if !starts_like_zlib_base64(payload) {
            return None;
        }
        return inflate_bounded(&base64_bytes(payload)?);
    }
    if starts_like_zlib_base64(trimmed) {
        return inflate_bounded(&base64_bytes(trimmed)?);
    }
    if starts_like_zlib_hex(trimmed) {
        return inflate_bounded(&hex_bytes(trimmed)?);
    }
    // Raw bytes are not trimmed: the stream can end with bytes that look like whitespace.
    if text.starts_with('x') && looks_binary(text) {
        if let Some(stream) = latin1_bytes(text) {
            if let Some(inflated) = inflate_bounded(&stream) {
                return Some(inflated);
            }
        }
        // Hexadecimal and Binary return UTF-8 instead of Latin-1 when the bytes are UTF-8
        if !text.is_ascii() {
            return inflate_bounded(text.as_bytes());
        }
    }
    None
}

/// Whether `text` starts with the Base64 of a `78 01`, `78 5E`, `78 9C` or `78 DA` header.
fn starts_like_zlib_base64(text: &str) -> bool {
    matches!(text.as_bytes(), [b'e', b'A' | b'F' | b'J' | b'N', ..])
}

/// Whether `text` starts with the hex of a `78` header byte, after an optional `0x` / `\x`.
fn starts_like_zlib_hex(text: &str) -> bool {
    let digits = ["0x", "0X", "\\x", "\\X"]
        .iter()
        .find_map(|prefix| text.strip_prefix(prefix))
        .unwrap_or(text);
    digits.starts_with("78")
}

/// Whether `text` contains a character that ordinary text doesn't but compressed bytes
/// almost always do: a control character other than tab and line breaks, or non-ASCII.
/// This keeps plain text that starts with an `x` ("xylophone") away from the raw view.
fn looks_binary(text: &str) -> bool {
    text.chars()
        .any(|c| !c.is_ascii() || (c.is_ascii_control() && !matches!(c, '\t' | '\n' | '\r')))
}

/// One byte per character, if every character is at most U+00FF (Latin-1).
fn latin1_bytes(text: &str) -> Option<Vec<u8>> {
    text.chars().map(|c| u8::try_from(c).ok()).collect()
}

/// Decodes standard or URL-safe Base64, ignoring whitespace and up to two `=` of padding.
/// Uses the same engines as the Base64 decoder.
fn base64_bytes(text: &str) -> Option<Vec<u8>> {
    let mut compact = String::with_capacity(text.len());
    for c in text.chars().filter(|c| !c.is_ascii_whitespace()) {
        if !(c.is_ascii_alphanumeric() || matches!(c, '+' | '/' | '-' | '_' | '=')) {
            return None;
        }
        compact.push(c);
    }
    let unpadded = compact.trim_end_matches('=');
    if compact.len() - unpadded.len() > 2 || unpadded.contains('=') {
        return None;
    }
    let engine = if unpadded.contains(['-', '_']) {
        &general_purpose::URL_SAFE_NO_PAD
    } else {
        &general_purpose::STANDARD_NO_PAD
    };
    engine.decode(unpadded).ok()
}

/// Decodes hex, ignoring whitespace, `:` and `,` between bytes and `0x` / `\x` prefixes.
fn hex_bytes(text: &str) -> Option<Vec<u8>> {
    let mut nibbles = Vec::with_capacity(text.len());
    let mut rest = text.as_bytes();
    while let Some((&first, tail)) = rest.split_first() {
        if matches!(first, b'0' | b'\\') && matches!(tail.first(), Some(b'x' | b'X')) {
            rest = &tail[1..];
            continue;
        }
        match first {
            b'0'..=b'9' => nibbles.push(first - b'0'),
            b'a'..=b'f' => nibbles.push(first - b'a' + 10),
            b'A'..=b'F' => nibbles.push(first - b'A' + 10),
            b':' | b',' => {}
            _ if first.is_ascii_whitespace() => {}
            _ => return None,
        }
        rest = tail;
    }
    if nibbles.is_empty() || nibbles.len() % 2 != 0 {
        return None;
    }
    let (pairs, _) = nibbles.as_chunks::<2>();
    Some(pairs.iter().map(|&[high, low]| (high << 4) | low).collect())
}

/// The RFC 1950 header check (section 2.2): compression method 8 (DEFLATE), a window of
/// at most 32 KiB (CINFO <= 7), the two header bytes a multiple of 31 as a big-endian
/// number, and no preset dictionary (FDICT), which we wouldn't have.
fn has_zlib_header(stream: &[u8]) -> bool {
    let &[cmf, flg, ..] = stream else {
        return false;
    };
    stream.len() >= MIN_STREAM_LEN
        && cmf & 0x0F == 8
        && cmf >> 4 <= 7
        && u16::from_be_bytes([cmf, flg]) % 31 == 0
        && flg & 0x20 == 0
}

/// Inflates `stream` if it is exactly one complete zlib stream: a valid header, a DEFLATE
/// body that inflates without error to at most `MAX_OUTPUT` bytes, a matching Adler-32
/// checksum and nothing after it.
fn inflate_bounded(stream: &[u8]) -> Option<Vec<u8>> {
    if !has_zlib_header(stream) {
        return None;
    }
    let mut inflater = Inflater::new(stream);
    let mut output = Vec::new();
    // flate2 reports a bad checksum, a truncated stream or a preset dictionary as an
    // error. Reading one byte past the cap tells "exactly MAX_OUTPUT" from "more".
    inflater
        .by_ref()
        .take(MAX_OUTPUT + 1)
        .read_to_end(&mut output)
        .ok()?;
    if output.len() as u64 > MAX_OUTPUT {
        debug!("Zlib output is over {MAX_OUTPUT} bytes");
        return None;
    }
    // flate2 stops at the end of the stream without looking at what follows it, so
    // check that the stream used up the whole input.
    if inflater.total_in() != stream.len() as u64 {
        return None;
    }
    Some(output)
}

/// Splits a git loose object, `<type> <size>\0<body>`, into a name for its type and its
/// body. The size has to match the body.
fn split_git_object(object: &[u8]) -> Option<(&'static str, &[u8])> {
    // The longest header is "commit " and a 20 digit size
    let nul = object.iter().take(32).position(|&byte| byte == 0)?;
    let header = std::str::from_utf8(&object[..nul]).ok()?;
    let body = &object[nul + 1..];
    let (object_type, size) = header.split_once(' ')?;
    let name = match object_type {
        "blob" => "git blob",
        "tree" => "git tree",
        "commit" => "git commit",
        "tag" => "git tag",
        _ => return None,
    };
    // parse() would also accept a leading `+`
    if size.is_empty() || !size.bytes().all(|byte| byte.is_ascii_digit()) {
        return None;
    }
    (size.parse::<usize>().ok()? == body.len()).then_some((name, body))
}

/// `bytes` as text, if they are UTF-8 without control characters other than tab and line
/// breaks.
fn as_text(bytes: &[u8]) -> Option<&str> {
    let text = std::str::from_utf8(bytes).ok()?;
    text.chars()
        .all(|c| !c.is_control() || matches!(c, '\t' | '\n' | '\r'))
        .then_some(text)
}

/// Whether binary output is itself compressed: another zlib stream (starting with `78`,
/// like the raw view expects), or a gzip member (`1F 8B 08`).
fn is_compressed(bytes: &[u8]) -> bool {
    (bytes.first() == Some(&0x78) && has_zlib_header(bytes))
        || bytes.starts_with(&[0x1F, 0x8B, 0x08])
}

/// If `text` is a JSON object, runs the checker on its string values (up to
/// `MAX_JSON_VALUES` of them, `MAX_JSON_DEPTH` deep, each at least `MIN_JSON_VALUE_CHARS`
/// long) and returns the first one it identifies.
fn check_json_values(text: &str, checker: &CheckerTypes) -> Option<CheckResult> {
    if !text.trim_start().starts_with('{') {
        return None;
    }
    let json: Value = serde_json::from_str(text).ok()?;
    let mut values = Vec::new();
    collect_json_strings(&json, 0, &mut values);
    values
        .into_iter()
        .map(|value| checker.check(value))
        .find(|result| result.is_identified)
}

/// Collects the string values worth checking in `value`, which is `depth` levels deep.
fn collect_json_strings<'a>(value: &'a Value, depth: usize, strings: &mut Vec<&'a str>) {
    if strings.len() >= MAX_JSON_VALUES {
        return;
    }
    match value {
        Value::String(string) if string.chars().count() >= MIN_JSON_VALUE_CHARS => {
            strings.push(string)
        }
        Value::Array(items) if depth < MAX_JSON_DEPTH => {
            for item in items {
                collect_json_strings(item, depth + 1, strings);
            }
        }
        Value::Object(map) if depth < MAX_JSON_DEPTH => {
            for item in map.values() {
                collect_json_strings(item, depth + 1, strings);
            }
        }
        _ => {}
    }
}

#[cfg(test)]
mod tests {
    use super::{
        collect_json_strings, inflate_bounded, split_git_object, ZlibDecoder, MAX_JSON_VALUES,
        MAX_OUTPUT,
    };
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::{
            crack_results::CrackResult,
            hexadecimal_decoder::HexadecimalDecoder,
            interface::{Crack, Decoder},
            DECODER_MAP,
        },
        filtration_system::get_decoder_by_name,
    };
    use base64::{engine::general_purpose, Engine as _};
    use flate2::{write::ZlibEncoder, Compression};
    use serde_json::json;
    use std::io::Write;

    const FOX: &str = "The quick brown fox jumps over the lazy dog";
    const SPHINX: &str = "Sphinx of black quartz, judge my vow.";

    // Unless noted, vectors are Python 3 `zlib.compress`, shown as `base64.b64encode` or
    // `.hex()`, and inflate to the same text with CyberChef's Zlib Inflate.

    /// zlib.compress(FOX), header 78 9C
    const FOX_B64: &str = "eJwLyUhVKCzNTM5WSCrKL89TSMuvUMgqzS0oVsgvSy1SKAFK5yRWVSqk5KcDAFvcD9o=";
    /// zlib.compress(FOX).hex()
    const FOX_HEX: &str = "789c0bc94855282ccd4cce56482aca2fcf5348cbaf50c82acd2d2856c82f4b2d5228014ae72456552aa4e4a703005bdc0fda";

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn crack(text: &str) -> CrackResult {
        Decoder::<ZlibDecoder>::new().crack(text, &get_athena_checker())
    }

    /// What the decoder returns for `text`, if anything
    fn decoded(text: &str) -> Option<String> {
        crack(text).unencrypted_text.map(|texts| texts[0].clone())
    }

    fn compress(data: &[u8]) -> Vec<u8> {
        let mut encoder = ZlibEncoder::new(Vec::new(), Compression::default());
        encoder.write_all(data).unwrap();
        encoder.finish().unwrap()
    }

    fn b64(data: &[u8]) -> String {
        general_purpose::STANDARD.encode(data)
    }

    #[test]
    fn issue_example_decodes() {
        // The issue's example: zlib.compress(SPHINX, 9), header 78 DA. Athena doesn't
        // recognise this sentence, so only the output is checked.
        assert_eq!(
            decoded("eNoLLsjIzKtQyE9TSMpJTM5WKCxNLCqp0lHIKk1JT1XIrVQoyy/XAwABXg1f").as_deref(),
            Some(SPHINX)
        );
        assert_eq!(
            decoded("78da0b2ec8c8ccab50c84f5348ca494cce56282c4d2c2aa9d251c82a4d494f55c8ad5428cb2fd70300015e0d5f")
                .as_deref(),
            Some(SPHINX)
        );
    }

    #[test]
    fn cyberchef_deflate_output_decodes() {
        // CyberChef 11.5 Zlib Deflate (Dynamic Huffman) of SPHINX, header 78 9C
        assert_eq!(
            decoded("eJwFQIEVgBAQXeUP0GuZJjhSCIfnqKa/d1Qfygu+YBLZB02oj39DlPN2yB8mr10BAV4NXw==")
                .as_deref(),
            Some(SPHINX)
        );
    }

    #[test]
    fn fox_is_identified() {
        let result = crack(FOX_B64);
        assert_eq!(result.unencrypted_text.unwrap()[0], FOX);
        assert!(result.success, "Athena should accept the pangram");
        assert_eq!(result.decoder, "Zlib");
        assert!(result.key.is_none());
    }

    #[test]
    fn every_common_header_decodes() {
        // The same DEFLATE body behind the 78 01, 78 5E and 78 9C headers. The header
        // only records the compression level, so all three are valid streams.
        for input in [
            "eAELyUhVKCzNTM5WSCrKL89TSMuvUMgqzS0oVsgvSy1SKAFK5yRWVSqk5KcDAFvcD9o=",
            "eF4LyUhVKCzNTM5WSCrKL89TSMuvUMgqzS0oVsgvSy1SKAFK5yRWVSqk5KcDAFvcD9o=",
            FOX_B64,
        ] {
            assert_eq!(decoded(input).as_deref(), Some(FOX), "{input}");
        }
    }

    #[test]
    fn hex_decodes() {
        let result = crack(FOX_HEX);
        assert_eq!(result.unencrypted_text.unwrap()[0], FOX);
        assert!(result.success);
    }

    #[test]
    fn hex_with_separators_and_prefixes_decodes() {
        let pairs: Vec<&str> = (0..FOX_HEX.len())
            .step_by(2)
            .map(|i| &FOX_HEX[i..i + 2])
            .collect();
        for input in [
            FOX_HEX.to_uppercase(),
            pairs.join(" "),
            pairs.join(":"),
            format!("0x{FOX_HEX}"),
            pairs
                .iter()
                .map(|p| format!("0x{p}"))
                .collect::<Vec<_>>()
                .join(", "),
            pairs.iter().map(|p| format!("\\x{p}")).collect::<String>(),
            format!("  {}\n", pairs.join(" ")),
        ] {
            assert_eq!(decoded(&input).as_deref(), Some(FOX), "{input}");
        }
    }

    #[test]
    fn wrapped_and_unpadded_base64_decodes() {
        let wrapped: String = FOX_B64
            .as_bytes()
            .chunks(20)
            .map(|line| format!("{}\n", std::str::from_utf8(line).unwrap()))
            .collect();
        for input in [
            wrapped,
            FOX_B64.trim_end_matches('=').to_string(),
            format!("  {FOX_B64}\r\n"),
        ] {
            assert_eq!(decoded(&input).as_deref(), Some(FOX), "{input:?}");
        }
    }

    #[test]
    fn git_loose_object_decodes_to_its_body() {
        // .git/objects/84/102df4576c91e5176899893215babee5ad1215 from `git hash-object -w`
        // of FOX + "\n": "blob 44\0" and the content, compressed by git (78 01)
        let result = crack(
            "eAFLyslPUjAxYQjJSFUoLM1MzlZIKsovz1NIy69QyCrNLShWyC9LLVIoAUrnJFZVKqTkp3MBANaIEgs=",
        );
        assert_eq!(result.unencrypted_text.unwrap()[0], format!("{FOX}\n"));
        assert_eq!(result.key.as_deref(), Some("git blob"));
        assert!(result.success);
    }

    #[test]
    fn git_header_needs_a_known_type_and_the_right_size() {
        let commit = b"commit 12\0tree abc\n\nhi";
        assert_eq!(
            split_git_object(commit),
            Some(("git commit", &b"tree abc\n\nhi"[..]))
        );
        assert_eq!(
            split_git_object(b"tag 3\0abc"),
            Some(("git tag", &b"abc"[..]))
        );
        for object in [
            &b"blob 4\0abc"[..], // size is wrong
            b"blob +3\0abc",     // parse() would accept the sign
            b"blob \0abc",       // no size
            b"blobs 3\0abc",     // unknown type
            b"blob 3 abc",       // no NUL
            b"\0blob 3\0abc",    // empty header
        ] {
            assert_eq!(split_git_object(object), None, "{object:?}");
        }
        // Without a valid header, the NUL makes the output binary
        assert_eq!(decoded(&b64(&compress(b"blob 99\0hello world"))), None);
    }

    #[test]
    fn flask_session_cookie_with_a_flag_is_identified() {
        // A real Flask session cookie: itsdangerous 2.2.0 URLSafeTimedSerializer, salt
        // "cookie-session", HMAC-SHA1. The payload is "." + base64url(zlib(json)).
        let result = crack(".eJxNikEOgDAIBP_CuS_wM6SxSBorGGgPpunfxZuX3dnMThhOBhvkclWBBKaNfrMpMxUM3roNSnC0zOG_mhF-opN7VXHMRuiVJf6iHUl2e-5OZcF6ATTKJYw.ar7Csw.9oMCUUZEyBpz7prlNVxFW_RVWso");
        assert_eq!(
            result.unencrypted_text.unwrap()[0],
            r#"{"user":"admin","role":"admin","logged_in":true,"flag":"flag{flask_sessions_are_signed_not_encrypted}"}"#
        );
        // Athena rejects the JSON as a whole, but LemmeKnow recognises the flag inside it
        assert!(result.success);
        assert_eq!(result.checker_name, "LemmeKnow Checker");
    }

    #[test]
    fn json_without_a_recognised_value_is_a_candidate() {
        // The payload segment of a Flask cookie for {"user":"admin","logged_in":true}
        let result = crack("eJyrViotTi1SslJKTMnNzFPSUcrJT09PTYkHsq1KikpTawG-FguV");
        assert_eq!(
            result.unencrypted_text.unwrap()[0],
            r#"{"user":"admin","logged_in":true}"#
        );
        assert!(!result.success);
    }

    #[test]
    fn django_style_cookie_decodes() {
        // django.core.signing.dumps(compress=True) uses the same "." marker with ":" as the
        // separator: .<base64url(zlib(json))>:<timestamp>:<signature>
        let json = r#"{"message":"attack at dawn, attack at dawn, attack at dawn"}"#;
        let payload = general_purpose::URL_SAFE_NO_PAD.encode(compress(json.as_bytes()));
        let cookie = format!(".{payload}:1u5PcM:Z2o3cWdQb1dGb2V5aWxqbnJ0eF9fc2lnbmF0dXJl");
        assert_eq!(decoded(&cookie).as_deref(), Some(json));
        // and with nothing after the payload
        assert_eq!(decoded(&format!(".{payload}")).as_deref(), Some(json));
    }

    #[test]
    fn cookie_payload_needs_a_zlib_header() {
        for input in [".", ".eJ", ".hello.world", ".SGVsbG8.abc.def", "..eJ"] {
            assert_eq!(decoded(input), None, "{input}");
        }
    }

    #[test]
    fn nested_zlib_is_passed_on_as_raw_bytes() {
        // base64.b64encode(zlib.compress(zlib.compress(FOX)))
        let outer = crack(
            "eJwBMgDN/3icC8lIVSgszUzOVkgqyi/PU0jLr1DIKs0tKFbIL0stUigBSuckVlUqpOSnAwBb3A/aExYUhg==",
        );
        assert!(!outer.success);
        let inner = outer.unencrypted_text.unwrap().remove(0);
        // one Latin-1 character per byte of the inner stream
        let inner_bytes: Vec<u8> = inner.chars().map(|c| u8::try_from(c).unwrap()).collect();
        assert_eq!(inner_bytes, hex_to_bytes(FOX_HEX));

        let result = crack(&inner);
        assert_eq!(result.unencrypted_text.unwrap()[0], FOX);
        assert!(result.success);
    }

    #[test]
    fn hexadecimal_output_is_read_as_raw_bytes() {
        // The Hexadecimal decoder turns the stream into Latin-1 text, which Zlib reads back
        let hexadecimal = Decoder::<HexadecimalDecoder>::new();
        let latin1 = hexadecimal
            .crack(FOX_HEX, &get_athena_checker())
            .unencrypted_text
            .unwrap()
            .remove(0);
        assert!(latin1.starts_with('x'));
        assert_eq!(decoded(&latin1).as_deref(), Some(FOX));

        // zlib.compress(b"data fox", 1) happens to be valid UTF-8 ("˯" is U+02EF), so the
        // Hexadecimal decoder returns it as UTF-8 instead of Latin-1
        let utf8 = hexadecimal
            .crack("78014b492c495448cbaf00000d740308", &get_athena_checker())
            .unencrypted_text
            .unwrap()
            .remove(0);
        assert!(utf8.contains('\u{2EF}'));
        assert_eq!(decoded(&utf8).as_deref(), Some("data fox"));
    }

    #[test]
    fn plain_text_starting_with_x_is_not_read_as_raw_bytes() {
        for input in ["xylophones are fun", "x^2 + y^2 = z^2", "x", "xyz"] {
            assert_eq!(decoded(input), None, "{input}");
        }
    }

    #[test]
    fn bad_checksum_fails() {
        // FOX_B64 with the Adler-32 changed; CyberChef: "invalid adler-32 checksum"
        assert_eq!(
            decoded("eJwLyUhVKCzNTM5WSCrKL89TSMuvUMgqzS0oVsgvSy1SKAFK5yRWVSqk5KcDAFvcDyU="),
            None
        );
    }

    #[test]
    fn bytes_after_the_stream_fail() {
        // FOX_B64's stream followed by "GARBAGE", which flate2 alone would ignore
        assert_eq!(
            decoded("eJwLyUhVKCzNTM5WSCrKL89TSMuvUMgqzS0oVsgvSy1SKAFK5yRWVSqk5KcDAFvcD9pHQVJCQUdF"),
            None
        );
    }

    #[test]
    fn preset_dictionary_fails() {
        // Header 78 F9: FDICT is set, and the dictionary isn't part of the stream
        assert_eq!(
            decoded("ePkaSQRmC8lIVShEcBXS8isUskpzC4oV8stSixRKgNI5iVWVCin56QBb3A/a"),
            None
        );
    }

    #[test]
    fn raw_deflate_without_a_header_fails() {
        // base64.b64encode(zlib.compress(FOX)[2:-4]): the same DEFLATE data, no zlib wrapper
        assert_eq!(
            decoded("C8lIVSgszUzOVkgqyi/PU0jLr1DIKs0tKFbIL0stUigBSuckVlUqpOSnAwA="),
            None
        );
    }

    #[test]
    fn truncated_streams_fail() {
        let stream = hex_to_bytes(FOX_HEX);
        assert!(inflate_bounded(&stream).is_some());
        for length in 0..stream.len() {
            assert_eq!(inflate_bounded(&stream[..length]), None, "{length} bytes");
        }
        assert_eq!(decoded(&b64(&stream[..stream.len() - 1])), None);
        assert_eq!(decoded(&FOX_HEX[..FOX_HEX.len() - 8]), None);
    }

    #[test]
    fn lookalike_headers_fail() {
        for input in [
            "eJ",
            "eJw=",
            // Base64 that starts like a zlib header but isn't a stream
            "eJxhelloworldhelloworld",
            "eNough of this",
            // 78 78 is not a multiple of 31
            "787878787878787878787878",
            "78",
            // 78 9C, then not hex
            "789cxyz",
        ] {
            assert_eq!(decoded(input), None, "{input}");
        }
    }

    #[test]
    fn empty_stream_fails() {
        // zlib.compress(b"") inflates to nothing
        assert_eq!(
            inflate_bounded(&hex_to_bytes("789c030000000001")),
            Some(vec![])
        );
        assert_eq!(decoded("eJwDAAAAAAE="), None);
    }

    #[test]
    fn binary_output_fails() {
        // zlib.compress(bytes(range(256))) is a valid stream, but not of text
        let binary: Vec<u8> = (0..=255).collect();
        assert!(inflate_bounded(&compress(&binary)).is_some());
        assert_eq!(decoded(&b64(&compress(&binary))), None);
        // Latin-1 text isn't UTF-8: zlib.compress("café au lait".encode("latin-1"))
        assert_eq!(decoded("eJxLTkx7qZBYqpCTmFkCACAmBNQ="), None);
        // UTF-8, but with a control character
        assert_eq!(decoded(&b64(&compress(b"ring the bell \x07 twice"))), None);
        assert_eq!(
            decoded(&b64(&compress("café au lait".as_bytes()))).as_deref(),
            Some("café au lait")
        );
    }

    #[test]
    fn output_is_capped_at_one_mebibyte() {
        let cap = usize::try_from(MAX_OUTPUT).unwrap();
        let at_cap = inflate_bounded(&compress(&vec![b'a'; cap]));
        assert_eq!(at_cap.map(|output| output.len()), Some(cap));
        assert_eq!(inflate_bounded(&compress(&vec![b'a'; cap + 1])), None);
    }

    #[test]
    fn zip_bomb_fails() {
        // zlib.compress(b"A" * 64 MiB) is 65,239 bytes; inflating stops at the cap
        let mut encoder = ZlibEncoder::new(Vec::new(), Compression::default());
        let chunk = vec![b'A'; 1 << 16];
        for _ in 0..1024 {
            encoder.write_all(&chunk).unwrap();
        }
        let bomb = encoder.finish().unwrap();
        assert!(bomb.len() < 100_000, "{}", bomb.len());
        assert_eq!(inflate_bounded(&bomb), None);
        assert_eq!(decoded(&b64(&bomb)), None);
    }

    #[test]
    fn zlib_decode_empty_string() {
        assert!(crack("").unencrypted_text.is_none());
    }

    #[test]
    fn zlib_handles_panic_if_emoji() {
        assert!(crack("😀").unencrypted_text.is_none());
        assert!(crack("x😀").unencrypted_text.is_none());
    }

    #[test]
    fn zlib_decode_handles_panics() {
        for input in [
            "hello world",
            "hello my name is panicky mc panic face!",
            "TXIgUm9ib3QgaXMgZ3JlYXQ=",
            "0x",
            "\\x",
            ".",
            "   ",
            "\t\n",
        ] {
            assert!(crack(input).unencrypted_text.is_none(), "{input}");
        }
    }

    #[test]
    fn json_values_are_bounded() {
        let mut strings = Vec::new();
        let many = json!({ "values": vec!["long enough"; 100] });
        collect_json_strings(&many, 0, &mut strings);
        assert_eq!(strings.len(), MAX_JSON_VALUES);

        let mut strings = Vec::new();
        let nested = json!({
            "a": "depth one",
            "short": "admin",
            "b": { "c": "depth two", "d": { "e": "depth three", "f": { "g": "depth four" } } },
        });
        collect_json_strings(&nested, 0, &mut strings);
        strings.sort_unstable();
        assert_eq!(strings, ["depth one", "depth three", "depth two"]);
    }

    #[test]
    fn zlib_is_registered() {
        let decoders = get_decoder_by_name("Zlib");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Zlib");
        assert!(DECODER_MAP.contains_key("Zlib"));
    }

    fn hex_to_bytes(hex: &str) -> Vec<u8> {
        (0..hex.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
            .collect()
    }
}
